import { createHash, randomUUID } from "node:crypto"
import { ONLYFANS_COMPLETION_MAX_BYTES, type CompletionRequest, type CompletionResult, type CompletionSuccess, type UploadIntentRequest, type UploadIntentSafeResponse, type VerifyIntentRequest, type VerifyIntentSafeResponse } from "./types"
import { fail, ok } from "./response"
export type DownloadedObject = { body: Blob | ReadableStream<Uint8Array>; contentType: string | null }
export type CoreDeps = { admin:any; now?:()=>Date; signUpload?:(bucket:string,path:string)=>Promise<{token:string}>; download?:(bucket:string,path:string)=>Promise<DownloadedObject>; removeObject?:(bucket:string,path:string)=>Promise<void>; logger?:Pick<Console,"error"|"warn"|"info"|"log"> }
const bucket="operator-completion-evidence"
export function credentialUseBy(intentExpiresAt:Date, signingStartedAt:Date){ return new Date(Math.min(intentExpiresAt.getTime(), signingStartedAt.getTime()+10*60*1000)) }
export function monotonicCredentialCleanup(existing:string|null|undefined, signingStartedAt:Date){ const next=new Date(signingStartedAt.getTime()+125*60*1000).toISOString(); return existing && existing>next ? existing : next }
function td(bytes:Uint8Array){ return new TextDecoder().decode(bytes) }
function u16be(b:Uint8Array,o:number){ return (b[o]<<8)|b[o+1] }
function u16le(b:Uint8Array,o:number){ return b[o]|(b[o+1]<<8) }
function u24le(b:Uint8Array,o:number){ return b[o]|(b[o+1]<<8)|(b[o+2]<<16) }
function u32be(b:Uint8Array,o:number){ return ((b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3])>>>0 }
function u32le(b:Uint8Array,o:number){ return (b[o]|(b[o+1]<<8)|(b[o+2]<<16)|(b[o+3]<<24))>>>0 }
const crcTable=Array.from({length:256},(_,n)=>{ let c=n; for(let k=0;k<8;k++) c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1); return c>>>0 })
function crc32(bytes:Uint8Array){ let c=0xffffffff; for(const byte of bytes) c=crcTable[(c^byte)&0xff]^(c>>>8); return (c^0xffffffff)>>>0 }
export function detectImageMime(bytes:Uint8Array): string { if (bytes.length<4 || bytes.length>ONLYFANS_COMPLETION_MAX_BYTES) throw new Error("IMAGE_TOO_LARGE_OR_EMPTY"); if (bytes[0]===0xff&&bytes[1]===0xd8) return validateJpeg(bytes); const png=[137,80,78,71,13,10,26,10]; if (png.every((v,i)=>bytes[i]===v)) return validatePng(bytes); if (td(bytes.slice(0,4))==="RIFF" && td(bytes.slice(8,12))==="WEBP") return validateWebp(bytes); throw new Error("UNSUPPORTED_IMAGE") }
function validateJpeg(bytes:Uint8Array){ let i=2; let sawFrame=false; let sawScan=false; while(i<bytes.length){ if(bytes[i]!==0xff) throw new Error("INVALID_JPEG_MARKER"); while(i<bytes.length && bytes[i]===0xff) i++; if(i>=bytes.length) throw new Error("TRUNCATED_JPEG_MARKER"); const marker=bytes[i++]; if(marker===0xd9) { if(!sawFrame) throw new Error("JPEG_FRAME_REQUIRED"); if(!sawScan) throw new Error("JPEG_SCAN_REQUIRED"); if(i!==bytes.length) throw new Error("INVALID_JPEG_TRAILING"); return "image/jpeg" } if(marker===0x01 || (marker>=0xd0&&marker<=0xd7)) continue; if(i+2>bytes.length) throw new Error("TRUNCATED_JPEG_SEGMENT"); const len=u16be(bytes,i); if(len<2||i+len>bytes.length) throw new Error("INVALID_JPEG_SEGMENT"); const start=i+2; if((marker>=0xc0&&marker<=0xc3)||(marker>=0xc5&&marker<=0xc7)||(marker>=0xc9&&marker<=0xcb)||(marker>=0xcd&&marker<=0xcf)){ if(len<8) throw new Error("INVALID_JPEG_FRAME"); const height=u16be(bytes,start+1); const width=u16be(bytes,start+3); if(width<1||height<1) throw new Error("INVALID_JPEG_DIMENSIONS"); sawFrame=true } if(marker===0xda){ if(!sawFrame) throw new Error("JPEG_FRAME_REQUIRED"); if(len<6) throw new Error("INVALID_JPEG_SCAN"); sawScan=true; i+=len; while(i+1<bytes.length && !(bytes[i]===0xff && bytes[i+1]===0xd9)) i++; continue } i+=len } throw new Error("JPEG_EOI_REQUIRED") }
function validatePng(bytes:Uint8Array){ let i=8; let sawIHDR=false; let sawIDAT=false; while(i+12<=bytes.length){ const len=u32be(bytes,i); const type=td(bytes.slice(i+4,i+8)); if(i+12+len>bytes.length) throw new Error("TRUNCATED_PNG_CHUNK"); const crcExpected=u32be(bytes,i+8+len); const crcActual=crc32(bytes.slice(i+4,i+8+len)); if(crcExpected!==crcActual) throw new Error("PNG_BAD_CRC"); if(!sawIHDR && (type!=="IHDR"||len!==13)) throw new Error("PNG_IHDR_REQUIRED"); if(type==="IHDR"){ if(sawIHDR) throw new Error("PNG_DUPLICATE_IHDR"); const width=u32be(bytes,i+8), height=u32be(bytes,i+12); if(width<1||height<1) throw new Error("PNG_DIMENSIONS_REQUIRED"); sawIHDR=true } else if(!sawIHDR) throw new Error("PNG_IHDR_REQUIRED"); if(type==="IDAT") sawIDAT=true; i += 12 + len; if(type==="IEND") { if(len!==0) throw new Error("PNG_IEND_LENGTH"); if(!sawIDAT) throw new Error("PNG_IDAT_REQUIRED"); if(i!==bytes.length) throw new Error("PNG_TRAILING_BYTES"); return "image/png" } } throw new Error("PNG_IEND_REQUIRED") }
function validateWebp(bytes:Uint8Array){
  if(bytes.length<20) throw new Error("TRUNCATED_WEBP"); const declared=u32le(bytes,4)+8; if(declared!==bytes.length) throw new Error("WEBP_LENGTH_MISMATCH");
  let i=12; let sawPayload=false; const first=td(bytes.slice(i,i+4)); if(!["VP8 ","VP8L","VP8X"].includes(first)) throw new Error("WEBP_IMAGE_CHUNK_REQUIRED");
  function vp8lPayload(chunkOffset:number,len:number){ if(len<=5) throw new Error("WEBP_IMAGE_PAYLOAD_REQUIRED"); if(bytes[chunkOffset]!==0x2f) throw new Error("INVALID_WEBP_VP8L"); const packed=bytes[chunkOffset+1] | (bytes[chunkOffset+2]<<8) | (bytes[chunkOffset+3]<<16) | (bytes[chunkOffset+4]<<24); const width=1+(packed&0x3fff); const height=1+((packed>>>14)&0x3fff); if(width<1||height<1) throw new Error("WEBP_DIMENSIONS_REQUIRED"); return true }
  function vp8Payload(chunkOffset:number,len:number){ if(len<=10) throw new Error("WEBP_IMAGE_PAYLOAD_REQUIRED"); if(bytes[chunkOffset+3]!==0x9d || bytes[chunkOffset+4]!==0x01 || bytes[chunkOffset+5]!==0x2a) throw new Error("INVALID_WEBP_VP8"); const width=u16le(bytes,chunkOffset+6)&0x3fff; const height=u16le(bytes,chunkOffset+8)&0x3fff; if(width<1||height<1) throw new Error("WEBP_DIMENSIONS_REQUIRED"); return true }
  function anmfPayload(chunkOffset:number,len:number){ if(len<24) throw new Error("INVALID_WEBP_ANMF"); const width=u24le(bytes,chunkOffset+6)+1; const height=u24le(bytes,chunkOffset+9)+1; if(width<1||height<1) throw new Error("WEBP_DIMENSIONS_REQUIRED"); let j=chunkOffset+24; const end=chunkOffset+len; let nested=false; while(j+8<=end){ const type=td(bytes.slice(j,j+4)); const clen=u32le(bytes,j+4); if(clen<=0||j+8+clen>end) throw new Error("TRUNCATED_WEBP_CHUNK"); if(type==="VP8L") nested=vp8lPayload(j+8,clen); else if(type==="VP8 ") nested=vp8Payload(j+8,clen); j+=8+clen+(clen%2) } if(j!==end||!nested) throw new Error("WEBP_IMAGE_PAYLOAD_REQUIRED"); return true }
  while(i+8<=bytes.length){ const type=td(bytes.slice(i,i+4)); const len=u32le(bytes,i+4); if(len<=0) throw new Error("WEBP_EMPTY_CHUNK"); if(i+8+len>bytes.length) throw new Error("TRUNCATED_WEBP_CHUNK"); const chunk=i+8; if(type==="VP8X"){ if(i!==12 || len<10) throw new Error("INVALID_WEBP_VP8X"); const width=u24le(bytes,i+12)+1; const height=u24le(bytes,i+15)+1; if(width<1||height<1) throw new Error("WEBP_DIMENSIONS_REQUIRED") } else if(type==="VP8L"){ sawPayload=vp8lPayload(chunk,len) } else if(type==="VP8 "){ sawPayload=vp8Payload(chunk,len) } else if(type==="ANMF"){ sawPayload=anmfPayload(chunk,len) } i += 8 + len + (len%2); if(i>bytes.length) throw new Error("TRUNCATED_WEBP_CHUNK") }
  if(i!==bytes.length) throw new Error("WEBP_TRAILING_BYTES"); if(!sawPayload) throw new Error("WEBP_IMAGE_PAYLOAD_REQUIRED"); return "image/webp" }
async function readAndHashObject(obj:DownloadedObject){ const stream = obj.body instanceof Blob ? obj.body.stream() : obj.body; const reader=stream.getReader(); const hash=createHash("sha256"); let total=0; const chunks:Uint8Array[]=[]; while(true){ const {done,value}=await reader.read(); if(done) break; const chunk=value instanceof Uint8Array ? value : new Uint8Array(value); total+=chunk.byteLength; if(total>ONLYFANS_COMPLETION_MAX_BYTES){ await reader.cancel().catch(()=>{}); throw new Error("IMAGE_TOO_LARGE") } hash.update(chunk); chunks.push(chunk) } const bytes=new Uint8Array(total); let off=0; for(const c of chunks){ bytes.set(c,off); off+=c.byteLength } return { bytes, size:total, sha256:hash.digest("hex"), mime:detectImageMime(bytes), contentType:String(obj.contentType||"").toLowerCase().split(";")[0].trim() } }
function requireRpcData<T>(response:any, fields:string[]): T { if(response?.error) throw response.error; const data=response?.data; if(!data || typeof data!=="object") throw new Error("MALFORMED_RPC_RESPONSE"); for(const f of fields) if(!(f in data)) throw new Error("MALFORMED_RPC_RESPONSE"); return data as T }

async function cleanupFailedEvidence(deps:CoreDeps){ try{ const rows=requireRpcData<any>(await deps.admin.rpc("creator_publishing_cleanup_failed_completion_evidence",{p_limit:25}),[]); const list=Array.isArray(rows)?rows:[]; for(const row of list){ if(row?.server_bucket && row?.server_path && deps.removeObject){ await deps.removeObject(row.server_bucket,row.server_path).catch(()=>{}) } } }catch{} }
async function terminalizeFailedEvidence(deps:CoreDeps, actorId:string, platformJobId:string, uploadIntentId:string, failureCode:string){ try{ await deps.admin.rpc("creator_publishing_fail_completion_evidence_intent",{ p_actor_id:actorId, p_platform_job_id:platformJobId, p_upload_intent_id:uploadIntentId, p_failure_code:failureCode }).then((r:any)=>requireRpcData(r,["ok"])) }catch{} }
function isConfirmedMissingStorageError(e:any){ const code=String(e?.code||e?.name||"").toUpperCase().replace(/[^A-Z0-9]+/g,"_"); const status=Number(e?.statusCode??e?.status??0); return status===404 || ["NOSUCHKEY","NO_SUCH_KEY","NOSUCHOBJECT","NO_SUCH_OBJECT","NOTFOUND","NOT_FOUND","404"].includes(code) }
function failureCodeFor(e:any){ const m=String(e?.message||e||""); if(m.includes("IMAGE_TOO_LARGE")) return "oversized_image"; if(m.includes("MIME")||m.includes("size mismatch")) return "mime_or_size_mismatch"; return "malformed_image" }
function codeFor(e:any){ const m=String(e?.message||e||""); if(m.includes("IDEMPOTENCY")) return "idempotency_conflict"; if(m.includes("CURRENT_CLAIM_REQUIRED")) return "current_claim_required"; if(m.includes("EVIDENCE_NOT_VERIFIED")||m.includes("EVIDENCE_NOT_PENDING")||m.includes("EVIDENCE_VERIFY_FAILED")) return "evidence_not_verified"; if(m.includes("EVIDENCE_REPLACEMENT_LIMIT_REACHED")) return "evidence_replacement_limit_reached"; if(m.includes("EVIDENCE_REPLACEMENT_TARGET_INVALID")) return "completion_rejected"; if(m.includes("fetch")||m.includes("network")||m.includes("download")||m.includes("sign")||m.includes("storage")||m.includes("temporarily")) return "service_unavailable"; return "completion_rejected" }
export async function createCompletionEvidenceUploadIntentCore(input:UploadIntentRequest, actorId:string, deps:CoreDeps): Promise<CompletionResult<UploadIntentSafeResponse>> { try { await cleanupFailedEvidence(deps); const now=deps.now?.()??new Date(); const path=`operator-completion-evidence/${input.platformJobId}/${actorId}/${randomUUID()}`; const rpc= await deps.admin.rpc("creator_publishing_reserve_completion_evidence_intent", { p_actor_id:actorId, p_platform_job_id:input.platformJobId, p_operation:input.operation, p_request_key:input.requestKey, p_expected_mime_type:input.mimeType, p_expected_size_bytes:input.sizeBytes, p_replaces_upload_intent_id:input.replacesUploadIntentId??null, p_server_bucket:bucket, p_server_path:path, p_intent_expires_at:null, p_credential_signing_started_at:now.toISOString() }); const row=requireRpcData<any>(rpc,["upload_intent_id","server_path","status","intent_expires_at"]); if(row.status === "expired" || new Date(row.intent_expires_at).getTime() <= now.getTime()) return ok({ uploadIntentId:row.upload_intent_id, bucket, path:row.server_path, token:null, intentExpiresAt:row.intent_expires_at, credentialUseBy:null, status:"expired" as any }); if (row.status === "verified") return ok({ uploadIntentId:row.upload_intent_id, bucket, path:row.server_path, token:null, intentExpiresAt:row.intent_expires_at, credentialUseBy:null, status:"verified" }); if(row.status!=="pending") return fail("completion_rejected","Upload intent is no longer pending."); const signed= await deps.signUpload?.(bucket,row.server_path); if (!signed?.token) return fail("service_unavailable","Upload credential could not be created.",true); const useBy=credentialUseBy(new Date(row.intent_expires_at), now); return ok({ uploadIntentId:row.upload_intent_id, bucket, path:row.server_path, token:signed.token, intentExpiresAt:row.intent_expires_at, credentialUseBy:useBy.toISOString(), status:"pending" }) } catch(e:any){ const c=codeFor(e); return fail(c,c==="service_unavailable"?"Upload service is temporarily unavailable.":"Upload intent rejected.",c==="service_unavailable") } }
export async function verifyCompletionEvidenceIntentCore(input:VerifyIntentRequest, actorId:string, deps:CoreDeps): Promise<CompletionResult<VerifyIntentSafeResponse>> { let reserved:any; try { await cleanupFailedEvidence(deps); reserved=requireRpcData<any>(await deps.admin.rpc("creator_publishing_prepare_completion_evidence_verification", { p_actor_id:actorId, p_platform_job_id:input.platformJobId, p_upload_intent_id:input.uploadIntentId }),["server_bucket","server_path","expected_mime_type","expected_size_bytes"]); let dl:DownloadedObject|undefined; try{ dl= await deps.download?.(reserved.server_bucket,reserved.server_path) }catch(e){ if(isConfirmedMissingStorageError(e)){ await terminalizeFailedEvidence(deps,actorId,input.platformJobId,input.uploadIntentId,"download_missing"); return fail("completion_rejected","Evidence verification rejected.") } return fail("service_unavailable","Evidence service is temporarily unavailable.",true) } if (!dl){ await terminalizeFailedEvidence(deps,actorId,input.platformJobId,input.uploadIntentId,"download_missing"); return fail("completion_rejected","Evidence verification rejected.") } let checked:any; try{ checked=await readAndHashObject(dl) }catch(e){ await terminalizeFailedEvidence(deps,actorId,input.platformJobId,input.uploadIntentId,failureCodeFor(e)); return fail("completion_rejected","Evidence verification rejected.") } if (checked.mime !== reserved.expected_mime_type || checked.mime !== checked.contentType || checked.size !== reserved.expected_size_bytes){ await terminalizeFailedEvidence(deps,actorId,input.platformJobId,input.uploadIntentId,"mime_or_size_mismatch"); return fail("completion_rejected","Evidence MIME or size mismatch.") } await deps.admin.rpc("creator_publishing_verify_completion_evidence_intent", { p_actor_id:actorId, p_platform_job_id:input.platformJobId, p_upload_intent_id:input.uploadIntentId, p_normalized_mime_type:checked.mime, p_actual_size_bytes:checked.size, p_verified_sha256:checked.sha256 }).then((r:any)=>requireRpcData(r,["ok"])); return ok({ uploadIntentId:input.uploadIntentId, status:"verified", normalizedMimeType:checked.mime, actualSizeBytes:checked.size }) } catch(e:any){ const c=codeFor(e); return fail(c,c==="service_unavailable"?"Evidence service is temporarily unavailable.":"Evidence verification rejected.",c==="service_unavailable") } }
export async function completeOnlyFansManualPostCore(input:CompletionRequest, actorId:string, deps:CoreDeps): Promise<CompletionResult<CompletionSuccess>> { try { await cleanupFailedEvidence(deps); const probe=requireRpcData<any>(await deps.admin.rpc("creator_publishing_complete_onlyfans_manual_post", { p_mode:"replay_probe", p_actor_id:actorId, p_platform_job_id:input.platformJobId, p_idempotency_key:input.idempotencyKey, p_evidence_intent_id:input.uploadIntentId, p_final_post_url:input.finalPostUrl??null, p_final_post_url_skip_reason:input.noUrlReason??null }),["replayed"]); if (probe.replayed) return ok({ platformJobId:input.platformJobId, status:"confirmed_posted_manual", finalPostUrl:probe.final_post_url??null, finalPostUrlSkipReason:probe.final_post_url_skip_reason??null, idempotent:true }); const prepared=requireRpcData<any>(await deps.admin.rpc("creator_publishing_prepare_manual_completion_fresh_verification", { p_actor_id:actorId, p_platform_job_id:input.platformJobId, p_evidence_intent_id:input.uploadIntentId }),["server_bucket","server_path","claim_token"]); const dl=await deps.download?.(prepared.server_bucket,prepared.server_path); if (!dl) return fail("service_unavailable","Evidence recheck could not be downloaded.",true); const checked=await readAndHashObject(dl); const done=requireRpcData<any>(await deps.admin.rpc("creator_publishing_complete_onlyfans_manual_post", { p_mode:"complete", p_actor_id:actorId, p_platform_job_id:input.platformJobId, p_idempotency_key:input.idempotencyKey, p_evidence_intent_id:input.uploadIntentId, p_final_post_url:input.finalPostUrl??null, p_final_post_url_skip_reason:input.noUrlReason??null, p_verified_sha256:checked.sha256, p_actual_size_bytes:checked.size, p_normalized_mime_type:checked.mime, p_claim_token:prepared.claim_token }),["platform_job_id","status","idempotent"]); if(done.platform_job_id!==input.platformJobId || done.status!=="confirmed_posted_manual") throw new Error("MALFORMED_RPC_RESPONSE"); return ok({ platformJobId:done.platform_job_id, status:"confirmed_posted_manual", finalPostUrl:done.final_post_url??null, finalPostUrlSkipReason:done.final_post_url_skip_reason??null, idempotent:Boolean(done.idempotent) }) } catch(e:any){ const c=codeFor(e); return fail(c,c==="service_unavailable"?"Completion service is temporarily unavailable.":"Completion rejected.",c==="service_unavailable") } }
export const __task18Test = { readAndHashObject, validateJpeg, validatePng, validateWebp, requireRpcData, cleanupFailedEvidence, terminalizeFailedEvidence, failureCodeFor, isConfirmedMissingStorageError }
