export type GeneratedMediaKind = "image" | "video"
export type GeneratedMediaLike = { status?: unknown; image_url?: unknown; mode?: unknown; job_type?: unknown; metadata?: unknown; r2_bucket?: unknown; r2_key?: unknown }
export function generatedMediaMetadata(row: GeneratedMediaLike): Record<string, unknown> { return row.metadata && typeof row.metadata === "object" && !Array.isArray(row.metadata) ? row.metadata as Record<string, unknown> : {} }
export function isCompletedGeneratedMedia(row: GeneratedMediaLike): boolean { return String(row.status || "").trim().toLowerCase() === "completed" }
export function isExplicitlyIneligibleGeneratedMediaMetadata(metadata: Record<string, unknown>): boolean { return metadata.placeholder === true || metadata.is_placeholder === true || metadata.test === true || metadata.is_test === true || metadata.unsafe === true || metadata.safety === "unsafe" }
export function resolveGeneratedMediaPreviewUrl(row: GeneratedMediaLike): string | null { const metadata = generatedMediaMetadata(row); if (isExplicitlyIneligibleGeneratedMediaMetadata(metadata)) return null; for (const value of [row.image_url, metadata.video_url, metadata.output_url]) { if (typeof value === "string" && value.trim().length > 0) return value.trim() } return null }
export function resolveGeneratedMediaKind(row: GeneratedMediaLike, url = resolveGeneratedMediaPreviewUrl(row) || ""): GeneratedMediaKind { const metadata = generatedMediaMetadata(row); const normalizedUrl = url.toLowerCase().split("?")[0].split("#")[0]; const normalizedMode = String(metadata.mode || row.mode || row.job_type || "").toLowerCase(); return normalizedUrl.endsWith(".mp4") || normalizedUrl.endsWith(".webm") || normalizedUrl.endsWith(".mov") || normalizedUrl.endsWith(".m4v") || normalizedMode.includes("video") ? "video" : "image" }
export function hasTrustedGeneratedMediaR2(row: GeneratedMediaLike): boolean { return typeof row.r2_bucket === "string" && row.r2_bucket.trim().length > 0 && typeof row.r2_key === "string" && row.r2_key.trim().length > 0 }
export function isEligibleGeneratedMediaRecord(row: GeneratedMediaLike): boolean { return isCompletedGeneratedMedia(row) && !isExplicitlyIneligibleGeneratedMediaMetadata(generatedMediaMetadata(row)) && hasTrustedGeneratedMediaR2(row) && Boolean(resolveGeneratedMediaPreviewUrl(row)) }
