import "server-only"
import { getSupabaseAdmin } from "../../supabaseAdmin"
import { runFanvuePublicationWorker, type ClaimedFanvueJob, type FanvueWorkerStore } from "./workerCore"
import type { PreparedFanvueExecutionEnvelope } from "./executor"
import type { FanvueProviderPostInput } from "../../autopost/fanvueProviderExecutorCore"
import { isFanvueGenerationEligible, nonblank, validateFanvueExecutionFacts } from "./serviceCore"

type Admin = ReturnType<typeof getSupabaseAdmin>
type MediaRow = { id:string; content_package_id:string; storage_key:string; mime_type:string; sha256:string; source:string; ai_generation_metadata:Record<string,unknown> }
export type FanvueTechnicalDependencies = {
  provider: Pick<FanvueProviderPostInput,"apiBaseUrl"|"apiVersion"|"fanvueFetch"|"fetchIdentity"|"signedPartUploader"|"decryptAccessToken"|"refreshAccessToken"|"reloadAccountAfterRefresh"|"now"|"waitForMediaReady">
  loadMediaBytes(asset: MediaRow): Promise<BodyInit>
}
async function loadEnvelope(admin:Admin,job:any,profileId:string,deps:FanvueTechnicalDependencies):Promise<PreparedFanvueExecutionEnvelope>{
 const [{data:destination},{data:oauth},{data:p},{data:media},{data:verification},{data:consent},{data:performers},{data:sourceCurrent}]=await Promise.all([
  admin.from("creator_platform_accounts").select("*").eq("id",job.platform_account_id).single(),admin.from("autopost_accounts").select("*").eq("id",job.oauth_account_id).single(),admin.from("creator_publishing_content_packages").select("*").eq("id",job.content_package_id).single(),admin.from("creator_publishing_media_assets").select("*").eq("content_package_id",job.content_package_id).order("id"),admin.from("creator_publishing_creator_verifications").select("status").eq("creator_id",job.creator_id).single(),admin.from("creator_publishing_ai_twin_consents").select("status,revoked_at,attestation_version,attestation_text_sha256").eq("creator_id",job.creator_id).single(),admin.from("creator_publishing_co_performer_records").select("platform_release_confirmed,release_document_reference").eq("content_package_id",job.content_package_id),admin.rpc("creator_publishing_job_source_is_current",{p_job_id:job.id})])
 const {data:reviews}=await admin.from("creator_publishing_compliance_reviews").select("*").eq("content_package_id",job.content_package_id).order("created_at",{ascending:false})
 const evidence=(reviews??[]).find((r:any)=>p?.compliance_status==="passed"?r.review_source==="automated"&&r.outcome==="pass"&&r.compliance_policy_version===p.compliance_policy_version:r.review_source==="human"&&r.outcome==="escalate"&&nonblank(r.escalated_approval_reason)&&r.compliance_policy_version===p?.compliance_policy_version)
 const laterBlockingReview=Boolean(evidence&&(reviews??[]).some((r:any)=>["block","manual_review"].includes(r.outcome)&&(r.created_at>evidence.created_at||(r.created_at===evidence.created_at&&r.id>evidence.id))))
 const error=validateFanvueExecutionFacts({job,destination,oauth,contentPackage:p,verification,consent,performers,sourceCurrent,complianceEvidence:evidence,laterBlockingReview});if(error)throw new Error(error)
 const assets=(media??[]) as MediaRow[];let approvedMedia:any=null
 if(assets.length){if(assets.length!==1)throw new Error("FANVUE_CPQ_MEDIA_INVALID");const asset=assets[0];const generationId=asset.ai_generation_metadata?.generation_id;if(asset.source!=="ai_pipeline"||!nonblank(generationId))throw new Error("FANVUE_CPQ_MEDIA_PROVENANCE_INVALID");const{data:g,error:gError}=await admin.from("generations").select("id,user_id,status,image_url,mode,job_type,r2_bucket,r2_key,metadata").eq("id",generationId).in("user_id",[job.creator_id,profileId]).maybeSingle();if(gError)throw new Error("FANVUE_CPQ_PREPARATION_TRANSIENT");if(!g||!isFanvueGenerationEligible(g,job.creator_id,profileId))throw new Error("FANVUE_CPQ_MEDIA_PROVENANCE_INVALID");const type=asset.mime_type.startsWith("video/")?"video":asset.mime_type.startsWith("image/")?"image":null;if(!type)throw new Error("FANVUE_CPQ_MEDIA_INVALID");approvedMedia={filename:asset.storage_key.split("/").pop()!,mediaType:type,contentType:asset.mime_type,bytes:await deps.loadMediaBytes(asset)}}
 const publicationType=approvedMedia?approvedMedia.mediaType:"text";if(job.publication_type!==publicationType)throw new Error("FANVUE_CPQ_PUBLICATION_TYPE_INVALID")
 return{creatorId:job.creator_id,destination:{id:destination.id,creator_id:destination.creator_id,platform:"fanvue",oauth_account_id:destination.oauth_account_id},oauthAccount:{...oauth,platform:"fanvue"},approvedContent:{platform:"fanvue",content_type:approvedMedia?"media":"text",text:p.caption_body,media:approvedMedia},provider:deps.provider}
}
const reconnectPreparationCodes=new Set(["FANVUE_CPQ_OAUTH_DISCONNECTED"])
const semanticPreparationCodes=new Set(["FANVUE_CPQ_REQUIREMENTS_INVALID","FANVUE_CPQ_DESTINATION_INVALID","FANVUE_CPQ_OAUTH_INVALID","FANVUE_CPQ_PACKAGE_NOT_APPROVED","FANVUE_CPQ_COMPLIANCE_INVALID","FANVUE_CPQ_CREATOR_NOT_VERIFIED","FANVUE_CPQ_CONSENT_INVALID","FANVUE_CPQ_RELEASE_INVALID","FANVUE_CPQ_SOURCE_STALE","FANVUE_CPQ_MEDIA_INVALID","FANVUE_CPQ_MEDIA_PROVENANCE_INVALID","FANVUE_CPQ_PUBLICATION_TYPE_INVALID"])
export function createFanvueCpqStore(admin:Admin,deps:FanvueTechnicalDependencies):FanvueWorkerStore{return{
 async claimDue(limit,leaseMinutes){const{data,error}=await admin.rpc("creator_publishing_claim_scheduled_fanvue_jobs",{p_limit:limit,p_lease_minutes:leaseMinutes});if(error)throw new Error("FANVUE_CPQ_CLAIM_FAILED");return(data??[]).map((c:any)=>({jobId:c.job_id,attemptId:c.attempt_id,leaseToken:c.lease_token,attemptOrdinal:c.attempt_ordinal}))},
 async prepareClaim(c){try{const{data:j,error:jError}=await admin.from("creator_publishing_platform_jobs").select("*").eq("id",c.jobId).eq("job_state","publishing_direct").eq("lease_token",c.leaseToken).single();if(jError||!j)throw new Error("FANVUE_CPQ_PREPARATION_TRANSIENT");const{data:p,error:pError}=await admin.from("profiles").select("id").eq("user_id",j.creator_id).single();if(pError)throw new Error("FANVUE_CPQ_PREPARATION_TRANSIENT");if(!p)return{ok:false,outcome:"permanent",safeCode:"FANVUE_CPQ_ENTITLEMENT_REQUIRED"};const{data:s,error:sError}=await admin.from("user_subscriptions").select("id").eq("user_id",p.id).in("status",["active","trialing"]).limit(1);if(sError)throw new Error("FANVUE_CPQ_PREPARATION_TRANSIENT");if(!s?.length)return{ok:false,outcome:"permanent",safeCode:"FANVUE_CPQ_ENTITLEMENT_REQUIRED"};return{ok:true,envelope:await loadEnvelope(admin,j,p.id,deps)}}catch(error){const code=error instanceof Error?error.message:"FANVUE_CPQ_PREPARATION_TRANSIENT";if(reconnectPreparationCodes.has(code))return{ok:false,outcome:"reconnect_required",safeCode:code};if(semanticPreparationCodes.has(code))return{ok:false,outcome:"permanent",safeCode:code};return{ok:false,outcome:"retryable_pre_create",safeCode:"FANVUE_CPQ_PREPARATION_TRANSIENT"}}},
 async markCreateDispatched(id,lease){const{data,error}=await admin.rpc("creator_publishing_mark_fanvue_create_dispatched",{p_attempt_id:id,p_lease_token:lease});return!error&&data===true},async finish(i){const r=i.result;const{data,error}=await admin.rpc("creator_publishing_finish_fanvue_attempt",{p_attempt_id:i.attemptId,p_lease_token:i.leaseToken,p_outcome:i.outcome,p_upload:r.upload_attempted,p_refresh:r.token_refresh_attempted,p_safe_code:r.safe_code,p_status:r.create_status_class,p_proof:r.provider_post_uuid,p_next:i.nextAttemptAt});return!error&&data===true}}}
export function runDormantFanvueCpqWorker(input:{enabled:boolean;batchSize:number;dependencies:FanvueTechnicalDependencies}){return runFanvuePublicationWorker({enabled:input.enabled,batchSize:input.batchSize,store:createFanvueCpqStore(getSupabaseAdmin(),input.dependencies)})}
