import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const oauth = readFileSync('lib/autopost/fanvueOAuth.ts', 'utf8')
const availability = readFileSync('lib/autopost/platformAvailability.ts', 'utf8')
const callback = readFileSync('app/api/autopost/connect/fanvue/callback/route.ts', 'utf8')
const tokenExchangeHelper = readFileSync('lib/autopost/fanvueOAuthTokenExchange.ts', 'utf8')
const clientAuthHelper = readFileSync('lib/autopost/fanvueOAuthClientAuth.ts', 'utf8')
const statusRoute = readFileSync('app/api/autopost/platforms/me/route.ts', 'utf8')
const envExample = readFileSync('.env.example', 'utf8')
const refreshScopeNote = readFileSync('backend/autopost/docs/fanvue-oauth-refresh-scopes-FV-40R.md', 'utf8')

assert.match(oauth, /FANVUE_CONNECT_ENABLED"\) === "true"/, 'Fanvue connect must default off unless exactly true')
assert.match(oauth, /provider: "fanvue"/, 'Fanvue OAuth state must bind provider')
assert.match(oauth, /code_challenge_method", "S256"/, 'Fanvue OAuth must use PKCE S256')
assert.match(oauth, /FANVUE_OAUTH_SCOPES_UNAPPROVED/, 'Fanvue scopes must reject unapproved scopes')

const approvedScopesMatch = oauth.match(/export const FANVUE_APPROVED_SCOPES = \[([\s\S]*?)\] as const/)
assert.ok(approvedScopesMatch, 'Fanvue approved scopes must be declared as a const allowlist')
const approvedScopes = Array.from(approvedScopesMatch[1].matchAll(/"([^"]+)"/g), (match) => match[1])
assert.ok(approvedScopes.includes('openid'), 'Fanvue approved/default scopes must include openid')
assert.ok(approvedScopes.includes('offline_access'), 'Fanvue approved/default scopes must include offline_access for refresh-token issuance')
assert.ok(approvedScopes.includes('offline'), 'Fanvue approved/default scopes must include offline')
assert.ok(approvedScopes.includes('read:media'), 'Fanvue approved/default scopes must preserve read:media')
assert.ok(approvedScopes.includes('write:media'), 'Fanvue approved/default scopes must preserve write:media')
assert.ok(approvedScopes.includes('write:creator'), 'Fanvue approved scopes may include optional write:creator for explicit internal requests')
const defaultRequestedScopesMatch = oauth.match(/export const FANVUE_DEFAULT_REQUESTED_SCOPES = \[([\s\S]*?)\] as const/)
assert.ok(defaultRequestedScopesMatch, 'Fanvue default requested scopes must be declared separately from the approved/requestable allowlist')
const defaultRequestedScopes = Array.from(defaultRequestedScopesMatch[1].matchAll(/"([^"]+)"/g), (match) => match[1])
assert.ok(defaultRequestedScopes.includes('openid'), 'Fanvue default requested scopes must include openid')
assert.ok(defaultRequestedScopes.includes('offline_access'), 'Fanvue default requested scopes must include offline_access for refresh-token issuance')
assert.ok(defaultRequestedScopes.includes('offline'), 'Fanvue default requested scopes must include offline')
assert.ok(defaultRequestedScopes.includes('read:self'), 'Fanvue default requested scopes must preserve read:self')
assert.ok(defaultRequestedScopes.includes('read:media'), 'Fanvue default requested scopes must preserve read:media')
assert.ok(defaultRequestedScopes.includes('write:media'), 'Fanvue default requested scopes must preserve write:media')
assert.ok(!defaultRequestedScopes.includes('write:creator'), 'Fanvue default requested scopes must not include write:creator')
const requiredScopesMatch = oauth.match(/export const FANVUE_REQUIRED_CONNECTION_SCOPES = \[([\s\S]*?)\] as const/)
assert.ok(requiredScopesMatch, 'Fanvue required connection scopes must be declared separately from approved/requestable scopes')
const requiredConnectionScopes = Array.from(requiredScopesMatch[1].matchAll(/"([^"]+)"/g), (match) => match[1])
assert.ok(requiredConnectionScopes.includes('read:self'), 'Fanvue required connection scopes must include read:self')
assert.ok(requiredConnectionScopes.includes('read:media'), 'Fanvue required connection scopes must include read:media')
assert.ok(requiredConnectionScopes.includes('write:media'), 'Fanvue required connection scopes must include write:media')
assert.ok(!requiredConnectionScopes.includes('openid'), 'Fanvue required connection scopes must not require openid echo')
assert.ok(!requiredConnectionScopes.includes('offline_access'), 'Fanvue required connection scopes must not require offline_access echo')
assert.ok(!requiredConnectionScopes.includes('offline'), 'Fanvue required connection scopes must not require offline echo')
assert.ok(!requiredConnectionScopes.includes('write:creator'), 'Fanvue required connection scopes must not include write:creator')
assert.ok(requiredConnectionScopes.length < approvedScopes.length, 'Fanvue required connection scopes must be smaller than the requestable allowlist')
const optionalCreatorScopesMatch = oauth.match(/export const FANVUE_OPTIONAL_CREATOR_UPLOAD_SCOPES = \[([\s\S]*?)\] as const/)
assert.ok(optionalCreatorScopesMatch, 'Fanvue optional creator upload scopes must be declared separately')
const optionalCreatorScopes = Array.from(optionalCreatorScopesMatch[1].matchAll(/"([^"]+)"/g), (match) => match[1])
assert.deepEqual(optionalCreatorScopes, ['write:creator'], 'Fanvue optional creator upload scopes must contain only write:creator')
assert.match(oauth, /export const FANVUE_DEFAULT_SCOPES = FANVUE_DEFAULT_REQUESTED_SCOPES\.join\(" "\)/, 'Fanvue default scopes must derive from default requested scopes, not the approved allowlist')
assert.doesNotMatch(oauth.match(/export const FANVUE_DEFAULT_REQUESTED_SCOPES[\s\S]*?\] as const/)?.[0] ?? '', /write:creator/, 'write:creator must not appear in the default requested scope pathway')
assert.match(oauth, /export function scopeList\(scopes: unknown\): string\[\]/, 'Fanvue OAuth must expose a safe local scope parser')
assert.match(oauth, /export function hasFanvueScope\(scopes: unknown, scope: FanvueScope\): boolean/, 'Fanvue OAuth must expose safe local scope membership checks')
assert.match(oauth, /export function hasFanvueWriteCreatorScope\(scopes: unknown\): boolean/, 'Fanvue OAuth must expose a safe write:creator scope check')

const buildAuthorizeUrlSource = oauth.match(/export function buildFanvueAuthorizeUrl[\s\S]*?^}/m)?.[0] ?? ''
assert.match(buildAuthorizeUrlSource, /searchParams\.set\("response_type", "code"\)/, 'Fanvue authorize URL must request authorization code flow')
assert.match(buildAuthorizeUrlSource, /searchParams\.set\("client_id", config\.clientId\)/, 'Fanvue authorize URL must include client_id')
assert.match(buildAuthorizeUrlSource, /searchParams\.set\("redirect_uri", config\.redirectUri\)/, 'Fanvue authorize URL must include redirect_uri')
assert.match(buildAuthorizeUrlSource, /searchParams\.set\("scope", config\.scopes\.join\(" "\)\)/, 'Fanvue authorize URL must include approved scopes through the existing scope parameter')
assert.match(buildAuthorizeUrlSource, /searchParams\.set\("state", input\.state\)/, 'Fanvue authorize URL must include state')
assert.match(buildAuthorizeUrlSource, /searchParams\.set\("code_challenge", input\.codeChallenge\)/, 'Fanvue authorize URL must include PKCE code_challenge')
assert.match(buildAuthorizeUrlSource, /searchParams\.set\("code_challenge_method", "S256"\)/, 'Fanvue authorize URL must include PKCE S256 method')
assert.doesNotMatch(buildAuthorizeUrlSource, /prompt|access_type/, 'Fanvue authorize URL must not invent prompt=consent or access_type=offline params')
assert.doesNotMatch(buildAuthorizeUrlSource, /clientSecret|FANVUE_CLIENT_SECRET/, 'Fanvue authorize URL must not leak client secrets')
assert.match(oauth, /FANVUE_OAUTH_SCOPES[\s\S]*FANVUE_DEFAULT_SCOPES/, 'Fanvue OAuth scopes must still use explicit env override or safe defaults')
assert.match(oauth, /const approved = new Set<string>\(FANVUE_APPROVED_SCOPES\)/, 'Fanvue OAuth must validate explicit scopes against the approved/requestable allowlist')
assert.match(oauth, /const disallowed = unique\.filter\(\(scope\) => !approved\.has\(scope\)\)/, 'Fanvue OAuth must fail closed on unknown scopes')

const missingRequiredScopesSource = callback.match(/function missingRequiredScopes[\s\S]*?^}/m)?.[0] ?? ''
assert.match(callback, /FANVUE_REQUIRED_CONNECTION_SCOPES/, 'Fanvue callback must import/use required connection scopes')
assert.match(missingRequiredScopesSource, /FANVUE_REQUIRED_CONNECTION_SCOPES\.filter/, 'Fanvue missing-scope check must use required connection scopes')
assert.doesNotMatch(missingRequiredScopesSource, /FANVUE_APPROVED_SCOPES/, 'Fanvue missing-scope check must not require every approved/requestable scope')
assert.ok(requiredConnectionScopes.every((scope) => !['openid', 'offline_access', 'offline'].includes(scope)), 'Fanvue callback must not block solely on optional refresh/offline scope echo')
assert.ok(['read:self', 'read:media', 'write:media'].every((scope) => requiredConnectionScopes.includes(scope)), 'Fanvue callback still blocks when a required connection scope is missing')
assert.match(callback, /const missingScopes = missingRequiredScopes\(scopes\)[\s\S]*?if \(missingScopes\.length > 0\)[\s\S]*?fanvue_oauth_missing_required_scopes/, 'Fanvue callback must keep rejecting missing required connection scopes')
assert.match(callback, /const missingScopes = missingRequiredScopes\(scopes\)[\s\S]*?const identity = await fetchFanvueIdentity/s, 'Fanvue callback must validate required scopes before identity verification')
assert.match(callback, /const providerAccountId = getIdentityId\(identity\)[\s\S]*?if \(!providerAccountId\)[\s\S]*?fanvue_identity_unverified[\s\S]*?const encryptedAccessToken = encryptAutopostToken/s, 'Fanvue callback must not encrypt/store token material before required-scope and identity checks')
assert.match(callback, /encryptAutopostToken\(tokenResponse\.access_token\)/, 'Fanvue access token must be encrypted before storage')
assert.match(callback, /encrypted_refresh_token: encryptedRefreshToken/, 'Fanvue refresh token must use encrypted storage')
assert.match(callback, /buildFanvueTokenExchangeRequestInit/, 'Fanvue callback must centralize token exchange request construction for mocked source safety')
const tokenExchangeHelperSource = tokenExchangeHelper
assert.match(tokenExchangeHelperSource, /applyFanvueOAuthClientAuth/, 'Fanvue token exchange must use the shared client auth helper')
assert.match(clientAuthHelper, /client_id/, 'Fanvue shared client auth helper must support body client_id')
assert.match(clientAuthHelper, /client_secret/, 'Fanvue shared client auth helper must support body client_secret')
assert.match(tokenExchangeHelperSource, /grant_type: "authorization_code"/, 'Fanvue token exchange must preserve authorization_code grant')
assert.match(tokenExchangeHelperSource, /redirect_uri: input\.redirectUri/, 'Fanvue token exchange must preserve redirect_uri')
assert.match(tokenExchangeHelperSource, /code_verifier: input\.codeVerifier/, 'Fanvue token exchange must preserve PKCE code_verifier')
assert.match(clientAuthHelper, /Authorization|authorization|Basic/, 'Fanvue shared client auth helper must support configurable Basic auth')
assert.doesNotMatch(callback, /function getBasicAuthHeader/, 'Fanvue OAuth callback must not keep Basic auth helper for token exchange')
assert.doesNotMatch(callback, /access_token:\s*tokenResponse/, 'Fanvue callback must not write legacy plaintext access_token')
assert.doesNotMatch(callback, /refresh_token:\s*tokenResponse/, 'Fanvue callback must not write legacy plaintext refresh_token')
assert.match(callback, /fetchFanvueIdentity/, 'Fanvue callback must verify identity before CONNECTED')
assert.match(callback, /connection_status: "CONNECTED"/, 'Fanvue callback may only set CONNECTED in verified callback path')

assert.match(availability, /public_selectable: false/, 'Fanvue must remain non-selectable')
assert.match(availability, /can_schedule: false/, 'Fanvue must remain non-schedulable')
assert.match(availability, /supports_real_posting: false/, 'Fanvue must not advertise real posting in FV-3')
assert.match(availability, /supports_async_dispatch: false/, 'Fanvue dispatch must remain unavailable')
assert.match(availability, /connection_blocker: connectionBlocker/, 'Fanvue status must expose a safe connection blocker')
assert.match(availability, /native_posting_available: false/, 'Fanvue native posting must remain unavailable')
assert.match(availability, /assisted_available: platform.supports_assisted_workflow/, 'Fanvue assisted workflow availability must remain explicit')
assert.match(availability, /FANVUE_PROVIDER_IDENTITY_MISSING/, 'Manual rows without provider identity must not count as connected')
assert.match(availability, /FANVUE_ENCRYPTED_ACCESS_TOKEN_MISSING/, 'Legacy or manual rows without encrypted tokens must not count as connected')
assert.match(availability, /FANVUE_IDENTITY_NOT_CONFIRMED/, 'Rows without FV-3 identity confirmation must not count as connected')

assert.match(statusRoute, /encrypted_access_token, encrypted_refresh_token, metadata/, 'Fanvue status lookup must include encrypted-token and metadata fields for validation')

assert.match(envExample, /FANVUE_CONNECT_ENABLED=false/, 'Fanvue connect env example must default off')
assert.match(envExample, /FANVUE_RUN_DISPATCH_ENABLED=false/, 'Fanvue dispatch env example must default off')
assert.match(envExample, /FANVUE_CLIENT_SECRET=\n/, 'Fanvue client secret placeholder must be empty')
assert.match(refreshScopeNote, /does not initiate Fanvue reconnect/i, 'FV-40R docs must not approve reconnect')
assert.match(refreshScopeNote, /does not prove that Fanvue will return a `refresh_token`/i, 'FV-40R docs must keep refresh-token issuance unproven')
assert.match(refreshScopeNote, /does not approve live upload/i, 'FV-40R docs must not approve live upload')

for (const source of [oauth, callback]) {
  assert.doesNotMatch(source, /\.env\.local|dotenv\/config|api\.fanvue\.com\/posts|\/media\/uploads|\/posts\//, 'OAuth source safety checks must not add env-local, upload, or posts behavior')
}
assert.doesNotMatch(oauth, /\/creators|createFanvueMediaPost|createFanvueTextPost|readFanvuePost|persistAutopostJobResult|calculateNextRunAtAfterPostedProof/, 'OAuth source must not add creator upload, posts, dispatch, or schedule-advance behavior')

console.log('Fanvue OAuth source safety checks passed')
