import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const migration = readFileSync("supabase/migrations/20260813035247_fanvue_oauth_cpq_account_bridge.sql", "utf8")
const callback = readFileSync("app/api/autopost/connect/fanvue/callback/route.ts", "utf8")
const disconnect = readFileSync("app/api/autopost/connect/fanvue/disconnect/route.ts", "utf8")
const refresh = readFileSync("lib/autopost/fanvueTokenRefresh.ts", "utf8")
const validation = readFileSync("lib/creator-publishing-queue/accounts/validation.ts", "utf8")
const accountService = readFileSync("lib/creator-publishing-queue/accounts/service.ts", "utf8")
const platformSetup = readFileSync("supabase/migrations/20260710000700_creator_publishing_platform_account_setup.sql", "utf8")
const packageMigration = readFileSync("supabase/migrations/20260721001800_creator_publishing_verified_destination_guards.sql", "utf8")
const registry = readFileSync("lib/autopost/platformRegistry.ts", "utf8")
const availability = readFileSync("lib/autopost/platformAvailability.ts", "utf8")

assert.match(migration, /autopost_accounts_id_user_platform_unique unique \(id, user_id, platform\)/)
assert.match(migration, /autopost_accounts_fanvue_provider_account_uidx[\s\S]*provider_account_id[\s\S]*where platform = 'fanvue' and provider_account_id is not null/)
assert.doesNotMatch(migration, /unique index[^;]+on public\.autopost_accounts \(platform, provider_account_id\)/)
assert.match(migration, /old\.platform = 'fanvue'[\s\S]*old\.provider_account_id is not null[\s\S]*new\.provider_account_id is distinct from old\.provider_account_id/)
assert.match(migration, /platform <> 'fanvue' or connection_status <> 'CONNECTED' or provider_account_id is not null/)
assert.match(migration, /drop policy if exists "autopost_accounts_select_own"/)
assert.match(migration, /drop policy if exists "autopost_accounts_insert_own"/)
assert.match(migration, /drop policy if exists "autopost_accounts_update_own"/)
assert.match(migration, /revoke select, insert, update, delete, truncate, references, trigger[\s\S]*from anon, authenticated/)

assert.match(migration, /add column oauth_account_id uuid/)
assert.match(migration, /creator_platform_accounts_oauth_account_uidx[\s\S]*where oauth_account_id is not null/)
assert.match(migration, /foreign key \(oauth_account_id, creator_id, platform\)[\s\S]*references public\.autopost_accounts \(id, user_id, platform\)[\s\S]*on update no action[\s\S]*on delete no action[\s\S]*deferrable initially deferred/)
assert.match(migration, /platform = 'fanvue' and oauth_account_id is not null/)
assert.match(migration, /platform in \('onlyfans', 'fansly'\) and oauth_account_id is null/)
assert.match(migration, /platform = 'fanvue' and \(platform_username is null or length\(btrim\(platform_username\)\) > 0\)/)
assert.match(migration, /platform in \('onlyfans', 'fansly'\) and platform_username is not null and length\(btrim\(platform_username\)\) > 0/)

const signature = /creator_publishing_link_fanvue_oauth_account\(uuid,text,text,text,text,jsonb,text,text,integer,timestamptz,jsonb\)/g
assert.equal([...migration.matchAll(signature)].length, 4)
assert.match(migration, /security definer[\s\S]*set search_path = public, pg_temp/)
assert.match(migration, /pg_advisory_xact_lock[\s\S]*fanvue-oauth-user:[\s\S]*pg_advisory_xact_lock[\s\S]*fanvue-provider:/)
assert.match(migration, /FANVUE_PROVIDER_IDENTITY_CHANGE_REQUIRES_EXPLICIT_RELINK/)
assert.match(migration, /FANVUE_PROVIDER_IDENTITY_ALREADY_LINKED/)
assert.match(migration, /verification_status[\s\S]*'unattested'/)
assert.doesNotMatch(migration, /verification_status[^;]*'verified'/)
assert.match(migration, /verification_reviewed_by,[\s\S]*null, null, null, null, false, v_account\.id/)
assert.match(migration, /revoke execute[^;]+from public/)
assert.match(migration, /revoke execute[^;]+from anon/)
assert.match(migration, /revoke execute[^;]+from authenticated/)
assert.match(migration, /grant execute[^;]+to service_role/)
for (const forbidden of ["p_access_token text", "p_refresh_token text", "p_plaintext", "encrypted_access_token',", "encrypted_refresh_token',"]) assert.equal(migration.includes(forbidden), false, forbidden)
assert.doesNotMatch(migration, /insert into public\.creator_platform_accounts[\s\S]*select[\s\S]*from public\.autopost_accounts/)

const entitlementAt = callback.indexOf("await ensureActiveSubscription()")
const exchangeAt = callback.indexOf("await exchangeCodeForTokens(")
const identityAt = callback.indexOf("await fetchFanvueIdentity(")
const rpcAt = callback.indexOf('.rpc("creator_publishing_link_fanvue_oauth_account"')
assert.ok(entitlementAt > 0 && entitlementAt < exchangeAt && exchangeAt < identityAt && identityAt < rpcAt)
assert.match(callback, /if \(statePayload\.operation === FANVUE_CONNECT_OPERATION\) \{[\s\S]*\.rpc\("creator_publishing_link_fanvue_oauth_account"/)
assert.match(callback, /\} else \{[\s\S]*Privileged write:creator reconnect is credential-only and must never create CPQ state\.[\s\S]*\.from\("autopost_accounts"\)[\s\S]*\.upsert/)
assert.equal(callback.slice(callback.indexOf("} else {", rpcAt)).includes('.rpc("creator_publishing_link_fanvue_oauth_account"'), false)
assert.match(callback, /if \(bridgeError\)[\s\S]*fanvue_oauth_account_bridge_failed/)
assert.ok(callback.indexOf("return redirectWithClearedCookie({ connected: \"fanvue\" })") > rpcAt)

assert.match(disconnect, /connection_status: "REVOKED"/)
assert.match(disconnect, /encrypted_access_token: null/)
assert.match(disconnect, /encrypted_refresh_token: null/)
for (const forbidden of ["provider_account_id:", ".delete(", "ensureActiveSubscription", "creator_platform_accounts"]) assert.equal(disconnect.includes(forbidden), false, forbidden)
for (const forbidden of ["provider_account_id", "oauth_account_id", "creator_platform_accounts", ".delete("]) assert.equal(refresh.includes(forbidden), false, forbidden)

assert.match(validation, /if \(p === "fanvue"\) throw[\s\S]*FANVUE_NOT_AVAILABLE/)
assert.match(accountService, /\.in\("platform", \["onlyfans", "fansly"\]\)/)
assert.match(platformSetup, /if v_platform = 'fanvue' then raise exception 'FANVUE_NOT_AVAILABLE'/)
assert.match(packageMigration, /if v_account\.platform = 'fanvue' then raise exception 'FANVUE_NOT_AVAILABLE'/)
assert.match(packageMigration, /target_platform='fanvue'\) then raise exception 'FANVUE_NOT_AVAILABLE'/)
for (const field of ["public_selectable: platform.public_selectable ?? false", "supports_real_posting: platform.supports_real_posting ?? false"]) assert.ok(registry.includes(field), field)
const fanvueAvailability = availability.slice(availability.indexOf('if (platform.id === "fanvue")'), availability.indexOf('if (platform.id === "x")'))
for (const field of ["can_schedule: false", "supports_real_posting: false", "supports_text_posting: false", "supports_media_posting: false"]) assert.ok(fanvueAvailability.includes(field), field)

console.log("fanvue OAuth/CPQ bridge source contract: PASS")
