import assert from "node:assert/strict"
import { controlledRefreshX,handleXControlledRefreshRequest,X_CONTROLLED_REFRESH_BUFFER_MS,X_CONTROLLED_REFRESH_TIMEOUT_MS,X_CONTROLLED_REFRESH_ENDPOINT,hasZeroByteBody,xControlledRefreshMethodNotAllowedResult,type Account } from "../../../lib/autopost/xControlledRefresh"
const account:Account={connection_status:"CONNECTED",provider_account_id:"protected-id",provider_username:" The_Beard0302 ",last_error:null,encrypted_access_token:"old-access",encrypted_refresh_token:"old-refresh",token_expires_at:"2026-01-01T00:00:00.000Z",token_key_version:1,metadata:{provider:"x",identity_fetched:true}}
const writer=async()=>({data:{id:"row"},error:null})
const deps=(extra:any={})=>({getTokenKeyVersion:()=>1,now:()=>new Date("2026-01-01T00:00:00.000Z"),decryptToken:(v:string)=>{assert.equal(v,"old-refresh");return "refresh-secret"},encryptToken:(v:string)=>`encrypted:${v}`,clientId:"client",clientSecret:"secret",createTimeoutSignal:(n:number)=>{assert.equal(n,10000);return new AbortController().signal},fetch:async()=>new Response(JSON.stringify({access_token:"access-secret",token_type:"Bearer",expires_in:3600}),{status:200,headers:{"content-type":"application/json"}}),...extra})
async function test(name:string,fn:()=>unknown|Promise<unknown>){await fn();process.stdout.write(`ok - ${name}\n`)}
await test("constants enforce the sixty-second buffer, ten-second timeout, and exact endpoint",()=>{assert.equal(X_CONTROLLED_REFRESH_BUFFER_MS,60000);assert.equal(X_CONTROLLED_REFRESH_TIMEOUT_MS,10000);assert.equal(X_CONTROLLED_REFRESH_ENDPOINT,"https://api.x.com/2/oauth2/token")})
await test("method result is sanitized",()=>assert.equal(xControlledRefreshMethodNotAllowedResult().safe_code,"X_CONTROLLED_REFRESH_METHOD_NOT_ALLOWED"))
await test("null, closed, and finite zero-byte bodies pass",async()=>{assert.equal(await hasZeroByteBody(new Request("https://local")),true);assert.equal(await hasZeroByteBody(new Request("https://local",{method:"POST",body:new ReadableStream({start(c){c.close()}}),duplex:"half" as any})),true);assert.equal(await hasZeroByteBody(new Request("https://local",{method:"POST",body:new ReadableStream({start(c){c.enqueue(new Uint8Array());c.close()}}),duplex:"half" as any})),true)})
await test("nonempty and excessive zero-byte bodies fail",async()=>{assert.equal(await hasZeroByteBody(new Request("https://local",{method:"POST",body:" ",duplex:"half" as any})),false);assert.equal(await hasZeroByteBody(new Request("https://local",{method:"POST",body:new ReadableStream({start(c){for(let i=0;i<9;i++)c.enqueue(new Uint8Array())}}),duplex:"half" as any})),false)})
const request=(header?:string,url="https://local/")=>new Request(url,{method:"POST",headers:header?{"x-autopost-x-controlled-refresh":header}:{}})
await test("authentication, confirmation, and parameter gates precede privilege",async()=>{let privileged=0;const base={createPrivilegedAccess:()=>{privileged++;throw Error()},dependencies:deps()};assert.equal((await handleXControlledRefreshRequest({request:request(),getAuthenticatedUserId:async()=>null,...base})).status,401);assert.equal((await handleXControlledRefreshRequest({request:request(),getAuthenticatedUserId:async()=>" ",...base})).status,401);assert.equal((await handleXControlledRefreshRequest({request:request(),getAuthenticatedUserId:async()=>"u",...base})).body.safe_code,"X_CONTROLLED_REFRESH_CONFIRMATION_REQUIRED");assert.equal((await handleXControlledRefreshRequest({request:request("wrong"),getAuthenticatedUserId:async()=>"u",...base})).status,400);assert.equal((await handleXControlledRefreshRequest({request:request("refresh-protected-x-once-v1","https://local/?x=1"),getAuthenticatedUserId:async()=>"u",...base})).body.safe_code,"X_CONTROLLED_REFRESH_PARAMETERS_NOT_ALLOWED");assert.equal(privileged,0)})
await test("protected username rejects an at-sign and accepts normalized identity",async()=>{assert.equal((await controlledRefreshX("u",{...account,provider_username:"@The_beard0302"},writer,deps())).safe_code,"X_CONTROLLED_REFRESH_PROTECTED_USERNAME_MISMATCH");assert.equal((await controlledRefreshX("u",account,writer,deps())).safe_code,"X_CONTROLLED_REFRESH_SUCCEEDED")})
await test("key and refresh-required gates stop before provider",async()=>{assert.equal((await controlledRefreshX("u",account,writer,deps({getTokenKeyVersion:()=>2}))).safe_code,"X_CONTROLLED_REFRESH_TOKEN_KEY_VERSION_MISMATCH");assert.equal((await controlledRefreshX("u",{...account,token_expires_at:"2026-01-01T00:01:00.001Z"},writer,deps())).safe_code,"X_CONTROLLED_REFRESH_NOT_REQUIRED")})
await test("exactly sixty seconds is eligible and request is exact confidential-client form",async()=>{let calls=0;await controlledRefreshX("u",{...account,token_expires_at:"2026-01-01T00:01:00.000Z"},writer,deps({fetch:async(url:string,init:any)=>{calls++;assert.equal(url,X_CONTROLLED_REFRESH_ENDPOINT);assert.equal(init.method,"POST");assert.equal(init.headers.Authorization,"Basic Y2xpZW50OnNlY3JldA==");assert.deepEqual([...init.body.entries()],[['grant_type','refresh_token'],['refresh_token','refresh-secret']]);assert.equal(init.body.has('client_id'),false);return new Response(JSON.stringify({access_token:"new",token_type:"bearer",expires_in:1}),{status:200})}}));assert.equal(calls,1)})
await test("provider failures are safely classified without retry",async()=>{for(const [status,error,code] of [[400,"invalid_client","X_CONTROLLED_REFRESH_PROVIDER_INVALID_CLIENT"],[429,"slow","X_CONTROLLED_REFRESH_PROVIDER_RATE_LIMITED"],[403,"denied","X_CONTROLLED_REFRESH_PROVIDER_REJECTED"],[503,"server","X_CONTROLLED_REFRESH_PROVIDER_OUTCOME_UNKNOWN"]] as const){let calls=0;const r=await controlledRefreshX("u",account,writer,deps({fetch:async()=>{calls++;return new Response(JSON.stringify({error}),{status})}}));assert.equal(r.safe_code,code);assert.equal(r.retry_attempted,false);assert.equal(calls,1)}})
await test("invalid grant performs only the lifecycle write",async()=>{let writes=0;const r=await controlledRefreshX("u",account,async(v)=>{writes++;assert.deepEqual(v,{connection_status:"EXPIRED",last_error:"X_CONTROLLED_REFRESH_PROVIDER_UNAUTHORIZED"});return{data:{id:"row"},error:null}},deps({fetch:async()=>new Response(JSON.stringify({error:"invalid_grant"}),{status:400})}));assert.equal(r.safe_code,"X_CONTROLLED_REFRESH_PROVIDER_UNAUTHORIZED");assert.equal(r.database_write_verified,true);assert.equal(writes,1)})
await test("strict response validation prevents writes",async()=>{let writes=0;for(const body of [null,[],{}, {access_token:"",token_type:"bearer",expires_in:1},{access_token:"a",token_type:"mac",expires_in:1},{access_token:"a",token_type:"bearer",expires_in:0},{access_token:"a",token_type:"bearer",expires_in:1,scope:" "}]){const r=await controlledRefreshX("u",account,async()=>{writes++;return{data:{id:"x"},error:null}},deps({fetch:async()=>new Response(JSON.stringify(body),{status:200})}));assert.equal(r.safe_code,"X_CONTROLLED_REFRESH_PROVIDER_RESPONSE_INVALID");assert.equal(r.outcome_uncertain,true)}assert.equal(writes,0)})
await test("replacement refresh is encrypted and omission preserves old ciphertext",async()=>{for(const replacement of [undefined,"replacement"]){let values:any;await controlledRefreshX("u",account,async(v)=>{values=v;return{data:{id:"x"},error:null}},deps({fetch:async()=>new Response(JSON.stringify({access_token:"new",token_type:"bearer",expires_in:10,...(replacement?{refresh_token:replacement}:{})}),{status:200})}));assert.equal(values.encrypted_refresh_token,replacement?"encrypted:replacement":"old-refresh")}})
await test("safe results never expose secret markers",async()=>{const r=await controlledRefreshX("user-secret",account,writer,deps());const serialized=JSON.stringify(r);for(const marker of ["access-secret","refresh-secret","protected-id","client","user-secret","old-access","old-refresh"])assert.equal(serialized.includes(marker),false);for(const key of ["retry_attempted","post_attempted","runner_invoked","scheduler_action_attempted","cron_action_attempted","public_enablement_attempted","fanvue_account_queried","fanvue_account_mutated"] as const)assert.equal(r[key],false)})
