import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { register } from "node:module"
register(`data:text/javascript,export async function resolve(s,c,n){return s==='server-only'?{url:'data:text/javascript,export default {}',shortCircuit:true}:n(s,c)}`)

const d = await import("../../../lib/autopost/xIdentityDiagnostic.ts")
const a = await import("../../../lib/autopost/platformAvailability.ts")
const r = await import("../../../lib/autopost/platformRegistry.ts")
const { X_IDENTITY_DIAGNOSTIC_CONFIRMATION_HEADER: HEADER, X_IDENTITY_DIAGNOSTIC_CONFIRMATION_VALUE: CONFIRM, X_IDENTITY_DIAGNOSTIC_TIMEOUT_MS: TIMEOUT, createXIdentityDiagnosticAccountLoader, handleXIdentityDiagnosticRequest, runXIdentityDiagnostic, xIdentityDiagnosticMethodNotAllowedResult } = d

const account = { connection_status:"CONNECTED", provider_account_id:" provider-id ", provider_username:" Fake_Handle ", connected_at:"2026-01-01T00:00:00.000Z", last_refresh_at:null, last_error:null, encrypted_access_token:"encrypted-access-marker", encrypted_refresh_token:"encrypted-refresh-marker", token_expires_at:"2020-01-01T00:00:00.000Z", token_key_version:7, metadata:{provider:"x",identity_fetched:true} }
type F = typeof fetch
function fixture(overrides:Record<string,unknown>={}) {
  let calls=0; const timeouts:number[]=[]
  const rawFetch=(overrides.fetchImpl as F|undefined)??(async()=>new Response(JSON.stringify({data:{id:"provider-id",username:"fake_handle"}}))) as F
  const rawTimeout=(overrides.createTimeoutSignal as ((n:number)=>AbortSignal)|undefined)??(()=>new AbortController().signal)
  const rest={...overrides}; delete rest.fetchImpl; delete rest.createTimeoutSignal
  return { calls:()=>calls, timeouts, deps:{ loadAccount:async()=>structuredClone(account), getTokenKeyVersion:()=>7, decryptToken:()=>"  fake-decrypted-token  ", getApiBaseUrl:()=>"https://api.x.invalid/base", ...rest,
    createTimeoutSignal:(n:number)=>{timeouts.push(n);return rawTimeout(n)},
    fetchImpl:(async(...args:Parameters<F>)=>{calls++;return rawFetch(...args)}) as F } as any }
}
function flags(out:any, expected:Record<string,unknown>) { const fixed={mode:"x_identity_read_only_diagnostic",read_only:true,database_write_attempted:false,refresh_attempted:false,retry_attempted:false,post_attempted:false}; for(const [k,v] of Object.entries({...fixed,...expected})) assert.deepEqual(out[k],v,k) }
async function provider(fetchImpl:F, expected:Record<string,unknown>) { const x=fixture({fetchImpl}); const out=await runXIdentityDiagnostic("u",x.deps); flags(out,expected); assert.equal(x.calls(),1); assert.deepEqual(x.timeouts,[5000]); return out }

{
  const ops:unknown[]=[]; const builder:any={select(v:string){ops.push(["select",v]);return this},eq(k:string,v:string){ops.push(["eq",k,v]);return this},async maybeSingle(){ops.push(["maybeSingle"]);return{data:account,error:null}}}; const client:any={from(t:string){ops.push(["from",t]);return builder}}
  assert.deepEqual(await createXIdentityDiagnosticAccountLoader(client)("session-user"),account)
  assert.deepEqual(ops,[["from","autopost_accounts"],["select","connection_status, provider_account_id, provider_username, last_error, encrypted_access_token, encrypted_refresh_token, token_expires_at, token_key_version, metadata"],["eq","user_id","session-user"],["eq","platform","x"],["maybeSingle"]])
}

const blockers:Array<[string,Partial<typeof account>|null]>=[["X_ACCOUNT_NOT_CONNECTED",null],["X_ACCOUNT_STATUS_DISCONNECTED",{connection_status:"DISCONNECTED"}],["X_ACCOUNT_STATUS_EXPIRED",{connection_status:"EXPIRED"}],["X_ACCOUNT_STATUS_REVOKED",{connection_status:"REVOKED"}],["X_ACCOUNT_STATUS_ERROR",{connection_status:"ERROR"}],["X_PROVIDER_ACCOUNT_ID_MISSING",{provider_account_id:" "}],["X_PROVIDER_USERNAME_MISSING",{provider_username:" "}],["X_ENCRYPTED_ACCESS_TOKEN_MISSING",{encrypted_access_token:""}],["X_ENCRYPTED_REFRESH_TOKEN_MISSING",{encrypted_refresh_token:""}],["X_TOKEN_EXPIRY_INVALID",{token_expires_at:"bad"}],["X_TOKEN_KEY_VERSION_INVALID",{token_key_version:0}],["X_PROVIDER_METADATA_MISSING",{metadata:{provider:"other",identity_fetched:true}}],["X_IDENTITY_NOT_CONFIRMED",{metadata:{provider:"x",identity_fetched:false}}],["X_ACCOUNT_ERROR_PRESENT",{last_error:"raw-last-error"}]]
for(const [blocker,patch] of blockers){const row=patch===null?null:{...structuredClone(account),...patch};const x=fixture({loadAccount:async()=>row});const out=await runXIdentityDiagnostic("u",x.deps);flags(out,{ok:false,safe_code:"X_IDENTITY_DIAGNOSTIC_ACCOUNT_NOT_READY",stored_posture_verified:false,stored_posture_blocker:blocker,provider_request_attempted:false,provider_status_class:null,provider_authenticated:null,identity_match:null});assert.equal(x.calls(),0);assert.equal(a.getXStoredPostureBlocker(row),blocker)}

for(const [overrides,code] of [[{getTokenKeyVersion:()=>undefined},"X_IDENTITY_DIAGNOSTIC_TOKEN_KEY_VERSION_UNAVAILABLE"],[{getTokenKeyVersion:()=>8},"X_IDENTITY_DIAGNOSTIC_TOKEN_KEY_VERSION_MISMATCH"],[{decryptToken:()=>{throw new Error("decrypt detail")}},"X_IDENTITY_DIAGNOSTIC_ACCESS_TOKEN_DECRYPT_FAILED"],[{decryptToken:()=>"   "},"X_IDENTITY_DIAGNOSTIC_ACCESS_TOKEN_INVALID"]] as const){const x=fixture(overrides);const out=await runXIdentityDiagnostic("u",x.deps);flags(out,{safe_code:code,stored_posture_verified:true,provider_request_attempted:false});assert.equal(x.calls(),0)}
for(const value of [undefined,null,7,""," ","bad","http://api.x.invalid","https://u@api.x.invalid","https://u:p@api.x.invalid","https://api.x.invalid?q=1","https://api.x.invalid#x"]){const x=fixture({getApiBaseUrl:()=>value});const out=await runXIdentityDiagnostic("u",x.deps);flags(out,{safe_code:"X_IDENTITY_DIAGNOSTIC_PROVIDER_CONFIG_INVALID",stored_posture_verified:true,provider_request_attempted:false});assert.equal(x.calls(),0)}

for(const [status,code,auth] of [[401,"X_IDENTITY_DIAGNOSTIC_PROVIDER_UNAUTHORIZED",false],[403,"X_IDENTITY_DIAGNOSTIC_PROVIDER_FORBIDDEN",null],[429,"X_IDENTITY_DIAGNOSTIC_PROVIDER_RATE_LIMITED",null],[500,"X_IDENTITY_DIAGNOSTIC_PROVIDER_TEMPORARY_FAILURE",null],[418,"X_IDENTITY_DIAGNOSTIC_PROVIDER_REJECTED",null]] as const) await provider(async()=>new Response("raw-provider-secret",{status}),{ok:false,safe_code:code,stored_posture_verified:true,provider_request_attempted:true,provider_status_class:status>=500?"5xx":"4xx",provider_authenticated:auth,identity_match:null})
for(const [error,code] of [[Object.assign(new Error("timeout detail"),{name:"TimeoutError"}),"X_IDENTITY_DIAGNOSTIC_TIMEOUT"],[new Error("network detail"),"X_IDENTITY_DIAGNOSTIC_NETWORK_FAILURE"]] as const) await provider(async()=>{throw error},{ok:false,safe_code:code,stored_posture_verified:true,provider_request_attempted:true,provider_status_class:null,provider_authenticated:null,identity_match:null})
for(const body of [null,"x",1,[],{}, {data:null},{data:{}},{data:{id:" ",username:"u"}},{data:{id:"provider-id",username:" "}}]) await provider(async()=>({ok:true,status:200,json:async()=>body}) as Response,{ok:false,safe_code:"X_IDENTITY_DIAGNOSTIC_RESPONSE_INVALID",stored_posture_verified:true,provider_request_attempted:true,provider_status_class:"2xx",provider_authenticated:true,identity_match:null})
for(const [body,code,match,ok] of [[{data:{id:"other",username:"other"}},"X_IDENTITY_DIAGNOSTIC_PROVIDER_ID_MISMATCH",false,false],[{data:{id:"provider-id",username:"other"}},"X_IDENTITY_DIAGNOSTIC_USERNAME_MISMATCH",false,false],[{data:{id:"provider-id",username:"FAKE_HANDLE"}},"X_IDENTITY_DIAGNOSTIC_MATCHED",true,true]] as const) await provider(async()=>new Response(JSON.stringify(body)),{ok,safe_code:code,stored_posture_verified:true,provider_request_attempted:true,provider_status_class:"2xx",provider_authenticated:true,identity_match:match})

{
  const signal=new AbortController().signal; const x=fixture({getApiBaseUrl:()=>"https://api.x.invalid/nested/base",createTimeoutSignal:(n:number)=>{assert.equal(n,TIMEOUT);return signal},fetchImpl:async(url:string|URL|Request,init?:RequestInit)=>{assert.equal(String(url),"https://api.x.invalid/2/users/me");assert.equal(init?.method,"GET");assert.equal(init?.signal,signal);assert.deepEqual(init?.headers,{Authorization:"Bearer fake-decrypted-token"});assert.equal("body" in (init??{}),false);return new Response(JSON.stringify({data:{id:"provider-id",username:"fake_handle"}}))}});assert.equal((await runXIdentityDiagnostic("u",x.deps)).safe_code,"X_IDENTITY_DIAGNOSTIC_MATCHED");assert.equal(x.calls(),1);assert.deepEqual(x.timeouts,[5000]);assert.equal(TIMEOUT,5000)
}

{
  let reads=0; const x=fixture({loadAccount:async()=>{reads++;return account}}); const req=(url="https://local.invalid/api",header?:string)=>new Request(url,{method:"POST",headers:header?{[HEADER]:header}:{}})
  for(const auth of [async()=>{throw new Error("auth")},async()=>" "]){const out=await handleXIdentityDiagnosticRequest({...x.deps,request:req("https://local.invalid/api",CONFIRM),getAuthenticatedUserId:auth});assert.equal(out.body.safe_code,"X_IDENTITY_DIAGNOSTIC_UNAUTHENTICATED")}
  for(const [request,code] of [[req(),"X_IDENTITY_DIAGNOSTIC_CONFIRMATION_REQUIRED"],[req("https://local.invalid/api","wrong"),"X_IDENTITY_DIAGNOSTIC_CONFIRMATION_REQUIRED"],[req("https://local.invalid/api?q=1",CONFIRM),"X_IDENTITY_DIAGNOSTIC_PARAMETERS_NOT_ALLOWED"]] as const){const out=await handleXIdentityDiagnosticRequest({...x.deps,request,getAuthenticatedUserId:async()=>"u"});assert.equal(out.body.safe_code,code)}
  assert.equal(reads,0);assert.equal(x.calls(),0);const out=await handleXIdentityDiagnosticRequest({...x.deps,request:req("https://local.invalid/api",CONFIRM),getAuthenticatedUserId:async()=>"u"});assert.equal(out.body.safe_code,"X_IDENTITY_DIAGNOSTIC_MATCHED");assert.equal(reads,1);assert.equal(x.calls(),1)
}
flags(xIdentityDiagnosticMethodNotAllowedResult(),{ok:false,safe_code:"X_IDENTITY_DIAGNOSTIC_METHOD_NOT_ALLOWED",stored_posture_verified:false,provider_request_attempted:false,provider_status_class:null,provider_authenticated:null,identity_match:null})

const route=readFileSync("app/api/admin/autopost/x/identity-diagnostic/route.ts","utf8")
for(const text of ['runtime = "nodejs"','dynamic = "force-dynamic"','revalidate = 0','private, no-store, max-age=0','Pragma: "no-cache"','Expires: "0"','Referrer-Policy": "no-referrer"','X-Content-Type-Options": "nosniff"','export async function POST','export function GET','status: 405','loadAccount: async'])assert.ok(route.includes(text),text)
assert.equal(route.includes("createXIdentityDiagnosticAccountLoader(getSupabaseAdmin()),"),false)
for(const path of ["lib/autopost/xIdentityDiagnostic.ts","app/api/admin/autopost/x/identity-diagnostic/route.ts"]){const source=readFileSync(path,"utf8");for(const bad of [".update(",".upsert(",".insert(",".delete(",".rpc(","refreshXAccessToken","postXTextOnlyAutopost","/2/tweets","console.log","console.error"])assert.equal(source.includes(bad),false)}
for(const path of ["app/autopost/AutopostPageClient.tsx","app/api/autopost/run/route.ts","vercel.json"]){const source=readFileSync(path,"utf8");assert.equal(source.includes("/api/admin/autopost/x/identity-diagnostic"),false)}

const oldDispatch=process.env.AUTOPOST_X_RUN_DISPATCH_ENABLED, oldFanvue=process.env.FANVUE_CONNECT_ENABLED;const names=["X_CLIENT_ID","X_CLIENT_SECRET","X_REDIRECT_URI","AUTOPOST_TOKEN_ENCRYPTION_KEY","AUTOPOST_OAUTH_STATE_SECRET"] as const;const old=new Map(names.map(n=>[n,process.env[n]]))
try{process.env.AUTOPOST_X_RUN_DISPATCH_ENABLED="false";process.env.FANVUE_CONNECT_ENABLED="false";for(const n of names)process.env[n]="fake";const platforms=r.getAutopostPlatformRegistry();const x=platforms.find((p:any)=>p.id==="x")!,fanvue=platforms.find((p:any)=>p.id==="fanvue")!;assert.equal(r.getSelectableAutopostPlatformIds().has("x"),false);const xs=a.buildUserPlatformStatus(x,new Map([["x",account]]) as any);assert.equal(xs.public_selectable,false);assert.equal(xs.can_schedule,false);assert.ok(xs.blockers.includes("X_PUBLIC_ENABLEMENT_NOT_APPROVED"));const fs=a.buildUserPlatformStatus(fanvue,new Map() as any);assert.equal(fs.user_connected,false);assert.equal(fs.can_schedule,false);assert.equal(fs.config_error,"FANVUE_CONNECT_DISABLED");assert.equal(process.env.AUTOPOST_X_RUN_DISPATCH_ENABLED,"false")}finally{if(oldDispatch===undefined)delete process.env.AUTOPOST_X_RUN_DISPATCH_ENABLED;else process.env.AUTOPOST_X_RUN_DISPATCH_ENABLED=oldDispatch;if(oldFanvue===undefined)delete process.env.FANVUE_CONNECT_ENABLED;else process.env.FANVUE_CONNECT_ENABLED=oldFanvue;for(const[n,v]of old){if(v===undefined)delete process.env[n];else process.env[n]=v}}

for(const marker of ["fake-decrypted-token","encrypted-access-marker","encrypted-refresh-marker","provider-id","Fake_Handle","raw-last-error","timeout detail","network detail","raw-provider-secret"])assert.equal(JSON.stringify(xIdentityDiagnosticMethodNotAllowedResult()).includes(marker),false)
console.log("X identity diagnostic deterministic read-only tests passed; fake evidence only; no network or Production action occurred.")
