import assert from 'node:assert/strict'
import { register } from 'node:module'

process.env.SUPABASE_URL = 'http://127.0.0.1:54321'
process.env.NEXT_PUBLIC_SUPABASE_URL = 'http://127.0.0.1:54321'
process.env.SUPABASE_SERVICE_ROLE_KEY = 'dummy-service-role-key'
process.env.CRON_SECRET = 'dummy-cron-secret'

const loaderSource = `export async function resolve(specifier, context, nextResolve) { if (specifier === 'server-only') return { url: 'data:text/javascript,export%20{}', shortCircuit: true }; return nextResolve(specifier, context) }`
register(`data:text/javascript,${encodeURIComponent(loaderSource)}`, import.meta.url)

const { executeAutopost } = await import('../../../app/api/autopost/run/route')
const { postXTextOnlyAutopost } = await import('../../../lib/autopost/xAdapter')
const { refreshXAccessToken } = await import('../../../lib/autopost/xTokenRefresh')
const { getAutopostPlatformRegistry, getSelectableAutopostPlatformIds } = await import('../../../lib/autopost/platformRegistry')
const { buildUserPlatformStatus } = await import('../../../lib/autopost/platformAvailability')

type Op = { table: string; type: string; values?: any; filters: any[]; select?: string }
const API = 'https://api.x.invalid'
const TWEETS = `${API}/2/tweets`
const TOKEN = `${API}/2/oauth2/token`
const OLD_ENC_ACCESS = 'enc-local-access-old'
const OLD_ENC_REFRESH = 'enc-local-refresh-old'
const NEW_ENC_ACCESS = 'enc-local-access-new'
const NEW_ENC_REFRESH = 'enc-local-refresh-new'
const OLD_ACCESS = 'plain-local-access-old'
const NEW_ACCESS = 'plain-local-access-new'
const OLD_REFRESH = 'plain-local-refresh-old'
const CLIENT_ID = 'local-test-client'
const CLIENT_SECRET = 'local-test-client-secret'
const RAW_PROVIDER_BODY = 'RAW_PROVIDER_BODY_MARKER'
const THROW_POST = 'THROWN_CREATE_POST_EXCEPTION_MARKER'
const THROW_REFRESH = 'THROWN_REFRESH_EXCEPTION_MARKER'
const RAW_DB = 'RAW_FAKE_DATABASE_ERROR_MARKER'
const LEVELS = new Set(['DEBUG', 'INFO', 'WARN', 'ERROR'])
const forbidden = [OLD_ENC_ACCESS, OLD_ENC_REFRESH, NEW_ENC_ACCESS, NEW_ENC_REFRESH, OLD_ACCESS, NEW_ACCESS, OLD_REFRESH, CLIENT_SECRET, RAW_PROVIDER_BODY, THROW_POST, THROW_REFRESH, RAW_DB]
let currentNow = new Date('2026-07-23T12:00:00.000Z')
const now = () => new Date(currentNow)

class FakeResponse { status:number; ok:boolean; body:any; constructor(status:number, body:any){this.status=status; this.ok=status>=200&&status<300; this.body=body} async json(){return this.body} }
class FakeFetch { queue:any[]=[]; calls:any[]=[]; enqueue(status:number, body:any){this.queue.push({status,body})} throwNext(e:Error){this.queue.push({throw:e})} impl=async (url:any, init:any={})=>{const href=String(url); if(href!==TWEETS&&href!==TOKEN) throw new Error(`unexpected fake URL ${href}`); const method=String(init.method||'GET').toUpperCase(); if(method!=='POST') throw new Error('unexpected fake method'); const h=new Headers(init.headers||{}); const rec={url:href, method, authorization:h.get('authorization'), contentType:h.get('content-type'), body:init.body}; this.calls.push(rec); const next=this.queue.shift(); if(!next) throw new Error('missing queued fake fetch response'); if(next.throw) throw next.throw; return new FakeResponse(next.status,next.body) as any }
  posts(){return this.calls.filter(c=>c.url===TWEETS)} refreshes(){return this.calls.filter(c=>c.url===TOKEN)} }
class Q { table:string; type='select'; values:any; filters:any[]=[]; selectValue?:string; c:DB; constructor(c:DB,t:string){this.c=c;this.table=t} select(v?:string){this.selectValue=v;return this} insert(v:any){this.type='insert';this.values=v;return this} update(v:any){this.type='update';this.values=v;return this} eq(c:string,v:any){this.filters.push(['eq',c,v]);return this} is(c:string,v:any){this.filters.push(['is',c,v]);return this} not(c:string,o:string,v:any){this.filters.push(['not',c,o,v]);return this} lte(c:string,v:any){this.filters.push(['lte',c,v]);return this} or(v:string){this.filters.push(['or',v]);return this} single(){return this} maybeSingle(){return this} then(r:any,j:any){return Promise.resolve(this.c.execute(this)).then(r,j)} }
const allowed = { autopost_jobs:new Set(['state','result_status','result','error_code','error_message','platform_post_id','posted_at','completed_at','next_attempt_at','locked_at','lock_id','attempt_count']), autopost_accounts:new Set(['encrypted_access_token','encrypted_refresh_token','token_key_version','token_expires_at','token_type','connection_status','last_refresh_at','last_error','scopes']), autopost_rules:new Set(['last_run_at','next_run_at']) } as any
class DB { operations:Op[]=[]; rules:any[]=[]; jobs:any[]=[]; logs:any[]=[]; accounts:any[]=[]; scheduleUpdates=0; resultUpdates=0; constructor(id='a', expired=false){this.rules=[rule(id)]; this.accounts=[account(`user-${id}`, expired)]} from(t:string){return new Q(this,t)} execute(q:Q){this.operations.push({table:q.table,type:q.type,values:q.values,filters:q.filters,select:q.selectValue}); if(q.type==='update'&&allowed[q.table]){const bad=Object.keys(q.values).filter(k=>!allowed[q.table].has(k)); if(bad.length) return {data:null,error:{message:`${RAW_DB}:${bad.join(',')}`}}}
 if(q.table==='autopost_rules'&&q.type==='select') return {data:this.rules.filter(r=>match(q,r)),error:null};
 if(q.table==='autopost_rules'&&q.type==='update'){const r=this.rules.find(x=>x.id===eq(q,'id')&&x.user_id===eq(q,'user_id')&&x.approval_state==='APPROVED'&&x.enabled&&x.paused_at===null&&x.revoked_at===null); if(r){Object.assign(r,q.values); this.scheduleUpdates++; return {data:{id:r.id},error:null}} return {data:null,error:null}}
 if(q.table==='autopost_job_logs'&&q.type==='insert'){assert.ok(LEVELS.has(q.values.level)); assert.equal(q.values.level,q.values.level.toUpperCase()); this.logs.push(q.values); return {data:null,error:null}}
 if(q.table==='autopost_accounts'&&q.type==='select'){const row=this.accounts.find(a=>match(q,a)); return {data:row??null,error:null}}
 if(q.table==='autopost_accounts'&&q.type==='update'){const row=this.accounts.find(a=>match(q,a)); if(row){Object.assign(row,q.values); return {data:q.selectValue?{user_id:row.user_id}:row,error:null}} return {data:null,error:null}}
 if(q.table==='autopost_jobs'&&q.type==='insert'){const old=this.jobs.find(j=>j.rule_id===q.values.rule_id&&j.platform===q.values.platform&&j.scheduled_for===q.values.scheduled_for); if(old) return {data:null,error:{code:'23505',message:'duplicate'}}; const job={id:`job-${this.jobs.length+1}`,...q.values}; this.jobs.push(job); return {data:pick(job),error:null}}
 if(q.table==='autopost_jobs'&&q.type==='select'){const id=eq(q,'id'); const j=id?this.jobs.find(x=>x.id===id):this.jobs.find(x=>match(q,x)); return {data:j??null,error:null}}
 if(q.table==='autopost_jobs'&&q.type==='update'){const j=this.jobs.find(x=>x.id===eq(q,'id')); if(!j) return {data:null,error:null}; if('lock_id' in q.values && !('result_status' in q.values) && !lockAllowed(q,j)) return {data:null,error:null}; Object.assign(j,q.values); if('result_status' in q.values) this.resultUpdates++; return {data:pick(j),error:null}}
 throw new Error(`unexpected ${q.table}.${q.type}`)} }
function eq(q:Q,c:string){return q.filters.find(f=>f[0]==='eq'&&f[1]===c)?.[2]} function match(q:Q,row:any){return q.filters.every(f=>f[0]==='eq'?row[f[1]]===f[2]:f[0]==='is'?row[f[1]]===f[2]:f[0]==='not'?row[f[1]]!==null:f[0]==='lte'?row[f[1]]<=f[2]:true)}
function lockAllowed(q:Q,j:any){const observed=eq(q,'attempt_count'); const or=String(q.filters.find(f=>f[0]==='or')?.[1]||''); const m=or.match(/next_attempt_at\.lte\.([^,)]*)/); const due=j.next_attempt_at===null||(m&&j.next_attempt_at<=m[1]); return j.state==='QUEUED'&&j.completed_at===null&&j.attempt_count===observed&&due&&j.locked_at===null}
function pick(j:any){return {id:j.id,attempt_count:j.attempt_count,locked_at:j.locked_at,lock_id:j.lock_id,state:j.state,next_attempt_at:j.next_attempt_at,completed_at:j.completed_at,result_status:j.result_status,error_code:j.error_code,error_message:j.error_message}}
function rule(id:string){return {id,user_id:`user-${id}`,approval_state:'APPROVED',enabled:true,selected_platforms:['x'],next_run_at:'2026-07-23T12:00:00.000Z',timezone:'UTC',start_date:null,end_date:null,posts_per_day:1,time_slots:['12:00'],paused_at:null,revoked_at:null,content_payload:{platform:'x',content_type:'text',media_posting_enabled:false,text:`fixture text ${id}`}}}
function account(user_id:string, expired=false){return {user_id,platform:'x',connection_status:'CONNECTED',encrypted_access_token:OLD_ENC_ACCESS,encrypted_refresh_token:OLD_ENC_REFRESH,token_expires_at:expired?'2026-07-23T11:00:00.000Z':'2026-07-24T12:00:00.000Z',token_type:'bearer',token_key_version:1,provider_username:'local_x_user',provider_account_id:'local-x-id',last_error:'old'}}
function req(q='dispatch=1'){return new Request(`http://local.test/api/autopost/run?${q}`,{headers:{authorization:'Bearer dummy-cron-secret'}})}
function decrypt(v:string){if(v===OLD_ENC_ACCESS)return OLD_ACCESS; if(v===NEW_ENC_ACCESS)return NEW_ACCESS; if(v===OLD_ENC_REFRESH)return OLD_REFRESH; throw new Error('decrypt failed')} function encrypt(v:string){if(v===NEW_ACCESS)return NEW_ENC_ACCESS; if(v==='plain-local-refresh-new')return NEW_ENC_REFRESH; throw new Error('encrypt failed')}
async function run(db:DB, fetcher:FakeFetch, env:any={AUTOPOST_X_RUN_DISPATCH_ENABLED:'true'}, q='dispatch=1'){let adapterCalls=0; const refreshDeps={supabaseAdmin:db as any,fetchImpl:fetcher.impl,decryptToken:decrypt,encryptToken:encrypt,getTokenKeyVersion:()=>2,getApiBaseUrl:()=>API,env:{X_CLIENT_ID:CLIENT_ID,X_CLIENT_SECRET:CLIENT_SECRET},now}; const adapterDeps={supabaseAdmin:db as any,fetchImpl:fetcher.impl,decryptToken:decrypt,refreshAccessToken:(input:any)=>refreshXAccessToken(input,refreshDeps),getApiBaseUrl:()=>API,now}; const res=await executeAutopost(req(q),{supabaseAdmin:db as any,cronSecret:'dummy-cron-secret',env,now,postXTextOnlyAutopost:(input:any)=>{adapterCalls++; return postXTextOnlyAutopost(input,adapterDeps)}}); return {body:await res.json(), adapterCalls} }
function noLeaks(db:DB, body:any){const surfaces=[body,db.jobs.map(j=>({result:j.result,error_code:j.error_code,error_message:j.error_message})),db.logs,db.rules.map(r=>({last_run_at:r.last_run_at,next_run_at:r.next_run_at}))]; const s=JSON.stringify(surfaces); for(const f of forbidden) assert.equal(s.includes(f),false,`leaked ${f}`)} function opi(db:DB,t:string,type:string){return db.operations.findIndex(o=>o.table===t&&o.type===type)} function count(db:DB,t:string,type:string){return db.operations.filter(o=>o.table===t&&o.type===type).length}

{ const db=new DB('success'); const f=new FakeFetch(); f.enqueue(201,{data:{id:'fake-provider-id'}}); const out=await run(db,f); const job=db.jobs[0]; assert.equal(db.rules.length,1); assert.equal(db.accounts.length,1); assert.equal(f.refreshes().length,0); assert.equal(job.attempt_count,1); assert.equal(f.posts().length,1); assert.equal(f.posts()[0].url,TWEETS); assert.equal(f.posts()[0].method,'POST'); assert.equal(f.posts()[0].authorization,`Bearer ${OLD_ACCESS}`); assert.equal(f.posts()[0].contentType,'application/json'); assert.deepEqual(JSON.parse(f.posts()[0].body),{text:'fixture text success'}); assert.equal(job.state,'SUCCEEDED'); assert.equal(job.result_status,'POSTED'); assert.equal(job.platform_post_id,'fake-provider-id'); assert.equal(job.posted_at,now().toISOString()); assert.equal(job.completed_at,now().toISOString()); assert.equal(job.next_attempt_at,null); assert.equal(job.locked_at,null); assert.equal(job.lock_id,null); assert.equal(job.result.posted,true); assert.equal(job.result.platform_post_id,'fake-provider-id'); assert.ok(opi(db,'autopost_jobs','update')<f.calls.findIndex(c=>c.url===TWEETS)+db.operations.length); assert.equal(db.scheduleUpdates,1); assert.equal(db.rules[0].last_run_at,now().toISOString()); assert.equal(db.rules[0].next_run_at,'2026-07-24T12:00:00.000Z'); assert.equal(db.logs.filter(l=>l.message==='schedule_advanced').length,1); assert.equal(out.body.summary.results_posted,1); assert.equal(out.body.summary.schedule_advancements,1); assert.equal(out.body.summary.schedule_advancement_skipped,0); noLeaks(db,out.body) }
{ currentNow=new Date('2026-07-23T12:00:00.000Z'); const db=new DB('retry'); const f=new FakeFetch(); f.enqueue(429,{error:RAW_PROVIDER_BODY}); let out=await run(db,f); assert.equal(f.posts().length,1); assert.equal(db.jobs[0].error_code,'X_API_RATE_LIMITED'); assert.equal(db.jobs[0].attempt_count,1); assert.equal(db.jobs[0].state,'QUEUED'); assert.equal(db.jobs[0].result_status,'FAILED'); assert.equal(db.jobs[0].completed_at,null); assert.equal(db.jobs[0].next_attempt_at,'2026-07-23T12:05:00.000Z'); assert.equal(db.scheduleUpdates,0); assert.equal(out.body.summary.results_failed,1); assert.equal(out.body.summary.schedule_advancement_skipped,1); currentNow=new Date('2026-07-23T12:04:59.999Z'); out=await run(db,f); assert.equal(f.posts().length,1); assert.equal(f.refreshes().length,0); assert.equal(db.jobs[0].attempt_count,1); assert.equal(db.resultUpdates,1); assert.equal(out.body.summary.retry_not_due,1); currentNow=new Date('2026-07-23T12:05:00.000Z'); f.enqueue(429,{}); out=await run(db,f); assert.equal(f.posts().length,2); assert.equal(db.jobs[0].attempt_count,2); noLeaks(db,out.body) }
{ currentNow=new Date('2026-07-23T12:00:00.000Z'); const db=new DB('throw'); const f=new FakeFetch(); f.throwNext(new Error(`${THROW_POST} ${OLD_ACCESS}`)); const out=await run(db,f); assert.equal(f.posts().length,1); assert.equal(db.jobs[0].error_code,'X_POST_OUTCOME_UNKNOWN'); assert.equal(db.jobs[0].state,'FAILED'); assert.equal(db.jobs[0].completed_at,now().toISOString()); assert.equal(db.jobs[0].next_attempt_at,null); assert.equal(db.scheduleUpdates,0); const later=await run(db,f); assert.equal(f.posts().length,1); assert.equal(later.body.summary.terminal_jobs_skipped,1); noLeaks(db,later.body) }
{ const db=new DB('missing'); const f=new FakeFetch(); f.enqueue(200,{data:{id:'   '}}); await run(db,f); assert.equal(f.posts().length,1); assert.equal(db.jobs[0].error_code,'X_POST_OUTCOME_UNKNOWN'); assert.equal(db.jobs[0].state,'FAILED'); assert.equal(db.jobs[0].platform_post_id,null); assert.equal(db.jobs[0].posted_at,null); assert.equal(db.scheduleUpdates,0); await run(db,f); assert.equal(f.posts().length,1) }
{ const db=new DB('refresh',true); const f=new FakeFetch(); f.enqueue(200,{access_token:NEW_ACCESS,token_type:'Bearer',expires_in:3600,refresh_token:'plain-local-refresh-new',scope:'tweet.write users.read'}); f.enqueue(201,{data:{id:'refresh-post-id'}}); const out=await run(db,f); assert.equal(f.refreshes().length,1); assert.equal(f.posts().length,1); const rr=f.refreshes()[0]; assert.equal(rr.method,'POST'); assert.equal(rr.contentType,'application/x-www-form-urlencoded'); assert.equal(rr.authorization,`Basic ${Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64')}`); assert.equal(rr.body.get('grant_type'),'refresh_token'); assert.equal(rr.body.get('refresh_token'),OLD_REFRESH); assert.equal(db.accounts[0].encrypted_access_token,NEW_ENC_ACCESS); assert.equal(db.accounts[0].encrypted_refresh_token,NEW_ENC_REFRESH); assert.equal(db.accounts[0].connection_status,'CONNECTED'); assert.equal(db.accounts[0].last_error,null); assert.equal(db.accounts[0].token_expires_at,'2026-07-23T13:00:00.000Z'); assert.equal(f.posts()[0].authorization,`Bearer ${NEW_ACCESS}`); assert.equal(db.jobs[0].state,'SUCCEEDED'); assert.equal(db.scheduleUpdates,1); noLeaks(db,out.body) }
{ const db=new DB('badrefresh',true); const f=new FakeFetch(); f.enqueue(200,{token_type:'Bearer',expires_in:3600}); const out=await run(db,f); assert.equal(f.refreshes().length,1); assert.equal(f.posts().length,0); assert.equal(db.accounts[0].encrypted_access_token,OLD_ENC_ACCESS); assert.equal(db.accounts[0].connection_status,'ERROR'); assert.equal(db.accounts[0].last_error,'X_REFRESH_RESPONSE_INVALID'); assert.equal(db.jobs[0].error_code,'X_REFRESH_RESPONSE_INVALID'); assert.equal(db.jobs[0].state,'SKIPPED'); assert.equal(db.jobs[0].result_status,'NOT_CONFIGURED'); assert.equal(db.jobs[0].completed_at,now().toISOString()); assert.equal(db.jobs[0].next_attempt_at,null); assert.equal(db.scheduleUpdates,0); noLeaks(db,out.body) }
{ const db=new DB('foundation'); const f=new FakeFetch(); let out=await run(db,f,{AUTOPOST_X_RUN_DISPATCH_ENABLED:'true'},'foundation=1&claim=1'); assert.equal(out.adapterCalls,0); assert.equal(f.posts().length,0); assert.equal(db.jobs[0].attempt_count,0); assert.equal(out.body.dispatch_enabled,false); assert.equal(out.body.summary.dispatches_attempted,0); assert.equal(out.body.summary.posts_attempted,0); db.jobs[0].next_attempt_at='2026-07-23T13:00:00.000Z'; db.jobs[0].locked_at=null; db.jobs[0].lock_id=null; out=await run(db,f,{AUTOPOST_X_RUN_DISPATCH_ENABLED:'false'},'dispatch=1&foundation=1'); assert.equal(out.adapterCalls,0); assert.equal(db.jobs[0].attempt_count,0); assert.equal(db.jobs[0].lock_id,null); assert.equal(db.scheduleUpdates,0) }
{ for(const [q,env,calls] of [['foundation=1',{AUTOPOST_X_RUN_DISPATCH_ENABLED:'true'},0],['dispatch=1',{AUTOPOST_X_RUN_DISPATCH_ENABLED:'false'},0],['dispatch=1',{AUTOPOST_X_RUN_DISPATCH_ENABLED:'TRUE'},0],['dispatch=1',{AUTOPOST_X_RUN_DISPATCH_ENABLED:'1'},0],['dispatch=1',{AUTOPOST_X_RUN_DISPATCH_ENABLED:'true'},1]] as any){const db=new DB(`gate${Math.random()}`); const f=new FakeFetch(); if(calls) f.enqueue(201,{data:{id:'gate-id'}}); const out=await run(db,f,env,q); assert.equal(f.posts().length,calls); assert.equal(out.body.dispatch_enabled,calls===1)} }
{ const registry=getAutopostPlatformRegistry(); const x=registry.find((p:any)=>p.id==='x'); assert.equal(x.public_selectable,false); assert.equal(x.supports_real_posting,false); assert.equal(getSelectableAutopostPlatformIds().has('x'),false); const status=buildUserPlatformStatus(x,new Map()); assert.equal(status.can_schedule,false); assert.equal(status.supports_real_posting,false); assert.equal(status.supports_text_posting,false); assert.equal(status.supports_media_posting,false) }
console.log('integrated X route/adapter/refresh/persistence/retry/schedule behavior passed using local injected fakes; local injected behavioral evidence only; no real X request occurred; no OAuth action occurred; no live token was used; no Supabase endpoint was contacted; no Vercel endpoint was contacted; no Production action occurred; no SQL ran; no Supabase CLI action occurred; no cron was added; no OnlyFans, Fanvue, Reddit, or Generate action occurred.')
