import assert from 'node:assert/strict'
import { register } from 'node:module'

process.env.SUPABASE_URL = 'http://127.0.0.1:54321'
process.env.NEXT_PUBLIC_SUPABASE_URL = 'http://127.0.0.1:54321'
process.env.SUPABASE_SERVICE_ROLE_KEY = 'dummy-service-role-key'
process.env.CRON_SECRET = 'dummy-cron-secret'
process.env.AUTOPOST_X_RUN_DISPATCH_ENABLED = 'false'

type Op = { table: string; type: string; values?: any; filters: any[]; select?: string }
class FakeQuery { table:string; type='select'; values:any; filters:any[]=[]; selectValue?:string; client:FakeSupabase; constructor(c:FakeSupabase,t:string){this.client=c;this.table=t} select(v?:string){this.selectValue=v;return this} insert(v:any){this.type='insert';this.values=v;return this} update(v:any){this.type='update';this.values=v;return this} eq(c:string,v:any){this.filters.push(['eq',c,v]);return this} is(c:string,v:any){this.filters.push(['is',c,v]);return this} not(c:string,o:string,v:any){this.filters.push(['not',c,o,v]);return this} lte(c:string,v:any){this.filters.push(['lte',c,v]);return this} or(v:string){this.filters.push(['or',v]);return this} single(){return this} maybeSingle(){return this} then(r:any,j:any){return Promise.resolve(this.client.execute(this)).then(r,j)} }
class FakeSupabase { operations:Op[]=[]; rules:any[]; jobs:any[]=[]; failResultUpdate=false; failResultLog=false; constructor(r:any[]=[]){this.rules=r} from(t:string){return new FakeQuery(this,t)} execute(q:FakeQuery){this.operations.push({table:q.table,type:q.type,values:q.values,filters:q.filters,select:q.selectValue}); if(q.table==='autopost_rules'&&q.type==='select')return{data:this.rules,error:null}; if(q.table==='autopost_rules'&&q.type==='update'){const id=filter(q,'id'); const rule=this.rules.find(r=>r.id===id); if(!rule)return{data:null,error:null}; Object.assign(rule,q.values); return{data:{id},error:null}} if(q.table==='autopost_job_logs'&&q.type==='insert')return{data:null,error:this.failResultLog&&['job_posted_proof_persisted','job_result_persisted'].includes(q.values.message)?{message:'SECRET_DB_LOG_LEAK'}:null}; if(q.table==='autopost_jobs'&&q.type==='insert'){const job={id:`job-${this.jobs.length+1}`,...q.values}; this.jobs.push(job); return{data:pickJob(job),error:null}} if(q.table==='autopost_jobs'&&q.type==='select'){const id=filter(q,'id'); const job=id?this.jobs.find(j=>j.id===id):this.jobs.find(j=>j.rule_id===filter(q,'rule_id')&&j.platform===filter(q,'platform')&&j.scheduled_for===filter(q,'scheduled_for')); return{data:job??null,error:null}} if(q.table==='autopost_jobs'&&q.type==='update'){const id=filter(q,'id'); const job=this.jobs.find(j=>j.id===id); if(this.failResultUpdate&&'result_status'in q.values)return{data:null,error:{message:'SECRET_DB_RESULT_LEAK'}}; if(!job)return{data:null,error:null}; Object.assign(job,q.values); return{data:pickJob(job),error:null}} throw new Error(`Unexpected ${q.table}.${q.type}`)} }
function filter(q:FakeQuery,c:string){return q.filters.find(f=>f[0]==='eq'&&f[1]===c)?.[2]} function pickJob(j:any){return{id:j.id,attempt_count:j.attempt_count,locked_at:j.locked_at,lock_id:j.lock_id,state:j.state}} function op(db:FakeSupabase,t:string,ty:string){return db.operations.filter(o=>o.table===t&&o.type===ty)} function logs(db:FakeSupabase,m:string){return op(db,'autopost_job_logs','insert').filter(o=>o.values.message===m)} function dueRule(id:string){return{id,user_id:`user-${id}`,approval_state:'APPROVED',enabled:true,selected_platforms:['x'],next_run_at:'2026-07-21T00:00:00.000Z',timezone:'UTC',start_date:null,end_date:null,posts_per_day:1,time_slots:['00:00'],paused_at:null,revoked_at:null,content_payload:{platform:'x',content_type:'text',media_posting_enabled:false,text:`local text ${id}`}}} function authed(url:string){return new Request(url,{headers:{authorization:'Bearer dummy-cron-secret'}})}
const loaderSource = `export async function resolve(specifier, context, nextResolve) { if (specifier === 'server-only') return { url: 'data:text/javascript,export%20{}', shortCircuit: true }; return nextResolve(specifier, context) }`
register(`data:text/javascript,${encodeURIComponent(loaderSource)}`, import.meta.url)
const { executeAutopost } = await import('../../../app/api/autopost/run/route')
const { persistAutopostJobResult } = await import('../../../lib/autopost/jobResults')

{
 const db=new FakeSupabase([dueRule('success')]); const calls:any[]=[]; const res=await executeAutopost(authed('http://local.test/api/autopost/run?execute=1'),{supabaseAdmin:db as any,cronSecret:'dummy-cron-secret',env:{AUTOPOST_X_RUN_DISPATCH_ENABLED:'true'},postXTextOnlyAutopost:async(i:any)=>{calls.push(i);return{ok:true,status:'POSTED',platform:'x',platform_post_id:'durable-local-id',posted_at:'2026-07-21T00:00:00.000Z'}}}); const body=await res.json(); assert.equal(calls.length,1,'injected X adapter is used and no real X call occurs'); assert.equal(body.summary.results_posted,1); assert.equal(db.jobs[0].platform_post_id,'durable-local-id'); assert.equal(op(db,'autopost_jobs','select').some(o=>o.select?.includes('result_status')&&o.filters.some(f=>f[1]==='id'&&f[2]==='job-1')),true,'persisted proof readback happens before schedule update'); const proof=op(db,'autopost_jobs','select').findIndex(o=>o.select?.includes('result_status')); const sched=op(db,'autopost_rules','update').length; assert.equal(sched,1); assert.ok(proof>=0); assert.equal(op(db,'autopost_rules','update')[0].filters.some(f=>f[1]==='id'&&f[2]==='success'),true); assert.equal(logs(db,'schedule_advanced').length,1)
}
{
 const db=new FakeSupabase(); db.jobs.push({id:'job-direct'}); db.failResultUpdate=true; const out=await persistAutopostJobResult(db as any,{job_id:'job-direct',now:new Date('2026-07-21T00:00:00.000Z'),adapter_result:{ok:true,status:'POSTED',platform:'x',platform_post_id:'local-failed-id',posted_at:'2026-07-21T00:00:00.000Z'}}); assert.deepEqual({ok:out.ok,job_result_persisted:out.job_result_persisted,posted:out.posted,platform_post_id:out.platform_post_id,error_code:out.error_code},{ok:false,job_result_persisted:false,posted:false,platform_post_id:null,error_code:'JOB_RESULT_PERSIST_FAILED'}); assert.equal(JSON.stringify(out).includes('SECRET_DB_RESULT_LEAK'),false)
}
{
 const db=new FakeSupabase([dueRule('fail')]); db.failResultUpdate=true; const res=await executeAutopost(authed('http://local.test/api/autopost/run?execute=1'),{supabaseAdmin:db as any,cronSecret:'dummy-cron-secret',env:{AUTOPOST_X_RUN_DISPATCH_ENABLED:'true'},postXTextOnlyAutopost:async()=>({ok:true,status:'POSTED',platform:'x',platform_post_id:'not-durable',posted_at:'2026-07-21T00:00:00.000Z'})}); const body=await res.json(); assert.equal(body.summary.results_posted,0); assert.equal(body.summary.results_failed,1); assert.equal(body.summary.result_persistence_failures,1); assert.equal(body.summary.schedule_advancements,0); assert.equal(body.summary.schedule_advancement_skipped,1); assert.equal(op(db,'autopost_jobs','select').some(o=>o.select?.includes('result_status')),false,'no persisted-proof lookup after result update failure'); assert.equal(op(db,'autopost_rules','update').length,0,'no schedule update after result update failure'); assert.equal(db.jobs[0].platform_post_id,null); assert.equal(logs(db,'schedule_advancement_skipped')[0].values.meta.reason,'JOB_RESULT_PERSIST_FAILED')
}
{
 const db=new FakeSupabase(); db.jobs.push({id:'job-log'}); db.failResultLog=true; const out=await persistAutopostJobResult(db as any,{job_id:'job-log',now:new Date('2026-07-21T00:00:00.000Z'),adapter_result:{ok:true,status:'POSTED',platform:'x',platform_post_id:'durable-with-log-fail',posted_at:'2026-07-21T00:00:00.000Z'}}); assert.equal(out.ok,true); assert.equal(out.job_result_persisted,true); assert.equal(out.audit_log_persisted,false); assert.equal(out.audit_log_error_code,'JOB_LOG_PERSIST_FAILED'); assert.equal(out.platform_post_id,'durable-with-log-fail'); assert.equal(JSON.stringify(out).includes('SECRET_DB_LOG_LEAK'),false); assert.equal(op(db,'autopost_jobs','update').length,1)
}
console.log('X job result persistence tests passed: local fakes only; no X, OAuth, Production, Supabase endpoint, Vercel, SQL, Supabase CLI, live route, adapter route, OnlyFans, Fanvue, Reddit, Generate, or real secret used')
