import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { register } from 'node:module'

process.env.SUPABASE_URL='http://127.0.0.1:54321'; process.env.NEXT_PUBLIC_SUPABASE_URL='http://127.0.0.1:54321'; process.env.SUPABASE_SERVICE_ROLE_KEY='dummy-service-role-key'; process.env.CRON_SECRET='dummy-cron-secret'

const route=readFileSync('app/api/autopost/run/route.ts','utf8')
const results=readFileSync('lib/autopost/jobResults.ts','utf8')
for (const src of [route, results]) { assert.doesNotMatch(src,/level:\s*"info"/); assert.doesNotMatch(src,/level:\s*"warn"/); assert.doesNotMatch(src,/\?\s*"info"\s*:\s*"warn"/) }
for (const m of route.matchAll(/level:\s*(?:JobLogLevel\s*=\s*)?"([A-Z]+)"/g)) assert.ok(['DEBUG','INFO','WARN','ERROR'].includes(m[1]))
for (const m of results.matchAll(/level:\s*(?:JobLogLevel\s*=\s*)?"([A-Z]+)"/g)) assert.ok(['DEBUG','INFO','WARN','ERROR'].includes(m[1]))
const migration=readFileSync('supabase/migrations/20251222_autopost_v1.sql','utf8')
assert.match(migration,/default 'INFO'/); assert.match(migration,/check \(level in \('DEBUG','INFO','WARN','ERROR'\)\)/)
execFileSync('git',['diff','--exit-code','59eae4f67a895539916f9f7603646b153ae1ede0','--','supabase/migrations/20251222_autopost_v1.sql'],{stdio:'pipe'})

type Op={table:string;type:string;values?:any;filters:any[];select?:string}
class Q{table:string;type='select';values:any;filters:any[]=[];selectValue?:string;c:DB;constructor(c:DB,t:string){this.c=c;this.table=t}select(v?:string){this.selectValue=v;return this}insert(v:any){this.type='insert';this.values=v;return this}update(v:any){this.type='update';this.values=v;return this}eq(c:string,v:any){this.filters.push(['eq',c,v]);return this}is(c:string,v:any){this.filters.push(['is',c,v]);return this}not(c:string,o:string,v:any){this.filters.push(['not',c,o,v]);return this}lte(c:string,v:any){this.filters.push(['lte',c,v]);return this}or(v:string){this.filters.push(['or',v]);return this}single(){return this}maybeSingle(){return this}then(r:any,j:any){const p=this.c.execute(this); return Promise.resolve(p).then(r,j)}}
class DB{operations:Op[]=[];jobs:any[]=[];failLogs:'none'|'error'|'reject'='none';rules=[{id:'r',user_id:'u',approval_state:'APPROVED',enabled:true,selected_platforms:['x'],next_run_at:'2026-07-21T00:00:00.000Z',timezone:'UTC',start_date:null,end_date:null,posts_per_day:1,time_slots:['00:00'],paused_at:null,revoked_at:null,content_payload:{platform:'x',content_type:'text',media_posting_enabled:false,text:'local'}}];from(t:string){return new Q(this,t)}execute(q:Q):any{this.operations.push({table:q.table,type:q.type,values:q.values,filters:q.filters,select:q.selectValue}); if(q.table==='autopost_job_logs'&&q.type==='insert'){if(this.failLogs==='reject')return Promise.reject(new Error('SUPER_SECRET_REJECTED_LOG')); if(this.failLogs==='error')return{data:null,error:{message:'SUPER_SECRET_LOG_ERROR'}}; return{data:null,error:null}} if(q.table==='autopost_rules'&&q.type==='select')return{data:this.rules,error:null}; if(q.table==='autopost_rules'&&q.type==='update')return{data:{id:'r'},error:null}; if(q.table==='autopost_jobs'&&q.type==='insert'){const job={id:'job-1',...q.values};this.jobs=[job];return{data:pick(job),error:null}} if(q.table==='autopost_jobs'&&q.type==='update'){Object.assign(this.jobs[0],q.values);return{data:pick(this.jobs[0]),error:null}} if(q.table==='autopost_jobs'&&q.type==='select')return{data:this.jobs[0]??null,error:null}; throw new Error('unexpected')}}
function pick(j:any){return{id:j.id,attempt_count:j.attempt_count,locked_at:j.locked_at,lock_id:j.lock_id,state:j.state}} function authed(){return new Request('http://local.test/api/autopost/run?execute=1',{headers:{authorization:'Bearer dummy-cron-secret'}})}
const loaderSource=`export async function resolve(specifier, context, nextResolve) { if (specifier === 'server-only') return { url: 'data:text/javascript,export%20{}', shortCircuit: true }; return nextResolve(specifier, context) }`; register(`data:text/javascript,${encodeURIComponent(loaderSource)}`, import.meta.url)
const { executeAutopost } = await import('../../../app/api/autopost/run/route')
const { persistAutopostJobResult } = await import('../../../lib/autopost/jobResults')
for (const mode of ['error','reject'] as const) { const db=new DB(); db.failLogs=mode; const res=await executeAutopost(authed(),{supabaseAdmin:db as any,cronSecret:'dummy-cron-secret',env:{AUTOPOST_X_RUN_DISPATCH_ENABLED:'true'},postXTextOnlyAutopost:async()=>({ok:true,status:'POSTED',platform:'x',platform_post_id:'durable-id',posted_at:'2026-07-21T00:00:00.000Z'})}); const body=await res.json(); assert.ok(body.summary.job_log_persistence_failures>=1); assert.equal(JSON.stringify(body).includes('SUPER_SECRET'),false) }
{ const db=new DB(); db.jobs=[{id:'job-1'}]; db.failLogs='error'; const out=await persistAutopostJobResult(db as any,{job_id:'job-1',now:new Date('2026-07-21T00:00:00.000Z'),adapter_result:{ok:true,status:'POSTED',platform:'x',platform_post_id:'durable-id',posted_at:'2026-07-21T00:00:00.000Z'}}); assert.equal(out.ok,true); assert.equal(out.job_result_persisted,true); assert.equal(out.audit_log_persisted,false); assert.equal(out.audit_log_error_code,'JOB_LOG_PERSIST_FAILED'); assert.equal(JSON.stringify(out).includes('SUPER_SECRET'),false); assert.equal(out.error_code,null) }
console.log('X job log level contract tests passed: no migration edit, SQL, Supabase CLI, Supabase, X, OAuth, Vercel, Production, or external service contacted')
