import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs"
const sql=fs.readFileSync("supabase/migrations/20260906040000_phase9_transactional_notifications.sql","utf8"),route=fs.readFileSync("app/api/internal/notifications/phase9/run/route.ts","utf8"),legacy=fs.readFileSync("app/api/admin/send-affiliate-referral-emails/route.ts","utf8")
test("outbox is unique, leased, bounded, RLS-forced, and service-role RPC only",()=>{assert.match(sql,/unique\(source_type, source_id, notification_kind\)/);assert.match(sql,/for update skip locked/i);assert.match(sql,/provider_attempt_started_at/);assert.match(sql,/prepare_phase9_notification_attempt/);assert.match(sql,/force row level security/i);assert.match(sql,/revoke all.+public,anon,authenticated/is);assert.match(sql,/grant execute.+service_role/is);assert.doesNotMatch(sql,/grant (insert|update|delete).+authenticated/is)})
test("all authoritative due markers are consumed and stale states revalidated",()=>{for(const marker of ["ready_notification_due_at","requested_notification_due_at","reactivated_notification_due_at","completed_notification_due_at","day_0_notification_due_at","day_30_notification_due_at","day_45_notification_due_at","day_55_notification_due_at"])assert.match(sql,new RegExp(marker));assert.match(sql,/source_stale/);assert.match(sql,/state in \('retention_countdown','expired'\)/)})
test("scheduler is authenticated and default-off; legacy route stays 404",()=>{assert.match(route,/authenticateSchedulerRequest/);assert.match(route,/notificationsEnabled/);assert.match(route,/createResendTransport/);assert.match(legacy,/404/);assert.doesNotMatch(route,/request\.json|searchParams/)})
test("materialization excludes existing identities before its bounded selection",()=>{const exclusion=sql.indexOf("not exists ("),limit=sql.indexOf("limit p_limit");assert.ok(exclusion>0&&limit>exclusion);assert.match(sql,/n\.source_type=c\.source_type and n\.source_id=c\.source_id and n\.notification_kind=c\.kind/)})
test("Phase 9 contains no obsolete production domain",()=>{for(const path of ["lib/notifications/templates.ts","docs/operations/phase9-notifications-closeout.md"])assert.doesNotMatch(fs.readFileSync(path,"utf8"),/sirensforge\.com/)})
test("outbox evidence cannot block authoritative Auth account deletion",()=>{assert.doesNotMatch(sql,/auth_user_id uuid not null references auth\.users/)})
test("deletion completion due marker uses durable purge completion evidence",()=>{assert.match(sql,/new\.completed_notification_due_at:=new\.purge_completed_at/);assert.match(sql,/set completed_notification_due_at=purge_completed_at/);assert.doesNotMatch(sql,/completed_notification_due_at=clock_timestamp/)})
