import test from "node:test"; import assert from "node:assert/strict"
import {notificationsEnabled,runNotifications} from "../../../lib/notifications/service"; import {buildNotification} from "../../../lib/notifications/templates"; import {createResendTransport} from "../../../lib/notifications/resend"; import {notificationKinds} from "../../../lib/notifications/types"
test("delivery is exact-default-off and missing transport config fails closed",()=>{assert.equal(notificationsEnabled({} as NodeJS.ProcessEnv),false);assert.equal(notificationsEnabled({PHASE9_NOTIFICATIONS_ENABLED:"TRUE"} as NodeJS.ProcessEnv),false);assert.equal(notificationsEnabled({PHASE9_NOTIFICATIONS_ENABLED:"true"} as NodeJS.ProcessEnv),true);assert.throws(()=>createResendTransport({} as NodeJS.ProcessEnv),/NOTIFICATION_TRANSPORT_NOT_CONFIGURED/)})
test("all twelve centralized templates have safe HTML and text",()=>{for(const kind of notificationKinds){const mail=buildNotification(kind,{expiresAt:"2026-10-01T00:00:00Z",recoveryDeadline:"2026-11-01T00:00:00Z",completedAt:"2026-09-01T00:00:00Z",paidAccessEndsAt:"2026-09-01T00:00:00Z",retentionUntil:"2026-11-01T00:00:00Z",retentionStartedAt:"2026-09-01T00:00:00Z"});assert.ok(mail.subject);assert.match(mail.text,/transactional account notice/);assert.match(mail.html,/sirensforge\.com/);assert.doesNotMatch(mail.text,/uuid|provider|guarantee/i)}})
const row={id:"n1",source_type:"creator_data_export",source_id:"s1",notification_kind:"export_ready",auth_user_id:"u1",due_at:"2026-09-01",attempts:1,context:{expiresAt:"2026-10-01T00:00:00Z"}}
function db(rows:any[],user:any={id:"u1",email:"creator@example.test"}){const calls:any[]=[];return {calls,auth:{admin:{getUserById:async()=>({data:{user},error:null})}},rpc:async(name:string,args:any)=>{calls.push([name,args]);if(name==="materialize_phase9_notifications")return{data:1,error:null};if(name==="claim_phase9_notifications")return{data:rows,error:null};return{data:true,error:null}}}}
test("behavior delivers once using authoritative recipient and sanitized log",async()=>{const d=db([row]);let sent:any,logged:any;const result=await runNotifications({db:d as any,transport:{send:async x=>(sent=x,{kind:"delivered",providerMessageId:"provider-secret-id"})},log:e=>logged=e});assert.equal(sent.to,"creator@example.test");assert.equal(sent.idempotencyKey,"phase9/n1");assert.deepEqual(result,{materialized:1,claimed:1,delivered:1,retried:0,suppressed:0,uncertain:0});assert.equal(JSON.stringify(logged).includes("creator@example"),false);const final=d.calls.at(-1)[1];assert.equal(final.p_outcome,"delivered");assert.match(final.p_provider_message_id_hash,/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(final).includes("provider-secret-id"),false)})
test("retryable, uncertain, and invalid recipients finalize safely",async()=>{for(const [transport,user,outcome] of [[{send:async()=>({kind:"retry",code:"X"})},{id:"u1",email:"a@b.test"},"retry"],[{send:async()=>({kind:"uncertain",code:"X"})},{id:"u1",email:"a@b.test"},"failed_uncertain"],[{send:async()=>{throw new Error("must not send")}},null,"suppressed"]] as any[]){const d=db([row],user);await runNotifications({db:d as any,transport});assert.equal(d.calls.at(-1)[1].p_outcome,outcome)}})
test("an empty claim (including disabled scheduler behavior) never invokes transport",async()=>{const d=db([]);let sends=0;await runNotifications({db:d as any,transport:{send:async()=>{sends++;return{kind:"delivered",providerMessageId:"x"}}}});assert.equal(sends,0)})
