import { strict as assert } from "node:assert"
import { readFileSync, existsSync, readdirSync } from "node:fs"
import test from "node:test"
import { normalizeAutopostPlanRequest, AUTOPOST_PROTECTED_REQUEST_FIELDS } from "../../../lib/creator-publishing-queue/autopost/validation"
import { aggregateAutopostPlanStatus, isAutopostJobSourceCurrent } from "../../../lib/creator-publishing-queue/autopost/aggregation"
const migrationPath="supabase/migrations/20260711001200_creator_publishing_autopost_orchestration.sql"
const migration=readFileSync(migrationPath,"utf8")
const pkg=readFileSync("package.json","utf8")
const files=()=>readdirSync("supabase/migrations").filter(f=>f.includes("creator_publishing"))
test("Task 14 migration adds platform-neutral plan/job schema without replacing package composer or queue",()=>{
  assert.equal(existsSync(migrationPath),true)
  assert.equal(files().filter(f=>f.includes("001200")||f.includes("01200")).length,1)
  for(const n of ["00100","00200","00300","00400","00500","00600","00700","00800","00900","01000","01100"]) assert.equal(files().some(f=>f.includes(n)),true)
  assert.match(migration,/create table if not exists public\.creator_publishing_plans/)
  assert.match(migration,/create table if not exists public\.creator_publishing_platform_jobs/)
  assert.match(migration,/content_package_id uuid not null/)
  assert.match(migration,/references public\.creator_publishing_content_packages|creator_publishing_jobs_package_creator_account_platform_fk/)
  assert.equal(migration.includes("creator_publishing_save_content_package"),false)
  assert.equal(migration.includes("insert into public.creator_publishing_queue_tasks"),false)
  assert.equal(migration.includes("update public.creator_publishing_queue_tasks"),false)
  assert.equal(migration.includes("create table if not exists public.creator_publishing_queue_tasks"),false)
})
test("database constraints enforce ownership/platform consistency, uniqueness, active conflicts, RLS, service-role RPC, and safe registry",()=>{
  assert.match(migration,/creator_publishing_platform_capabilities/)
  assert.match(migration,/canonical Task 14 server-controlled Creator Publishing capability registry/i)
  assert.match(migration,/creator_publishing_platform_capability_public/)
  assert.match(migration,/platform_supports_native_scheduling/)
  assert.match(migration,/connector_can_schedule_directly/)
  assert.doesNotMatch(migration,/supportsScheduledPublish/)
  assert.match(migration,/'onlyfans'[^;]+'assisted'[^;]+'available'/s)
  assert.match(migration,/human_publishing_required[^\n]+default false/)
  assert.match(migration,/'fansly'[^;]+'disabled'[^;]+'unassigned'/s)
  assert.match(migration,/'fanvue'[^;]+'disabled'[^;]+'frozen'/s)
  assert.match(migration,/creator_publishing_jobs_plan_package_unique unique \(publishing_plan_id, content_package_id\)/)
  assert.match(migration,/creator_publishing_jobs_plan_account_unique unique \(publishing_plan_id, platform_account_id\)/)
  assert.match(migration,/creator_publishing_jobs_active_package_uidx[\s\S]+where job_state not in/)
  assert.match(migration,/foreign key \(publishing_plan_id, creator_id\)/)
  assert.match(migration,/foreign key \(content_package_id, creator_id, platform_account_id, target_platform\)/)
  assert.match(migration,/foreign key \(platform_account_id, creator_id, target_platform\)/)
  assert.match(migration,/target_platform <> 'fanvue'/)
  assert.match(migration,/alter table public\.creator_publishing_plans enable row level security/)
  assert.match(migration,/for select using \(auth\.uid\(\) = creator_id\)/)
  assert.match(migration,/revoke execute on function public\.creator_publishing_create_autopost_plan[\s\S]+from public, anon, authenticated/)
  assert.match(migration,/grant execute[\s\S]+to service_role/)
})
test("trusted RPC documents minimal atomic creation, idempotency, generated-media provenance, audits, and no queue false conflict",()=>{
  assert.match(migration,/p_content_package_ids uuid\[\]/)
  assert.match(migration,/p_idempotency_key text/)
  assert.match(migration,/pg_advisory_xact_lock/)
  assert.match(migration,/jsonb_build_object\('creator_id',p_creator_id,'content_package_ids'/)
  for(const f of ["platform_account_ids","target_platforms","source_package_versions","publishing_modes","registry_version"]) assert.match(migration,new RegExp(f))
  assert.match(migration,/request_fingerprint text not null/)
  assert.match(migration,/source_package_updated_at timestamptz not null/)
  assert.match(migration,/if v_existing\.request_fingerprint <> v_fingerprint then raise exception 'IDEMPOTENCY_CONFLICT'/)
  assert.match(migration,/return jsonb_build_object\('plan',to_jsonb\(v_existing\)/)
  assert.equal((migration.match(/insert into public\.creator_publishing_audit_events/g)||[]).length,2)
  assert.match(migration,/creator_publishing_plan_created/)
  assert.match(migration,/creator_publishing_platform_job_created/)
  assert.match(migration,/source <> 'ai_pipeline'/)
  assert.match(migration,/ai_generation_metadata \? 'generation_id'/)
  assert.match(migration,/ACTIVE_PUBLICATION_JOB_CONFLICT/)
  assert.equal(migration.includes("creator_publishing_queue_tasks where content_package_id"),false)
})
test("Task 14 states start draft and future states are only reserved with deterministic aggregation",()=>{
  assert.match(migration,/status text not null default 'draft'/)
  assert.match(migration,/job_state text not null default 'draft'/)
  assert.match(migration,/values\(v_plan\.id,p_creator_id[\s\S]+'draft'/)
  assert.match(migration,/Other constrained values are reserved for future Tasks 15-17/)
  assert.match(migration,/creator_publishing_aggregate_plan_status/)
  assert.equal(aggregateAutopostPlanStatus(["draft","draft"]),"draft")
  assert.equal(aggregateAutopostPlanStatus(["scheduled_internally","scheduled_on_platform"]),"scheduled")
  assert.equal(aggregateAutopostPlanStatus(["publishing_direct","draft"]),"in_progress")
  assert.equal(aggregateAutopostPlanStatus(["published_direct","draft"]),"partially_published")
  assert.equal(aggregateAutopostPlanStatus(["published_direct","confirmed_posted_manual"]),"completed")
  assert.equal(aggregateAutopostPlanStatus(["published_direct","failed_manual_upload"]),"completed_with_failures")
  assert.equal(aggregateAutopostPlanStatus(["draft"],"cancelled"),"cancelled")
  assert.equal(isAutopostJobSourceCurrent({source_package_updated_at:"2026-01-01T00:00:00Z"},{updated_at:"2026-01-01T00:00:00Z"}),true)
  assert.equal(isAutopostJobSourceCurrent({source_package_updated_at:"old"},{updated_at:"new"}),false)
})
test("minimal browser request parsing rejects trusted browser copies and normalizes sorted IDs",()=>{
  const ids=["00000000-0000-4000-8000-000000000002","00000000-0000-4000-8000-000000000001","00000000-0000-4000-8000-000000000001"]
  assert.deepEqual(normalizeAutopostPlanRequest({contentPackageIds:ids,idempotencyKey:"abcDEF_123"}).contentPackageIds,["00000000-0000-4000-8000-000000000001","00000000-0000-4000-8000-000000000002"])
  for(const field of AUTOPOST_PROTECTED_REQUEST_FIELDS) assert.throws(()=>normalizeAutopostPlanRequest({contentPackageIds:ids,idempotencyKey:"abcDEF_123",[field]:"forged"}))
  assert.throws(()=>normalizeAutopostPlanRequest({contentPackageIds:ids,idempotencyKey:"bad space"}))
  assert.throws(()=>normalizeAutopostPlanRequest({contentPackageIds:["not-a-uuid"],idempotencyKey:"abcDEF_123"}))
})
test("Task 14 UI/API integration is minimal and routes through trusted service",()=>{
  assert.match(pkg,/autopostOrchestration\.test\.ts/)
  const page=readFileSync("app/autopost/page.tsx","utf8")
  const component=readFileSync("app/autopost/Task14AutopostOrchestration.tsx","utf8")
  const service=readFileSync("lib/creator-publishing-queue/autopost/service.ts","utf8")
  assert.match(page,/Task14AutopostOrchestration/)
  assert.match(component,/contentPackageIds:selected,idempotencyKey/)
  assert.match(component,/Select authoritative destination-specific content packages/)
  assert.match(component,/captions, media, pricing, visibility, disclosure, compliance, approval, and routing are loaded from trusted server state/)
  assert.match(service,/\.rpc\("creator_publishing_create_autopost_plan"/)
  for(const forbidden of ["OnlyFans API","One-click publish to OnlyFans","Direct OnlyFans integration","Autoposts to OnlyFans","Auto-publishes to OnlyFans"]) assert.equal(component.includes(forbidden),false)
})
test("safety source checks: no credentials/platform calls/uploads/Fanvue production/scheduler/operator implementation",()=>{
  for(const forbidden of ["fetch(\"https://onlyfans","fetch(\"https://fansly","fetch(\"https://fanvue","proxy","browser automation","proof_screenshot_storage_key","local file","camera_upload", "cron"]) assert.equal(migration.toLowerCase().includes(forbidden.toLowerCase()), false, forbidden)
  assert.equal(migration.includes("autopost_accounts"),false)
  assert.equal(migration.includes("fanvueApiClient"),false)
})
