import assert from 'node:assert/strict'
import { executePreparedFanvuePublication, type PreparedFanvueExecutionEnvelope } from '../../../lib/creator-publishing-queue/fanvue/executor'
import type { FanvueFetch } from '../../../lib/autopost/fanvueApiClientCore'

const creatorId='879c8a17-f9e8-473d-8de1-1fd1a77c080e', destinationId='123e4567-e89b-42d3-a456-426614174000', accountId='223e4567-e89b-42d3-a456-426614174000', postUuid='523e4567-e89b-42d3-a456-426614174000'
const now=new Date('2026-08-14T00:00:00Z'), fresh=new Date(now.getTime()+3600000).toISOString(), stale=new Date(now.getTime()-3600000).toISOString()
const cipher='ciphertext-must-not-leak', refreshCipher='refresh-ciphertext-must-not-leak', token='plaintext-token-must-not-leak'

function envelope(overrides: any={}): PreparedFanvueExecutionEnvelope {
  const calls=overrides.calls as any[]|undefined
  const fanvueFetch: FanvueFetch=overrides.fanvueFetch ?? (async (url,init)=>{ calls?.push({url,init}); return {ok:true,status:200,json:async()=>({uuid:postUuid})} })
  return {
    creatorId,
    destination:{id:destinationId,creator_id:creatorId,platform:'fanvue',oauth_account_id:accountId},
    oauthAccount:{id:accountId,user_id:creatorId,platform:'fanvue',connection_status:'CONNECTED',encrypted_access_token:cipher,encrypted_refresh_token:refreshCipher,token_expires_at:fresh,scopes:['read:media','write:media','write:creator']},
    approvedContent:{platform:'fanvue',content_type:'text',text:'Approved caption'},
    provider:{apiBaseUrl:'https://api.test.fanvue.example',apiVersion:'2025-01-01',fanvueFetch,fetchIdentity:async()=>({ok:true,status:200,json:async()=>({uuid:'423e4567-e89b-42d3-a456-426614174000',isCreator:true})}),signedPartUploader:async()=>({ETag:'etag'}),decryptAccessToken:()=>token,now:()=>now},
    ...overrides,
  } as PreparedFanvueExecutionEnvelope
}
function safe(result: unknown){const value=JSON.stringify(result); for(const secret of [cipher,refreshCipher,token,'Authorization','Bearer']) assert.equal(value.includes(secret),false)}

async function run(){
  const calls:any[]=[]; const text=await executePreparedFanvuePublication(envelope({calls})); assert.equal(text.ok,true); assert.equal(text.provider_post_uuid,postUuid); assert.equal(calls.length,1); assert.deepEqual(JSON.parse(calls[0].init.body),{text:'Approved caption',audience:'subscribers'}); assert.equal(calls[0].init.body.includes('publishAt'),false); assert.equal(text.publishAt_used,false); assert.equal(text.schedule_attempted,false); assert.equal(text.dispatch_attempted,false); safe(text)
  const mediaCalls:any[]=[]; const mediaUuid='623e4567-e89b-42d3-a456-426614174000', uploadId='723e4567-e89b-42d3-a456-426614174000'; let readiness:any=null, uploads=0
  const mediaEnvelope=envelope(); (mediaEnvelope.approvedContent as any)={platform:'fanvue',content_type:'media',text:'Approved media',media:{filename:'approved.png',mediaType:'image',bytes:new Blob(['bytes'])}}; (mediaEnvelope.provider as any).fanvueFetch=async(url:string,init:any)=>{mediaCalls.push({url,init}); if(/media\/uploads$/.test(url))return {ok:true,status:200,json:async()=>({mediaUuid,uploadId})}; if(/parts\/1\/url$/.test(url))return {ok:true,status:200,json:async()=>'https://signed.test/part'}; if(init.method==='PATCH')return {ok:true,status:200,json:async()=>({status:'processing'})}; return {ok:true,status:200,json:async()=>({uuid:postUuid})}}; (mediaEnvelope.provider as any).signedPartUploader=async()=>{uploads++;return {ETag:'etag'}}; (mediaEnvelope.provider as any).waitForMediaReady=async(_config:any,args:any)=>{readiness=args;return {ok:true,media:{uuid:args.uuid,status:'ready'},attempts:1,proof:'MEDIA_READY_READBACK'}}
  const media=await executePreparedFanvuePublication(mediaEnvelope); assert.equal(media.ok,true); assert.equal(uploads,1); assert.equal(readiness.uuid,mediaUuid); assert.equal(mediaCalls.length,4); assert.equal(media.publishAt_used,false); assert.equal(media.schedule_attempted,false); assert.equal(media.dispatch_attempted,false)
  const videoEnvelope=envelope(); (videoEnvelope.approvedContent as any)={platform:'fanvue',content_type:'media',media:{filename:'approved.mp4',mediaType:'video',bytes:new Blob(['video'])}}; let videoReadiness:any=null; Object.assign(videoEnvelope.provider,(mediaEnvelope as any).provider,{waitForMediaReady:async(_config:any,args:any)=>{videoReadiness=args;return {ok:true,media:{uuid:args.uuid,status:'ready'},attempts:2,proof:'MEDIA_READY_READBACK'}}}); assert.equal((await executePreparedFanvuePublication(videoEnvelope)).ok,true); assert.ok(videoReadiness.maxAttempts>readiness.maxAttempts)
  const missing=await executePreparedFanvuePublication(envelope({fanvueFetch:async()=>({ok:true,status:200,json:async()=>({})})})); assert.equal(missing.ok,false); assert.equal(missing.safe_code,'FANVUE_EXECUTION_PROVIDER_POST_UUID_INVALID'); assert.equal(missing.provider_post_uuid_present,false); assert.equal(missing.provider_post_uuid,null)
  const malformedText=await executePreparedFanvuePublication(envelope({fanvueFetch:async()=>({ok:true,status:200,json:async()=>({uuid:'not-a-valid-uuid'})})})); assert.equal(malformedText.ok,false); assert.equal(malformedText.safe_code,'FANVUE_EXECUTION_PROVIDER_POST_UUID_INVALID'); assert.equal(malformedText.provider_post_uuid_present,false); assert.equal(malformedText.provider_post_uuid,null); safe(malformedText)
  const malformedMediaEnvelope=envelope(); (malformedMediaEnvelope.approvedContent as any)=(mediaEnvelope as any).approvedContent; Object.assign(malformedMediaEnvelope.provider,(mediaEnvelope as any).provider,{fanvueFetch:async(url:string,init:any)=>{if(/media\/uploads$/.test(url))return {ok:true,status:200,json:async()=>({mediaUuid,uploadId})}; if(/parts\/1\/url$/.test(url))return {ok:true,status:200,json:async()=>'https://signed.test/part'}; if(init.method==='PATCH')return {ok:true,status:200,json:async()=>({status:'processing'})}; return {ok:true,status:200,json:async()=>({uuid:'not-a-valid-uuid'})}}}); const malformedMedia=await executePreparedFanvuePublication(malformedMediaEnvelope); assert.equal(malformedMedia.ok,false); assert.equal(malformedMedia.safe_code,'FANVUE_EXECUTION_PROVIDER_POST_UUID_INVALID'); assert.equal(malformedMedia.provider_post_uuid_present,false); assert.equal(malformedMedia.provider_post_uuid,null); safe(malformedMedia)
  let identityUploads=0; const identityFailure=envelope(); (identityFailure.approvedContent as any)=(mediaEnvelope as any).approvedContent; (identityFailure.provider as any).fetchIdentity=async()=>{throw new Error(token)}; (identityFailure.provider as any).fanvueFetch=async()=>{identityUploads++; throw new Error('must not execute')}; const identityResult=await executePreparedFanvuePublication(identityFailure); assert.equal(identityResult.ok,false); assert.equal(identityResult.safe_code,'FANVUE_EXECUTION_CREATOR_IDENTITY_NETWORK_FAILED'); assert.equal(identityUploads,0); assert.equal(identityResult.upload_attempted,false); assert.equal(identityResult.create_attempted,false); safe(identityResult)
  for(const status of [400,500]) { const result=await executePreparedFanvuePublication(envelope({fanvueFetch:async()=>({ok:false,status,json:async()=>({secret:token})})})); assert.equal(result.ok,false); assert.equal(result.create_status_class,status===400?'4xx':'5xx'); safe(result) }
  const network=await executePreparedFanvuePublication(envelope({fanvueFetch:async()=>{throw new Error(token)}})); assert.equal(network.ok,false); assert.equal(network.create_status_class,'unknown'); safe(network)
  const disconnected=envelope(); (disconnected.oauthAccount as any).connection_status='DISCONNECTED'; assert.equal((await executePreparedFanvuePublication(disconnected)).safe_code,'FANVUE_EXECUTION_CONNECTED_ACCOUNT_REQUIRED')
  const mismatch=envelope(); (mismatch.destination as any).creator_id='other'; assert.equal((await executePreparedFanvuePublication(mismatch)).safe_code,'FANVUE_CPQ_DESTINATION_ACCOUNT_MISMATCH')
  const wrongPlatform=envelope(); (wrongPlatform.destination as any).platform='x'; assert.equal((await executePreparedFanvuePublication(wrongPlatform)).safe_code,'FANVUE_CPQ_PLATFORM_INVALID')
  const noToken=envelope(); (noToken.oauthAccount as any).encrypted_access_token=null; assert.equal((await executePreparedFanvuePublication(noToken)).safe_code,'FANVUE_EXECUTION_CONNECTED_ACCOUNT_REQUIRED')
  const noRefresh=envelope(); Object.assign(noRefresh.oauthAccount,{token_expires_at:stale,encrypted_refresh_token:null}); assert.equal((await executePreparedFanvuePublication(noRefresh)).safe_code,'FANVUE_REFRESH_TOKEN_MISSING')
  let refreshed=0; const refresh=envelope(); Object.assign(refresh.oauthAccount,{token_expires_at:stale}); (refresh.provider as any).refreshAccessToken=async()=>{refreshed++;return {ok:true,refreshed:true,token_expires_at:fresh,token_type:'bearer',scopes:[]}}; (refresh.provider as any).reloadAccountAfterRefresh=async()=>({...refresh.oauthAccount,token_expires_at:fresh,encrypted_access_token:'new-cipher'}); assert.equal((await executePreparedFanvuePublication(refresh)).ok,true); assert.equal(refreshed,1)
  const decrypt=envelope(); (decrypt.provider as any).decryptAccessToken=()=>{throw new Error(cipher)}; const decryptResult=await executePreparedFanvuePublication(decrypt); assert.equal(decryptResult.safe_code,'FANVUE_EXECUTION_TOKEN_DECRYPT_FAILED'); safe(decryptResult)
  const scopes=envelope(); (scopes.oauthAccount as any).scopes=[]; (scopes.approvedContent as any)={platform:'fanvue',content_type:'media',media:{filename:'a.png',mediaType:'image',bytes:new Blob(['x'])}}; assert.equal((await executePreparedFanvuePublication(scopes)).safe_code,'FANVUE_EXECUTION_REQUIRED_SCOPES_MISSING')
}
run().then(()=>console.log('CPQ Fanvue executor tests passed')).catch(e=>{console.error(e);process.exit(1)})
