import { strict as assert } from "node:assert"
import { readFileSync } from "node:fs"
import test from "node:test"

const activation=readFileSync("supabase/migrations/20260817170000_cpq_fanvue_public_activation.sql","utf8")
const factsMigration=readFileSync("supabase/migrations/20260817170050_cpq_fanvue_direct_compliance_facts.sql","utf8")
const complianceMigration=readFileSync("supabase/migrations/20260817170100_cpq_fanvue_direct_compliance_approval.sql","utf8")
const hardening=readFileSync("supabase/migrations/20260817170200_cpq_fanvue_direct_preparation_hardening.sql","utf8")
const personaCorrection=readFileSync("supabase/migrations/20260818164748_cpq_fanvue_ai_persona_policy_correction.sql","utf8")
const personaRollback=readFileSync("supabase/manual/cpq_fanvue_ai_persona_policy_correction_rollback.sql","utf8")
const rollback=readFileSync("supabase/manual/cpq_fanvue_public_activation_rollback.sql","utf8")
const registry=readFileSync("lib/autopost/platformRegistry.ts","utf8")
const autopostService=readFileSync("lib/creator-publishing-queue/autopost/service.ts","utf8")
const directPreparation=readFileSync("lib/creator-publishing-queue/fanvue/directPreparation.ts","utf8")
const directCompliance=readFileSync("lib/creator-publishing-queue/fanvue/directCompliance.ts","utf8")
const schedulingService=readFileSync("lib/creator-publishing-queue/scheduling/service.ts","utf8")
const directScheduling=readFileSync("lib/creator-publishing-queue/scheduling/fanvueDirect.ts","utf8")
const schedulingUi=readFileSync("app/autopost/Task15PlanScheduling.tsx","utf8")
const workerRoute=readFileSync("app/api/creator-publishing-queue/fanvue/run/route.ts","utf8")
const workerRuntime=readFileSync("lib/creator-publishing-queue/fanvue/workerRuntime.ts","utf8")
const envExample=readFileSync(".env.example","utf8")
const vercel=readFileSync("vercel.json","utf8")

test("activation publishes coherent Fanvue direct capability and backfills only missing OAuth destinations",()=>{
 assert.match(activation,/registry_version = 'task14\.20260817\.002'/)
 assert.match(activation,/where platform = 'fanvue'/)
 assert.match(activation,/publishing_mode = 'direct'/)
 assert.match(activation,/availability_status = 'available'/)
 assert.match(activation,/connector_can_publish_immediately = true/)
 assert.match(activation,/connector_can_upload_media = true/)
 assert.match(activation,/connector_can_schedule_directly = false/)
 assert.match(activation,/human_publishing_required = false/)
 assert.match(activation,/from public\.autopost_accounts a/)
 assert.match(activation,/a\.connection_status = 'CONNECTED'/)
 assert.match(activation,/not exists \([\s\S]*?public\.creator_platform_accounts d[\s\S]*?d\.oauth_account_id = a\.id/)
 assert.match(activation,/credentials_mutated', false/)
 assert.doesNotMatch(activation,/update public\.autopost_accounts/)
 assert.doesNotMatch(activation,/fetch\s*\(|fanvueFetch|createFanvueTextPost|createFanvueMediaPost|signedUrl/i)
})

test("dedicated Fanvue plan creator is service-role only and server-derives execution fields",()=>{
 assert.match(activation,/create or replace function public\.creator_publishing_create_fanvue_autopost_plan/)
 assert.match(activation,/security definer/)
 assert.match(activation,/set search_path = public, pg_temp/)
 for(const field of ["oauth_account_id","publication_type","server_idempotency_key"]) assert.match(activation,new RegExp(field))
 assert.match(activation,/grant execute on function public\.creator_publishing_create_fanvue_autopost_plan\([^;]+\) to service_role/)
 assert.match(activation,/revoke execute on function public\.creator_publishing_create_fanvue_autopost_plan\([^;]+\) from authenticated/)
 assert.match(activation,/revoke execute on function public\.creator_publishing_create_fanvue_autopost_plan\([^;]+\) from anon/)
})

test("Fanvue trusted facts are isolated from legacy compliance and support text-only packages",()=>{
 assert.match(factsMigration,/creator_publishing_build_fanvue_direct_compliance_facts/)
 assert.match(factsMigration,/creator_publishing_load_fanvue_direct_compliance_facts/)
 assert.match(factsMigration,/if v_media_count>1 then raise exception 'FANVUE_COMPLIANCE_MEDIA_INVALID'/)
 assert.match(factsMigration,/if v_media_count=0 then/)
 assert.match(factsMigration,/FANVUE_COMPLIANCE_TEXT_REQUIRED/)
 assert.match(factsMigration,/oauth_destination_verified',true/)
 assert.doesNotMatch(factsMigration,/create or replace function public\.creator_publishing_build_compliance_facts/)
 assert.doesNotMatch(factsMigration,/create or replace function public\.creator_publishing_load_compliance_facts/)
})

test("Fanvue direct compliance and approval stay outside the manual operator queue",()=>{
 assert.match(complianceMigration,/creator_publishing_apply_fanvue_direct_compliance/)
 assert.match(complianceMigration,/creator_publishing_approve_fanvue_direct_package/)
 assert.match(complianceMigration,/queue_task_created',false/)
 assert.match(complianceMigration,/FANVUE_APPROVAL_CREATOR_NOT_VERIFIED/)
 assert.match(complianceMigration,/FANVUE_APPROVAL_AI_TWIN_CONSENT_REQUIRED/)
 assert.match(complianceMigration,/review_source='automated'/)
 assert.doesNotMatch(complianceMigration,/insert into public\.creator_publishing_queue_tasks/i)
 assert.doesNotMatch(complianceMigration,/create or replace function public\.creator_publishing_apply_creator_approval_decision/)
})

test("hardening binds compliance to Fanvue facts and database rejects unprepared Fanvue jobs",()=>{
 assert.match(hardening,/creator_publishing_build_fanvue_direct_compliance_facts/)
 assert.doesNotMatch(hardening,/v_facts:=public\.creator_publishing_build_compliance_facts/)
 assert.match(hardening,/creator_publishing_fanvue_job_insert_guard/)
 assert.match(hardening,/before insert on public\.creator_publishing_platform_jobs/)
 assert.match(hardening,/creator_approval_status<>'approved'/)
 assert.match(hardening,/compliance_status<>'passed'/)
 assert.match(hardening,/v_verification\.status<>'verified'/)
 assert.match(hardening,/v_consent\.status<>'granted'/)
 assert.match(hardening,/FANVUE_JOB_TRUST_GATE_FAILED/)
})


test("Fanvue AI-persona correction is forward-only, V2-bound, and preserves every trust gate",()=>{
 assert.match(personaCorrection,/platform_requires_ai_disclosure = true/)
 assert.match(personaCorrection,/platform_blocks_fictional_personas = false/)
 assert.doesNotMatch(personaCorrection,/registry_version\s*=/)
 assert.match(personaCorrection,/creator_publishing_approve_fanvue_direct_package/)
 assert.match(personaCorrection,/creator_publishing_fanvue_job_insert_guard/)
 assert.match(personaCorrection,/creator-ai-content-persona-consent-v2/g)
 assert.match(personaCorrection,/b6c9ee005f1800b0cf41757592f846a97b4a28843bbee8abe0cb0997a47b760d/g)
 assert.doesNotMatch(personaCorrection,/creator-ai-twin-consent-v1|0c36baeb6477f36caa583cc46dd204cad4b5b57f0bd9c34779b0a14672b5de12/)
 for(const gate of ["security definer","set search_path = public, pg_temp","FANVUE_APPROVAL_STALE","FANVUE_APPROVAL_EVIDENCE_REQUIRED","FANVUE_APPROVAL_DESTINATION_INVALID","write:post","FANVUE_APPROVAL_CREATOR_NOT_VERIFIED","FANVUE_APPROVAL_MEDIA_INVALID","FANVUE_JOB_TRUST_GATE_FAILED"]) assert.match(personaCorrection,new RegExp(gate.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))
 const executableCorrection=personaCorrection.replace(/^--.*$/gm,"")
 assert.doesNotMatch(executableCorrection,/fetch\s*\(|createFanvue|creator_publishing_schedule_plan|insert into public\.creator_publishing_(scheduler_events|fanvue_attempts|platform_jobs)/i)
 assert.match(personaRollback,/publishing_mode = 'disabled'/)
 assert.match(personaRollback,/availability_status = 'frozen'/)
 assert.match(personaRollback,/drop function if exists public\.creator_publishing_approve_fanvue_direct_package/)
 assert.match(personaRollback,/drop function if exists public\.creator_publishing_fanvue_job_insert_guard/)
 assert.doesNotMatch(personaRollback,/delete\s+from|update public\.autopost_accounts|insert into public\.creator_publishing_(platform_jobs|fanvue_attempts|scheduler_events)/i)
})

test("launch-facing Fanvue consent wording no longer calls the current contract AI Twin consent",()=>{
 assert.doesNotMatch(autopostService,/Grant the current AI Twin consent/)
 assert.match(autopostService,/Grant the current AI content & persona consent before creating a Fanvue direct plan/)
})

test("server preparation orders trusted facts, compliance, approval, then plan creation",()=>{
 assert.match(autopostService,/prepareFanvueDirectPackage/)
 const prep=autopostService.indexOf("await prepareFanvueDirectPackage")
 const create=autopostService.indexOf('client.rpc("creator_publishing_create_fanvue_autopost_plan"')
 assert(prep>0&&create>prep)
 const load=directPreparation.indexOf('client.rpc("creator_publishing_load_fanvue_direct_compliance_facts"')
 const apply=directPreparation.indexOf('client.rpc("creator_publishing_apply_fanvue_direct_compliance"')
 const approve=directPreparation.indexOf('client.rpc("creator_publishing_approve_fanvue_direct_package"')
 assert(load>0&&apply>load&&approve>apply)
 assert.match(directPreparation,/subKey\("fvcomp"/)
 assert.match(directPreparation,/subKey\("fvappr"/)
 assert.match(directPreparation,/evaluation\.outcome!=="passed"/)
 assert.match(directCompliance,/policy_mode:"direct_api"/)
 assert.match(directCompliance,/queue_enabled:false/)
 assert.match(directCompliance,/fanvue-ai-twin-consent-missing/)
})

test("rollback freezes Fanvue and removes only activation surfaces without deleting persisted data",()=>{
 assert.match(rollback,/publishing_mode = 'disabled'/)
 assert.match(rollback,/availability_status = 'frozen'/)
 for(const surface of ["creator_publishing_create_fanvue_autopost_plan","creator_publishing_approve_fanvue_direct_package","creator_publishing_apply_fanvue_direct_compliance","creator_publishing_load_fanvue_direct_compliance_facts","creator_publishing_build_fanvue_direct_compliance_facts","creator_publishing_fanvue_job_insert_guard"]) assert.match(rollback,new RegExp(`drop function if exists public\\.${surface}`))
 assert.match(rollback,/drop trigger if exists trg_creator_publishing_fanvue_job_insert_guard/)
 assert.doesNotMatch(rollback,/delete\s+from\s+public\.(creator_platform_accounts|autopost_accounts|creator_publishing_content_packages|creator_publishing_media_assets|creator_publishing_platform_jobs|creator_publishing_fanvue_attempts)/i)
})

test("public registry activation is exact-env gated and X Reddit remain unavailable",()=>{
 assert.match(registry,/process\.env\.FANVUE_PUBLIC_ACTIVATION_ENABLED === "true"/)
 assert.match(registry,/platform\.id === "fanvue"/)
 assert.match(registry,/public_selectable: fanvuePublicActivationEnabled/)
 assert.match(registry,/id:\s*"x"[\s\S]*?public_selectable:\s*false/)
 assert.match(registry,/id:\s*"reddit"[\s\S]*?public_selectable:\s*false/)
})

test("Fanvue scheduling routes only direct Fanvue jobs into dedicated validation",()=>{
 assert.match(schedulingService,/data\?\.target_platform\s*===\s*"fanvue"/)
 assert.match(schedulingService,/scheduleFanvueDirectPlanCore/)
 assert.match(schedulingService,/cancelFanvueDirectPlanCore/)
 assert.match(schedulingService,/return schedulePlanCore\(input,deps\)/)
 assert.match(schedulingService,/return cancelPlanCore\(input,deps\)/)
 assert.match(directScheduling,/creator_publishing_schedule_plan/)
 assert.match(directScheduling,/operator_claim_cleanup/)
 assert.match(directScheduling,/performed\s*!==\s*false/)
})

test("launch worker is cron-authenticated, doubly gated, bounded, and processes scheduler before provider worker",()=>{
 assert.match(workerRoute,/authenticateSchedulerRequest/)
 assert.match(workerRoute,/process\.env\.FANVUE_PUBLIC_ACTIVATION_ENABLED\s*!==\s*"true"/)
 assert.match(workerRoute,/fanvueWorkerEnabled\(\)/)
 const scheduler=workerRoute.indexOf("const scheduler=await runCreatorPublishingScheduler")
 const worker=workerRoute.indexOf("const worker=await runProductionFanvueCpqWorker")
 assert(scheduler>0&&worker>scheduler)
 assert.doesNotMatch(workerRoute,/export async function POST/)
 assert.match(workerRuntime,/FANVUE_PUBLIC_ACTIVATION_ENABLED === "true"/)
 assert.match(workerRuntime,/FANVUE_CPQ_WORKER_ENABLED === "true"/)
 assert.match(workerRuntime,/const BATCH_SIZE = 1/)
 assert.match(workerRuntime,/runDormantFanvueCpqWorker/)
 assert.match(workerRuntime,/GENERATED_MEDIA_BUCKET/)
 assert.match(workerRuntime,/refreshFanvueAccessToken/)
})

test("scheduling UI stays truthful for Fanvue direct and OnlyFans assisted modes",()=>{
 assert.match(schedulingUi,/Fanvue direct plans publish through your connected Fanvue account/)
 assert.match(schedulingUi,/OnlyFans remains assisted\/manual/)
 assert.match(schedulingUi,/Schedulable Fanvue direct plan/)
 assert.match(schedulingUi,/!fanvueDirect/)
})

test("activation runtime gates remain false by default and no Fanvue cron is added blindly",()=>{
 assert.match(envExample,/CREATOR_PUBLISHING_SCHEDULER_ENABLED=false/)
 assert.match(envExample,/FANVUE_PUBLIC_ACTIVATION_ENABLED=false/)
 assert.match(envExample,/FANVUE_CPQ_WORKER_ENABLED=false/)
 assert.doesNotMatch(vercel,/creator-publishing-queue\/fanvue\/run/)
})

console.log("fanvuePublicActivation ok")
