import assert from "node:assert/strict"
import fs from "node:fs"
import { completeCreatorPublishingMediaUpload, createCreatorPublishingMediaUploadIntent, extensionForCreatorPublishingMime, validateCreatorPublishingUploadInput } from "../../../lib/creator-publishing-queue/media/uploadCore"
import { POST as disabledUploadIntentPOST } from "../../../app/api/creator-publishing-queue/media/upload-intents/route"
import { POST as disabledUploadCompletePOST } from "../../../app/api/creator-publishing-queue/media/upload-intents/[uploadIntentId]/complete/route"
async function test(name: string, fn: () => void | Promise<void>) { try { await fn(); console.log(`ok - ${name}`) } catch (e) { console.error(`not ok - ${name}`); throw e } }
const creator = "11111111-1111-4111-8111-111111111111", foreign = "99999999-9999-4999-8999-999999999999", pkg = "22222222-2222-4222-8222-222222222222", intentId = "33333333-3333-4333-8333-333333333333", assetId = "44444444-4444-4444-8444-444444444444", sha = "a".repeat(64)
function admin(opts: any = {}) { const calls: any = { signed: [], rpc: [], removed: [], info: [], inserted: null, updated: [], buckets: [] }; const api: any = { storage: { from(bucket: string) { calls.buckets.push(bucket); return { createSignedUploadUrl(path: string, options: any) { calls.signed.push({ bucket, path, options }); return opts.signError ? { data: null, error: {} } : { data: { signedUrl: "https://signed.example/?token=secret", token: "secret-token", path }, error: null } }, info(path: string) { calls.info.push({ bucket, path }); return opts.info ?? { data: { size: 123, contentType: "image/png" }, error: null } }, remove(paths: string[]) { calls.removed.push({ bucket, paths }); return { data: [], error: null } } } } }, from(table: string) { const q: any = { select() { return q }, eq(k: string, v: any) { (q.filters ||= []).push([k, v]); return q }, neq() { return q }, limit() { return table === "creator_publishing_queue_tasks" ? { data: opts.tasks ?? [], error: null } : q }, in() { return q }, insert(v: any) { calls.inserted = v; return q }, update(v: any) { calls.updated.push(v); return q }, single() { return { data: { id: intentId }, error: opts.insertError ?? null } }, maybeSingle() { if (table === "creator_publishing_content_packages") return { data: ("package" in opts ? opts.package : { id: pkg, creator_id: creator, target_platform: "onlyfans", creator_approval_status: "pending" }), error: null }; if (table === "creator_publishing_queue_tasks") return { data: opts.tasks ?? [], error: null }; if (table === "creator_publishing_media_upload_intents") return { data: opts.intent, error: null }; if (table === "creator_publishing_media_assets") return { data: opts.asset, error: null }; return { data: null, error: null } } }; return q }, rpc(name: string, args: any) { calls.rpc.push({ name, args }); return opts.rpc ?? { data: { media_asset: { id: assetId, content_package_id: pkg, storage_key: `${creator}/${pkg}/${assetId}.png`, mime_type: "image/png", sha256: sha, source: "camera_upload", ai_generation_metadata: {} } }, error: null } } }; return { api, calls } }

await test("validation covers MIME, size, sha, source, and browser-controlled fields", () => { for (const mime of ["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/quicktime","video/webm"]) assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: mime, sizeBytes: 1, sha256: sha, source: "camera_upload" }).ok, true); assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "text/plain", sizeBytes: 1, sha256: sha, source: "camera_upload" }).code, "INVALID_MIME_TYPE"); assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 0, sha256: sha, source: "camera_upload" }).code, "INVALID_FILE_SIZE"); assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 99, sha256: sha, source: "camera_upload" }, 50).code, "INVALID_FILE_SIZE"); assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: "A".repeat(64), source: "camera_upload" }).code, "INVALID_SHA256"); assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: sha, source: "ai_pipeline" }).code, "INVALID_SOURCE"); assert.deepEqual(["jpg","png","webp","gif","mp4","mov","webm"], ["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/quicktime","video/webm"].map((m) => extensionForCreatorPublishingMime(m))) })
await test("initiation persists configured bucket and returns no signedUrl", async () => { const { api, calls } = admin(); const c = { n: 0, randomUUID() { return ++this.n === 1 ? intentId : assetId } }; const res = await createCreatorPublishingMediaUploadIntent({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 123, sha256: sha, source: "camera_upload", bucket: "evil", storageKey: "evil", filename: "evil.exe" }, { supabaseAdmin: api, creatorId: creator, crypto: c as any, bucket: "private-override", now: () => new Date("2026-01-01T00:00:00Z") }); assert.equal(res.ok, true); assert.equal(calls.inserted.bucket_name, "private-override"); assert.equal(calls.signed[0].bucket, "private-override"); assert.equal(calls.signed[0].options.upsert, false); assert.equal(calls.inserted.storage_key, `${creator}/${pkg}/${assetId}.png`); assert.equal((res as any).value.bucket, "private-override"); assert.equal((res as any).value.signedUrl, undefined); assert(!JSON.stringify(calls.inserted).includes("secret-token")) })
await test("missing foreign fanvue approved and active-task packages fail before signing; archived task passes", async () => { for (const [opt, status, code] of [[{ package: null }, 404, "NOT_FOUND"], [{ package: { id: pkg, creator_id: foreign, target_platform: "onlyfans", creator_approval_status: "pending" } }, 404, "NOT_FOUND"], [{ package: { id: pkg, creator_id: creator, target_platform: "fanvue", creator_approval_status: "pending" } }, 404, "NOT_FOUND"], [{ package: { id: pkg, creator_id: creator, target_platform: "onlyfans", creator_approval_status: "approved" } }, 409, "PACKAGE_LOCKED"], [{ tasks: [{ id: "task" }] }, 409, "PACKAGE_LOCKED"]] as any[]) { const { api, calls } = admin(opt); const r = await createCreatorPublishingMediaUploadIntent({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: sha, source: "camera_upload" }, { supabaseAdmin: api, creatorId: creator }); assert.equal(r.ok, false); assert.equal((r as any).status, status); assert.equal((r as any).code, code); assert.equal(calls.signed.length, 0) } const archived = admin({ tasks: [] }); assert.equal((await createCreatorPublishingMediaUploadIntent({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: sha, source: "camera_upload" }, { supabaseAdmin: archived.api, creatorId: creator })).ok, true) })
await test("signing failure marks the inserted intent failed", async () => { const { api, calls } = admin({ signError: true }); const r = await createCreatorPublishingMediaUploadIntent({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: sha, source: "camera_upload" }, { supabaseAdmin: api, creatorId: creator, crypto: { randomUUID: (() => { let n = 0; return () => ++n === 1 ? intentId : assetId })() } as any }); assert.equal(r.ok, false); assert.equal((r as any).code, "UPLOAD_SIGNING_FAILED"); assert(calls.updated.some((u: any) => u.status === "failed" && u.failure_code === "UPLOAD_SIGNING_FAILED")) })
await test("completion uses persisted bucket for metadata and cleanup even when environment differs", async () => { const intent = { id: intentId, reserved_media_asset_id: assetId, creator_id: creator, content_package_id: pkg, bucket_name: "persisted-bucket", storage_key: `${creator}/${pkg}/${assetId}.png`, mime_type: "image/png", expected_size_bytes: 123, expected_sha256: sha, source: "camera_upload", status: "pending", expires_at: "2099-01-01T00:00:00Z" }; const good = admin({ intent }); assert.equal((await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: good.api, creatorId: creator })).ok, true); assert.deepEqual(good.calls.info[0], { bucket: "persisted-bucket", path: intent.storage_key }); const bad = admin({ intent, info: { data: { size: 0, contentType: "image/png" }, error: null } }); assert.equal((await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: bad.api, creatorId: creator })).code, "UPLOAD_METADATA_MISMATCH"); assert.deepEqual(bad.calls.removed[0], { bucket: "persisted-bucket", paths: [intent.storage_key] }); assert.equal(bad.calls.rpc.length, 0) })
await test("completion fail-closed and idempotent cases", async () => { const intent = { id: intentId, reserved_media_asset_id: assetId, creator_id: creator, content_package_id: pkg, bucket_name: "persisted-bucket", storage_key: `${creator}/${pkg}/${assetId}.png`, mime_type: "image/png", expected_size_bytes: 123, expected_sha256: sha, source: "camera_upload", status: "completed", expires_at: "2099-01-01T00:00:00Z" }; const idem = admin({ intent, asset: { id: assetId, content_package_id: pkg, storage_key: intent.storage_key, mime_type: "image/png", sha256: sha, source: "camera_upload", ai_generation_metadata: {} } }); assert.equal((await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: idem.api, creatorId: creator })).ok, true); assert.equal(idem.calls.rpc.length, 0); for (const [row, code] of [[null,"NOT_FOUND"], [{ ...intent, status: "failed" },"UPLOAD_INTENT_FAILED"], [{ ...intent, status: "expired" },"UPLOAD_INTENT_EXPIRED"], [{ ...intent, status: "pending", expires_at: "2000-01-01T00:00:00Z" },"UPLOAD_INTENT_EXPIRED"]] as any[]) assert.equal((await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: admin({ intent: row }).api, creatorId: creator }) as any).code, code) })
await test("disabled browser upload routes return identical no-store 404s without reading request inputs", async () => {
  let bodyRead = false
  const request = {
    headers: new Headers({ authorization: "Bearer fake", cookie: "session=fake" }),
    async json() { bodyRead = true; throw new Error("body must not be parsed") },
  } as unknown as Request
  const throwingParams = new Proxy({}, { get() { throw new Error("params must not be inspected") } }) as any
  for (const response of [await disabledUploadIntentPOST(request), await disabledUploadCompletePOST(request, { params: throwingParams })]) {
    assert.equal(response.status, 404)
    assert.equal(response.headers.get("Cache-Control"), "no-store")
    assert.deepEqual(await response.json(), { error: "NOT_FOUND" })
  }
  assert.equal(bodyRead, false)
})
await test("route and migration source assertions cover disabled public routes, RLS, partial conflict predicate, and client boundaries", () => { const initRoute = fs.readFileSync("app/api/creator-publishing-queue/media/upload-intents/route.ts", "utf8"), completeRoute = fs.readFileSync("app/api/creator-publishing-queue/media/upload-intents/[uploadIntentId]/complete/route.ts", "utf8"), migration = fs.readFileSync("supabase/migrations/20260710000500_creator_publishing_media_upload_intents.sql", "utf8"), client = fs.readFileSync("lib/creator-publishing-queue/media/uploadClient.ts", "utf8"); const forbiddenRouteTerms = ["getSupabaseAdmin", "requireUserId", "createCreatorPublishingMediaUploadIntent", "completeCreatorPublishingMediaUpload", "createSignedUploadUrl", "uploadToSignedUrl", "creator_publishing_complete_media_upload", "service_role", "supabaseAdmin", "Unauthorized", "UNAUTHENTICATED", "INVALID_REQUEST", "ASSET_REGISTRATION_FAILED", "signedUrl", "token", "storage_key", "cookie", "session", "stack"]; for (const source of [initRoute, completeRoute]) { assert.match(source, /NextResponse\.json\(\{ error: "NOT_FOUND" \}, \{ status: 404, headers: disabledUploadResponse \}\)/); assert.match(source, /Cache-Control": "no-store"/); for (const term of forbiddenRouteTerms) assert.equal(source.includes(term), false, `${term} must stay out of disabled routes`) } assert.match(migration, /bucket_name text not null/); assert.match(migration, /bucket_name_nonblank/); assert.match(migration, /enable row level security/); assert.doesNotMatch(migration, /create policy[\s\S]*(authenticated|anon)[\s\S]*(insert|update|delete)/i); assert.match(migration, /security definer/); assert.match(migration, /where idempotency_key is not null\n  do nothing/); assert.doesNotMatch(migration, /on conflict \(entity_type, entity_id, action, idempotency_key\) do nothing/); assert.match(migration, /return jsonb_build_object\('error', jsonb_build_object\('code', 'UPLOAD_INTENT_EXPIRED'\)/); assert.match(migration, /grant execute on function public\.creator_publishing_complete_media_upload\(uuid, uuid\) to service_role/); assert.match(fs.readFileSync("supabase/migrations/20260710000400_creator_publishing_creator_approval_queue.sql", "utf8"), /trg_creator_publishing_media_assets_invalidate_parent/); assert.match(client, /from "\.\/uploadShared"/); assert.doesNotMatch(client, /uploadCore|supabaseAdmin|getSupabaseAdmin|service_role|rpc\(/); const core = fs.readFileSync("lib/creator-publishing-queue/media/uploadCore.ts", "utf8"); assert.doesNotMatch(core + client, /getPublicUrl|\.list\(|onlyfans\.com|fansly\.com|placeholder|ai_pipeline.*insert/i); assert.match(core, /createSignedUploadUrl\(storageKey, \{ upsert: false \}\)/); assert.match(client, /uploadToSignedUrl/) })
console.log("media upload tests cover Task 7 corrected mocked upload flow and source-level migration/security assertions")
