import assert from "node:assert/strict"
import fs from "node:fs"
import { execSync } from "node:child_process"
import { buildCreatorPublishingStorageKey, completeCreatorPublishingMediaUpload, createCreatorPublishingMediaUploadIntent, extensionForCreatorPublishingMime, validateCreatorPublishingUploadInput } from "../../../lib/creator-publishing-queue/media/uploadCore"
async function test(name: string, fn: () => void | Promise<void>) { try { await fn(); console.log(`ok - ${name}`) } catch (e) { console.error(`not ok - ${name}`); throw e } }
const creator = "11111111-1111-4111-8111-111111111111", pkg = "22222222-2222-4222-8222-222222222222", intentId = "33333333-3333-4333-8333-333333333333", assetId = "44444444-4444-4444-8444-444444444444"
const sha = "a".repeat(64)
function admin(opts: any = {}) { const calls: any = { tables: [], signed: [], rpc: [], removed: [], info: [], inserted: null, updated: [] }; const api: any = { storage: { from(bucket: string) { calls.bucket = bucket; return { createSignedUploadUrl(path: string, options: any) { calls.signed.push({ path, options }); return opts.signError ? { data: null, error: {} } : { data: { signedUrl: "https://signed.example/?token=secret", token: "secret-token", path }, error: null } }, info(path: string) { calls.info.push(path); return opts.info ?? { data: { size: 123, contentType: "image/png" }, error: null } }, remove(paths: string[]) { calls.removed.push(paths); return { data: [], error: null } } } } }, from(table: string) { calls.tables.push(table); const q: any = { select() { return q }, eq(k: string, v: any) { (q.filters ||= []).push([k, v]); return q }, neq() { return q }, limit() { return q }, in() { return q }, insert(v: any) { calls.inserted = v; return q }, update(v: any) { calls.updated.push(v); return q }, single() { return { data: { id: intentId }, error: opts.insertError ?? null } }, maybeSingle() { if (table === "creator_publishing_content_packages") return { data: ("package" in opts ? opts.package : { id: pkg, creator_id: creator, target_platform: "onlyfans", creator_approval_status: "pending" }), error: null }; if (table === "creator_publishing_media_upload_intents") return { data: opts.intent, error: null }; if (table === "creator_publishing_media_assets") return { data: opts.asset, error: null }; return { data: null, error: null } } }; return q }, rpc(name: string, args: any) { calls.rpc.push({ name, args }); return opts.rpc ?? { data: { media_asset: { id: assetId, content_package_id: pkg, storage_key: `${creator}/${pkg}/${assetId}.png`, mime_type: "image/png", sha256: sha, source: "camera_upload", ai_generation_metadata: {} } }, error: null } } }; return { api, calls } }

await test("validation covers MIME, size, sha, source, browser-controlled fields", () => {
  for (const mime of ["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/quicktime","video/webm"]) assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: mime, sizeBytes: 1, sha256: sha, source: "camera_upload" }).ok, true)
  assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "text/plain", sizeBytes: 1, sha256: sha, source: "camera_upload" }).code, "INVALID_MIME_TYPE")
  assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 0, sha256: sha, source: "camera_upload" }).code, "INVALID_FILE_SIZE")
  assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 99, sha256: sha, source: "camera_upload" }, 50).code, "INVALID_FILE_SIZE")
  assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: "A".repeat(64), source: "camera_upload" }).code, "INVALID_SHA256")
  assert.equal(validateCreatorPublishingUploadInput({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: sha, source: "ai_pipeline" }).code, "INVALID_SOURCE")
  assert.deepEqual(["jpg","png","webp","gif","mp4","mov","webm"], ["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/quicktime","video/webm"].map((m) => extensionForCreatorPublishingMime(m)))
})
await test("initiation checks ownership before signing and reserves server path", async () => { const { api, calls } = admin(); const c = { n: 0, randomUUID() { return ++this.n === 1 ? intentId : assetId } }; const res = await createCreatorPublishingMediaUploadIntent({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 123, sha256: sha, source: "camera_upload", creatorId: "evil", bucket: "evil", storageKey: "evil/../../x", filename: "evil.exe" }, { supabaseAdmin: api, creatorId: creator, crypto: c as any, now: () => new Date("2026-01-01T00:00:00Z") }); assert.equal(res.ok, true); assert.equal(calls.signed[0].options.upsert, false); assert.equal(calls.inserted.storage_key, `${creator}/${pkg}/${assetId}.png`); assert.equal((res as any).value.storageKey, calls.inserted.storage_key); assert.equal((res as any).value.bucket, "creator-publishing-media"); assert.equal(calls.inserted.creator_id, creator); assert(!JSON.stringify(calls.inserted).includes("secret-token")); })
await test("missing foreign fanvue approved and active-task packages fail before signing", async () => { for (const opt of [{ package: null }, { package: { id: pkg, creator_id: creator, target_platform: "fanvue", creator_approval_status: "pending" } }, { package: { id: pkg, creator_id: creator, target_platform: "onlyfans", creator_approval_status: "approved" } }]) { const { api, calls } = admin(opt); const r = await createCreatorPublishingMediaUploadIntent({ contentPackageId: pkg, mimeType: "image/png", sizeBytes: 1, sha256: sha, source: "camera_upload" }, { supabaseAdmin: api, creatorId: creator }); assert.equal(r.ok, false); assert.equal(calls.signed.length, 0) } })
await test("completion verifies storage before RPC, cleans exact reserved object, and is idempotent", async () => { const intent = { id: intentId, reserved_media_asset_id: assetId, creator_id: creator, content_package_id: pkg, storage_key: `${creator}/${pkg}/${assetId}.png`, mime_type: "image/png", expected_size_bytes: 123, expected_sha256: sha, source: "camera_upload", status: "pending", expires_at: "2099-01-01T00:00:00Z" }; const good = admin({ intent }); const r = await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: good.api, creatorId: creator }); assert.equal(r.ok, true); assert.equal(good.calls.info[0], intent.storage_key); assert.equal(good.calls.rpc.length, 1); const bad = admin({ intent, info: { data: { size: 0, contentType: "image/png" }, error: null } }); const b = await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: bad.api, creatorId: creator }); assert.equal(b.code, "UPLOAD_METADATA_MISMATCH"); assert.deepEqual(bad.calls.removed[0], [intent.storage_key]); assert.equal(bad.calls.rpc.length, 0); const idem = admin({ intent: { ...intent, status: "completed" }, asset: { id: assetId, content_package_id: pkg, storage_key: intent.storage_key, mime_type: "image/png", sha256: sha, source: "camera_upload", ai_generation_metadata: {} } }); assert.equal((await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: idem.api, creatorId: creator })).ok, true); assert.equal(idem.calls.rpc.length, 0) })
await test("completion fail-closed cases", async () => { for (const [intent, code] of [[null,"NOT_FOUND"], [{ status: "failed" },"UPLOAD_INTENT_FAILED"], [{ status: "expired" },"UPLOAD_INTENT_EXPIRED"], [{ status: "pending", expires_at: "2000-01-01T00:00:00Z", storage_key: `${creator}/${pkg}/${assetId}.png` },"UPLOAD_INTENT_EXPIRED"]] as any[]) { const r = await completeCreatorPublishingMediaUpload({ uploadIntentId: intentId }, { supabaseAdmin: admin({ intent: intent && { id: intentId, reserved_media_asset_id: assetId, creator_id: creator, content_package_id: pkg, mime_type: "image/png", expected_size_bytes: 123, expected_sha256: sha, source: "camera_upload", ...intent } }).api, creatorId: creator }); assert.equal((r as any).code, code) } })
await test("routes and migration enforce no-store, service-role-only RPC, RLS, uniqueness, no broad storage behavior", () => { const migration = fs.readFileSync("supabase/migrations/20260710000500_creator_publishing_media_upload_intents.sql", "utf8"); assert.match(migration, /create table if not exists public\.creator_publishing_media_upload_intents/); assert.match(migration, /enable row level security/); assert.doesNotMatch(migration, /create policy[\s\S]*(authenticated|anon)[\s\S]*(insert|update|delete)/i); assert.match(migration, /reserved_media_asset_id[\s\S]*unique/); assert.match(migration, /creator_publishing_media_assets_storage_key_uidx/); assert.match(migration, /security definer/); assert.match(migration, /revoke all on function public\.creator_publishing_complete_media_upload\(uuid, uuid\) from PUBLIC/); assert.match(migration, /grant execute on function public\.creator_publishing_complete_media_upload\(uuid, uuid\) to service_role/); assert.match(migration, /on conflict \(id\) do nothing/); assert.match(migration, /v_intent\.reserved_media_asset_id/); assert.doesNotMatch(migration, /signedUrl|signed_url|service_role_key|password|cookie/); assert.match(fs.readFileSync("supabase/migrations/20260710000400_creator_publishing_creator_approval_queue.sql", "utf8"), /trg_creator_publishing_media_assets_invalidate_parent/); for (const p of ["app/api/creator-publishing-queue/media/upload-intents/route.ts", "app/api/creator-publishing-queue/media/upload-intents/[uploadIntentId]/complete/route.ts"]) assert.match(fs.readFileSync(p, "utf8"), /Cache-Control": "no-store"/); const src = fs.readFileSync("lib/creator-publishing-queue/media/uploadCore.ts", "utf8") + fs.readFileSync("lib/creator-publishing-queue/media/uploadClient.ts", "utf8"); assert.doesNotMatch(src, /getPublicUrl|\.list\(|\.upload\(|onlyfans\.com|fansly\.com|placeholder|ai_pipeline.*insert/i); assert.match(src, /createSignedUploadUrl\(storageKey, \{ upsert: false \}\)/); assert.match(src, /uploadToSignedUrl/); assert.match(src, /\.info\(intent\.storage_key\)/); assert.match(src, /\.remove\(\[intent\.storage_key\]\)/); assert(!execSync("git diff --name-only", { encoding: "utf8" }).split(/\n/).some((p) => /fanvue|generation|autopost/.test(p))) })
console.log("media upload tests cover Task 7 mocked upload flow and source-level migration/security assertions")
