import { spawn, spawnSync } from 'node:child_process';
import { appendFileSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const databaseUrl=process.env.TASK20_DATABASE_URL||process.env.DATABASE_URL;if(!databaseUrl)throw new Error('TASK20_DATABASE_URL or DATABASE_URL is required');const parsed=new URL(databaseUrl);if(!['postgres:','postgresql:'].includes(parsed.protocol)||!['127.0.0.1','localhost','[::1]'].includes(parsed.hostname)||parsed.port!=='5432'||parsed.pathname!=='/task20_ci'||parsed.search||parsed.hash)throw new Error('Task 20 concurrency tests require local PostgreSQL database task20_ci on port 5432');
const logPath='task20-concurrency-diagnostics.log';writeFileSync(logPath,`Task 20 audited-wrapper concurrency diagnostics\nstarted_at=${new Date().toISOString()}\n`);const actor='00000000-0000-4000-8000-000000000202',digest='1111111111111111111111111111111111111111111111111111111111111111';
const finite="('current_claim_required','work_not_completable','account_not_verified','package_not_approved','capability_unavailable','source_changed','evidence_mismatch','url_or_reason_required','idempotency_conflict')";
function uuid(f,s){return`${f}-0000-4000-8000-${String(s).padStart(12,'0')}`}function q(v){return`'${String(v).replaceAll("'","''")}'`}function tail(){try{console.error(readFileSync(logPath,'utf8').split(/\n/).slice(-220).join('\n'))}catch{}}
function file(label,sql){const f=join(mkdtempSync(join(tmpdir(),'task20-concurrency-')),`${label.replace(/[^A-Za-z0-9_-]/g,'_')}.sql`);writeFileSync(f,`\\set ON_ERROR_STOP on\nset lock_timeout='10s';\nset statement_timeout='30s';\n${sql}\n`);return f}
function run(label,sql){const r=spawnSync('psql',[databaseUrl,'-v','ON_ERROR_STOP=1','-f',file(label,sql)],{encoding:'utf8'});appendFileSync(logPath,`\n## ${label}\n${r.stdout||''}${r.stderr||''}`);if(r.status!==0)throw new Error(`${label} failed with status ${r.status}`)}
function scalar(label,sql){const r=spawnSync('psql',[databaseUrl,'-X','-q','-A','-t','-v','ON_ERROR_STOP=1','-c',sql],{encoding:'utf8'});if(r.status!==0)throw new Error(`${label} scalar failed`);const v=(r.stdout||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(v.length!==1)throw new Error(`${label} scalar expected one value`);return v[0]}
async function side(label,sql){return await new Promise(resolve=>{const p=spawn('psql',[databaseUrl,'-v','ON_ERROR_STOP=1','-f',file(label,sql)]);let stdout='',stderr='';p.stdout.on('data',c=>stdout+=String(c));p.stderr.on('data',c=>stderr+=String(c));p.on('error',e=>resolve({status:null,stdout,stderr:`${stderr}${e}`}));p.on('exit',status=>resolve({status,stdout,stderr}))})}
function fixture(s){return{seed:s,job:uuid('40000000',s),token:uuid('60000000',s),evidence:uuid('70000000',s)}}
function call(f,key,{url='https://www.onlyfans.com/12345/trusteduser',reason=null,token=f.token}={}){return`select public.creator_publishing_complete_onlyfans_manual_post_audited('complete','${actor}'::uuid,'${f.job}'::uuid,${q(key)},'${f.evidence}'::uuid,${url===null?'null':q(url)},${reason===null?'null':q(reason)},'${digest}',8,'image/jpeg','${token}'::uuid) as result;`}
async function race(label,a,b){const at=scalar(`barrier-${label}`,`select (clock_timestamp()+interval '2 seconds')::text;`),wait=`select pg_sleep(greatest(0,extract(epoch from ('${at}'::timestamptz-clock_timestamp()))));`;const [l,r]=await Promise.all([side(`left-${label}`,`${wait}\n${a}`),side(`right-${label}`,`${wait}\n${b}`)]);appendFileSync(logPath,`\n## ${label}\nL=${l.status}\n${l.stdout}${l.stderr}\nR=${r.status}\n${r.stdout}${r.stderr}`);if(l.status!==0||r.status!==0)throw new Error(`${label} concurrent calls failed`)}
try{
run('verify',`do $$ begin if to_regprocedure('public.creator_publishing_complete_onlyfans_manual_post_audited(text,uuid,uuid,text,uuid,text,text,text,integer,text,uuid)') is null then raise exception 'TASK20_WRAPPER_MISSING';end if;end $$;`);
const s=fixture(100);run('seed-success',`select task20_test.create_fixture(${s.seed});`);await race('identical-success',call(s,'task20-race-success-0100'),call(s,'task20-race-success-0100'));run('assert-success',`do $$ begin if(select count(*) from public.creator_publishing_audit_events where entity_id='${s.job}'::uuid and action='operator_onlyfans_manual_completion_proof_recorded' and idempotency_key='task20-race-success-0100')<>1 then raise exception 'TASK20_SUCCESS_RACE_PROOF_COUNT';end if;if(select count(*) from public.creator_publishing_operator_action_idempotency where actor_id='${actor}'::uuid and action_type='manual_completion' and idempotency_key='task20-race-success-0100')<>1 then raise exception 'TASK20_SUCCESS_RACE_IDEMPOTENCY_COUNT';end if;end $$;`);run('success-replay',`${call(s,'task20-race-success-0100')}do $$begin if(select count(*) from public.creator_publishing_audit_events where entity_id='${s.job}'::uuid and action='operator_onlyfans_manual_completion_proof_recorded' and idempotency_key='task20-race-success-0100')<>1 then raise exception 'TASK20_SUCCESS_REPLAY_DUPLICATE_PROOF';end if;end$$;`);
const r=fixture(101);run('seed-rejection',`select task20_test.create_fixture(${r.seed});`);await race('identical-rejection',call(r,'task20-race-reject-0101',{url:null,reason:'invalid_reason'}),call(r,'task20-race-reject-0101',{url:null,reason:'invalid_reason'}));run('assert-rejection',`do $$declare c text;begin select after_state->>'rejection_code' into c from public.creator_publishing_audit_events where entity_id='${r.job}'::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-race-reject-0101';if(select count(*) from public.creator_publishing_audit_events where entity_id='${r.job}'::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-race-reject-0101')<>1 then raise exception 'TASK20_REJECTION_RACE_EVENT_COUNT';end if;if c not in ${finite} then raise exception 'TASK20_REJECTION_RACE_WRONG_CODE';end if;if(select count(*) from public.creator_publishing_operator_action_idempotency where actor_id='${actor}'::uuid and action_type='manual_completion_rejection' and idempotency_key='task20-race-reject-0101')<>1 then raise exception 'TASK20_REJECTION_RACE_IDEMPOTENCY_COUNT';end if;end$$;`);run('rejection-replay',`${call(r,'task20-race-reject-0101',{url:null,reason:'invalid_reason'})}do$$begin if(select count(*) from public.creator_publishing_audit_events where entity_id='${r.job}'::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-race-reject-0101')<>1 then raise exception 'TASK20_REJECTION_REPLAY_DUPLICATE_EVENT';end if;end$$;`);run('rejection-conflict',`do$$declare x jsonb;c text;begin x:=public.creator_publishing_complete_onlyfans_manual_post_audited('complete','${actor}'::uuid,'${r.job}'::uuid,'task20-race-reject-0101','${r.evidence}'::uuid,null,'different_invalid_reason','${digest}',8,'image/jpeg','${r.token}'::uuid);if x->>'code'<>'idempotency_conflict' or coalesce((x->>'replayed')::boolean,false) then raise exception 'TASK20_REJECTION_DIFFERENT_REQUEST_NOT_CONFLICT';end if;select stored_result->>'code' into c from public.creator_publishing_operator_action_idempotency where actor_id='${actor}'::uuid and action_type='manual_completion_rejection' and idempotency_key='task20-race-reject-0101';if c not in ${finite} then raise exception 'TASK20_REJECTION_CONFLICT_REUSED_UNRELATED_RESULT';end if;if(select count(*) from public.creator_publishing_audit_events where entity_id='${r.job}'::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-race-reject-0101')<>1 then raise exception 'TASK20_REJECTION_CONFLICT_DUPLICATE_EVENT';end if;end$$;`);
appendFileSync(logPath,'\nTASK20_CONCURRENCY_PASSED\n');console.log('TASK20_CONCURRENCY_PASSED')}catch(e){appendFileSync(logPath,`\nFAILED: ${e?.stack||e}\n`);tail();process.exit(1)}
