import { spawnSync } from 'node:child_process'; import { appendFileSync, writeFileSync, mkdtempSync, readFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
const databaseUrl=process.env.TASK18_DATABASE_URL||process.env.DATABASE_URL; if(!databaseUrl) throw new Error('TASK18_DATABASE_URL or DATABASE_URL is required');
const adminUrl=process.env.DATABASE_URL||databaseUrl;
function printTail(path){ try{ const text=readFileSync(path,'utf8'); console.error(text.split(/\n/).slice(-100).join('\n')) }catch{} }
const logPath='task18-postgres-diagnostics.log'; writeFileSync(logPath,`Task 18 PostgreSQL integration diagnostics\nstarted_at=${new Date().toISOString()}\n`);
function runSql(label,sql,url=databaseUrl){ const file=join(mkdtempSync(join(tmpdir(),'task18-sql-')),`${label.replace(/[^a-z0-9_-]/gi,'_')}.sql`); writeFileSync(file,sql); runFile(label,file,url) }
function runFile(label,file,url=databaseUrl,expectFailure){ appendFileSync(logPath,`\n## ${label}: ${file}\nurl=${url}\n`); const res=spawnSync('psql',[url,'-v','ON_ERROR_STOP=1','-f',file],{encoding:'utf8'}); appendFileSync(logPath,res.stdout||''); appendFileSync(logPath,res.stderr||''); if(res.error) appendFileSync(logPath,`spawn_error=${res.error.message}\n`); if(expectFailure){ if(res.status===0) throw new Error(`${label} unexpectedly succeeded`); return `${res.stdout||''}\n${res.stderr||''}` } if(res.status!==0){ console.error(res.stdout||''); console.error(res.stderr||''); throw new Error(`${label} failed with status ${res.status}`) } return `${res.stdout||''}\n${res.stderr||''}` }
const bootstrapSql=`do $$ begin if not exists (select 1 from pg_roles where rolname='anon') then create role anon; end if; if not exists (select 1 from pg_roles where rolname='authenticated') then create role authenticated; end if; if not exists (select 1 from pg_roles where rolname='service_role') then create role service_role bypassrls; end if; end $$; create schema if not exists auth; create schema if not exists extensions; create extension if not exists pgcrypto with schema extensions; create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$; create table if not exists auth.users(id uuid primary key, email text, created_at timestamptz default now()); create table if not exists public.profiles(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), created_at timestamptz default now()); create table if not exists public.generations(id uuid primary key default gen_random_uuid(), user_id uuid, status text, r2_bucket text, r2_key text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz default now());`;
const migrations=['20260710000100_creator_publishing_queue_foundation.sql','20260710000200_creator_publishing_compliance_manual_review_outcome.sql','20260710000300_creator_publishing_manual_review_workflow.sql','20260710000400_creator_publishing_creator_approval_queue.sql','20260710000500_creator_publishing_media_upload_intents.sql','20260710000600_creator_publishing_generated_media_association.sql','20260710000700_creator_publishing_platform_account_setup.sql','20260710000800_creator_publishing_package_composer.sql','20260710000900_creator_publishing_trusted_verification.sql','20260710001000_creator_publishing_ai_twin_consent.sql','20260710001100_creator_publishing_trusted_compliance_submission.sql','20260711001200_creator_publishing_autopost_orchestration.sql','20260711001300_creator_publishing_scheduler_due_state.sql','20260712001400_creator_publishing_onlyfans_operator_queue.sql','20260716001500_creator_publishing_onlyfans_manual_completion.sql'].map(f=>`supabase/migrations/${f}`);
const through17a=migrations.filter(m=>!m.includes('20260716001500'));
function dbUrl(name){ const u=new URL(adminUrl); u.pathname=`/${name}`; return u.toString() }
function adminSql(label,sql){ runSql(label,sql,adminUrl) }
function createDb(name){ adminSql(`create-${name}`,`drop database if exists ${name} with (force); create database ${name};`) }
function dropDb(name){ try{ adminSql(`drop-${name}`,`drop database if exists ${name} with (force);`) }catch(e){ appendFileSync(logPath,`cleanup failed for ${name}: ${e}\n`) } }
function applyThrough17a(url){ runSql('upgrade-bootstrap',bootstrapSql,url); for(const m of through17a) runFile('upgrade-migration-17a',m,url) }
function seedPreTask18(url, status){ runSql(`seed-${status}`,`
  insert into auth.users(id,email) values ('00000000-0000-4000-8000-000000000101','upgrade-creator@test'),('00000000-0000-4000-8000-000000000202','upgrade-actor@test'),('00000000-0000-4000-8000-000000000303','upgrade-reviewer@test') on conflict do nothing;
  insert into public.creator_platform_accounts(id,creator_id,platform,platform_username,verification_status,verification_attested_at,verification_reviewed_by,verification_reviewed_at,verification_evidence_reference,verification_reason,verification_legacy_revoked)
    values ('00000000-0000-4000-8000-000000000401','00000000-0000-4000-8000-000000000101','onlyfans','trusteduser','verified',clock_timestamp(),'00000000-0000-4000-8000-000000000303',clock_timestamp(),'task18-upgrade-test-evidence','task18 upgrade fixture trusted verification',false)
    on conflict (id) do update set creator_id=excluded.creator_id, platform=excluded.platform, platform_username=excluded.platform_username, verification_status='verified', verification_attested_at=excluded.verification_attested_at, verification_reviewed_by=excluded.verification_reviewed_by, verification_reviewed_at=excluded.verification_reviewed_at, verification_evidence_reference=excluded.verification_evidence_reference, verification_reason=excluded.verification_reason, verification_legacy_revoked=false;
  insert into public.creator_publishing_content_packages(id,creator_id,platform_account_id,target_platform,title,caption_body,compliance_status,creator_approval_status,creator_approved_at,creator_approved_by) values ('00000000-0000-4000-8000-000000000501','00000000-0000-4000-8000-000000000101','00000000-0000-4000-8000-000000000401','onlyfans','upgrade','caption','passed','approved',now(),'00000000-0000-4000-8000-000000000101') on conflict do nothing;
  insert into public.creator_publishing_queue_tasks(id,content_package_id,creator_id,target_platform,platform_account_id,status,due_at,posted_by,posted_at,posted_confirmation,operator_progress_state,proof_screenshot_storage_key,final_post_url,final_post_url_skip_reason)
  values ('00000000-0000-4000-8000-000000000601','00000000-0000-4000-8000-000000000501','00000000-0000-4000-8000-000000000101','onlyfans','00000000-0000-4000-8000-000000000401','${status}',now(),${status==='confirmed_posted_manual'?`'00000000-0000-4000-8000-000000000202',now(),true,'handoff_ready','operator-completion-evidence/upgrade/proof.png','https://example.test/x',null`:`null,null,false,'not_started',null,null,null`});
`,url) }
function runUpgradePreflightTests(){ const bad=`task18_bad_${process.pid}`; const good=`task18_good_${process.pid}`; try{ createDb(bad); const badUrl=dbUrl(bad); applyThrough17a(badUrl); seedPreTask18(badUrl,'confirmed_posted_manual'); const out=runFile('upgrade-task18-incompatible',migrations.at(-1),badUrl,true); if(!out.includes('TASK18_EXISTING_COMPLETION_ROWS_INCOMPATIBLE')) throw new Error('incompatible upgrade did not raise TASK18_EXISTING_COMPLETION_ROWS_INCOMPATIBLE'); appendFileSync(logPath,'\nTASK18_INCOMPATIBLE_PREFLIGHT_REJECTED\n'); runSql('upgrade-rollback-assertions',`do $$ begin if to_regclass('public.creator_publishing_operator_completion_evidence_intents') is not null then raise exception 'TASK18_ROLLBACK_TABLE_PRESENT'; end if; if to_regprocedure('public.creator_publishing_complete_onlyfans_manual_post(text,uuid,uuid,text,uuid,text,text,text,integer,text,uuid)') is not null then raise exception 'TASK18_ROLLBACK_FUNCTION_PRESENT'; end if; if exists(select 1 from pg_constraint where conname='task18_queue_manual_completion_invariants') then raise exception 'TASK18_ROLLBACK_QUEUE_CONSTRAINT_PRESENT'; end if; if exists(select 1 from pg_constraint where conname='task18_operator_action_type_check') then raise exception 'TASK18_ROLLBACK_ACTION_CONSTRAINT_PRESENT'; end if; if not exists(select 1 from public.creator_publishing_queue_tasks where id='00000000-0000-4000-8000-000000000601' and status='confirmed_posted_manual' and final_post_url='https://example.test/x') then raise exception 'TASK18_INCOMPATIBLE_SEED_LOST'; end if; end $$;`,badUrl); appendFileSync(logPath,'\nTASK18_INCOMPATIBLE_UPGRADE_ROLLBACK_VERIFIED\n'); createDb(good); const goodUrl=dbUrl(good); applyThrough17a(goodUrl); seedPreTask18(goodUrl,'due_now'); runFile('upgrade-task18-compatible',migrations.at(-1),goodUrl); runSql('upgrade-compatible-assertions',`do $$ begin if to_regclass('public.creator_publishing_operator_completion_evidence_intents') is null then raise exception 'TASK18_UPGRADE_TABLE_MISSING'; end if; if to_regprocedure('public.creator_publishing_complete_onlyfans_manual_post(text,uuid,uuid,text,uuid,text,text,text,integer,text,uuid)') is null then raise exception 'TASK18_UPGRADE_FUNCTION_MISSING'; end if; if not exists(select 1 from public.creator_publishing_queue_tasks where id='00000000-0000-4000-8000-000000000601' and status='due_now' and posted_confirmation=false and final_post_url is null) then raise exception 'TASK18_COMPATIBLE_ROW_REWRITTEN'; end if; if not exists(select 1 from pg_constraint where conname='task18_queue_manual_completion_invariants') then raise exception 'TASK18_UPGRADE_CONSTRAINT_MISSING'; end if; if not exists(select 1 from pg_constraint where conname='task18_operator_action_type_check') then raise exception 'TASK18_UPGRADE_ACTION_CONSTRAINT_MISSING'; end if; end $$;`,goodUrl); appendFileSync(logPath,'\nTASK18_COMPATIBLE_UPGRADE_VERIFIED\nTASK18_UPGRADE_PREFLIGHT_TESTS_PASSED\n') } finally { dropDb(bad); dropDb(good) } }
try{ runUpgradePreflightTests(); runSql('bootstrap',bootstrapSql); for(const m of migrations) runFile('migration',m); runFile('task18 assertions','backend/creator-publishing-queue/tests/task18ManualCompletionPostgresIntegration.sql'); appendFileSync(logPath,`\nTASK18_POSTGRES_INTEGRATION_PASSED\ncompleted_at=${new Date().toISOString()}\n`); console.log('TASK18_POSTGRES_INTEGRATION_PASSED') }catch(e){ appendFileSync(logPath,`\nFAILED: ${e?.stack||e}\ncompleted_at=${new Date().toISOString()}\n`); printTail(logPath); process.exit(1) }
