\set ON_ERROR_STOP on
create schema if not exists task21_retry_recovery_test;
create or replace function task21_retry_recovery_test.assert(ok boolean,msg text) returns void language plpgsql as $$ begin if not coalesce(ok,false) then raise exception 'ASSERTION_FAILED: %',msg; end if; end $$;
create or replace function task21_retry_recovery_test.uuid(kind int,n int) returns uuid language sql immutable as $$ select ('21300000-0000-4'||lpad(kind::text,3,'0')||'-8000-'||lpad(n::text,12,'0'))::uuid $$;

-- Migration application is definition-only.
with current_rows as (
 select 'account' t,id::text k,to_jsonb(x) v from public.creator_platform_accounts x union all
 select 'package',id::text,to_jsonb(x) from public.creator_publishing_content_packages x union all
 select 'plan',id::text,to_jsonb(x) from public.creator_publishing_plans x union all
 select 'job',id::text,to_jsonb(x) from public.creator_publishing_platform_jobs x union all
 select 'queue',id::text,to_jsonb(x) from public.creator_publishing_queue_tasks x union all
 select 'event',id::text,to_jsonb(x) from public.creator_publishing_scheduler_events x union all
 select 'audit',id::text,to_jsonb(x) from public.creator_publishing_audit_events x union all
 select 'idempotency',creator_id::text||':'||action_type||':'||idempotency_key,to_jsonb(x) from public.creator_publishing_scheduler_idempotency x union all
 select 'capability',platform,to_jsonb(x) from public.creator_publishing_platform_capabilities x union all
 select 'generation',id::text,to_jsonb(x) from public.generations x
),delta as ((select * from current_rows except select entity_type,entity_id,row_data from public.task21_recovery_pre_data_snapshot) union all (select entity_type,entity_id,row_data from public.task21_recovery_pre_data_snapshot except select * from current_rows))
select task21_retry_recovery_test.assert(not exists(select 1 from delta),'02000 application mutates no fixture data');
select task21_retry_recovery_test.assert(not exists(select 1 from public.creator_publishing_audit_events where action='creator_publishing_scheduler_event_retry_requeued'),'02000 application creates no recovery audit');

-- Exact function and unchanged repository definitions.
select task21_retry_recovery_test.assert(pg_get_function_arguments('public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)'::regprocedure)='p_event_id uuid, p_idempotency_key text, p_reason_code text','signature exact');
select task21_retry_recovery_test.assert(pg_get_function_result('public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)'::regprocedure)='jsonb','return exact');
select task21_retry_recovery_test.assert((select prosecdef and proconfig=array['search_path=public, pg_temp'] from pg_proc where oid='public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)'::regprocedure),'security/search path exact');
select task21_retry_recovery_test.assert(has_function_privilege('service_role','public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)','execute') and not has_function_privilege('public','public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)','execute') and not has_function_privilege('anon','public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)','execute') and not has_function_privilege('authenticated','public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)','execute'),'service-role-only privilege');
select task21_retry_recovery_test.assert((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='creator_publishing_requeue_retry_exhausted_scheduler_event'),'one recovery function');
select task21_retry_recovery_test.assert((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.oid::regprocedure::text not in(select signature from public.task21_recovery_pre_function_snapshot)),'only one public function added');
select task21_retry_recovery_test.assert(not exists(select 1 from public.task21_recovery_pre_function_snapshot s left join pg_proc p on p.oid=to_regprocedure(s.signature) where p.oid is null or s.definition is distinct from pg_get_functiondef(p.oid) or s.acl is distinct from coalesce(p.proacl::text,'')),'existing function definitions and ACLs unchanged');
select task21_retry_recovery_test.assert(not exists(select 1 from public.task21_recovery_pre_relation_snapshot s left join pg_class c on c.oid=to_regclass(s.relation_name) where c.oid is null or s.relkind<>c.relkind or s.relrowsecurity<>c.relrowsecurity or s.relacl is distinct from coalesce(c.relacl::text,'')),'relations unchanged');
select task21_retry_recovery_test.assert(not exists(select 1 from public.task21_recovery_pre_constraint_snapshot s left join pg_constraint c on c.oid=s.constraint_oid where c.oid is null or s.definition is distinct from pg_get_constraintdef(c.oid)),'constraints unchanged');
select task21_retry_recovery_test.assert(not exists(select 1 from public.task21_recovery_pre_index_snapshot s left join pg_class c on c.oid=s.index_oid where c.oid is null or s.definition is distinct from pg_get_indexdef(c.oid)),'indexes unchanged');
select task21_retry_recovery_test.assert(not exists(select 1 from public.task21_recovery_pre_trigger_snapshot s left join pg_trigger t on t.oid=s.trigger_oid where t.oid is null or s.definition is distinct from pg_get_triggerdef(t.oid)),'triggers unchanged');
with d as (select lower(pg_get_functiondef('public.creator_publishing_requeue_retry_exhausted_scheduler_event(uuid,text,text)'::regprocedure)) b) select task21_retry_recovery_test.assert(regexp_count(b,'transaction_timestamp\(\)')=1 and position('clock_timestamp()' in b)=0 and regexp_count(b,'pg_advisory_xact_lock')=1 and position('creator_scheduler_retry_recovery:' in b)>0 and position('for update of plan_source' in b)>0 and position('for update of job_source' in b)>position('for update of plan_source' in b) and position('for update of event_source' in b)>position('for update of job_source' in b),'timestamp/advisory/lock order exact') from d;

create or replace procedure task21_retry_recovery_test.seed(n int,event_type text default 'publish_due',mode text default 'assisted',state text default 'scheduled_internally') language plpgsql as $$
declare c uuid:='21500000-0000-4000-8000-000000000101'; t timestamptz:=transaction_timestamp(); intended timestamptz:=t-interval '10 minutes'; operator_due timestamptz:=t-interval '70 minutes';
begin
 insert into public.creator_platform_accounts(id,creator_id,platform,platform_username,verification_status,verification_attested_at) values(task21_retry_recovery_test.uuid(1,n),c,'onlyfans','recovery_'||n,'creator_attested',t);
 insert into public.creator_publishing_content_packages(id,creator_id,platform_account_id,target_platform,title,caption_body,ai_flag,ai_detail,second_person_present,compliance_status,compliance_policy_version,creator_approval_status,platform_meta) values(task21_retry_recovery_test.uuid(2,n),c,task21_retry_recovery_test.uuid(1,n),'onlyfans','r'||n,'r','none','{}',false,'pending','unassigned','pending','{}');
 insert into public.creator_publishing_plans(id,creator_id,status,idempotency_key,request_fingerprint,registry_version) values(task21_retry_recovery_test.uuid(3,n),c,'scheduled','recovery-plan-'||lpad(n::text,4,'0'),md5(('p'||n)::text)||md5(('p'||n)::text),'task14.20260711.001');
 insert into public.creator_publishing_platform_jobs(id,publishing_plan_id,creator_id,content_package_id,platform_account_id,target_platform,publishing_mode,job_state,source_package_updated_at,source_package_fingerprint,capability_registry_version,original_request_fingerprint,schedule_revision,intended_publish_at,schedule_timezone,operator_due_at,scheduled_at,scheduled_by) values(task21_retry_recovery_test.uuid(4,n),task21_retry_recovery_test.uuid(3,n),c,task21_retry_recovery_test.uuid(2,n),task21_retry_recovery_test.uuid(1,n),'onlyfans',mode,state,t,md5(('s'||n)::text)||md5(('s'||n)::text),'task14.20260711.001',md5(('r'||n)::text)||md5(('r'||n)::text),1,intended,'UTC',operator_due,t,c);
 insert into public.creator_publishing_scheduler_events(id,creator_id,publishing_plan_id,platform_job_id,event_type,status,due_at,schedule_revision,processing_attempts,processed_at,safe_error_code) values(task21_retry_recovery_test.uuid(5,n),c,task21_retry_recovery_test.uuid(3,n),task21_retry_recovery_test.uuid(4,n),event_type,'blocked',case when event_type='operator_due' then operator_due else intended end,1,3,t-interval '1 minute','SCHEDULER_RETRY_EXHAUSTED');
 insert into public.creator_publishing_queue_tasks(id,content_package_id,creator_id,target_platform,platform_account_id,status,created_at,updated_at) values(task21_retry_recovery_test.uuid(8,n),task21_retry_recovery_test.uuid(2,n),c,'onlyfans',task21_retry_recovery_test.uuid(1,n),'ready_for_handoff',t,t);
end $$;

-- Existing claim ceiling remains after recovery.
call task21_retry_recovery_test.seed(60);
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,60),'recovery_claim_0060','TRANSIENT_INFRASTRUCTURE_RECOVERED')='{"ok":true,"code":"SCHEDULER_RETRY_RECOVERY_REQUEUED","idempotent":false}'::jsonb,'recovery succeeds');
create temp table c1 as select * from public.creator_publishing_claim_due_scheduler_events(1,1); update public.creator_publishing_scheduler_events set locked_at=transaction_timestamp()-interval '2 minutes' where id=task21_retry_recovery_test.uuid(5,60);
create temp table c2 as select * from public.creator_publishing_claim_due_scheduler_events(1,1); update public.creator_publishing_scheduler_events set locked_at=transaction_timestamp()-interval '2 minutes' where id=task21_retry_recovery_test.uuid(5,60);
create temp table c3 as select * from public.creator_publishing_claim_due_scheduler_events(1,1); update public.creator_publishing_scheduler_events set locked_at=transaction_timestamp()-interval '2 minutes' where id=task21_retry_recovery_test.uuid(5,60);
create temp table c4 as select * from public.creator_publishing_claim_due_scheduler_events(1,1);
select task21_retry_recovery_test.assert((select count(*)=1 from c1) and (select count(*)=1 from c2) and (select count(*)=1 from c3) and (select count(*)=0 from c4),'recovered event gets claims 1 2 3 and no fourth');
select task21_retry_recovery_test.assert((select status='blocked' and processing_attempts=3 and safe_error_code='SCHEDULER_RETRY_EXHAUSTED' from public.creator_publishing_scheduler_events where id=task21_retry_recovery_test.uuid(5,60)),'recovered event exhausts again');

-- Seed valid transition families and failures.
call task21_retry_recovery_test.seed(1,'publish_due','assisted','scheduled_internally');
call task21_retry_recovery_test.seed(2,'operator_due','assisted','scheduled_internally');
call task21_retry_recovery_test.seed(3,'publish_due','assisted','awaiting_operator');
call task21_retry_recovery_test.seed(4,'publish_due','direct','ready_to_publish');
call task21_retry_recovery_test.seed(5,'publish_due','planner','package_ready');
call task21_retry_recovery_test.seed(6);
call task21_retry_recovery_test.seed(7);
insert into public.creator_publishing_scheduler_events(id,creator_id,publishing_plan_id,platform_job_id,event_type,status,due_at,schedule_revision,processing_attempts,processed_at,safe_error_code) select task21_retry_recovery_test.uuid(6,7),creator_id,publishing_plan_id,id,'operator_due','blocked',operator_due_at,1,3,transaction_timestamp()-interval '1 minute','SCHEDULER_RETRY_EXHAUSTED' from public.creator_publishing_platform_jobs where id=task21_retry_recovery_test.uuid(4,7);
create temp table sibling_before as select to_jsonb(e) v from public.creator_publishing_scheduler_events e where id=task21_retry_recovery_test.uuid(6,7);

call task21_retry_recovery_test.seed(10); update public.creator_publishing_scheduler_events set status='pending',processed_at=null,safe_error_code=null where id=task21_retry_recovery_test.uuid(5,10);
call task21_retry_recovery_test.seed(11); update public.creator_publishing_scheduler_events set status='processing',lock_token=task21_retry_recovery_test.uuid(7,11),locked_at=transaction_timestamp() where id=task21_retry_recovery_test.uuid(5,11);
call task21_retry_recovery_test.seed(12); update public.creator_publishing_scheduler_events set status='processed',safe_error_code=null where id=task21_retry_recovery_test.uuid(5,12);
call task21_retry_recovery_test.seed(13); update public.creator_publishing_scheduler_events set status='superseded',processed_at=null,safe_error_code=null,superseded_at=transaction_timestamp() where id=task21_retry_recovery_test.uuid(5,13);
call task21_retry_recovery_test.seed(14); update public.creator_publishing_scheduler_events set status='cancelled',processed_at=null,safe_error_code=null,cancelled_at=transaction_timestamp() where id=task21_retry_recovery_test.uuid(5,14);
call task21_retry_recovery_test.seed(15); update public.creator_publishing_scheduler_events set safe_error_code='OTHER_BLOCK' where id=task21_retry_recovery_test.uuid(5,15);
call task21_retry_recovery_test.seed(16); update public.creator_publishing_scheduler_events set processing_attempts=2 where id=task21_retry_recovery_test.uuid(5,16);
call task21_retry_recovery_test.seed(17); update public.creator_publishing_scheduler_events set due_at=transaction_timestamp()+interval '1 hour' where id=task21_retry_recovery_test.uuid(5,17);
call task21_retry_recovery_test.seed(18); update public.creator_publishing_plans set status='cancelled',cancelled_at=transaction_timestamp() where id=task21_retry_recovery_test.uuid(3,18);
call task21_retry_recovery_test.seed(19); update public.creator_publishing_platform_jobs set cancelled_at=transaction_timestamp(),cancelled_by='21500000-0000-4000-8000-000000000101',cancellation_reason='test cancellation' where id=task21_retry_recovery_test.uuid(4,19);
call task21_retry_recovery_test.seed(20); update public.creator_publishing_platform_jobs set schedule_revision=2 where id=task21_retry_recovery_test.uuid(4,20);
call task21_retry_recovery_test.seed(21,'operator_due','direct','ready_to_publish');
call task21_retry_recovery_test.seed(22,'operator_due','assisted','due_now');
call task21_retry_recovery_test.seed(23,'publish_due','assisted','due_now');
call task21_retry_recovery_test.seed(24,'publish_due','direct','retry_scheduled');
call task21_retry_recovery_test.seed(25,'publish_due','planner','ready_for_export');
call task21_retry_recovery_test.seed(26,'operator_due','assisted','scheduled_internally'); update public.creator_publishing_scheduler_events set due_at=due_at-interval '1 minute' where id=task21_retry_recovery_test.uuid(5,26);
call task21_retry_recovery_test.seed(27,'publish_due','assisted','scheduled_internally'); update public.creator_publishing_scheduler_events set due_at=due_at-interval '1 minute' where id=task21_retry_recovery_test.uuid(5,27);
call task21_retry_recovery_test.seed(29);
call task21_retry_recovery_test.seed(30,'publish_due','assisted','published_direct');
call task21_retry_recovery_test.seed(31,'publish_due','assisted','confirmed_posted_manual');
call task21_retry_recovery_test.seed(32,'publish_due','assisted','exported');
call task21_retry_recovery_test.seed(33,'publish_due','assisted','direct_publish_failed');
call task21_retry_recovery_test.seed(34,'publish_due','assisted','failed_manual_upload');
call task21_retry_recovery_test.seed(35,'publish_due','assisted','skipped');
call task21_retry_recovery_test.seed(36,'publish_due','assisted','blocked');
call task21_retry_recovery_test.seed(37,'publish_due','assisted','platform_rejected');
call task21_retry_recovery_test.seed(38,'publish_due','assisted','archived');
call task21_retry_recovery_test.seed(70);
call task21_retry_recovery_test.seed(71);

create temp table failed_before as select id,to_jsonb(e) v from public.creator_publishing_scheduler_events e where id in(select task21_retry_recovery_test.uuid(5,n) from generate_series(10,38)n);
create temp table non_event_before as select 'account' t,id::text k,to_jsonb(x) v from public.creator_platform_accounts x where id::text like '21300000-%' union all select 'package',id::text,to_jsonb(x) from public.creator_publishing_content_packages x where id::text like '21300000-%' union all select 'plan',id::text,to_jsonb(x) from public.creator_publishing_plans x where id::text like '21300000-%' union all select 'job',id::text,to_jsonb(x) from public.creator_publishing_platform_jobs x where id::text like '21300000-%' union all select 'queue',id::text,to_jsonb(x) from public.creator_publishing_queue_tasks x where id::text like '21300000-%' union all select 'capability',platform,to_jsonb(x) from public.creator_publishing_platform_capabilities x union all select 'generation',id::text,to_jsonb(x) from public.generations x;

-- Exact mutation, audit, idempotency and cycles.
create temp table preserve1 as select id,creator_id,publishing_plan_id,platform_job_id,event_type,due_at,schedule_revision,created_at,superseded_at,cancelled_at,processed_at cycle from public.creator_publishing_scheduler_events where id=task21_retry_recovery_test.uuid(5,1);
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0001','TRANSIENT_INFRASTRUCTURE_RECOVERED')='{"ok":true,"code":"SCHEDULER_RETRY_RECOVERY_REQUEUED","idempotent":false}'::jsonb,'first success exact');
select task21_retry_recovery_test.assert((select status='pending' and processing_attempts=0 and processed_at is null and safe_error_code is null and lock_token is null and locked_at is null from public.creator_publishing_scheduler_events where id=task21_retry_recovery_test.uuid(5,1)),'mutation exact');
select task21_retry_recovery_test.assert((select row(e.id,e.creator_id,e.publishing_plan_id,e.platform_job_id,e.event_type,e.due_at,e.schedule_revision,e.created_at,e.superseded_at,e.cancelled_at) is not distinct from row(p.id,p.creator_id,p.publishing_plan_id,p.platform_job_id,p.event_type,p.due_at,p.schedule_revision,p.created_at,p.superseded_at,p.cancelled_at) from public.creator_publishing_scheduler_events e cross join preserve1 p where e.id=p.id),'preserved fields exact');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0001','TRANSIENT_INFRASTRUCTURE_RECOVERED')='{"ok":true,"code":"SCHEDULER_RETRY_RECOVERY_REQUEUED","idempotent":true}'::jsonb,'exact replay');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0001','DEPENDENCY_RESTORED')->>'code'='SCHEDULER_RETRY_RECOVERY_IDEMPOTENCY_CONFLICT','same key different reason conflict');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'different_key_0001','TRANSIENT_INFRASTRUCTURE_RECOVERED')->>'code'='SCHEDULER_RETRY_RECOVERY_NOT_ELIGIBLE','different key before new cycle fails');
select task21_retry_recovery_test.assert((select count(*)=1 and bool_and(actor_id is null and actor_role='scheduler_operator' and idempotency_key='recovery_key_0001' and array(select jsonb_object_keys(before_state) order by 1)=array['due_at','event_type','processed_at','processing_attempts','reason_code','safe_error_code','schedule_revision','status']::text[] and array(select jsonb_object_keys(after_state) order by 1)=array['due_at','event_type','processing_attempts','reason_code','safe_error_code','schedule_revision','status']::text[] and before_state->>'reason_code'='TRANSIENT_INFRASTRUCTURE_RECOVERED' and created_at=(select updated_at from public.creator_publishing_scheduler_events where id=task21_retry_recovery_test.uuid(5,1))) from public.creator_publishing_audit_events where entity_id=task21_retry_recovery_test.uuid(5,1) and action='creator_publishing_scheduler_event_retry_requeued'),'audit shape and timestamp exact');
update public.creator_publishing_scheduler_events set status='processing',lock_token=task21_retry_recovery_test.uuid(7,1),locked_at=transaction_timestamp() where id=task21_retry_recovery_test.uuid(5,1);
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0001','TRANSIENT_INFRASTRUCTURE_RECOVERED')->>'idempotent'='true','replay after processing');
update public.creator_publishing_scheduler_events set status='processed',processed_at=transaction_timestamp(),lock_token=null,locked_at=null where id=task21_retry_recovery_test.uuid(5,1);
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0001','TRANSIENT_INFRASTRUCTURE_RECOVERED')->>'idempotent'='true','replay after processed');
update public.creator_publishing_scheduler_events set status='blocked',processing_attempts=3,processed_at=(select (before_state->>'processed_at')::timestamptz+interval '1 second' from public.creator_publishing_audit_events where entity_id=task21_retry_recovery_test.uuid(5,1) and action='creator_publishing_scheduler_event_retry_requeued' and idempotency_key='recovery_key_0001'),safe_error_code='SCHEDULER_RETRY_EXHAUSTED' where id=task21_retry_recovery_test.uuid(5,1);
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0001','DEPENDENCY_RESTORED')->>'code'='SCHEDULER_RETRY_RECOVERY_IDEMPOTENCY_CONFLICT','old key different reason conflicts on later cycle');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0001','TRANSIENT_INFRASTRUCTURE_RECOVERED')='{"ok":false,"code":"SCHEDULER_RETRY_RECOVERY_IDEMPOTENCY_KEY_STALE"}'::jsonb,'old key stale on later cycle');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,1),'recovery_key_0003','DEPENDENCY_RESTORED')->>'idempotent'='false','new key succeeds later cycle');
select task21_retry_recovery_test.assert((select count(*)=2 and count(distinct before_state->>'processed_at')=2 from public.creator_publishing_audit_events where entity_id=task21_retry_recovery_test.uuid(5,1) and action='creator_publishing_scheduler_event_retry_requeued'),'processed_at distinguishes cycles');

-- Exact compatible families and trimming.
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,2),'recovery_key_0002','MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_REQUEUED','operator_due succeeds');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,3),'recovery_key_0003','MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_REQUEUED','assisted publish succeeds');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,4),'recovery_key_0004','CONFIGURATION_CORRECTED')->>'code'='SCHEDULER_RETRY_RECOVERY_REQUEUED','direct publish succeeds');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,5),'recovery_key_0005','DEPENDENCY_RESTORED')->>'code'='SCHEDULER_RETRY_RECOVERY_REQUEUED','planner publish succeeds');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,6),'  recovery_key_0006  ','  MANUAL_RETRY_APPROVED  ')->>'code'='SCHEDULER_RETRY_RECOVERY_REQUEUED','trim accepted');
select task21_retry_recovery_test.assert((select idempotency_key='recovery_key_0006' and before_state->>'reason_code'='MANUAL_RETRY_APPROVED' from public.creator_publishing_audit_events where entity_id=task21_retry_recovery_test.uuid(5,6) and action='creator_publishing_scheduler_event_retry_requeued'),'trimmed values stored');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,7),'recovery_key_0007','MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_REQUEUED','sibling case succeeds');
select task21_retry_recovery_test.assert((select v=to_jsonb(e) from sibling_before cross join public.creator_publishing_scheduler_events e where e.id=task21_retry_recovery_test.uuid(6,7)),'sibling unchanged');

-- Finite inputs.
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(null,'recovery_key_0099','MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_EVENT_REQUIRED','null event finite');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,29),null,'MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_IDEMPOTENCY_KEY_INVALID','null key finite');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,29),'short','MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_IDEMPOTENCY_KEY_INVALID','short key finite');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,29),'bad key!','MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_IDEMPOTENCY_KEY_INVALID','bad key finite');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,29),repeat('a',129),'MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_IDEMPOTENCY_KEY_INVALID','long key finite');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,29),'recovery_key_0029',null)->>'code'='SCHEDULER_RETRY_RECOVERY_REASON_INVALID','null reason finite');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,29),'recovery_key_0029','manual_retry_approved')->>'code'='SCHEDULER_RETRY_RECOVERY_REASON_INVALID','lowercase rejected');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,29),'recovery_key_0029','ARBITRARY_REASON')->>'code'='SCHEDULER_RETRY_RECOVERY_REASON_INVALID','arbitrary reason rejected');
select task21_retry_recovery_test.assert(public.creator_publishing_requeue_retry_exhausted_scheduler_event('ffffffff-ffff-4fff-8fff-ffffffffffff','recovery_key_0099','MANUAL_RETRY_APPROVED')->>'code'='SCHEDULER_RETRY_RECOVERY_EVENT_NOT_FOUND','missing finite');

create temp table failure_results as select n,public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,n),'failure_key_'||lpad(n::text,4,'0'),'MANUAL_RETRY_APPROVED') result from generate_series(10,27)n union all select n,public.creator_publishing_requeue_retry_exhausted_scheduler_event(task21_retry_recovery_test.uuid(5,n),'failure_key_'||lpad(n::text,4,'0'),'MANUAL_RETRY_APPROVED') from generate_series(30,38)n;
select task21_retry_recovery_test.assert((select bool_and(result='{"ok":false,"code":"SCHEDULER_RETRY_RECOVERY_NOT_ELIGIBLE"}'::jsonb) from failure_results),'ineligible matrix finite');
select task21_retry_recovery_test.assert(not exists(select 1 from failed_before s join public.creator_publishing_scheduler_events e using(id) where s.v is distinct from to_jsonb(e)),'ineligible events unchanged');
select task21_retry_recovery_test.assert(not exists(select 1 from public.creator_publishing_audit_events where action='creator_publishing_scheduler_event_retry_requeued' and entity_id in(select task21_retry_recovery_test.uuid(5,n) from generate_series(10,38)n)),'ineligible no audits');
with current_non_event as (select 'account' t,id::text k,to_jsonb(x) v from public.creator_platform_accounts x where id::text like '21300000-%' union all select 'package',id::text,to_jsonb(x) from public.creator_publishing_content_packages x where id::text like '21300000-%' union all select 'plan',id::text,to_jsonb(x) from public.creator_publishing_plans x where id::text like '21300000-%' union all select 'job',id::text,to_jsonb(x) from public.creator_publishing_platform_jobs x where id::text like '21300000-%' union all select 'queue',id::text,to_jsonb(x) from public.creator_publishing_queue_tasks x where id::text like '21300000-%' union all select 'capability',platform,to_jsonb(x) from public.creator_publishing_platform_capabilities x union all select 'generation',id::text,to_jsonb(x) from public.generations x),delta as ((select * from current_non_event except select * from non_event_before) union all(select * from non_event_before except select * from current_non_event)) select task21_retry_recovery_test.assert(not exists(select 1 from delta),'no unrelated mutation');
select task21_retry_recovery_test.assert(not exists(select 1 from public.creator_publishing_scheduler_idempotency where idempotency_key like 'recovery_%' or idempotency_key like 'failure_%'),'no scheduler idempotency mutation');
select task21_retry_recovery_test.assert(not exists(select 1 from public.task21_recovery_pre_data_snapshot s join public.creator_publishing_audit_events a on s.entity_type='audit' and s.entity_id=a.id::text where s.row_data is distinct from to_jsonb(a)),'historical audit rows unchanged');
select task21_retry_recovery_test.assert(not exists(select 1 from public.task21_recovery_pre_data_snapshot s join public.creator_publishing_scheduler_idempotency i on s.entity_type='idempotency' and s.entity_id=i.creator_id::text||':'||i.action_type||':'||i.idempotency_key where s.row_data is distinct from to_jsonb(i)),'historical scheduler idempotency rows unchanged');
select task21_retry_recovery_test.assert((select count(*)=2 and bool_and(status='blocked' and processing_attempts=3 and safe_error_code='SCHEDULER_RETRY_EXHAUSTED') from public.creator_publishing_scheduler_events where id in(task21_retry_recovery_test.uuid(5,70),task21_retry_recovery_test.uuid(5,71))),'concurrency fixtures ready');
\echo 'TASK21_SCHEDULER_RETRY_RECOVERY_ASSERTIONS_PASSED'
