import assert from 'node:assert/strict'
import { normalizeCancelPlanRequest, normalizeSchedulePlanRequest, resolveScheduleLocalDateTime, confirmCancelledReconciliation, confirmScheduleReconciliation } from '../../../lib/creator-publishing-queue/scheduling/validation'
import { parseCancelPlanRpcResult, parseScheduleRpcResult } from '../../../lib/creator-publishing-queue/scheduling/response'
import { cancelPlanCore, schedulePlanCore } from '../../../lib/creator-publishing-queue/scheduling/serviceCore'
const creator='00000000-0000-4000-8000-000000000001', plan='70000000-0000-4000-8000-000000000001', job='80000000-0000-4000-8000-000000000001', pkg='90000000-0000-4000-8000-000000000001', acct='91000000-0000-4000-8000-000000000001', task='92000000-0000-4000-8000-000000000001'
function row(over:any={}){ return {plan:{id:plan,creator_id:creator,status:'draft',cancelled_at:null,cancellation_reason:null,registry_version:'onlyfans-assisted-v1',...over.plan},jobs:[{id:job,creator_id:creator,publishing_plan_id:plan,content_package_id:pkg,platform_account_id:acct,target_platform:'onlyfans',publishing_mode:'assisted',job_state:'draft',schedule_revision:null,intended_publish_at:null,operator_due_at:null,schedule_timezone:null,scheduled_at:null,scheduled_by:null,cancelled_at:null,source_package_fingerprint:'fp',source_package_updated_at:'2026-07-20T00:00:00.000Z',capability_registry_version:'onlyfans-assisted-v1',...over.job},...(over.extraJobs??[])],idempotency:over.idempotency??null,events:over.events??[],siblings:over.siblings,queue:over.queue??[{id:task,content_package_id:pkg,creator_id:creator,platform_account_id:acct,target_platform:'onlyfans',status:'ready_for_handoff',claimed_by:null,claimed_at:null,claim_token:null,claim_expires_at:null,posted_by:null,posted_at:null,posted_confirmation:false,final_post_url:null,final_post_url_skip_reason:null,proof_screenshot_storage_key:null,skip_or_fail_reason:null}],capability:{platform:'onlyfans',registry_version:'onlyfans-assisted-v1',publishing_mode:'assisted',availability_status:'available',human_publishing_required:true,connector_can_publish_immediately:false,connector_can_schedule_directly:false,connector_can_upload_media:false,human_operator_queue_supported:true,...over.capability},creatorVerification:{creator_id:creator,status:'verified',...over.creatorVerification},account:{id:acct,creator_id:creator,platform:'onlyfans',verification_status:'verified',...over.account},consent:{creator_id:creator,status:'granted',attestation_version:'server-version',attestation_text_sha256:'a'.repeat(64),revoked_at:null,...over.consent},pkg:{id:pkg,creator_id:creator,platform_account_id:acct,target_platform:'onlyfans',updated_at:'2026-07-20T00:00:00.000Z',creator_approval_status:'approved',compliance_status:'passed',compliance_policy_version:'policy-v1',second_person_present:false,...over.pkg},reviews:over.reviews??[{content_package_id:pkg,outcome:'pass',review_source:'automated',compliance_policy_version:'policy-v1',escalated_approval_reason:null,created_at:'2026-07-20T00:00:00.000Z',id:'1'}],performers:over.performers??[],fingerprint:over.fingerprint??'fp',rpcCalls:[],rpcData:over.rpcData} }
function admin(t:any){ const all=(name:string)=> name==='creator_publishing_plans'?[t.plan]:name==='creator_publishing_platform_jobs'?(t.siblings??t.jobs):name==='creator_publishing_scheduler_idempotency'?(t.idempotency?[t.idempotency]:[]):name==='creator_publishing_scheduler_events'?t.events:name==='creator_publishing_queue_tasks'?t.queue:name==='creator_publishing_platform_capabilities'?[t.capability]:name==='creator_publishing_creator_verifications'?[t.creatorVerification]:name==='creator_platform_accounts'?[t.account]:name==='creator_publishing_ai_twin_consents'?[t.consent]:name==='creator_publishing_content_packages'?[t.pkg]:name==='creator_publishing_compliance_reviews'?t.reviews:name==='creator_publishing_co_performer_records'?t.performers:[]; return { from(name:string){ let rows=all(name); const b:any={select(){return b},eq(col:string,val:any){rows=rows.filter((r:any)=>r?.[col]===val);return b},in(col:string,vals:any[]){rows=rows.filter((r:any)=>vals.includes(r?.[col]));return b},not(){return b},order(){return b},limit(){return b},maybeSingle:async()=>({data:rows[0]??null,error:null}),then:(resolve:any)=>resolve({data:rows,error:null})}; return b }, rpc:async(name:string,args:any)=>{ t.rpcCalls.push({name,args}); if(name==='creator_publishing_autopost_source_fingerprint') return {data:t.fingerprint,error:null}; return {data:t.rpcData??{ok:true,action_type:name.includes('cancel')?'cancel_plan':'schedule',publishing_plan_id:plan,success_count:1,failure_count:0,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true,operator_claim_cleanup:{performed:false}}],task17a_queue_claims_cleared:0,idempotent:!!t.idempotency},error:null} } } }
const deps=(t:any,auth=creator)=>({getAuthenticatedCreatorId:async()=>auth,getAdminClient:()=>admin(t),getConsent:async()=>({version:'server-version',textSha256:'a'.repeat(64)}),now:()=>new Date('2026-07-20T00:00:00Z')})
const sched={publishingPlanId:plan,platformJobId:job,localDateTime:{date:'2026-07-20',time:'03:00'},scheduleTimezone:'UTC',idempotencyKey:'abcdefgh'}
assert.equal((await schedulePlanCore(sched,deps(row(),null))).code,'UNAUTHENTICATED')
let lazy=false; await schedulePlanCore(sched,{...deps(row(),null),getAdminClient:()=>{lazy=true}} as any); assert.equal(lazy,false)
for(const bad of [{...sched,creatorId:creator},{...sched,unknown:true}]) assert.throws(()=>normalizeSchedulePlanRequest(bad))
for(const [label,over] of Object.entries({crossCreatorPlan:{plan:{creator_id:'bad'}},crossCreatorJob:{job:{creator_id:'bad'}},mismatch:{job:{publishing_plan_id:'bad'}},zeroActive:{job:{job_state:'archived'}},multiple:{extraJobs:[{id:'80000000-0000-4000-8000-000000000002',creator_id:creator,publishing_plan_id:plan,content_package_id:'x',platform_account_id:acct,target_platform:'onlyfans',publishing_mode:'assisted',job_state:'draft'}]},nonOnly:{job:{target_platform:'fanvue'}},nonAssisted:{job:{publishing_mode:'direct'}},nonDraftPlan:{plan:{status:'scheduled'}},nonDraftJob:{job:{job_state:'scheduled_internally'}},scheduled:{job:{schedule_revision:1}},cancelled:{plan:{cancelled_at:'x'}},dirty:{job:{intended_publish_at:'x'}},event:{events:[{id:'e',platform_job_id:job,status:'pending'}]},sibling:{siblings:[row().jobs[0],{id:'s',job_state:'draft',content_package_id:pkg}]},cap:{capability:{availability_status:'disabled'}},registry:{capability:{registry_version:'wrong'}},verification:{creatorVerification:{status:'unverified'}},account:{account:{verification_status:'revoked'}},consent:{consent:{status:'revoked'}},approval:{pkg:{creator_approval_status:'pending'}},compliance:{reviews:[{content_package_id:pkg,outcome:'manual_review',review_source:'automated',compliance_policy_version:'policy-v1',created_at:'2026-07-20T01:00:00Z',id:'2'}]},laterBlock:{reviews:[{content_package_id:pkg,outcome:'pass',review_source:'automated',compliance_policy_version:'policy-v1',created_at:'2026-07-20T00:00:00Z',id:'1'},{content_package_id:pkg,outcome:'block',review_source:'automated',compliance_policy_version:'policy-v1',created_at:'2026-07-20T01:00:00Z',id:'3'}]},performer:{pkg:{second_person_present:true},performers:[{content_package_id:pkg,platform_release_confirmed:false,release_document_reference:'doc'}]},timestamp:{pkg:{updated_at:'later'}},policy:{pkg:{compliance_policy_version:null}},fingerprint:{fingerprint:'bad'},queue:{queue:[{id:task,content_package_id:pkg,creator_id:creator,platform_account_id:acct,target_platform:'onlyfans',status:'ready_for_handoff',claimed_by:'op'}]}})){ const r=await schedulePlanCore(sched,deps(row(over as any))); assert.equal(r.ok,false,label) }
const noPerformer=row({pkg:{second_person_present:false},performers:[]}); assert.equal((await schedulePlanCore(sched,deps(noPerformer))).ok,true,'second_person_present false needs no performer'); const performerOk=row({pkg:{second_person_present:true},performers:[{content_package_id:pkg,platform_release_confirmed:true,release_document_reference:'doc'}]}); assert.equal((await schedulePlanCore(sched,deps(performerOk))).ok,true,'second_person_present true accepts release records'); const escalated=row({pkg:{compliance_status:'escalated_approved'},reviews:[{content_package_id:pkg,outcome:'escalate',review_source:'human',compliance_policy_version:'policy-v1',escalated_approval_reason:'approved by reviewer',created_at:'2026-07-20T00:00:00Z',id:'4'}]}); assert.equal((await schedulePlanCore(sched,deps(escalated))).ok,true,'escalated_approved requires human escalate reason'); const fresh=row(); const freshResult=await schedulePlanCore(sched,deps(fresh)); assert.equal(freshResult.ok,true); assert.equal(fresh.rpcCalls.at(-1).name,'creator_publishing_schedule_plan'); assert.equal(fresh.rpcCalls.at(-1).args.p_action_type,'schedule'); assert.deepEqual(fresh.rpcCalls.at(-1).args.p_target_job_ids,[job]); assert.deepEqual(fresh.rpcCalls.at(-1).args.p_expected_schedule_revisions,{})
const replay=row({idempotency:{creator_id:creator,publishing_plan_id:plan,action_type:'schedule',idempotency_key:'abcdefgh'},plan:{status:'scheduled'},job:{job_state:'scheduled_internally',schedule_revision:1,intended_publish_at:'2026-07-20T03:00:00.000Z',operator_due_at:'2026-07-20T02:00:00.000Z',schedule_timezone:'UTC',scheduled_at:'x',scheduled_by:creator},queue:[{id:task,content_package_id:pkg,creator_id:creator,platform_account_id:acct,target_platform:'onlyfans',status:'scheduled_internally',posted_by:null,posted_at:null,posted_confirmation:false,final_post_url:null,final_post_url_skip_reason:null,proof_screenshot_storage_key:null,skip_or_fail_reason:null}]}); const rr=await schedulePlanCore(sched,deps(replay)); assert.equal(rr.ok,true); assert.equal((rr as any).idempotent,true); assert.equal(replay.rpcCalls.at(-1).name,'creator_publishing_schedule_plan')
assert.equal((await schedulePlanCore(sched,deps(row({plan:{status:'scheduled'},job:{job_state:'scheduled_internally',schedule_revision:1,intended_publish_at:'2026-07-20T03:00:00.000Z',schedule_timezone:'UTC'}})))).ok,false,'absent schedule key conflicts')
assert.equal((await schedulePlanCore({...sched,idempotencyKey:'otherkey'},deps(replay))).ok,false,'nonmatching schedule key conflicts')
assert.equal(parseScheduleRpcResult({ok:true,action_type:'schedule',publishing_plan_id:plan,success_count:1,failure_count:0,idempotent:true,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true,operator_claim_cleanup:{performed:false}}]},{planId:plan,jobId:job,intendedPublishAtUtc:'x',operatorDueAtUtc:'y',idempotent:true}).ok,true)
assert.equal((parseScheduleRpcResult({ok:true,action_type:'schedule',publishing_plan_id:plan,success_count:1,failure_count:0,idempotent:false,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true,operator_claim_cleanup:{performed:true,queue_task_id:task,previous_status:'claimed',resulting_status:'scheduled_internally',reason:'scheduled_before_operator_due'}}]},{planId:plan,jobId:job,intendedPublishAtUtc:'x',operatorDueAtUtc:'y',idempotent:false,queueTaskId:task}) as any).operatorClaimCleared,true)
for(const bad of [{ok:true,action_type:'schedule',publishing_plan_id:'bad',success_count:1,failure_count:0,idempotent:false,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true,operator_claim_cleanup:{performed:false}}]},{ok:true,action_type:'schedule',publishing_plan_id:plan,success_count:1,failure_count:0,idempotent:true,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:false,operator_claim_cleanup:{performed:false}}]},{ok:true,action_type:'schedule',publishing_plan_id:plan,success_count:1,failure_count:0,idempotent:false,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true,operator_claim_cleanup:{performed:true,queue_task_id:'bad'}}]},{ok:true,action_type:'schedule',publishing_plan_id:plan,success_count:1,failure_count:0,idempotent:false,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true,operator_claim_cleanup:{performed:true,queue_task_id:task,previous_status:'claimed',resulting_status:'scheduled_internally',reason:'rescheduled_before_operator_due'}}]}]) assert.equal(parseScheduleRpcResult(bad,{planId:plan,jobId:job,intendedPublishAtUtc:'x',operatorDueAtUtc:'y',idempotent:false}).ok,false)
assert.equal(resolveScheduleLocalDateTime({date:'2026-07-20',time:'03:00'},'UTC',new Date('2026-07-20T00:00:00Z')).intendedPublishAtUtc,'2026-07-20T03:00:00.000Z')
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-03-08',time:'02:30'},'America/New_York',new Date('2026-01-01T00:00:00Z'))); assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-11-01',time:'01:30'},'America/New_York',new Date('2026-01-01T00:00:00Z')))
const cross=resolveScheduleLocalDateTime({date:'2026-11-01',time:'01:30',utcOffsetMinutes:-300},'America/New_York',new Date('2026-01-01T00:00:00Z')); assert.notEqual(cross.publicationUtcOffsetMinutes,cross.operatorDueUtcOffsetMinutes)
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-02-30',time:'03:00'},'UTC')); assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-07-20',time:'00:30'},'UTC',new Date('2026-07-20T00:00:00Z')))
assert.equal(normalizeCancelPlanRequest({publishingPlanId:plan,cancellationReason:' ok ',idempotencyKey:'cancelkey'}).cancellationReason,'ok'); assert.throws(()=>normalizeCancelPlanRequest({publishingPlanId:plan,cancellationReason:' ',idempotencyKey:'cancelkey'})); assert.throws(()=>normalizeCancelPlanRequest({publishingPlanId:plan,cancellationReason:'x'.repeat(501),idempotencyKey:'cancelkey'}))
const cancelFresh=row({plan:{status:'scheduled'},job:{job_state:'scheduled_internally',schedule_revision:1}}); assert.equal((await cancelPlanCore({publishingPlanId:plan,cancellationReason:'reason',idempotencyKey:'cancelkey'},deps(cancelFresh))).ok,true); assert.equal(cancelFresh.rpcCalls.at(-1).name,'creator_publishing_cancel_plan_schedule')
const cancelReplay=row({idempotency:{creator_id:creator,publishing_plan_id:plan,action_type:'cancel_plan',idempotency_key:'cancelkey'},plan:{status:'cancelled',cancellation_reason:'reason'},job:{job_state:'archived'}}); assert.equal((await cancelPlanCore({publishingPlanId:plan,cancellationReason:'reason',idempotencyKey:'cancelkey'},deps(cancelReplay))).ok,true)
assert.equal((await cancelPlanCore({publishingPlanId:plan,cancellationReason:'other',idempotencyKey:'cancelkey'},deps(cancelReplay))).ok,false); assert.equal((await cancelPlanCore({publishingPlanId:plan,cancellationReason:'reason',idempotencyKey:'otherkey'},deps(row({plan:{status:'cancelled',cancellation_reason:'reason'},job:{job_state:'archived'}})))).ok,false)
assert.equal(parseCancelPlanRpcResult({ok:true,action_type:'cancel_plan',publishing_plan_id:plan,task17a_queue_claims_cleared:0,idempotent:false},{planId:plan,idempotent:false,countBound:1}).ok,true); assert.equal(parseCancelPlanRpcResult({ok:true,action_type:'cancel_plan',publishing_plan_id:plan,task17a_queue_claims_cleared:2,idempotent:true},{planId:plan,idempotent:true,countBound:1}).ok,false)
assert.equal(confirmScheduleReconciliation([{publishingPlanId:plan,platformJobId:job,scheduleRevision:1,intendedPublishAtUtc:'x',scheduleTimezone:'UTC',jobState:'scheduled_internally'}],{publishingPlanId:plan,platformJobId:job,intendedPublishAtUtc:'x',scheduleTimezone:'UTC'}),true)
assert.equal(confirmCancelledReconciliation([{publishingPlanId:plan,status:'cancelled',normalizedCancellationReason:'reason',allPlanJobsBelongToCreator:true,planJobRelationshipConsistent:true}],plan,'reason'),true); assert.equal(confirmCancelledReconciliation([{publishingPlanId:plan,status:'cancelled',normalizedCancellationReason:'reason',allPlanJobsBelongToCreator:false,planJobRelationshipConsistent:true}],plan,'reason'),false)
console.log('task21PlanSchedulingServices ok')
