import assert from 'node:assert/strict'
import fs from 'node:fs'
const files=['lib/creator-publishing-queue/scheduling/types.ts','lib/creator-publishing-queue/scheduling/validation.ts','lib/creator-publishing-queue/scheduling/response.ts','lib/creator-publishing-queue/scheduling/serviceCore.ts','lib/creator-publishing-queue/scheduling/service.ts','lib/creator-publishing-queue/scheduling/loaders.ts','app/api/creator-publishing-queue/scheduling/schedule/route.ts','app/api/creator-publishing-queue/scheduling/cancel-plan/route.ts','app/autopost/Task15PlanScheduling.tsx','app/autopost/page.tsx','app/autopost/Task14AutopostOrchestration.tsx','backend/creator-publishing-queue/tests/task21PlanSchedulingServices.test.ts','backend/creator-publishing-queue/tests/task21PlanSchedulingSourceContract.test.ts','backend/creator-publishing-queue/tests/task21PlanSchedulingUi.test.ts','docs/creator-publishing/task21-onlyfans-reliability-operations.md','.github/workflows/task21-onlyfans-reliability.yml']
for(const f of files) assert.ok(fs.existsSync(f),`authorized file exists ${f}`)
const service=fs.readFileSync('lib/creator-publishing-queue/scheduling/service.ts','utf8'), loaders=fs.readFileSync('lib/creator-publishing-queue/scheduling/loaders.ts','utf8'), core=fs.readFileSync('lib/creator-publishing-queue/scheduling/serviceCore.ts','utf8'), response=fs.readFileSync('lib/creator-publishing-queue/scheduling/response.ts','utf8'), validation=fs.readFileSync('lib/creator-publishing-queue/scheduling/validation.ts','utf8'), ui=fs.readFileSync('app/autopost/Task15PlanScheduling.tsx','utf8')
assert.match(service,/import "server-only"/); assert.match(loaders,/import "server-only"/); assert.doesNotMatch(core+response,/server-only|supabaseServer|getSupabaseAdmin|process\.env|cookies\(|headers\(|AI_TWIN_CONSENT|getAiTwinConsent/)
assert.doesNotMatch(validation,/server-only|supabase|serviceRole|getSupabaseAdmin|AI_TWIN_CONSENT|getAiTwinConsent/)
assert.doesNotMatch(ui,/serviceCore|response|service"|loaders/)
for(const r of ['app/api/creator-publishing-queue/scheduling/schedule/route.ts','app/api/creator-publishing-queue/scheduling/cancel-plan/route.ts']){ const s=fs.readFileSync(r,'utf8'); assert.match(s,/ensureActiveSubscription/); assert.match(s,/req\.json\(\)/); assert.doesNotMatch(s,/console\.|stack|exception|stackTrace/) }
assert.match(core,/getAuthenticatedCreatorId[\s\S]*getAdminClient/); assert.match(service,/getAuthenticatedCreatorId:creatorId/)
assert.match(validation,/protectedFields/); for(const p of ['creatorId','accountId','packageId','consentVersion','consentHash','targetPlatform','publishingMode','actionType','scheduleRevision','expectedScheduleRevisions','rpcName','credentials','tokens','cookies','authorization','headers','metadata']) assert.match(validation,new RegExp(p))
assert.match(core,/creator_publishing_schedule_plan/); assert.match(core,/creator_publishing_cancel_plan_schedule/); assert.doesNotMatch(core,/creator_publishing_cancel_job_schedule/)
assert.doesNotMatch(core+service+loaders,/\.insert\(|\.update\(|\.upsert\(|\.delete\(/)
assert.doesNotMatch(core+service+loaders+ui,/scheduler\/run|browser\.launch|puppeteer|playwright|fetch\([^)]*onlyfans|cron|CRON|process\.env/)
const wf=fs.readFileSync('.github/workflows/task21-onlyfans-reliability.yml','utf8'); assert.match(wf,/task21PlanSchedulingServices/); assert.match(wf,/task21SchedulerRunnerServices/); assert.match(wf,/vercel\.json|package\.json|package-lock\.json|supabase\/migrations|scheduler-runner\/service/)
console.log('task21PlanSchedulingSourceContract ok')
