import assert from 'node:assert/strict'
import fs from 'node:fs'
const authorized=['.github/workflows/task21-onlyfans-reliability.yml','app/api/creator-publishing-queue/scheduling/cancel-plan/route.ts','app/api/creator-publishing-queue/scheduling/schedule/route.ts','app/autopost/Task14AutopostOrchestration.tsx','app/autopost/Task15PlanScheduling.tsx','app/autopost/page.tsx','backend/creator-publishing-queue/tests/task21PlanSchedulingServices.test.ts','backend/creator-publishing-queue/tests/task21PlanSchedulingSourceContract.test.ts','backend/creator-publishing-queue/tests/task21PlanSchedulingUi.test.ts','docs/creator-publishing/task21-onlyfans-reliability-operations.md','lib/creator-publishing-queue/scheduling/loaders.ts','lib/creator-publishing-queue/scheduling/response.ts','lib/creator-publishing-queue/scheduling/service.ts','lib/creator-publishing-queue/scheduling/serviceCore.ts','lib/creator-publishing-queue/scheduling/types.ts','lib/creator-publishing-queue/scheduling/validation.ts']
for(const f of authorized) assert.ok(fs.existsSync(f),`authorized file exists ${f}`)
const service=fs.readFileSync('lib/creator-publishing-queue/scheduling/service.ts','utf8'), loaders=fs.readFileSync('lib/creator-publishing-queue/scheduling/loaders.ts','utf8'), core=fs.readFileSync('lib/creator-publishing-queue/scheduling/serviceCore.ts','utf8'), response=fs.readFileSync('lib/creator-publishing-queue/scheduling/response.ts','utf8'), validation=fs.readFileSync('lib/creator-publishing-queue/scheduling/validation.ts','utf8'), ui=fs.readFileSync('app/autopost/Task15PlanScheduling.tsx','utf8')
assert.match(service,/import "server-only"/); assert.match(loaders,/import "server-only"/); assert.doesNotMatch(core+response,/server-only|supabaseServer|getSupabaseAdmin|process\.env|cookies\(|headers\(|AI_TWIN_CONSENT|getAiTwinConsent/)
assert.doesNotMatch(validation,/server-only|supabase|serviceRole|getSupabaseAdmin|AI_TWIN_CONSENT|getAiTwinConsent/); assert.doesNotMatch(ui,/serviceCore|response|service"|loaders/)
for(const r of ['app/api/creator-publishing-queue/scheduling/schedule/route.ts','app/api/creator-publishing-queue/scheduling/cancel-plan/route.ts']){ const s=fs.readFileSync(r,'utf8'); assert.match(s,/ensureActiveSubscription/); assert.match(s,/req\.json\(\)/); assert.doesNotMatch(s,/console\.|stack|exception|stackTrace/) }
assert.match(core,/creator_publishing_scheduler_idempotency/); assert.match(core,/action_type", "schedule"|"schedule", request\.idempotencyKey/); assert.match(core,/action_type", "cancel_plan"|"cancel_plan", request\.idempotencyKey/)
assert.match(core,/creator_publishing_schedule_plan/); assert.match(core,/creator_publishing_cancel_plan_schedule/); assert.doesNotMatch(core,/creator_publishing_cancel_job_schedule/)
assert.doesNotMatch(core+service+loaders,/\.insert\(|\.update\(|\.upsert\(|\.delete\(/)
assert.match(core,/registry_version/); assert.match(core,/capability_registry_version/); assert.match(core,/creator_publishing_platform_capabilities/); assert.match(core,/creator_publishing_creator_verifications/); assert.match(core,/creator_platform_accounts/); assert.doesNotMatch(core,/creator_platform_accounts[\s\S]{0,120}revoked_at/); assert.match(core,/creator_publishing_ai_twin_consents/); assert.match(core,/creator_publishing_compliance_reviews/); assert.doesNotMatch(core,/creator_publishing_compliance_evidence/); assert.match(core,/creator_publishing_co_performer_records/); assert.match(core,/platform_release_confirmed/); assert.match(core,/release_document_reference/); assert.match(core,/source_package_updated_at/); assert.match(core,/creator_publishing_autopost_source_fingerprint/)
assert.match(loaders,/select\("id,status,cancelled_at,cancellation_reason,updated_at,registry_version"\)/); assert.doesNotMatch(loaders,/select\("[^"]*title[^"]*"\)\.eq\("creator_id"/)
assert.match(response,/operatorClaimCleared/); assert.doesNotMatch(response,/queue_task_id:/); assert.doesNotMatch(response,/operator_claim_cleanup:/)
assert.doesNotMatch(core+service+loaders+ui,/scheduler\/run|browser\.launch|puppeteer|playwright|fetch\([^)]*onlyfans|process\.env/)
const wf=fs.readFileSync('.github/workflows/task21-onlyfans-reliability.yml','utf8'); assert.match(wf,/app\/api\/creator-publishing-queue\/scheduler\/run\/route\.ts/); assert.match(wf,/task21SchedulerRunnerServices/); assert.match(wf,/task21PlanSchedulingServices/); assert.match(wf,/vercel\.json|package\.json|package-lock\.json|supabase\/migrations|scheduler-runner\/service/)
console.log('task21PlanSchedulingSourceContract ok')
