\set ON_ERROR_STOP on
\i backend/creator-publishing-queue/tests/task17aTestSupport.sql
\echo TASK17A_SCENARIO_START: ownership_creator_claim
select task17a_test.reset_fixture(920001) as fixture \gset
select public.creator_publishing_claim_onlyfans_operator_task((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','ownership01') as claim_result \gset
select task17a_test.assert(status='claimed' and claimed_by=(:'fixture'::jsonb->>'creator')::uuid and claimed_at is not null and claim_token is not null and claim_expires_at is not null, 'ownership fields populate together') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select task17a_test.assert(claim_expires_at > claimed_at and claim_expires_at <= claimed_at + interval '30 minutes', 'claim expiration within 30 minutes') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select task17a_test.assert(claim_attempt_count=1 and assigned_operator_id=(:'fixture'::jsonb->>'operator_b')::uuid, 'claim attempt increments once and assigned operator preserved') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select public.creator_publishing_claim_onlyfans_operator_task((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','ownership01') as replay_result \gset
select task17a_test.assert((select claim_attempt_count from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid)=1, 'claim replay does not increment attempts');
select task17a_test.expect_error('active claim cannot be stolen','OPERATOR_TASK_ALREADY_CLAIMED',format('select public.creator_publishing_claim_onlyfans_operator_task(%L,%L,%L,%L,%L,%L)',(:'fixture'::jsonb->>'operator_a'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','steal0001'));
select task17a_test.expect_error('same actor cannot rotate token','OPERATOR_TASK_ALREADY_CLAIMED',format('select public.creator_publishing_claim_onlyfans_operator_task(%L,%L,%L,%L,%L,%L)',(:'fixture'::jsonb->>'creator'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','rotate001'));
select task17a_test.reset_fixture(920101) as partial_fixture \gset
select task17a_test.expect_error('partial claim violates constraint','creator_publishing_queue_claim_all_or_none',format('update public.creator_publishing_queue_tasks set status=%L, claimed_by=%L where id=%L','claimed',(:'partial_fixture'::jsonb->>'creator'),(:'partial_fixture'::jsonb->>'task')));
select task17a_test.reset_fixture(920102) as nonclaimed_fixture \gset
select task17a_test.expect_error('nonclaimed cannot retain ownership','creator_publishing_queue_claim_all_or_none',format('update public.creator_publishing_queue_tasks set claimed_by=%L, claimed_at=clock_timestamp(), claim_token=%L, claim_expires_at=clock_timestamp()+interval ''10 minutes'' where id=%L',(:'nonclaimed_fixture'::jsonb->>'creator'),'92010200-0000-4000-8000-000000000001',(:'nonclaimed_fixture'::jsonb->>'task')));
select claim_token as progress_token from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid \gset
select public.creator_publishing_update_onlyfans_operator_progress((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'progress_token'::uuid,'not_started',0,'preparing',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','progress01');
select task17a_test.assert(operator_progress_state='preparing' and operator_progress_revision=1 and operator_progress_updated_by=(:'fixture'::jsonb->>'creator')::uuid and operator_progress_updated_at is not null, 'progress not_started to preparing updates actor timestamp revision') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select public.creator_publishing_update_onlyfans_operator_progress((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'progress_token'::uuid,'preparing',1,'prepared',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','progress02');
select public.creator_publishing_update_onlyfans_operator_progress((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'progress_token'::uuid,'prepared',2,'handoff_ready',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','progress03');
select task17a_test.assert(operator_progress_state='handoff_ready' and operator_progress_revision=3, 'progress reaches handoff_ready revision 3') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select task17a_test.expect_error('invalid progress transition','OPERATOR_PROGRESS_INVALID_TRANSITION',format('select public.creator_publishing_update_onlyfans_operator_progress(%L,%L,%L,%L,%L,%s,%L,%L,%L,%L)',(:'fixture'::jsonb->>'creator'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'progress_token','handoff_ready',3,'preparing',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','badtrans1'));
select task17a_test.expect_error('stale progress state','OPERATOR_PROGRESS_STALE',format('select public.creator_publishing_update_onlyfans_operator_progress(%L,%L,%L,%L,%L,%s,%L,%L,%L,%L)',(:'fixture'::jsonb->>'creator'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'progress_token','prepared',2,'handoff_ready',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','stale001'));
select task17a_test.expect_error('wrong progress owner','OPERATOR_CLAIM_TOKEN_MISMATCH',format('select public.creator_publishing_update_onlyfans_operator_progress(%L,%L,%L,%L,%L,%s,%L,%L,%L,%L)',(:'fixture'::jsonb->>'operator_a'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'progress_token','handoff_ready',3,'handoff_ready',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','wrongown1'));
select task17a_test.assert(status not in ('scheduled_on_platform','awaiting_post_confirmation','confirmed_posted_manual'), 'no Task 18 queue state written') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
\echo TASK17A_SCENARIO_START: claim_audit_prior_status_matrix
select task17a_test.reset_fixture(920201,'ready_for_handoff','draft',false) as audit_ready_fixture \gset
select status as audit_ready_prior_status from public.creator_publishing_queue_tasks where id=(:'audit_ready_fixture'::jsonb->>'task')::uuid \gset
select public.creator_publishing_claim_onlyfans_operator_task((:'audit_ready_fixture'::jsonb->>'creator')::uuid,(:'audit_ready_fixture'::jsonb->>'task')::uuid,(:'audit_ready_fixture'::jsonb->>'job')::uuid,:'audit_ready_fixture'::jsonb->>'consent_version',:'audit_ready_fixture'::jsonb->>'consent_hash','auditready1') as audit_ready_claim \gset
select task17a_test.reset_fixture(920202,'scheduled_internally','scheduled_internally',true) as audit_scheduled_fixture \gset
select task17a_test.set_valid_schedule_phase((:'audit_scheduled_fixture'::jsonb->>'job')::uuid,'after_operator_due');
select status as audit_scheduled_prior_status from public.creator_publishing_queue_tasks where id=(:'audit_scheduled_fixture'::jsonb->>'task')::uuid \gset
select public.creator_publishing_claim_onlyfans_operator_task((:'audit_scheduled_fixture'::jsonb->>'creator')::uuid,(:'audit_scheduled_fixture'::jsonb->>'task')::uuid,(:'audit_scheduled_fixture'::jsonb->>'job')::uuid,:'audit_scheduled_fixture'::jsonb->>'consent_version',:'audit_scheduled_fixture'::jsonb->>'consent_hash','auditsched1') as audit_scheduled_claim \gset
select task17a_test.reset_fixture(920203,'awaiting_operator','awaiting_operator',true) as audit_awaiting_fixture \gset
select task17a_test.set_valid_schedule_phase((:'audit_awaiting_fixture'::jsonb->>'job')::uuid,'after_operator_due');
select status as audit_awaiting_prior_status from public.creator_publishing_queue_tasks where id=(:'audit_awaiting_fixture'::jsonb->>'task')::uuid \gset
select public.creator_publishing_claim_onlyfans_operator_task((:'audit_awaiting_fixture'::jsonb->>'creator')::uuid,(:'audit_awaiting_fixture'::jsonb->>'task')::uuid,(:'audit_awaiting_fixture'::jsonb->>'job')::uuid,:'audit_awaiting_fixture'::jsonb->>'consent_version',:'audit_awaiting_fixture'::jsonb->>'consent_hash','auditawait1') as audit_awaiting_claim \gset
select task17a_test.reset_fixture(920204,'due_now','due_now',true) as audit_due_fixture \gset
select task17a_test.set_valid_schedule_phase((:'audit_due_fixture'::jsonb->>'job')::uuid,'after_publish_due');
select status as audit_due_prior_status from public.creator_publishing_queue_tasks where id=(:'audit_due_fixture'::jsonb->>'task')::uuid \gset
select public.creator_publishing_claim_onlyfans_operator_task((:'audit_due_fixture'::jsonb->>'creator')::uuid,(:'audit_due_fixture'::jsonb->>'task')::uuid,(:'audit_due_fixture'::jsonb->>'job')::uuid,:'audit_due_fixture'::jsonb->>'consent_version',:'audit_due_fixture'::jsonb->>'consent_hash','auditdue01') as audit_due_claim \gset
select task17a_test.assert((select count(*) from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key in ('auditready1','auditsched1','auditawait1','auditdue01'))=4, 'claim prior-status matrix writes one audit per status');
select task17a_test.assert((select count(*) from public.creator_publishing_operator_action_idempotency where action_type='claim' and idempotency_key in ('auditready1','auditsched1','auditawait1','auditdue01'))=4, 'claim prior-status matrix writes one idempotency row per status');
select task17a_test.assert((select before_state->>'status' from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key='auditready1')=:'audit_ready_prior_status', 'claim audit records ready_for_handoff prior status');
select task17a_test.assert((select before_state->>'status' from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key='auditsched1')=:'audit_scheduled_prior_status', 'claim audit records scheduled_internally prior status');
select task17a_test.assert((select before_state->>'status' from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key='auditawait1')=:'audit_awaiting_prior_status', 'claim audit records awaiting_operator prior status');
select task17a_test.assert((select before_state->>'status' from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key='auditdue01')=:'audit_due_prior_status', 'claim audit records due_now prior status');
select task17a_test.assert(not exists(select 1 from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key in ('auditready1','auditsched1','auditawait1','auditdue01') and (before_state ? 'claim_token' or after_state ? 'claim_token')), 'claim audit prior-status matrix omits claim token');
select task17a_test.assert(not exists(select 1 from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key in ('auditready1','auditsched1','auditawait1','auditdue01') and not (before_state ? 'progress_state') and not (before_state ? 'assigned_operator_id')), 'claim audit prior-status matrix includes safe progress assignment fields');
\echo TASK17A_SCENARIO_START: runtime_privilege_assertions
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_operator_validate_idempotency_key(text)','execute'), 'anon cannot execute validate helper');
select task17a_test.assert(not has_function_privilege('authenticated','public.creator_publishing_operator_validate_idempotency_key(text)','execute'), 'authenticated cannot execute validate helper');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_operator_is_authorized(uuid,uuid,text)','execute'), 'anon cannot execute authorization helper');
select task17a_test.assert(not has_function_privilege('authenticated','public.creator_publishing_operator_is_authorized(uuid,uuid,text)','execute'), 'authenticated cannot execute authorization helper');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_operator_current_safety_gate(public.creator_publishing_platform_jobs,public.creator_publishing_queue_tasks,uuid,text,text)','execute'), 'anon cannot execute safety helper');
select task17a_test.assert(not has_function_privilege('authenticated','public.creator_publishing_operator_current_safety_gate(public.creator_publishing_platform_jobs,public.creator_publishing_queue_tasks,uuid,text,text)','execute'), 'authenticated cannot execute safety helper');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_operator_restore_queue_status(public.creator_publishing_platform_jobs,timestamptz)','execute'), 'anon cannot execute restore helper');
select task17a_test.assert(not has_function_privilege('authenticated','public.creator_publishing_operator_restore_queue_status(public.creator_publishing_platform_jobs,timestamptz)','execute'), 'authenticated cannot execute restore helper');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_operator_queue_is_clean(public.creator_publishing_queue_tasks)','execute'), 'anon cannot execute cleanliness helper');
select task17a_test.assert(not has_function_privilege('authenticated','public.creator_publishing_operator_queue_is_clean(public.creator_publishing_queue_tasks)','execute'), 'authenticated cannot execute cleanliness helper');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_operator_request_fingerprint(jsonb)','execute'), 'anon cannot execute fingerprint helper');
select task17a_test.assert(not has_function_privilege('authenticated','public.creator_publishing_operator_request_fingerprint(jsonb)','execute'), 'authenticated cannot execute fingerprint helper');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_operator_replay_or_conflict(uuid,text,text,text)','execute'), 'anon cannot execute idempotency helper');
select task17a_test.assert(not has_function_privilege('authenticated','public.creator_publishing_operator_replay_or_conflict(uuid,text,text,text)','execute'), 'authenticated cannot execute idempotency helper');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_claim_onlyfans_operator_task(uuid,uuid,uuid,text,text,text)','execute') and not has_function_privilege('authenticated','public.creator_publishing_claim_onlyfans_operator_task(uuid,uuid,uuid,text,text,text)','execute') and has_function_privilege('service_role','public.creator_publishing_claim_onlyfans_operator_task(uuid,uuid,uuid,text,text,text)','execute'), 'claim RPC service-role only');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_release_onlyfans_operator_task(uuid,uuid,uuid,uuid,text)','execute') and not has_function_privilege('authenticated','public.creator_publishing_release_onlyfans_operator_task(uuid,uuid,uuid,uuid,text)','execute') and has_function_privilege('service_role','public.creator_publishing_release_onlyfans_operator_task(uuid,uuid,uuid,uuid,text)','execute'), 'release RPC service-role only');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_update_onlyfans_operator_progress(uuid,uuid,uuid,uuid,text,integer,text,text,text,text)','execute') and not has_function_privilege('authenticated','public.creator_publishing_update_onlyfans_operator_progress(uuid,uuid,uuid,uuid,text,integer,text,text,text,text)','execute') and has_function_privilege('service_role','public.creator_publishing_update_onlyfans_operator_progress(uuid,uuid,uuid,uuid,text,integer,text,text,text,text)','execute'), 'progress RPC service-role only');
select task17a_test.assert(not has_function_privilege('anon','public.creator_publishing_recover_expired_onlyfans_operator_claim(uuid,uuid,uuid,text)','execute') and not has_function_privilege('authenticated','public.creator_publishing_recover_expired_onlyfans_operator_claim(uuid,uuid,uuid,text)','execute') and has_function_privilege('service_role','public.creator_publishing_recover_expired_onlyfans_operator_claim(uuid,uuid,uuid,text)','execute'), 'recovery RPC service-role only');
