import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const loader=readFileSync("lib/creator-publishing-queue/onlyfans-history/loaders.ts","utf8")
const creatorPackage=readFileSync("lib/creator-publishing-queue/onlyfans-history/creator-package.ts","utf8")
const resolution=readFileSync("lib/creator-publishing-queue/onlyfans-history/resolution.ts","utf8")
const timeline=readFileSync("app/creator/publishing-queue/OnlyFansHistoryTimeline.tsx","utf8")
const core=readFileSync("lib/creator-publishing-queue/onlyfans-history/core.ts","utf8")
const completionCore=readFileSync("lib/creator-publishing-queue/operator-completion/serviceCore.ts","utf8")

assert.match(loader,/select\("id,creator_id,target_platform"\)/)
assert.match(loader,/\.eq\("platform_job_id", job\.id\)[\s\S]*\.eq\("action_type", "manual_completion"\)/)
assert.match(loader,/creator_publishing_operator_completion_evidence_intents[\s\S]*\.eq\("platform_job_id", job\.id\)/)
assert.match(loader,/operator_onlyfans_manual_completion_proof_recorded|jobAuditEvents/)
assert.match(loader,/resolveQueueTaskIdFromJobLinks/)
assert.match(loader,/chooseHistoryQueueTask/)
assert.doesNotMatch(loader,/creator_publishing_queue_tasks[\s\S]{0,500}\.order\("updated_at", \{ ascending: false \}\)\.limit\(1\)/)
assert.ok(loader.indexOf("const evidenceIntents") < loader.indexOf("const task = await resolveTaskForJob"))
assert.ok(loader.indexOf("const idempotencyRows") < loader.indexOf("const task = await resolveTaskForJob"))
assert.match(loader,/loadCreatorOnlyFansPackageHistoryCore/)
assert.match(loader,/\.eq\("content_package_id", packageId\)[\s\S]*\.eq\("creator_id", creatorId\)[\s\S]*\.eq\("target_platform", "onlyfans"\)[\s\S]*\.eq\("publishing_mode", "assisted"\)/)
assert.match(loader,/\.order\("created_at", \{ ascending: false \}\)[\s\S]*\.order\("id", \{ ascending: false \}\)/)
assert.doesNotMatch(loader,/loadJobs:[\s\S]{0,600}\.limit\(1\)/)

assert.match(creatorPackage,/job\?\.creator_id===creatorId/)
assert.match(creatorPackage,/job\?\.content_package_id===pkg\.id/)
assert.match(creatorPackage,/job\?\.target_platform==="onlyfans"/)
assert.match(creatorPackage,/job\?\.publishing_mode==="assisted"/)
assert.match(creatorPackage,/\.sort\(compareJobsNewestFirst\)/)
assert.match(creatorPackage,/for \(const job of jobs\)/)
assert.match(creatorPackage,/taskLinkState:rows\.task\?\.id \? "exact" as const : "limited" as const/)

assert.match(resolution,/completion_proof_audit/)
assert.match(resolution,/manual_completion_idempotency/)
assert.match(resolution,/completion_evidence/)
assert.match(resolution,/if \(terminalJobStates\.has\(job\?\.job_state\)\) return null/)
assert.match(resolution,/exact\.length === 1 \? exact\[0\] : null/)
assert.match(resolution,/scopeHistoryAuditEvents/)
assert.match(resolution,/scopedKeys/)

assert.doesNotMatch(timeline,/internal_request_snapshot|claim_token|request_fingerprint|server_path/)
assert.match(timeline,/<ol/)
assert.match(timeline,/<time dateTime=/)
assert.match(timeline,/noUrlReasonLabel\(entry\.noUrlReason\)/)
assert.doesNotMatch(timeline,/<dd>\{entry\.noUrlReason\}<\/dd>/)
assert.match(timeline,/"attempts" in view/)
assert.match(timeline,/Publication attempts/)
assert.match(timeline,/Limited job history/)
assert.match(timeline,/attempt\.history\.timezone/)

for(const action of ["evidence_reserved","evidence_verified","evidence_superseded","evidence_failed","evidence_expired","evidence_consumed"]) assert.match(core,new RegExp(action))
assert.match(core,/id:`evidence:\$\{evidence\.id\}:\$\{lifecycle\.action\}`/)
assert.match(core,/replacesIntentId/)
assert.match(core,/replacedByIntentId/)
assert.match(core,/operator_onlyfans_manual_completion_proof_recorded"\) return 50/)
assert.match(core,/manual_completion_reconstructed/)
assert.match(core,/completionPriority:40/)
assert.match(core,/const proofSurvives=correlated\.some/)
assert.doesNotMatch(core,/if \(entry\.kind === "completion"\) return `completion:\$\{entry\.occurredAt\}`/)
assert.match(completionCore,/creator_publishing_complete_onlyfans_manual_post_audited/g)

console.log("task20OnlyFansHistory source contract tests passed")
