\set ON_ERROR_STOP on
\i backend/creator-publishing-queue/tests/task17aTestSupport.sql
\echo TASK17A_SCENARIO_START: ownership_creator_claim
select task17a_test.reset_fixture(920001) as fixture \gset
select public.creator_publishing_claim_onlyfans_operator_task((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','ownership01') as claim_result \gset
select task17a_test.assert(status='claimed' and claimed_by=(:'fixture'::jsonb->>'creator')::uuid and claimed_at is not null and claim_token is not null and claim_expires_at is not null, 'ownership fields populate together') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select task17a_test.assert(claim_expires_at > claimed_at and claim_expires_at <= claimed_at + interval '30 minutes', 'claim expiration within 30 minutes') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select task17a_test.assert(claim_attempt_count=1 and assigned_operator_id=(:'fixture'::jsonb->>'operator_b')::uuid, 'claim attempt increments once and assigned operator preserved') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select public.creator_publishing_claim_onlyfans_operator_task((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','ownership01') as replay_result \gset
select task17a_test.assert((select claim_attempt_count from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid)=1, 'claim replay does not increment attempts');
select task17a_test.expect_error('active claim cannot be stolen','OPERATOR_TASK_ALREADY_CLAIMED',format('select public.creator_publishing_claim_onlyfans_operator_task(%L,%L,%L,%L,%L,%L)',(:'fixture'::jsonb->>'operator_a'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','steal0001'));
select task17a_test.expect_error('same actor cannot rotate token','OPERATOR_TASK_ALREADY_CLAIMED',format('select public.creator_publishing_claim_onlyfans_operator_task(%L,%L,%L,%L,%L,%L)',(:'fixture'::jsonb->>'creator'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','rotate001'));
select task17a_test.reset_fixture(920101) as partial_fixture \gset
select task17a_test.expect_error('partial claim violates constraint','creator_publishing_queue_claim_all_or_none',format('update public.creator_publishing_queue_tasks set status=%L, claimed_by=%L where id=%L','claimed',(:'partial_fixture'::jsonb->>'creator'),(:'partial_fixture'::jsonb->>'task')));
select task17a_test.reset_fixture(920102) as nonclaimed_fixture \gset
select task17a_test.expect_error('nonclaimed cannot retain ownership','creator_publishing_queue_claim_all_or_none',format('update public.creator_publishing_queue_tasks set claimed_by=%L, claimed_at=clock_timestamp(), claim_token=%L, claim_expires_at=clock_timestamp()+interval ''10 minutes'' where id=%L',(:'nonclaimed_fixture'::jsonb->>'creator'),'92010200-0000-4000-8000-000000000001',(:'nonclaimed_fixture'::jsonb->>'task')));
select claim_token as progress_token from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid \gset
select public.creator_publishing_update_onlyfans_operator_progress((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'progress_token'::uuid,'not_started',0,'preparing',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','progress01');
select task17a_test.assert(operator_progress_state='preparing' and operator_progress_revision=1 and operator_progress_updated_by=(:'fixture'::jsonb->>'creator')::uuid and operator_progress_updated_at is not null, 'progress not_started to preparing updates actor timestamp revision') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select public.creator_publishing_update_onlyfans_operator_progress((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'progress_token'::uuid,'preparing',1,'prepared',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','progress02');
select public.creator_publishing_update_onlyfans_operator_progress((:'fixture'::jsonb->>'creator')::uuid,(:'fixture'::jsonb->>'task')::uuid,(:'fixture'::jsonb->>'job')::uuid,:'progress_token'::uuid,'prepared',2,'handoff_ready',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','progress03');
select task17a_test.assert(operator_progress_state='handoff_ready' and operator_progress_revision=3, 'progress reaches handoff_ready revision 3') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
select task17a_test.expect_error('invalid progress transition','OPERATOR_PROGRESS_INVALID_TRANSITION',format('select public.creator_publishing_update_onlyfans_operator_progress(%L,%L,%L,%L,%L,%s,%L,%L,%L,%L)',(:'fixture'::jsonb->>'creator'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'progress_token','handoff_ready',3,'preparing',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','badtrans1'));
select task17a_test.expect_error('stale progress state','OPERATOR_PROGRESS_STALE',format('select public.creator_publishing_update_onlyfans_operator_progress(%L,%L,%L,%L,%L,%s,%L,%L,%L,%L)',(:'fixture'::jsonb->>'creator'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'progress_token','prepared',2,'handoff_ready',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','stale001'));
select task17a_test.expect_error('wrong progress owner','OPERATOR_CLAIM_TOKEN_MISMATCH',format('select public.creator_publishing_update_onlyfans_operator_progress(%L,%L,%L,%L,%L,%s,%L,%L,%L,%L)',(:'fixture'::jsonb->>'operator_a'),(:'fixture'::jsonb->>'task'),(:'fixture'::jsonb->>'job'),:'progress_token','handoff_ready',3,'handoff_ready',:'fixture'::jsonb->>'consent_version',:'fixture'::jsonb->>'consent_hash','wrongown1'));
select task17a_test.assert(status not in ('scheduled_on_platform','awaiting_post_confirmation','confirmed_posted_manual'), 'no Task 18 queue state written') from public.creator_publishing_queue_tasks where id=(:'fixture'::jsonb->>'task')::uuid;
\echo TASK17A_SCENARIO_START: claim_audit_prior_status_matrix
select task17a_test.reset_fixture(920201,'scheduled_internally','scheduled_internally',true) as audit_fixture \gset
update public.creator_publishing_platform_jobs set operator_due_at=clock_timestamp()-interval '1 minute', intended_publish_at=clock_timestamp()+interval '1 hour' where id=(:'audit_fixture'::jsonb->>'job')::uuid;
select status as audit_prior_status from public.creator_publishing_queue_tasks where id=(:'audit_fixture'::jsonb->>'task')::uuid \gset
select public.creator_publishing_claim_onlyfans_operator_task((:'audit_fixture'::jsonb->>'creator')::uuid,(:'audit_fixture'::jsonb->>'task')::uuid,(:'audit_fixture'::jsonb->>'job')::uuid,:'audit_fixture'::jsonb->>'consent_version',:'audit_fixture'::jsonb->>'consent_hash','auditsched1') as audit_claim \gset
select task17a_test.assert((select before_state->>'status' from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key='auditsched1' order by id desc limit 1)=:'audit_prior_status', 'claim audit records actual scheduled prior status');
select task17a_test.assert((select before_state ? 'claim_token' from public.creator_publishing_audit_events where action='operator_task_claimed' and idempotency_key='auditsched1' order by id desc limit 1)=false, 'claim audit omits claim token');
