import test from "node:test"; import assert from "node:assert/strict"; import { readFileSync } from "node:fs";
import { canShowClaimControl, canShowReleaseControl, canShowRecoveryControl, canShowProgressControl, getNextProgressState, buildAuthoritativeTaskVersion, createOperatorLifecycle, deriveOperatorActionKeys, markOperatorActionFailed, markOperatorActionSucceeded, markOperatorActionUncertain, reconcileOperatorLifecycle, coerceProgressRevisionTransportValue, formDataToForwardedObject, trustedSuccessRevalidationPaths, isOperatorActionSubmissionDisabled } from "../../../app/creator/publishing-queue/operator/presentation";
import { queueStatusLabel } from "../../../lib/creator-publishing-queue/ui/status";
const base:any={platformJobId:"job-a",queueStatus:"awaiting_operator",progressState:"not_started",progressRevision:1,claimExpiresAt:null,bucket:"due_now",readOnly:false,attentionReasons:[]};
test("control visibility",()=>{ assert.equal(canShowClaimControl({...base,bucket:"due_now"}),true); assert.equal(canShowClaimControl({...base,bucket:"overdue"}),true); assert.equal(canShowClaimControl({...base,bucket:"ready_but_unscheduled"}),true); for (const b of ["due_soon","upcoming","needs_attention","claimed_by_me"]) assert.equal(canShowClaimControl({...base,bucket:b}),false); assert.equal(canShowReleaseControl({...base,bucket:"claimed_by_me"}),true); assert.equal(canShowReleaseControl({...base,bucket:"due_now"}),false); assert.equal(canShowRecoveryControl({...base,bucket:"needs_attention",attentionReasons:["expired_claim_recovery_available"]}),true); assert.equal(canShowRecoveryControl({...base,bucket:"needs_attention",attentionReasons:["authorization_or_safety_attention"]}),false); assert.equal(canShowClaimControl({...base,bucket:"needs_attention",attentionReasons:["authorization_or_safety_attention"]}),false); assert.equal(canShowRecoveryControl({...base,bucket:"needs_attention",attentionReasons:["claimed_by_another_operator"]}),false); });

test("action-aware disabled behavior",()=>{
  const expired={...base,bucket:"needs_attention",readOnly:true,attentionReasons:["expired_claim_recovery_available"]};
  assert.equal(canShowRecoveryControl(expired),true);
  assert.equal(isOperatorActionSubmissionDisabled("recovery",expired,false),false);
  assert.equal(isOperatorActionSubmissionDisabled("recovery",expired,true),true);
  for (const reason of ["authorization_or_safety_attention","claimed_by_another_operator","task_no_longer_eligible"]) assert.equal(isOperatorActionSubmissionDisabled("recovery",{...base,bucket:"needs_attention",readOnly:true,attentionReasons:[reason]},false),true);
  assert.equal(isOperatorActionSubmissionDisabled("claim",{...base,bucket:"due_now",readOnly:true},false),true);
  assert.equal(isOperatorActionSubmissionDisabled("release",{...base,bucket:"claimed_by_me",readOnly:true},false),true);
  assert.equal(isOperatorActionSubmissionDisabled("progress",{...base,bucket:"claimed_by_me",progressState:"not_started",readOnly:true},false),true);
  assert.equal(isOperatorActionSubmissionDisabled("claim",{...base,bucket:"due_now",readOnly:false},false),false);
  assert.equal(isOperatorActionSubmissionDisabled("release",{...base,bucket:"claimed_by_me",readOnly:false},false),false);
  assert.equal(isOperatorActionSubmissionDisabled("progress",{...base,bucket:"claimed_by_me",progressState:"not_started",readOnly:false},false),false);
  for (const action of ["claim","release","progress","recovery"] as const) assert.equal(isOperatorActionSubmissionDisabled(action,{...expired,bucket: action === "recovery" ? "needs_attention" : action === "claim" ? "due_now" : "claimed_by_me",readOnly:false,progressState:"not_started",attentionReasons: action === "recovery" ? ["expired_claim_recovery_available"] : []},true),true);
});
test("progress transitions",()=>{ assert.equal(getNextProgressState("not_started"),"preparing"); assert.equal(getNextProgressState("preparing"),"prepared"); assert.equal(getNextProgressState("prepared"),"handoff_ready"); assert.equal(getNextProgressState("handoff_ready"),null); assert.equal(canShowProgressControl({...base,bucket:"due_now",progressState:"not_started"}),false); assert.equal(canShowProgressControl({...base,bucket:"claimed_by_me",progressState:"prepared"}),true); });
test("authoritative version",()=>{ const a=buildAuthoritativeTaskVersion({...base,attentionReasons:["claimed_by_another_operator","authorization_or_safety_attention"]}); const b=buildAuthoritativeTaskVersion({...base,attentionReasons:["authorization_or_safety_attention","claimed_by_another_operator"]}); assert.equal(a,b); assert.match(a,/platformJobId/); assert.match(a,/queueStatus/); assert.match(a,/progressState/); assert.match(a,/progressRevision/); assert.match(a,/claimExpiresAt/); assert.match(a,/bucket/); assert.match(a,/readOnly/); assert.match(a,/attentionReasons/); assert.notEqual(b,buildAuthoritativeTaskVersion({...base,attentionReasons:["task_no_longer_eligible"]})); assert.notEqual(buildAuthoritativeTaskVersion({...base,bucket:"needs_attention",attentionReasons:["claimed_by_another_operator"]}),buildAuthoritativeTaskVersion({...base,bucket:"needs_attention",attentionReasons:["expired_claim_recovery_available"]})); for (const k of ["platformJobId","queueStatus","progressState","progressRevision","claimExpiresAt","bucket","readOnly"] as const) assert.notEqual(buildAuthoritativeTaskVersion(base), buildAuthoritativeTaskVersion({...base,[k]: k==="readOnly"?true:`changed-${k}`})); assert.equal(buildAuthoritativeTaskVersion(base), buildAuthoritativeTaskVersion({...base,capturedAt:"different"})); });
test("idempotency lifecycle",()=>{ const keys=deriveOperatorActionKeys("abcDEF_123-456"); assert.equal(new Set(Object.values(keys)).size,4); for (const k of Object.values(keys)) assert.match(k,/^[A-Za-z0-9_-]{8,128}$/); const s=createOperatorLifecycle("v1","seed-1111"); assert.equal(markOperatorActionFailed(s).keys.claim,s.keys.claim); assert.equal(markOperatorActionUncertain(s).keys.progress,s.keys.progress); assert.equal(reconcileOperatorLifecycle(markOperatorActionFailed(s),{authoritativeTaskVersion:"v1",serverSeed:"new-seed"}).keys.claim,s.keys.claim); const done=markOperatorActionSucceeded(s,"seed-2222"); assert.equal(done.successLocked,true); assert.notEqual(done.keys.claim,s.keys.claim); assert.notEqual(done.keys.release,s.keys.release); assert.notEqual(done.keys.progress,s.keys.progress); assert.notEqual(done.keys.recovery,s.keys.recovery); assert.equal(reconcileOperatorLifecycle(s,{authoritativeTaskVersion:"v2",serverSeed:"seed-3333"}).activeSeed,"seed-3333"); const refreshed=reconcileOperatorLifecycle(done,{authoritativeTaskVersion:"v1",serverSeed:"seed-4444"}); assert.equal(refreshed.activeSeed,"seed-4444"); assert.notEqual(refreshed.keys.claim,done.keys.claim); });
test("progress revision conversion",()=>{ assert.equal(coerceProgressRevisionTransportValue("0"),0); assert.equal(coerceProgressRevisionTransportValue("27"),27); const invalid:any[]=[""," ","1.2","-1","+1","1e2","01","abc", new File(["x"],"x.txt")]; for (const v of invalid) { assert.equal(coerceProgressRevisionTransportValue(v),v); assert.notEqual(coerceProgressRevisionTransportValue(v),0); } });
test("form forwarding",()=>{ const fd=new FormData(); fd.set("$ACTION_ID","x"); fd.set("unknown","u"); fd.set("creatorId","protected"); fd.set("expectedProgressRevision","27"); const out=formDataToForwardedObject(fd,true); assert.deepEqual(out,{unknown:"u",creatorId:"protected",expectedProgressRevision:27}); const fd2=new FormData(); fd2.set("expectedProgressRevision","01"); assert.equal(formDataToForwardedObject(fd2,true).expectedProgressRevision,"01"); });
test("revalidation helper",()=>{ const ok:any={ok:true,data:{platformJobId:"trusted"}}; assert.deepEqual(trustedSuccessRevalidationPaths(ok),["/creator/publishing-queue/operator","/creator/publishing-queue","/creator/publishing-queue/operator/trusted"]); assert(!trustedSuccessRevalidationPaths(ok).includes("raw")); assert.deepEqual(trustedSuccessRevalidationPaths({ok:false,code:"service_unavailable",message:"x",retryable:true} as any),[]); });
test("shared status",()=>{ assert(readFileSync("lib/creator-publishing-queue/approval/types.ts","utf8").includes('"awaiting_operator"')); assert.equal(queueStatusLabel("awaiting_operator" as any),"Awaiting operator"); });
