import assert from 'node:assert/strict'
import { normalizeCancelPlanRequest, normalizeSchedulePlanRequest, resolveScheduleLocalDateTime } from '../../../lib/creator-publishing-queue/scheduling/validation'
import { parseCancelPlanRpcResult, parseScheduleRpcResult } from '../../../lib/creator-publishing-queue/scheduling/response'
import { cancelPlanCore, schedulePlanCore } from '../../../lib/creator-publishing-queue/scheduling/serviceCore'
const creator='00000000-0000-4000-8000-000000000001', plan='70000000-0000-4000-8000-000000000001', job='80000000-0000-4000-8000-000000000001', pkg='90000000-0000-4000-8000-000000000001', acct='91000000-0000-4000-8000-000000000001'
function tables(over:any={}){ return {plan:{id:plan,creator_id:creator,status:'draft',cancelled_at:null,cancellation_reason:null,...over.plan},jobs:[{id:job,creator_id:creator,publishing_plan_id:plan,content_package_id:pkg,platform_account_id:acct,target_platform:'onlyfans',publishing_mode:'assisted',job_state:'draft',schedule_revision:null,intended_publish_at:null,operator_due_at:null,schedule_timezone:null,scheduled_at:null,scheduled_by:null,cancelled_at:null,source_package_fingerprint:'fp',...over.job},...(over.extraJobs??[])],events:over.events??[],siblings:over.siblings??[],queue:over.queue??[{id:'q',status:'ready_for_handoff',claimed_by:null,claimed_at:null,claim_token:null,claim_expires_at:null,posted_by:null,posted_at:null,posted_confirmation:false,final_post_url:null,final_post_url_skip_reason:null,proof_screenshot_storage_key:null,skip_or_fail_reason:null}],rpcCalls:[]} }
function admin(t:any){ return {from(name:string){ const b:any={select(){return b},eq(){return b},in(){return b},not(){return b},order(){return b},limit(){return b},maybeSingle:async()=> name==='creator_publishing_plans'?{data:t.plan,error:null}:{data:null,error:null},then:(res:any)=>res({data:name==='creator_publishing_platform_jobs'?(t.siblings.length?t.siblings:t.jobs):name==='creator_publishing_scheduler_events'?t.events:name==='creator_publishing_queue_tasks'?t.queue:[],error:null})}; return b}, rpc:async(name:string,args:any)=>{ t.rpcCalls.push({name,args}); if(name==='creator_publishing_autopost_source_fingerprint') return {data:overFp??'fp',error:null}; return {data:{ok:true,action_type:name.includes('cancel')?'cancel_plan':'schedule',publishing_plan_id:plan,success_count:1,failure_count:0,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true}],task17a_queue_claims_cleared:0,idempotent:false},error:null} } } }
let overFp:any
const deps=(t:any,auth=creator)=>({getAuthenticatedCreatorId:async()=>auth,getAdminClient:()=>admin(t),getConsent:async()=>({version:'server-version',textSha256:'a'.repeat(64)}),now:()=>new Date('2026-07-20T00:00:00Z')})
assert.equal((await schedulePlanCore({publishingPlanId:plan,platformJobId:job,localDateTime:{date:'2026-07-20',time:'03:00'},scheduleTimezone:'UTC',idempotencyKey:'abcdefgh'}, deps(tables(),null))).code,'UNAUTHENTICATED')
let created=false; await schedulePlanCore({bad:true},{getAuthenticatedCreatorId:async()=>null,getAdminClient:()=>{created=true},getConsent:async()=>({version:'v',textSha256:'h'})} as any); assert.equal(created,false,'admin client is lazy and created only after authentication')
assert.throws(()=>normalizeSchedulePlanRequest({publishingPlanId:plan,platformJobId:job,localDateTime:{date:'2026-01-01',time:'00:00'},scheduleTimezone:'UTC',idempotencyKey:'abcdefgh',creatorId:creator}))
assert.throws(()=>normalizeSchedulePlanRequest({publishingPlanId:plan,platformJobId:job,localDateTime:{date:'2026-01-01',time:'00:00'},scheduleTimezone:'UTC',idempotencyKey:'abcdefgh',unknown:true}))
for (const [label,over] of Object.entries({crossCreatorPlan:{plan:{creator_id:'00000000-0000-4000-8000-000000000002'}},crossCreatorJob:{job:{creator_id:'00000000-0000-4000-8000-000000000002'}},planJobMismatch:{job:{publishing_plan_id:'70000000-0000-4000-8000-000000000002'}},zeroActive:{job:{job_state:'archived'}},multipleActive:{extraJobs:[{id:'80000000-0000-4000-8000-000000000002',creator_id:creator,publishing_plan_id:plan,content_package_id:'x',platform_account_id:acct,target_platform:'onlyfans',publishing_mode:'assisted',job_state:'draft'}]},nonOnlyFans:{job:{target_platform:'fanvue'}},nonAssisted:{job:{publishing_mode:'direct'}},nonDraftPlan:{plan:{status:'scheduled'}},nonDraftJob:{job:{job_state:'scheduled_internally'}},scheduledJob:{job:{schedule_revision:1}},cancelled:{plan:{cancelled_at:'x'}},dirty:{job:{intended_publish_at:'x'}},event:{events:[{id:'e'}]},sibling:{siblings:[{id:job,job_state:'draft'},{id:'s',job_state:'draft'}]},dirtyQueue:{queue:[{status:'ready_for_handoff',claimed_by:'op'}]}})){ overFp= label==='stale'?'bad':'fp'; const r=await schedulePlanCore({publishingPlanId:plan,platformJobId:job,localDateTime:{date:'2026-07-20',time:'03:00'},scheduleTimezone:'UTC',idempotencyKey:'abcdefgh'},deps(tables(over as any))); assert.equal(r.ok,false,label) }
overFp='bad'; assert.equal((await schedulePlanCore({publishingPlanId:plan,platformJobId:job,localDateTime:{date:'2026-07-20',time:'03:00'},scheduleTimezone:'UTC',idempotencyKey:'abcdefgh'},deps(tables()))).ok,false,'stale source fingerprint rejected'); overFp='fp'
const t=tables(); const good=await schedulePlanCore({publishingPlanId:plan,platformJobId:job,localDateTime:{date:'2026-07-20',time:'03:00'},scheduleTimezone:'UTC',idempotencyKey:'abcdefgh'},deps(t)); assert.equal(good.ok,true); assert.equal(t.rpcCalls.at(-1).name,'creator_publishing_schedule_plan'); assert.deepEqual(t.rpcCalls.at(-1).args.p_target_job_ids,[job]); assert.equal(t.rpcCalls.at(-1).args.p_action_type,'schedule'); assert.deepEqual(t.rpcCalls.at(-1).args.p_expected_schedule_revisions,{}); assert.equal(t.rpcCalls.at(-1).args.p_expected_ai_twin_consent_version,'server-version')
assert.equal(parseScheduleRpcResult({ok:true,action_type:'schedule',success_count:1,failure_count:0,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:true}],idempotent:false},{planId:plan,jobId:job,intendedPublishAt:'x',timezone:'UTC',operatorDueAt:'y'}).ok,true)
assert.equal(parseScheduleRpcResult({ok:true,action_type:'schedule',success_count:1,failure_count:0,jobs:[{job_id:job,status:'scheduled',schedule_revision:1,mutated:false}],idempotent:true},{planId:plan,jobId:job,intendedPublishAt:'x',timezone:'UTC',operatorDueAt:'y'}).ok,true)
for(const bad of [{}, {ok:true,action_type:'schedule',success_count:0,failure_count:1,jobs:[]},{ok:true,action_type:'schedule',success_count:1,failure_count:0,jobs:[{job_id:'bad',status:'scheduled',schedule_revision:1,mutated:true}]},{ok:true,action_type:'schedule',success_count:1,failure_count:0,jobs:[{job_id:job,status:'scheduled',schedule_revision:2,mutated:true}]}]) assert.equal(parseScheduleRpcResult(bad,{planId:plan,jobId:job,intendedPublishAt:'x',timezone:'UTC',operatorDueAt:'y'}).ok,false)
assert.equal(resolveScheduleLocalDateTime({date:'2026-07-20',time:'03:00'},'UTC',new Date('2026-07-20T00:00:00Z')).intendedPublishAt,'2026-07-20T03:00:00.000Z')
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-07-20',time:'03:00'},'Nope/Bad'))
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-02-30',time:'03:00'},'UTC'))
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-03-08',time:'02:30'},'America/New_York',new Date('2026-01-01T00:00:00Z')))
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-11-01',time:'01:30'},'America/New_York',new Date('2026-01-01T00:00:00Z')))
assert.equal(resolveScheduleLocalDateTime({date:'2026-11-01',time:'01:30',utcOffsetMinutes:-240},'America/New_York',new Date('2026-01-01T00:00:00Z')).utcOffsetMinutes,-240)
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-11-01',time:'01:30',utcOffsetMinutes:0},'America/New_York',new Date('2026-01-01T00:00:00Z')))
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-07-20',time:'00:30'},'UTC',new Date('2026-07-20T00:00:00Z')))
assert.throws(()=>resolveScheduleLocalDateTime({date:'2026-07-20',time:'bad'},'UTC'))
assert.deepEqual(normalizeCancelPlanRequest({publishingPlanId:plan,cancellationReason:'  ok  ',idempotencyKey:'cancelkey'}).cancellationReason,'ok')
assert.throws(()=>normalizeCancelPlanRequest({publishingPlanId:plan,cancellationReason:' ',idempotencyKey:'cancelkey'})); assert.throws(()=>normalizeCancelPlanRequest({publishingPlanId:plan,cancellationReason:'x'.repeat(501),idempotencyKey:'cancelkey'}))
const ct=tables({plan:{status:'scheduled'},job:{job_state:'scheduled_internally',schedule_revision:1,intended_publish_at:'x',operator_due_at:'y',schedule_timezone:'UTC',scheduled_at:'z',scheduled_by:creator}}); const cr=await cancelPlanCore({publishingPlanId:plan,cancellationReason:' reason ',idempotencyKey:'cancelkey'},deps(ct)); assert.equal(cr.ok,true); assert.equal(ct.rpcCalls.at(-1).name,'creator_publishing_cancel_plan_schedule')
assert.equal(parseCancelPlanRpcResult({ok:true,action_type:'cancel_plan',publishing_plan_id:plan,task17a_queue_claims_cleared:1,idempotent:false},{planId:plan,freshActiveJobCount:1,replayTotalJobBound:2}).ok,true)
assert.equal(parseCancelPlanRpcResult({ok:true,action_type:'cancel_plan',publishing_plan_id:plan,task17a_queue_claims_cleared:2,idempotent:true},{planId:plan,freshActiveJobCount:0,replayTotalJobBound:2}).ok,true)
assert.equal(parseCancelPlanRpcResult({bad:true},{planId:plan,freshActiveJobCount:1,replayTotalJobBound:1}).ok,false)
console.log('task21PlanSchedulingServices ok')
