\set ON_ERROR_STOP on
set client_min_messages=warning;

select task20_test.assert(to_regprocedure('public.creator_publishing_complete_onlyfans_manual_post_audited(text,uuid,uuid,text,uuid,text,text,text,integer,text,uuid)') is not null,'audited wrapper exists');
select task20_test.assert(not has_function_privilege('authenticated','public.creator_publishing_complete_onlyfans_manual_post_audited(text,uuid,uuid,text,uuid,text,text,text,integer,text,uuid)','execute'),'audited wrapper is not browser executable');
select task20_test.assert(has_function_privilege('service_role','public.creator_publishing_complete_onlyfans_manual_post_audited(text,uuid,uuid,text,uuid,text,text,text,integer,text,uuid)','execute'),'audited wrapper is service-role executable');
select task20_test.assert(not has_function_privilege('service_role','public.task20_record_onlyfans_completion_rejection(uuid,uuid,uuid,uuid,uuid,text,text,text,text,timestamptz)','execute'),'rejection recorder is not an application-callable RPC');
select task20_test.assert(exists(select 1 from pg_indexes where schemaname='public' and tablename='creator_publishing_audit_events' and indexname='task20_onlyfans_completion_audit_once_uidx' and indexdef like '%UNIQUE%' and indexdef like '%operator_onlyfans_manual_completion_proof_recorded%' and indexdef like '%operator_onlyfans_manual_completion_rejected%'),'Task 20 audit uniqueness is database enforced and narrowly partial');
select task20_test.assert((select pg_get_constraintdef(oid) from pg_constraint where conrelid='public.creator_publishing_operator_action_idempotency'::regclass and conname='task18_operator_action_type_check') like '%manual_completion_rejection%','rejection idempotency action is allowed by the single action-type constraint');
select task20_test.assert(public.task20_onlyfans_completion_rejection_code('XX000','CURRENT_CLAIM_REQUIRED') is null,'unknown SQLSTATE is never converted into a business rejection');
select task20_test.assert(public.task20_onlyfans_completion_rejection_code('P0001','CURRENT_CLAIM_REQUIRED')='current_claim_required','approved business rejection is mapped by the database');

select task20_test.create_fixture(1) as f1 \gset
select public.creator_publishing_complete_onlyfans_manual_post_audited('replay_probe',(:'f1'::jsonb->>'actor')::uuid,(:'f1'::jsonb->>'job')::uuid,'task20-success-0001',(:'f1'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/12345/trusteduser',null,null,null,null,null) as pre_probe \gset
select task20_test.assert((:'pre_probe'::jsonb->>'replayed')::boolean=false,'new request replay probe is false');
select task20_test.assert((select count(*)=0 from public.creator_publishing_audit_events where entity_id=(:'f1'::jsonb->>'job')::uuid and action in ('operator_onlyfans_manual_completion_proof_recorded','operator_onlyfans_manual_completion_rejected')),'replay probe creates no Task 20 event');
select task20_test.assert((select status='claimed' from public.creator_publishing_queue_tasks where id=(:'f1'::jsonb->>'task')::uuid),'replay probe does not mutate completion state');

select public.creator_publishing_complete_onlyfans_manual_post_audited('complete',(:'f1'::jsonb->>'actor')::uuid,(:'f1'::jsonb->>'job')::uuid,'task20-success-0001',(:'f1'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/12345/trusteduser',null,:'f1'::jsonb->>'digest',8,'image/jpeg',(:'f1'::jsonb->>'token')::uuid) as completed \gset
select task20_test.assert(:'completed'::jsonb->>'status'='confirmed_posted_manual','audited completion succeeds');
select task20_test.assert(:'completed'::jsonb->>'final_post_url'='https://onlyfans.com/12345/trusteduser','audited completion preserves canonical URL');
select task20_test.assert((select count(*)=1 from public.creator_publishing_audit_events where entity_id=(:'f1'::jsonb->>'job')::uuid and actor_id=(:'f1'::jsonb->>'actor')::uuid and idempotency_key='task20-success-0001' and action='operator_onlyfans_manual_completion_proof_recorded'),'one future success creates exactly one proof event');
select task20_test.assert((select after_state->>'platform_job_id'=:'f1'::jsonb->>'job' and after_state->>'queue_task_id'=:'f1'::jsonb->>'task' and after_state->>'evidence_intent_id'=:'f1'::jsonb->>'evidence' and after_state->>'final_post_url'='https://onlyfans.com/12345/trusteduser' and after_state->>'verified_sha256'=:'f1'::jsonb->>'digest' and (after_state->>'actual_size_bytes')::int=8 and after_state->>'normalized_mime_type'='image/jpeg' and (after_state->>'operator_actor_id')::uuid=(:'f1'::jsonb->>'actor')::uuid and after_state->>'idempotency_key'='task20-success-0001' and after_state->>'completed_at' is not null from public.creator_publishing_audit_events where entity_id=(:'f1'::jsonb->>'job')::uuid and action='operator_onlyfans_manual_completion_proof_recorded' and idempotency_key='task20-success-0001'),'proof event contains the minimum durable completion linkage');
select task20_test.assert(not exists(select 1 from public.creator_publishing_audit_events where entity_id=(:'f1'::jsonb->>'job')::uuid and action in ('operator_onlyfans_manual_completion_proof_recorded','operator_onlyfans_manual_completion_rejected') and (before_state ? 'claim_token' or after_state ? 'claim_token' or before_state ? 'request_fingerprint' or after_state ? 'request_fingerprint' or after_state ? 'raw_error' or after_state ? 'sqlerrm')),'Task 20 events contain no protected values or unrestricted errors');

select public.creator_publishing_complete_onlyfans_manual_post_audited('replay_probe',(:'f1'::jsonb->>'actor')::uuid,(:'f1'::jsonb->>'job')::uuid,'task20-success-0001',(:'f1'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/12345/trusteduser',null,null,null,null,null) as successful_probe \gset
select task20_test.assert((:'successful_probe'::jsonb->>'replayed')::boolean=true,'successful replay probe returns the stored success');
select task20_test.assert((select count(*)=1 from public.creator_publishing_audit_events where entity_id=(:'f1'::jsonb->>'job')::uuid and action='operator_onlyfans_manual_completion_proof_recorded' and idempotency_key='task20-success-0001'),'successful replay probe creates no duplicate proof event');

select public.creator_publishing_complete_onlyfans_manual_post_audited('complete',(:'f1'::jsonb->>'actor')::uuid,(:'f1'::jsonb->>'job')::uuid,'task20-success-0001',(:'f1'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/12345/trusteduser',null,:'f1'::jsonb->>'digest',8,'image/jpeg',null) as successful_replay \gset
select task20_test.assert((:'successful_replay'::jsonb->>'replayed')::boolean=true,'sequential success replay returns stored success');
select task20_test.assert((select count(*)=1 from public.creator_publishing_audit_events where entity_id=(:'f1'::jsonb->>'job')::uuid and action='operator_onlyfans_manual_completion_proof_recorded' and idempotency_key='task20-success-0001'),'sequential success replay creates no duplicate proof event');

select public.creator_publishing_complete_onlyfans_manual_post_audited('complete',(:'f1'::jsonb->>'actor')::uuid,(:'f1'::jsonb->>'job')::uuid,'task20-success-0001',(:'f1'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/54321/trusteduser',null,:'f1'::jsonb->>'digest',8,'image/jpeg',null) as success_conflict \gset
select task20_test.assert(:'success_conflict'::jsonb->>'code'='idempotency_conflict','materially different reuse after success is a conflict');
select task20_test.assert((select count(*)=1 from public.creator_publishing_audit_events where entity_id=(:'f1'::jsonb->>'job')::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-success-0001' and after_state->>'rejection_code'='idempotency_conflict'),'success-key conflict creates one sanitized rejection event');

select task20_test.create_fixture(2) as f2 \gset
select public.creator_publishing_complete_onlyfans_manual_post_audited('complete',(:'f2'::jsonb->>'actor')::uuid,(:'f2'::jsonb->>'job')::uuid,'task20-reject-0002',(:'f2'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/12345/trusteduser',null,:'f2'::jsonb->>'digest',8,'image/jpeg','99999999-0000-4000-8000-000000000002'::uuid) as rejected \gset
select task20_test.assert(:'rejected'::jsonb->>'status'='completion_rejected','known rejection returns a structured safe failure');
select task20_test.assert(:'rejected'::jsonb->>'code'='current_claim_required','known rejection uses finite database code');
select task20_test.assert((select count(*)=1 from public.creator_publishing_audit_events where entity_id=(:'f2'::jsonb->>'job')::uuid and actor_id=(:'f2'::jsonb->>'actor')::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-reject-0002' and after_state->>'rejection_code'='current_claim_required'),'one approved rejection creates exactly one sanitized event');
select task20_test.assert((select count(*)=1 from public.creator_publishing_operator_action_idempotency where actor_id=(:'f2'::jsonb->>'actor')::uuid and action_type='manual_completion_rejection' and idempotency_key='task20-reject-0002'),'approved rejection has a database idempotency record');

select public.creator_publishing_complete_onlyfans_manual_post_audited('complete',(:'f2'::jsonb->>'actor')::uuid,(:'f2'::jsonb->>'job')::uuid,'task20-reject-0002',(:'f2'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/12345/trusteduser',null,:'f2'::jsonb->>'digest',8,'image/jpeg','99999999-0000-4000-8000-000000000002'::uuid) as rejected_replay \gset
select task20_test.assert((:'rejected_replay'::jsonb->>'replayed')::boolean=true,'rejected replay is deterministic');
select task20_test.assert(:'rejected_replay'::jsonb->>'code'='current_claim_required','rejected replay returns the matching safe result');
select task20_test.assert((select count(*)=1 from public.creator_publishing_audit_events where entity_id=(:'f2'::jsonb->>'job')::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-reject-0002'),'rejected replay creates no duplicate event');

select public.creator_publishing_complete_onlyfans_manual_post_audited('complete',(:'f2'::jsonb->>'actor')::uuid,(:'f2'::jsonb->>'job')::uuid,'task20-reject-0002',(:'f2'::jsonb->>'evidence')::uuid,'https://www.onlyfans.com/54321/trusteduser',null,:'f2'::jsonb->>'digest',8,'image/jpeg','99999999-0000-4000-8000-000000000002'::uuid) as rejected_conflict \gset
select task20_test.assert(:'rejected_conflict'::jsonb->>'code'='idempotency_conflict','materially different rejected request remains a conflict');
select task20_test.assert((:'rejected_conflict'::jsonb->>'replayed')::boolean=false,'different request does not replay an unrelated rejection');
select task20_test.assert((select count(*)=1 from public.creator_publishing_audit_events where entity_id=(:'f2'::jsonb->>'job')::uuid and action='operator_onlyfans_manual_completion_rejected' and idempotency_key='task20-reject-0002'),'different rejected request does not create duplicate event');

select task20_test.create_fixture(3,'00000000-0000-4000-8000-000000000909'::uuid,false) as f3 \gset
select task20_test.expect_error('unauthorized actor cannot create rejection history','TASK20_ACTOR_UNAUTHORIZED',format('select public.creator_publishing_complete_onlyfans_manual_post_audited(%L,%L::uuid,%L::uuid,%L,%L::uuid,%L,null,%L,8,%L,%L::uuid)','complete',:'f3'::jsonb->>'actor',:'f3'::jsonb->>'job','task20-unauth-0003',:'f3'::jsonb->>'evidence','https://www.onlyfans.com/12345/trusteduser',:'f3'::jsonb->>'digest','image/jpeg',:'f3'::jsonb->>'token'));
select task20_test.assert(not exists(select 1 from public.creator_publishing_audit_events where entity_id=(:'f3'::jsonb->>'job')::uuid and action in ('operator_onlyfans_manual_completion_proof_recorded','operator_onlyfans_manual_completion_rejected')),'unauthorized actor creates no Task 20 event');
select task20_test.assert(not exists(select 1 from public.creator_publishing_operator_action_idempotency where actor_id=(:'f3'::jsonb->>'actor')::uuid and idempotency_key='task20-unauth-0003'),'unauthorized actor creates no idempotency record');

select task20_test.create_fixture(4) as f4 \gset
create or replace function task20_test.raise_unknown_completion_fault() returns trigger language plpgsql as $$ begin if new.id='50000000-0000-4000-8000-000000000004'::uuid then raise exception using errcode='XX000', message='TASK20_TEST_UNKNOWN_DATABASE_FAULT'; end if; return new; end $$;
create trigger task20_unknown_completion_fault_trg before update on public.creator_publishing_queue_tasks for each row execute function task20_test.raise_unknown_completion_fault();
select task20_test.expect_error('unknown database error remains an error','TASK20_TEST_UNKNOWN_DATABASE_FAULT',format('select public.creator_publishing_complete_onlyfans_manual_post_audited(%L,%L::uuid,%L::uuid,%L,%L::uuid,%L,null,%L,8,%L,%L::uuid)','complete',:'f4'::jsonb->>'actor',:'f4'::jsonb->>'job','task20-unknown-0004',:'f4'::jsonb->>'evidence','https://www.onlyfans.com/12345/trusteduser',:'f4'::jsonb->>'digest','image/jpeg',:'f4'::jsonb->>'token'));
drop trigger task20_unknown_completion_fault_trg on public.creator_publishing_queue_tasks;
drop function task20_test.raise_unknown_completion_fault();
select task20_test.assert(not exists(select 1 from public.creator_publishing_audit_events where entity_id=(:'f4'::jsonb->>'job')::uuid and action in ('operator_onlyfans_manual_completion_proof_recorded','operator_onlyfans_manual_completion_rejected')),'unknown database error creates no Task 20 event');
select task20_test.assert(not exists(select 1 from public.creator_publishing_operator_action_idempotency where actor_id=(:'f4'::jsonb->>'actor')::uuid and idempotency_key='task20-unknown-0004'),'unknown database error creates no idempotency record');

select 'TASK20_POSTGRES_INTEGRATION_PASSED' as result;
