import assert from "node:assert/strict"
import { test } from "node:test"
import { readFileSync, readdirSync, statSync } from "node:fs"
import { join, relative } from "node:path"
import { validateOperatorClaimInput, validateOperatorProgressInput } from "../../../lib/creator-publishing-queue/operator-queue/validation"
const root = process.cwd(); const implDir=join(root,"lib/creator-publishing-queue/operator-queue")
function files(dir:string): string[] { return readdirSync(dir).flatMap(n=>{const p=join(dir,n); return statSync(p).isDirectory()?files(p):p.endsWith(".ts")?[p]:[]}) }
const sourceFiles=files(implDir); const rel=(p:string)=>relative(root,p); const byName=(n:string)=>readFileSync(join(implDir,n),"utf8")
test("production code derives identity from Supabase auth and contains no dev bypass identity source",()=>{ const forbidden=[/requireUserId\b/,/DEV_BYPASS_USER_ID/,/x-dev-user-id/,/from ["']next\/headers["']/,/request\.headers/,/req\.headers/,/headers\.get\(/,/Request\s*[),]/]; for (const f of sourceFiles) { const text=readFileSync(f,"utf8"); for (const pat of forbidden) assert.doesNotMatch(text,pat,`${rel(f)} must not match ${pat}`) } const service=byName("service.ts"); assert.match(service,/const supabase = await supabaseServer\(\)/); assert.match(service,/const \{ data, error \} = await supabase\.auth\.getUser\(\)/); assert.match(service,/claimOnlyFansOperatorTaskCore\(input, \{ actorId \}/); const loaders=byName("loaders.ts"); assert.match(loaders,/const supabase = await supabaseServer\(\)/); assert.match(loaders,/const \{ data, error \} = await supabase\.auth\.getUser\(\)/) })
test("public production barrel does not export core injection seams or raw token parsers",()=>{ const index=byName("index.ts"); for (const forbidden of ["serviceCore","loadOnlyFansOperatorQueueCore","loadOnlyFansOperatorTaskDetailCore","TrustedActorContext","OperatorQueueCoreDeps","parseClaimRpcResponse","parseReleaseRpcResponse","TrustedOperatorJobTaskProjection","claimToken","claim_token","getSupabaseAdmin"]) assert(!index.includes(forbidden),`index.ts must not export ${forbidden}`) })
test("public production service signatures accept operation inputs, not actor overrides or Request objects",()=>{ const service=byName("service.ts"); assert.doesNotMatch(service,/function \w+\([^)]*actorId/); assert.doesNotMatch(service,/function \w+\([^)]*creatorId/); assert.doesNotMatch(service,/function \w+\([^)]*operatorId/); assert.doesNotMatch(service,/Request/); assert.doesNotMatch(service,/auth.*override|override.*auth/i) })
test("browser validators reject protected actor, ownership, platform, credential, and Task 18 fields",()=>{ for (const key of ["actorId","actor_id","creatorId","creator_id","operatorId","operator_id","queueTaskId","queue_task_id","claimedBy","claimed_by","claimToken","claim_token","platform","publishing_mode","storageKey","proofScreenshotStorageKey","completionState","evidence","task18Completion"]) { assert.throws(()=>validateOperatorClaimInput({platformJobId:"00000000-0000-4000-8000-000000000010",idempotencyKey:"idemKey01",[key]:"evil"}), undefined, key); assert.throws(()=>validateOperatorProgressInput({platformJobId:"00000000-0000-4000-8000-000000000010",expectedProgressState:"not_started",expectedProgressRevision:0,nextProgressState:"preparing",idempotencyKey:"idemKey01",[key]:"evil"}), undefined, key) } })

test("public result types and production loaders expose no claim token or actor override",()=>{ const types=byName("types.ts"); const publicSection=types.replace(/export type TrustedOperatorJobTaskProjection[\s\S]*?export type OnlyFansOperatorListRecord/, "export type OnlyFansOperatorListRecord"); assert.doesNotMatch(publicSection,/claimToken|claim_token/); const loaders=byName("loaders.ts"); assert.doesNotMatch(loaders,/export async function loadOnlyFansOperatorQueue\([^)]*(actorId|deps|admin)/); assert.doesNotMatch(loaders,/export async function loadOnlyFansOperatorTaskDetail\([^)]*(actorId|deps|admin)/); assert.match(loaders,/loadOnlyFansOperatorQueueCore/); assert.match(loaders,/loadOnlyFansOperatorTaskDetailCore/); })
test("implementation scope excludes migrations, routes, server actions, media access, credentials, Fanvue, Fansly, and GET mutations",()=>{ const all=sourceFiles.map(f=>[rel(f),readFileSync(f,"utf8")] as const); for (const [name,text] of all) { if (!name.endsWith("instructions.ts")) assert.doesNotMatch(text,/credentials?|password|cookie|session token|OnlyFans API|browser automation|puppeteer|playwright/i, name); assert.doesNotMatch(text,/fanvue/i, name); assert.doesNotMatch(text,/fansly/i, name); assert.doesNotMatch(text,/GET\s*\(|method\s*===\s*["']GET["']/i, name); if (!name.endsWith("instructions.ts")) assert.doesNotMatch(text,/\.update\(|\.insert\(|\.upsert\(|final_post_url\s*=|proof_screenshot_storage_key\s*=|posted_at\s*=|posted_by\s*=/i, name) } assert(sourceFiles.length >= 9) })
