import assert from 'node:assert/strict'
import fs from 'node:fs'
import { cancelUncertainTransition, classifyMutationResponse, failureTransition, confirmCancelledReconciliation, confirmScheduleReconciliation, scheduleUncertainTransition } from '../../../lib/creator-publishing-queue/scheduling/validation'
const ui=fs.readFileSync('app/autopost/Task15PlanScheduling.tsx','utf8'), t14=fs.readFileSync('app/autopost/Task14AutopostOrchestration.tsx','utf8')
assert.match(ui,/confirm\(/); assert.match(ui,/localDate|localTime|scheduleTimezone|publicationUtcOffsetMinutes|intendedPublishAtUtc/); assert.match(ui,/operatorDueUtcOffsetMinutes|operatorDueAtUtc|operatorDueLocalDate|operatorDueLocalTime/)
assert.doesNotMatch(ui,/useEffect\([^)]*fetch|setTimeout\([^)]*fetch|automaticRetry/i); assert.doesNotMatch(ui,/scheduler\/run/)
assert.match(ui,/assisted\/manual/); assert.match(ui,/never logs into OnlyFans|never.*posts directly|will not log in or post/)
assert.match(t14,/router\.refresh\(\)/); assert.match(ui,/router\.refresh\(\)/)
assert.match(ui,/same key|same idempotency key|keep the same idempotency key/); assert.match(ui,/setKey\(newKey\(\)\)/); assert.match(ui,/setCancelKey\(newKey\(\)\)/)
assert.match(ui,/occurrences.*map|Fall-back ambiguity requires explicit offset occurrence/s); assert.match(ui,/confirmScheduleReconciliation/); assert.match(ui,/confirmCancelledReconciliation/)
assert.match(ui,/classifyMutationResponse/); assert.match(ui,/failureTransition/); assert.match(ui,/scheduleUncertainTransition/); assert.match(ui,/cancelUncertainTransition/); assert.doesNotMatch(ui,/UNCERTAIN_CODES/)
assert.match(ui,/classified\.kind==="failure"/); assert.match(ui,/classified\.kind==="confirmed"/); assert.match(ui,/setScheduleExpectation\(transition\.scheduleExpectation!/); assert.match(ui,/setCancelExpectation\(transition\.cancelExpectation!/)
for (const code of ['SCHEDULING_TRUSTED_RESPONSE_INVALID','SCHEDULING_SERVICE_UNAVAILABLE'] as const) { assert.equal(classifyMutationResponse(502,{error:code}).kind,'uncertain'); assert.equal(classifyMutationResponse(503,{error:code}).kind,'uncertain') }
for (const [code,httpStatus] of [['UNAUTHENTICATED',401],['NO_ACTIVE_SUBSCRIPTION',402],['NO_PROFILE',403],['PROFILE_LOOKUP_FAILED',500],['SUBSCRIPTION_LOOKUP_FAILED',500],['INTERNAL_ERROR',500],['SUBSCRIPTION_REQUIRED',402],['SCHEDULING_INVALID_REQUEST',400],['SCHEDULING_INELIGIBLE',409],['SCHEDULING_CONFLICT',409]] as const) { assert.equal(classifyMutationResponse(httpStatus,{error:code}).kind,'failure',code); const failure=failureTransition(); assert.equal(failure.refresh,false,code); assert.equal(failure.automaticRetry,false,code); assert.equal(failure.replacementKey,false,code); assert.equal('scheduleExpectation' in failure,false,code); assert.equal('cancelExpectation' in failure,false,code) }
const sched=scheduleUncertainTransition({publishingPlanId:'plan',platformJobId:'job',intendedPublishAtUtc:'2026-07-20T03:00:00.000Z',scheduleTimezone:'UTC',idempotencyKey:'same-key'}); assert.equal(sched.retainedIdempotencyKey,'same-key'); assert.equal(sched.refresh,true); assert.equal(sched.automaticRetry,false); assert.equal(sched.replacementKey,false); assert.deepEqual(sched.scheduleExpectation,{publishingPlanId:'plan',platformJobId:'job',intendedPublishAtUtc:'2026-07-20T03:00:00.000Z',scheduleTimezone:'UTC',idempotencyKey:'same-key'})
assert.equal(confirmScheduleReconciliation([],sched.scheduleExpectation!),false); assert.equal(confirmScheduleReconciliation([{publishingPlanId:'plan',platformJobId:'job',scheduleRevision:1,intendedPublishAtUtc:'2026-07-20T03:00:00.000Z',scheduleTimezone:'UTC',jobState:'scheduled_internally',cancelledAt:null}],sched.scheduleExpectation!),true); assert.equal(confirmScheduleReconciliation([{publishingPlanId:'plan',platformJobId:'job',scheduleRevision:1,intendedPublishAtUtc:'2026-07-20T03:00:00.000Z',scheduleTimezone:'UTC',jobState:'archived',cancelledAt:null}],sched.scheduleExpectation!),false)
const cancel=cancelUncertainTransition({publishingPlanId:'plan',cancellationReason:' reason ',idempotencyKey:'cancel-key'}); assert.equal(cancel.retainedIdempotencyKey,'cancel-key'); assert.equal(cancel.refresh,true); assert.equal(cancel.automaticRetry,false); assert.equal(cancel.replacementKey,false); assert.deepEqual(cancel.cancelExpectation,{publishingPlanId:'plan',normalizedReason:'reason',idempotencyKey:'cancel-key'})
assert.equal(confirmCancelledReconciliation([], 'plan','reason'),false); assert.equal(confirmCancelledReconciliation([{publishingPlanId:'plan',status:'cancelled',normalizedCancellationReason:'reason',allPlanJobsBelongToCreator:true,planJobRelationshipConsistent:true}], 'plan','reason'),true); assert.equal(confirmCancelledReconciliation([{publishingPlanId:'plan',status:'cancelled',normalizedCancellationReason:'reason',allPlanJobsBelongToCreator:true,planJobRelationshipConsistent:false}], 'plan','reason'),false)
assert.match(ui,/not an unschedule operation/); assert.match(ui,/cancels active scheduler events/); assert.match(ui,/archives active plan jobs/); assert.match(ui,/archives related operator queue work/); assert.match(ui,/may clear an active operator claim/); assert.match(ui,/cannot be undone after confirmation/); assert.equal((ui.match(/cannot be undone after confirmation/g)||[]).length,2); assert.doesNotMatch(ui,/cannot be undone through Phase B1/); assert.doesNotMatch(ui,/Task 15 trusted plan scheduling/); for (const label of ['Task 15','Task 21','Phase B1','Phase B2','Gate 21'] as const) assert.equal(ui.includes(label),false,label)
assert.equal((ui.match(/fetch\("\/api\/creator-publishing-queue\/scheduling\/cancel-plan/g)||[]).length,1); assert.equal((ui.match(/fetch\("\/api\/creator-publishing-queue\/scheduling\/schedule/g)||[]).length,1)
console.log('task21PlanSchedulingUi ok')
