import assert from "node:assert/strict"
import { readFileSync, readdirSync } from "node:fs"
import { join } from "node:path"
import { deriveTrustedComplianceInput } from "../../../lib/creator-publishing-queue/compliance/submission/deriveInput"
import { normalizeComplianceSubmissionFormInput, submitTrustedComplianceWithDeps } from "../../../lib/creator-publishing-queue/compliance/submission/serviceCore"
import { parseApplyRpcResponse, parseTrustedFactsRpcResponse } from "../../../lib/creator-publishing-queue/compliance/submission/facts"
import { AI_TWIN_CONSENT_VERSION } from "../../../lib/creator-publishing-queue/consent/copy"
import { getAiTwinConsentTextSha256 } from "../../../lib/creator-publishing-queue/consent/hash"
const migration = readFileSync("supabase/migrations/20260710001100_creator_publishing_trusted_compliance_submission.sql","utf8")
const page = readFileSync("app/creator/publishing-queue/[contentPackageId]/page.tsx","utf8")
const panel = readFileSync("app/creator/publishing-queue/[contentPackageId]/ComplianceEvaluationPanel.tsx","utf8")
const actions = readFileSync("app/creator/publishing-queue/[contentPackageId]/compliance-actions.ts","utf8")
const uuid="11111111-1111-4111-8111-111111111111", pkg="22222222-2222-4222-8222-222222222222", acct="33333333-3333-4333-8333-333333333333", media="44444444-4444-4444-8444-444444444444", gen="55555555-5555-4555-8555-555555555555", hash="a".repeat(64)
function facts(over:any={}){ return { facts:{ schema_version:"creator-publishing-compliance-facts-v1", package:{ id:pkg, creator_id:uuid, platform_account_id:acct, target_platform:"onlyfans", title:"t", caption_body:"c", second_person_present:false, creator_approval_status:"pending", compliance_status:"pending", compliance_policy_version:"unassigned", updated_at:"2026-01-01T00:00:00.123456Z", ...(over.package||{}) }, platform_account:{ id:acct, creator_id:uuid, platform:"onlyfans", verification_status:"verified", updated_at:"2026-01-01T00:00:00Z", is_virtual_entity:false, ...(over.platform_account||{}) }, creator_verification:{ status:"verified", updated_at:null, ...(over.creator_verification||{}) }, ai_twin_consent:{ status:"granted", attestation_version:AI_TWIN_CONSENT_VERSION, attestation_text_sha256:getAiTwinConsentTextSha256(), granted_at:"2026-01-01T00:00:00Z", revoked_at:null, updated_at:"2026-01-01T00:00:00Z", ...(over.ai_twin_consent||{}) }, media_manifest:[{ id:media, storage_key:"k", mime_type:"image/png", sha256:hash, source:"ai_pipeline", ai_generation_metadata:{ generation_id:gen } }], generation_manifest:[{ generation_id:gen, user_id:uuid, status:"completed", lora_used:null, job_type:null, body_type:null, mode:null, r2_bucket:"b", r2_key:"k", safe_classification_metadata:{ non_photorealistic:true }, ...(over.generation||{}) }], co_performer_summary:{ record_count:0, all_platform_release_confirmed:false, ...(over.co_performer_summary||{}) }, active_queue_task:false, ...(over.facts||{}) }, facts_fingerprint:hash, media_manifest_hash:hash } }
assert.equal(readdirSync("supabase/migrations").filter(f=>f.includes("trusted_compliance_submission")).length,1)
assert.match(migration,/creator_publishing_build_compliance_facts\(p_creator_id uuid, p_content_package_id uuid\)/)
assert.match(migration,/creator_publishing_load_compliance_facts\(p_creator_id uuid, p_content_package_id uuid\)/)
assert.match(migration,/creator_publishing_apply_automated_compliance_evaluation\(p_creator_id uuid,p_content_package_id uuid,p_expected_package_updated_at timestamptz/)
assert.match(migration,/security definer/g); assert.match(migration,/set search_path = public, pg_temp/g)
assert.match(migration,/revoke .*creator_publishing_build_compliance_facts[\s\S]*from PUBLIC/i); assert.match(migration,/from anon/i); assert.match(migration,/from authenticated/i); assert.match(migration,/grant execute[\s\S]*creator_publishing_load_compliance_facts[\s\S]*to service_role/i); assert.match(migration,/grant execute[\s\S]*creator_publishing_apply_automated_compliance_evaluation[\s\S]*to service_role/i)
assert.match(migration,/creator_publishing_compliance_evaluated_actor_key_uidx/); assert.match(migration,/hashtextextended/); assert.doesNotMatch(migration,/hashtext\(/); assert.doesNotMatch(migration,/insert into public\.creator_publishing_queue_tasks/i); assert.doesNotMatch(migration,/platform api|fetch\(|http/i)
for (const code of ["COMPLIANCE_PACKAGE_NOT_FOUND","COMPLIANCE_FANVUE_NOT_SUPPORTED","COMPLIANCE_PLATFORM_ACCOUNT_INVALID","COMPLIANCE_MEDIA_REQUIRED","COMPLIANCE_UNTRUSTED_MEDIA_SOURCE","COMPLIANCE_GENERATION_LINK_INVALID","COMPLIANCE_GENERATION_NOT_FOUND","COMPLIANCE_GENERATION_NOT_OWNED","COMPLIANCE_GENERATION_NOT_ELIGIBLE","COMPLIANCE_PACKAGE_LOCKED","COMPLIANCE_STALE","COMPLIANCE_INVALID_EVALUATION","COMPLIANCE_IDEMPOTENCY_CONFLICT"]) assert.match(migration,new RegExp(code))
const parsed=parseTrustedFactsRpcResponse(facts(), uuid); assert.equal(parsed.facts.package.id,pkg); assert.equal(parsed.facts.media_manifest[0].source,"ai_pipeline")
for (const bad of [facts({package:{creator_id:"99999999-9999-4999-8999-999999999999"}}), facts({package:{target_platform:"fanvue"}}), facts({platform_account:{creator_id:"99999999-9999-4999-8999-999999999999"}}), facts({facts:{active_queue_task:true}}), facts({package:{creator_approval_status:"approved"}})]) assert.throws(()=>parseTrustedFactsRpcResponse(bad, uuid))
let d=deriveTrustedComplianceInput(parsed.facts); assert.equal(d.aiDetail.non_photorealistic,true); assert.equal(d.aiDetail.photorealistic,false); assert.equal(d.input.ai_twin_consent_status,"not_applicable")
d=deriveTrustedComplianceInput(parseTrustedFactsRpcResponse(facts({generation:{lora_used:"lora-x", safe_classification_metadata:{identity_lora:true}}}),uuid).facts); assert.equal(d.aiDetail.lora_generated,true); assert.equal(d.aiDetail.ai_twin,true); assert.equal(d.aiDetail.generated_creator_likeness,true); assert.equal(d.aiDetail.photorealistic,true); assert.equal(d.aiDetail.lifelike,true); assert.equal(d.input.ai_twin_consent_status,"granted")
d=deriveTrustedComplianceInput(parseTrustedFactsRpcResponse(facts({ai_twin_consent:{revoked_at:"2026-01-01T00:00:01Z"}, generation:{lora_used:"x"}}),uuid).facts); assert.equal(d.input.ai_twin_consent_status,"missing")
d=deriveTrustedComplianceInput(parseTrustedFactsRpcResponse(facts({package:{target_platform:"fansly"}, platform_account:{platform:"fansly"}}),uuid).facts); assert.equal(d.input.ai_twin_consent_status,"not_applicable"); assert.equal(d.input.virtual_entity_registration_status,"not_registered")
assert.equal(normalizeComplianceSubmissionFormInput([["contentPackageId",pkg],["expectedPackageUpdatedAt","2026-01-01T00:00:00.123456Z"],["expectedMediaManifestHash",hash],["idempotencyKey","abcdefgh"]]).ok,true)
for (const entry of [["creator_id",uuid],["policy_version","x"],["outcome","passed"],["ai_detail","{}"],["consentStatus","granted"],["verificationStatus","verified"],["contentPackageId","bad"]]) assert.equal(normalizeComplianceSubmissionFormInput([["contentPackageId",pkg],["expectedPackageUpdatedAt","2026-01-01T00:00:00Z"],["expectedMediaManifestHash",hash],["idempotencyKey","abcdefgh"], entry as any]).ok,false)
assert.equal(normalizeComplianceSubmissionFormInput([["$ACTION_ID","x"],["contentPackageId",pkg],["expectedPackageUpdatedAt","2026-01-01T00:00:00Z"],["expectedMediaManifestHash",hash],["idempotencyKey","abcdefgh"]]).ok,true)
assert.equal(normalizeComplianceSubmissionFormInput([["contentPackageId",pkg],["expectedPackageUpdatedAt","2026-01-01"],["expectedMediaManifestHash",hash],["idempotencyKey","abcdefgh"]]).ok,false)
assert.equal(parseApplyRpcResponse({content_package_id:pkg,creator_id:uuid,prior_compliance_status:"pending",resulting_compliance_status:"passed",policy_version:"v",review_record_id:media,audit_event_ids:["123"],idempotent:false,outcome:"evaluated",evaluated_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-01T00:00:00Z"},uuid,pkg).audit_event_ids[0],"123")
assert.throws(()=>parseApplyRpcResponse({content_package_id:pkg,creator_id:uuid,resulting_compliance_status:"weird",policy_version:"v",review_record_id:media,audit_event_ids:[],idempotent:false,outcome:"evaluated",evaluated_at:"x",updated_at:"x"},uuid,pkg))
assert.equal((await submitTrustedComplianceWithDeps({contentPackageId:pkg,expectedPackageUpdatedAt:"2026-01-01T00:00:00Z",expectedMediaManifestHash:hash,idempotencyKey:"abcdefgh"},{getAuthenticatedUserId:async()=>null,getAdminClient:null as any})).code,"UNAUTHENTICATED")
assert.equal((await submitTrustedComplianceWithDeps({contentPackageId:pkg,expectedPackageUpdatedAt:"2026-01-01T00:00:00Z",expectedMediaManifestHash:hash,idempotencyKey:"abcdefgh"},{getAuthenticatedUserId:async()=>uuid,getAdminClient:()=>({rpc:async()=>({data:null,error:new Error("COMPLIANCE_STALE")})}) as any})).code,"COMPLIANCE_STALE")
for (const text of ["ComplianceEvaluationPanel","Run compliance review","Re-run compliance review","router.refresh()","no platform login occurs","no credentials are accessed","LoRA trainer uploads are unchanged","only Sirens Forge-generated media is evaluated","mediaManifestHash","pkg.updated_at","pkg.compliance_status","pkg.compliance_policy_version"]) assert.match(page+panel,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))
assert.doesNotMatch(panel+actions,/randomUUID\(|type="file"|password|api key/i)
assert.match(actions,/normalizeComplianceSubmissionFormInput\(formData\.entries\(\)\)/)
console.log("trusted compliance submission tests passed")
