"use client"
import { useMemo, useState } from "react"
import type { AutopostPackageOption, SafeCapability } from "@/lib/creator-publishing-queue/autopost/types"
export function Task14AutopostOrchestration({capabilities,packages,idempotencyKey}:{capabilities:SafeCapability[];packages:AutopostPackageOption[];idempotencyKey:string}){
  const [selected,setSelected]=useState<string[]>([]); const [result,setResult]=useState<any>(null); const [pending,setPending]=useState(false)
  const byPlatform=useMemo(()=>new Map(capabilities.map(c=>[c.platform,c])),[capabilities])
  async function submit(){ setPending(true); setResult(null); try{ const res=await fetch("/api/creator-publishing-queue/autopost/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contentPackageIds:selected,idempotencyKey})}); setResult(await res.json()) } finally{ setPending(false) } }
  return <section className="mx-auto mt-8 max-w-6xl rounded-3xl border border-cyan-300/20 bg-cyan-950/20 p-5 text-white"><p className="text-sm uppercase tracking-[0.25em] text-cyan-200">Task 14 Creator Publishing Orchestration</p><h2 className="mt-2 text-2xl font-semibold">Create a draft Publishing Plan from existing packages</h2><p className="mt-2 text-sm text-cyan-100">Select authoritative destination-specific content packages already created in the Package Composer. This form submits only package IDs and one idempotency key; captions, media, pricing, visibility, disclosure, compliance, approval, and routing are loaded from trusted server state.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{capabilities.filter(c=>["onlyfans","fansly","fanvue"].includes(c.platform)).map(c=><div key={c.platform} className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="font-semibold">{c.display_name}</div><div className="mt-1 text-sm text-cyan-100">{c.safe_label}</div><p className="mt-2 text-xs text-zinc-300">{c.safe_description}</p></div>)}</div><div className="mt-5 space-y-3">{packages.length===0?<p className="rounded-2xl border border-amber-300/30 bg-amber-950/30 p-4 text-amber-100">No existing Creator Publishing content packages are available. Create packages through the Package Composer first.</p>:packages.map(p=>{ const cap=byPlatform.get(p.target_platform); return <label key={p.id} className="flex gap-3 rounded-2xl border border-white/10 bg-black/30 p-4"><input type="checkbox" disabled={!p.eligible || cap?.availability_status!=="available"} checked={selected.includes(p.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(id=>id!==p.id))}/><span><span className="font-semibold">{p.title}</span><span className="ml-2 text-sm text-zinc-300">{cap?.display_name ?? p.target_platform} · @{p.platform_username} · {cap?.safe_label ?? "Unavailable"}</span>{p.blockedReason&&<span className="block text-sm text-amber-200">{p.blockedReason}</span>}</span></label>})}</div><button onClick={submit} disabled={pending||selected.length===0} className="mt-5 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-black disabled:cursor-not-allowed disabled:opacity-50">{pending?"Creating draft plan…":"Create draft Publishing Plan"}</button>{result&&<pre className="mt-4 overflow-auto rounded-2xl bg-black/50 p-4 text-xs text-cyan-50">{JSON.stringify(result,null,2)}</pre>}</section>
}
