import "server-only";
import { getSupabaseAdmin } from "../../supabaseAdmin";
import { requireActiveCreatorPageIdentity } from "../creatorEntitlement";
import type { SafeSchedulingView } from "./types";
import { classifyCancellationScope } from "./validation";
const terminal = new Set(["published_direct","confirmed_posted_manual","exported","failed_manual_upload","direct_publish_failed","skipped","blocked","platform_rejected","archived"]);
function fanvueCancellationScope(plan:any,planJobs:any[],creatorId:string){ const active=planJobs.filter(job=>!terminal.has(job.job_state)&&job.cancelled_at==null); const malformedActive=planJobs.some(job=>!terminal.has(job.job_state)&&job.cancelled_at!=null); const allIdentityValid=planJobs.length>0&&planJobs.every(job=>job.creator_id===creatorId&&job.publishing_plan_id===plan.id&&job.target_platform==="fanvue"&&job.publishing_mode==="direct"); return {cancellable:allIdentityValid&&!malformedActive&&active.length>0} }
export async function loadCreatorPublishingSchedulingView(): Promise<SafeSchedulingView> {
 const creatorId=(await requireActiveCreatorPageIdentity()).authUserId; const admin=getSupabaseAdmin(); const plans=await admin.from("creator_publishing_plans").select("id,status,cancelled_at,cancellation_reason,updated_at,registry_version").eq("creator_id",creatorId).order("updated_at",{ascending:false}).limit(50); if(plans.error)throw new Error("Scheduling plans unavailable"); const ids=(plans.data??[]).map((plan:any)=>plan.id); const jobs=ids.length?await admin.from("creator_publishing_platform_jobs").select("id,creator_id,publishing_plan_id,target_platform,publishing_mode,job_state,schedule_revision,intended_publish_at,operator_due_at,schedule_timezone,cancelled_at,content_package_id").in("publishing_plan_id",ids):{data:[],error:null}; if(jobs.error)throw new Error("Scheduling jobs unavailable"); const byPlan=new Map<string,any[]>(); for(const job of jobs.data??[])byPlan.set(job.publishing_plan_id,[...(byPlan.get(job.publishing_plan_id)??[]),job]); const draftPlans:any[]=[],activePlans:any[]=[],cancelledReconciliationPlans:any[]=[];
 for(const plan of plans.data??[]){ const planJobs=byPlan.get(plan.id)??[]; const active=planJobs.filter(job=>!terminal.has(job.job_state)&&job.cancelled_at==null); if(plan.status==="cancelled"){cancelledReconciliationPlans.push({publishingPlanId:plan.id,status:"cancelled",cancelledAt:plan.cancelled_at??null,normalizedCancellationReason:(plan.cancellation_reason??"").trim(),trustedTotalPlanJobCount:planJobs.length,allPlanJobsBelongToCreator:planJobs.every(job=>job.creator_id===creatorId),planJobRelationshipConsistent:planJobs.every(job=>job.publishing_plan_id===plan.id)});continue}
  const onlyJob=active.length===1?active[0]:null; const directFanvue=!!onlyJob&&onlyJob.target_platform==="fanvue"&&onlyJob.publishing_mode==="direct"; const assistedOnlyFans=!!onlyJob&&onlyJob.target_platform==="onlyfans"&&onlyJob.publishing_mode==="assisted"; const eligible=plan.status==="draft"&&!!onlyJob&&(directFanvue||assistedOnlyFans)&&onlyJob.job_state==="draft"&&!onlyJob.cancelled_at; const modeReason=directFanvue||assistedOnlyFans?"plan is no longer eligible":"destination is not an enabled OnlyFans assisted or Fanvue direct mode"; const record={publishingPlanId:plan.id,platformJobId:onlyJob?.id,title:`Publishing plan ${String(plan.id).slice(0,8)}`,status:plan.status,eligible,reason:eligible?undefined:plan.status!=="draft"?"plan is no longer a draft":active.length!==1?"plan does not contain exactly one eligible job":modeReason,targetPlatform:onlyJob?.target_platform,publishingMode:onlyJob?.publishing_mode,jobState:onlyJob?.job_state,scheduleRevision:onlyJob?.schedule_revision??null,intendedPublishAtUtc:onlyJob?.intended_publish_at??null,scheduleTimezone:onlyJob?.schedule_timezone??null,operatorDueAtUtc:onlyJob?.operator_due_at??null,cancelledAt:onlyJob?.cancelled_at??null}; if(plan.status==="draft")draftPlans.push(record); else {const cancellationScope=directFanvue?fanvueCancellationScope(plan,planJobs,creatorId):classifyCancellationScope(plan,planJobs,creatorId);if(cancellationScope.cancellable)activePlans.push({...record,eligible:false})}
 }
 return{draftPlans,activePlans,cancelledReconciliationPlans};
}
