import type { CancelPlanRequest, ResolvedScheduleTime, SchedulePlanRequest } from "./types"
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, key=/^[A-Za-z0-9_-]{8,128}$/
const protectedFields=new Set(["creatorId","creator_id","accountId","packageId","consentVersion","consentHash","targetPlatform","publishingMode","actionType","scheduleRevision","expectedScheduleRevisions","rpcName","credentials","tokens","cookies","authorization","headers","metadata"])
function plain(o:unknown){return !!o&&typeof o==="object"&&!Array.isArray(o)&&Object.getPrototypeOf(o)===Object.prototype}
function assertKeys(o:any, allowed:string[]){ if(!plain(o)) throw Object.assign(new Error("bad object"),{code:"SCHEDULING_INVALID_REQUEST"}); const seen=new Set<string>(); for(const k of Object.keys(o)){ if(seen.has(k)||!allowed.includes(k)||protectedFields.has(k)) throw Object.assign(new Error("bad key"),{code:"SCHEDULING_INVALID_REQUEST"}); seen.add(k) } }
export function normalizeSchedulePlanRequest(input:unknown):SchedulePlanRequest{ assertKeys(input,["publishingPlanId","platformJobId","localDateTime","scheduleTimezone","idempotencyKey"]); const i=input as any; assertKeys(i.localDateTime,["date","time","utcOffsetMinutes"]); if(!uuid.test(i.publishingPlanId)||!uuid.test(i.platformJobId)||!key.test(i.idempotencyKey)||typeof i.scheduleTimezone!=="string"||!i.scheduleTimezone.trim()) throw Object.assign(new Error("invalid"),{code:"SCHEDULING_INVALID_REQUEST"}); const l=i.localDateTime; if(typeof l.date!=="string"||typeof l.time!=="string"||(l.utcOffsetMinutes!==undefined&&(!Number.isInteger(l.utcOffsetMinutes)||l.utcOffsetMinutes<-840||l.utcOffsetMinutes>840))) throw Object.assign(new Error("invalid"),{code:"SCHEDULING_INVALID_REQUEST"}); return {publishingPlanId:i.publishingPlanId,platformJobId:i.platformJobId,localDateTime:{date:l.date,time:l.time,utcOffsetMinutes:l.utcOffsetMinutes},scheduleTimezone:i.scheduleTimezone.trim(),idempotencyKey:i.idempotencyKey} }
export function normalizeCancelPlanRequest(input:unknown):CancelPlanRequest{ assertKeys(input,["publishingPlanId","cancellationReason","idempotencyKey"]); const i=input as any; if(!uuid.test(i.publishingPlanId)||!key.test(i.idempotencyKey)||typeof i.cancellationReason!=="string") throw Object.assign(new Error("invalid"),{code:"SCHEDULING_INVALID_REQUEST"}); const cancellationReason=i.cancellationReason.trim(); if(cancellationReason.length<1||cancellationReason.length>500) throw Object.assign(new Error("reason"),{code:"SCHEDULING_INVALID_REQUEST"}); return {publishingPlanId:i.publishingPlanId,cancellationReason,idempotencyKey:i.idempotencyKey} }
function parts(d:Date,tz:string){ const f=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}); const m=Object.fromEntries(f.formatToParts(d).filter(p=>p.type!=="literal").map(p=>[p.type,p.value])); return {date:`${m.year}-${m.month}-${m.day}`,time:`${m.hour}:${m.minute}`} }
function offMin(d:Date,tz:string){ const p=parts(d,tz); const asUtc=Date.UTC(+p.date.slice(0,4),+p.date.slice(5,7)-1,+p.date.slice(8,10),+p.time.slice(0,2),+p.time.slice(3,5)); return Math.round((asUtc-d.getTime())/60000) }
export function resolveScheduleLocalDateTime(local:{date:string;time:string;utcOffsetMinutes?:number}, timezone:string, now=new Date()):ResolvedScheduleTime{ if(!/^\d{4}-\d{2}-\d{2}$/.test(local.date)||!/^\d{2}:\d{2}$/.test(local.time)) throw Object.assign(new Error("bad time"),{code:"SCHEDULING_INVALID_REQUEST"}); new Intl.DateTimeFormat("en-US",{timeZone:timezone}).format(new Date()); const y=+local.date.slice(0,4),mo=+local.date.slice(5,7),da=+local.date.slice(8,10),h=+local.time.slice(0,2),mi=+local.time.slice(3,5); const check=new Date(Date.UTC(y,mo-1,da,h,mi)); if(check.getUTCFullYear()!==y||check.getUTCMonth()!==mo-1||check.getUTCDate()!==da||h>23||mi>59) throw Object.assign(new Error("bad date"),{code:"SCHEDULING_INVALID_REQUEST"}); const center=Date.UTC(y,mo-1,da,h,mi); const cand:Date[]=[]; for(let m=-14*60;m<=14*60;m++){ const d=new Date(center-m*60000); const p=parts(d,timezone); if(p.date===local.date&&p.time===local.time)cand.push(d) } const uniq=[...new Map(cand.map(d=>[d.toISOString(),d])).values()]; if(uniq.length===0) throw Object.assign(new Error("nonexistent"),{code:"SCHEDULING_INVALID_REQUEST"}); const occurrences=uniq.map(d=>({utcOffsetMinutes:offMin(d,timezone),intendedPublishAt:d.toISOString(),label:`UTC${offMin(d,timezone)>=0?"+":""}${Math.trunc(offMin(d,timezone)/60)}`})); let selected=uniq[0]; if(uniq.length>1){ if(local.utcOffsetMinutes===undefined) throw Object.assign(new Error("ambiguous"),{code:"SCHEDULING_INVALID_REQUEST",occurrences}); const matches=uniq.filter(d=>offMin(d,timezone)===local.utcOffsetMinutes); if(matches.length!==1) throw Object.assign(new Error("offset mismatch"),{code:"SCHEDULING_INVALID_REQUEST",occurrences}); selected=matches[0] } else if(local.utcOffsetMinutes!==undefined&&offMin(selected,timezone)!==local.utcOffsetMinutes) throw Object.assign(new Error("offset mismatch"),{code:"SCHEDULING_INVALID_REQUEST"}); if(!Number.isFinite(selected.getTime())||selected.getTime()-now.getTime()<90*60000) throw Object.assign(new Error("too soon"),{code:"SCHEDULING_INVALID_REQUEST"}); const due=new Date(selected.getTime()-60*60000), dueParts=parts(due,timezone); return {localDate:local.date,localTime:local.time,scheduleTimezone:timezone,utcOffsetMinutes:offMin(selected,timezone),intendedPublishAt:selected.toISOString(),operatorDueAt:due.toISOString(),operatorDueLocalDate:dueParts.date,operatorDueLocalTime:dueParts.time,occurrences} }
export function confirmCancelledReconciliation(plans:{publishingPlanId:string;normalizedCancellationReason:string}[], planId:string, reason:string){ return plans.some(p=>p.publishingPlanId===planId&&p.normalizedCancellationReason===reason.trim()) }
