"use client";
import { Suspense,useEffect,useMemo,useState } from "react";
import { useSearchParams } from "next/navigation";
import { boundedCompletionState, COMPLETION_POLL_INTERVAL_MS, shouldPollCheckoutCompletion } from "@/lib/billing/checkoutCompletion";
type State="awaiting_confirmation"|"ready_to_claim"|"claimed"|"expired"|"canceled"|"unpaid"|"invalid"|"unavailable"|"temporarily_unavailable"|"claim_conflict";
export default function CheckoutComplete(){return <Suspense fallback={<main className="min-h-screen bg-slate-950 text-white flex items-center justify-center">Confirming checkout…</main>}><CheckoutCompleteContent/></Suspense>}
function CheckoutCompleteContent(){const p=useSearchParams(),session=p.get("session_id")||"",reservation=p.get("reservation")||"",[state,setState]=useState<State>("awaiting_confirmation");
 const continuation=useMemo(()=>new URLSearchParams({session_id:session,reservation,next:"/checkout/complete"}).toString(),[session,reservation]);
 useEffect(()=>{let active=true,t:any,attempt=0;const run=async()=>{attempt+=1;const q=new URLSearchParams({session_id:session,reservation});const get=await fetch(`/api/checkout/claim?${q}`,{cache:"no-store"});const data=await get.json().catch(()=>({state:"invalid"}));if(!active)return;if(data.state==="ready_to_claim"&&get.status===401){setState("ready_to_claim");return}if(data.state==="claimed"){setState("claimed");return}if(get.status===202&&shouldPollCheckoutCompletion(data.state,attempt)){setState("awaiting_confirmation");t=setTimeout(run,COMPLETION_POLL_INTERVAL_MS);return}if(get.status===202){setState(boundedCompletionState(data.state,attempt) as State);return}if(get.ok){const post=await fetch(`/api/checkout/claim?${q}`,{method:"POST"}),claimed=await post.json().catch(()=>({state:"unavailable"}));if(active)setState(claimed.state)}else setState(data.state||"unavailable")};run();return()=>{active=false;clearTimeout(t)}},[session,reservation]);
 const auth=`/login?checkout_intent=${encodeURIComponent(continuation)}`;
 return <main className="min-h-screen bg-slate-950 text-white flex items-center justify-center p-6"><section className="max-w-xl rounded-2xl border border-purple-500/30 bg-slate-900 p-8 text-center"><h1 className="text-3xl font-bold">Complete your founder access</h1>{state==="awaiting_confirmation"&&<p className="mt-4">Payment received. We are safely confirming it with the payment provider.</p>}{state==="ready_to_claim"&&<><p className="mt-4">Your payment is confirmed. Sign in or create an account to claim access.</p><div className="mt-6 flex justify-center gap-3"><a className="rounded bg-purple-600 px-4 py-2" href={auth}>Sign in</a><a className="rounded border border-purple-400 px-4 py-2" href={`${auth}&mode=signup`}>Create account</a></div></>}{state==="claimed"&&<><p className="mt-4 text-emerald-300">Your founder access has been claimed.</p><a className="mt-6 inline-block underline" href="/dashboard">Continue to Sirens Forge</a></>}{state==="claim_conflict"&&<p className="mt-4">This purchase is already associated with another account or conflicts with this profile.</p>}{["expired","canceled","unpaid","invalid","unavailable","temporarily_unavailable"].includes(state)&&<p className="mt-4">This checkout is expired, unpaid, or unavailable. No access was claimed.</p>}</section></main>}
