import type { AutopostPlanSuccess, JobState, PlanStatus, PublishingMode, SafeCapability } from "./types"
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const ts=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/
const dec=/^(0|[1-9]\d*)$/
const hash=/^[a-f0-9]{64}$/
const planStatuses = new Set<PlanStatus>(["draft","scheduled","in_progress","partially_published","completed","completed_with_failures","cancelled"])
const jobStates = new Set<JobState>(["draft","ready_to_publish","direct_publish_queued","publishing_direct","published_direct","direct_publish_failed","retry_scheduled","authentication_required","platform_rejected","scheduled_internally","awaiting_operator","due_now","claimed","scheduled_on_platform","awaiting_post_confirmation","confirmed_posted_manual","failed_manual_upload","needs_fix","skipped","blocked","archived","package_ready","ready_for_export","exported"])
const modes = new Set<PublishingMode>(["direct","assisted","planner","disabled"])
function str(v:unknown){ if(typeof v!=="string" || !v) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); return v }
function uuidStr(v:unknown){ const s=str(v); if(!uuid.test(s)) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); return s }
function tsStr(v:unknown){ const s=str(v); if(!ts.test(s)) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); return s }
function auditStr(v:unknown){ const s=String(v ?? ""); if(!dec.test(s)) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); return s }
function hashStr(v:unknown){ const s=str(v); if(!hash.test(s)) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); return s }
function labelFor(mode:PublishingMode){ return mode === "direct" ? "Direct autopost available" : mode === "assisted" ? "Assisted publish required" : mode === "planner" ? "Planner/export only" : "Unavailable" }
export function toSafeCapabilities(rows: any[]): SafeCapability[]{ return rows.map(r=>({ platform:str(r.platform), registryVersion:str(r.registry_version), displayName:str(r.display_name), publishingMode:str(r.publishing_mode) as PublishingMode, availabilityStatus:str(r.availability_status) as SafeCapability["availabilityStatus"], humanPublishingRequired:Boolean(r.human_publishing_required), connectorCanPublishImmediately:Boolean(r.connector_can_publish_immediately), connectorCanScheduleDirectly:Boolean(r.connector_can_schedule_directly), connectorCanUploadMedia:Boolean(r.connector_can_upload_media), humanOperatorQueueSupported:Boolean(r.human_operator_queue_supported), safeLabel:str(r.safe_label), safeDescription:str(r.safe_description) })) }
export function parseCreateAutopostPlanRpcResult(data:any, expectedCreatorId:string, requestedPackageIds:string[]): AutopostPlanSuccess { if(!data || typeof data!=="object") throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); const plan=data.plan; const rawJobs=Array.isArray(data.jobs)?data.jobs:[]; const registryVersion=str(data.registry_version); const planId=uuidStr(plan?.id); if(str(plan?.creator_id)!==expectedCreatorId) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); const status=str(plan?.status) as PlanStatus; if(!planStatuses.has(status)) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); if(str(plan?.registry_version)!==registryVersion) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); const planAudit=auditStr(plan?.original_plan_audit_event_id); const planJobAudits=(Array.isArray(plan?.original_job_audit_event_ids)?plan.original_job_audit_event_ids:[]).map(auditStr); const requested=new Set(requestedPackageIds); const jobIds=new Set<string>(); const packageIds=new Set<string>(); const accountIds=new Set<string>(); const jobs=rawJobs.map((j:any)=>{ const id=uuidStr(j.id); const contentPackageId=uuidStr(j.content_package_id); const accountId=uuidStr(j.platform_account_id); if(jobIds.has(id)||packageIds.has(contentPackageId)||accountIds.has(accountId)||!requested.has(contentPackageId)) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); jobIds.add(id); packageIds.add(contentPackageId); accountIds.add(accountId); if(uuidStr(j.publishing_plan_id)!==planId || str(j.creator_id)!==expectedCreatorId) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); const publishingMode=str(j.publishing_mode) as PublishingMode; const jobState=str(j.job_state) as JobState; if(!modes.has(publishingMode)||!jobStates.has(jobState)||str(j.capability_registry_version)!==registryVersion) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); const auditId=auditStr(j.original_job_audit_event_id); return { id, publishingPlanId:planId, contentPackageId, platformAccountId:accountId, targetPlatform:str(j.target_platform), platformLabel:str(j.platform_label ?? j.target_platform), publishingMode, publishingModeLabel:labelFor(publishingMode), jobState, sourcePackageFingerprint:hashStr(j.source_package_fingerprint), originalJobAuditEventId:auditId, createdAt:tsStr(j.created_at), updatedAt:tsStr(j.updated_at) } })
 if(jobs.length!==requested.size || planJobAudits.length!==jobs.length || jobs.some(j=>!planJobAudits.includes(j.originalJobAuditEventId))) throw new Error("AUTOPOST_MALFORMED_TRUSTED_RESPONSE"); return { ok:true, plan:{ id:planId, status, registryVersion, originalPlanAuditEventId:planAudit, originalJobAuditEventIds:planJobAudits, createdAt:tsStr(plan.created_at), updatedAt:tsStr(plan.updated_at) }, jobs, auditEventIds:{plan:planAudit,jobs:planJobAudits}, registryVersion, idempotent:Boolean(data.idempotent) } }
