import { getSupabaseAdmin } from "../../supabaseAdmin"
import { supabaseServer } from "../../supabaseServer"
export const AUTOPOST_SCHEMA_UNAVAILABLE = "AUTOPOST_SCHEMA_UNAVAILABLE"
function isAutopostSchemaUnavailableError(error:any){ const code=String(error?.code??""); const message=String(error?.message??""); return code === "42P01" || code === "42883" || code === "PGRST202" || /does not exist|schema cache|Could not find the function|relation .* does not exist/i.test(message) }
async function requireAutopostCreatorId(deps:Deps={}){ if(deps.getAuthenticatedUserId) return deps.getAuthenticatedUserId(); const supabase=await supabaseServer(); const {data,error}=await supabase.auth.getUser(); return error||!data.user?.id?null:data.user.id }

export const ASSISTED_OPERATOR_LEAD_MINUTES = 60
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const rfc3339=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?(Z|[+-]\d{2}:\d{2})$/
export type ScheduleInput={publishingPlanId?:unknown;platformJobId?:unknown;intendedPublishAt?:unknown;scheduleTimezone?:unknown;idempotencyKey?:unknown;expectedScheduleRevision?:unknown}
export type CancelInput={publishingPlanId?:unknown;platformJobId?:unknown;reason?:unknown}
export type Deps={getAuthenticatedUserId?:()=>Promise<string|null>;getAdminClient?:()=>any;now?:()=>Date}
function admin(d:Deps){return d.getAdminClient?.()??getSupabaseAdmin()}
function cleanId(v:unknown){if(typeof v!=="string"||!uuid.test(v)) throw Object.assign(new Error("INVALID_IDENTIFIER"),{code:"INVALID_IDENTIFIER"}); return v}
function cleanKey(v:unknown){if(typeof v!=="string"||!/^[A-Za-z0-9_-]{8,128}$/.test(v.trim())) throw Object.assign(new Error("INVALID_IDEMPOTENCY_KEY"),{code:"INVALID_IDEMPOTENCY_KEY"}); return v.trim()}
export function isValidIanaTimeZone(tz:unknown):tz is string{ if(typeof tz!=="string"||tz.trim()!==tz||tz.length<3||tz.length>128||/^UTC[+-]|^[+-]\d{2}:?\d{2}$|^Etc\/GMT[+-]/.test(tz)) return false; try{ const zones=(Intl as any).supportedValuesOf?.("timeZone") as string[]|undefined; if(zones?.includes(tz)) return true; const got=new Intl.DateTimeFormat("en-US",{timeZone:tz}).resolvedOptions().timeZone; return Boolean(got) }catch{return false}}
function partsInZone(d:Date,tz:string){const vals=new Intl.DateTimeFormat("en-CA",{timeZone:tz,hour12:false,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}).formatToParts(d).reduce((a,p)=>({...a,[p.type]:p.value}),{} as Record<string,string>); return vals}
export function validateScheduleInstant(instant:unknown, timeZone:unknown){ if(typeof instant!=="string") throw Object.assign(new Error("INVALID_RFC3339_INSTANT"),{code:"INVALID_RFC3339_INSTANT"}); const m=rfc3339.exec(instant); if(!m) throw Object.assign(new Error("INVALID_RFC3339_INSTANT"),{code:"INVALID_RFC3339_INSTANT"}); const [,y,mo,da,h,mi,s,,off]=m; if(!isValidIanaTimeZone(timeZone)) throw Object.assign(new Error("INVALID_IANA_TIMEZONE"),{code:"INVALID_IANA_TIMEZONE"}); const date=new Date(instant); if(!Number.isFinite(date.getTime())) throw Object.assign(new Error("INVALID_RFC3339_INSTANT"),{code:"INVALID_RFC3339_INSTANT"}); const iso=date.toISOString(); if(new Date(iso).getUTCFullYear()>9999) throw Object.assign(new Error("INVALID_RFC3339_INSTANT"),{code:"INVALID_RFC3339_INSTANT"}); const p=partsInZone(date,timeZone); if(p.year!==y||p.month!==mo||p.day!==da||p.hour!==h||p.minute!==mi||p.second!==s) throw Object.assign(new Error("OFFSET_TIMEZONE_INCOMPATIBLE"),{code:"OFFSET_TIMEZONE_INCOMPATIBLE"}); if(off!=="Z"){ const mins=(Number(off.slice(1,3))*60+Number(off.slice(4,6)))*(off[0]==="-"?-1:1); if(!Number.isFinite(mins)||Math.abs(mins)>14*60) throw Object.assign(new Error("INVALID_RFC3339_OFFSET"),{code:"INVALID_RFC3339_OFFSET"}) } return {iso:date.toISOString(),timeZone} }
function message(code:string){return ({UNAUTHENTICATED:"Sign in to manage schedules.",AUTOPOST_SCHEMA_UNAVAILABLE:"Scheduling is temporarily unavailable.",INVALID_IANA_TIMEZONE:"Choose a valid IANA timezone.",INVALID_RFC3339_INSTANT:"Enter a valid RFC3339 publication instant with an explicit offset.",OFFSET_TIMEZONE_INCOMPATIBLE:"The publication instant offset does not match the selected timezone.",IDEMPOTENCY_CONFLICT:"This idempotency key was already used for a different schedule.",ASSISTED_LEAD_TIME_REQUIRED:"Assisted publishing requires at least 60 minutes of operator lead time.",CANCELLATION_REASON_REQUIRED:"Enter a cancellation reason.",SCHEDULE_FAILED:"Schedule request failed."} as Record<string,string>)[code]??"Schedule request failed."}
function dbCode(e:any){const m=String(e?.message??""); for(const c of ["IDEMPOTENCY_CONFLICT","ASSISTED_LEAD_TIME_REQUIRED","STALE_SCHEDULE_REVISION","PLAN_NOT_FOUND","CANCELLATION_REASON_REQUIRED"]) if(m.includes(c)) return c; return isAutopostSchemaUnavailableError(e)?AUTOPOST_SCHEMA_UNAVAILABLE:"SCHEDULE_FAILED"}
export function httpStatusForSchedulerError(code:string){if(code==="UNAUTHENTICATED")return 401;if(code===AUTOPOST_SCHEMA_UNAVAILABLE)return 503;if(["IDEMPOTENCY_CONFLICT","STALE_SCHEDULE_REVISION"].includes(code))return 409;if(code==="SCHEDULE_FAILED")return 500;return 400}
export async function schedulePublishingPlan(input:ScheduleInput,deps:Deps={}){const creatorId=await requireAutopostCreatorId(deps); if(!creatorId)return {ok:false,code:"UNAUTHENTICATED",message:message("UNAUTHENTICATED")}; let n; try{n=validateScheduleInstant(input.intendedPublishAt,input.scheduleTimezone)}catch(e:any){return {ok:false,code:e.code,message:message(e.code)}} try{const {data,error}=await admin(deps).rpc("creator_publishing_schedule_plan",{p_creator_id:creatorId,p_publishing_plan_id:cleanId(input.publishingPlanId),p_intended_publish_at:n.iso,p_schedule_timezone:n.timeZone,p_idempotency_key:cleanKey(input.idempotencyKey),p_expected_schedule_revision:typeof input.expectedScheduleRevision==="number"?input.expectedScheduleRevision:null}); if(error)throw error; return data}catch(e:any){const code=e.code||dbCode(e); return {ok:false,code,message:message(code)}}}
export async function cancelPublishingSchedule(input:CancelInput,deps:Deps={}){const creatorId=await requireAutopostCreatorId(deps); if(!creatorId)return {ok:false,code:"UNAUTHENTICATED",message:message("UNAUTHENTICATED")}; try{const reason=typeof input.reason==="string"?input.reason.trim():""; if(reason.length<1||reason.length>500) throw Object.assign(new Error("CANCELLATION_REASON_REQUIRED"),{code:"CANCELLATION_REASON_REQUIRED"}); const {data,error}=await admin(deps).rpc("creator_publishing_cancel_schedule",{p_creator_id:creatorId,p_publishing_plan_id:cleanId(input.publishingPlanId),p_platform_job_id:input.platformJobId?cleanId(input.platformJobId):null,p_reason:reason}); if(error)throw error; return data}catch(e:any){const code=e.code||dbCode(e); return {ok:false,code,message:message(code)}}}
export function isAuthorizedSchedulerRun(req:Request){const secret=process.env.CRON_SECRET||process.env.VERCEL_CRON_SECRET; if(!secret)return false; const auth=req.headers.get("authorization")||""; const vercel=req.headers.get("x-vercel-cron-secret")||req.headers.get("x-cron-secret")||""; return auth===`Bearer ${secret}`||vercel===secret}
export async function runDueScheduler(deps:Deps={}){const client=admin(deps); const summary={scanned:0,claimed:0,processed:0,blocked:0,skipped:0,failed:0}; const {data,error}=await client.rpc("creator_publishing_claim_due_scheduler_events",{p_limit:25,p_lock_minutes:15}); if(error)throw error; const events=Array.isArray(data)?data:[]; summary.scanned=events.length; summary.claimed=events.length; for(const e of events){try{const r=await client.rpc("creator_publishing_process_scheduler_event",{p_event_id:e.id,p_lock_token:e.lock_token}); if(r.error)throw r.error; if(r.data?.blocked)summary.blocked++; else if(r.data?.skipped)summary.skipped++; else summary.processed++}catch{summary.failed++}} return summary}
