import "server-only"
import { getSupabaseAdmin } from "../../supabaseAdmin"
import { supabaseServer } from "../../supabaseServer"
import { normalizeExpectedRevisionMap } from "./schedulerFacts"
import { validateScheduleInstant } from "./schedulerTime"
export { isValidIanaTimeZone, validateScheduleInstant } from "./schedulerTime"

export const AUTOPOST_SCHEMA_UNAVAILABLE = "AUTOPOST_SCHEMA_UNAVAILABLE"
export const ASSISTED_OPERATOR_LEAD_MINUTES = 60
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const auditId=/^[1-9][0-9]{0,30}$/
const rfc3339=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/
const allowedJobStates=new Set(["draft","ready_to_publish","direct_publish_queued","publishing_direct","published_direct","direct_publish_failed","retry_scheduled","authentication_required","platform_rejected","scheduled_internally","awaiting_operator","due_now","claimed","scheduled_on_platform","awaiting_post_confirmation","confirmed_posted_manual","failed_manual_upload","needs_fix","skipped","blocked","archived","package_ready","ready_for_export","exported"])
const successCodes=new Set(["OK"])
const failureCodes=new Set(["JOB_NOT_FOUND","EXPECTED_REVISION_REQUIRED","STALE_SCHEDULE_REVISION","ASSISTED_LEAD_TIME_REQUIRED","PLAN_OWNERSHIP_INVALID","PACKAGE_OWNERSHIP_INVALID","DESTINATION_ACCOUNT_INVALID","CAPABILITY_NOT_FOUND","CAPABILITY_SNAPSHOT_STALE","PLATFORM_UNAVAILABLE","FANVUE_NOT_AVAILABLE","COMPLIANCE_BLOCKED","COMPLIANCE_MANUAL_REVIEW_REQUIRED","COMPLIANCE_NOT_PASSED","BLOCKING_MANUAL_REVIEW","CREATOR_APPROVAL_REQUIRED","CREATOR_VERIFICATION_REQUIRED","DESTINATION_ACCOUNT_VERIFICATION_REQUIRED","DESTINATION_ACCOUNT_VERIFICATION_REVOKED","AI_TWIN_CONSENT_REQUIRED","CO_PERFORMER_RELEASE_REQUIRED","MEDIA_REQUIRED","GENERATED_MEDIA_PROVENANCE_REQUIRED","STALE_SOURCE_FINGERPRINT","ACTIVE_QUEUE_TASK_CONFLICT","ACTIVE_PUBLICATION_JOB_CONFLICT","TERMINAL_JOB"])
const allowedScheduleKeys=new Set(["publishingPlanId","intendedPublishAt","scheduleTimezone","idempotencyKey","targetJobIds","expectedScheduleRevisions","actionType"])
const allowedCancelKeys=new Set(["publishingPlanId","platformJobId","reason"])
export type ScheduleInput={publishingPlanId?:unknown;intendedPublishAt?:unknown;scheduleTimezone?:unknown;idempotencyKey?:unknown;targetJobIds?:unknown;expectedScheduleRevisions?:unknown;actionType?:unknown}
export type CancelInput={publishingPlanId?:unknown;platformJobId?:unknown;reason?:unknown}
export type SchedulerJobResult={jobId:string;ok:boolean;code?:string;jobState?:string;scheduleRevision:number;operatorDueAt?:string|null;schedulerEventIds?:string[];auditEventId?:string}
export type ScheduleResult={ok:true;planId:string;results:SchedulerJobResult[];auditEventIds:string[];idempotent:boolean}|{ok:false;code:string;message:string}
export type CancellationJobResult={jobId:string;outcome:"archived"|"already_terminal"|"already_cancelled"|"noop"|"not_found";jobState?:string;scheduleRevision:number;auditEventId?:string}
export type CancelResult={ok:true;planId:string;jobId:string|null;cancelledJobs:number;results:CancellationJobResult[];idempotent:boolean}|{ok:false;code:string;message:string}
export type Deps={getAuthenticatedUserId?:()=>Promise<string|null>;getAdminClient?:()=>any}
type ParseContext={planId:string;targetJobIds:string[]}
function admin(d:Deps){return d.getAdminClient?.()??getSupabaseAdmin()}
async function creatorId(deps:Deps={}){ if(deps.getAuthenticatedUserId) return deps.getAuthenticatedUserId(); const supabase=await supabaseServer(); const {data,error}=await supabase.auth.getUser(); return error||!data.user?.id?null:data.user.id }
function schemaUnavailable(error:any){ const code=String(error?.code??""); const message=String(error?.message??""); return code === "42P01" || code === "42883" || code === "PGRST202" || /does not exist|schema cache|Could not find the function|relation .* does not exist/i.test(message) }
function cleanId(v:unknown,code="INVALID_IDENTIFIER"){if(typeof v!=="string"||!uuid.test(v)) throw Object.assign(new Error(code),{code}); return v}
function cleanKey(v:unknown){if(typeof v!=="string"||!/^[A-Za-z0-9_-]{8,128}$/.test(v.trim())) throw Object.assign(new Error("INVALID_IDEMPOTENCY_KEY"),{code:"INVALID_IDEMPOTENCY_KEY"}); return v.trim()}
function assertKeys(input:Record<string,unknown>,allowed:Set<string>){for(const k of Object.keys(input)) if(!allowed.has(k)) throw Object.assign(new Error("INVALID_REQUEST_FIELD"),{code:"INVALID_REQUEST_FIELD"})}
function cleanTargetJobIds(v:unknown){if(!Array.isArray(v)||v.length===0) throw Object.assign(new Error("TARGET_JOBS_REQUIRED"),{code:"TARGET_JOBS_REQUIRED"}); const ids=v.map(x=>cleanId(x,"INVALID_TARGET_JOB")); if(new Set(ids).size!==ids.length) throw Object.assign(new Error("DUPLICATE_TARGET_JOB"),{code:"DUPLICATE_TARGET_JOB"}); return ids.sort()}
function cleanAction(v:unknown){if(v==null)return "schedule"; if(v==="schedule"||v==="reschedule")return v; throw Object.assign(new Error("INVALID_SCHEDULE_ACTION"),{code:"INVALID_SCHEDULE_ACTION"})}
function message(code:string){return ({UNAUTHENTICATED:"Sign in to manage schedules.",AUTOPOST_SCHEMA_UNAVAILABLE:"Scheduling is temporarily unavailable.",INVALID_IANA_TIMEZONE:"Choose a valid IANA timezone.",INVALID_RFC3339_INSTANT:"Enter a valid RFC3339 publication instant with an explicit offset.",OFFSET_TIMEZONE_INCOMPATIBLE:"The publication instant offset does not match the selected timezone.",IDEMPOTENCY_CONFLICT:"This idempotency key was already used for a different schedule.",ASSISTED_LEAD_TIME_REQUIRED:"Assisted publishing requires at least 60 minutes of operator lead time.",CANCELLATION_REASON_REQUIRED:"Enter a cancellation reason.",INVALID_REQUEST_FIELD:"Schedule requests may include only the documented safe fields.",INVALID_EXPECTED_REVISION:"Expected revision must be a bounded nonnegative integer.",EXPECTED_REVISIONS_REQUIRED:"Rescheduling requires an expected revision for every targeted destination job.",TARGET_JOBS_REQUIRED:"Scheduling requires explicit destination job targets.",JOB_NOT_FOUND:"The selected destination job could not be found.",SCHEDULE_FAILED:"Schedule request failed."} as Record<string,string>)[code]??"Schedule request failed."}
function dbCode(e:any){const m=String(e?.message??""); for(const c of ["IDEMPOTENCY_CONFLICT","ASSISTED_LEAD_TIME_REQUIRED","STALE_SCHEDULE_REVISION","PLAN_NOT_FOUND","JOB_NOT_FOUND","CANCELLATION_REASON_REQUIRED","INVALID_EXPECTED_REVISION","EXPECTED_REVISIONS_REQUIRED","TARGET_JOBS_REQUIRED"]) if(m.includes(c)) return c; return schemaUnavailable(e)?AUTOPOST_SCHEMA_UNAVAILABLE:"SCHEDULE_FAILED"}
export function httpStatusForSchedulerError(code:string){if(code==="UNAUTHENTICATED")return 401;if(code===AUTOPOST_SCHEMA_UNAVAILABLE)return 503;if(["IDEMPOTENCY_CONFLICT","STALE_SCHEDULE_REVISION"].includes(code))return 409;if(code==="SCHEDULE_FAILED")return 500;return 400}
function parseStringArrayStrict(v:unknown,kind="MALFORMED_TRUSTED_RESPONSE"){ if(!Array.isArray(v)) throw Object.assign(new Error(kind),{code:kind}); const ids=v.map(x=>cleanId(x,kind)); if(new Set(ids).size!==ids.length) throw Object.assign(new Error(kind),{code:kind}); return ids }
function parseAuditArrayStrict(v:unknown){ if(!Array.isArray(v)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const ids=v.map(x=>{if(typeof x!=="string"||!auditId.test(x)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return x}); if(new Set(ids).size!==ids.length) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return ids }
function parseIso(v:unknown){ if(v==null)return null; if(typeof v!=="string") throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const iso=new Date(v).toISOString(); if(!rfc3339.test(iso)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return iso }
export function parseScheduleResult(raw:any,context:ParseContext):ScheduleResult{ if(!raw||raw.ok!==true||cleanId(raw.planId,"MALFORMED_TRUSTED_RESPONSE")!==context.planId) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const expected=new Set(context.targetJobIds); const seen=new Set<string>(); const rows=Array.isArray(raw.results)?raw.results:[]; const results=rows.map((r:any)=>{const jobId=cleanId(r.jobId,"MALFORMED_TRUSTED_RESPONSE"); if(!expected.has(jobId)||seen.has(jobId)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); seen.add(jobId); const rev=Number(r.scheduleRevision??0); if(!Number.isInteger(rev)||rev<0||rev>1_000_000) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); if(r.ok===true){ if(!r.jobState||!allowedJobStates.has(String(r.jobState))||rev<=0) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const events=parseStringArrayStrict(r.schedulerEventIds); if(events.length===0||typeof r.auditEventId!=="string"||!auditId.test(r.auditEventId)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return {jobId,ok:true,jobState:String(r.jobState),scheduleRevision:rev,operatorDueAt:parseIso(r.operatorDueAt),schedulerEventIds:events,auditEventId:r.auditEventId} }
 const code=String(r.code??""); if(!failureCodes.has(code)||r.schedulerEventIds!=null) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return {jobId,ok:false,code,scheduleRevision:rev} }); if(seen.size!==expected.size) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const audits=parseAuditArrayStrict(raw.auditEventIds??[]); if(results.filter(r=>r.ok).length!==audits.length) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return {ok:true,planId:context.planId,results,auditEventIds:audits,idempotent:raw.idempotent===true} }
export function parseCancellationResult(raw:any,context:{planId:string;jobId?:string|null}):CancelResult{ if(!raw||raw.ok!==true||cleanId(raw.planId,"MALFORMED_TRUSTED_RESPONSE")!==context.planId) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const allowedOutcomes=new Set(["archived","already_terminal","already_cancelled","noop","not_found"]); const rows=Array.isArray(raw.results)?raw.results:[]; const seen=new Set<string>(); const results=rows.map((r:any)=>{const jobId=cleanId(r.jobId,"MALFORMED_TRUSTED_RESPONSE"); if(context.jobId&&jobId!==context.jobId) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); if(seen.has(jobId)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); seen.add(jobId); const outcome=String(r.outcome); if(!allowedOutcomes.has(outcome)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); if(r.jobState!=null&&!allowedJobStates.has(String(r.jobState))) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const rev=Number(r.scheduleRevision??0); if(!Number.isInteger(rev)||rev<0||rev>1_000_000) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); if(r.auditEventId!=null&&(typeof r.auditEventId!=="string"||!auditId.test(r.auditEventId))) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return {jobId,outcome:outcome as CancellationJobResult["outcome"],jobState:typeof r.jobState==="string"?r.jobState:undefined,scheduleRevision:rev,auditEventId:r.auditEventId} }); const jobId=raw.jobId?cleanId(raw.jobId,"MALFORMED_TRUSTED_RESPONSE"):null; if(context.jobId&&jobId!==context.jobId) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return {ok:true,planId:context.planId,jobId,cancelledJobs:Number(raw.cancelledJobs??0),results,idempotent:raw.idempotent===true} }
export async function schedulePublishingPlan(input:ScheduleInput,deps:Deps={}):Promise<ScheduleResult>{ const creator=await creatorId(deps); if(!creator)return {ok:false,code:"UNAUTHENTICATED",message:message("UNAUTHENTICATED")}; try{assertKeys(input as Record<string,unknown>,allowedScheduleKeys); const n=validateScheduleInstant(input.intendedPublishAt,input.scheduleTimezone); const action=cleanAction(input.actionType); const targetJobIds=cleanTargetJobIds(input.targetJobIds); const expected=normalizeExpectedRevisionMap(input.expectedScheduleRevisions,targetJobIds,action==="reschedule"); const {data,error}=await admin(deps).rpc("creator_publishing_schedule_plan",{p_creator_id:creator,p_publishing_plan_id:cleanId(input.publishingPlanId),p_intended_publish_at:n.iso,p_schedule_timezone:n.timeZone,p_idempotency_key:cleanKey(input.idempotencyKey),p_target_job_ids:targetJobIds,p_expected_schedule_revisions:expected,p_action_type:action}); if(error)throw error; return parseScheduleResult(data,{planId:cleanId(input.publishingPlanId),targetJobIds})}catch(e:any){const code=e.code||dbCode(e); return {ok:false,code,message:message(code)}}}
export async function cancelPublishingSchedule(input:CancelInput,deps:Deps={}):Promise<CancelResult>{ const creator=await creatorId(deps); if(!creator)return {ok:false,code:"UNAUTHENTICATED",message:message("UNAUTHENTICATED")}; try{assertKeys(input as Record<string,unknown>,allowedCancelKeys); const reason=typeof input.reason==="string"?input.reason.trim():""; if(reason.length<1||reason.length>500) throw Object.assign(new Error("CANCELLATION_REASON_REQUIRED"),{code:"CANCELLATION_REASON_REQUIRED"}); const planId=cleanId(input.publishingPlanId); const jobId=input.platformJobId?cleanId(input.platformJobId):null; const {data,error}=await admin(deps).rpc("creator_publishing_cancel_schedule",{p_creator_id:creator,p_publishing_plan_id:planId,p_platform_job_id:jobId,p_reason:reason}); if(error)throw error; return parseCancellationResult(data,{planId,jobId})}catch(e:any){const code=e.code||dbCode(e); return {ok:false,code,message:message(code)}}}
export function isAuthorizedSchedulerRun(req:Request){const secret=process.env.CRON_SECRET||process.env.VERCEL_CRON_SECRET; if(!secret)return false; const auth=req.headers.get("authorization")||""; const vercel=req.headers.get("x-vercel-cron-secret")||req.headers.get("x-cron-secret")||""; return auth===`Bearer ${secret}`||vercel===secret}
export async function runDueScheduler(deps:Deps={}){const client=admin(deps); const summary={scanned:0,claimed:0,processed:0,blocked:0,skipped:0,failed:0}; const {data,error}=await client.rpc("creator_publishing_claim_due_scheduler_events",{p_limit:25,p_lock_minutes:15}); if(error)throw error; const events=Array.isArray(data)?data:[]; summary.scanned=events.length; summary.claimed=events.length; for(const e of events){try{const eventId=cleanId(e.id); const lockToken=cleanId(e.lock_token); const r=await client.rpc("creator_publishing_process_scheduler_event",{p_event_id:eventId,p_lock_token:lockToken}); if(r.error)throw r.error; if(r.data?.blocked)summary.blocked++; else if(r.data?.skipped)summary.skipped++; else summary.processed++}catch{summary.failed++}} return summary}
