export type SchedulerUiActionType="schedule"|"reschedule"|"cancel"
export type SchedulerUiJobState={jobId:string;currentJobState?:string;currentScheduleRevision:number;hasEverScheduled:boolean;lastActionType?:SchedulerUiActionType;lastActionCode?:string;cancellationOutcome?:string}
export type ScheduleResultLike={jobId:string;ok:boolean;jobState?:string;scheduleRevision?:number;code?:string}
export type CancellationResultLike={jobId:string;outcome:string;jobState?:string;scheduleRevision?:number;code?:string}
export const nonReschedulableSchedulerStates=new Set(["published_direct","confirmed_posted_manual","exported","direct_publish_failed","failed_manual_upload","skipped","blocked","platform_rejected","archived"])
export const nonInitialSchedulerStates=new Set([...nonReschedulableSchedulerStates,"scheduled_internally","awaiting_operator","due_now","ready_to_publish","direct_publish_queued","package_ready","ready_for_export","needs_fix"])
function rev(value:unknown, fallback=0){return Number.isInteger(value)&&Number(value)>=0?Number(value):fallback}
export function applyScheduleUiResults(previous:Record<string,SchedulerUiJobState>,results:ScheduleResultLike[],actionType:"schedule"|"reschedule"){const next={...previous}; for(const result of results){const prior=next[result.jobId]??{jobId:result.jobId,currentScheduleRevision:0,hasEverScheduled:false}; const returnedRevision=rev(result.scheduleRevision,prior.currentScheduleRevision); const success=result.ok===true; next[result.jobId]={jobId:result.jobId,currentJobState:result.jobState??prior.currentJobState,currentScheduleRevision:returnedRevision,hasEverScheduled:prior.hasEverScheduled||success||returnedRevision>0,lastActionType:actionType,lastActionCode:success?"OK":result.code,cancellationOutcome:prior.cancellationOutcome}} return next}
export function applyCancellationUiResults(previous:Record<string,SchedulerUiJobState>,results:CancellationResultLike[]){const next={...previous}; for(const result of results){const prior=next[result.jobId]??{jobId:result.jobId,currentScheduleRevision:0,hasEverScheduled:false}; next[result.jobId]={...prior,currentJobState:result.jobState??prior.currentJobState,currentScheduleRevision:rev(result.scheduleRevision,prior.currentScheduleRevision),lastActionType:"cancel",lastActionCode:result.code??result.outcome,cancellationOutcome:result.outcome}} return next}
export function selectInitialScheduleTargets(jobs:{id:string;jobState?:string}[],state:Record<string,SchedulerUiJobState>){return jobs.filter(job=>{const known=state[job.id]; const revision=known?.currentScheduleRevision??0; const jobState=known?.currentJobState??job.jobState??""; return revision<=0&&!known?.hasEverScheduled&&!nonInitialSchedulerStates.has(jobState)&&known?.cancellationOutcome!="archived"&&known?.cancellationOutcome!="already_cancelled"}).map(job=>job.id).sort()}
export function selectRescheduleTargets(state:Record<string,SchedulerUiJobState>){return Object.values(state).filter(job=>job.currentScheduleRevision>0&&!nonReschedulableSchedulerStates.has(job.currentJobState??"")&&job.cancellationOutcome!=="archived"&&job.cancellationOutcome!=="already_cancelled").map(job=>job.jobId).sort()}
export function preserveUncertainScheduleUiState<T extends Record<string,SchedulerUiJobState>>(state:T){return state}
