import "server-only"
import { getSupabaseAdmin } from "../../supabaseAdmin"
import { supabaseServer } from "../../supabaseServer"
import { validateScheduleInstant } from "./schedulerTime"
export { isValidIanaTimeZone, validateScheduleInstant } from "./schedulerTime"

export const AUTOPOST_SCHEMA_UNAVAILABLE = "AUTOPOST_SCHEMA_UNAVAILABLE"
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const auditId=/^[1-9][0-9]{0,30}$/
const allowedJobStates=new Set(["draft","ready_to_publish","direct_publish_queued","publishing_direct","published_direct","direct_publish_failed","retry_scheduled","authentication_required","platform_rejected","scheduled_internally","awaiting_operator","due_now","claimed","scheduled_on_platform","awaiting_post_confirmation","confirmed_posted_manual","failed_manual_upload","needs_fix","skipped","blocked","archived","package_ready","ready_for_export","exported"])
const allowedScheduleKeys=new Set(["publishingPlanId","intendedPublishAt","scheduleTimezone","idempotencyKey","expectedScheduleRevision"])
const allowedCancelKeys=new Set(["publishingPlanId","platformJobId","reason"])
export const ASSISTED_OPERATOR_LEAD_MINUTES = 60
export type ScheduleInput={publishingPlanId?:unknown;intendedPublishAt?:unknown;scheduleTimezone?:unknown;idempotencyKey?:unknown;expectedScheduleRevision?:unknown}
export type CancelInput={publishingPlanId?:unknown;platformJobId?:unknown;reason?:unknown}
export type SchedulerJobResult={jobId:string;ok:boolean;code?:string;jobState?:string;scheduleRevision:number;operatorDueAt?:string|null;schedulerEventIds?:string[];auditEventId?:string}
export type ScheduleResult={ok:true;planId:string;results:SchedulerJobResult[];auditEventIds:string[];idempotent:boolean}|{ok:false;code:string;message:string}
export type Deps={getAuthenticatedUserId?:()=>Promise<string|null>;getAdminClient?:()=>any}
function admin(d:Deps){return d.getAdminClient?.()??getSupabaseAdmin()}
async function creatorId(deps:Deps={}){ if(deps.getAuthenticatedUserId) return deps.getAuthenticatedUserId(); const supabase=await supabaseServer(); const {data,error}=await supabase.auth.getUser(); return error||!data.user?.id?null:data.user.id }
function schemaUnavailable(error:any){ const code=String(error?.code??""); const message=String(error?.message??""); return code === "42P01" || code === "42883" || code === "PGRST202" || /does not exist|schema cache|Could not find the function|relation .* does not exist/i.test(message) }
function cleanId(v:unknown,code="INVALID_IDENTIFIER"){if(typeof v!=="string"||!uuid.test(v)) throw Object.assign(new Error(code),{code}); return v}
function cleanKey(v:unknown){if(typeof v!=="string"||!/^[A-Za-z0-9_-]{8,128}$/.test(v.trim())) throw Object.assign(new Error("INVALID_IDEMPOTENCY_KEY"),{code:"INVALID_IDEMPOTENCY_KEY"}); return v.trim()}
function cleanRevision(v:unknown){if(v==null)return null; if(!Number.isInteger(v)||Number(v)<0||Number(v)>1_000_000) throw Object.assign(new Error("INVALID_EXPECTED_REVISION"),{code:"INVALID_EXPECTED_REVISION"}); return Number(v)}
function assertKeys(input:Record<string,unknown>,allowed:Set<string>){for(const k of Object.keys(input)) if(!allowed.has(k)) throw Object.assign(new Error("INVALID_REQUEST_FIELD"),{code:"INVALID_REQUEST_FIELD"})}
function message(code:string){return ({UNAUTHENTICATED:"Sign in to manage schedules.",AUTOPOST_SCHEMA_UNAVAILABLE:"Scheduling is temporarily unavailable.",INVALID_IANA_TIMEZONE:"Choose a valid IANA timezone.",INVALID_RFC3339_INSTANT:"Enter a valid RFC3339 publication instant with an explicit offset.",OFFSET_TIMEZONE_INCOMPATIBLE:"The publication instant offset does not match the selected timezone.",IDEMPOTENCY_CONFLICT:"This idempotency key was already used for a different schedule.",ASSISTED_LEAD_TIME_REQUIRED:"Assisted publishing requires at least 60 minutes of operator lead time.",CANCELLATION_REASON_REQUIRED:"Enter a cancellation reason.",INVALID_REQUEST_FIELD:"Schedule requests may include only the documented safe fields.",INVALID_EXPECTED_REVISION:"Expected revision must be a bounded nonnegative integer.",JOB_NOT_FOUND:"The selected destination job could not be found.",SCHEDULE_FAILED:"Schedule request failed."} as Record<string,string>)[code]??"Schedule request failed."}
function dbCode(e:any){const m=String(e?.message??""); for(const c of ["IDEMPOTENCY_CONFLICT","ASSISTED_LEAD_TIME_REQUIRED","STALE_SCHEDULE_REVISION","PLAN_NOT_FOUND","JOB_NOT_FOUND","CANCELLATION_REASON_REQUIRED","INVALID_EXPECTED_REVISION"]) if(m.includes(c)) return c; return schemaUnavailable(e)?AUTOPOST_SCHEMA_UNAVAILABLE:"SCHEDULE_FAILED"}
export function httpStatusForSchedulerError(code:string){if(code==="UNAUTHENTICATED")return 401;if(code===AUTOPOST_SCHEMA_UNAVAILABLE)return 503;if(["IDEMPOTENCY_CONFLICT","STALE_SCHEDULE_REVISION"].includes(code))return 409;if(code==="SCHEDULE_FAILED")return 500;return 400}
function parseStringArray(v:unknown){if(!Array.isArray(v))return []; const ids=[...new Set(v.filter((x):x is string=>typeof x==="string"&&uuid.test(x)))]; if(ids.length!==v.length) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); return ids}
export function parseScheduleResult(raw:any):ScheduleResult{ if(!raw||raw.ok!==true||!uuid.test(String(raw.planId))) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const seen=new Set<string>(); const results=(Array.isArray(raw.results)?raw.results:[]).map((r:any)=>{const jobId=cleanId(r.jobId,"MALFORMED_TRUSTED_RESPONSE"); if(seen.has(jobId)) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); seen.add(jobId); const rev=Number(r.scheduleRevision??0); if(!Number.isInteger(rev)||rev<0||rev>1_000_000) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); if(r.jobState!=null&&!allowedJobStates.has(String(r.jobState))) throw Object.assign(new Error("MALFORMED_TRUSTED_RESPONSE"),{code:"MALFORMED_TRUSTED_RESPONSE"}); const events=parseStringArray(r.schedulerEventIds??[]); const audit=typeof r.auditEventId==="string"&&auditId.test(r.auditEventId)?r.auditEventId:undefined; return {jobId,ok:r.ok===true,code:typeof r.code==="string"?r.code:undefined,jobState:typeof r.jobState==="string"?r.jobState:undefined,scheduleRevision:rev,operatorDueAt:typeof r.operatorDueAt==="string"?new Date(r.operatorDueAt).toISOString():null,schedulerEventIds:events,auditEventId:audit} }); return {ok:true,planId:String(raw.planId),results,auditEventIds:(Array.isArray(raw.auditEventIds)?raw.auditEventIds:[]).filter((x:unknown):x is string=>typeof x==="string"&&auditId.test(x)),idempotent:raw.idempotent===true} }
export async function schedulePublishingPlan(input:ScheduleInput,deps:Deps={}):Promise<ScheduleResult>{ const creator=await creatorId(deps); if(!creator)return {ok:false,code:"UNAUTHENTICATED",message:message("UNAUTHENTICATED")}; try{assertKeys(input as Record<string,unknown>,allowedScheduleKeys); const n=validateScheduleInstant(input.intendedPublishAt,input.scheduleTimezone); const {data,error}=await admin(deps).rpc("creator_publishing_schedule_plan",{p_creator_id:creator,p_publishing_plan_id:cleanId(input.publishingPlanId),p_intended_publish_at:n.iso,p_schedule_timezone:n.timeZone,p_idempotency_key:cleanKey(input.idempotencyKey),p_expected_schedule_revision:cleanRevision(input.expectedScheduleRevision)}); if(error)throw error; return parseScheduleResult(data)}catch(e:any){const code=e.code||dbCode(e); return {ok:false,code,message:message(code)}}}
export async function cancelPublishingSchedule(input:CancelInput,deps:Deps={}){ const creator=await creatorId(deps); if(!creator)return {ok:false,code:"UNAUTHENTICATED",message:message("UNAUTHENTICATED")}; try{assertKeys(input as Record<string,unknown>,allowedCancelKeys); const reason=typeof input.reason==="string"?input.reason.trim():""; if(reason.length<1||reason.length>500) throw Object.assign(new Error("CANCELLATION_REASON_REQUIRED"),{code:"CANCELLATION_REASON_REQUIRED"}); const {data,error}=await admin(deps).rpc("creator_publishing_cancel_schedule",{p_creator_id:creator,p_publishing_plan_id:cleanId(input.publishingPlanId),p_platform_job_id:input.platformJobId?cleanId(input.platformJobId):null,p_reason:reason}); if(error)throw error; return {ok:true,planId:cleanId(data?.planId),jobId:data?.jobId?cleanId(data.jobId):null,cancelledJobs:Number(data?.cancelledJobs??0),idempotent:data?.idempotent===true}}catch(e:any){const code=e.code||dbCode(e); return {ok:false,code,message:message(code)}}}
export function isAuthorizedSchedulerRun(req:Request){const secret=process.env.CRON_SECRET||process.env.VERCEL_CRON_SECRET; if(!secret)return false; const auth=req.headers.get("authorization")||""; const vercel=req.headers.get("x-vercel-cron-secret")||req.headers.get("x-cron-secret")||""; return auth===`Bearer ${secret}`||vercel===secret}
export async function runDueScheduler(deps:Deps={}){const client=admin(deps); const summary={scanned:0,claimed:0,processed:0,blocked:0,skipped:0,failed:0}; const {data,error}=await client.rpc("creator_publishing_claim_due_scheduler_events",{p_limit:25,p_lock_minutes:15}); if(error)throw error; const events=Array.isArray(data)?data:[]; summary.scanned=events.length; summary.claimed=events.length; for(const e of events){try{const eventId=cleanId(e.id); const lockToken=cleanId(e.lock_token); const r=await client.rpc("creator_publishing_process_scheduler_event",{p_event_id:eventId,p_lock_token:lockToken}); if(r.error)throw r.error; if(r.data?.blocked)summary.blocked++; else if(r.data?.skipped)summary.skipped++; else summary.processed++}catch{summary.failed++}} return summary}
