import "server-only"
import { randomUUID } from "node:crypto"
import { getSupabaseAdmin } from "../../supabaseAdmin"
import { supabaseServer } from "../../supabaseServer"
import { normalizeAutopostPlanRequest } from "./validation"
import type { AutopostPlanRequest, AutopostPlanResult, SafeCapability, AutopostPackageOption } from "./types"
async function currentCreatorId(){ const supabase=await supabaseServer(); const {data,error}=await supabase.auth.getUser(); if(error||!data.user?.id) return null; return data.user.id }
function msg(code:string){ return ({UNAUTHENTICATED:"Sign in to create an Autopost plan.",IDEMPOTENCY_CONFLICT:"This idempotency key was already used for different Autopost inputs.",NO_CONTENT_PACKAGES_SELECTED:"Select at least one existing content package.",FANVUE_NOT_AVAILABLE:"Fanvue is frozen for new Autopost plans.",PLATFORM_UNAVAILABLE:"That destination is unavailable for active Autopost plan creation.",GENERATED_MEDIA_PROVENANCE_REQUIRED:"Every selected package must have Sirens Forge generated media attached.",ACTIVE_PUBLICATION_JOB_CONFLICT:"A selected package already belongs to an active Autopost publication job."} as Record<string,string>)[code] ?? "Autopost plan creation failed." }
function codeFromDb(e:any){ const m=String(e?.message??""); for(const c of ["IDEMPOTENCY_CONFLICT","NO_CONTENT_PACKAGES_SELECTED","CONTENT_PACKAGE_NOT_FOUND","FANVUE_NOT_AVAILABLE","PLATFORM_UNAVAILABLE","GENERATED_MEDIA_PROVENANCE_REQUIRED","ACTIVE_PUBLICATION_JOB_CONFLICT","UNAUTHENTICATED"]) if(m.includes(c)) return c; return "AUTOPOST_CREATE_FAILED" }
export async function loadAutopostCapabilities():Promise<SafeCapability[]>{ const admin=getSupabaseAdmin(); const {data,error}=await admin.from("creator_publishing_platform_capability_public").select("platform,registry_version,display_name,publishing_mode,availability_status,human_publishing_required,connector_can_publish_immediately,connector_can_schedule_directly,connector_can_upload_media,human_operator_queue_supported,safe_label,safe_description").order("platform",{ascending:true}); if(error) throw new Error("Autopost capabilities could not be loaded."); return (data??[]) as SafeCapability[] }
export async function loadAutopostPackageOptions():Promise<AutopostPackageOption[]>{ const creatorId=await currentCreatorId(); if(!creatorId) return []; const admin=getSupabaseAdmin(); const {data,error}=await admin.from("creator_publishing_content_packages").select("id,title,target_platform,platform_account_id,updated_at,creator_platform_accounts!creator_publishing_content_platform_account_fk(platform_username),creator_publishing_media_assets(id,source,ai_generation_metadata)").eq("creator_id",creatorId).order("updated_at",{ascending:false}).limit(50); if(error) throw new Error("Autopost package options could not be loaded."); return ((data??[]) as any[]).map(p=>{ const media=p.creator_publishing_media_assets??[]; const fanvue=p.target_platform==="fanvue"; const mediaOk=media.length>0&&media.every((m:any)=>m.source==="ai_pipeline"&&typeof m.ai_generation_metadata?.generation_id==="string"); return {id:p.id,title:p.title,target_platform:p.target_platform,platform_account_id:p.platform_account_id,platform_username:p.creator_platform_accounts?.platform_username??"unknown",updated_at:p.updated_at,eligible:!fanvue&&mediaOk,blockedReason:fanvue?"Fanvue is frozen for new Autopost plans.":!mediaOk?"Attach Sirens Forge generated media before creating a plan.":null} }) }
export async function createAutopostPlan(input:AutopostPlanRequest):Promise<AutopostPlanResult>{ const creatorId=await currentCreatorId(); if(!creatorId) return {ok:false,code:"UNAUTHENTICATED",message:msg("UNAUTHENTICATED")}; let n; try{ n=normalizeAutopostPlanRequest(input); }catch(e:any){ const code=e.code??"AUTOPOST_INVALID_REQUEST"; return {ok:false,code,message:msg(code)} } const admin=getSupabaseAdmin(); const {data,error}=await admin.rpc("creator_publishing_create_autopost_plan",{p_creator_id:creatorId,p_content_package_ids:n.contentPackageIds,p_idempotency_key:n.idempotencyKey || randomUUID()}); if(error){ const code=codeFromDb(error); return {ok:false,code,message:msg(code)} } const d=data as any; return {ok:true,plan:d.plan,jobs:d.jobs??[],auditEventIds:{plan:d.audit_event_ids?.plan,jobs:d.audit_event_ids?.jobs??[]},registryVersion:d.registry_version,idempotent:Boolean(d.idempotent),requestFingerprint:d.request_fingerprint} }
