import "server-only"
import { randomUUID } from "node:crypto"
import { getSupabaseAdmin } from "../../supabaseAdmin"
import { supabaseServer } from "../../supabaseServer"
import { normalizeAutopostPlanRequest } from "./validation"
import { parseCreateAutopostPlanRpcResult, toSafeCapabilities } from "./response"
import { validateAutopostGeneratedMediaFacts } from "./sourceFingerprint"
import type { AutopostPlanRequest, AutopostPlanResult, SafeCapability, AutopostPackageOption } from "./types"

type Deps = { getAuthenticatedUserId?:()=>Promise<string|null>; getAdminClient?:()=>any; randomUUID?:()=>string }
export const AUTOPOST_SCHEMA_UNAVAILABLE = "AUTOPOST_SCHEMA_UNAVAILABLE"
export function isAutopostSchemaUnavailableError(error:any){ const code=String(error?.code??""); const message=String(error?.message??""); return code === "42P01" || code === "42883" || code === "PGRST202" || /does not exist|schema cache|Could not find the function|relation .* does not exist/i.test(message) }
function autopostSchemaUnavailable(){ return Object.assign(new Error(AUTOPOST_SCHEMA_UNAVAILABLE),{code:AUTOPOST_SCHEMA_UNAVAILABLE}) }
async function defaultCreatorId(){ const supabase=await supabaseServer(); const {data,error}=await supabase.auth.getUser(); if(error||!data.user?.id) return null; return data.user.id }
function admin(deps:Deps){ return deps.getAdminClient?.() ?? getSupabaseAdmin() }
function msg(code:string){ return ({UNAUTHENTICATED:"Sign in to use Autopost orchestration.",AUTOPOST_INVALID_REQUEST:"Autopost accepted only selected package IDs and one idempotency key.",IDEMPOTENCY_CONFLICT:"This idempotency key was already used for different Autopost inputs.",NO_CONTENT_PACKAGES_SELECTED:"Select at least one existing content package.",CONTENT_PACKAGE_NOT_FOUND:"A selected content package could not be found.",FANVUE_NOT_AVAILABLE:"Fanvue is frozen for new Autopost plans.",PLATFORM_UNAVAILABLE:"That destination is unavailable for active Autopost plan creation.",CAPABILITY_REGISTRY_INCONSISTENT:"Autopost routing is temporarily unavailable.",GENERATED_MEDIA_PROVENANCE_REQUIRED:"Every selected package must have trusted Sirens Forge generated media attached.",ACTIVE_PUBLICATION_JOB_CONFLICT:"A selected package already belongs to an active Autopost publication job.",DUPLICATE_DESTINATION_ACCOUNT:"Select only one package for each destination account.",AUTOPOST_SCHEMA_UNAVAILABLE:"Autopost orchestration is temporarily unavailable.",AUTOPOST_CREATE_FAILED:"Autopost plan creation failed.",AUTOPOST_MALFORMED_TRUSTED_RESPONSE:"Autopost plan creation returned an invalid trusted response."} as Record<string,string>)[code] ?? "Autopost plan creation failed." }
function codeFromDb(e:any){ const m=String(e?.message??""); for(const c of ["IDEMPOTENCY_CONFLICT","NO_CONTENT_PACKAGES_SELECTED","CONTENT_PACKAGE_NOT_FOUND","FANVUE_NOT_AVAILABLE","PLATFORM_UNAVAILABLE","CAPABILITY_REGISTRY_INCONSISTENT","GENERATED_MEDIA_PROVENANCE_REQUIRED","ACTIVE_PUBLICATION_JOB_CONFLICT","DUPLICATE_DESTINATION_ACCOUNT","UNAUTHENTICATED",AUTOPOST_SCHEMA_UNAVAILABLE]) if(m.includes(c)) return c; if(isAutopostSchemaUnavailableError(e)) return AUTOPOST_SCHEMA_UNAVAILABLE; return "AUTOPOST_CREATE_FAILED" }
export function httpStatusForAutopostError(code:string){ if(code==="UNAUTHENTICATED") return 401; if(["IDEMPOTENCY_CONFLICT","ACTIVE_PUBLICATION_JOB_CONFLICT","DUPLICATE_DESTINATION_ACCOUNT"].includes(code)) return 409; if(code===AUTOPOST_SCHEMA_UNAVAILABLE) return 503; if(["AUTOPOST_CREATE_FAILED","AUTOPOST_MALFORMED_TRUSTED_RESPONSE","CAPABILITY_REGISTRY_INCONSISTENT"].includes(code)) return 500; return 400 }
export async function requireAutopostCreatorId(deps:Deps={}): Promise<string|null>{ return (deps.getAuthenticatedUserId ?? defaultCreatorId)() }
export async function loadAutopostCapabilities(deps:Deps={}):Promise<SafeCapability[]>{ const creatorId=await requireAutopostCreatorId(deps); if(!creatorId) throw Object.assign(new Error("UNAUTHENTICATED"),{code:"UNAUTHENTICATED"}); const {data,error}=await admin(deps).from("creator_publishing_platform_capability_public").select("platform,registry_version,display_name,publishing_mode,availability_status,human_publishing_required,connector_can_publish_immediately,connector_can_schedule_directly,connector_can_upload_media,human_operator_queue_supported,safe_label,safe_description").order("platform",{ascending:true}); if(error) throw isAutopostSchemaUnavailableError(error) ? autopostSchemaUnavailable() : new Error("Autopost capabilities could not be loaded."); return toSafeCapabilities(data??[]) }
export async function loadAutopostPackageOptions(deps:Deps={}):Promise<AutopostPackageOption[]>{ const creatorId=await requireAutopostCreatorId(deps); if(!creatorId) return []; const {data,error}=await admin(deps).from("creator_publishing_content_packages").select("id,title,target_platform,platform_account_id,updated_at,creator_platform_accounts!creator_publishing_content_platform_account_fk(platform_username),creator_publishing_media_assets(id,storage_key,mime_type,sha256,source,ai_generation_metadata)").eq("creator_id",creatorId).order("updated_at",{ascending:false}).limit(50); if(error) throw isAutopostSchemaUnavailableError(error) ? autopostSchemaUnavailable() : new Error("Autopost package options could not be loaded."); return ((data??[]) as any[]).map(p=>{ const media=p.creator_publishing_media_assets??[]; const fanvue=p.target_platform==="fanvue"; const mediaOk=validateAutopostGeneratedMediaFacts(media); return {id:p.id,title:p.title,targetPlatform:p.target_platform,platformAccountId:p.platform_account_id,platformUsername:p.creator_platform_accounts?.platform_username??"unknown",updatedAt:p.updated_at,eligible:!fanvue&&mediaOk,blockedReason:fanvue?"Fanvue is frozen for new Autopost plans.":!mediaOk?"Attach trusted Sirens Forge generated media before creating a plan.":null} }) }
export async function createAutopostPlan(input:AutopostPlanRequest, deps:Deps={}):Promise<AutopostPlanResult>{ const creatorId=await requireAutopostCreatorId(deps); if(!creatorId) return {ok:false,code:"UNAUTHENTICATED",message:msg("UNAUTHENTICATED")}; let n; try{ n=normalizeAutopostPlanRequest(input); }catch(e:any){ const code=e.code??"AUTOPOST_INVALID_REQUEST"; return {ok:false,code,message:msg(code)} } const client=admin(deps); const {data,error}=await client.rpc("creator_publishing_create_autopost_plan",{p_creator_id:creatorId,p_content_package_ids:n.contentPackageIds,p_idempotency_key:n.idempotencyKey || (deps.randomUUID ?? randomUUID)()}); if(error){ const code=codeFromDb(error); return {ok:false,code,message:msg(code)} } try { return parseCreateAutopostPlanRpcResult(data, creatorId, n.contentPackageIds) } catch(e:any) { return {ok:false,code:"AUTOPOST_MALFORMED_TRUSTED_RESPONSE",message:msg("AUTOPOST_MALFORMED_TRUSTED_RESPONSE")} } }
