import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { createCheckoutHandler,productionCheckoutConfiguration,type CheckoutDependencies } from "../../../app/api/checkout/subscription/route";
import { checkoutApplicationBaseUrl, checkoutCreationConfiguration, checkoutSupabaseUrl, networkRateLimitHash, payFirstCheckoutEnabled, trustedSourceNetwork } from "../../../lib/billing/checkoutCreationSecurity";
import { PAY_FIRST_CHECKOUT_CONTRACT,generatePurchaserToken,hashPurchaserToken,isPurchaserToken,PURCHASER_COOKIE,PURCHASER_TOKEN_MAX_AGE } from "../../../lib/billing/payFirstCheckout";
import { paymentMethodTypesForLaunchPlan } from "../../../lib/billing/launchCheckoutPolicy";
let assertions=0;const equal=(a:unknown,b:unknown)=>{assert.deepEqual(a,b);assertions++};
const logged:any[][]=[];const originalConsoleError=console.error;console.error=(...values:any[])=>{logged.push(values)};
const reservation="11111111-1111-4111-8111-111111111111",token="A".repeat(43),networkHash="b".repeat(64);
const state={inputs:[] as any[],hashes:[] as string[],networks:[] as string[],associated:[] as any[],released:0,privileged:0,generated:0,retrieved:0,expired:[] as string[],switched:[] as any[]};
const reset=()=>{state.inputs=[];state.hashes=[];state.networks=[];state.associated=[];state.released=0;state.privileged=0;state.generated=0;state.retrieved=0;state.expired=[];state.switched=[]};
const deps=(overrides:Partial<CheckoutDependencies>={}):CheckoutDependencies=>({
 enabled:()=>true,preflight:()=>({priceId:"price_server",baseUrl:"https://sirens.test",networkHash}),generateToken:()=>{state.generated++;return token},retrievePrice:async()=>({unitAmount:10000}),
 createSession:async(input,key)=>{state.inputs.push({input,key});return{id:"cs_server12345678",url:"https://checkout.stripe.com/pay/server"}},retrieveSession:async id=>{state.retrieved++;return{id,url:"https://checkout.stripe.com/pay/server",status:"open"}},expireSession:async id=>{state.expired.push(id);return{id,status:"expired"}},
 privileged:async()=>{state.privileged++;return{tier:async()=>({is_active:true}),switchReservation:async(hash,network,plan,id,session)=>{state.switched.push([hash,network,plan,id,session]);return{switch_outcome:"switched",reservation_id:"22222222-2222-4222-8222-222222222222",expires_at:new Date(Date.now()+3_599_000).toISOString(),reservation_tier:plan}},reserve:async(hash,network)=>{state.hashes.push(hash);state.networks.push(network);return{reservation_id:reservation,expires_at:new Date(Date.now()+3_599_000).toISOString()}},release:async()=>{state.released++},associate:async(...args)=>{state.associated.push(args)},referral:async()=>({code:"SERVER",affiliateUserId:"affiliate",commissionPercent:20,destination:"acct_server",connectOnboarded:true,payable:true})}},...overrides});
const request=(body:any,cookie?:string,url="https://sirens.test/api/checkout/subscription")=>new Request(url,{method:"POST",headers:{"content-type":"application/json",...(cookie?{cookie}: {})},body:JSON.stringify(body)});

// Server-only activation gate runs before token generation, privileged DB, RPC, or Stripe boundaries.
for(const value of [undefined,"","false","0","yes","truth","TRUE"]){equal(payFirstCheckoutEnabled(value),false)}equal(payFirstCheckoutEnabled(" true "),true);
for(const body of [{tierName:"og_throne"},{tierName:"og_throne",PAY_FIRST_CHECKOUT_ENABLED:true}]){reset();const inactive=deps({enabled:()=>false});const response=await createCheckoutHandler(inactive)(request(body,`${PURCHASER_COOKIE}=override`,"https://sirens.test/api/checkout/subscription?PAY_FIRST_CHECKOUT_ENABLED=true"));equal(response.status,503);equal((await response.json()).code,"CHECKOUT_INACTIVE");equal(state.privileged,0);equal(state.generated,0);equal(state.inputs.length,0);equal(state.retrieved,0);equal(response.headers.get("set-cookie"),null)}
reset();let preflightCalls=0;const missing=deps({preflight:()=>{preflightCalls++;return null}});let response=await createCheckoutHandler(missing)(request({tierName:"og_throne"}));equal(response.status,503);equal(preflightCalls,1);equal(state.privileged,0);equal(state.generated,0);equal(state.inputs.length,0);

for(const tier of ["og_throne","early_bird"] as const){reset();const before=Math.floor(Date.now()/1000);const response=await createCheckoutHandler(deps())(request({tierName:tier,referralCode:"server"}));equal(response.status,200);equal((await response.json()).url,"https://checkout.stripe.com/pay/server");equal(response.headers.get("set-cookie")?.includes(`${PURCHASER_COOKIE}=`),true);equal(response.headers.get("set-cookie")?.includes(`Max-Age=${PURCHASER_TOKEN_MAX_AGE}`),true);const input=state.inputs[0].input;equal(input.mode,tier==="og_throne"?"payment":"subscription");equal(input.line_items[0].price,"price_server");equal(input.payment_method_types,tier==="og_throne"?paymentMethodTypesForLaunchPlan(tier,process.env.STRIPE_OG_BNPL_METHODS):["card"]);equal(input.metadata.checkout_contract,PAY_FIRST_CHECKOUT_CONTRACT);equal(JSON.stringify(input).includes(token),false);equal(input.success_url,`https://sirens.test/checkout/complete?session_id={CHECKOUT_SESSION_ID}&reservation=${reservation}`);equal(input.cancel_url.includes(token),false);equal(state.hashes[0],hashPurchaserToken(token));equal(state.networks[0],networkHash);equal(input.expires_at>=before+3598&&input.expires_at<=before+3600,true)}
for(const tier of ["prime_access","starter_hit","standard","",null])equal((await createCheckoutHandler(deps())(request({tier}))).status,400);
for(const evil of [{tierName:"og_throne",priceId:"evil"},{tierName:"og_throne",mode:"subscription"},{tierName:"early_bird",destination:"acct_evil"},{tierName:"early_bird",commissionPercent:99}])equal((await createCheckoutHandler(deps())(request(evil))).status,400);
equal(isPurchaserToken(generatePurchaserToken()),true);equal(Buffer.from(generatePurchaserToken(),"base64url").length,32);equal(hashPurchaserToken(token).length,64);equal(PURCHASER_TOKEN_MAX_AGE,604800);
reset();const limited=deps();const db=await limited.privileged();limited.privileged=async()=>({...db,reserve:async()=>{throw new Error("rate_limit_daily")}});response=await createCheckoutHandler(limited)(request({tierName:"og_throne"}));equal(response.status,429);equal((await response.json()).code,"RATE_LIMITED");equal(state.inputs.length,0);

// Trusted platform source and HMAC privacy contract.
const trusted=(ip:string,extra:Record<string,string>={})=>new Request("https://sirens.test",{headers:{"x-vercel-forwarded-for":ip,...extra}});
equal(trustedSourceNetwork(trusted("8.8.8.8")),"8.8.8.8");equal(trustedSourceNetwork(trusted(" 8.8.4.4 ")),"8.8.4.4");
for(const value of ["","8.8.8.8, 1.1.1.1","not-ip","127.0.0.1","10.0.0.1","192.168.1.1","::1","fd00::1"])equal(trustedSourceNetwork(trusted(value)),null);
for(const value of ["203.0.113.1","198.51.100.1","192.0.2.1","0:0:0:0:0:0:0:1","::","0:0:0:0:0:0:0:0","::ffff:8.8.8.8","0:0:0:0:0:ffff:0808:0808"])equal(trustedSourceNetwork(trusted(value)),null);
for(const value of ["64:ff9b:1::1","100:0:0:1::1","3fff::1","5f00::1","192.88.99.1"])equal(trustedSourceNetwork(trusted(value)),null);
for(const value of ["203.0.114.1","198.51.101.1","192.30.252.153"])equal(trustedSourceNetwork(trusted(value)),value);
for(const value of ["64:ff9b::1","2001:20::1","2001:30::1","2001:1::1","2001:1::2","2001:1::3","2001:3::1","2001:4:112::1","2620:4f:8000::1"])equal(trustedSourceNetwork(trusted(value)),value);
equal(trustedSourceNetwork(new Request("https://sirens.test",{headers:{"x-forwarded-for":"8.8.8.8","x-real-ip":"8.8.8.8","user-agent":"fingerprint"}})),"8.8.8.8");
equal(trustedSourceNetwork(new Request("https://sirens.test",{headers:{"x-real-ip":"8.8.4.4"}})),"8.8.4.4");
equal(trustedSourceNetwork(new Request("https://sirens.test",{headers:{"x-vercel-forwarded-for":"8.8.8.8","x-forwarded-for":"1.1.1.1"}})),null);
equal(trustedSourceNetwork(new Request("https://sirens.test",{headers:{"x-vercel-forwarded-for":"2606:4700:4700::1111","x-real-ip":"2606:4700:4700:0:0:0:0:1111"}})),"2606:4700:4700:0:0:0:0:1111");
const secret="s".repeat(32),h1=networkRateLimitHash("8.8.8.8",secret);equal(Buffer.from(h1,"hex").length,32);equal(h1===networkRateLimitHash("1.1.1.1",secret),false);equal(h1===networkRateLimitHash("8.8.8.8","t".repeat(32)),false);
const compressed="2606:4700:4700::1111",expanded="2606:4700:4700:0:0:0:0:1111";equal(networkRateLimitHash(compressed,secret),networkRateLimitHash(expanded,secret));equal(networkRateLimitHash(compressed.toUpperCase(),secret),networkRateLimitHash(compressed,secret));equal(networkRateLimitHash(compressed,secret)===networkRateLimitHash("2606:4700:4700::1001",secret),false);equal(Buffer.from(networkRateLimitHash(compressed,secret),"hex").length,32);
const complete={request:trusted("8.8.8.8"),rateLimitSecret:secret,supabaseUrl:"https://project.supabase.co",serviceRoleKey:"service",stripeSecret:"sk_test_inert",priceId:"price_inert",canonicalUrl:"https://sirens.test"};equal(checkoutCreationConfiguration(complete)?.networkHash,h1);
equal(checkoutSupabaseUrl(undefined," https://public.inert.supabase.co/path "),"https://public.inert.supabase.co");equal(checkoutSupabaseUrl("https://server.inert.supabase.co","https://public.inert.supabase.co"),"https://server.inert.supabase.co");equal(checkoutSupabaseUrl("   ","https://public.inert.supabase.co"),"https://public.inert.supabase.co");
for(const [server,publicUrl] of [["http://server.example","https://valid-fallback.example"],[undefined,"http://public.example"],["https://user:pass@server.example",undefined],["https://server.example?query=1",undefined],["https://server.example#fragment",undefined],["https://server .example",undefined],["https://server.example\n.evil",undefined],["ftp://server.example",undefined]] as const)equal(checkoutSupabaseUrl(server,publicUrl),null);
equal(checkoutSupabaseUrl("http://localhost:54321/path"),"http://localhost:54321");equal(checkoutSupabaseUrl("http://127.12.34.56:54321"),"http://127.12.34.56:54321");
for(const key of ["rateLimitSecret","supabaseUrl","serviceRoleKey","stripeSecret","priceId"] as const)equal(checkoutCreationConfiguration({...complete,[key]:undefined}),null);
equal(checkoutCreationConfiguration({...complete,request:new Request("https://sirens.test")}),null);equal(checkoutCreationConfiguration({...complete,canonicalUrl:"http://sirens.test"}),null);
const forwarded=new Request("https://framework.invalid/api",{headers:{"x-forwarded-proto":"https","x-forwarded-host":"checkout.example.com"}});
equal(checkoutApplicationBaseUrl(forwarded),"https://checkout.example.com");equal(checkoutApplicationBaseUrl(forwarded,"https://configured.example.com/base/"),"https://configured.example.com/base");
equal(checkoutApplicationBaseUrl(new Request("https://framework.example/api",{headers:{host:"bounded.example.com"}})),"https://bounded.example.com");equal(checkoutApplicationBaseUrl(new Request("https://framework.example/api")),"https://framework.example");
equal(checkoutApplicationBaseUrl(new Request("http://localhost:3000/api")),"http://localhost:3000");equal(checkoutApplicationBaseUrl(new Request("http://example.com/api")),null);
for(const headers of [{"x-forwarded-proto":"https,http","x-forwarded-host":"example.com"},{"x-forwarded-proto":"https","x-forwarded-host":"one.example,two.example"},{"x-forwarded-proto":"ftp","x-forwarded-host":"example.com"}])equal(checkoutApplicationBaseUrl(new Request("https://framework.example/api",{headers})),null);
for(const configured of ["https://user:pass@example.com","https://example.com/?query=1","https://example.com/#fragment","ftp://example.com","https://bad host.example"])equal(checkoutApplicationBaseUrl(forwarded,configured),null);
equal(checkoutCreationConfiguration({...complete,canonicalUrl:undefined,request:new Request("https://framework.invalid/api",{headers:{"x-vercel-forwarded-for":"8.8.8.8","x-forwarded-proto":"https","x-forwarded-host":"checkout.example.com"}})})?.baseUrl,"https://checkout.example.com");

// Actual Production-shaped configuration wiring remains pure and all provider/database boundaries are injected.
const inertEnvironment={PAY_FIRST_CHECKOUT_ENABLED:"true",CHECKOUT_RATE_LIMIT_SECRET:"inert-rate-limit-secret-value-123456789",NEXT_PUBLIC_SUPABASE_URL:"https://public-project.inert.supabase.co/path",SUPABASE_SERVICE_ROLE_KEY:"inert-service-role-value",STRIPE_SECRET_KEY:"sk_test_inert_only",STRIPE_PRICE_OG_THRONE:"price_og_inert"};
const productionRequest=request({tierName:"og_throne"},undefined,"https://framework.invalid/api/checkout/subscription");productionRequest.headers.set("x-forwarded-proto","https");productionRequest.headers.set("x-forwarded-host","production-origin.inert");productionRequest.headers.set("x-forwarded-for","8.8.8.8");
const productionResolved=productionCheckoutConfiguration(inertEnvironment,"og_throne",productionRequest);equal(productionResolved.enabled,true);equal(productionResolved.supabaseUrl,"https://public-project.inert.supabase.co");equal(productionResolved.configuration?.baseUrl,"https://production-origin.inert");equal(productionResolved.configuration?.priceId,"price_og_inert");equal(productionResolved.configuration?.networkHash.length,64);
const preferredResolved=productionCheckoutConfiguration({...inertEnvironment,SUPABASE_URL:"https://private-project.inert.supabase.co"},"og_throne",productionRequest);equal(preferredResolved.supabaseUrl,"https://private-project.inert.supabase.co");
reset();const productionDeps=deps({enabled:()=>productionResolved.enabled,preflight:()=>productionResolved.configuration,createSession:async(input,key)=>{state.inputs.push({input,key});return{id:"cs_inert",url:"https://checkout.stripe.com/pay/inert"}}});response=await createCheckoutHandler(productionDeps)(productionRequest);equal(response.status,200);equal(state.inputs.length,1);equal(state.networks[0]?.length,64);equal(/^[0-9a-f]{64}$/.test(state.networks[0]||""),true);equal(state.inputs[0].input.line_items[0].price,"price_og_inert");equal(state.inputs[0].input.success_url.startsWith("https://production-origin.inert/checkout/complete"),true);equal(state.inputs[0].input.cancel_url.startsWith("https://production-origin.inert/pricing"),true);

// Provider ambiguity: once createSession starts, a Session may exist and capacity must remain retryable.
reset();let reserveCalls=0,creationCalls=0;const retryDb=(await deps().privileged());
const retryDeps=deps({
 privileged:async()=>({...retryDb,reserve:async(hash,network)=>{reserveCalls++;state.hashes.push(hash);state.networks.push(network);return{reservation_id:reservation,expires_at:new Date(Date.now()+3_599_000).toISOString()}}}),
 createSession:async(input,key)=>{creationCalls++;state.inputs.push({input,key});if(creationCalls===1)throw new Error("ambiguous provider connection");return{id:"cs_retry",url:"https://checkout.stripe.com/pay/retry"}},
});
response=await createCheckoutHandler(retryDeps)(request({tierName:"early_bird"},`${PURCHASER_COOKIE}=${token}`));equal(response.status,502);equal((await response.json()).code,"CHECKOUT_PROVIDER_FAILURE");equal(state.released,0);const firstKey=state.inputs[0].key;
response=await createCheckoutHandler(retryDeps)(request({tierName:"early_bird"},`${PURCHASER_COOKIE}=${token}`));equal(response.status,200);equal(state.inputs[1].key,firstKey);equal(firstKey,`launch-checkout:${reservation}`);equal(reserveCalls,2);equal(new Set(state.hashes).size,1);equal(state.associated.length,1);equal(state.released,0);
reset();response=await createCheckoutHandler(deps({createSession:async()=>({id:"cs_invalid",url:"https://evil.invalid"})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"CHECKOUT_PROVIDER_FAILURE");equal(state.released,0);
reset();const associationDb=await deps().privileged();response=await createCheckoutHandler(deps({privileged:async()=>({...associationDb,associate:async()=>{throw new Error("association sql identity")}})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"CHECKOUT_DATABASE_FAILURE");equal(state.released,0);
reset();response=await createCheckoutHandler(deps({retrievePrice:async()=>{throw new Error("price provider payload")}}))(request({tierName:"og_throne"}));equal((await response.json()).code,"CHECKOUT_PROVIDER_FAILURE");equal(state.released,1);
reset();const referralDb=await deps().privileged();response=await createCheckoutHandler(deps({privileged:async()=>({...referralDb,referral:async()=>{throw new Error("referral sql identity")}})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"CHECKOUT_DATABASE_FAILURE");equal(state.released,1);
reset();const cleanupDb=await deps().privileged();response=await createCheckoutHandler(deps({privileged:async()=>({...cleanupDb,referral:async()=>{throw new Error("original referral")},release:async()=>{throw new Error("cleanup reservation identity")}})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"CHECKOUT_DATABASE_FAILURE");

// Cross-tier recovery validates provider state and maps post-expiration database outcomes truthfully.
const crossTierDb=async(from:"early_bird"|"og_throne",outcome:any="switched")=>{const base=await deps().privileged();return{...base,reserve:async()=>({reservation_id:reservation,expires_at:new Date(Date.now()+3_599_000).toISOString(),stripe_session_id:"cs_previous",reservation_tier:from}),switchReservation:async(...args:any[])=>{state.switched.push(args);return outcome==="switched"?{switch_outcome:"switched",reservation_id:"22222222-2222-4222-8222-222222222222",expires_at:new Date(Date.now()+3_599_000).toISOString(),reservation_tier:from==="early_bird"?"og_throne":"early_bird"}:{switch_outcome:outcome}}};};
for(const [from,to] of [["early_bird","og_throne"],["og_throne","early_bird"]] as const){for(const providerStatus of ["open","expired"]){reset();const switching=deps({retrieveSession:async id=>({id,status:providerStatus,url:null})});switching.privileged=async()=>crossTierDb(from);response=await createCheckoutHandler(switching)(request({tierName:to},`${PURCHASER_COOKIE}=${token}`));equal(response.status,200);equal(state.expired.length,providerStatus==="open"?1:0);equal(state.switched.length,1);equal(state.inputs.length,1)}}
for(const providerStatus of ["complete","unknown"]){reset();const blocked=deps({retrieveSession:async id=>({id,status:providerStatus,url:null})});blocked.privileged=async()=>crossTierDb("early_bird");response=await createCheckoutHandler(blocked)(request({tierName:"og_throne"},`${PURCHASER_COOKIE}=${token}`));equal(response.status,409);equal((await response.json()).code,"PLAN_SWITCH_UNAVAILABLE");equal(state.expired.length,0);equal(state.switched.length,0);equal(state.inputs.length,0)}
for(const [outcome,code,status] of [["closed_sold_out","SOLD_OUT",409],["closed_rate_limited","RATE_LIMITED",429],["closed_plan_unavailable","PLAN_SWITCH_RETRY",409],["closed_database_failure","PLAN_SWITCH_RETRY",409]] as const){reset();const closed=deps({retrieveSession:async id=>({id,status:"expired",url:null})});closed.privileged=async()=>crossTierDb("early_bird",outcome);response=await createCheckoutHandler(closed)(request({tierName:"og_throne"},`${PURCHASER_COOKIE}=${token}`));equal(response.status,status);equal((await response.json()).code,code);equal(state.expired.length,0);equal(state.inputs.length,0)}
reset();let recoveryAttempts=0;const recovery=deps({retrieveSession:async id=>({id,status:"expired",url:null})});const recoveryBase=await recovery.privileged();recovery.privileged=async()=>({...recoveryBase,reserve:async()=>++recoveryAttempts===1?{reservation_id:reservation,expires_at:new Date(Date.now()+3_599_000).toISOString(),stripe_session_id:"cs_previous",reservation_tier:"early_bird"}:{reservation_id:"33333333-3333-4333-8333-333333333333",expires_at:new Date(Date.now()+3_599_000).toISOString(),reservation_tier:"og_throne"},switchReservation:async()=>({switch_outcome:"closed_database_failure"} as any)});response=await createCheckoutHandler(recovery)(request({tierName:"og_throne"},`${PURCHASER_COOKIE}=${token}`));equal((await response.json()).code,"PLAN_SWITCH_RETRY");equal(state.inputs.length,0);response=await createCheckoutHandler(recovery)(request({tierName:"og_throne"},`${PURCHASER_COOKIE}=${token}`));equal(response.status,200);equal(state.inputs.length,1);equal(state.inputs[0].key,"launch-checkout:33333333-3333-4333-8333-333333333333");
reset();const databaseSwitch=deps({retrieveSession:async id=>({id,status:"expired",url:null})});const databaseSwitchDb=await crossTierDb("og_throne");databaseSwitch.privileged=async()=>({...databaseSwitchDb,switchReservation:async()=>{throw new Error("database secret")}});response=await createCheckoutHandler(databaseSwitch)(request({tierName:"early_bird"},`${PURCHASER_COOKIE}=${token}`));equal(response.status,409);equal((await response.json()).code,"PLAN_SWITCH_RETRY");equal(state.inputs.length,0);

// Complete stable failure-boundary matrix.
reset();response=await createCheckoutHandler(deps({privileged:async()=>{throw new Error("secret database detail")}}))(request({tierName:"og_throne"}));equal((await response.json()).code,"CHECKOUT_DATABASE_FAILURE");
reset();const reservationDb=await deps().privileged();response=await createCheckoutHandler(deps({privileged:async()=>({...reservationDb,reserve:async()=>{throw new Error("raw rpc failure")}})}))(request({tierName:"og_throne"}));equal((await response.json()).code,"CHECKOUT_RESERVATION_FAILURE");
reset();response=await createCheckoutHandler(deps({privileged:async()=>({...reservationDb,reserve:async()=>({reservation_id:reservation,expires_at:"invalid"})})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"CHECKOUT_RESERVATION_FAILURE");
reset();response=await createCheckoutHandler(deps({privileged:async()=>({...reservationDb,tier:async()=>{throw new Error("tier sql")}})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"CHECKOUT_DATABASE_FAILURE");
reset();response=await createCheckoutHandler(deps({privileged:async()=>({...reservationDb,reserve:async()=>{throw new Error("sold_out internal")}})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"SOLD_OUT");
for(const limit of ["rate_limit_hourly","rate_limit_daily"]){reset();response=await createCheckoutHandler(deps({privileged:async()=>({...reservationDb,reserve:async()=>{throw new Error(limit)}})}))(request({tierName:"early_bird"}));equal((await response.json()).code,"RATE_LIMITED")}
reset();response=await createCheckoutHandler(deps({privileged:async()=>({...reservationDb,reserve:async()=>({...await reservationDb.reserve(token,networkHash,"early_bird"),stripe_session_id:"cs_existing"})}),retrieveSession:async()=>{throw new Error("existing session payload")}}))(request({tierName:"early_bird"}));equal((await response.json()).code,"CHECKOUT_PROVIDER_FAILURE");equal(state.released,0);
reset();response=await createCheckoutHandler(deps({createSession:async()=>{throw new Error("provider payload secret")}}))(request({tierName:"early_bird"}));const sanitizedBody=JSON.stringify(await response.json());equal(response.status,502);equal(sanitizedBody.includes("provider payload secret"),false);equal(state.released,0);
equal(logged.every(entry=>entry[0]==="checkout_creation_failure"&&Object.keys(entry[1]).sort().join(",")==="category,stage"),true);for(const forbidden of ["secret database detail","8.8.8.8","public-project","service-role","inert-rate","ambiguous provider","association sql","referral sql","cleanup reservation","cs_existing",reservation,token,networkHash])equal(JSON.stringify(logged).includes(forbidden),false);
const routeSource=readFileSync("app/api/checkout/subscription/route.ts","utf8"),pricingSource=readFileSync("app/pricing/PricingClient.tsx","utf8");equal(routeSource.includes("user-agent"),false);equal(routeSource.includes("NEXT_PUBLIC_PAY_FIRST"),false);equal(pricingSource.includes("Too many checkout attempts. Please try again later."),true);equal(pricingSource.includes("finally"),true);equal(pricingSource.includes("/login?checkout_intent"),false);
const planSwitchMigration=readFileSync("supabase/migrations/20260730002400_safe_guest_checkout_plan_switch.sql");
equal(createHash("sha1").update(`blob ${planSwitchMigration.length}\0`).update(planSwitchMigration).digest("hex"),"d65f47c65737d7f9df164cff08c7f24659dfc833");
const schemaReloadMigration=readFileSync("supabase/migrations/20260730002500_reload_checkout_rpc_schema.sql","utf8");
equal(schemaReloadMigration.includes("notify pgrst, 'reload schema';"),true);
equal(state.networks.every(value=>value.length===64),true);equal(JSON.stringify(state.networks).includes("8.8.8.8"),false);equal(routeSource.includes("p_network_hash"),true);
console.log(`checkoutAuthenticationContract: ${assertions} assertions passed`);
console.error=originalConsoleError;
