import assert from "node:assert/strict";
import { checkoutSessionIdempotencyKey } from "../../../lib/billing/launchCheckoutPolicy";
import { ensureStripeCustomer, type CustomerBoundaries } from "../../../lib/stripe/customers";
type R={id:string;profile:string;tier:string;expires:number;status:"active"|"released"};
class Capacity { reservations:R[]=[]; entitlements=new Set<string>(); constructor(public max:number){} async acquire(profile:string,tier:string){await Promise.resolve();this.reservations=this.reservations.filter(r=>r.expires>Date.now()&&r.status==="active");const same=this.reservations.find(r=>r.profile===profile&&r.tier===tier);if(same)return same;const held=this.reservations.filter(r=>!this.entitlements.has(`${r.profile}:${r.tier}`)).length;if(this.entitlements.size+held>=this.max)throw new Error("sold_out");const r={id:`r${this.reservations.length+1}`,profile,tier,expires:Date.now()+1000,status:"active" as const};this.reservations.push(r);return r;} release(id:string){const r=this.reservations.find(x=>x.id===id);if(r)r.status="released";} }
let assertions=0;const eq=(a:any,b:any)=>{assert.equal(a,b);assertions++};
const cap=new Capacity(1);const results=await Promise.allSettled([cap.acquire("p1","og_throne"),cap.acquire("p2","og_throne")]);eq(results.filter(x=>x.status==="fulfilled").length,1);eq(results.filter(x=>x.status==="rejected").length,1);const first=await cap.acquire("p1","og_throne");eq((await cap.acquire("p1","og_throne")).id,first.id);eq(cap.reservations.length,1);cap.release(first.id);eq((await cap.acquire("p2","og_throne")).profile,"p2");cap.reservations[0].expires=0;eq((await cap.acquire("p3","og_throne")).profile,"p3");eq(checkoutSessionIdempotencyKey("abc"),"launch-checkout:abc");
let assigned:string|null=null,created=0;const boundary:CustomerBoundaries={createCustomer:async()=>({id:`cus_${++created}`}),assignIfEmpty:async(_p,_u,id)=>{if(assigned)return false;assigned=id;return true},readCustomer:async()=>assigned};
const customers=await Promise.all([ensureStripeCustomer({id:"p",userId:"u"},boundary),ensureStripeCustomer({id:"p",userId:"u"},boundary)]);eq(new Set(customers).size,1);eq(assigned,customers[0]);eq(await ensureStripeCustomer({id:"p",userId:"u",stripeCustomerId:"existing"},boundary),"existing");
const sql=(await import("node:fs")).readFileSync("supabase/migrations/20260729002100_checkout_capacity_reservations.sql","utf8");for(const token of ["for update","status='expired'","counts_toward_seats","service_role","unique index","release_checkout_capacity_reservation","associate_checkout_capacity_session"]){eq(sql.includes(token),true)}
console.log(`checkoutCapacityReservation: ${assertions} assertions passed`);
