import assert from "node:assert/strict";
import { createCheckoutHandler,type CheckoutDependencies } from "../../../app/api/checkout/subscription/route";
import { PAY_FIRST_CHECKOUT_CONTRACT,generatePurchaserToken,hashPurchaserToken,isPurchaserToken,PURCHASER_COOKIE } from "../../../lib/billing/payFirstCheckout";
import { paymentMethodTypesForLaunchPlan } from "../../../lib/billing/launchCheckoutPolicy";
let assertions=0;const equal=(a:unknown,b:unknown)=>{assert.deepEqual(a,b);assertions++};
const reservation="11111111-1111-4111-8111-111111111111",token="A".repeat(43),state={inputs:[] as any[],hashes:[] as string[],associated:[] as any[],released:0};
const deps=(planActive=true):CheckoutDependencies=>({generateToken:()=>token,configuration:()=>({priceId:"price_server",baseUrl:"https://sirens.test"}),retrievePrice:async()=>({unitAmount:10000}),createSession:async(input,key)=>{state.inputs.push({input,key});return{id:"cs_server12345678",url:"https://checkout.stripe.com/pay/server"}},retrieveSession:async id=>({id,url:"https://checkout.stripe.com/pay/server",status:"open"}),privileged:async()=>({tier:async()=>({is_active:planActive}),reserve:async(hash)=>{state.hashes.push(hash);return{reservation_id:reservation,expires_at:"2030-01-01T00:00:00Z"}},release:async()=>{state.released++},associate:async(...args)=>{state.associated.push(args)},referral:async()=>({code:"SERVER",affiliateUserId:"affiliate",commissionPercent:20,destination:"acct_server",connectOnboarded:true,payable:true})})});
const request=(body:any,cookie?:string)=>new Request("https://sirens.test/api/checkout/subscription",{method:"POST",headers:{"content-type":"application/json",...(cookie?{cookie}: {})},body:JSON.stringify(body)});
for(const tier of ["og_throne","early_bird"] as const){state.inputs=[];const response=await createCheckoutHandler(deps())(request({tierName:tier,referralCode:"server"}));equal(response.status,200);equal((await response.json()).url,"https://checkout.stripe.com/pay/server");equal(response.headers.get("set-cookie")?.includes(`${PURCHASER_COOKIE}=`),true);equal(response.headers.get("set-cookie")?.includes("HttpOnly"),true);equal(response.headers.get("set-cookie")?.includes("SameSite=lax"),true);const input=state.inputs[0].input;equal(input.mode,tier==="og_throne"?"payment":"subscription");equal(input.line_items[0].price,"price_server");equal(input.payment_method_types,tier==="og_throne"?paymentMethodTypesForLaunchPlan(tier,process.env.STRIPE_OG_BNPL_METHODS):["card"]);equal(input.metadata.checkout_contract,PAY_FIRST_CHECKOUT_CONTRACT);equal(input.metadata.profile_id,undefined);equal(input.metadata.user_id,undefined);equal(JSON.stringify(input).includes(token),false);equal(input.success_url,`https://sirens.test/checkout/complete?session_id={CHECKOUT_SESSION_ID}&reservation=${reservation}`);equal(input.cancel_url.includes(token),false);equal(state.hashes.at(-1),hashPurchaserToken(token));}
for(const tier of ["prime_access","starter_hit","standard","",null]){const r=await createCheckoutHandler(deps())(request({tier}));equal(r.status,400)}
for(const evil of [{tierName:"og_throne",priceId:"evil"},{tierName:"og_throne",mode:"subscription"},{tierName:"early_bird",destination:"acct_evil"},{tierName:"early_bird",commissionPercent:99}])equal((await createCheckoutHandler(deps())(request(evil))).status,400);
equal(isPurchaserToken(generatePurchaserToken()),true);equal(Buffer.from(generatePurchaserToken(),"base64url").length,32);equal(hashPurchaserToken(token).length,64);equal(state.hashes.includes(token),false);
state.inputs=[];await createCheckoutHandler(deps())(request({tierName:"og_throne"},`${PURCHASER_COOKIE}=${token}`));equal(state.hashes.at(-1),hashPurchaserToken(token));equal(state.inputs[0].key,`launch-checkout:${reservation}`);
state.inputs=[];const early=deps();const db=await early.privileged();early.privileged=async()=>({...db,referral:async()=>({code:null,affiliateUserId:null,commissionPercent:0,destination:null,connectOnboarded:false,payable:false})});await createCheckoutHandler(early)(request({tierName:"early_bird"}));equal(state.inputs[0].input.subscription_data.transfer_data,undefined);equal(state.inputs[0].input.subscription_data.application_fee_percent,undefined);
console.log(`checkoutAuthenticationContract: ${assertions} assertions passed`);
