import assert from "node:assert/strict";
import { createCheckoutHandler, type CheckoutDependencies } from "../../../app/api/checkout/subscription/route";
let assertions=0; const eq=(a:any,b:any)=>{assert.equal(a,b);assertions++};
const request=(body:any)=>new Request("https://sirens.test/api/checkout/subscription",{method:"POST",body:JSON.stringify(body)});
function deps(overrides:Partial<CheckoutDependencies>={}):CheckoutDependencies { return { authenticate:async()=>({id:"u1",email:"a@b.test"}), privileged:async()=>({profiles:async()=>[{id:"p1",user_id:"u1"}],tier:async()=>({is_active:true}),entitlements:async()=>[],reserve:async()=>({reservation_id:"r1",expires_at:"later"}),release:async()=>{},associate:async()=>{},referral:async()=>({code:null,affiliateUserId:null,commissionPercent:0,destination:null})}),configuration:()=>({priceId:"price_server",baseUrl:"https://sirens.test"}),customer:async()=>"cus_server",createSession:async(input)=>({id:"cs1",url:"https://checkout.stripe.com/test"}),...overrides}; }
let privileged=0, stripe=0; let res=await createCheckoutHandler(deps({authenticate:async()=>null,privileged:async()=>{privileged++;throw 0},createSession:async()=>{stripe++;throw 0}}))(request({tier:"og_throne"}));eq(res.status,401);eq(privileged,0);eq(stripe,0);
for(const tier of ["prime_access","Standard","Starter Hit","unknown"]){res=await createCheckoutHandler(deps())(request({tierName:tier,profileId:"evil",priceId:"evil",mode:"evil"}));eq(res.status,400)}
res=await createCheckoutHandler(deps({privileged:async()=>({...await deps().privileged(),profiles:async()=>[]})}))(request({tierName:"og_throne"}));eq(res.status,403);
res=await createCheckoutHandler(deps({privileged:async()=>({...await deps().privileged(),profiles:async()=>[{id:"p1",user_id:"u1"},{id:"p2",user_id:"u1"}]})}))(request({tierName:"og_throne"}));eq(res.status,403);
res=await createCheckoutHandler(deps({privileged:async()=>({...await deps().privileged(),tier:async()=>({is_active:false})})}))(request({tierName:"og_throne"}));eq(res.status,409);
res=await createCheckoutHandler(deps({privileged:async()=>({...await deps().privileged(),entitlements:async()=>[{status:"active",tier_name:"early_bird"}]})}))(request({tierName:"og_throne"}));eq(res.status,409);
let captured:any; res=await createCheckoutHandler(deps({createSession:async(i)=>{captured=i;return{id:"cs",url:"https://checkout.stripe.com/x"}}}))(request({tierName:"og_throne",userId:"evil",customer:"evil",priceId:"evil",commissionPercent:99}));eq(res.status,200);eq(captured.customer,"cus_server");eq(captured.line_items[0].price,"price_server");eq(captured.mode,"payment");checkUrl(captured.success_url,"checkout=success");checkUrl(captured.cancel_url,"checkout=canceled");eq(captured.metadata.commission_percent,"0");
for(const boundary of ["configuration","createSession"] as const){const bad:any=boundary==="configuration"?()=>({priceId:"",baseUrl:""}):async()=>{throw new Error("secret SQL env")};res=await createCheckoutHandler(deps({[boundary]:bad}))(request({tierName:"early_bird"}));const text=await res.text();eq(text.includes("secret"),false)}
function checkUrl(v:string,s:string){eq(v.includes(s),true)}
console.log(`checkoutAuthenticationContract: ${assertions} assertions passed`);
