import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{createHash}from"node:crypto";import{processPayFirstStripeEvent,type PayFirstWebhookDependencies}from"../../../app/api/webhook/route";import{createClaimHandler,type ClaimDependencies}from"../../../app/api/checkout/claim/route";import{PAY_FIRST_CHECKOUT_CONTRACT,PURCHASER_COOKIE,hashPurchaserToken}from"../../../lib/billing/payFirstCheckout";
let assertions=0;const equal=(a:unknown,b:unknown)=>{assert.deepEqual(a,b);assertions++};const reservation="11111111-1111-4111-8111-111111111111",token="A".repeat(43),hash=hashPurchaserToken(token),sessionId="cs_1234567890";
const metadata=(tier:"og_throne"|"early_bird")=>({checkout_contract:PAY_FIRST_CHECKOUT_CONTRACT,reservation_id:reservation,tier_name:tier,stripe_price_id:tier==="og_throne"?"price_og":"price_early",purchase_mode:tier==="og_throne"?"payment":"subscription",connect_mode:"none",connect_destination_account:"",connect_onboarded:"false",platform_fee_percent:"100",commission_percent:"0"});let calls:any[]=[];
const webhook:PayFirstWebhookDependencies={ogPriceId:"price_og",earlyPriceId:"price_early",paymentIntent:async id=>({id,status:"succeeded",customer:"cus_1",amount:1000,application_fee_amount:null,metadata:metadata("og_throne")}),subscription:async id=>({id,status:"active",customer:"cus_1",items:{data:[{price:{id:"price_early"}}]},latest_invoice:{paid:true,status:"paid"},application_fee_percent:null,transfer_data:null,metadata:metadata("early_bird")}),record:async i=>calls.push(["record",i]),expire:async i=>calls.push(["expire",i])};
const event=(tier:"og_throne"|"early_bird",change:any={})=>({type:"checkout.session.completed",data:{object:{id:sessionId,status:"complete",payment_status:"paid",mode:tier==="og_throne"?"payment":"subscription",customer:"cus_1",payment_intent:tier==="og_throne"?"pi_1":null,subscription:tier==="early_bird"?"sub_1":null,metadata:metadata(tier),...change}}});
for(const tier of ["og_throne","early_bird"]as const){calls=[];equal(await processPayFirstStripeEvent(event(tier),webhook),"recorded");equal(calls.length,1);equal(calls[0][1].paymentIntentId,tier==="og_throne"?"pi_1":null);equal(calls[0][1].subscriptionId,tier==="early_bird"?"sub_1":null)}
for(const change of [{payment_status:"unpaid"},{status:"expired"},{customer:""},{mode:"setup"},{metadata:{...metadata("og_throne"),stripe_price_id:"wrong"}}]){calls=[];equal(await processPayFirstStripeEvent(event("og_throne",change),webhook),"ignored");equal(calls.length,0)}
calls=[];equal(await processPayFirstStripeEvent({type:"checkout.session.expired",data:{object:{id:sessionId,metadata:metadata("og_throne")}}},webhook),"expired");equal(calls[0][0],"expire");
const purchase:any={reservation_id:reservation,purchaser_token_hash:`\\x${hash}`,tier:"og_throne",stripe_session_id:sessionId,stripe_customer_id:"cus_1",stripe_price_id:"price_og",payment_intent_id:"pi_1",stripe_subscription_id:null,state:"paid_unclaimed",claimed_profile_id:null};let claimed=0;
const claimDeps=(authenticated=true):ClaimDependencies=>({authenticate:async()=>authenticated?{id:"user_1"}:null,profiles:async()=>[{id:"profile_1",user_id:"user_1"}],purchase:async()=>purchase,session:async()=>({id:sessionId,status:"complete",payment_status:"paid",mode:"payment",customer:"cus_1",payment_intent:"pi_1",metadata:metadata("og_throne")}),subscription:async()=>({}),claim:async()=>{claimed++;return"claimed"}});
const req=(method="POST",cookie=`${PURCHASER_COOKIE}=${token}`)=>new Request(`https://sirens.test/api/checkout/claim?session_id=${sessionId}&reservation=${reservation}`,{method,headers:{cookie}});
equal((await createClaimHandler(claimDeps(false))(req("GET"))).status,401);equal((await createClaimHandler(claimDeps())(req())).status,200);equal(claimed,1);equal((await createClaimHandler(claimDeps())(req("POST",""))).status,403);
const wrong=claimDeps();wrong.purchase=async()=>({...purchase,purchaser_token_hash:"\\x"+"0".repeat(64)});equal((await createClaimHandler(wrong)(req())).status,404);
const migration=readFileSync("supabase/migrations/20260729002200_pay_first_checkout_claims.sql","utf8"),old=readFileSync("supabase/migrations/20260729002100_checkout_capacity_reservations.sql");equal(createHash("sha1").update(`blob ${old.length}\0`).update(old).digest("hex"),"33e05a52b1974fc1257dd0484980ed79dcca5837");equal((migration.match(/security definer/g)||[]).length,5);equal((migration.match(/search_path = public, pg_temp/g)||[]).length,5);for(const role of["public","anon","authenticated"])equal(migration.includes(`from public,anon,authenticated`),true);equal(migration.includes("grant select,insert,update on public.pay_first_purchases to service_role"),true);equal(migration.includes("enable row level security"),true);equal(migration.includes("purchaser_token_hash bytea"),true);equal(migration.includes("for update"),true);
console.log(`payFirstCheckoutClaim: ${assertions} assertions passed`);
