import "server-only";
import { CopyObjectCommand, DeleteObjectCommand, GetObjectCommand, HeadObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { createHash, randomUUID } from "node:crypto";
import { detectImageMime, MAX_PRIVATE_CREATOR_MEDIA_BYTES } from "@/lib/private-creator-media/core";
const supported=new Set(["image/jpeg","image/png","image/webp"]); export const VIDEO_SOURCE_UPLOAD_TTL_SECONDS=300;
function config(env:NodeJS.ProcessEnv=process.env){const endpoint=env.R2_ENDPOINT?.trim(),bucket=env.CREATOR_GENERATION_R2_BUCKET?.trim(),accessKeyId=env.CREATOR_GENERATION_R2_UPLOAD_ACCESS_KEY_ID?.trim(),secretAccessKey=env.CREATOR_GENERATION_R2_UPLOAD_SECRET_ACCESS_KEY?.trim();if(!endpoint||!bucket||!accessKeyId||!secretAccessKey)throw new Error("VIDEO_SOURCE_UPLOAD_NOT_CONFIGURED");return{endpoint,bucket,accessKeyId,secretAccessKey,region:env.R2_REGION||"auto"};}
const r2=(c:ReturnType<typeof config>)=>new S3Client({region:c.region,endpoint:c.endpoint,credentials:{accessKeyId:c.accessKeyId,secretAccessKey:c.secretAccessKey}});
export function isVideoSourceUploadReady(){try{config();return true}catch{return false}}
export function validateSourceMetadata(mime:string,size:number){if(!supported.has(mime)||!Number.isSafeInteger(size)||size<1||size>MAX_PRIVATE_CREATOR_MEDIA_BYTES)throw new Error("INVALID_VIDEO_SOURCE_UPLOAD");}
export async function signStagingUpload(input:{ownerId:string;mime:string;size:number}){validateSourceMetadata(input.mime,input.size);const c=config(),uploadId=randomUUID(),ext=input.mime==="image/png"?"png":input.mime==="image/webp"?"webp":"jpg",stagingKey=`creator-video-source-staging/${input.ownerId}/${uploadId}.${ext}`,finalKey=`creator-video-sources/${input.ownerId}/${uploadId}/source.${ext}`;const uploadUrl=await getSignedUrl(r2(c),new PutObjectCommand({Bucket:c.bucket,Key:stagingKey,ContentType:input.mime,ContentLength:input.size}),{expiresIn:VIDEO_SOURCE_UPLOAD_TTL_SECONDS});return{uploadId,uploadUrl,bucket:c.bucket,stagingKey,finalKey};}
async function readVerified(c:ReturnType<typeof config>,key:string,expectedMime:string,expectedSize:number){const result=await r2(c).send(new GetObjectCommand({Bucket:c.bucket,Key:key}));if(!result.Body)throw new Error("VIDEO_SOURCE_UPLOAD_MISSING");const hash=createHash("sha256"),head:Buffer[]=[];let bytes=0;for await(const raw of result.Body as AsyncIterable<Uint8Array>){const chunk=Buffer.from(raw);bytes+=chunk.length;if(bytes>MAX_PRIVATE_CREATOR_MEDIA_BYTES)throw new Error("INVALID_VIDEO_SOURCE_UPLOAD");hash.update(chunk);if(Buffer.concat(head).length<32)head.push(chunk.subarray(0,32-Buffer.concat(head).length));}const mime=detectImageMime(Buffer.concat(head));if(bytes!==expectedSize||mime!==expectedMime)throw new Error("INVALID_VIDEO_SOURCE_UPLOAD");return{mimeType:mime,sizeBytes:bytes,sha256:hash.digest("hex")};}
export async function promoteSource(input:{stagingKey:string;finalKey:string;mime:string;size:number}){const c=config();const first=await readVerified(c,input.stagingKey,input.mime,input.size);await r2(c).send(new CopyObjectCommand({Bucket:c.bucket,Key:input.finalKey,CopySource:`${c.bucket}/${encodeURIComponent(input.stagingKey).replaceAll("%2F","/")}`,ContentType:input.mime,MetadataDirective:"REPLACE"}));await r2(c).send(new HeadObjectCommand({Bucket:c.bucket,Key:input.finalKey}));const final=await readVerified(c,input.finalKey,input.mime,input.size);if(final.sha256!==first.sha256)throw new Error("VIDEO_SOURCE_PROMOTION_MISMATCH");return{bucket:c.bucket,objectKey:input.finalKey,...final,cleanup:()=>r2(c).send(new DeleteObjectCommand({Bucket:c.bucket,Key:input.stagingKey}))};}
