import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { paymentFirstWebhook, type PaymentV2Database, type PaymentV2Provider, type StripeEvent, type StripeSubscription } from "../../../lib/payment-v2/webhookService";
import { paymentFirstClaim, type ClaimDatabase, type ClaimInput } from "../../../lib/payment-v2/claimService";
import type { InboxStatus, PaymentV2InboxDatabase } from "../../../lib/payment-v2/eventInboxService";

let assertions=0;const equal=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);assertions++};const check=(a:unknown,m:string)=>{assert.ok(a,m);assertions++};
const hold="10000000-0000-4000-8000-000000000001";
const subscription=(status:string="active"):StripeSubscription=>({id:"sub_early",customer:"cus_early",status,current_period_start:1785542400,current_period_end:1788220800,cancel_at_period_end:true,canceled_at:null,trial_start:null,trial_end:null,items:{data:[{quantity:1,price:{id:"price_early"}}]},metadata:{checkout_contract_version:"pfc-03-v2",payment_v2_hold_id:hold,tier_name:"early_bird"}});

type LifecycleOptions={eventType?:string;state?:InboxStatus;current?:StripeSubscription;result?:string;dbError?:string;providerFailure?:boolean;invoiceCustomer?:unknown;invoiceMetadata?:Record<string,string>|null;invoiceStatus?:string;invoiceAmountDue?:number;invoiceAmountPaid?:number;invoicePaidAt?:number};
function lifecycle(options:LifecycleOptions={}){
  let state:InboxStatus=options.state||"RECEIVED", result=options.result||"applied", providerFailure=options.providerFailure||false;
  const current=options.current||subscription(),eventType=options.eventType||"customer.subscription.updated";
  const calls={apply:[] as Record<string,unknown>[],failures:[] as Record<string,unknown>[],recoveries:[] as Record<string,unknown>[],subscription:0,invoice:0,transitions:[] as string[]};
  const event:StripeEvent={id:"evt_lifecycle",type:eventType,created:1785542400,data:{object:{id:eventType==="invoice.payment_failed"?"in_failed":"sub_early"}}};
  const provider:PaymentV2Provider={constructEvent:()=>event,retrieveSession:async()=>{throw new Error()},retrievePaymentIntent:async()=>{throw new Error()},async retrieveSubscription(){calls.subscription++;if(providerFailure)throw new Error("transient provider failure");return current},async retrieveInvoice(){calls.invoice++;return{id:"in_failed",status:options.invoiceStatus??"open",amount_due:options.invoiceAmountDue??1000,amount_paid:options.invoiceAmountPaid??0,status_transitions:{paid_at:options.invoicePaidAt??null},customer:options.invoiceCustomer===undefined?"cus_early":options.invoiceCustomer,billing_reason:"subscription_cycle",lines:{data:[{quantity:1,pricing:{type:"price_details",price_details:{price:"price_early"}},period:{start:1785542400,end:1788220800}}]},parent:{type:"subscription_details",subscription_details:{subscription:"sub_early",metadata:options.invoiceMetadata===undefined?current.metadata:options.invoiceMetadata}}}}};
  const db:PaymentV2Database={loadHold:async()=>[],loadTier:async()=>[],loadPurchase:async()=>[],recordPaid:async()=>"",recordTerminal:async()=>"",async applyEarlyBirdLifecycle(args){calls.apply.push(args);if(options.dbError)throw new Error(options.dbError);return result},async recordSubscriptionPaymentFailure(args){calls.failures.push(args);return"first_miss_frozen"},async recoverSubscriptionPaymentDelinquency(args){calls.recoveries.push(args);return"no_open_delinquency"}};
  const allowed:Record<InboxStatus,InboxStatus[]>={RECEIVED:["PENDING_PHASE","PENDING_PURCHASE","PENDING_RETRY","PROCESSED","IGNORED_NON_V2","FAILED_TERMINAL"],PENDING_PHASE:["PENDING_PURCHASE","PENDING_RETRY","PROCESSED","IGNORED_NON_V2","FAILED_TERMINAL"],PENDING_PURCHASE:["PENDING_PURCHASE","PROCESSED","IGNORED_NON_V2","FAILED_TERMINAL"],PENDING_RETRY:["PENDING_RETRY","PROCESSED","IGNORED_NON_V2","FAILED_TERMINAL"],PROCESSED:[],IGNORED_NON_V2:[],FAILED_TERMINAL:[]};
  const inbox:PaymentV2InboxDatabase={receiveEvent:async()=>state,async transitionStatus(args){check(allowed[state].includes(args.p_new_status),`real inbox contract allows ${state}->${args.p_new_status}`);equal(args.p_expected_status,state,"transition expects durable state");state=args.p_new_status;calls.transitions.push(`${args.p_expected_status}->${args.p_new_status}`);return state}};
  return{calls,setResult(v:string){result=v},setProviderFailure(v:boolean){providerFailure=v},get state(){return state},async run(){return paymentFirstWebhook({enabled:"true",inboxEnabled:"true",apiKey:"sk_test",webhookSecret:"whsec_test",signature:"sig",readRawBody:async()=>Buffer.from("signed"),createProvider:()=>provider,createDatabase:()=>db,createInboxDatabase:()=>inbox})}};
}

for(const status of ["active","trialing","past_due","canceled","unpaid","paused","incomplete","incomplete_expired"]){const h=lifecycle({current:subscription(status)});await h.run();equal(h.state,"PROCESSED",`${status} processed`);equal(h.calls.apply[0].p_status,status,`${status} authoritative snapshot applied`);equal(h.calls.apply[0].p_hold_id,hold,`${status} binds authoritative hold`);equal(h.calls.apply[0].p_price_id,"price_early",`${status} binds authoritative price`);}
{const h=lifecycle({eventType:"customer.subscription.deleted",current:subscription("active")});await h.run();equal(h.calls.apply[0].p_status,"active","deleted event cannot override current active truth");equal(h.calls.subscription,1,"current subscription retrieved");}
{const h=lifecycle({eventType:"invoice.payment_failed",current:subscription("past_due")});await h.run();equal(h.calls.invoice,1,"failed invoice retrieved");equal(h.calls.subscription,1,"invoice subscription retrieved");equal(h.state,"PROCESSED","failed invoice processed");}
{const h=lifecycle({eventType:"invoice.payment_failed",current:subscription("past_due")});await h.run();equal(h.calls.failures.length,1,"failed recurring invoice reaches additive delinquency RPC");equal(h.calls.failures[0].p_invoice_id,"in_failed","authoritative invoice identity is forwarded");}
for(const status of ["active","trialing","canceled"]){const h=lifecycle({eventType:"invoice.payment_failed",current:subscription(status)});await h.run();equal(h.state,"PROCESSED",`stale failure with current ${status} is safe`);equal(h.calls.failures.length,0,`stale failure with current ${status} cannot create delinquency`);}
for(const invoiceStatus of ["paid","void"]){const h=lifecycle({eventType:"invoice.payment_failed",current:subscription("past_due"),invoiceStatus});await h.run();equal(h.state,"PROCESSED",`currently ${invoiceStatus} invoice is safe`);equal(h.calls.failures.length,0,`currently ${invoiceStatus} invoice cannot create delinquency`);}
{const h=lifecycle({eventType:"invoice.payment_failed",current:subscription("past_due"),invoiceAmountPaid:1000});await h.run();equal(h.state,"PROCESSED","satisfied invoice failure is safe");equal(h.calls.failures.length,0,"satisfied invoice cannot create delinquency");}
{const paidAt=1786000000,h=lifecycle({eventType:"invoice.payment_failed",current:subscription("active"),invoiceStatus:"paid",invoiceAmountPaid:1000,invoicePaidAt:paidAt});await h.run();equal(h.calls.recoveries.length,1,"stale failed delivery may use authoritative paid recovery");equal(h.calls.recoveries[0].p_recovered_at,new Date(paidAt*1000).toISOString(),"recovery uses invoice paid_at, not historical failed-event time");}
{const h=lifecycle({current:{...subscription(),metadata:{}}});await h.run();equal(h.state,"IGNORED_NON_V2","legacy subscription ignored");equal(h.calls.apply.length,0,"legacy subscription not mutated");}
for(const eventType of ["refund.created","charge.dispute.created"]){const h=lifecycle({eventType});const r=await h.run();equal(h.state,"PENDING_PHASE",`${eventType} remains dormant`);equal(r.status,200,`${eventType} retains 2xx dormant response`);equal(h.calls.apply.length,0,`${eventType} does not apply lifecycle`);}

{const h=lifecycle({result:"purchase_pending"});let r=await h.run();equal(h.state,"PENDING_PURCHASE","initial purchase race persists");equal(r.status,503,"initial purchase race retries");equal(r.body.code,"PAYMENT_V2_EVENT_PENDING_PURCHASE_RETRY","purchase retry code stable");r=await h.run();equal(h.state,"PENDING_PURCHASE","purchase-pending replay sticks");equal(r.status,503,"purchase-pending replay retries");h.setProviderFailure(true);r=await h.run();equal(h.state,"PENDING_PURCHASE","transient failure sticks to purchase pending");equal(r.status,503,"sticky purchase pending retries");check(!h.calls.transitions.includes("PENDING_PURCHASE->PENDING_RETRY"),"no purchase-to-retry cross transition");h.setProviderFailure(false);h.setResult("applied");r=await h.run();equal(h.state,"PROCESSED","purchase-pending replay recovers");equal(r.status,200,"purchase-pending recovery is 2xx");}
{const h=lifecycle({providerFailure:true});let r=await h.run();equal(h.state,"PENDING_RETRY","initial transient failure persists");equal(r.status,503,"initial transient failure retries");equal(r.body.code,"PAYMENT_V2_EVENT_PENDING_RETRY","transient retry code stable");r=await h.run();equal(h.state,"PENDING_RETRY","transient replay sticks");equal(r.status,503,"transient replay retries");h.setProviderFailure(false);h.setResult("purchase_pending");r=await h.run();equal(h.state,"PENDING_RETRY","missing purchase sticks to pending retry");equal(r.status,503,"sticky pending retry retries");check(!h.calls.transitions.includes("PENDING_RETRY->PENDING_PURCHASE"),"no retry-to-purchase cross transition");h.setResult("applied");r=await h.run();equal(h.state,"PROCESSED","pending-retry replay recovers");equal(r.status,200,"pending-retry recovery is 2xx");}
for(const terminal of ["PROCESSED","IGNORED_NON_V2","FAILED_TERMINAL"] as InboxStatus[]){const h=lifecycle({state:terminal});const r=await h.run();equal(r.status,200,`${terminal} replay is 2xx`);equal(h.calls.apply.length,0,`${terminal} replay does not mutate`);equal(h.state,terminal,`${terminal} remains terminal`);}
{const h=lifecycle({eventType:"invoice.payment_failed",invoiceCustomer:null});await h.run();equal(h.state,"FAILED_TERMINAL","missing invoice customer fails terminal");equal(h.calls.apply.length,0,"missing invoice customer does not call RPC");}
{const h=lifecycle({eventType:"invoice.payment_failed",invoiceCustomer:"cus_wrong"});await h.run();equal(h.state,"FAILED_TERMINAL","wrong invoice customer fails terminal");equal(h.calls.apply.length,0,"wrong invoice customer does not call RPC");}
{const h=lifecycle({eventType:"invoice.payment_failed",invoiceMetadata:{checkout_contract_version:"pfc-03-v2",payment_v2_hold_id:"bad",tier_name:"early_bird"}});await h.run();equal(h.state,"FAILED_TERMINAL","malformed V2 invoice metadata fails terminal");equal(h.calls.apply.length,0,"malformed V2 invoice metadata does not call RPC");}
{const h=lifecycle({eventType:"invoice.payment_failed",invoiceMetadata:{checkout_contract_version:"pfc-03-v2",payment_v2_hold_id:"10000000-0000-4000-8000-000000000099",tier_name:"early_bird"}});await h.run();equal(h.state,"FAILED_TERMINAL","invoice hold mismatch fails terminal");equal(h.calls.apply.length,0,"invoice hold mismatch does not call RPC");}
{const h=lifecycle({current:{...subscription(),metadata:{...subscription().metadata,payment_v2_hold_id:"10000000-0000-4000-8000-000000000099"}},dbError:"subscription_hold_mismatch"});await h.run();equal(h.state,"FAILED_TERMINAL","subscription metadata hold mismatch fails closed");equal(h.calls.apply.length,1,"authoritative mismatched hold reaches exact RPC boundary once");}
{const h=lifecycle({dbError:"subscription_price_mismatch"});await h.run();equal(h.state,"FAILED_TERMINAL","subscription price mismatch fails closed");equal(h.calls.apply.length,1,"wrong current price reaches exact RPC boundary once");}
for(const [label,items] of [["multiple items",[{quantity:1,price:{id:"price_early"}},{quantity:1,price:{id:"price_other"}}]],["wrong quantity",[{quantity:2,price:{id:"price_early"}}]],["missing price",[{quantity:1,price:{}}]]] as const){const h=lifecycle({current:{...subscription(),items:{data:[...items]}}});await h.run();equal(h.state,"FAILED_TERMINAL",`${label} fails terminal`);equal(h.calls.apply.length,0,`${label} never calls lifecycle RPC`);}

const raw=Buffer.alloc(32,7),cookie=raw.toString("base64url"),digest=createHash("sha256").update(raw).digest();
function claimHarness(tier:"early_bird"|"og_throne",status="active",providerFailure=false,current=subscription(status)){let rpc=0,retrieves=0;const sid="cs_test_lock05e",profile="30000000-0000-4000-8000-000000000001",user="40000000-0000-4000-8000-000000000001",purchase="50000000-0000-4000-8000-000000000001";const db:ClaimDatabase={loadHolds:async()=>[{id:hold,purchaser_credential_hash:digest,tier,state:"PAID_UNCLAIMED",stripe_checkout_session_id:sid}],loadPurchases:async()=>[{id:purchase,hold_id:hold,purchaser_credential_hash:digest,tier,state:"PAID_UNCLAIMED",stripe_checkout_session_id:sid,stripe_subscription_id:tier==="early_bird"?"sub_early":null,stripe_customer_id:"cus_early",stripe_price_id:tier==="early_bird"?"price_early":"price_og",claimed_profile_id:null}],loadProfiles:async()=>[{id:profile,user_id:user}],loadAllocations:async()=>[],loadEntitlements:async()=>[],async claim(){rpc++;return"claimed"}};const input:ClaimInput={enabled:"true",production:true,configuredOrigin:"https://sirensforge.test",readOrigin:()=>"https://sirensforge.test",readSessionId:()=>sid,readCookie:()=>cookie,getAuthenticatedUser:async()=>user,createDatabase:()=>db,async retrieveSubscription(){retrieves++;if(providerFailure)throw new Error("temporary");return current}};return{input,get rpc(){return rpc},get retrieves(){return retrieves}}}
for(const status of ["past_due","canceled","unpaid","paused","incomplete","incomplete_expired"]){const h=claimHarness("early_bird",status);const r=await paymentFirstClaim(h.input);equal(r.body.code,"PAYMENT_V2_SUBSCRIPTION_NOT_ACTIVE",`${status} claim rejected stably`);equal(h.rpc,0,`${status} never calls claim RPC`)}
for(const status of ["active","trialing"]){const h=claimHarness("early_bird",status);await paymentFirstClaim(h.input);equal(h.rpc,1,`${status} reaches existing claim RPC`)}
for(const [label,current] of [["wrong price",{...subscription(),items:{data:[{quantity:1,price:{id:"price_wrong"}}]}}],["multiple items",{...subscription(),items:{data:[{quantity:1,price:{id:"price_early"}},{quantity:1,price:{id:"price_other"}}]}}],["wrong quantity",{...subscription(),items:{data:[{quantity:2,price:{id:"price_early"}}]}}],["missing price",{...subscription(),items:{data:[{quantity:1,price:{}}]}}]] as const){const h=claimHarness("early_bird","active",false,current);equal((await paymentFirstClaim(h.input)).status,500,`${label} claim fails closed`);equal(h.rpc,0,`${label} never calls claim RPC`);}
{const h=claimHarness("early_bird","active",true);equal((await paymentFirstClaim(h.input)).body.code,"PAYMENT_V2_SUBSCRIPTION_VERIFICATION_UNAVAILABLE","provider failure stable");equal(h.rpc,0,"provider failure never claims");}
{const h=claimHarness("og_throne");await paymentFirstClaim(h.input);equal(h.retrieves,0,"OG claim performs no subscription lookup");}

const baseline="eff1aa6e96c21dfd2b17f59b292476da164f0073";
// Durable mainline baseline: the merge commit for approved material-policy PR #273.
// Keep the authorized MFA plus Phase 7 stale recurring-expiry hardening exact while
// continuing to reject any future drift in the protected Payment V2 surface.
const postPr273Baseline="15e0ce3e3e7be77fa6847aa3544a06b446773c5b";
const protectedSurfaceBaselines:Record<string,string>={
  "app/api/checkout/subscription-v2/route.ts":postPr273Baseline,
  "lib/payment-v2/checkoutService.ts":postPr273Baseline,
  "lib/payment-v2/checkoutRequestProtection.ts":baseline,
};
for(const [path,pathBaseline] of Object.entries(protectedSurfaceBaselines)){execFileSync("git",["diff","--quiet",pathBaseline,"--",path]);assertions++;}
const approvedMfaSubscriptionCheckerDiff=execFileSync("git",["diff",postPr273Baseline,"--","lib/subscription-checker.ts"],{encoding:"utf8"});
equal(createHash("sha256").update(approvedMfaSubscriptionCheckerDiff).digest("hex"),"adeeba53bd1e712411aea7d2d27c706527bb4a4504ce4b285379788425466877","subscription checker differs from PR #273 only by approved MFA, Phase 7 recurring-expiry, and delinquency gates");
const historicalMigrationMutations=(statusLines:string[])=>statusLines.filter(line=>line.length>0&&!line.startsWith("A\t"));
const migrationChanges=execFileSync("git",["diff","--name-status",baseline,"--","supabase/migrations"],{encoding:"utf8"}).trim().split(/\r?\n/).filter(Boolean);
equal(historicalMigrationMutations(migrationChanges),[],"historical migrations remain immutable while later forward-only additions are allowed");
equal(historicalMigrationMutations(["A\tsupabase/migrations/20990101000000_future_forward_only.sql"]),[],"new forward-only migration is allowed");
equal(historicalMigrationMutations(["M\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql"]),["M\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql"],"modified historical migration is rejected");
equal(historicalMigrationMutations(["D\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql"]),["D\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql"],"deleted historical migration is rejected");
equal(historicalMigrationMutations(["R100\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql\tsupabase/migrations/20990101000000_replacement.sql"]),["R100\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql\tsupabase/migrations/20990101000000_replacement.sql"],"renamed historical migration is rejected");
equal(historicalMigrationMutations(["T\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql"]),["T\tsupabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql"],"historical migration type change is rejected");
execFileSync("git",["diff","--quiet","e47e641048b48ed858b9fe21af7c0169fe0575c2","--","supabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql"]);assertions++;
const migration=await import("node:fs").then(({readFileSync})=>readFileSync("supabase/migrations/20260812080000_lock05e_payment_v2_early_bird_subscription_lifecycle.sql","utf8"));
const inboxSource=await import("node:fs").then(({readFileSync})=>readFileSync("lib/payment-v2/eventInboxService.ts","utf8"));
const receiveArgs=["p_provider_event_id","p_provider_event_type","p_provider_object_id","p_provider_object_type","p_provider_created_at","p_raw_payload_sha256","p_lifecycle_phase","p_lifecycle_version"];
const transitionArgs=["p_provider_event_id","p_expected_status","p_new_status","p_error_code","p_count_attempt"];
for(const name of receiveArgs){check(new RegExp(`\\b${name}\\s*:`).test(inboxSource),`receive TypeScript contract includes ${name}`);check(migration.includes(`'${name}'`),`SQL postcondition includes receive argument ${name}`);}
for(const name of transitionArgs){check(new RegExp(`\\b${name}\\s*:`).test(inboxSource),`transition TypeScript contract includes ${name}`);check(migration.includes(`'${name}'`),`SQL postcondition includes transition argument ${name}`);}
check(/^begin;/m.test(migration)&&/commit;\s*$/.test(migration),"forward migration is transaction wrapped");
check(migration.includes("pg_catalog.pg_notify('pgrst', 'reload schema')"),"forward migration notifies PostgREST schema reload");
const rollback=await import("node:fs").then(({readFileSync})=>readFileSync("supabase/manual/lock05e_payment_v2_subscription_lifecycle_rollback.sql","utf8"));check(rollback.includes("pg_catalog.pg_notify('pgrst','reload schema')"),"rollback notifies PostgREST schema reload");
for(const name of ["payment_v2_record_paid","payment_v2_record_paid_with_charge","payment_v2_claim","payment_v2_associate_session","payment_v2_record_session_unpaid_terminal","payment_v2_expire_unpaid","payment_v2_reconcile_paid_invoices"]){check(!new RegExp(`create\\s+(?:or\\s+replace\\s+)?function\\s+public\\.${name}\\b`,"i").test(migration),`migration does not rewrite ${name}`);}
check(!/alter\s+table\s+public\.payment_v2_reconciliation_evidence|(?:create|drop)\s+(?:unique\s+)?index[^;]*payment_v2_(?:reconciliation_)?evidence/i.test(migration),"migration does not alter evidence contracts");
for(const path of ["backend/affiliate"]){execFileSync("git",["diff","--quiet",baseline,"--",path]);assertions++;}
check(true,"no live provider used");console.log(`LOCK-05E lifecycle tests passed (${assertions} assertions; no external network calls)`);
