\set ON_ERROR_STOP on
DO $$
DECLARE h uuid;p uuid;e uuid;r text;d text;
BEGIN
 select hold_id into h from public.payment_v2_acquire_hold(extensions.digest('phase12-og','sha256'),'og_throne',now()+interval '1 hour','PHASE12');
 perform public.payment_v2_associate_session(h,extensions.digest('phase12-og','sha256'),'cs_phase12_og');
 perform public.payment_v2_record_paid_with_charge(h,extensions.digest('phase12-og','sha256'),'cs_phase12_og','cus_phase12','price_og','pi_phase12',null,'evt_paid_phase12',now(),10000,'usd','pi_phase12','ch_phase12',null);
 select id into p from public.payment_v2_purchases where hold_id=h;
 perform public.payment_v2_apply_refund('re_pending1','ch_phase12','pi_phase12',1000,'usd','pending',null,null,now(),'evt_re_pending1',now());
 if (select state from public.payment_v2_purchases where id=p)<>'PAID_UNCLAIMED' then raise exception 'pending_mutated';end if;
 perform public.payment_v2_apply_refund('re_partial1','ch_phase12','pi_phase12',4000,'usd','succeeded',null,null,now(),'evt_re_partial1',now()+interval '1 second');
 if not public.payment_v2_source_charge_blocks_affiliate_payout('ch_phase12') or not exists(select 1 from public.payment_v2_financial_reviews where review_reason='PARTIAL_REFUND'and state='OPEN')then raise exception 'partial_not_blocked';end if;
 perform public.payment_v2_apply_refund('re_full1','ch_phase12','pi_phase12',6000,'usd','succeeded',null,null,now(),'evt_re_full1',now()+interval '2 seconds');
 if (select state from public.payment_v2_purchases where id=p)<>'REFUNDED'or(select state from public.payment_v2_holds where id=h)<>'REFUNDED'or exists(select 1 from public.payment_v2_financial_reviews where review_reason='PARTIAL_REFUND'and state='OPEN')then raise exception 'full_refund_failed';end if;
 r:=public.payment_v2_apply_refund('re_full1','ch_phase12','pi_phase12',6000,'usd','succeeded',null,null,now(),'evt_re_full1',now()+interval '2 seconds');if r<>'already_applied'then raise exception 'refund_replay';end if;
 begin perform public.payment_v2_apply_refund('re_over1','ch_phase12','pi_phase12',1,'usd','succeeded',null,null,now(),'evt_over',now()+interval '3 seconds');raise exception 'overgross_accepted';exception when others then if sqlerrm='overgross_accepted'then raise;end if;end;
 if public.payment_v2_apply_refund('re_badcurrency1','ch_phase12','pi_phase12',1,'eur','pending',null,null,now(),'evt_currency',now())<>'source_currency_mismatch'then raise exception 'currency_not_blocked';end if;
 if exists(select 1 from public.payment_v2_refunds where provider_refund_id='re_badcurrency1')then raise exception 'invalid_snapshot_saved';end if;
 -- Stronger REFUNDED state survives a later lost dispute.
 perform public.payment_v2_apply_dispute('du_afterrefund1','ch_phase12','pi_phase12',10000,'usd','lost','fraudulent',null,now(),'evt_du_lost',now()+interval '4 seconds');
 if(select state from public.payment_v2_purchases where id=p)<>'REFUNDED'or(select state from public.payment_v2_holds where id=h)<>'REFUNDED'then raise exception 'refunded_downgraded';end if;
 perform public.payment_v2_apply_dispute('du_open1','ch_phase12','pi_phase12',1000,'usd','needs_response','fraudulent',now()+interval '1 day',now(),'evt_du_open1',now()+interval '5 seconds');
 perform public.payment_v2_apply_dispute('du_open1','ch_phase12','pi_phase12',1000,'usd','won','fraudulent',null,now(),'evt_du_won',now()+interval '6 seconds');
 if exists(select 1 from public.payment_v2_financial_reviews where provider_object_id='du_open1'and review_reason='PARTIAL_DISPUTE_LOSS'and state='OPEN')then raise exception 'dispute_review_not_resolved';end if;
END$$;

create temporary table phase12_assertions(n integer not null default 1);
create function pg_temp.assert_phase12(ok boolean,label text)returns void language plpgsql as $$begin if ok is not true then raise exception 'phase12_assertion_failed: %',label;end if;insert into phase12_assertions default values;end$$;
DO $$
DECLARE h uuid;p uuid;ent uuid;res text;before_count integer;item uuid;payload jsonb;invoice uuid;ledger uuid;
BEGIN
 -- Non-successful refund statuses persist without entitlement mutation.
 select id,hold_id into p,h from payment_v2_purchases where stripe_source_charge_id='ch_phase12';
 perform payment_v2_apply_refund('re_requires1','ch_phase12','pi_phase12',25,'usd','requires_action',null,null,now(),'evt_requires',now()+interval '10 seconds');
 perform pg_temp.assert_phase12(exists(select 1 from payment_v2_refunds where provider_refund_id='re_requires1'and status='requires_action'),'requires_action snapshot');
 perform pg_temp.assert_phase12((select state='REFUNDED'from payment_v2_purchases where id=p),'requires_action entitlement unchanged');
 perform payment_v2_apply_refund('re_failed1','ch_phase12','pi_phase12',25,'usd','failed',null,'declined',now(),'evt_failed',now()+interval '11 seconds');
 perform pg_temp.assert_phase12(exists(select 1 from payment_v2_refunds where provider_refund_id='re_failed1'and status='failed'),'failed snapshot');
 perform payment_v2_apply_refund('re_canceled1','ch_phase12','pi_phase12',25,'usd','canceled',null,null,now(),'evt_canceled',now()+interval '12 seconds');
 perform pg_temp.assert_phase12(exists(select 1 from payment_v2_refunds where provider_refund_id='re_canceled1'and status='canceled'),'canceled snapshot');
 begin perform payment_v2_claim(p,extensions.digest('phase12-og','sha256'),'20000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002');raise exception 'claim_accepted';exception when others then if sqlerrm='claim_accepted'then raise;end if;end;
 perform pg_temp.assert_phase12((select count(*)from payment_v2_holds where tier='og_throne'and((state='HELD'and expires_at>now())or state in('SESSION_ASSOCIATED','PAID_UNCLAIMED','CLAIMED')))=0,'refunded seat excluded');

 -- Claimed OG full refund preserves allocation and entitlement row.
 select hold_id into h from payment_v2_acquire_hold(extensions.digest('claimed-og','sha256'),'og_throne',now()+interval '1 hour',null);perform payment_v2_associate_session(h,extensions.digest('claimed-og','sha256'),'cs_claimedog');perform payment_v2_record_paid_with_charge(h,extensions.digest('claimed-og','sha256'),'cs_claimedog','cus_claimedog','price_og','pi_claimedog',null,'evt_claimedog',now(),10000,'usd','pi_claimedog','ch_claimedog',null);select id into p from payment_v2_purchases where hold_id=h;perform payment_v2_claim(p,extensions.digest('claimed-og','sha256'),'20000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002');select entitlement_id into ent from payment_v2_allocations where purchase_id=p;perform payment_v2_apply_refund('re_claimedfull1','ch_claimedog','pi_claimedog',10000,'usd','succeeded',null,null,now(),'evt_claimedfull',now());
 perform pg_temp.assert_phase12((select state='REFUNDED'from payment_v2_purchases where id=p),'claimed full refund purchase');
 perform pg_temp.assert_phase12((select state='REFUNDED'from payment_v2_holds where id=h),'claimed full refund hold');
 perform pg_temp.assert_phase12(exists(select 1 from payment_v2_allocations where purchase_id=p and entitlement_id=ent),'claimed allocation retained');
 perform pg_temp.assert_phase12(exists(select 1 from user_subscriptions where id=ent and status='refunded'),'claimed entitlement retained and refunded');

 -- Revoked remains stronger when refund arrives afterward.
 select hold_id into h from payment_v2_acquire_hold(extensions.digest('revoked-og','sha256'),'og_throne',now()+interval '1 hour',null);perform payment_v2_associate_session(h,extensions.digest('revoked-og','sha256'),'cs_revokedog');perform payment_v2_record_paid_with_charge(h,extensions.digest('revoked-og','sha256'),'cs_revokedog','cus_revokedog','price_og','pi_revokedog',null,'evt_revokedog',now(),10000,'usd','pi_revokedog','ch_revokedog',null);select id into p from payment_v2_purchases where hold_id=h;perform payment_v2_claim(p,extensions.digest('revoked-og','sha256'),'20000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000003');select entitlement_id into ent from payment_v2_allocations where purchase_id=p;perform payment_v2_apply_dispute('du_revoke1','ch_revokedog','pi_revokedog',10000,'usd','lost','fraudulent',null,now(),'evt_revoke',now());perform payment_v2_apply_refund('re_afterrevoke1','ch_revokedog','pi_revokedog',10000,'usd','succeeded',null,null,now(),'evt_afterrevoke',now()+interval '1 second');
 perform pg_temp.assert_phase12((select state='REVOKED'from payment_v2_purchases where id=p),'lost dispute revokes purchase');
 perform pg_temp.assert_phase12((select state='REVOKED'from payment_v2_holds where id=h),'lost dispute revokes hold');
 perform pg_temp.assert_phase12((select status='revoked'from user_subscriptions where id=ent),'lost dispute revokes entitlement');
 perform pg_temp.assert_phase12(exists(select 1 from payment_v2_allocations where purchase_id=p and entitlement_id=ent),'lost dispute retains allocation');
 perform pg_temp.assert_phase12(exists(select 1 from payment_v2_refunds where provider_refund_id='re_afterrevoke1'),'refund after revoked recorded');

 -- Early Bird initial and recurring refunds cannot mutate A3 entitlement.
 select hold_id into h from payment_v2_acquire_hold(extensions.digest('early-p12','sha256'),'early_bird',now()+interval '1 hour',null);perform payment_v2_associate_session(h,extensions.digest('early-p12','sha256'),'cs_earlyp12');perform payment_v2_record_paid_with_charge(h,extensions.digest('early-p12','sha256'),'cs_earlyp12','cus_earlyp12','price_early',null,'sub_earlyp12','evt_earlyp12',now(),3000,'usd','pi_earlyp12','ch_earlyp12','in_earlyp12');select id into p from payment_v2_purchases where hold_id=h;perform payment_v2_claim(p,extensions.digest('early-p12','sha256'),'20000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002');select entitlement_id into ent from payment_v2_allocations where purchase_id=p;perform payment_v2_apply_refund('re_earlyinitial1','ch_earlyp12','pi_earlyp12',3000,'usd','succeeded',null,null,now(),'evt_earlyrefund',now());
 perform pg_temp.assert_phase12((select status in('active','trialing')from user_subscriptions where id=ent)and exists(select 1 from payment_v2_refunds where provider_refund_id='re_earlyinitial1'),'early initial A3 authority');
 insert into payment_v2_affiliate_recurring_invoices(payment_v2_purchase_id,stripe_subscription_id,stripe_invoice_id,stripe_event_id,stripe_payment_intent_id,stripe_source_charge_id,stripe_price_id,billing_reason,service_period_start,service_period_end,paid_month_number,gross_amount_cents,currency,commission_percent,commission_amount_cents)values(p,'sub_earlyp12','in_earlycycle','evt_earlycycle','pi_earlycycle','ch_earlycycle','price_early','subscription_cycle',now(),now()+interval '1 month',2,3000,'usd',20,600)returning id into invoice;perform payment_v2_apply_refund('re_earlycycle1','ch_earlycycle','pi_earlycycle',3000,'usd','succeeded',null,null,now(),'evt_earlycyclerefund',now());
 perform pg_temp.assert_phase12((select status in('active','trialing')from user_subscriptions where id=ent)and exists(select 1 from payment_v2_refunds where provider_refund_id='re_earlycycle1'and recurring_invoice_id=invoice),'early recurring A3 authority');
 res:=payment_v2_apply_refund('re_wrongpi1','ch_earlycycle','pi_wrong',1,'usd','pending',null,null,now(),'evt_wrongpi',now());perform pg_temp.assert_phase12(res='source_payment_intent_mismatch'and not exists(select 1 from payment_v2_refunds where provider_refund_id='re_wrongpi1'),'wrong refund PI fails closed');
 perform payment_v2_apply_refund('re_stale1','ch_earlycycle','pi_earlycycle',1,'usd','pending',null,null,now(),'evt_newer',now()+interval '20 seconds');res:=payment_v2_apply_refund('re_stale1','ch_earlycycle','pi_earlycycle',1,'usd','failed',null,null,now(),'evt_older',now()+interval '19 seconds');perform pg_temp.assert_phase12(res='stale_ignored'and(select status='pending'from payment_v2_refunds where provider_refund_id='re_stale1'),'stale refund ignored');

 -- Dispute statuses, stale ordering, replay, and Early Bird authority.
 perform payment_v2_apply_dispute('du_status1','ch_earlycycle','pi_earlycycle',100,'usd','needs_response','fraudulent',now()+interval '1 day',now(),'evt_duopen',now());perform pg_temp.assert_phase12((select status='needs_response'from payment_v2_disputes where provider_dispute_id='du_status1')and(select status in('active','trialing')from user_subscriptions where id=ent)and payment_v2_source_charge_blocks_affiliate_payout('ch_earlycycle'),'open dispute');
 perform payment_v2_apply_dispute('du_status1','ch_earlycycle','pi_earlycycle',100,'usd','won','fraudulent',null,now(),'evt_duwon',now()+interval '1 second');perform pg_temp.assert_phase12((select status='won'from payment_v2_disputes where provider_dispute_id='du_status1'),'won dispute');
 perform payment_v2_apply_dispute('du_warning1','ch_earlycycle','pi_earlycycle',100,'usd','warning_closed','fraudulent',null,now(),'evt_warning',now());perform pg_temp.assert_phase12((select status='warning_closed'from payment_v2_disputes where provider_dispute_id='du_warning1'),'warning closed');
 perform payment_v2_apply_dispute('du_prevented1','ch_earlycycle','pi_earlycycle',100,'usd','prevented','fraudulent',null,now(),'evt_prevented',now());perform pg_temp.assert_phase12((select status='prevented'from payment_v2_disputes where provider_dispute_id='du_prevented1'),'prevented');
 perform payment_v2_apply_dispute('du_earlylost1','ch_earlycycle','pi_earlycycle',3000,'usd','lost','fraudulent',null,now(),'evt_earlylost',now());perform pg_temp.assert_phase12((select status in('active','trialing')from user_subscriptions where id=ent)and exists(select 1 from payment_v2_financial_reviews where provider_object_id='du_earlylost1'and state='OPEN'),'early lost A3 authority and review');
 res:=payment_v2_apply_dispute('du_wrongpi1','ch_earlycycle','pi_wrong',1,'usd','needs_response','fraudulent',null,now(),'evt_duwrongpi',now());perform pg_temp.assert_phase12(res='source_payment_intent_mismatch'and not exists(select 1 from payment_v2_disputes where provider_dispute_id='du_wrongpi1'),'wrong dispute PI');
 res:=payment_v2_apply_dispute('du_wrongcur1','ch_earlycycle','pi_earlycycle',1,'eur','needs_response','fraudulent',null,now(),'evt_duwrongcur',now());perform pg_temp.assert_phase12(res='source_currency_mismatch'and not exists(select 1 from payment_v2_disputes where provider_dispute_id='du_wrongcur1'),'wrong dispute currency');
 perform payment_v2_apply_dispute('du_stale1','ch_earlycycle','pi_earlycycle',10,'usd','under_review','fraudulent',null,now(),'evt_dunewer',now()+interval '30 seconds');res:=payment_v2_apply_dispute('du_stale1','ch_earlycycle','pi_earlycycle',10,'usd','lost','fraudulent',null,now(),'evt_duolder',now()+interval '29 seconds');perform pg_temp.assert_phase12(res='stale_ignored'and(select status='under_review'from payment_v2_disputes where provider_dispute_id='du_stale1'),'stale dispute ignored');res:=payment_v2_apply_dispute('du_stale1','ch_earlycycle','pi_earlycycle',10,'usd','under_review','fraudulent',null,now(),'evt_dunewer',now()+interval '30 seconds');perform pg_temp.assert_phase12(res='already_applied','dispute replay');

 -- Payout first-dispatch race and already-dispatching frozen recovery.
 select id into ledger from affiliate_ledger where payment_v2_purchase_id=p;update affiliate_ledger set status='available',attribution_status='PURCHASER_ATTACHED',referred_user_id='10000000-0000-4000-8000-000000000002',commission_amount_cents=6000 where id=ledger;insert into affiliate_payout_batches(notes)values('phase12-race');insert into affiliate_payout_items(batch_id,ledger_id,affiliate_user_id,amount_cents,currency,source_charge_id,connect_destination,transfer_idempotency_key,execution_status,attempt_count)select b.id,ledger,'20000000-0000-4000-8000-000000000001',6000,'usd','ch_earlyp12','acct_referrer','pfc03d:'||ledger,'pending',0 from affiliate_payout_batches b where notes='phase12-race'returning id into item;
 perform pg_temp.assert_phase12(payment_v2_begin_payout_dispatch(item)is null and(select execution_status='pending'from affiliate_payout_items where id=item),'blocked pending dispatch');
 update affiliate_payout_items set execution_status='dispatching',attempt_count=1 where id=item;select payment_v2_begin_payout_dispatch(item)into payload;perform pg_temp.assert_phase12(payload->>'execution_status'='dispatching'and payload->>'source_charge_id'='ch_earlyp12'and(payload->>'amount_cents')::integer=6000,'dispatching frozen replay');

 -- Recurring evidence refresh, reconciliation mismatch, destination failure, and won eligibility.
 insert into payment_v2_affiliate_recurring_invoices(payment_v2_purchase_id,stripe_subscription_id,stripe_invoice_id,stripe_event_id,stripe_payment_intent_id,stripe_source_charge_id,stripe_price_id,billing_reason,service_period_start,service_period_end,paid_month_number,gross_amount_cents,currency,commission_percent,commission_amount_cents)values(p,'sub_earlyp12','in_refresh','evt_refresh','pi_refresh','ch_refresh','price_early','subscription_cycle',now()+interval '2 months',now()+interval '3 months',3,4000,'usd',20,800)returning id into invoice;
 insert into affiliate_ledger(affiliate_user_id,referred_user_id,stripe_event_id,stripe_subscription_id,tier_name,commission_amount_cents,gross_amount_cents,commission_percent,status,referral_code_id,referrer_affiliate_tier,attribution_status,payment_v2_recurring_invoice_id)values('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000002','invoice:in_refresh','sub_earlyp12','early_bird',800,4000,20,'available',(select id from referral_codes where code='PHASE12'),'og_throne','PURCHASER_ATTACHED',invoice)returning id into ledger;
 insert into affiliate_payout_items(batch_id,ledger_id,affiliate_user_id,amount_cents,currency,source_charge_id,connect_destination,transfer_idempotency_key,execution_status,attempt_count)select id,ledger,'20000000-0000-4000-8000-000000000001',1,'eur','ch_stale','acct_stale','pfc03d:'||ledger,'pending',0 from affiliate_payout_batches where notes='phase12-race'returning id into item;
 select payment_v2_begin_payout_dispatch(item)into payload;perform pg_temp.assert_phase12(payload->>'source_charge_id'='ch_refresh'and(payload->>'amount_cents')::integer=800 and payload->>'currency'='usd'and(select paid_month_number=3 and commission_percent=20 from affiliate_payout_items where id=item),'recurring authoritative refresh');

 insert into payment_v2_affiliate_recurring_invoices(payment_v2_purchase_id,stripe_subscription_id,stripe_invoice_id,stripe_event_id,stripe_payment_intent_id,stripe_source_charge_id,stripe_price_id,billing_reason,service_period_start,service_period_end,paid_month_number,gross_amount_cents,currency,commission_percent,commission_amount_cents)values(p,'sub_earlyp12','in_mismatch','evt_mismatch','pi_mismatch','ch_mismatch','price_early','subscription_cycle',now()+interval '3 months',now()+interval '4 months',4,4000,'usd',20,800)returning id into invoice;
 insert into affiliate_ledger(affiliate_user_id,referred_user_id,stripe_event_id,stripe_subscription_id,tier_name,commission_amount_cents,gross_amount_cents,commission_percent,status,referral_code_id,referrer_affiliate_tier,attribution_status,payment_v2_recurring_invoice_id)values('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000002','invoice:in_mismatch','sub_earlyp12','early_bird',799,4000,20,'available',(select id from referral_codes where code='PHASE12'),'og_throne','PURCHASER_ATTACHED',invoice)returning id into ledger;
 insert into affiliate_payout_items(batch_id,ledger_id,affiliate_user_id,amount_cents,currency,source_charge_id,connect_destination,transfer_idempotency_key,execution_status,attempt_count)select id,ledger,'20000000-0000-4000-8000-000000000001',799,'usd','ch_mismatch','acct_referrer','pfc03d:'||ledger,'pending',0 from affiliate_payout_batches where notes='phase12-race'returning id into item;perform pg_temp.assert_phase12(payment_v2_begin_payout_dispatch(item)is null and(select execution_status='pending'from affiliate_payout_items where id=item),'recurring mismatch blocked');

 update profiles set stripe_connect_onboarded=false,stripe_connect_account_id=null where id='20000000-0000-4000-8000-000000000001';update payment_v2_holds set stripe_connect_destination=null where id=h;update affiliate_ledger set commission_amount_cents=800 where id=ledger;perform pg_temp.assert_phase12(payment_v2_begin_payout_dispatch(item)is null and(select execution_status='pending'from affiliate_payout_items where id=item),'missing destination blocked');
 perform payment_v2_apply_dispute('du_clean1','ch_refresh','pi_refresh',100,'usd','needs_response','fraudulent',null,now(),'evt_cleanopen',now());perform payment_v2_apply_dispute('du_clean1','ch_refresh','pi_refresh',100,'usd','won','fraudulent',null,now(),'evt_cleanwon',now()+interval '1 second');perform pg_temp.assert_phase12(not payment_v2_source_charge_blocks_affiliate_payout('ch_refresh'),'won source eligible without other blocker');
END$$;

-- Database security contracts execute under actual PostgreSQL roles and catalogs.
select pg_temp.assert_phase12(relrowsecurity and relforcerowsecurity,'refund RLS force')from pg_class where oid='payment_v2_refunds'::regclass;
select pg_temp.assert_phase12(relrowsecurity and relforcerowsecurity,'dispute RLS force')from pg_class where oid='payment_v2_disputes'::regclass;
select pg_temp.assert_phase12(relrowsecurity and relforcerowsecurity,'review RLS force')from pg_class where oid='payment_v2_financial_reviews'::regclass;
select pg_temp.assert_phase12(not has_table_privilege('anon','payment_v2_refunds','select')and not has_table_privilege('authenticated','payment_v2_refunds','select')and not has_table_privilege('service_role','payment_v2_refunds','select'),'refund direct select revoked');
select pg_temp.assert_phase12(not has_table_privilege('anon','payment_v2_disputes','select')and not has_table_privilege('authenticated','payment_v2_disputes','select')and not has_table_privilege('service_role','payment_v2_disputes','select'),'dispute direct select revoked');
select pg_temp.assert_phase12(not has_table_privilege('anon','payment_v2_financial_reviews','select')and not has_table_privilege('authenticated','payment_v2_financial_reviews','select')and not has_table_privilege('service_role','payment_v2_financial_reviews','select'),'review direct select revoked');
select pg_temp.assert_phase12(has_function_privilege('service_role','payment_v2_apply_refund(text,text,text,integer,text,text,text,text,timestamptz,text,timestamptz)','execute')and not has_function_privilege('anon','payment_v2_apply_refund(text,text,text,integer,text,text,text,text,timestamptz,text,timestamptz)','execute'),'bounded refund RPC ACL');
select pg_temp.assert_phase12((select bool_and(capability_key='billing.financial.read')from admin_role_capabilities where role_key='billing_operator'),'billing operator bounded');
select pg_temp.assert_phase12(exists(select 1 from admin_role_capabilities where role_key='founder_admin'and capability_key='billing.financial.read'),'founder billing capability');
select 'phase12_postgres_assertions='||count(*) from phase12_assertions;
