export const FANVUE_MEDIA_READINESS_MAX_ATTEMPTS = 6 as const
export const FANVUE_MEDIA_READINESS_BACKOFF_BASE_MS = 5_000 as const
export const FANVUE_MEDIA_READINESS_MAX_DELAY_MS = 5_000 as const
export const FANVUE_VIDEO_MEDIA_READINESS_MAX_ATTEMPTS = 24 as const
export const FANVUE_VIDEO_MEDIA_READINESS_BACKOFF_BASE_MS = 5_000 as const
export const FANVUE_VIDEO_MEDIA_READINESS_MAX_DELAY_MS = 5_000 as const
