import { decryptAutopostToken, encryptAutopostToken, getAutopostTokenKeyVersion } from "./tokenCryptoCore"
import { getXStoredPostureBlocker, type XStoredPostureAccount } from "./xStoredPosture"
export const X_CONTROLLED_REFRESH_BUFFER_MS=60000, X_CONTROLLED_REFRESH_TIMEOUT_MS=10000, MAX_ZERO_LENGTH_READS=8, BODY_READ_TIMEOUT_MS=250, BODY_CANCEL_TIMEOUT_MS=50
export const X_CONTROLLED_REFRESH_CONFIRMATION="refresh-protected-x-once-v1", X_CONTROLLED_REFRESH_ENDPOINT="https://api.x.com/2/oauth2/token"
type SC="2xx"|"4xx"|"5xx"|null
export type Result={ok:boolean;mode:"x_controlled_refresh";safe_code:string;provider_request_attempted:boolean;provider_status_class:SC;refresh_attempted:boolean;refresh_verified:boolean;outcome_uncertain:boolean;database_write_attempted:boolean;database_write_verified:boolean;retry_attempted:false;post_attempted:false;runner_invoked:false;scheduler_action_attempted:false;cron_action_attempted:false;public_enablement_attempted:false;fanvue_account_queried:false;fanvue_account_mutated:false}
const result=(safe_code:string,v:Partial<Result>={}):Result=>({ok:false,mode:"x_controlled_refresh",safe_code,provider_request_attempted:false,provider_status_class:null,refresh_attempted:false,refresh_verified:false,outcome_uncertain:false,database_write_attempted:false,database_write_verified:false,retry_attempted:false,post_attempted:false,runner_invoked:false,scheduler_action_attempted:false,cron_action_attempted:false,public_enablement_attempted:false,fanvue_account_queried:false,fanvue_account_mutated:false,...v})
export const xControlledRefreshMethodNotAllowedResult=()=>result("X_CONTROLLED_REFRESH_METHOD_NOT_ALLOWED")
async function bounded<T>(p:Promise<T>,ms:number){let t:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([p,new Promise<T>((_,r)=>{t=setTimeout(r,ms)})])}finally{if(t)clearTimeout(t)}}
export async function hasZeroByteBody(request:Request){if(request.body===null)return true;const r=request.body.getReader();let ok=false;try{for(let n=0;n<=MAX_ZERO_LENGTH_READS;n++){const x=await bounded(r.read(),BODY_READ_TIMEOUT_MS);if(x.done){ok=true;break}if(x.value.byteLength||n===MAX_ZERO_LENGTH_READS)break}}catch{}if(!ok)try{await bounded(Promise.resolve(r.cancel()),BODY_CANCEL_TIMEOUT_MS)}catch{}try{r.releaseLock()}catch{}return ok}
export type Account=XStoredPostureAccount&{encrypted_access_token:string|null;encrypted_refresh_token:string|null;token_expires_at:string|null;token_key_version:number|null}
type Proof={data:{id?:unknown}|null;error:unknown};export type Writer=(v:Record<string,unknown>,a:Account,u:string)=>Promise<Proof>
export type Dependencies={decryptToken?:(v:string)=>string;encryptToken?:(v:string)=>string;getTokenKeyVersion?:()=>number;now?:()=>Date;fetch?:typeof fetch;createTimeoutSignal?:(n:number)=>AbortSignal;clientId?:string;clientSecret?:string;endpoint?:string}
const plain=(x:unknown):x is Record<string,unknown>=>{if(!x||typeof x!=="object")return false;const p=Object.getPrototypeOf(x);return p===Object.prototype||p===null}
const sc=(n:number):SC=>n>=200&&n<300?"2xx":n>=400&&n<500?"4xx":n>=500&&n<600?"5xx":null
const tried=(c:string,s:SC,u=false)=>result(c,{provider_request_attempted:true,provider_status_class:s,refresh_attempted:true,outcome_uncertain:u})
const endpointOk=(s:string)=>{try{const u=new URL(s);return u.href===X_CONTROLLED_REFRESH_ENDPOINT&&u.protocol==="https:"&&u.hostname==="api.x.com"&&!u.port&&!u.username&&!u.password&&!u.search&&!u.hash&&u.pathname==="/2/oauth2/token"}catch{return false}}
async function write(w:Writer,v:Record<string,unknown>,a:Account,u:string,b:Partial<Result>,code:string){try{const p=await w(v,a,u);if(p.error)return result("X_CONTROLLED_REFRESH_ACCOUNT_UPDATE_FAILED",{...b,database_write_attempted:true,outcome_uncertain:true});if(p.data===null)return result("X_CONTROLLED_REFRESH_ACCOUNT_CHANGED",{...b,database_write_attempted:true});if(typeof p.data.id!=="string"||!p.data.id.trim())return result("X_CONTROLLED_REFRESH_ACCOUNT_UPDATE_FAILED",{...b,database_write_attempted:true,outcome_uncertain:true});return result(code,{...b,ok:code==="X_CONTROLLED_REFRESH_SUCCEEDED",database_write_attempted:true,database_write_verified:true})}catch{return result("X_CONTROLLED_REFRESH_ACCOUNT_UPDATE_FAILED",{...b,database_write_attempted:true,outcome_uncertain:true})}}
export async function controlledRefreshX(userId:string,a:Account,w:Writer,d:Dependencies={}):Promise<Result>{
 if(getXStoredPostureBlocker(a))return result("X_CONTROLLED_REFRESH_ACCOUNT_NOT_READY");if((a.provider_username as string).trim().toLowerCase()!=="the_beard0302"||!(a.provider_account_id as string).trim())return result("X_CONTROLLED_REFRESH_PROTECTED_USERNAME_MISMATCH")
 let k:number;try{k=(d.getTokenKeyVersion??getAutopostTokenKeyVersion)()}catch{return result("X_CONTROLLED_REFRESH_TOKEN_KEY_VERSION_UNAVAILABLE")}if(!Number.isFinite(k)||!Number.isInteger(k)||k<=0)return result("X_CONTROLLED_REFRESH_TOKEN_KEY_VERSION_UNAVAILABLE");if(k!==a.token_key_version)return result("X_CONTROLLED_REFRESH_TOKEN_KEY_VERSION_MISMATCH")
 let now:Date,n:number;try{now=(d.now??(()=>new Date()))();n=now.getTime();if(!(now instanceof Date)||!Number.isFinite(n)||!now.toISOString())throw 0}catch{return result("X_CONTROLLED_REFRESH_CLOCK_INVALID")}if(new Date(a.token_expires_at as string).getTime()>n+X_CONTROLLED_REFRESH_BUFFER_MS)return result("X_CONTROLLED_REFRESH_NOT_REQUIRED")
 let rt:string;try{rt=(d.decryptToken??decryptAutopostToken)(a.encrypted_refresh_token as string)}catch{return result("X_CONTROLLED_REFRESH_REFRESH_TOKEN_DECRYPT_FAILED")}if(typeof rt!=="string"||!rt.trim())return result("X_CONTROLLED_REFRESH_REFRESH_TOKEN_INVALID")
 const id=(d.clientId??process.env.X_CLIENT_ID??"").trim(),secret=(d.clientSecret??process.env.X_CLIENT_SECRET??"").trim(),ep=d.endpoint??X_CONTROLLED_REFRESH_ENDPOINT;if(!id||!secret||!endpointOk(ep))return result("X_CONTROLLED_REFRESH_PROVIDER_CONFIG_INVALID")
 let signal:AbortSignal;try{signal=(d.createTimeoutSignal??((x)=>AbortSignal.timeout(x)))(X_CONTROLLED_REFRESH_TIMEOUT_MS)}catch{return result("X_CONTROLLED_REFRESH_PROVIDER_CONFIG_INVALID")}
 let response:Response;try{response=await(d.fetch??fetch)(ep,{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams([["grant_type","refresh_token"],["refresh_token",rt]]),cache:"no-store",redirect:"error",signal})}catch(e){const name=e instanceof Error?e.name:plain(e)&&typeof e.name==="string"?e.name:"";return tried(name==="TimeoutError"||(name==="AbortError"&&signal.aborted)?"X_CONTROLLED_REFRESH_PROVIDER_TIMEOUT":"X_CONTROLLED_REFRESH_PROVIDER_NETWORK_FAILURE",null,true)}
 const s=sc(response.status);let body:unknown;try{body=await response.json()}catch{}if(!response.ok){const oe=plain(body)&&typeof body.error==="string"?body.error:"";if(oe==="invalid_grant")return write(w,{connection_status:"EXPIRED",last_error:"X_CONTROLLED_REFRESH_PROVIDER_UNAUTHORIZED"},a,userId,{provider_request_attempted:true,provider_status_class:s,refresh_attempted:true},"X_CONTROLLED_REFRESH_PROVIDER_UNAUTHORIZED");if(oe==="invalid_client")return tried("X_CONTROLLED_REFRESH_PROVIDER_INVALID_CLIENT",s);if(response.status===429)return tried("X_CONTROLLED_REFRESH_PROVIDER_RATE_LIMITED",s);if(response.status>=400&&response.status<500)return tried("X_CONTROLLED_REFRESH_PROVIDER_REJECTED",s);return tried("X_CONTROLLED_REFRESH_PROVIDER_OUTCOME_UNKNOWN",s,true)}
 const bad=()=>tried("X_CONTROLLED_REFRESH_PROVIDER_RESPONSE_INVALID",s,true);if(!plain(body))return bad();const at=body.access_token,ty=body.token_type,ex=body.expires_in,rr=body.refresh_token;if(typeof at!=="string"||!at.trim()||typeof ty!=="string"||ty.trim().toLowerCase()!=="bearer"||typeof ex!=="number"||!Number.isFinite(ex)||ex<=0||rr!==undefined&&(typeof rr!=="string"||!rr.trim()))return bad();const em=n+ex*1000;if(!Number.isFinite(em))return bad();let iso:string;try{iso=new Date(em).toISOString()}catch{return bad()}let scopes:string[]|undefined;if(body.scope!==undefined){if(typeof body.scope!=="string"||!body.scope.trim())return bad();scopes=[...new Set(body.scope.split(/\s+/).filter(Boolean))];if(!scopes.length)return bad()}
 let ea:string,er=a.encrypted_refresh_token as string;try{const enc=d.encryptToken??encryptAutopostToken;ea=enc(at);if(typeof rr==="string")er=enc(rr)}catch{return result("X_CONTROLLED_REFRESH_TOKEN_ENCRYPTION_FAILED",{provider_request_attempted:true,provider_status_class:s,refresh_attempted:true,refresh_verified:true,outcome_uncertain:true})}const values:Record<string,unknown>={encrypted_access_token:ea,encrypted_refresh_token:er,token_expires_at:iso,token_type:"bearer",token_key_version:k,connection_status:"CONNECTED",last_refresh_at:now.toISOString(),last_error:null};if(scopes)values.scopes=scopes;return write(w,values,a,userId,{provider_request_attempted:true,provider_status_class:s,refresh_attempted:true,refresh_verified:true},"X_CONTROLLED_REFRESH_SUCCEEDED")}
export function createXControlledRefreshAccountLoader(c:any){return async(u:string)=>{const q=await c.from("autopost_accounts").select("connection_status,provider_account_id,provider_username,last_error,encrypted_access_token,encrypted_refresh_token,token_expires_at,token_key_version,metadata").eq("user_id",u).eq("platform","x").maybeSingle();return{account:q.data as Account|null,error:q.error}}}
export function createXControlledRefreshWriter(c:any):Writer{return async(v,a,u)=>c.from("autopost_accounts").update(v).eq("user_id",u).eq("platform","x").eq("connection_status","CONNECTED").eq("provider_account_id",a.provider_account_id).eq("provider_username",a.provider_username).eq("token_key_version",a.token_key_version).eq("encrypted_access_token",a.encrypted_access_token).eq("encrypted_refresh_token",a.encrypted_refresh_token).eq("token_expires_at",a.token_expires_at).is("last_error",null).select("id").maybeSingle()}
export async function handleXControlledRefreshRequest(i:{request:Request;getAuthenticatedUserId:()=>Promise<string|null|undefined>;createPrivilegedAccess:()=>{load:ReturnType<typeof createXControlledRefreshAccountLoader>;writer:Writer};dependencies?:Dependencies}){let raw;try{raw=await i.getAuthenticatedUserId()}catch{return{status:401,body:result("X_CONTROLLED_REFRESH_UNAUTHENTICATED")}}const u=typeof raw==="string"?raw.trim():"";if(!u)return{status:401,body:result("X_CONTROLLED_REFRESH_UNAUTHENTICATED")};if(i.request.headers.get("x-autopost-x-controlled-refresh")!==X_CONTROLLED_REFRESH_CONFIRMATION)return{status:400,body:result("X_CONTROLLED_REFRESH_CONFIRMATION_REQUIRED")};if(new URL(i.request.url).search||!await hasZeroByteBody(i.request))return{status:400,body:result("X_CONTROLLED_REFRESH_PARAMETERS_NOT_ALLOWED")};let x,l;try{x=i.createPrivilegedAccess();l=await x.load(u)}catch{return{status:200,body:result("X_CONTROLLED_REFRESH_ACCOUNT_LOOKUP_FAILED")}}if(l.error||!l.account)return{status:200,body:result("X_CONTROLLED_REFRESH_ACCOUNT_LOOKUP_FAILED")};return{status:200,body:await controlledRefreshX(u,l.account,x.writer,i.dependencies)}}
