"use client"
import { useActionState, useEffect, useMemo, useRef, useState } from "react"
import { useFormStatus } from "react-dom"
import { useRouter } from "next/navigation"
import { decideCreatorPublishingPackage, type ApprovalActionState } from "./actions"

function SubmitButton({ children, tone }: { children: React.ReactNode; tone: "approve" | "reject" }) { const { pending } = useFormStatus(); return <button type="submit" disabled={pending} className={`rounded-xl px-5 py-3 text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-black disabled:cursor-not-allowed disabled:opacity-60 ${tone === "approve" ? "bg-emerald-400 text-black focus:ring-emerald-200" : "border border-rose-400/60 bg-rose-950/60 text-rose-100 focus:ring-rose-300"}`}>{pending ? "Saving decision…" : children}</button> }
export function ApprovalDecisionForm({ hidden, approvable }: { hidden: Record<string,string>; approvable: boolean }) {
  const router = useRouter(); const [state, action] = useActionState<ApprovalActionState, FormData>(decideCreatorPublishingPackage, { ok: false }); const [decision, setDecision] = useState<"approve"|"reject"|null>(null); const [reason, setReason] = useState(""); const key = useMemo(() => hidden.idempotency_key, [hidden.idempotency_key]); const live = useRef<HTMLDivElement>(null)
  useEffect(() => { if (state.message && live.current) live.current.focus(); if (state.ok) router.refresh() }, [state, router])
  const controlsBlocked = !approvable || state.ok || state.controlsDisabled
  if (controlsBlocked) return <div tabIndex={-1} ref={live} aria-live="polite" className="rounded-2xl border border-emerald-400/30 bg-emerald-950/30 p-5 text-emerald-100"><h2 className="text-lg font-semibold">{state.title ?? "Current status"}</h2>{state.message && <p className="mt-2 text-sm">{state.message}</p>}{state.reloadRequired && <button type="button" onClick={() => router.refresh()} className="mt-4 rounded-xl border border-white/20 px-4 py-2 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-white/60">Reload package</button>}</div>
  return <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5" aria-labelledby="decision-title"><div ref={live} tabIndex={-1} aria-live="assertive">{state.message && <div className="mb-4 rounded-2xl border border-amber-300/40 bg-amber-950/40 p-4 text-sm text-amber-100"><strong>{state.title}</strong><p>{state.message}</p></div>}</div><h2 id="decision-title" className="text-xl font-semibold text-white">Creator decision</h2><p className="mt-2 text-sm text-zinc-300">Approve only after reviewing the exact snapshot. Rejection stops this package from proceeding to manual handoff.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => setDecision("approve")} className="rounded-xl border border-emerald-300/40 px-4 py-3 text-left text-emerald-100 focus:outline-none focus:ring-2 focus:ring-emerald-200">Approve package</button><button type="button" onClick={() => setDecision("reject")} className="rounded-xl border border-rose-300/40 px-4 py-3 text-left text-rose-100 focus:outline-none focus:ring-2 focus:ring-rose-200">Reject package</button></div>{decision && <form action={action} className="mt-5 rounded-2xl border border-white/10 bg-black/30 p-4"><input type="hidden" name="decision" value={decision}/>{Object.entries(hidden).map(([k,v]) => <input key={k} type="hidden" name={k} value={k === "idempotency_key" ? key : v}/>)}<h3 className="font-semibold text-white">Confirm {decision === "approve" ? "approval" : "rejection"}</h3><p className="mt-1 text-sm text-zinc-300">This calls the trusted approval service. Sirens Forge will not post to any platform.</p>{decision === "reject" && <label className="mt-4 block text-sm font-medium text-zinc-200">Rejection reason <textarea required minLength={1} name="rejection_reason" value={reason} onChange={e => setReason(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-white/10 bg-black/50 p-3 text-white focus:outline-none focus:ring-2 focus:ring-rose-200" /></label>}<div className="mt-4 flex gap-3"><SubmitButton tone={decision}>{decision === "approve" ? "I confirm approval" : "I confirm rejection"}</SubmitButton><button type="button" onClick={() => setDecision(null)} className="rounded-xl border border-white/10 px-5 py-3 text-sm text-zinc-200 focus:outline-none focus:ring-2 focus:ring-white/50">Cancel</button></div></form>}</section>
}
