import { noUrlReasonLabel } from "@/lib/creator-publishing-queue/onlyfans-history/presentation"
import { formatHistoryTimestamp } from "@/lib/creator-publishing-queue/onlyfans-history/timezone"
import type { OnlyFansCreatorPackageHistoryView, OnlyFansHistorySuccessView, OnlyFansHistoryView } from "@/lib/creator-publishing-queue/onlyfans-history/types"

type Audience = "creator"|"operator"

function HistoryTimelineSection({ view, audience, headingId, title="Publishing timeline" }: { view:OnlyFansHistorySuccessView; audience:Audience; headingId:string; title?:string }) {
  if (view.entries.length === 0) return <section className="mt-5 rounded-3xl border border-white/10 bg-white/[0.04] p-5" aria-live="polite"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 text-zinc-400">No OnlyFans publishing history has been recorded for this attempt.</p></section>
  return <section className="mt-5 rounded-3xl border border-white/10 bg-white/[0.04] p-5" aria-labelledby={headingId}><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-200">OnlyFans history</p><h3 id={headingId} className="text-xl font-semibold">{title}</h3></div><p className="text-sm text-zinc-400">Times shown in {view.timezoneLabel}.</p></div><ol className="mt-5 space-y-4">{view.entries.map(entry => <li key={entry.id} className="rounded-2xl border border-white/10 bg-black/30 p-4"><article><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h4 className="font-semibold text-white">{entry.label}</h4><p className="mt-1 text-sm text-zinc-300">{entry.explanation}</p></div><time dateTime={entry.occurredAt} className="text-sm text-cyan-100">{formatHistoryTimestamp(entry.occurredAt, view.timezone)}</time></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-zinc-500">Evidence state</dt><dd>{entry.evidenceState ?? "Not applicable"}</dd></div><div><dt className="text-zinc-500">Source</dt><dd>{audience === "operator" ? entry.provenance.replaceAll("_"," ") : entry.provenance === "reconstructed_completion_state" ? "Reconstructed from trusted records" : "Trusted publishing record"}</dd></div>{entry.finalPostUrl ? <div className="sm:col-span-2"><dt className="text-zinc-500">Final URL</dt><dd><a href={entry.finalPostUrl} target="_blank" rel="noreferrer" className="break-all text-cyan-200 underline">{entry.finalPostUrl}</a></dd></div> : null}{entry.noUrlReason ? <div className="sm:col-span-2"><dt className="text-zinc-500">No-URL reason</dt><dd>{noUrlReasonLabel(entry.noUrlReason)}</dd></div> : null}</dl>{audience === "operator" && entry.metadata ? <details className="mt-3 rounded-xl border border-white/10 p-3"><summary className="cursor-pointer font-medium focus:outline-none focus:ring-2 focus:ring-cyan-200">Operational details</summary><dl className="mt-3 grid gap-2 break-all text-xs text-zinc-300 sm:grid-cols-2">{Object.entries(entry.metadata).filter(([,value])=>value!==undefined && value!==null && value!=="").map(([key,value])=><div key={key}><dt className="text-zinc-500">{key}</dt><dd>{String(value)}</dd></div>)}</dl></details> : null}</article></li>)}</ol></section>
}

function PackageAttempts({ view }: { view:Extract<OnlyFansCreatorPackageHistoryView,{ok:true}> }) {
  if (view.attempts.length === 0) return <section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.04] p-5" aria-live="polite"><h2 className="text-2xl font-semibold">Publication attempts</h2><p className="mt-3 text-zinc-400">No OnlyFans publishing attempts have been recorded yet.</p></section>
  return <section className="mt-8" aria-labelledby="creator-onlyfans-publication-attempts"><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><p className="text-sm uppercase tracking-[0.25em] text-cyan-200">OnlyFans history</p><h2 id="creator-onlyfans-publication-attempts" className="mt-1 text-2xl font-semibold">Publication attempts</h2><p className="mt-2 text-sm text-zinc-400">Newest attempt first. Each attempt keeps its own schedule timezone and trusted records.</p></div><div className="mt-5 space-y-8">{view.attempts.map((attempt,index)=><article key={attempt.platformJobId} className="rounded-3xl border border-fuchsia-300/20 bg-fuchsia-950/10 p-5" aria-labelledby={`creator-onlyfans-attempt-${attempt.platformJobId}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-fuchsia-200">Publication attempt {index+1}</p><h3 id={`creator-onlyfans-attempt-${attempt.platformJobId}`} className="mt-1 text-2xl font-semibold">{attempt.jobState.replaceAll("_"," ")}</h3><p className="mt-2 text-sm text-zinc-400">Created <time dateTime={attempt.createdAt}>{formatHistoryTimestamp(attempt.createdAt,attempt.history.timezone)}</time></p></div><span className="rounded-full border border-white/10 px-3 py-1 text-sm text-zinc-300">{attempt.taskLinkState === "exact" ? "Exact task history" : "Limited job history"}</span></div>{attempt.taskLinkState === "limited" ? <p className="mt-4 rounded-2xl border border-amber-300/30 bg-amber-950/20 p-4 text-sm text-amber-100">An exact queue-task relationship could not be proven for this attempt. Only job-level trusted history is shown.</p> : null}<HistoryTimelineSection view={attempt.history} audience="creator" headingId={`creator-onlyfans-attempt-timeline-${attempt.platformJobId}`} title="Attempt timeline"/></article>)}</div></section>
}

export function OnlyFansHistoryTimeline({ view, audience="creator" }: { view: OnlyFansHistoryView|OnlyFansCreatorPackageHistoryView; audience?:Audience }) {
  if (view.ok === false) return <section className="mt-8 rounded-3xl border border-amber-300/30 bg-amber-950/20 p-5 text-amber-100" aria-live="polite"><h2 className="text-2xl font-semibold">Publishing history</h2><p className="mt-3">{view.message}</p></section>
  if ("attempts" in view) return <PackageAttempts view={view}/>
  return <HistoryTimelineSection view={view} audience={audience} headingId={`${audience}-onlyfans-history-heading`}/>
}
