"use client"

import { useActionState, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react"
import { useFormStatus } from "react-dom"
import { useRouter } from "next/navigation"
import type { OnlyFansOperatorDetailRecord, OperatorMutationResult } from "@/lib/creator-publishing-queue/operator-queue"
import { claimOnlyFansOperatorTaskAction, recoverExpiredOnlyFansOperatorClaimAction, releaseOnlyFansOperatorTaskAction, updateOnlyFansOperatorProgressAction } from "./actions"
import { canShowClaimControl, canShowProgressControl, canShowRecoveryControl, canShowReleaseControl, createOperatorLifecycle, getNextProgressState, markOperatorActionFailed, markOperatorActionSucceeded, progressStateLabel, reconcileOperatorLifecycle, isOperatorActionSubmissionDisabled } from "./presentation"

type State = OperatorMutationResult<{ platformJobId: string }> | null
type Props = { record: OnlyFansOperatorDetailRecord; serverSeed: string; authoritativeTaskVersion: string }
function SubmitButton({ label, pendingLabel, disabled }: { label: string; pendingLabel: string; disabled: boolean }) { const { pending } = useFormStatus(); return <button type="submit" disabled={disabled || pending} className="rounded-xl bg-fuchsia-500 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-zinc-700 disabled:text-zinc-300 focus:outline-none focus:ring-2 focus:ring-fuchsia-200">{pending ? pendingLabel : label}</button> }
function ResultMessage({ state }: { state: State }) { const resultRef = useRef<HTMLDivElement>(null); useLayoutEffect(()=>{ if (state?.ok === false) resultRef.current?.focus() },[state]); if (!state) return null; return <div ref={resultRef} tabIndex={-1} aria-live="polite" className={`mt-3 rounded-xl border p-3 text-sm ${state.ok ? "border-emerald-300/40 bg-emerald-950/30 text-emerald-100" : "border-amber-300/40 bg-amber-950/30 text-amber-100"}`}>{state.ok === true ? "Action accepted. Refreshing the trusted task snapshot." : state.message}{state.ok === false && state.retryable === true ? <button type="button" onClick={() => window.location.reload()} className="ml-3 underline focus:outline-none focus:ring-2 focus:ring-amber-200">Reload snapshot</button> : null}</div> }
function ClaimForm({ record, actionKey, disabled, onResult }: any) { const [state, action] = useActionState(claimOnlyFansOperatorTaskAction, null); useLayoutEffect(()=>{ if (state !== null) onResult(state) },[state,onResult]); return <form action={action} className="rounded-2xl border border-white/10 p-4"><input type="hidden" name="platformJobId" value={record.platformJobId}/><input type="hidden" name="idempotencyKey" value={actionKey}/><SubmitButton label="Claim task" pendingLabel="Claiming…" disabled={disabled || state?.ok === true}/><ResultMessage state={state}/></form> }
function ReleaseForm({ record, actionKey, disabled, onResult }: any) { const [state, action] = useActionState(releaseOnlyFansOperatorTaskAction, null); useLayoutEffect(()=>{ if (state !== null) onResult(state) },[state,onResult]); return <form action={action} className="rounded-2xl border border-white/10 p-4"><input type="hidden" name="platformJobId" value={record.platformJobId}/><input type="hidden" name="idempotencyKey" value={actionKey}/><SubmitButton label="Release claim" pendingLabel="Releasing…" disabled={disabled || state?.ok === true}/><ResultMessage state={state}/></form> }
function ProgressForm({ record, actionKey, disabled, onResult }: any) { const [state, action] = useActionState(updateOnlyFansOperatorProgressAction, null); useLayoutEffect(()=>{ if (state !== null) onResult(state) },[state,onResult]); const next = getNextProgressState(record.progressState); if (!next) return null; return <form action={action} className="rounded-2xl border border-white/10 p-4"><input type="hidden" name="platformJobId" value={record.platformJobId}/><input type="hidden" name="expectedProgressState" value={record.progressState}/><input type="hidden" name="expectedProgressRevision" value={record.progressRevision}/><input type="hidden" name="nextProgressState" value={next}/><input type="hidden" name="idempotencyKey" value={actionKey}/><SubmitButton label={`Mark ${progressStateLabel(next)}`} pendingLabel="Saving progress…" disabled={disabled || state?.ok === true}/><ResultMessage state={state}/></form> }
function RecoveryForm({ record, actionKey, disabled, onResult }: any) { const [state, action] = useActionState(recoverExpiredOnlyFansOperatorClaimAction, null); useLayoutEffect(()=>{ if (state !== null) onResult(state) },[state,onResult]); return <form action={action} className="rounded-2xl border border-white/10 p-4"><input type="hidden" name="platformJobId" value={record.platformJobId}/><input type="hidden" name="idempotencyKey" value={actionKey}/><SubmitButton label="Recover expired claim" pendingLabel="Recovering…" disabled={disabled || state?.ok === true}/><ResultMessage state={state}/></form> }
export default function OperatorTaskControls({ record, serverSeed, authoritativeTaskVersion }: Props) { const router = useRouter(); const successNoticeRef = useRef<HTMLParagraphElement>(null); const [lifecycle,setLifecycle] = useState(()=>createOperatorLifecycle(authoritativeTaskVersion, serverSeed)); useEffect(()=>setLifecycle(s=>reconcileOperatorLifecycle(s,{authoritativeTaskVersion,serverSeed})),[authoritativeTaskVersion,serverSeed]); useLayoutEffect(()=>{ if (!lifecycle.successLocked) return; successNoticeRef.current?.focus(); const refreshTimer = window.setTimeout(()=>{ router.refresh() },0); return () => window.clearTimeout(refreshTimer) },[lifecycle.successLocked,router]); const onResult = useMemo(()=> (state: State) => { if (state === null) return; if (state.ok === true) { setLifecycle(s=>markOperatorActionSucceeded(s, crypto.randomUUID())); return } setLifecycle(markOperatorActionFailed) },[]); const claimDisabled = isOperatorActionSubmissionDisabled("claim", record, lifecycle.successLocked); const releaseDisabled = isOperatorActionSubmissionDisabled("release", record, lifecycle.successLocked); const progressDisabled = isOperatorActionSubmissionDisabled("progress", record, lifecycle.successLocked); const recoveryDisabled = isOperatorActionSubmissionDisabled("recovery", record, lifecycle.successLocked); return <section className="mt-6 rounded-3xl border border-white/10 bg-white/[0.04] p-5" aria-labelledby="operator-controls"><h2 id="operator-controls" className="text-2xl font-semibold">Operator controls</h2><p className="mt-2 rounded-2xl border border-amber-300/30 bg-amber-950/20 p-3 text-sm text-amber-100">Snapshot action eligibility may change. Every submission is rechecked by the trusted server service before mutation.</p>{lifecycle.successLocked ? <p ref={successNoticeRef} tabIndex={-1} aria-live="polite" className="mt-3 text-sm text-emerald-100">Action accepted. Controls are locked while refreshing the authoritative task snapshot.</p> : null}<div className="mt-4 grid gap-3">{canShowClaimControl(record) ? <ClaimForm key={`claim-${lifecycle.keys.claim}`} record={record} actionKey={lifecycle.keys.claim} disabled={claimDisabled} onResult={onResult}/> : null}{canShowReleaseControl(record) ? <ReleaseForm key={`release-${lifecycle.keys.release}`} record={record} actionKey={lifecycle.keys.release} disabled={releaseDisabled} onResult={onResult}/> : null}{canShowProgressControl(record) ? <ProgressForm key={`progress-${lifecycle.keys.progress}`} record={record} actionKey={lifecycle.keys.progress} disabled={progressDisabled} onResult={onResult}/> : null}{canShowRecoveryControl(record) ? <RecoveryForm key={`recovery-${lifecycle.keys.recovery}`} record={record} actionKey={lifecycle.keys.recovery} disabled={recoveryDisabled} onResult={onResult}/> : null}</div></section> }
