"use client"
import { useEffect, useRef, useState } from "react"
import type { OnlyFansOperatorMediaRecord, OnlyFansOperatorSignedMediaUrl } from "@/lib/creator-publishing-queue/operator-media"

type Preview = Pick<OnlyFansOperatorSignedMediaUrl, "mediaAssetId" | "signedUrl" | "kind" | "mimeType" | "filename"> & { expiresAt: number }
type Props = { platformJobId: string; media: OnlyFansOperatorMediaRecord[] }
const genericError = "Media access is unavailable. Reload and confirm your current claim."
export default function OperatorTaskMedia({ platformJobId, media }: Props) {
  const [previews, setPreviews] = useState<Record<string, Preview>>({})
  const [pending, setPending] = useState<Record<string, "preview" | "download" | undefined>>({})
  const [message, setMessage] = useState("")
  const timers = useRef<Record<string, ReturnType<typeof setTimeout>>>({})
  const clearPreview = (id: string) => { if (timers.current[id]) clearTimeout(timers.current[id]); delete timers.current[id]; setPreviews(p => { const n={...p}; delete n[id]; return n }) }
  useEffect(() => () => { Object.values(timers.current).forEach(clearTimeout); timers.current={}; setPreviews({}) }, [])
  async function requestUrl(item: OnlyFansOperatorMediaRecord, mode: "preview" | "download") {
    const requestStartedAt = Date.now()
    const response = await fetch(`/api/creator-publishing-queue/operator/${encodeURIComponent(platformJobId)}/media/${encodeURIComponent(item.mediaAssetId)}/signed-url?mode=${mode}`, { credentials:"same-origin", cache:"no-store", referrerPolicy:"no-referrer" })
    const data = await response.json().catch(() => null)
    if (!response.ok || !data?.ok || typeof data.value?.signedUrl !== "string" || data.value.signedUrl.length === 0 || !Number.isInteger(data.value.expiresIn) || data.value.expiresIn <= 0 || data.value.expiresIn > 300) throw new Error(genericError)
    return { ...(data.value as OnlyFansOperatorSignedMediaUrl), requestStartedAt } as OnlyFansOperatorSignedMediaUrl & { requestStartedAt: number }
  }
  async function preview(item: OnlyFansOperatorMediaRecord) { clearPreview(item.mediaAssetId); setPending(p=>({...p,[item.mediaAssetId]:"preview"})); setMessage("Loading preview."); try { const result=await requestUrl(item,"preview"); const remainingMs=result.requestStartedAt+result.expiresIn*1000-Date.now(); if (remainingMs <= 0) { clearPreview(item.mediaAssetId); setMessage(genericError); return } const safeRemainingMs=Math.max(0, remainingMs - 250); const expiresAt=Date.now()+safeRemainingMs; setPreviews(p=>({...p,[item.mediaAssetId]:{ mediaAssetId:result.mediaAssetId, signedUrl:result.signedUrl, expiresAt, kind:result.kind, mimeType:result.mimeType, filename:result.filename }})); timers.current[item.mediaAssetId]=setTimeout(()=>clearPreview(item.mediaAssetId), safeRemainingMs); setMessage("Preview ready.") } catch { clearPreview(item.mediaAssetId); setMessage(genericError) } finally { setPending(p=>({...p,[item.mediaAssetId]:undefined})) } }
  async function download(item: OnlyFansOperatorMediaRecord) { setPending(p=>({...p,[item.mediaAssetId]:"download"})); setMessage("Preparing download."); try { const result=await requestUrl(item,"download"); const anchor=document.createElement("a"); anchor.href=result.signedUrl; anchor.download=result.filename; anchor.rel="noopener noreferrer"; anchor.referrerPolicy="no-referrer"; document.body.appendChild(anchor); anchor.click(); anchor.remove(); setMessage("Download started.") } catch { clearPreview(item.mediaAssetId); setMessage(genericError) } finally { setPending(p=>({...p,[item.mediaAssetId]:undefined})) } }
  if (media.length === 0) return <section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-zinc-300"><h2 className="text-lg font-semibold text-white">Media</h2><p className="mt-2">No media is attached to this package.</p></section>
  return <section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="text-lg font-semibold text-white">Media</h2><p className="mt-2 text-sm text-zinc-300">Preview and download links are short-lived and require your current claim.</p><p aria-live="polite" tabIndex={-1} className="mt-3 text-sm text-cyan-100">{message}</p><ul className="mt-4 grid gap-4">{media.map(item => { const p=previews[item.mediaAssetId]; return <li key={item.mediaAssetId} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{item.displayOrder}. {item.filename}</p><p className="text-sm text-zinc-400">{item.kind} · {item.mimeType}</p></div><div className="flex gap-2"><button disabled={pending[item.mediaAssetId] === "preview"} onClick={()=>preview(item)} className="rounded-lg border border-cyan-300/40 px-3 py-2 text-sm disabled:opacity-50">Preview</button><button disabled={pending[item.mediaAssetId] === "download"} onClick={()=>download(item)} className="rounded-lg border border-fuchsia-300/40 px-3 py-2 text-sm disabled:opacity-50">Download</button></div></div>{p ? <div className="mt-4">{p.kind === "image" ? <img src={p.signedUrl} alt={`Preview ${item.displayOrder}: ${p.filename}`} loading="lazy" referrerPolicy="no-referrer" className="max-h-96 rounded-lg"/> : <video src={p.signedUrl} controls preload="metadata" playsInline aria-label={`Preview ${item.displayOrder}: ${p.filename}`} className="max-h-96 rounded-lg"/>}</div> : null}</li> })}</ul></section>
}
