"use client"
import { useActionState, useEffect, useMemo, useRef, useState } from "react"
import { useFormStatus } from "react-dom"
import { useRouter } from "next/navigation"
import { supabaseBrowser } from "@/lib/supabase"
import { ONLYFANS_COMPLETION_APPROVED_REASONS, ONLYFANS_COMPLETION_ALLOWED_MIME_TYPES, ONLYFANS_COMPLETION_MAX_BYTES, type CompletionResult, type CompletionSuccess } from "@/lib/creator-publishing-queue/operator-completion/types"
import { completeOnlyFansManualPostAction } from "./completionActions"
type Props={ platformJobId:string; serverSeed:string }
type UploadDisplay={ uploadIntentId:string; intentExpiresAt:string; credentialUseBy:string|null; status:"pending"|"verified"|"expired" }
type EvidenceState={ activeVerifiedIntentId:string|null; replacementTargetIntentId:string|null; pendingReplacementIntentId:string|null; createRequestKey:string; replacementRequestKey:string; busy:boolean; terminalSuccess:boolean }
function nextLifecycleKey(prefix:string){ return `${prefix}_${crypto.randomUUID()}` }
export function task18CompletionStateAfterExpired(state:EvidenceState, operation:"create"|"replace"):EvidenceState{ return operation==="replace"?{...state,activeVerifiedIntentId:null,pendingReplacementIntentId:null,replacementRequestKey:nextLifecycleKey("replace"),busy:false}:{...state,activeVerifiedIntentId:null,replacementTargetIntentId:null,pendingReplacementIntentId:null,createRequestKey:nextLifecycleKey("create"),busy:false} }
export function task18CompletionStateAfterReplacementReserve(state:EvidenceState,newIntentId:string):EvidenceState{ return {...state,activeVerifiedIntentId:null,pendingReplacementIntentId:newIntentId,busy:true} }
function SubmitButton({disabled}:{disabled:boolean}){ const { pending }=useFormStatus(); return <button type="submit" disabled={disabled||pending} className="rounded-xl bg-emerald-500 px-4 py-2 text-sm font-semibold text-white disabled:bg-zinc-700">{pending?"Completing…":"Confirm manual OnlyFans completion"}</button> }
async function jsonOrThrow(response:Response){ const text=await response.text(); try { return JSON.parse(text) } catch { throw new Error("Invalid server response") } }
export default function OperatorTaskCompletion({ platformJobId, serverSeed }:Props){
  const router=useRouter(); const [file,setFile]=useState<File|null>(null); const [uploadDisplay,setUploadDisplay]=useState<UploadDisplay|null>(null); const [evidence,setEvidence]=useState<EvidenceState>({activeVerifiedIntentId:null,replacementTargetIntentId:null,pendingReplacementIntentId:null,createRequestKey:`create_${serverSeed}`,replacementRequestKey:`replace_${serverSeed}`,busy:false,terminalSuccess:false}); const [message,setMessage]=useState<string|null>(null); const [state,action]=useActionState<CompletionResult<CompletionSuccess>|null,FormData>(completeOnlyFansManualPostAction as any,null); const successRef=useRef<HTMLParagraphElement>(null); const completeKey=useMemo(()=>`complete_${serverSeed}`,[serverSeed]);
  useEffect(()=>()=>setUploadDisplay(null),[]);
  useEffect(()=>{ if(state?.ok){ setEvidence(s=>({...s,terminalSuccess:true})); setUploadDisplay(null); successRef.current?.focus(); const t=window.setTimeout(()=>router.refresh(),300); return()=>window.clearTimeout(t) } if(state?.ok===false) setMessage(state.message) },[state,router]);
  async function verifyIntent(uploadIntentId:string){ const v=await fetch(`/api/creator-publishing-queue/operator/${encodeURIComponent(platformJobId)}/completion-evidence/${encodeURIComponent(uploadIntentId)}/verify`,{ method:"POST" }); const verifiedJson=await jsonOrThrow(v); if(!verifiedJson.ok) throw new Error(verifiedJson.message||"Verification failed."); setEvidence(s=>({...s,activeVerifiedIntentId:verifiedJson.data.uploadIntentId,replacementTargetIntentId:null,pendingReplacementIntentId:null,busy:false})); setMessage("Proof image verified.") }
  async function allocate(){
    if(!file || evidence.busy || evidence.terminalSuccess) return; const operation: "create"|"replace" = evidence.replacementTargetIntentId ? "replace" : "create"; const target=evidence.replacementTargetIntentId; setEvidence(s=>({...s,busy:true,activeVerifiedIntentId:operation==="replace"?null:s.activeVerifiedIntentId})); setMessage(null); setUploadDisplay(null);
    try {
      const requestKey=operation==="create"?evidence.createRequestKey:evidence.replacementRequestKey; const res=await fetch(`/api/creator-publishing-queue/operator/${encodeURIComponent(platformJobId)}/completion-evidence/upload-intent`,{ method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ operation, mimeType:file.type, sizeBytes:file.size, requestKey, ...(operation==="replace"&&target?{replacesUploadIntentId:target}:{}) }) });
      const json=await jsonOrThrow(res); if(!json.ok) throw new Error(json.message||"Upload intent failed."); const data=json.data as {uploadIntentId:string; bucket:string; path:string; token:string|null; intentExpiresAt:string; credentialUseBy:string|null; status:"pending"|"verified"|"expired"}; setUploadDisplay({uploadIntentId:data.uploadIntentId,intentExpiresAt:data.intentExpiresAt,credentialUseBy:data.credentialUseBy,status:data.status}); if(operation==="replace") setEvidence(s=>task18CompletionStateAfterReplacementReserve(s,data.uploadIntentId));
      if(data.status==="verified"){ setEvidence(s=>({...s,activeVerifiedIntentId:data.uploadIntentId,replacementTargetIntentId:null,pendingReplacementIntentId:null,busy:false})); setMessage("Proof image already verified."); return }
      if(data.status==="expired"){ setEvidence(s=>task18CompletionStateAfterExpired(s,operation)); throw new Error("Upload intent expired. Start a new upload lifecycle and try again.") }
      if(!data.token) throw new Error("Upload credential was not issued.");
      const supabase=supabaseBrowser(); let uploadBucket:string|null=data.bucket; let uploadPath:string|null=data.path; let uploadToken:string|null=data.token; const uploadPromise=supabase.storage.from(uploadBucket).uploadToSignedUrl(uploadPath,uploadToken,file); uploadBucket=null; uploadPath=null; uploadToken=null; const uploaded=await uploadPromise; setUploadDisplay(null);
      if(uploaded.error){ try { await verifyIntent(data.uploadIntentId); return } catch { throw new Error("Upload failed. Retry keeps the same replacement target and request key.") } }
      await verifyIntent(data.uploadIntentId);
    } catch(e:any){ setUploadDisplay(null); setEvidence(s=>({...s,busy:false})); setMessage(e?.message||"Upload or verification failed. You can retry safely.") }
  }
  const badFile=file && (!ONLYFANS_COMPLETION_ALLOWED_MIME_TYPES.includes(file.type as any)||file.size>ONLYFANS_COMPLETION_MAX_BYTES); const replacing=Boolean(evidence.replacementTargetIntentId); const locked=evidence.terminalSuccess; const completionEnabled=Boolean(evidence.activeVerifiedIntentId)&&!evidence.busy&&!locked;
  return <section className="mt-6 rounded-3xl border border-emerald-300/20 bg-emerald-950/10 p-5" aria-labelledby="manual-completion"><h2 id="manual-completion" className="text-2xl font-semibold">Manual completion</h2><p className="mt-2 text-sm text-emerald-100">Upload one proof screenshot, then provide either the canonical OnlyFans post URL or an approved no-URL reason.</p><div className="mt-4 space-y-3"><input type="file" accept={ONLYFANS_COMPLETION_ALLOWED_MIME_TYPES.join(",")} disabled={locked||evidence.busy} onChange={e=>{setFile(e.target.files?.[0]??null);setUploadDisplay(null); if(!evidence.busy && evidence.activeVerifiedIntentId){ setEvidence(s=>({...s,replacementTargetIntentId:s.activeVerifiedIntentId,pendingReplacementIntentId:null})) }}} />{badFile?<p className="text-sm text-amber-100">Use JPEG, PNG or WebP up to 10 MiB.</p>:null}<button type="button" disabled={!file||!!badFile||locked||evidence.busy} onClick={()=>allocate()} className="rounded-xl border border-emerald-300/40 px-4 py-2 text-sm disabled:opacity-50">{evidence.busy?"Working…":replacing?"Replace and verify proof":"Upload and verify proof"}</button>{uploadDisplay?.credentialUseBy?<p className="text-xs text-zinc-300">Transient upload credential active until {new Date(uploadDisplay.credentialUseBy).toLocaleTimeString()}.</p>:null}{message?<p tabIndex={-1} aria-live="polite" className="text-sm text-cyan-100">{message}</p>:null}<form action={action} className="grid gap-3"><input type="hidden" name="platformJobId" value={platformJobId}/><input type="hidden" name="uploadIntentId" value={completionEnabled?evidence.activeVerifiedIntentId??"":""}/><input type="hidden" name="idempotencyKey" value={completeKey}/><label className="text-sm">Final OnlyFans URL<input name="finalPostUrl" disabled={locked} className="mt-1 w-full rounded bg-black/40 p-2 text-white" placeholder="https://onlyfans.com/123456/username"/></label><label className="text-sm">No URL reason<select name="noUrlReason" disabled={locked} className="mt-1 w-full rounded bg-black/40 p-2 text-white"><option value="">URL provided</option>{ONLYFANS_COMPLETION_APPROVED_REASONS.map(r=><option key={r} value={r}>{r}</option>)}</select></label><SubmitButton disabled={!completionEnabled}/>{state?.ok===false?<p aria-live="polite" className="text-sm text-amber-100">{state.message}</p>:null}{state?.ok?<p ref={successRef} tabIndex={-1} aria-live="polite" className="text-sm text-emerald-100">Completion accepted. Refreshing.</p>:null}</form></div></section>
}
