import type { OnlyFansOperatorDisplayBucket, OnlyFansOperatorListRecord, OnlyFansOperatorProgressState, OperatorMutationResult } from "@/lib/creator-publishing-queue/operator-queue"

export type OperatorActionName = "claim" | "release" | "progress" | "recovery"
export type OperatorActionKeys = Record<OperatorActionName, string>
export type OperatorLifecycle = { authoritativeTaskVersion: string; serverSeed: string; activeSeed: string; successLocked: boolean; actionState: "idle" | "failed" | "uncertain" | "succeeded"; keys: OperatorActionKeys }
export const operatorBucketOrder: readonly OnlyFansOperatorDisplayBucket[] = ["claimed_by_me","needs_attention","overdue","due_now","due_soon","upcoming","ready_but_unscheduled"]
export const bucketDisplayLabel = (b: OnlyFansOperatorDisplayBucket) => ({claimed_by_me:"Claimed by me",needs_attention:"Needs attention",overdue:"Overdue",due_now:"Due now",due_soon:"Due soon",upcoming:"Upcoming",ready_but_unscheduled:"Ready but unscheduled"})[b]
export const attentionReasonDisplayText = (r: OnlyFansOperatorListRecord["attentionReasons"][number]) => ({expired_claim_recovery_available:"Expired claim can be recovered",claimed_by_another_operator:"Claimed by another operator",authorization_or_safety_attention:"Authorization or safety attention required",task_no_longer_eligible:"Task no longer eligible"})[r]
export const queueStateLabel = (s: string) => ({ready_for_handoff:"Ready for handoff",scheduled_internally:"Scheduled internally",awaiting_operator:"Awaiting operator",due_now:"Due now",claimed:"Claimed"} as Record<string,string>)[s] ?? s
export const progressStateLabel = (s: OnlyFansOperatorProgressState) => ({not_started:"Not started",preparing:"Preparing",prepared:"Prepared",handoff_ready:"Handoff ready"})[s]
export const formatOperatorTimestamp = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : "Not provided"
export const canShowClaimControl = (r: Pick<OnlyFansOperatorListRecord,"bucket"|"readOnly">) => r.readOnly === false && ["due_now","overdue","ready_but_unscheduled"].includes(r.bucket)
export const canShowReleaseControl = (r: Pick<OnlyFansOperatorListRecord,"bucket">) => r.bucket === "claimed_by_me"
export const getNextProgressState = (s: OnlyFansOperatorProgressState): OnlyFansOperatorProgressState | null => s === "not_started" ? "preparing" : s === "preparing" ? "prepared" : s === "prepared" ? "handoff_ready" : null
export const canShowProgressControl = (r: Pick<OnlyFansOperatorListRecord,"bucket"|"progressState">) => r.bucket === "claimed_by_me" && getNextProgressState(r.progressState) !== null
export const canShowRecoveryControl = (r: Pick<OnlyFansOperatorListRecord,"bucket"|"attentionReasons">) => r.bucket === "needs_attention" && r.attentionReasons.includes("expired_claim_recovery_available")
export function buildAuthoritativeTaskVersion(r: Pick<OnlyFansOperatorListRecord,"platformJobId"|"queueStatus"|"progressState"|"progressRevision"|"claimExpiresAt"|"bucket"|"readOnly"|"attentionReasons">) { return JSON.stringify({platformJobId:r.platformJobId,queueStatus:r.queueStatus,progressState:r.progressState,progressRevision:r.progressRevision,claimExpiresAt:r.claimExpiresAt,bucket:r.bucket,readOnly:r.readOnly,attentionReasons:[...r.attentionReasons].sort()}) }
export function deriveOperatorActionKeys(seed: string): OperatorActionKeys { return {claim:`${seed}-claim`,release:`${seed}-release`,progress:`${seed}-progress`,recovery:`${seed}-recovery`} }
export const createOperatorLifecycle = (authoritativeTaskVersion: string, serverSeed: string): OperatorLifecycle => ({authoritativeTaskVersion,serverSeed,activeSeed:serverSeed,successLocked:false,actionState:"idle",keys:deriveOperatorActionKeys(serverSeed)})
export function reconcileOperatorLifecycle(s: OperatorLifecycle, p: {authoritativeTaskVersion: string; serverSeed: string}) { if (p.authoritativeTaskVersion !== s.authoritativeTaskVersion || (s.successLocked && p.serverSeed !== s.serverSeed)) return createOperatorLifecycle(p.authoritativeTaskVersion,p.serverSeed); return s }
export function markOperatorActionFailed(s: OperatorLifecycle): OperatorLifecycle { return {...s, actionState:"failed"} }
export function markOperatorActionUncertain(s: OperatorLifecycle): OperatorLifecycle { return {...s, actionState:"uncertain"} }
export function markOperatorActionSucceeded(s: OperatorLifecycle, nextSeed: string): OperatorLifecycle { return {...s, activeSeed:nextSeed, successLocked:true, actionState:"succeeded", keys:deriveOperatorActionKeys(nextSeed)} }
export function coerceProgressRevisionTransportValue(value: unknown) { if (typeof value !== "string" || !/^(0|[1-9][0-9]*)$/.test(value)) return value; const n = Number.parseInt(value,10); return Number.isSafeInteger(n) ? n : value }
export function formDataToForwardedObject(formData: FormData, convertProgressRevision = false): Record<string, unknown> { const out: Record<string, unknown> = {}; for (const [key,value] of formData.entries()) { if (key.startsWith("$ACTION_")) continue; out[key] = convertProgressRevision && key === "expectedProgressRevision" ? coerceProgressRevisionTransportValue(value) : value } return out }
export function trustedSuccessRevalidationPaths(result: OperatorMutationResult<{platformJobId: string}>): string[] { return result.ok === true ? ["/creator/publishing-queue/operator","/creator/publishing-queue",`/creator/publishing-queue/operator/${result.data.platformJobId}`] : [] }
