import { deepFreezePolicy, type PlatformPolicy } from "./schema"

export const fanvuePolicy = deepFreezePolicy({
  platform: "fanvue", display_name: "Fanvue", mode: "direct_api", enabled_for_queue: false,
  policy_version: "fanvue-reference-2026-07-10-v1", policy_effective_date: "2026-08-18",
  source_references: [
    { label: "Fanvue: Is AI content allowed on Fanvue?", url: "https://help.fanvue.com/en/articles/9538738-is-ai-content-allowed-on-fanvue", retrieved_or_verified_date: "2026-08-18" },
    { label: "Fanvue: What is an AI-Generated model?", url: "https://help.fanvue.com/en/articles/9538752-what-is-an-ai-generated-model", retrieved_or_verified_date: "2026-08-18" },
    { label: "Fanvue platform registry", internal_path: "lib/autopost/platformRegistry.ts" },
  ],
  core_rule: "Fanvue permits fully AI-generated creator models, including entirely fictional synthetic personas. The verified human account owner and the generated persona are separate concepts; a Fanvue AI persona does not have to resemble the verified account owner.",
  disclosure_policy: {
    disclosure_required_for_ai: true,
    allowed_signifiers: [],
    default_disclosure: null,
    disclosure_position: "not_applicable",
    disclosure_removable: false,
    copy_caption_must_include_disclosure: false,
    disclosure_cures_prohibited_ai: false,
    notes: ["Fanvue requires clear and prominent disclosure that AI-generated media is not real. Fanvue states this may be provided in the profile bio, content caption, or as a watermark; Sirens Forge must not assume caption text is the only valid disclosure mechanism."],
  },
  ai_policy: {
    allowed: ["fully AI-generated content", "fully synthetic fictional AI personas unrelated to the verified account owner's appearance", "AI creator models that resemble the verified account owner", "AI-generated models customized for a separate niche or brand"],
    requires: ["verified human account owner/KYC", "clear and prominent AI disclosure through a Fanvue-accepted mechanism", "authorization and verification when a real person's body or likeness is used"],
    hard_blocked: ["unauthorized real-person likeness or body", "stolen or reposted third-party content without authorization", "AI media intended to deceive users into believing the synthetic persona is a real person"],
    manual_review: ["deepfake or face-swap involving a real person", "ambiguous real-person provenance", "unclear AI disclosure state"],
  },
  creator_verification_policy: { required: true, requirements: ["The human Fanvue account owner must satisfy Fanvue account/KYC requirements. This verification does not require the AI persona to match the account owner's likeness."] },
  co_performer_policy: { required: true, requirements: ["When a real person is depicted, obtain the required authorization/verification. A wholly synthetic fictional persona is not a co-performer and does not need to match the account owner."] },
  blocked_categories: ["unauthorized real-person likeness/body", "stolen third-party content", "deceptive AI impersonation", "missing required AI disclosure"],
  manual_review_categories: ["real-person deepfake/face-swap", "ambiguous real-person provenance", "unclear AI disclosure"],
  allowed_categories: ["fully synthetic fictional AI persona", "creator-likeness AI persona", "AI niche persona", "direct Fanvue publishing through the connected account"],
  handoff_checklist: [],
  operator_attestation: "Fanvue is a direct API destination and is not routed through the Creator Publishing Queue manual handoff path.",
  posted_confirmation: "Fanvue direct publishing remains governed by the connected provider integration and the platform-specific Fanvue compliance path.",
  disclaimers: ["Fanvue creator verification identifies the human account owner; it is not a requirement that a fully synthetic AI persona resemble that human."],
  capabilities: { direct_posting: true, manual_handoff: false, native_scheduling: false, internal_scheduling: false, text_posts: true, image_posts: true, video_posts: true, ppv_or_locked_posts: false, visibility_controls: false, provider_post_id: true, platform_credentials: true, platform_sessions: false, browser_automation: false, unofficial_api: false, dm_automation: false, fan_interaction_automation: false, remote_post_verification: false, final_url_human_entry: false, proof_screenshot_optional: false },
  forbidden_capabilities: ["manual queue routing", "manual handoff mode", "treating human KYC as a persona-likeness requirement"],
  reference_only: true,
  integration_notes: ["Do not route Fanvue through the manual queue.", "Do not require a Fanvue synthetic persona to resemble the verified account owner.", "Keep OnlyFans likeness rules isolated to the OnlyFans policy path.", "Do not activate public/live Fanvue controls from policy metadata alone."],
} as const satisfies PlatformPolicy)
