\set ON_ERROR_STOP on
create schema pass4a_test;
create function pass4a_test.image_request(p_count integer) returns jsonb language sql immutable as $$select jsonb_build_object('prompt','authoritative prompt','negative_prompt','authoritative negative','body_presentation','athletic','identity_id','20000000-0000-4000-8000-000000000001','width',768,'height',1024,'steps',31,'cfg',6.5,'seed',42,'output_count',p_count)$$;
create function pass4a_test.asset(p_job uuid,p_ordinal integer,p_suffix text default '.png') returns jsonb language sql immutable as $$select jsonb_build_object('ordinal',p_ordinal,'bucket','private-test','object_key','creator-generations/'||p_job::text||'/'||p_ordinal||p_suffix,'mime_type','image/png','size_bytes',8,'sha256',repeat((p_ordinal+1)::text,64))$$;

-- Every finalizer is service-role-only; helpers and compute tables remain unavailable.
do $$ declare signature text; begin
 foreach signature in array array['finalize_image_compute_job(uuid,uuid,uuid,jsonb)','finalize_recovered_image_compute_job(uuid,uuid,uuid,uuid,jsonb,bigint,bigint,text)','finalize_trainer_compute_job(uuid,uuid,uuid,text,text)','finalize_recovered_trainer_compute_job(uuid,uuid,uuid,uuid,text,text,bigint,bigint,text)'] loop
  assert not has_function_privilege('public','public.'||signature,'execute'); assert not has_function_privilege('anon','public.'||signature,'execute'); assert not has_function_privilege('authenticated','public.'||signature,'execute'); assert has_function_privilege('service_role','public.'||signature,'execute');
 end loop;
 assert not has_function_privilege('service_role','public.finalize_durable_image_product(public.compute_jobs,public.compute_job_attempts,jsonb,bigint)','execute');
 assert not has_table_privilege('service_role','public.compute_jobs','update'); assert not has_table_privilege('service_role','public.compute_job_attempts','update'); assert not has_table_privilege('service_role','public.compute_cost_ledger','insert');
 assert (select relrowsecurity from pg_class where oid='public.compute_jobs'::regclass); assert (select relrowsecurity from pg_class where oid='public.compute_job_attempts'::regclass);
end$$;

-- Normal Image: generic bypass, authority/evidence failures, canonical metadata and one-output replay.
do $$ declare j uuid; a uuid; l uuid; assets jsonb; product jsonb; begin
 select job_id into j from public.submit_compute_job('10000000-0000-4000-8000-000000000001','image','normal-one',repeat('1',64),pass4a_test.image_request(1),'standard'); assets:=jsonb_build_array(pass4a_test.asset(j,0));
 select job_id,attempt_id,lease_token into j,a,l from public.claim_compute_job('image','normal-one-worker'); perform public.compute_worker_transition(j,a,l,'start');
 begin perform public.finalize_image_compute_job(j,gen_random_uuid(),l,assets); raise exception 'wrong attempt accepted'; exception when others then assert sqlerrm like '%IMAGE_FINALIZATION_AUTHORITY_MISMATCH%'; end;
 begin perform public.finalize_image_compute_job(j,a,gen_random_uuid(),assets); raise exception 'wrong lease accepted'; exception when others then assert sqlerrm like '%IMAGE_FINALIZATION_AUTHORITY_MISMATCH%'; end;
 begin perform public.finalize_image_compute_job(j,a,l,assets); raise exception 'missing dispatch accepted'; exception when others then assert sqlerrm like '%IMAGE_EXECUTION_EVIDENCE_REQUIRED%'; end;
 perform public.authorize_compute_dispatch(j,a,l,100); perform public.begin_compute_provider_dispatch(j,a,l); perform public.mark_compute_provider_dispatch(j,a,l,'normal-image-op');
 begin perform public.finalize_image_compute_job(j,a,l,assets); raise exception 'missing actual accepted'; exception when others then assert sqlerrm like '%ACTUAL_COST_REQUIRED%'; end;
 perform public.record_compute_actual_cost(j,a,l,0,17);
 begin perform public.compute_worker_transition(j,a,l,'success'); raise exception 'generic Image success bypassed'; exception when others then assert sqlerrm like '%WORKLOAD_FINALIZATION_REQUIRED%'; end;
 update public.compute_jobs set lease_expires_at=now()-interval '1 second' where id=j; begin perform public.finalize_image_compute_job(j,a,l,assets); raise exception 'expired lease accepted'; exception when others then assert sqlerrm like '%IMAGE_FINALIZATION_AUTHORITY_MISMATCH%'; end; update public.compute_jobs set lease_expires_at=now()+interval '1 hour' where id=j;
 begin perform public.finalize_image_compute_job(j,a,l,jsonb_build_array(jsonb_set(assets->0,'{object_key}',to_jsonb('outside.png'::text)))); raise exception 'outside namespace accepted'; exception when others then assert sqlerrm like '%IMAGE_OBJECT_NAMESPACE_INVALID%'; end;
 begin perform public.finalize_image_compute_job(j,a,l,jsonb_build_array(assets->0||jsonb_build_object('owner_id',gen_random_uuid()))); raise exception 'owner evidence accepted'; exception when others then assert sqlerrm like '%IMAGE_ASSET_EVIDENCE_INVALID%'; end;
 product:=public.finalize_image_compute_job(j,a,l,assets); assert product->>'generation_id'=j::text; assert (select state='succeeded' and result_reference=product from public.compute_jobs where id=j);
 assert (select prompt='authoritative prompt' and negative_prompt='authoritative negative' and lora_used='20000000-0000-4000-8000-000000000001' and body_type='athletic' and steps=31 and cfg_scale=6.5 and seed=42 and width=768 and height=1024 and processing_time_ms=17 and metadata=jsonb_build_object('private_creator_media',true,'policy_version',1,'output_count',1) from public.generations where id=j);
 assert public.finalize_image_compute_job(j,a,l,assets)=product;
 begin perform public.finalize_image_compute_job(j,a,l,jsonb_build_array(jsonb_set(assets->0,'{sha256}',to_jsonb(repeat('f',64))))); raise exception 'conflicting replay accepted'; exception when others then assert sqlerrm like '%IMAGE_FINALIZATION_REPLAY_CONFLICT%'; end;
end$$;

-- Four-output exact ordering plus output-count, missing/noncontiguous/duplicate failures.
do $$ declare j uuid; a uuid; l uuid; good jsonb; begin
 select job_id into j from public.submit_compute_job('10000000-0000-4000-8000-000000000002','image','normal-four',repeat('2',64),pass4a_test.image_request(4),'standard');
 good:=jsonb_build_array(pass4a_test.asset(j,3),pass4a_test.asset(j,1),pass4a_test.asset(j,0),pass4a_test.asset(j,2)); select job_id,attempt_id,lease_token into j,a,l from public.claim_compute_job('image','four-worker'); perform public.compute_worker_transition(j,a,l,'start'); perform public.authorize_compute_dispatch(j,a,l,100); perform public.begin_compute_provider_dispatch(j,a,l); perform public.mark_compute_provider_dispatch(j,a,l,'four-op'); perform public.record_compute_actual_cost(j,a,l,1,20);
 begin perform public.finalize_image_compute_job(j,a,l,jsonb_build_array(pass4a_test.asset(j,0))); raise exception 'count mismatch accepted'; exception when others then assert sqlerrm like '%IMAGE_OUTPUT_COUNT_MISMATCH%'; end;
 begin perform public.finalize_image_compute_job(j,a,l,jsonb_build_array(pass4a_test.asset(j,0),pass4a_test.asset(j,1),pass4a_test.asset(j,2),pass4a_test.asset(j,2))); raise exception 'duplicate accepted'; exception when others then assert sqlerrm like '%IMAGE_OUTPUT_ORDINALS_INVALID%'; end;
 begin perform public.finalize_image_compute_job(j,a,l,jsonb_build_array(pass4a_test.asset(j,0),pass4a_test.asset(j,1),pass4a_test.asset(j,2),pass4a_test.asset(j,4))); raise exception 'noncontiguous accepted'; exception when others then assert sqlerrm ~ 'IMAGE_ASSET_EVIDENCE_INVALID|IMAGE_OUTPUT_ORDINALS_INVALID'; end;
 perform public.finalize_image_compute_job(j,a,l,good); assert (select array_agg(ordinal order by ordinal)=array[0,1,2,3]::smallint[] from public.generation_assets where generation_id=j);
end$$;

-- A private-object conflict rolls back canonical generation and terminal success together.
do $$ declare j uuid; a uuid; l uuid; assets jsonb; begin
 select job_id into j from public.submit_compute_job('10000000-0000-4000-8000-000000000003','image','atomic-conflict',repeat('3',64),pass4a_test.image_request(1),'standard'); assets:=jsonb_build_array(pass4a_test.asset(j,0));
 insert into public.private_storage_objects(owner_id,storage_class,bucket,object_key,mime_type,size_bytes,sha256) values('10000000-0000-4000-8000-000000000003','creator_generation','private-test','creator-generations/'||j||'/0.png','image/png',8,repeat('f',64));
 select job_id,attempt_id,lease_token into j,a,l from public.claim_compute_job('image','conflict-worker'); perform public.compute_worker_transition(j,a,l,'start'); perform public.authorize_compute_dispatch(j,a,l,100); perform public.begin_compute_provider_dispatch(j,a,l); perform public.mark_compute_provider_dispatch(j,a,l,'conflict-op'); perform public.record_compute_actual_cost(j,a,l,1,2);
 begin perform public.finalize_image_compute_job(j,a,l,assets); raise exception 'private conflict accepted'; exception when others then assert sqlerrm like '%PRIVATE_STORAGE_OBJECT_CONFLICT%'; end;
 assert (select state='running' from public.compute_jobs where id=j); assert not exists(select 1 from public.generations where id=j); assert not exists(select 1 from public.generation_assets where generation_id=j);
end$$;

-- Recovery Image permits dispatch uncertainty/no operation ref, requires exact live authority, settles zero once, and replays exactly.
do $$ declare j uuid; a uuid; l uuid; rt uuid; rl uuid; assets jsonb; product jsonb; begin
 update public.compute_jobs set available_at=now()+interval '1 day' where state='queued'; select job_id into j from public.submit_compute_job('10000000-0000-4000-8000-000000000001','image','recovered-image',repeat('4',64),pass4a_test.image_request(1),'standard'); assets:=jsonb_build_array(pass4a_test.asset(j,0));
 select job_id,attempt_id,lease_token into j,a,l from public.claim_compute_job('image','uncertain-worker'); perform public.compute_worker_transition(j,a,l,'start'); perform public.authorize_compute_dispatch(j,a,l,100); perform public.begin_compute_provider_dispatch(j,a,l); update public.compute_jobs set lease_expires_at=now()-interval '1 second' where id=j; perform public.recover_stale_compute_jobs(); select recovery_token,recovery_lease_token into rt,rl from public.claim_compute_recovery('image','image-reconciler') where job_id=j;
 begin perform public.reconcile_compute_recovery(j,a,rt,rl,'succeeded',false,null,null,0,9,null); raise exception 'generic recovery bypassed'; exception when others then assert sqlerrm like '%WORKLOAD_FINALIZATION_REQUIRED%'; end;
 begin perform public.finalize_recovered_image_compute_job(j,a,gen_random_uuid(),rl,assets,0,9,null); raise exception 'wrong token accepted'; exception when others then assert sqlerrm like '%IMAGE_RECOVERY_AUTHORITY_MISMATCH%'; end;
 begin perform public.finalize_recovered_image_compute_job(j,a,rt,gen_random_uuid(),assets,0,9,null); raise exception 'wrong recovery lease accepted'; exception when others then assert sqlerrm like '%IMAGE_RECOVERY_AUTHORITY_MISMATCH%'; end;
 update public.compute_job_attempts set recovery_lease_expires_at=now()-interval '1 second' where id=a; begin perform public.finalize_recovered_image_compute_job(j,a,rt,rl,assets,0,9,null); raise exception 'expired recovery lease accepted'; exception when others then assert sqlerrm like '%IMAGE_RECOVERY_AUTHORITY_MISMATCH%'; end; update public.compute_job_attempts set recovery_lease_expires_at=now()+interval '1 hour' where id=a;
 product:=public.finalize_recovered_image_compute_job(j,a,rt,rl,assets,0,9,null); assert product->>'generation_id'=j::text; assert (select state='succeeded' from public.compute_jobs where id=j); assert (select count(*)=1 from public.compute_cost_ledger where attempt_id=a and kind='actual' and amount_micros=0);
 assert public.finalize_recovered_image_compute_job(j,a,rt,rl,assets,0,9,null)=product;
 begin perform public.finalize_recovered_image_compute_job(j,a,rt,rl,assets,1,9,null); raise exception 'recovery cost replay accepted'; exception when others then assert sqlerrm like '%IMAGE_FINALIZATION_REPLAY_CONFLICT%'; end;
end$$;

-- Normal Trainer result, canonical artifact key, authority, atomic completion and replay.
do $$ declare j uuid; a uuid; l uuid; key text:='loras/20000000-0000-4000-8000-000000000001/final.safetensors'; begin
 select job_id into j from public.submit_trainer_compute_job('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','trainer-normal',repeat('5',64),'{"identity_id":"20000000-0000-4000-8000-000000000001"}','standard','datasets','approved/a');
 select job_id,attempt_id,lease_token into j,a,l from public.claim_compute_job('trainer','trainer-worker'); assert (select status='training' and started_at is null from public.user_loras where id='20000000-0000-4000-8000-000000000001'); perform public.compute_worker_transition(j,a,l,'start'); assert (select started_at=(select started_at from public.compute_jobs where id=j) from public.user_loras where id='20000000-0000-4000-8000-000000000001');
 begin perform public.finalize_trainer_compute_job(j,gen_random_uuid(),l,'identity-loras',key); raise exception 'wrong Trainer attempt accepted'; exception when others then assert sqlerrm like '%TRAINER_FINALIZATION_AUTHORITY_MISMATCH%'; end; begin perform public.finalize_trainer_compute_job(j,a,gen_random_uuid(),'identity-loras',key); raise exception 'wrong Trainer lease accepted'; exception when others then assert sqlerrm like '%TRAINER_FINALIZATION_AUTHORITY_MISMATCH%'; end; begin perform public.finalize_trainer_compute_job(j,a,l,'identity-loras',key); raise exception 'Trainer missing dispatch accepted'; exception when others then assert sqlerrm like '%TRAINER_EXECUTION_EVIDENCE_REQUIRED%'; end;
 perform public.authorize_compute_dispatch(j,a,l,100); perform public.begin_compute_provider_dispatch(j,a,l); perform public.mark_compute_provider_dispatch(j,a,l,'trainer-op'); begin perform public.finalize_trainer_compute_job(j,a,l,'identity-loras',key); raise exception 'Trainer missing actual accepted'; exception when others then assert sqlerrm like '%ACTUAL_COST_REQUIRED%'; end; perform public.record_compute_actual_cost(j,a,l,0,10);
 update public.compute_jobs set lease_expires_at=now()-interval '1 second' where id=j; begin perform public.finalize_trainer_compute_job(j,a,l,'identity-loras',key); raise exception 'expired Trainer lease accepted'; exception when others then assert sqlerrm like '%TRAINER_FINALIZATION_AUTHORITY_MISMATCH%'; end; update public.compute_jobs set lease_expires_at=now()+interval '1 hour' where id=j;
 begin perform public.compute_worker_transition(j,a,l,'success'); raise exception 'generic Trainer bypassed'; exception when others then assert sqlerrm like '%WORKLOAD_FINALIZATION_REQUIRED%'; end;
 begin perform public.finalize_trainer_compute_job(j,a,l,'identity-loras','unsafe.safetensors'); raise exception 'unsafe artifact accepted'; exception when others then assert sqlerrm like '%TRAINER_ARTIFACT_REFERENCE_INVALID%'; end;
 assert public.finalize_trainer_compute_job(j,a,l,'identity-loras',key)='succeeded'; assert (select result_reference=jsonb_build_object('result_id','20000000-0000-4000-8000-000000000001'::uuid) from public.compute_jobs where id=j);
 assert (select status='completed' and progress=100 and artifact_r2_key=key and trigger_token='sf20000000' from public.user_loras where id='20000000-0000-4000-8000-000000000001'); assert public.finalize_trainer_compute_job(j,a,l,'identity-loras',key)='succeeded';
 begin perform public.finalize_trainer_compute_job(j,a,l,'other-bucket',key); raise exception 'artifact replay accepted'; exception when others then assert sqlerrm like '%TRAINER_FINALIZATION_REPLAY_CONFLICT%'; end;
end$$;

-- Recovery Trainer authority, zero-cost settlement, creator result and exact replay.
do $$ declare j uuid; a uuid; l uuid; rt uuid; rl uuid; key text:='loras/20000000-0000-4000-8000-000000000002/final.safetensors'; begin
 select job_id into j from public.submit_trainer_compute_job('10000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000002','trainer-recovery',repeat('6',64),'{"identity_id":"20000000-0000-4000-8000-000000000002"}','standard','datasets','approved/b'); select job_id,attempt_id,lease_token into j,a,l from public.claim_compute_job('trainer','trainer-recovery-worker'); perform public.compute_worker_transition(j,a,l,'start'); perform public.authorize_compute_dispatch(j,a,l,100); perform public.begin_compute_provider_dispatch(j,a,l); update public.compute_jobs set lease_expires_at=now()-interval '1 second' where id=j; perform public.recover_stale_compute_jobs(); select recovery_token,recovery_lease_token into rt,rl from public.claim_compute_recovery('trainer','trainer-reconciler') where job_id=j;
 begin perform public.reconcile_compute_recovery(j,a,rt,rl,'succeeded',false,null,null,0,11,null); raise exception 'generic Trainer recovery bypassed'; exception when others then assert sqlerrm like '%WORKLOAD_FINALIZATION_REQUIRED%'; end;
 begin perform public.finalize_recovered_trainer_compute_job(j,a,gen_random_uuid(),rl,'identity-loras',key,0,11,null); raise exception 'wrong recovery token accepted'; exception when others then assert sqlerrm like '%TRAINER_RECOVERY_AUTHORITY_MISMATCH%'; end;
 begin perform public.finalize_recovered_trainer_compute_job(j,a,rt,gen_random_uuid(),'identity-loras',key,0,11,null); raise exception 'wrong Trainer recovery lease accepted'; exception when others then assert sqlerrm like '%TRAINER_RECOVERY_AUTHORITY_MISMATCH%'; end;
 assert public.finalize_recovered_trainer_compute_job(j,a,rt,rl,'identity-loras',key,0,11,null)='succeeded'; assert (select result_reference=jsonb_build_object('result_id','20000000-0000-4000-8000-000000000002'::uuid) from public.compute_jobs where id=j); assert (select count(*)=1 from public.compute_cost_ledger where attempt_id=a and kind='actual' and amount_micros=0); assert public.finalize_recovered_trainer_compute_job(j,a,rt,rl,'identity-loras',key,0,11,null)='succeeded';
 begin perform public.finalize_recovered_trainer_compute_job(j,a,rt,rl,'identity-loras',key,0,12,null); raise exception 'runtime replay accepted'; exception when others then assert sqlerrm like '%TRAINER_FINALIZATION_REPLAY_CONFLICT%'; end;
end$$;

-- Projection maps every state, never invents claim start/completion, and ignores stale bindings.
do $$ declare j uuid; newer uuid:=gen_random_uuid(); start_time timestamptz:=clock_timestamp(); begin
 insert into public.compute_jobs(owner_id,workload,state,idempotency_key,request_fingerprint,request_payload,priority_class,max_attempts) values('10000000-0000-4000-8000-000000000001','trainer','queued','projection-all',repeat('7',64),'{"identity_id":"20000000-0000-4000-8000-000000000001"}','standard',2) returning id into j; update public.user_loras set training_job_id=j::text,status='draft',started_at=null,completed_at=null where id='20000000-0000-4000-8000-000000000001'; update public.compute_jobs set state='queued' where id=j; assert (select status='queued' and progress=0 and started_at is null and completed_at is null from public.user_loras where id='20000000-0000-4000-8000-000000000001');
 update public.compute_jobs set state='claimed',lease_token=gen_random_uuid(),lease_expires_at=now()+interval '1 hour' where id=j; assert (select status='training' and started_at is null from public.user_loras where id='20000000-0000-4000-8000-000000000001'); update public.compute_jobs set state='running',started_at=start_time where id=j; assert (select status='training' and started_at=start_time from public.user_loras where id='20000000-0000-4000-8000-000000000001'); update public.compute_jobs set state='recovering',lease_token=null,lease_expires_at=null where id=j; assert (select status='training' and started_at=start_time from public.user_loras where id='20000000-0000-4000-8000-000000000001'); update public.compute_jobs set state='cancel_requested',lease_token=gen_random_uuid(),lease_expires_at=now()+interval '1 hour' where id=j; assert (select status='training' and started_at=start_time from public.user_loras where id='20000000-0000-4000-8000-000000000001'); update public.compute_jobs set state='failed',safe_error_code='TRAINING_FAILED',terminal_at=now(),lease_token=null,lease_expires_at=null where id=j; assert (select status='failed' and error_message='TRAINING_FAILED' from public.user_loras where id='20000000-0000-4000-8000-000000000001');
 update public.compute_jobs set state='cancelled' where id=j; assert (select status='failed' and error_message='TRAINING_CANCELLED' from public.user_loras where id='20000000-0000-4000-8000-000000000001'); update public.user_loras set artifact_r2_key=null; update public.compute_jobs set state='succeeded' where id=j; assert (select status='failed' and artifact_r2_key is null from public.user_loras where id='20000000-0000-4000-8000-000000000001'); update public.user_loras set training_job_id=newer::text,status='draft'; update public.compute_jobs set state='failed' where id=j; assert (select status='draft' and training_job_id=newer::text from public.user_loras where id='20000000-0000-4000-8000-000000000001');
end$$;

-- Stitch generic success remains available. Pass 4A does not alter Video policy.
do $$ declare j uuid; a uuid; l uuid; video_enabled boolean; begin select enabled into video_enabled from public.compute_scheduler_policies where workload='video'; select job_id into j from public.submit_compute_job('10000000-0000-4000-8000-000000000003','stitch','stitch-generic',repeat('8',64),'{}','standard'); select job_id,attempt_id,lease_token into j,a,l from public.claim_compute_job('stitch','stitch-worker'); perform public.compute_worker_transition(j,a,l,'start'); perform public.authorize_compute_dispatch(j,a,l,100); perform public.begin_compute_provider_dispatch(j,a,l); perform public.mark_compute_provider_dispatch(j,a,l,'stitch-op'); perform public.record_compute_actual_cost(j,a,l,0,1); assert public.compute_worker_transition(j,a,l,'success')='succeeded'; assert (select enabled=video_enabled from public.compute_scheduler_policies where workload='video'); end$$;

drop schema pass4a_test cascade;
