import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs";
const read=(p:string)=>fs.readFileSync(p,"utf8");
const migration=read("supabase/migrations/20260825090000_durable_compute_job_plane.sql");
test("durable gate is server-only, exact true, and defaults off",()=>{const s=read("lib/compute-jobs.ts");assert.match(s,/DURABLE_COMPUTE_JOBS_ENABLED === "true"/);assert.doesNotMatch(read(".env.example"),/NEXT_PUBLIC_DURABLE/);assert.match(read(".env.example"),/DURABLE_COMPUTE_JOBS_ENABLED=false/)});
test("fake process-memory generation plane is absent",()=>{assert.equal(fs.existsSync("lib/generation-jobs.ts"),false);for(const p of ["lib","app","components"])for(const f of walk(p)){const s=read(f);assert.doesNotMatch(s,/placehold\.co|sample-videos\.com|simulateProcessing/)}});
test("image durable path queues product intent before legacy provider execution",()=>{const s=read("app/api/generate/route.ts");assert.match(s,/isDurableComputeJobsEnabled\(\)/);assert.ok(s.indexOf("submitComputeJob")<s.indexOf("buildWorkflow({"));assert.ok(s.indexOf("return NextResponse.json(toCreatorComputeStatus(job), { status: 202 })")<s.indexOf("await sirensApiFetch"));assert.match(s,/output_count: normalized\.batch/);assert.match(s,/identity_id: identityLora/)});
test("canonical schema and safe contract cover required boundaries",()=>{for(const token of ["'trainer','image','video','stitch'","FOR UPDATE SKIP LOCKED".toLowerCase(),"provider_operation_ref","daily_limit_micros","monthly_limit_micros","video_job_limit_micros","recovering"])assert.ok(migration.toLowerCase().includes(token.toLowerCase()),token);const safe=read("lib/compute-jobs.ts").split("toCreatorComputeStatus")[1];for(const secret of ["provider_operation","worker_ref","lease_token","cost_micros","priority_class"])assert.doesNotMatch(safe,new RegExp(secret))});
test("video remains unavailable and client submits one 1-4 output durable job",()=>{assert.match(read("app/api/generate_video/route.ts"),/VIDEO_GENERATION_UNAVAILABLE/);const client=read("app/generate/page.tsx");assert.match(client,/batch: runCount/);assert.match(client,/res\.status !== 202/);assert.match(read("app/api/generate/route.ts"),/Math\.max\(1, Math\.min\(4/)});
function walk(dir:string):string[]{return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.name.startsWith(".")?[]:e.isDirectory()?walk(`${dir}/${e.name}`):/\.(ts|tsx|js|mjs)$/.test(e.name)?[`${dir}/${e.name}`]:[])}
