\set ON_ERROR_STOP on
-- Structural, security, boundary, and submission truth on the disposable Pass 4C database.
do $$ begin
 assert to_regclass('public.video_projects') is not null;
 assert to_regclass('public.video_project_segments') is not null;
 assert (select relrowsecurity and relforcerowsecurity from pg_class where oid='public.video_projects'::regclass);
 assert (select relrowsecurity and relforcerowsecurity from pg_class where oid='public.video_project_segments'::regclass);
 assert not has_table_privilege('service_role','public.video_projects','select');
 assert not has_table_privilege('service_role','public.video_project_segments','select');
 assert has_function_privilege('service_role','public.submit_video_project_compute_jobs(uuid,uuid,uuid,text,text,jsonb,text)','execute');
 assert not has_function_privilege('authenticated','public.submit_video_project_compute_jobs(uuid,uuid,uuid,text,text,jsonb,text)','execute');
 assert not has_function_privilege('service_role','public.finalize_video_segments(public.compute_jobs,public.compute_job_attempts,jsonb)','execute');
 assert pg_get_functiondef('public.compute_worker_transition(uuid,uuid,uuid,text,text,jsonb)'::regprocedure) like '%image%trainer%video%stitch%WORKLOAD_FINALIZATION_REQUIRED%';
 assert pg_get_functiondef('public.reconcile_compute_recovery(uuid,uuid,uuid,uuid,text,boolean,text,jsonb,bigint,bigint,text)'::regprocedure) like '%image%trainer%video%stitch%WORKLOAD_FINALIZATION_REQUIRED%';
end$$;

do $$ begin
 begin perform public.submit_compute_job('10000000-0000-4000-8000-000000000001','video','blocked',repeat('a',64),'{}','standard'); raise exception 'generic Video accepted'; exception when others then assert sqlerrm like '%WORKLOAD_SUBMISSION_REQUIRED%'; end;
 begin perform public.submit_compute_job('10000000-0000-4000-8000-000000000001','stitch','blocked',repeat('a',64),'{}','standard'); raise exception 'generic Stitch accepted'; exception when others then assert sqlerrm like '%WORKLOAD_SUBMISSION_REQUIRED%'; end;
end$$;

update public.user_loras set status='completed',artifact_r2_bucket='private-bucket',artifact_r2_key='loras/20000000-0000-4000-8000-000000000001/final.safetensors' where id='20000000-0000-4000-8000-000000000001';
insert into public.compute_scheduler_policies(workload,max_global_active,lease_seconds,stale_seconds,max_attempts,og_priority_seconds,spend_hold_seconds,enabled) values
 ('image',2,60,120,2,0,60,true),('video',2,60,120,3,120,60,true),('stitch',2,60,120,4,0,60,true) on conflict(workload) do update set max_attempts=excluded.max_attempts,enabled=true;
-- Preserve the original Image-only finalizer boundary after broadening the shared object table.
select public.finalize_private_generation('30000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001',
 '{"prompt":"source","body_type":"default","steps":20,"cfg_scale":7,"seed":1,"width":1080,"height":1080,"processing_time_ms":1,"metadata":{"private_creator_media":true}}',
 '[{"owner_id":"10000000-0000-4000-8000-000000000001","ordinal":0,"kind":"image","storage_class":"creator_generation","bucket":"image-private","object_key":"creator-generations/30000000-0000-4000-8000-000000000001/source.png","mime_type":"image/png","size_bytes":1000,"sha256":"1111111111111111111111111111111111111111111111111111111111111111"}]');
do $$ begin
 begin perform public.finalize_private_generation('30000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001','{"prompt":"bad"}','[{"owner_id":"10000000-0000-4000-8000-000000000001","ordinal":0,"kind":"image","storage_class":"creator_generation","bucket":"image-private","object_key":"bad.mp4","mime_type":"video/mp4","size_bytes":1000,"sha256":"2222222222222222222222222222222222222222222222222222222222222222"}]'); raise exception 'MP4 accepted by image finalizer'; exception when others then assert sqlerrm like '%PRIVATE_GENERATION_ASSET_INVALID%'; end;
 begin perform public.finalize_private_generation('30000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000001','{"prompt":"bad"}',jsonb_build_array(jsonb_build_object('owner_id','10000000-0000-4000-8000-000000000001','ordinal',0,'kind','image','storage_class','creator_generation','bucket','image-private','object_key','too-big.png','mime_type','image/png','size_bytes',52428801,'sha256',repeat('3',64)))); raise exception 'oversize image accepted'; exception when others then assert sqlerrm like '%PRIVATE_GENERATION_ASSET_INVALID%'; end;
end$$;

insert into public.user_loras(id,user_id,status,artifact_r2_bucket,artifact_r2_key) values
 ('20000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002','completed','private-bucket','loras/other/final.safetensors'),
 ('20000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000001','draft',null,null);

do $$ declare source_id uuid:=(select id from public.generation_assets where generation_id='30000000-0000-4000-8000-000000000001'); begin
 -- Duration boundaries and derived segment counts.
 perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'std-15',repeat('4',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":15}','standard');
 perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'og-20',repeat('5',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":20}','og');
 perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'og-25',repeat('6',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":25}','og');
 assert (select segment_count=2 from public.video_projects where idempotency_key='std-15'); assert (select bool_and(segment_count=3) from public.video_projects where idempotency_key in('og-20','og-25'));
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'std-9',repeat('7',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":9}','standard'); raise exception 'std 9 accepted'; exception when others then assert sqlerrm like '%VIDEO_DURATION_TIER_INVALID%'; end;
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'std-16',repeat('8',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":16}','standard'); raise exception 'std 16 accepted'; exception when others then assert sqlerrm like '%VIDEO_DURATION_TIER_INVALID%'; end;
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'og-19',repeat('9',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":19}','og'); raise exception 'og 19 accepted'; exception when others then assert sqlerrm like '%VIDEO_DURATION_TIER_INVALID%'; end;
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'og-26',repeat('a',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":26}','og'); raise exception 'og 26 accepted'; exception when others then assert sqlerrm like '%VIDEO_DURATION_TIER_INVALID%'; end;
 -- Identity and source posture.
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000002',null,'wrong-owner',repeat('b',64),'{"identity_id":"20000000-0000-4000-8000-000000000002","mode":"text_to_video","requested_duration_seconds":10}','standard'); raise exception 'wrong identity accepted'; exception when others then assert sqlerrm like '%VIDEO_IDENTITY_NOT_READY%'; end;
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000003',null,'incomplete',repeat('c',64),'{"identity_id":"20000000-0000-4000-8000-000000000003","mode":"text_to_video","requested_duration_seconds":10}','standard'); raise exception 'incomplete identity accepted'; exception when others then assert sqlerrm like '%VIDEO_IDENTITY_NOT_READY%'; end;
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',source_id,'text-source',repeat('d',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10}','standard'); raise exception 'text source accepted'; exception when others then assert sqlerrm like '%VIDEO_SOURCE_MODE_INVALID%'; end;
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'image-missing',repeat('e',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"image_to_video","requested_duration_seconds":10}','standard'); raise exception 'missing image source accepted'; exception when others then assert sqlerrm like '%VIDEO_SOURCE_REQUIRED%'; end;
 perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',source_id,'image-valid',repeat('f',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"image_to_video","requested_duration_seconds":10}','standard');
 update public.generations set status='failed' where id='30000000-0000-4000-8000-000000000001';
 begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',source_id,'image-incomplete',repeat('0',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"image_to_video","requested_duration_seconds":10}','standard'); raise exception 'incomplete source accepted'; exception when others then assert sqlerrm like '%VIDEO_SOURCE_INVALID%'; end;
 update public.generations set status='completed' where id='30000000-0000-4000-8000-000000000001';
end$$;

select * from public.submit_compute_job('10000000-0000-4000-8000-000000000001','image','generic-image-preserved',repeat('3',64),'{}','standard');
create temporary table submitted as select project_id from public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'video-project-a',repeat('a',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10,"fps":30,"prompt":"test","body_type":"default"}','standard') \gset

do $$ begin
 assert (select segment_count=2 and target_fps=30 and target_min_short_edge=1080 from public.video_projects where id=(select project_id from submitted));
 assert (select count(*)=1 from public.compute_jobs where workload='video' and request_payload->>'project_id'=(select project_id::text from submitted));
 assert (select count(*)=1 from public.compute_jobs where workload='stitch' and request_payload->>'project_id'=(select project_id::text from submitted));
 assert (select max_attempts=3 from public.compute_jobs where workload='video' and request_payload->>'project_id'=(select project_id::text from submitted));
 assert (select max_attempts=4 from public.compute_jobs where workload='stitch' and request_payload->>'project_id'=(select project_id::text from submitted));
 assert not exists(select 1 from public.claim_compute_job('stitch','worker'));
end$$;
-- Exercise normal authority, contiguous segment persistence, Stitch dependency, and canonical product.
update public.compute_jobs set state='running',attempt_count=1,lease_token='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',lease_expires_at=clock_timestamp()+interval '5 minutes',started_at=clock_timestamp()
 where id=(select video_job_id from public.video_projects where id=(select project_id from submitted));
insert into public.compute_job_attempts(job_id,ordinal,lease_token,worker_ref,lease_expires_at,started_at,provider_dispatch_intent_at,provider_dispatched_at,provider_operation_ref,actual_cost_micros,runtime_ms)
 select video_job_id,1,'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','video-test',clock_timestamp()+interval '5 minutes',clock_timestamp(),clock_timestamp(),clock_timestamp(),'opaque-video-operation',0,5000 from public.video_projects where id=(select project_id from submitted);
do $$ declare v public.video_projects;a public.compute_job_attempts;assets jsonb;bad jsonb; begin
 select * into v from public.video_projects where id=(select project_id from submitted); select * into a from public.compute_job_attempts where job_id=v.video_job_id;
 assets:=jsonb_build_array(jsonb_build_object('ordinal',0,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/0/segment-0.mp4','mime_type','video/mp4','size_bytes',1000,'sha256',repeat('1',64)),jsonb_build_object('ordinal',1,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/1/segment-1.mp4','mime_type','video/mp4','size_bytes',1001,'sha256',repeat('2',64)));
 assert (public.video_compute_manifest(v.video_job_id,a.id,a.lease_token)->>'project_id')=v.id::text;
 begin perform public.video_compute_manifest(v.video_job_id,a.id,gen_random_uuid()); raise exception 'wrong manifest lease accepted'; exception when others then assert sqlerrm like '%VIDEO_MANIFEST_AUTHORITY_MISMATCH%'; end;
 begin perform public.finalize_video_compute_job(v.video_job_id,a.id,gen_random_uuid(),assets); raise exception 'wrong lease accepted'; exception when others then assert sqlerrm like '%VIDEO_FINALIZATION_AUTHORITY_MISMATCH%'; end;
 bad:=jsonb_set(assets,'{0,ordinal}','"0"'); begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,bad); raise exception 'string ordinal accepted'; exception when others then assert sqlerrm like '%VIDEO_SEGMENT_EVIDENCE_INVALID%'; end;
 bad:=jsonb_set(assets,'{0,size_bytes}','1.5'); begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,bad); raise exception 'fraction size accepted'; exception when others then assert sqlerrm like '%VIDEO_SEGMENT_EVIDENCE_INVALID%'; end;
 bad:=jsonb_set(assets,'{0,bucket}','123'); begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,bad); raise exception 'numeric bucket accepted'; exception when others then assert sqlerrm like '%VIDEO_SEGMENT_EVIDENCE_INVALID%'; end;
 bad:=jsonb_set(assets,'{0,mime_type}','"video/webm"'); begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,bad); raise exception 'webm accepted'; exception when others then assert sqlerrm like '%VIDEO_SEGMENT_EVIDENCE_INVALID%'; end;
 bad:=jsonb_set(assets,'{0,sha256}','"ABC"'); begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,bad); raise exception 'bad hash accepted'; exception when others then assert sqlerrm like '%VIDEO_SEGMENT_EVIDENCE_INVALID%'; end;
 bad:=jsonb_set(assets,'{0,object_key}',to_jsonb('creator-video-projects/'||v.id||'/segments/9/bad.mp4')); begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,bad); raise exception 'bad namespace accepted'; exception when others then assert sqlerrm like '%VIDEO_OBJECT_NAMESPACE_INVALID%'; end;
 bad:=jsonb_set(assets,'{1,bucket}','"other-bucket"'); begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,bad); raise exception 'mixed bucket accepted'; exception when others then assert sqlerrm like '%VIDEO_BUCKET_CONFLICT%'; end;
end$$;
select public.finalize_video_compute_job(v.video_job_id,a.id,'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',jsonb_build_array(
 jsonb_build_object('ordinal',0,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/0/segment-0.mp4','mime_type','video/mp4','size_bytes',1000,'sha256',repeat('1',64)),
 jsonb_build_object('ordinal',1,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/1/segment-1.mp4','mime_type','video/mp4','size_bytes',1001,'sha256',repeat('2',64))))
 from public.video_projects v join public.compute_job_attempts a on a.job_id=v.video_job_id where v.id=(select project_id from submitted);
do $$ begin assert (select count(*)=2 from public.video_project_segments where project_id=(select project_id from submitted)); assert not exists(select 1 from public.generation_assets where generation_id=(select project_id from submitted)); end$$;
-- Exact terminal replay validates without writing; missing state and fingerprints never self-heal.
select public.finalize_video_compute_job(v.video_job_id,a.id,'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',jsonb_build_array(
 jsonb_build_object('ordinal',0,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/0/segment-0.mp4','mime_type','video/mp4','size_bytes',1000,'sha256',repeat('1',64)),
 jsonb_build_object('ordinal',1,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/1/segment-1.mp4','mime_type','video/mp4','size_bytes',1001,'sha256',repeat('2',64))))
 from public.video_projects v join public.compute_job_attempts a on a.job_id=v.video_job_id where v.id=(select project_id from submitted);
create temporary table saved_segment as select * from public.video_project_segments where project_id=(select project_id from submitted) and ordinal=1;
delete from public.video_project_segments where project_id=(select project_id from submitted) and ordinal=1;
do $$ declare v public.video_projects;a public.compute_job_attempts;assets jsonb;begin select * into v from public.video_projects where id=(select project_id from submitted);select * into a from public.compute_job_attempts where job_id=v.video_job_id;assets:=jsonb_build_array(jsonb_build_object('ordinal',0,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/0/segment-0.mp4','mime_type','video/mp4','size_bytes',1000,'sha256',repeat('1',64)),jsonb_build_object('ordinal',1,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/1/segment-1.mp4','mime_type','video/mp4','size_bytes',1001,'sha256',repeat('2',64)));begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,assets);raise exception 'missing segment repaired';exception when others then assert sqlerrm like '%VIDEO_FINALIZATION_REPLAY_CONFLICT%';end;assert not exists(select 1 from public.video_project_segments where project_id=v.id and ordinal=1);end$$;
insert into public.video_project_segments select * from saved_segment;
create temporary table saved_video_telemetry as select id,internal_telemetry from public.compute_job_attempts where job_id=(select video_job_id from public.video_projects where id=(select project_id from submitted));
update public.compute_job_attempts set internal_telemetry=internal_telemetry-'workload_finalization_fingerprint' where id=(select id from saved_video_telemetry);
do $$ declare v public.video_projects;a public.compute_job_attempts;assets jsonb;begin select * into v from public.video_projects where id=(select project_id from submitted);select * into a from public.compute_job_attempts where job_id=v.video_job_id;assets:=jsonb_build_array(jsonb_build_object('ordinal',0,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/0/segment-0.mp4','mime_type','video/mp4','size_bytes',1000,'sha256',repeat('1',64)),jsonb_build_object('ordinal',1,'bucket','video-private','object_key','creator-video-projects/'||v.id||'/segments/1/segment-1.mp4','mime_type','video/mp4','size_bytes',1001,'sha256',repeat('2',64)));begin perform public.finalize_video_compute_job(v.video_job_id,a.id,a.lease_token,assets);raise exception 'missing fingerprint repaired';exception when others then assert sqlerrm like '%VIDEO_FINALIZATION_REPLAY_CONFLICT%';end;assert a.internal_telemetry->>'workload_finalization_fingerprint' is null;end$$;
update public.compute_job_attempts a set internal_telemetry=s.internal_telemetry from saved_video_telemetry s where a.id=s.id;

create temporary table stitch_claim as select * from public.claim_compute_job('stitch','stitch-test');
update public.compute_jobs set state='running',started_at=clock_timestamp() where id=(select job_id from stitch_claim);
update public.compute_job_attempts set started_at=clock_timestamp(),provider_dispatch_intent_at=clock_timestamp(),provider_dispatched_at=clock_timestamp(),provider_operation_ref='opaque-stitch-operation',actual_cost_micros=0,runtime_ms=6000 where id=(select attempt_id from stitch_claim);
do $$ declare c record;e jsonb;bad jsonb;begin select * into c from stitch_claim;e:=jsonb_build_object('asset',jsonb_build_object('bucket','video-private','object_key','creator-video-projects/'||(select project_id from submitted)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2000,'sha256',repeat('3',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000);
 assert (public.stitch_compute_manifest(c.job_id,c.attempt_id,c.lease_token)->>'project_id')=(select project_id::text from submitted);
 begin perform public.stitch_compute_manifest(c.job_id,c.attempt_id,gen_random_uuid());raise exception 'wrong Stitch manifest lease accepted';exception when others then assert sqlerrm like '%STITCH_MANIFEST_AUTHORITY_MISMATCH%';end;
 bad:=jsonb_set(e,'{duration_ms}','"10000"');begin perform public.finalize_stitch_compute_job(c.job_id,c.attempt_id,c.lease_token,bad);raise exception 'string duration accepted';exception when others then assert sqlerrm like '%STITCH_OUTPUT_INVALID%';end;
 bad:=jsonb_set(e,'{asset,size_bytes}','"2000"');begin perform public.finalize_stitch_compute_job(c.job_id,c.attempt_id,c.lease_token,bad);raise exception 'string size accepted';exception when others then assert sqlerrm like '%STITCH_OUTPUT_INVALID%';end;
 bad:=jsonb_set(e,'{height}','1079');begin perform public.finalize_stitch_compute_job(c.job_id,c.attempt_id,c.lease_token,bad);raise exception 'short edge accepted';exception when others then assert sqlerrm like '%STITCH_OUTPUT_INVALID%';end;
 bad:=jsonb_set(e,'{fps_millihz}','29899');begin perform public.finalize_stitch_compute_job(c.job_id,c.attempt_id,c.lease_token,bad);raise exception 'low fps accepted';exception when others then assert sqlerrm like '%STITCH_OUTPUT_INVALID%';end;
 bad:=jsonb_set(e,'{fps_millihz}','30101');begin perform public.finalize_stitch_compute_job(c.job_id,c.attempt_id,c.lease_token,bad);raise exception 'high fps accepted';exception when others then assert sqlerrm like '%STITCH_OUTPUT_INVALID%';end;
 bad:=jsonb_set(e,'{duration_ms}','16000');begin perform public.finalize_stitch_compute_job(c.job_id,c.attempt_id,c.lease_token,bad);raise exception 'duration accepted';exception when others then assert sqlerrm like '%STITCH_OUTPUT_INVALID%';end;
end$$;
select public.finalize_stitch_compute_job((select job_id from stitch_claim),(select attempt_id from stitch_claim),(select lease_token from stitch_claim),jsonb_build_object('asset',jsonb_build_object('bucket','video-private','object_key','creator-video-projects/'||(select project_id from submitted)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2000,'sha256',repeat('3',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000));
do $$ begin
 assert (select completed_at is not null from public.video_projects where id=(select project_id from submitted));
 assert (select count(*)=1 from public.generations where id=(select project_id from submitted) and job_type='video' and status='completed' and image_url is null and r2_bucket is null and r2_key is null and runpod_job_id is null);
 assert (select count(*)=1 from public.generation_assets where generation_id=(select project_id from submitted) and kind='video' and ordinal=0);
 assert (select count(*)=2 from public.video_project_segments where project_id=(select project_id from submitted));
 assert (select result_reference=jsonb_build_object('project_id',video_projects.id,'generation_id',video_projects.id,'asset_ids',compute_jobs.result_reference->'asset_ids') from public.compute_jobs join public.video_projects on stitch_job_id=compute_jobs.id where video_projects.id=(select project_id from submitted));
end$$;

-- Exact Stitch replay is validation-only.
select public.finalize_stitch_compute_job((select job_id from stitch_claim),(select attempt_id from stitch_claim),(select lease_token from stitch_claim),jsonb_build_object('asset',jsonb_build_object('bucket','video-private','object_key','creator-video-projects/'||(select project_id from submitted)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2000,'sha256',repeat('3',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000));
update public.generations set body_type='poisoned' where id=(select project_id from submitted);
do $$ begin begin perform public.finalize_stitch_compute_job((select job_id from stitch_claim),(select attempt_id from stitch_claim),(select lease_token from stitch_claim),jsonb_build_object('asset',jsonb_build_object('bucket','video-private','object_key','creator-video-projects/'||(select project_id from submitted)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2000,'sha256',repeat('3',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000));raise exception 'poisoned generation repaired';exception when others then assert sqlerrm like '%VIDEO_GENERATION_CONFLICT%';end;assert (select body_type='poisoned' from public.generations where id=(select project_id from submitted));end$$;
update public.generations set body_type='default' where id=(select project_id from submitted);
create temporary table saved_final_asset as select * from public.generation_assets where generation_id=(select project_id from submitted);
delete from public.generation_assets where generation_id=(select project_id from submitted);
do $$ begin begin perform public.finalize_stitch_compute_job((select job_id from stitch_claim),(select attempt_id from stitch_claim),(select lease_token from stitch_claim),jsonb_build_object('asset',jsonb_build_object('bucket','video-private','object_key','creator-video-projects/'||(select project_id from submitted)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2000,'sha256',repeat('3',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000));raise exception 'missing final asset repaired';exception when others then assert sqlerrm like '%STITCH_FINALIZATION_REPLAY_CONFLICT%';end;assert not exists(select 1 from public.generation_assets where generation_id=(select project_id from submitted));end$$;
insert into public.generation_assets select * from saved_final_asset;
create temporary table saved_stitch_telemetry as select id,internal_telemetry from public.compute_job_attempts where id=(select attempt_id from stitch_claim);
update public.compute_job_attempts set internal_telemetry=internal_telemetry-'workload_finalization_fingerprint' where id=(select id from saved_stitch_telemetry);
do $$ begin begin perform public.finalize_stitch_compute_job((select job_id from stitch_claim),(select attempt_id from stitch_claim),(select lease_token from stitch_claim),jsonb_build_object('asset',jsonb_build_object('bucket','video-private','object_key','creator-video-projects/'||(select project_id from submitted)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2000,'sha256',repeat('3',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000));raise exception 'missing Stitch fingerprint repaired';exception when others then assert sqlerrm like '%STITCH_FINALIZATION_REPLAY_CONFLICT%';end;assert (select internal_telemetry->>'workload_finalization_fingerprint' is null from public.compute_job_attempts where id=(select attempt_id from stitch_claim));end$$;
update public.compute_job_attempts a set internal_telemetry=s.internal_telemetry from saved_stitch_telemetry s where a.id=s.id;
create temporary table completed_replay as select * from public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'video-project-a',repeat('a',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10,"fps":30,"prompt":"test","body_type":"default"}','standard');
do $$ begin assert (select creator_status='completed' and not can_cancel from completed_replay);end$$;

-- Recovery manifests/finalizers preserve exact recovery authority, cost, and replay contracts.
create temporary table recovered_project as select project_id from public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'recovered-project',repeat('b',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10,"prompt":"recovered","body_type":"recovered-body"}','standard');
update public.compute_jobs set state='recovering',attempt_count=1 where id=(select video_job_id from public.video_projects where id=(select project_id from recovered_project));
insert into public.compute_job_attempts(job_id,ordinal,lease_token,worker_ref,lease_expires_at,started_at,provider_dispatch_intent_at,provider_dispatched_at,provider_operation_ref,actual_cost_micros,runtime_ms,recovery_token,recovery_lease_token,recovery_worker_ref,recovery_heartbeat_at,recovery_lease_expires_at)
 select video_job_id,1,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','lost-video',clock_timestamp()-interval '1 minute',clock_timestamp(),clock_timestamp(),clock_timestamp(),'recovered-video-op',7,5000,'cccccccc-cccc-4ccc-8ccc-cccccccccccc','dddddddd-dddd-4ddd-8ddd-dddddddddddd','video-recovery',clock_timestamp(),clock_timestamp()+interval '5 minutes' from public.video_projects where id=(select project_id from recovered_project);
do $$ declare v public.video_projects;a public.compute_job_attempts;begin select * into v from public.video_projects where id=(select project_id from recovered_project);select * into a from public.compute_job_attempts where job_id=v.video_job_id;assert (public.recovered_video_compute_manifest(v.video_job_id,a.id,a.recovery_token,a.recovery_lease_token)->>'project_id')=v.id::text;begin perform public.recovered_video_compute_manifest(v.video_job_id,a.id,gen_random_uuid(),a.recovery_lease_token);raise exception 'wrong recovery token accepted';exception when others then assert sqlerrm like '%VIDEO_RECOVERY_AUTHORITY_MISMATCH%';end;end$$;
select public.finalize_recovered_video_compute_job(v.video_job_id,a.id,a.recovery_token,a.recovery_lease_token,jsonb_build_array(jsonb_build_object('ordinal',0,'bucket','video-recovered','object_key','creator-video-projects/'||v.id||'/segments/0/a.mp4','mime_type','video/mp4','size_bytes',1100,'sha256',repeat('4',64)),jsonb_build_object('ordinal',1,'bucket','video-recovered','object_key','creator-video-projects/'||v.id||'/segments/1/b.mp4','mime_type','video/mp4','size_bytes',1101,'sha256',repeat('5',64))),7,5000,'recovered-video-op') from public.video_projects v join public.compute_job_attempts a on a.job_id=v.video_job_id where v.id=(select project_id from recovered_project);
-- exact recovered Video replay
select public.finalize_recovered_video_compute_job(v.video_job_id,a.id,a.recovery_token,'dddddddd-dddd-4ddd-8ddd-dddddddddddd',jsonb_build_array(jsonb_build_object('ordinal',0,'bucket','video-recovered','object_key','creator-video-projects/'||v.id||'/segments/0/a.mp4','mime_type','video/mp4','size_bytes',1100,'sha256',repeat('4',64)),jsonb_build_object('ordinal',1,'bucket','video-recovered','object_key','creator-video-projects/'||v.id||'/segments/1/b.mp4','mime_type','video/mp4','size_bytes',1101,'sha256',repeat('5',64))),7,5000,'recovered-video-op') from public.video_projects v join public.compute_job_attempts a on a.job_id=v.video_job_id where v.id=(select project_id from recovered_project);
do $$ declare v public.video_projects;a public.compute_job_attempts;begin select * into v from public.video_projects where id=(select project_id from recovered_project);select * into a from public.compute_job_attempts where job_id=v.video_job_id;begin perform public.finalize_recovered_video_compute_job(v.video_job_id,a.id,a.recovery_token,'dddddddd-dddd-4ddd-8ddd-dddddddddddd',jsonb_build_array(jsonb_build_object('ordinal',0,'bucket','video-recovered','object_key','creator-video-projects/'||v.id||'/segments/0/a.mp4','mime_type','video/mp4','size_bytes',1100,'sha256',repeat('4',64)),jsonb_build_object('ordinal',1,'bucket','video-recovered','object_key','creator-video-projects/'||v.id||'/segments/1/b.mp4','mime_type','video/mp4','size_bytes',1101,'sha256',repeat('5',64))),8,5000,'recovered-video-op');raise exception 'recovery cost conflict accepted';exception when others then assert sqlerrm like '%VIDEO_FINALIZATION_REPLAY_CONFLICT%';end;end$$;
create temporary table recovered_stitch_claim as select * from public.claim_compute_job('stitch','lost-stitch');
update public.compute_jobs set state='recovering',lease_token=null,lease_expires_at=null where id=(select job_id from recovered_stitch_claim);
update public.compute_job_attempts set started_at=clock_timestamp(),provider_dispatch_intent_at=clock_timestamp(),provider_dispatched_at=clock_timestamp(),provider_operation_ref='recovered-stitch-op',actual_cost_micros=9,runtime_ms=6000,recovery_token='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',recovery_lease_token='ffffffff-ffff-4fff-8fff-ffffffffffff',recovery_worker_ref='stitch-recovery',recovery_heartbeat_at=clock_timestamp(),recovery_lease_expires_at=clock_timestamp()+interval '5 minutes' where id=(select attempt_id from recovered_stitch_claim);
do $$ begin assert (public.recovered_stitch_compute_manifest((select job_id from recovered_stitch_claim),(select attempt_id from recovered_stitch_claim),'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','ffffffff-ffff-4fff-8fff-ffffffffffff')->>'project_id')=(select project_id::text from recovered_project);begin perform public.recovered_stitch_compute_manifest((select job_id from recovered_stitch_claim),(select attempt_id from recovered_stitch_claim),gen_random_uuid(),'ffffffff-ffff-4fff-8fff-ffffffffffff');raise exception 'wrong Stitch recovery accepted';exception when others then assert sqlerrm like '%STITCH_RECOVERY_AUTHORITY_MISMATCH%';end;end$$;
select public.finalize_recovered_stitch_compute_job((select job_id from recovered_stitch_claim),(select attempt_id from recovered_stitch_claim),'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','ffffffff-ffff-4fff-8fff-ffffffffffff',jsonb_build_object('asset',jsonb_build_object('bucket','video-recovered','object_key','creator-video-projects/'||(select project_id from recovered_project)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2100,'sha256',repeat('6',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000),9,6000,'recovered-stitch-op');
-- exact recovered Stitch replay
select public.finalize_recovered_stitch_compute_job((select job_id from recovered_stitch_claim),(select attempt_id from recovered_stitch_claim),'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','ffffffff-ffff-4fff-8fff-ffffffffffff',jsonb_build_object('asset',jsonb_build_object('bucket','video-recovered','object_key','creator-video-projects/'||(select project_id from recovered_project)||'/final/final.mp4','mime_type','video/mp4','size_bytes',2100,'sha256',repeat('6',64)),'duration_ms',10000,'width',1920,'height',1080,'fps_millihz',30000),9,6000,'recovered-stitch-op');

-- Status precedence and cancellation remain truthful and idempotent.
create temporary table failure_project as select project_id from public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'failure-status',repeat('7',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10}','standard');
update public.video_projects set cancellation_requested_at=clock_timestamp() where id=(select project_id from failure_project);
update public.compute_jobs set state='failed',terminal_at=clock_timestamp(),safe_error_code='TEST_FAILURE' where id=(select video_job_id from public.video_projects where id=(select project_id from failure_project));
do $$ begin assert (select creator_status='failed' from public.creator_video_project_status('10000000-0000-4000-8000-000000000001',(select project_id from failure_project)));assert (select state='failed' and safe_error_code='VIDEO_GENERATION_STAGE_FAILED' from public.compute_jobs where id=(select stitch_job_id from public.video_projects where id=(select project_id from failure_project)));end$$;
create temporary table cancel_project as select project_id from public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'cancel-queued',repeat('8',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10}','standard');
select public.cancel_video_project('10000000-0000-4000-8000-000000000001',(select project_id from cancel_project));
select public.cancel_video_project('10000000-0000-4000-8000-000000000001',(select project_id from cancel_project));
do $$ begin assert (select creator_status='cancelled' and not can_cancel from public.creator_video_project_status('10000000-0000-4000-8000-000000000001',(select project_id from cancel_project)));end$$;

-- Identical submission replays the same safe project; changed fingerprints conflict.
select project_id from public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'video-project-a',repeat('a',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10,"fps":30,"prompt":"test","body_type":"default"}','standard');
do $$ begin begin perform public.submit_video_project_compute_jobs('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',null,'video-project-a',repeat('b',64),'{"identity_id":"20000000-0000-4000-8000-000000000001","mode":"text_to_video","requested_duration_seconds":10}','standard'); raise exception 'conflict accepted'; exception when others then assert sqlerrm like '%IDEMPOTENCY_CONFLICT%'; end; end$$;
