import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { canonicalWarningSnapshot, classifyDatasetDoctorQuality, DATASET_DOCTOR_TRAINING_DECISION_VERSION, sha256Fingerprint, V1_QUALITY_ISSUE_CODES, V1_QUALITY_WARNING_CODES } from "../../../lib/dataset-doctor/training-decision-contract";
import { DATASET_LIMITS } from "../../../lib/dataset-doctor/dataset-limits";
const valid = { dataset_ready: false, dataset_warnings: ["dataset_unbalanced"], dataset_warnings_structured: [], secondary_issues: [], primary_issue: null };

test("capacity supports 30+ while count is never readiness",()=>{assert.equal(DATASET_LIMITS.minimumUploadCount,10);assert.equal(DATASET_LIMITS.maximumUploadCount,50);assert.ok(DATASET_LIMITS.maximumUploadCount>=30);assert.equal(classifyDatasetDoctorQuality(valid,50).state,"overridable");assert.notEqual(classifyDatasetDoctorQuality({dataset_ready:true},50).state,"overridable")});
test("all current Railway quality warning codes are V1 overridable",()=>{for(const code of V1_QUALITY_WARNING_CODES)assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings:[code]},3).state,"overridable",code)});
test("all current Railway issue codes are V1 overridable",()=>{for(const code of V1_QUALITY_ISSUE_CODES){assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings:[],primary_issue:code},3).state,"overridable",code);assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings:[],secondary_issues:[code]},3).state,"overridable",code)}});
test("unknown warnings and issues fail closed",()=>{assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings:["future_safety_code"]},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings:[],primary_issue:"future_issue"},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings:[],secondary_issues:["future_issue"]},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings_structured:[{type:"future_type"}]},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality({...valid,future_safety_evidence:true},3).state,"prohibited")});
test("malformed readiness, structured warnings and blockers fail closed",()=>{for(const dataset_ready of [undefined,null,"false",0])assert.equal(classifyDatasetDoctorQuality({...valid,dataset_ready},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality({...valid,dataset_warnings_structured:["bad"]},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality({...valid,non_overridable_conditions:["anything"]},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality({...valid,non_overridable_conditions:"bad"},3).state,"prohibited");assert.equal(classifyDatasetDoctorQuality(valid,2).state,"prohibited")});
test("ready evidence is fully validated before returning ready",()=>{const ready={...valid,dataset_ready:true,dataset_warnings:[]};assert.equal(classifyDatasetDoctorQuality(ready,0).state,"ready");for(const summary of [{...ready,future_safety_evidence:true},{...ready,non_overridable_conditions:["block"]},{...ready,non_overridable_conditions:"bad"},{...ready,dataset_warnings:["future"]},{...ready,primary_issue:"future"},{...ready,secondary_issues:["future"]},{...ready,dataset_warnings_structured:[{type:"future"}]},{...ready,dataset_warnings:{bad:true}}])assert.equal(classifyDatasetDoctorQuality(summary,3).state,"prohibited");for(const dataset_ready of [undefined,null,"true",1])assert.equal(classifyDatasetDoctorQuality({...ready,dataset_ready},3).state,"prohibited")});
test("snapshot uses authoritative job columns, includes structured warnings, and is deterministic",()=>{const a=canonicalWarningSnapshot({summary:{...valid,dataset_warnings:["too_many_side_profiles","dataset_unbalanced"],dataset_warnings_structured:[{type:"low_resolution_images_present",z:2},{type:"dataset_unbalanced",a:1}],needs_more_images:false,missing_coverage:["wrong"]},needs_more_images:true,missing_coverage:["side","closeup"]});const b=canonicalWarningSnapshot({summary:{...valid,dataset_warnings:["dataset_unbalanced","too_many_side_profiles"],dataset_warnings_structured:[{a:1,type:"dataset_unbalanced"},{z:2,type:"low_resolution_images_present"}]},needs_more_images:true,missing_coverage:["closeup","side"]});assert.deepEqual(a,b);assert.equal(a.needs_more_images,true);assert.deepEqual(a.missing_coverage,["closeup","side"]);assert.ok(Array.isArray(a.dataset_warnings_structured));assert.equal(sha256Fingerprint(a),sha256Fingerprint(b));assert.equal(DATASET_DOCTOR_TRAINING_DECISION_VERSION,"dataset-doctor-training-decision-v1")});
test("source ordering and authority contracts",async()=>{const route=await readFile("app/api/lora/dataset-training-decision/route.ts","utf8"),train=await readFile("app/api/lora/train/route.ts","utf8"),ui=await readFile("app/lora/train/TrainPageClient.tsx","utf8");assert.match(route,/action === "prepare"/);assert.match(route,/action === "confirm"/);assert.match(route,/idempotency-key/);assert.doesNotMatch(route,/\.from\("dataset_doctor_training_decision_receipts"\)\.upsert/);assert.match(route,/prepare_dataset_training_decision_prompt/);assert.match(route,/record_dataset_training_decision_receipt/);assert.doesNotMatch(ui,/dataset_ready !== false/);assert.ok(ui.indexOf('action: "prepare"')<ui.indexOf("setShowTrainAnywayConfirm(true)"));const handler=ui.slice(ui.indexOf("const handleApproveAndStartTraining"),ui.indexOf("const toggleSelectedImage"));const prohibited=handler.indexOf('datasetQualityClassification.state === "prohibited"'),approve=handler.indexOf("approveDatasetDoctorJob");assert.ok(prohibited>=0&&prohibited<approve);assert.match(handler,/datasetQualityClassification.state === "overridable"/);assert.match(ui,/datasetQualityClassification.state === "ready"/);assert.equal((ui.match(/onClick=\{\(\) => handleApproveAndStartTraining\(false\)\}/g)||[]).length>=2,true);assert.match(handler,/handleImproveDataset/);assert.match(handler,/clearPendingSubmission\("sirensforge:pending-dataset-training-decision"/);assert.ok(train.indexOf("DATASET_TRAINING_DECISION_EXECUTION_UNAVAILABLE")<train.indexOf('.update({\n        status: "queued"'));assert.match(train,/classifyDatasetDoctorQuality/);assert.match(train,/qualityClassification.state === "prohibited"/);assert.match(train,/validate_dataset_training_decision_receipt/)});
