import Link from "next/link"
import LegalPageLayout from "@/components/legal/LegalPageLayout"

export default function PrivacyPage() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="August 22, 2026">
      <section><p>This policy explains how Sirens Forge collects, uses, shares, protects, and retains information.</p></section>
      <section><h2 className="text-xl font-semibold">1. Information we collect</h2><ul className="list-disc pl-6 space-y-2"><li>Account, authentication, billing, and subscription information</li><li>Prompts, uploads, references, identity and Twin materials, vault content, and generated content</li><li>Usage, device, browser, IP, security, and system-log data</li><li>Support requests, complaints, removal reports, appeals, and communications</li></ul></section>
      <section><h2 className="text-xl font-semibold">2. How we use information</h2><p>We process the minimum creator data necessary to deliver requested features; authenticate users; manage billing; secure and troubleshoot the service; provide legitimate creator-requested support; conduct safety, NCII, fraud, security, or compliance review; prevent abuse; enforce policy; and satisfy legal obligations.</p></section>
      <section><h2 className="text-xl font-semibold">3. Private creator content and model training</h2><p>Private creator uploads, identity or Twin materials, prompts, and generated content are not used for generalized model training by default. Any future generalized model-training or improvement use of private creator content requires a separate explicit opt-in. We do not treat permission to operate or support the service as that opt-in.</p><p>We never sell creator personal data or creator content. We do not use private creator content to build advertising or marketing profiles.</p></section>
      <section><h2 className="text-xl font-semibold">4. Automated processing and human access</h2><p>Automated processing does not imply casual human browsing of private creator content. Human access is purpose-limited to legitimate circumstances such as creator-requested support, genuine technical troubleshooting, safety or NCII investigation, fraud or security investigation, policy enforcement, or a legal requirement. Access may be restricted or content preserved where needed for those purposes.</p></section>
      <section><h2 className="text-xl font-semibold">5. Service providers and sharing</h2><p>We may use providers for hosting, storage, authentication, payments, AI processing, delivery, communications, security, and support. Provider processing is limited to the minimum information necessary for the assigned purpose. We may also disclose information to respond to valid legal process, investigate abuse, protect safety or security, or support a business transaction, subject to applicable obligations.</p><p>Payment providers process payment details under their own policies. Sirens Forge does not store full payment-card numbers.</p></section>
      <section><h2 className="text-xl font-semibold">6. Cookies and service data</h2><p>We may use cookies, local storage, and similar technologies for authentication, security, preferences, performance, abuse prevention, and platform functionality. Blocking them may affect features.</p></section>
      <section><h2 className="text-xl font-semibold">7. Security</h2><p>We use reasonable technical and organizational safeguards. No internet service, cloud system, AI processor, storage system, or transmission method can be guaranteed completely secure.</p></section>
      <section><h2 className="text-xl font-semibold">8. Retention and deletion requests</h2><p>We keep information only as needed for the purposes described here, including providing the service, maintaining necessary business and billing records, security, fraud prevention, dispute resolution, policy enforcement, backups, and legal obligations. Retention may vary by data and purpose.</p><p>You may contact admin@sirensforge.vip to request deletion of an account or certain stored data. Requests are reviewed through the current manual process and may be limited where continued retention is necessary for the purposes above. This policy does not represent that automated deletion, recovery, export, Recently Deleted, or purge lifecycle controls are currently available.</p></section>
      <section><h2 className="text-xl font-semibold">9. Connected platforms</h2><p>Disconnecting a supported connected platform revokes or deletes its stored access credentials and cancels associated unpublished scheduled jobs where that connection is implemented. It does not remove content already published on an external platform. Applicable platform deletion notices and creator requests are handled subject to minimum necessary legal, fraud-prevention, security, and dispute records; retained exceptions are not used for future publishing or marketing.</p></section>
      <section><h2 className="text-xl font-semibold">10. Rights, safety, and complaints</h2><p>You are responsible for having the rights and consent needed for submitted likenesses and identity materials. To report unauthorized intimate content, use our public <Link className="text-cyan-400 hover:underline" href="/report-intimate-content">intimate-content reporting route</Link>. Other concerns may use our <Link className="text-cyan-400 hover:underline" href="/content-removal">content-removal process</Link>.</p></section>
      <section><h2 className="text-xl font-semibold">11. Adults only and international processing</h2><p>Sirens Forge is for adults aged 18 and older and does not knowingly collect information from minors. Information may be processed in the United States or other locations where purpose-limited providers operate, which may have different data-protection laws.</p></section>
      <section><h2 className="text-xl font-semibold">12. Changes</h2><p>We may update this policy. We will post the updated version and date and provide additional notice or obtain acceptance when required. This statement does not claim a general automated material-policy re-consent system currently exists.</p></section>
      <section><h2 className="text-xl font-semibold">13. Contact</h2><p>Privacy questions and current deletion requests may be sent to admin@sirensforge.vip.</p></section>
    </LegalPageLayout>
  )
}
