import "server-only"
import { supabaseServer } from "../../supabaseServer"
import { getSupabaseAdmin } from "../../supabaseAdmin"
import type { OnlyFansOperatorDetailRecord, OnlyFansOperatorDisplayBucket, OnlyFansOperatorListRecord, OperatorDetailLoaderResult, OperatorListLoaderResult, TrustedOperatorJobTaskProjection } from "./types"
import { ONLYFANS_OPERATOR_BUCKET_ORDER, assignDisplayBucket, isActiveOnlyFansAssistedPreparation } from "./status"
import { OFFICIAL_ONLYFANS_HOME_URL, ONLYFANS_OPERATOR_MANUAL_HANDOFF_INSTRUCTIONS, ONLYFANS_OPERATOR_SAFETY_NOTICE } from "./instructions"
import { actorCanAccessCreator, resolveOperatorJobTask } from "./serviceCore"
import { isValidUuid } from "./validation"
async function authenticatedActorId(): Promise<string | null> { const supabase = await supabaseServer(); const { data, error } = await supabase.auth.getUser(); if (error || !data.user?.id) return null; return data.user.id }
function emptyBuckets(): Record<OnlyFansOperatorDisplayBucket, OnlyFansOperatorListRecord[]> { return { claimed_by_me:[], needs_attention:[], overdue:[], due_now:[], due_soon:[], upcoming:[], ready_but_unscheduled:[] } }
function safeProgress(s: string): any { return ["not_started","preparing","prepared","handoff_ready"].includes(s) ? s : "not_started" }
export function projectOperatorRecord(row: TrustedOperatorJobTaskProjection, actorId: string, capturedAt: string): OnlyFansOperatorListRecord | null { if (!isActiveOnlyFansAssistedPreparation(row)) return null; const b=assignDisplayBucket(row, actorId, capturedAt); return { platformJobId:row.platformJobId, queueTaskId:row.queueTaskId, creatorId:row.creatorId, contentPackageId:row.contentPackageId, platformAccountId:row.platformAccountId, title:row.title ?? null, accountUsername:row.accountUsername ?? null, queueStatus:row.queueStatus as any, progressState:safeProgress(row.operatorProgressState), progressRevision:row.operatorProgressRevision, bucket:b.bucket, attentionReasons:b.reasons, intendedPublishAt:row.intendedPublishAt, operatorDueAt:row.operatorDueAt, claimExpiresAt:row.claimedBy === actorId ? row.claimExpiresAt : null, claimedByMe:row.claimedBy === actorId, readOnly:b.readOnly } }
async function creatorScope(admin: any, actorId: string): Promise<string[]> { const r=await admin.from("creator_publishing_operator_authorizations").select("creator_id").eq("operator_id", actorId).eq("platform", "onlyfans").eq("status", "active").is("revoked_at", null); if (r.error) throw r.error; return Array.from(new Set([actorId, ...((r.data ?? []) as any[]).map(r => r.creator_id).filter(Boolean)])) }
async function enrich(admin: any, row: TrustedOperatorJobTaskProjection): Promise<TrustedOperatorJobTaskProjection> { const [pkg, acct, ver, con, cap] = await Promise.all([admin.from("creator_publishing_content_packages").select("title,caption_body,creator_approval_status,compliance_status,updated_at").eq("id", row.contentPackageId).maybeSingle(), admin.from("creator_platform_accounts").select("platform_username,verification_status").eq("id", row.platformAccountId).maybeSingle(), admin.from("creator_publishing_creator_verifications").select("status").eq("creator_id", row.creatorId).maybeSingle(), admin.from("creator_publishing_ai_twin_consents").select("status,attestation_version,attestation_text_sha256,revoked_at").eq("creator_id", row.creatorId).maybeSingle(), admin.from("creator_publishing_platform_capabilities").select("availability_status,publishing_mode").eq("platform", "onlyfans").maybeSingle()]); return { ...row, title:pkg.data?.title ?? null, captionPreview:pkg.data?.caption_body?.slice?.(0,180) ?? null, creatorApprovalStatus:pkg.data?.creator_approval_status ?? null, complianceStatus:pkg.data?.compliance_status ?? null, accountUsername:acct.data?.platform_username ?? null, accountVerificationStatus:acct.data?.verification_status ?? null, creatorVerificationStatus:ver.data?.status ?? null, consentStatus:con.data?.revoked_at ? "revoked" : con.data?.status ?? null, consentVersion:con.data?.attestation_version ?? null, consentHash:con.data?.attestation_text_sha256 ?? null, capabilityAvailabilityStatus:cap.data?.availability_status ?? null, capabilityPublishingMode:cap.data?.publishing_mode ?? null, sourceFingerprintStale: false } }
export async function loadOnlyFansOperatorQueue(): Promise<OperatorListLoaderResult> { const capturedAt = new Date().toISOString(); const actorId=await authenticatedActorId(); if (!actorId) return {ok:false,code:"sign_in_required",message:"Sign in to view the operator queue."}; try { const admin=getSupabaseAdmin() as any; const creators=await creatorScope(admin,actorId); const jobs=await admin.from("creator_publishing_platform_jobs").select("id").in("creator_id", creators).eq("target_platform", "onlyfans").eq("publishing_mode", "assisted").in("job_state", ["draft","scheduled_internally","awaiting_operator","due_now"]); if (jobs.error) throw jobs.error; const buckets=emptyBuckets(); const records: OnlyFansOperatorListRecord[]=[]; for (const j of (jobs.data ?? []) as any[]) { const resolved=await resolveOperatorJobTask(admin,j.id); if (!resolved) continue; const enriched=await enrich(admin,resolved); const rec=projectOperatorRecord(enriched,actorId,capturedAt); if (!rec) continue; records.push(rec); buckets[rec.bucket].push(rec) } records.sort((a,b)=>ONLYFANS_OPERATOR_BUCKET_ORDER.indexOf(a.bucket)-ONLYFANS_OPERATOR_BUCKET_ORDER.indexOf(b.bucket) || String(a.operatorDueAt ?? "").localeCompare(String(b.operatorDueAt ?? ""))); return {ok:true,capturedAt,records,buckets} } catch { return {ok:false,code:"service_unavailable",message:"The operator queue could not be loaded."} } }
export async function loadOnlyFansOperatorTaskDetail(platformJobId: string): Promise<OperatorDetailLoaderResult> { const capturedAt = new Date().toISOString(); const actorId=await authenticatedActorId(); if (!actorId) return {ok:false,code:"sign_in_required",message:"Sign in to view the operator task."}; if (!isValidUuid(platformJobId)) return {ok:false,code:"task_unavailable",message:"This operator task is unavailable."}; try { const admin=getSupabaseAdmin() as any; const row=await resolveOperatorJobTask(admin,platformJobId); if (!row || !(await actorCanAccessCreator(admin, actorId, row.creatorId))) return {ok:false,code:"task_unavailable",message:"This operator task is unavailable."}; const rec=projectOperatorRecord(await enrich(admin,row), actorId, capturedAt); if (!rec) return {ok:false,code:"task_unavailable",message:"This operator task is unavailable."}; const detail: OnlyFansOperatorDetailRecord = { ...rec, officialOnlyFansUrl: OFFICIAL_ONLYFANS_HOME_URL, manualInstructions: ONLYFANS_OPERATOR_MANUAL_HANDOFF_INSTRUCTIONS, safetyNotice: ONLYFANS_OPERATOR_SAFETY_NOTICE }; return {ok:true,capturedAt,record:detail} } catch { return {ok:false,code:"service_unavailable",message:"The operator task could not be loaded."} } }
