import type { OperatorClaimSuccess, OperatorProgressSuccess, OperatorRecoverySuccess, OperatorReleaseSuccess, OnlyFansOperatorActivePreparationState, OnlyFansOperatorProgressState } from "./types"
import { isValidUuid, ONLYFANS_OPERATOR_PROGRESS_STATES } from "./validation"
const active = new Set(["ready_for_handoff","scheduled_internally","awaiting_operator","due_now","claimed"])
function rec(v: unknown): Record<string, unknown> | null { return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : null }
function reqStr(r: Record<string, unknown>, k: string) { return typeof r[k] === "string" && r[k] ? r[k] as string : null }
function reqUuid(r: Record<string, unknown>, k: string) { const v=reqStr(r,k); return v && isValidUuid(v) ? v : null }
function requireBase(r: Record<string, unknown>, platformJobId: string, queueTaskId: string) { return reqUuid(r,"platform_job_id") === platformJobId && reqUuid(r,"queue_task_id") === queueTaskId }
export function parseClaimRpcResponse(input: unknown, expected: { actorId: string; creatorId: string; platformJobId: string; queueTaskId: string }): OperatorClaimSuccess | null { const r=rec(input); if (!r || r.ok !== true || r.action !== "claim" || !requireBase(r, expected.platformJobId, expected.queueTaskId)) return null; if (reqUuid(r,"creator_id") !== expected.creatorId || reqUuid(r,"operator_id") !== expected.actorId) return null; if (!reqUuid(r,"claim_token")) return null; const exp=reqStr(r,"claim_expires_at"); if (!exp || Number.isNaN(Date.parse(exp)) || r.status !== "claimed") return null; return { action:"claim", platformJobId: expected.platformJobId, queueTaskId: expected.queueTaskId, creatorId: expected.creatorId, operatorId: expected.actorId, status:"claimed", claimExpiresAt: exp, expiredClaimRecovered: r.expired_claim_recovered === true, replacementClaimGranted: r.replacement_claim_granted === true, idempotent: r.idempotent === true } }
export function parseReleaseRpcResponse(input: unknown, expected: { platformJobId: string; queueTaskId: string }): OperatorReleaseSuccess | null { const r=rec(input); const s=reqStr(r ?? {},"status"); if (!r || r.ok !== true || r.action !== "release" || !requireBase(r, expected.platformJobId, expected.queueTaskId) || !s || !active.has(s)) return null; return { action:"release", platformJobId: expected.platformJobId, queueTaskId: expected.queueTaskId, status: s as OnlyFansOperatorActivePreparationState, idempotent: r.idempotent === true } }
export function parseProgressRpcResponse(input: unknown, expected: { platformJobId: string; queueTaskId: string }): OperatorProgressSuccess | null { const r=rec(input); const s=reqStr(r ?? {},"progress_state") as OnlyFansOperatorProgressState | null; if (!r || r.ok !== true || r.action !== "progress_update" || !requireBase(r, expected.platformJobId, expected.queueTaskId) || !s || !ONLYFANS_OPERATOR_PROGRESS_STATES.includes(s)) return null; if (!Number.isInteger(r.progress_revision) || (r.progress_revision as number) < 0) return null; return { action:"progress_update", platformJobId: expected.platformJobId, queueTaskId: expected.queueTaskId, progressState: s, progressRevision: r.progress_revision as number, idempotent: r.idempotent === true } }
export function parseRecoveryRpcResponse(input: unknown, expected: { platformJobId: string; queueTaskId: string }): OperatorRecoverySuccess | null { const r=rec(input); const s=reqStr(r ?? {},"status"); if (!r || r.ok !== true || r.action !== "expired_claim_recovery" || !requireBase(r, expected.platformJobId, expected.queueTaskId) || !s || !active.has(s)) return null; return { action:"expired_claim_recovery", platformJobId: expected.platformJobId, queueTaskId: expected.queueTaskId, status: s as OnlyFansOperatorActivePreparationState, idempotent: r.idempotent === true } }
export function isTrustedRpcSoftFailure(input: unknown): string | null { const r=rec(input); if (!r || r.ok !== false) return null; return typeof r.safe_error_code === "string" ? r.safe_error_code : null }
