import type { OnlyFansOperatorAttentionReason, OnlyFansOperatorDisplayBucket, TrustedOperatorJobTaskProjection } from "./types"
export const ONLYFANS_OPERATOR_DUE_SOON_WINDOW_MS = 24 * 60 * 60 * 1000
export const ONLYFANS_OPERATOR_BUCKET_ORDER: readonly OnlyFansOperatorDisplayBucket[] = ["claimed_by_me","needs_attention","overdue","due_now","due_soon","upcoming","ready_but_unscheduled"]
const terminalJobStates = new Set(["published_direct","confirmed_posted_manual","exported","failed_manual_upload","direct_publish_failed","skipped","blocked","platform_rejected","archived","scheduled_on_platform","awaiting_post_confirmation"])
const terminalTaskStates = new Set(["confirmed_posted_manual","skipped","failed_manual_upload","blocked","archived"])
const activeTaskStates = new Set(["ready_for_handoff","scheduled_internally","awaiting_operator","due_now","claimed"])
export function isActiveOnlyFansAssistedPreparation(row: TrustedOperatorJobTaskProjection): boolean { if (row.targetPlatform !== "onlyfans" || row.publishingMode !== "assisted") return false; if (row.jobCancelledAt || row.jobArchived) return false; if (terminalJobStates.has(row.jobState) || terminalTaskStates.has(row.queueStatus)) return false; if (!activeTaskStates.has(row.queueStatus)) return false; if (row.postedBy || row.postedAt || row.postedConfirmation || row.finalPostUrl || row.finalPostUrlSkipReason || row.proofScreenshotStorageKey || row.skipOrFailReason) return false; if (row.creatorId !== row.creatorId || !row.platformJobId || !row.queueTaskId) return false; return true }
export function getAttentionReasons(row: TrustedOperatorJobTaskProjection, actorId: string, capturedAtMs: number): OnlyFansOperatorAttentionReason[] { const reasons: OnlyFansOperatorAttentionReason[] = []; const exp = row.claimExpiresAt ? Date.parse(row.claimExpiresAt) : null; if (row.queueStatus === "claimed" && row.claimedBy && exp && exp <= capturedAtMs) reasons.push("expired_claim_recovery_available"); else if (row.queueStatus === "claimed" && row.claimedBy && row.claimedBy !== actorId) reasons.push("claimed_by_another_operator"); if ([row.creatorVerificationStatus,row.accountVerificationStatus].some(v => v && v !== "verified") || (row.consentStatus && row.consentStatus !== "granted") || (row.creatorApprovalStatus && row.creatorApprovalStatus !== "approved") || (row.complianceStatus && !["passed","escalated_approved"].includes(row.complianceStatus)) || row.capabilityAvailabilityStatus === "unavailable" || row.capabilityPublishingMode && row.capabilityPublishingMode !== "assisted" || row.sourceFingerprintStale) reasons.push("authorization_or_safety_attention"); return Array.from(new Set(reasons)) }
export function assignDisplayBucket(row: TrustedOperatorJobTaskProjection, actorId: string, capturedAt: string): { bucket: OnlyFansOperatorDisplayBucket; reasons: OnlyFansOperatorAttentionReason[]; readOnly: boolean } { const now = Date.parse(capturedAt); const claimExp = row.claimExpiresAt ? Date.parse(row.claimExpiresAt) : null; if (row.queueStatus === "claimed" && row.claimedBy === actorId && Boolean(claimExp && now < claimExp)) return { bucket:"claimed_by_me", reasons:[], readOnly:false }; const reasons = getAttentionReasons(row, actorId, now); if (reasons.length) return { bucket:"needs_attention", reasons, readOnly:true }; const intended = row.intendedPublishAt ? Date.parse(row.intendedPublishAt) : null; const due = row.operatorDueAt ? Date.parse(row.operatorDueAt) : null; if (intended && intended <= now) return { bucket:"overdue", reasons:[], readOnly:false }; if (due && due <= now && (!intended || intended > now)) return { bucket:"due_now", reasons:[], readOnly:false }; if (due && due > now && due - now <= ONLYFANS_OPERATOR_DUE_SOON_WINDOW_MS) return { bucket:"due_soon", reasons:[], readOnly:true }; if (due && due > now) return { bucket:"upcoming", reasons:[], readOnly:true }; return { bucket:"ready_but_unscheduled", reasons:[], readOnly:false } }
