import type { OperatorClaimInput, OperatorProgressInput, OperatorRecoverExpiredClaimInput, OperatorReleaseInput, OnlyFansOperatorProgressState } from "./types"
const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const idemRe = /^[A-Za-z0-9_-]{8,128}$/
export const ONLYFANS_OPERATOR_PROGRESS_STATES: readonly OnlyFansOperatorProgressState[] = ["not_started", "preparing", "prepared", "handoff_ready"]
const protectedFields = new Set(["actorId","actor_id","creatorId","creator_id","operatorId","operator_id","claimedBy","claimed_by","queueTaskId","queue_task_id","claimToken","claim_token","authorizationStatus","authorization_status","claimOwnership","claim_ownership","platform","targetPlatform","target_platform","publishingMode","publishing_mode","consentVersion","consent_version","consentHash","consent_hash","verificationStatus","verification_status","complianceStatus","compliance_status","sourceFingerprint","source_fingerprint","accountVerification","account_verification","storageKey","storage_key","storageKeys","storage_keys","completionState","completion_state","evidence","evidenceFields","evidence_fields","task18","task18Completion","task18_completion","postedBy","posted_by","postedAt","posted_at","finalPostUrl","final_post_url","proofScreenshotStorageKey","proof_screenshot_storage_key"])
function fail(): never { throw new Error("OPERATOR_INPUT_INVALID") }
function object(input: unknown): Record<string, unknown> { if (!input || typeof input !== "object" || Array.isArray(input)) fail(); return input as Record<string, unknown> }
function assertKeys(row: Record<string, unknown>, allowed: readonly string[]) { const ok = new Set(allowed); for (const k of Object.keys(row)) { if (protectedFields.has(k) || !ok.has(k)) fail() } }
function str(v: unknown) { if (typeof v !== "string") fail(); return v }
function platformJobId(v: unknown) { const s = str(v).trim(); if (!uuidRe.test(s)) fail(); return s }
function idempotencyKey(v: unknown) { const s = str(v).trim(); if (!idemRe.test(s)) fail(); return s }
function progressState(v: unknown) { const s = str(v) as OnlyFansOperatorProgressState; if (!ONLYFANS_OPERATOR_PROGRESS_STATES.includes(s)) fail(); return s }
export function validateOperatorClaimInput(input: unknown): OperatorClaimInput { const r=object(input); assertKeys(r,["platformJobId","idempotencyKey"]); return { platformJobId: platformJobId(r.platformJobId), idempotencyKey: idempotencyKey(r.idempotencyKey) } }
export function validateOperatorReleaseInput(input: unknown): OperatorReleaseInput { const r=object(input); assertKeys(r,["platformJobId","idempotencyKey"]); return { platformJobId: platformJobId(r.platformJobId), idempotencyKey: idempotencyKey(r.idempotencyKey) } }
export function validateOperatorProgressInput(input: unknown): OperatorProgressInput { const r=object(input); assertKeys(r,["platformJobId","expectedProgressState","expectedProgressRevision","nextProgressState","idempotencyKey"]); if (!Number.isInteger(r.expectedProgressRevision) || (r.expectedProgressRevision as number) < 0) fail(); return { platformJobId: platformJobId(r.platformJobId), expectedProgressState: progressState(r.expectedProgressState), expectedProgressRevision: r.expectedProgressRevision as number, nextProgressState: progressState(r.nextProgressState), idempotencyKey: idempotencyKey(r.idempotencyKey) } }
export function validateOperatorRecoverExpiredClaimInput(input: unknown): OperatorRecoverExpiredClaimInput { const r=object(input); assertKeys(r,["platformJobId","idempotencyKey"]); return { platformJobId: platformJobId(r.platformJobId), idempotencyKey: idempotencyKey(r.idempotencyKey) } }
export function isValidUuid(value: unknown): value is string { return typeof value === "string" && uuidRe.test(value) }
