import { AI_TWIN_CONSENT_VERSION, getAiTwinConsentTextSha256 } from "./copy"
import type { AiTwinConsentActionInput, AiTwinConsentDeps, AiTwinConsentErrorCode, AiTwinConsentResult, AiTwinConsentRpcResult } from "./types"

const protectedFields = ["creatorId","status","attestationVersion","attestationText","attestationTextSha256","grantedAt","revokedAt","reviewerId","password","token","cookie","session","apiKey"]
const errorCodes: AiTwinConsentErrorCode[] = ["UNAUTHENTICATED","AI_TWIN_CONSENT_INVALID_FORM","AI_TWIN_CONSENT_CREATOR_NOT_VERIFIED","AI_TWIN_CONSENT_NOT_FOUND","AI_TWIN_CONSENT_ALREADY_GRANTED","AI_TWIN_CONSENT_ALREADY_REVOKED","AI_TWIN_CONSENT_STALE","AI_TWIN_CONSENT_IDEMPOTENCY_CONFLICT","AI_TWIN_CONSENT_SAVE_FAILED"]
function fail(code: AiTwinConsentErrorCode): AiTwinConsentResult { return { ok:false, code, message: code } }
export function parseAiTwinConsentRpcResult(data: unknown): AiTwinConsentRpcResult { if (!data || typeof data !== "object") throw new Error("invalid"); const r = data as Record<string, unknown>; const ids = r.audit_event_ids; if (!Array.isArray(ids) || !ids.every(x => typeof x === "string" && /^[0-9]+$/.test(x))) throw new Error("invalid audit_event_ids"); for (const k of ["creator_id","resulting_status","attestation_version","attestation_text_sha256","granted_at","updated_at","outcome"] as const) if (typeof r[k] !== "string" || !r[k]) throw new Error("invalid"); if (r.revoked_at !== null && typeof r.revoked_at !== "string") throw new Error("invalid"); if (r.prior_status !== null && typeof r.prior_status !== "string") throw new Error("invalid"); if (typeof r.idempotent !== "boolean") throw new Error("invalid"); if (!/^[0-9a-f]{64}$/.test(r.attestation_text_sha256 as string)) throw new Error("invalid"); return r as AiTwinConsentRpcResult }
export function hasProtectedAiTwinConsentFields(input: Record<string, unknown>) { return protectedFields.some(f => Object.prototype.hasOwnProperty.call(input, f)) }
export async function saveAiTwinConsentWithDeps(input: AiTwinConsentActionInput, deps: AiTwinConsentDeps): Promise<AiTwinConsentResult> { if (hasProtectedAiTwinConsentFields(input)) return fail("AI_TWIN_CONSENT_INVALID_FORM"); if (input.decision !== "grant" && input.decision !== "revoke") return fail("AI_TWIN_CONSENT_INVALID_FORM"); if (typeof input.idempotencyKey !== "string" || !/^[A-Za-z0-9_-]{8,128}$/.test(input.idempotencyKey)) return fail("AI_TWIN_CONSENT_INVALID_FORM"); if (input.decision === "grant" && input.confirmGrant !== "on") return fail("AI_TWIN_CONSENT_INVALID_FORM"); if (input.decision === "revoke" && input.confirmRevoke !== "on") return fail("AI_TWIN_CONSENT_INVALID_FORM"); const creatorId = await deps.getAuthenticatedUserId(); if (!creatorId) return fail("UNAUTHENTICATED"); const { data, error } = await deps.getAdminClient().rpc("creator_publishing_set_ai_twin_consent", { p_creator_id: creatorId, p_decision: input.decision, p_attestation_version: AI_TWIN_CONSENT_VERSION, p_attestation_text_sha256: getAiTwinConsentTextSha256(), p_expected_updated_at: input.expectedUpdatedAt || null, p_idempotency_key: input.idempotencyKey }); if (error) { const msg = String(error.message || error.code || ""); const code = errorCodes.find(c => msg.includes(c)); return fail(code && code !== "UNAUTHENTICATED" && code !== "AI_TWIN_CONSENT_INVALID_FORM" ? code : "AI_TWIN_CONSENT_SAVE_FAILED") } try { return { ok:true, result: parseAiTwinConsentRpcResult(data) } } catch { return fail("AI_TWIN_CONSENT_SAVE_FAILED") } }
