import Link from "next/link"
import LegalPageLayout from "@/components/legal/LegalPageLayout"

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="August 22, 2026">
      <section><p>These Terms govern your access to Sirens Forge. You must agree to these Terms and the policies that apply to your use of the service.</p></section>
      <section><h2 className="text-xl font-semibold">1. Eligibility and accounts</h2><p>Sirens Forge is strictly for adults aged 18 and older. You are responsible for your account credentials, all activity under your account, and keeping your information accurate. Do not share, sell, or transfer access.</p></section>
      <section><h2 className="text-xl font-semibold">2. Subscriptions and billing</h2><p>Subscriptions and paid access are processed through our payment provider. Available billing controls govern cancellation. Refunds are not guaranteed for unused time, digital access, lifetime access, or consumed services unless required by law.</p></section>
      <section><h2 className="text-xl font-semibold">3. Using the service</h2><p>You may use Sirens Forge only lawfully and in accordance with our Acceptable Use Policy. Features may use asynchronous queues and may be delayed, limited, rejected, or unavailable because of capacity, safety controls, maintenance, or fair-use limits. Access does not guarantee a particular processing time, volume, output, or uninterrupted compute availability.</p></section>
      <section><h2 className="text-xl font-semibold">4. AI-generated content</h2><p>Outputs are generated from user inputs and may not be accurate, lawful, suitable, safe, unique, or appropriate for a particular purpose. You are responsible for reviewing an output before using, publishing, or selling it.</p></section>
      <section><h2 className="text-xl font-semibold">5. Your content and limited processing permission</h2><p>You retain ownership of content you submit or create, subject to third-party rights. You give Sirens Forge a limited, non-exclusive permission to process, store, display, and transmit the minimum creator material necessary to deliver requested features, secure and troubleshoot the service, provide creator-requested support, conduct safety or compliance review, prevent fraud or abuse, meet legal obligations, and enforce policy.</p><p>Private creator uploads, identity or Twin materials, prompts, and generated content are not used for generalized model training by default. Any future use of private creator content for generalized model training or improvement requires your separate explicit opt-in; this operational permission does not provide that consent.</p></section>
      <section><h2 className="text-xl font-semibold">6. Identity, likeness, and publishing</h2><p>You remain responsible for obtaining the rights, consent, and authorization required for real-person likenesses and identity materials. Sirens Forge applies consent, verification, likeness, safety, and platform-policy controls where supported, but those controls do not establish every legal right.</p><p>General generation may use a fully synthetic fictional persona and does not require every persona to resemble the creator. Fanvue may permit a fully synthetic fictional AI persona that does not resemble the verified human account owner, subject to Fanvue requirements. The OnlyFans launch workflow is different: content prepared for that workflow must depict the verified creator and follow its existing consent, verification, disclosure, and manual-handoff requirements.</p></section>
      <section><h2 className="text-xl font-semibold">7. Prohibited conduct</h2><p>You may not create, request, upload, store, or distribute prohibited content, including sexual content involving minors or underage-looking persons; nonconsensual intimate imagery; unauthorized intimate AI depictions, deepfakes, or face swaps of identifiable real people; exploitation; coercion; harassment; fraud; or other unlawful activity. Authorized, consensual creator Twin use is not prohibited merely because it uses AI.</p></section>
      <section><h2 className="text-xl font-semibold">8. Purpose-limited review and enforcement</h2><p>Automated processing does not imply casual human browsing of private creator content. Human access is purpose-limited to legitimate circumstances such as creator-requested support, genuine technical troubleshooting, safety or NCII investigation, fraud or security investigation, policy enforcement, or a legal requirement. We may restrict content or accounts when supported by policy, safety, security, or legal needs.</p></section>
      <section><h2 className="text-xl font-semibold">9. Complaints and removal</h2><p>Our <Link className="text-cyan-400 hover:underline" href="/content-removal">content-removal process</Link> accepts rights and policy concerns. Reports of nonconsensual or unauthorized intimate content can use the dedicated <Link className="text-cyan-400 hover:underline" href="/report-intimate-content">reporting route</Link>. A report does not predetermine the outcome.</p></section>
      <section><h2 className="text-xl font-semibold">10. Suspension and termination</h2><p>We may suspend, restrict, or terminate access when we reasonably believe these Terms, applicable policies, payment rules, law, or platform safety has been violated.</p></section>
      <section><h2 className="text-xl font-semibold">11. No warranty</h2><p>The service is provided as-is and as-available without warranties of any kind. We do not guarantee uninterrupted, completely secure, or error-free operation, compatibility, commercial usability, or that outputs will meet your expectations or legal requirements.</p></section>
      <section><h2 className="text-xl font-semibold">12. Limitation of liability</h2><p>To the maximum extent permitted by law, Sirens Forge is not liable for indirect, incidental, special, consequential, exemplary, or punitive damages. Our total liability will not exceed the amount you paid Sirens Forge in the 12 months before the claim arose.</p></section>
      <section><h2 className="text-xl font-semibold">13. Indemnification</h2><p>You agree to defend, indemnify, and hold harmless Sirens Forge and its operators, affiliates, contractors, processors, and service providers from claims arising from your use, content, policy violations, or infringement of another party&apos;s rights.</p></section>
      <section><h2 className="text-xl font-semibold">14. Governing law</h2><p>These Terms are governed by Florida law, without regard to conflict-of-law rules. Disputes will be resolved in Florida courts unless applicable law requires otherwise.</p></section>
      <section><h2 className="text-xl font-semibold">15. Changes</h2><p>We may update these Terms. We will post the updated version and its date and provide any additional notice or obtain acceptance when required. An updated policy applies according to the notice presented and applicable law; this section does not claim that a general automated re-consent system currently exists.</p></section>
      <section><h2 className="text-xl font-semibold">16. Contact</h2><p>Questions may be sent to admin@sirensforge.vip.</p></section>
    </LegalPageLayout>
  )
}
