"use client"
import { FormEvent, useEffect, useRef, useState } from "react"
import ChatUI from "./ChatUI"
type Subscriber={id:string;display_name:string;platform:string;platform_handle:string|null}
type Conversation={id:string;status:string;label:string;last_used_at?:string|null}
const platforms=["OnlyFans","Fanvue","Fansly","LoyalFans","JustForFans","Reddit","X / Twitter","Telegram","Instagram","Other"]
export default function CreatorReplyWorkspace(){
 const [subscribers,setSubscribers]=useState<Subscriber[]>([]),[active,setActive]=useState<Subscriber|null>(null),[conversation,setConversation]=useState<Conversation|null>(null),[conversationList,setConversationList]=useState<Conversation[]>([]),[modal,setModal]=useState(false),[library,setLibrary]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[platformFilter,setPlatformFilter]=useState(""),[saving,setSaving]=useState(false),[platform,setPlatform]=useState(platforms[0]),[dirty,setDirty]=useState(false),[archivedView,setArchivedView]=useState(false); const first=useRef<HTMLInputElement>(null),newButton=useRef<HTMLButtonElement>(null)
 useEffect(()=>{void(async()=>{try{const r=await fetch("/api/sirens-mind/creator-reply/subscribers");if(!r.ok)throw new Error();const x=await r.json();setSubscribers(x.subscribers);const sid=sessionStorage.getItem("sirensforge:sirens_mind_creator_reply_selected_subscriber"),cid=sessionStorage.getItem("sirensforge:sirens_mind_creator_reply_selected_conversation"),selected=x.subscribers.find((s:Subscriber)=>s.id===sid);if(!selected||!cid)throw new Error("STALE_SELECTION");const cr=await fetch(`/api/sirens-mind/creator-reply/subscribers/${selected.id}/conversations`);if(!cr.ok)throw new Error("STALE_SELECTION");const cx=await cr.json(),stored=cx.conversations.find((c:Conversation)=>c.id===cid&&c.status==="active"),chosen=stored||cx.conversations.find((c:Conversation)=>c.status==="active")||null;setActive(selected);setConversation(chosen);setConversationList(cx.conversations);if(chosen)sessionStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_conversation",chosen.id);else sessionStorage.removeItem("sirensforge:sirens_mind_creator_reply_selected_conversation")}catch(e){if(e instanceof Error&&e.message==="STALE_SELECTION"){sessionStorage.removeItem("sirensforge:sirens_mind_creator_reply_selected_subscriber");sessionStorage.removeItem("sirensforge:sirens_mind_creator_reply_selected_conversation")}else setError("Subscribers could not be loaded.")}})()},[])
 const closeModal=()=>{if(dirty&&!confirm("Discard the subscriber information you entered?"))return;setModal(false);setDirty(false);newButton.current?.focus()}
 useEffect(()=>{if(modal)first.current?.focus()},[modal]); useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==="Escape"&&modal)closeModal()};addEventListener("keydown",esc);return()=>removeEventListener("keydown",esc)},[modal,dirty])
 async function selectSubscriber(s:Subscriber){setActive(s);setConversation(null);const r=await fetch(`/api/sirens-mind/creator-reply/subscribers/${s.id}/conversations`);if(!r.ok)return setError("Conversations could not be loaded.");const x=await r.json();setConversationList(x.conversations);const c=x.conversations.find((v:Conversation)=>v.status==="active")||null;setConversation(c);setLibrary(false);if(c){sessionStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_subscriber",s.id);sessionStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_conversation",c.id)}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(saving)return;setSaving(true);setError("");const form=new FormData(e.currentTarget),body=Object.fromEntries(form);if(body.platform==="Other")body.platform=body.custom_platform;const r=await fetch("/api/sirens-mind/creator-reply/subscribers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setSaving(false);setError("Subscriber could not be saved. Your entries were kept.");return}const x=await r.json();setSubscribers(s=>[x.subscriber,...s]);setActive(x.subscriber);setConversation(x.conversation);setConversationList([x.conversation]);sessionStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_subscriber",x.subscriber.id);sessionStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_conversation",x.conversation.id);setDirty(false);setModal(false);setSaving(false);setNotice(`New subscriber started — ${x.subscriber.display_name} • ${x.subscriber.platform}`);newButton.current?.focus()}
 async function startConversation(){if(!active)return;const r=await fetch(`/api/sirens-mind/creator-reply/subscribers/${active.id}/conversations`,{method:"POST"});if(!r.ok)return setError("Conversation could not be started.");const x=await r.json();setConversation(x.conversation);setConversationList(c=>[x.conversation,...c.map(v=>({...v,status:"paused"}))]);sessionStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_conversation",x.conversation.id);setNotice(`New conversation started with ${active.display_name}.`)}
 async function resume(c:Conversation){const r=await fetch(`/api/sirens-mind/creator-reply/conversations/${c.id}/resume`,{method:"POST"});if(!r.ok)return setError("Conversation could not be restored.");setConversation(c);sessionStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_conversation",c.id);setNotice(`${active?.display_name} • ${active?.platform} — ${c.label} restored`)}
 async function reset(){if(!conversation||!confirm("Reset destroys the saved resume point for this conversation. Continue?"))return;const r=await fetch(`/api/sirens-mind/creator-reply/conversations/${conversation.id}/reset`,{method:"POST"});if(!r.ok)return setError("Context could not be reset.");setConversation({...conversation});setNotice("Conversation context reset.")}
 async function archive(){if(!active)return;const r=await fetch(`/api/sirens-mind/creator-reply/subscribers/${active.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"archive"})});if(!r.ok)return setError("Subscriber could not be archived.");setSubscribers(v=>v.filter(s=>s.id!==active.id));setActive(null);setConversation(null);setNotice("Subscriber archived. Archived subscribers can be restored from the library.")}
 async function showArchived(value:boolean){setArchivedView(value);const r=await fetch(`/api/sirens-mind/creator-reply/subscribers${value?"?archived=true":""}`);if(!r.ok)return setError("Subscribers could not be loaded.");setSubscribers((await r.json()).subscribers)}
 async function unarchive(s:Subscriber){const r=await fetch(`/api/sirens-mind/creator-reply/subscribers/${s.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"unarchive"})});if(!r.ok)return setError("Subscriber could not be restored.");setSubscribers(v=>v.filter(x=>x.id!==s.id));setNotice(`${s.display_name} restored.`)}
 async function editSubscriber(){if(!active)return;const d=await fetch(`/api/sirens-mind/creator-reply/subscribers/${active.id}`);if(!d.ok)return setError("Subscriber could not be loaded for editing.");const x=(await d.json()).subscriber,name=prompt("Display name",x.display_name),p=prompt("Platform",x.platform),h=prompt("Handle / Username",x.platform_handle||""),notes=prompt("Key Notes",x.notes||"");if([name,p,h,notes].some(v=>v===null))return;const r=await fetch(`/api/sirens-mind/creator-reply/subscribers/${active.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({display_name:name,platform:p,platform_handle:h,notes})});if(!r.ok)return setError("Subscriber could not be updated.");const updated=(await r.json()).subscriber;setActive(updated);setSubscribers(v=>v.map(q=>q.id===updated.id?updated:q));setNotice("Subscriber profile and Key Notes updated.")}
 async function rename(c:Conversation){const label=prompt("Conversation label",c.label);if(label===null)return;const r=await fetch(`/api/sirens-mind/creator-reply/conversations/${c.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({label})});if(!r.ok)return setError("Conversation could not be renamed.");const updated={...c,label:(await r.json()).conversation.label||"Conversation"};setConversationList(v=>v.map(x=>x.id===c.id?updated:x));if(conversation?.id===c.id)setConversation(updated)}
 async function remove(){if(!active||!confirm(`Permanently delete ${active.display_name} and every saved conversation? This cannot be undone.`))return;const r=await fetch(`/api/sirens-mind/creator-reply/subscribers/${active.id}`,{method:"DELETE"});if(!r.ok)return setError("Subscriber could not be deleted.");setSubscribers(v=>v.filter(s=>s.id!==active.id));setActive(null);setConversation(null);sessionStorage.removeItem("sirensforge:sirens_mind_creator_reply_selected_subscriber");sessionStorage.removeItem("sirensforge:sirens_mind_creator_reply_selected_conversation");setNotice("Subscriber data deleted.")}
 return <div>
  <div className="mx-auto max-w-5xl px-4 pt-4"><div className="flex flex-wrap gap-2"><button className="rounded border px-3 py-2" onClick={()=>setLibrary(v=>!v)}>Subscribers</button><button ref={newButton} className="rounded bg-fuchsia-700 px-3 py-2 text-white" onClick={()=>setModal(true)}>New Subscriber</button>{active&&<><button className="rounded border px-3 py-2" onClick={editSubscriber}>Edit Subscriber</button><button className="rounded border px-3 py-2" onClick={startConversation}>New Conversation</button><button className="rounded border px-3 py-2" onClick={archive}>Archive</button><button className="rounded border border-red-500 px-3 py-2" onClick={remove}>Delete</button></>}{conversation&&<button className="rounded border border-red-500 px-3 py-2" onClick={reset}>Reset Context</button>}</div>
  {notice&&<p role="status" className="mt-2 text-sm text-emerald-400">{notice}</p>}{error&&<p role="alert" className="mt-2 text-sm text-red-400">{error}</p>}
  {active?<section aria-label="Active subscriber" className="mt-3 rounded border p-3"><strong>{active.display_name} • {active.platform}</strong>{active.platform_handle&&<div>@{active.platform_handle.replace(/^@/,"")}</div>}<div className="text-sm">Conversation: {conversation?.label||"Select a saved conversation"}</div></section>:<p className="mt-3 rounded border p-3">Select a subscriber or start a new one.</p>}
  {library&&<section aria-label="Subscriber library" className="mt-3 rounded border p-3"><h2 className="font-semibold">Subscribers</h2><div className="flex gap-2"><button aria-pressed={!archivedView} onClick={()=>showArchived(false)}>Active</button><button aria-pressed={archivedView} onClick={()=>showArchived(true)}>Archived</button><input aria-label="Search subscribers" value={search} onChange={e=>setSearch(e.target.value)} className="border bg-transparent p-2"/><select aria-label="Filter platform" value={platformFilter} onChange={e=>setPlatformFilter(e.target.value)} className="border bg-zinc-900 p-2"><option value="">All platforms</option>{[...new Set(subscribers.map(s=>s.platform))].map(p=><option key={p}>{p}</option>)}</select></div>{subscribers.filter(s=>(!platformFilter||s.platform===platformFilter)&&(`${s.display_name} ${s.platform_handle||""}`.toLowerCase().includes(search.toLowerCase()))).map(s=><div key={s.id} className="flex border-b"><button className="flex-1 p-2 text-left" onClick={()=>!archivedView&&selectSubscriber(s)}>{s.display_name} • {s.platform}{s.platform_handle?` — @${s.platform_handle.replace(/^@/,"")}`:""}</button>{archivedView&&<button onClick={()=>unarchive(s)}>Unarchive</button>}</div>)}{active&&conversationList.map(c=><div key={c.id} className="flex justify-between p-2 text-sm"><span>{c.label} {c.last_used_at?`• ${new Date(c.last_used_at).toLocaleDateString()}`:""}</span><span><button onClick={()=>rename(c)}>Rename</button> <button onClick={()=>resume(c)}>Resume</button></span></div>)}</section>}</div>
  {active&&conversation?<ChatUI key={`${active.id}:${conversation.id}:${notice}`} experience="creator_reply" subscriberId={active.id} conversationId={conversation.id}/>:<div className="h-24"/>}
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div role="dialog" aria-modal="true" aria-labelledby="new-subscriber-title" className="w-full max-w-lg rounded bg-zinc-900 p-5"><h2 id="new-subscriber-title" className="text-xl font-semibold">New Subscriber</h2><form onSubmit={save} onChange={()=>setDirty(true)} className="space-y-3"><label className="block">Name<input ref={first} required maxLength={120} name="display_name" className="mt-1 w-full rounded border bg-transparent p-2"/></label><label className="block">Platform<select required name="platform" value={platform} onChange={e=>setPlatform(e.target.value)} className="mt-1 w-full rounded border bg-zinc-900 p-2">{platforms.map(p=><option key={p}>{p}</option>)}</select></label>{platform==="Other"&&<label className="block">Custom platform<input required maxLength={80} name="custom_platform" className="mt-1 w-full rounded border bg-transparent p-2"/></label>}<label className="block">Handle / Username<input maxLength={120} name="platform_handle" className="mt-1 w-full rounded border bg-transparent p-2"/></label><label className="block">Key Notes<textarea maxLength={2000} name="notes" rows={5} className="mt-1 w-full rounded border bg-transparent p-2"/></label>{error&&<p role="alert">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2" onClick={closeModal}>Cancel</button><button disabled={saving} className="rounded bg-fuchsia-700 px-3 py-2 text-white disabled:opacity-50">{saving?"Saving…":"Save Subscriber"}</button></div></form></div></div>}
 </div>
}
