"use client"
import { FormEvent, useEffect, useRef, useState } from "react"
import ChatUI from "./ChatUI"
type Subscriber={id:string;display_name:string;platform:string;platform_handle:string|null}
const platforms=["OnlyFans","Fanvue","Fansly","LoyalFans","JustForFans","Reddit","X / Twitter","Telegram","Instagram","Other"]
export default function CreatorReplyWorkspace(){
 const [subscribers,setSubscribers]=useState<Subscriber[]>([]),[active,setActive]=useState<Subscriber|null>(null),[modal,setModal]=useState(false),[library,setLibrary]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""); const first=useRef<HTMLInputElement>(null)
 useEffect(()=>{fetch("/api/sirens-mind/creator-reply/subscribers").then(r=>r.ok?r.json():Promise.reject()).then(x=>setSubscribers(x.subscribers)).catch(()=>setError("Subscribers could not be loaded."))},[])
 useEffect(()=>{if(modal)first.current?.focus()},[modal]); useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")setModal(false)};addEventListener("keydown",esc);return()=>removeEventListener("keydown",esc)},[])
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const form=new FormData(e.currentTarget),body=Object.fromEntries(form);const r=await fetch("/api/sirens-mind/creator-reply/subscribers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("Subscriber could not be saved. Your entries were kept.");return}const x=await r.json();setSubscribers(s=>[x.subscriber,...s]);setActive(x.subscriber);localStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_subscriber",x.subscriber.id);localStorage.setItem("sirensforge:sirens_mind_creator_reply_selected_conversation",x.conversation.id);setModal(false);setNotice(`New subscriber started — ${x.subscriber.display_name} • ${x.subscriber.platform}`)}
 return <div>
  <div className="mx-auto max-w-5xl px-4 pt-4"><div className="flex flex-wrap gap-2"><button className="rounded border px-3 py-2" onClick={()=>setLibrary(v=>!v)}>Subscribers</button><button className="rounded bg-fuchsia-700 px-3 py-2 text-white" onClick={()=>setModal(true)}>New Subscriber</button></div>
  {notice&&<p role="status" className="mt-2 text-sm text-emerald-400">{notice}</p>}{error&&<p role="alert" className="mt-2 text-sm text-red-400">{error}</p>}
  {active?<section aria-label="Active subscriber" className="mt-3 rounded border p-3"><strong>{active.display_name} • {active.platform}</strong>{active.platform_handle&&<div>@{active.platform_handle.replace(/^@/,"")}</div>}<div className="text-sm">Conversation: Active conversation</div></section>:<p className="mt-3 rounded border p-3">Select a subscriber or start a new one.</p>}
  {library&&<section aria-label="Subscriber library" className="mt-3 rounded border p-3"><h2 className="font-semibold">Subscribers</h2>{subscribers.map(s=><button key={s.id} className="block w-full border-b p-2 text-left" onClick={()=>{setActive(s);setLibrary(false);setNotice(`${s.display_name} • ${s.platform} selected`)}}>{s.display_name} • {s.platform}{s.platform_handle?` — @${s.platform_handle.replace(/^@/,"")}`:""}</button>)}</section>}</div>
  {active?<ChatUI key={active.id} experience="creator_reply"/>:<div className="h-24"/>}
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div role="dialog" aria-modal="true" aria-labelledby="new-subscriber-title" className="w-full max-w-lg rounded bg-zinc-900 p-5"><h2 id="new-subscriber-title" className="text-xl font-semibold">New Subscriber</h2><form onSubmit={save} className="space-y-3"><label className="block">Name<input ref={first} required maxLength={120} name="display_name" className="mt-1 w-full rounded border bg-transparent p-2"/></label><label className="block">Platform<select required name="platform" className="mt-1 w-full rounded border bg-zinc-900 p-2">{platforms.map(p=><option key={p}>{p}</option>)}</select></label><label className="block">Handle / Username<input maxLength={120} name="platform_handle" className="mt-1 w-full rounded border bg-transparent p-2"/></label><label className="block">Key Notes<textarea maxLength={2000} name="notes" rows={5} className="mt-1 w-full rounded border bg-transparent p-2"/></label>{error&&<p role="alert">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2" onClick={()=>setModal(false)}>Cancel</button><button className="rounded bg-fuchsia-700 px-3 py-2 text-white">Save Subscriber</button></div></form></div></div>}
 </div>
}
