import { sortOnlyFansHistoryEntries } from "./controls"
import {
  actionCopy,
  evidenceLifecycleCopy,
  isIntentionallyExcludedHistoryAction,
  jobStateLabel,
  noUrlReasonLabel,
  rejectionWording,
  scheduleGateWording,
} from "./presentation"
import { normalizeHistoryTimezone } from "./timezone"
import type { OnlyFansHistoryAudience, OnlyFansHistoryEntry, OnlyFansHistoryKind, OnlyFansHistoryRows, OnlyFansHistoryView } from "./types"

type InternalHistoryEntry = OnlyFansHistoryEntry & { completionGroup?:string; completionPriority?:number }

function iso(value:any){ return typeof value === "string" && !Number.isNaN(Date.parse(value)) ? value : null }
function safeAuditEventId(value:any) { if (typeof value === "number" && Number.isFinite(value)) return String(value); if (typeof value === "string" && /^\d+$/.test(value)) return value; return undefined }
function auditKind(audit:any): OnlyFansHistoryKind { if (audit.action === "operator_onlyfans_manual_completion_rejected") return "rejection"; if (audit.action === "operator_onlyfans_manual_completion_proof_recorded" || audit.action === "operator_onlyfans_manual_completion") return "completion"; const category=actionCopy(audit.action,"operator").category; if (category === "scheduling") return "scheduler"; if (category === "operator") return "operator"; return "lifecycle" }
function completionPriority(audit:any) { if (audit.action === "operator_onlyfans_manual_completion_proof_recorded") return 50; if (audit.action === "operator_onlyfans_manual_completion" && audit.entity_type === "creator_publishing_platform_job") return 30; if (audit.action === "operator_onlyfans_manual_completion" && audit.entity_type === "creator_publishing_queue_task") return 20; return null }
function completionGroup(jobId:string|undefined, occurredAt:string) { return `publication-confirmation:${jobId ?? "unknown"}:${occurredAt}` }
function collapsePublicationConfirmations(entries:InternalHistoryEntry[]) { const selected=new Map<string,InternalHistoryEntry>(); const unrelated:InternalHistoryEntry[]=[]; for (const entry of entries) { if (!entry.completionGroup || entry.completionPriority == null) { unrelated.push(entry); continue } const prior=selected.get(entry.completionGroup); if (!prior || entry.completionPriority > (prior.completionPriority ?? -1) || (entry.completionPriority === prior.completionPriority && (entry.auditEventId ?? "").localeCompare(prior.auditEventId ?? "") > 0)) selected.set(entry.completionGroup,entry) } return [...unrelated,...selected.values()] }
function schedulerResultStatus(entry:InternalHistoryEntry) { const status=entry.metadata?.status; if (typeof status === "string") return status; if (entry.action.includes("superseded")) return "superseded"; if (entry.action.includes("processed")) return "processed"; if (entry.action.includes("gate_failed")) return "blocked"; if (entry.action.includes("claimed")) return "processing"; return undefined }
function displayDeduplicationKey(entry:InternalHistoryEntry){ if (entry.metadata?.schedulerEventId) { const status=schedulerResultStatus(entry); if (status) return `scheduler-transition:${entry.metadata.schedulerEventId}:${status}:${entry.occurredAt}`; return `scheduler:${entry.action}:${entry.metadata.schedulerEventId}` } if (entry.action === "operator_expired_claim_recovered") return `claim-expired:${entry.occurredAt}`; return entry.id }
function evidenceMetadata(event:any, audience:OnlyFansHistoryAudience){ if (audience !== "operator") return undefined; return { evidenceIntentId:event.id, operation:event.operation, replacesIntentId:event.replaces_intent_id, replacedByIntentId:event.replaced_by_intent_id, mimeType:event.normalized_mime_type, actualSizeBytes:event.actual_size_bytes, digest:typeof event.verified_sha256 === "string" ? `${event.verified_sha256.slice(0,12)}…` : undefined, failureCode:event.failure_code } }
function matchingScheduleJob(after:any, platformJobId:string|undefined) { if (!platformJobId || !Array.isArray(after?.jobs)) return null; const matches=after.jobs.filter((item:any)=>item?.job_id===platformJobId || item?.platform_job_id===platformJobId || item?.id===platformJobId); return matches.length===1 ? matches[0] : null }
function normalizedScheduleOutcome(action:string,status:unknown) { if (status === "scheduled") return action === "creator_publishing_schedule_rescheduled" ? "rescheduled" : "scheduled"; if (status === "rescheduled") return "rescheduled"; if (status === "blocked") return "blocked"; return "failed" }
function scheduleAuditEntry(audit:any, job:any, audience:OnlyFansHistoryAudience):InternalHistoryEntry|null {
  const after=audit.after_state ?? {}; const jobResult=matchingScheduleJob(after,job?.id); if (!jobResult) return null; const copy=actionCopy(audit.action,audience); const outcome=normalizedScheduleOutcome(audit.action,jobResult.status); const safeGateCode=typeof jobResult.safe_error_code === "string" && /^[A-Z0-9_]{1,80}$/.test(jobResult.safe_error_code) ? jobResult.safe_error_code : undefined; const gateWording=scheduleGateWording(safeGateCode,audience); const cleanup=jobResult.operator_claim_cleanup && typeof jobResult.operator_claim_cleanup === "object" ? jobResult.operator_claim_cleanup : null; const cleanupPerformed=cleanup?.performed === true;
  const baseExplanation=outcome === "scheduled" ? (audience === "creator" ? "This publication attempt was scheduled." : "This job was scheduled by the plan request.") : outcome === "rescheduled" ? (audience === "creator" ? "The schedule for this publication attempt was changed." : "This job was rescheduled by the plan request.") : (audience === "creator" ? "This scheduling request did not change the publication attempt." : `This job's schedule request ended as ${outcome}.`); const cleanupExplanation=cleanupPerformed ? (audience === "creator" ? " An earlier operator hold was cleared safely." : " The schedule operation also cleared the current operator claim.") : ""; const auditEventId=safeAuditEventId(audit.id);
  return { id:`audit:${auditEventId ?? audit.id}`, kind:"scheduler", category:"scheduling", action:audit.action, label:outcome === "blocked" || outcome === "failed" ? `${copy.label} — ${outcome}` : copy.label, explanation:`${baseExplanation}${gateWording ? ` ${gateWording}` : ""}${cleanupExplanation}`, occurredAt:audit.created_at, auditEventId, sortAuditId:typeof audit.id === "number" ? audit.id : null, provenance:"append_only_audit_evidence", scheduleOutcome:outcome, scheduleRevision:typeof jobResult.schedule_revision === "number" ? jobResult.schedule_revision : undefined, metadata:audience === "operator" ? { entityType:audit.entity_type, entityId:audit.entity_id, platformJobId:job.id, scheduleOutcome:outcome, scheduleRevision:typeof jobResult.schedule_revision === "number" ? jobResult.schedule_revision : undefined, safeGateCode, claimCleanupPerformed:cleanupPerformed, claimCleanupReason:typeof cleanup?.reason === "string" ? cleanup.reason : undefined, queueTaskId:typeof cleanup?.queue_task_id === "string" ? cleanup.queue_task_id : undefined } : undefined }
}
function genericAuditEntry(audit:any, rows:OnlyFansHistoryRows, audience:OnlyFansHistoryAudience):InternalHistoryEntry|null {
  if (isIntentionallyExcludedHistoryAction(audit.action)) return null; if (audit.action === "creator_publishing_schedule_created" || audit.action === "creator_publishing_schedule_rescheduled") return scheduleAuditEntry(audit,rows.job,audience);
  const before=audit.before_state ?? {}; const after=audit.after_state ?? {}; const copy=actionCopy(audit.action,audience); const rejectionCode=typeof after.rejection_code === "string" ? after.rejection_code : undefined; const safeGateCode=typeof after.safe_error_code === "string" && /^[A-Z0-9_]{1,80}$/.test(after.safe_error_code) ? after.safe_error_code : undefined; const gateWording=scheduleGateWording(safeGateCode,audience); let explanation=rejectionCode ? (rejectionWording[rejectionCode]?.[audience] ?? "Completion was rejected.") : copy[audience]; if (gateWording) explanation+=` ${gateWording}`; if (audit.action === "creator_publishing_scheduler_event_processed" && typeof after.job_state === "string") explanation+=` Result: ${jobStateLabel(after.job_state,audience)}.`; const priority=completionPriority(audit); const auditEventId=safeAuditEventId(audit.id);
  return { id:`audit:${auditEventId ?? audit.id}`, kind:auditKind(audit), category:copy.category, action:audit.action, label:copy.label, explanation, occurredAt:audit.created_at, auditEventId, sortAuditId:typeof audit.id === "number" ? audit.id : null, provenance:"append_only_audit_evidence", evidenceState:after.evidence_intent_id?"proof present":null, finalPostUrl:after.final_post_url??null, noUrlReason:after.final_post_url_skip_reason??null, scheduleRevision:typeof (after.schedule_revision ?? before.schedule_revision) === "number" ? (after.schedule_revision ?? before.schedule_revision) : undefined, metadata:audience==="operator" ? { entityType:audit.entity_type, entityId:audit.entity_id, actorId:audit.actor_id, schedulerEventId:audit.entity_type === "creator_publishing_scheduler_event" ? audit.entity_id : undefined, queueTaskId:after.queue_task_id, platformJobId:after.platform_job_id, evidenceIntentId:after.evidence_intent_id, rejectionCode, safeGateCode, scheduleRevision:after.schedule_revision ?? before.schedule_revision, jobState:after.job_state, status:after.status, mimeType:after.normalized_mime_type, actualSizeBytes:after.actual_size_bytes, digest:typeof after.verified_sha256 === "string" ? `${after.verified_sha256.slice(0,12)}…` : undefined } : undefined, completionGroup:priority == null ? undefined : completionGroup(rows.job?.id,audit.created_at), completionPriority:priority ?? undefined }
}
function schedulerDerivedAction(status:string) { if (status === "processing") return "creator_publishing_scheduler_event_claimed"; if (status === "processed") return "creator_publishing_scheduler_event_processed"; if (status === "blocked") return "creator_publishing_scheduler_gate_failed"; if (status === "superseded") return "creator_publishing_scheduler_event_superseded"; return `scheduler_${status}` }

export function normalizeOnlyFansHistory(rows: OnlyFansHistoryRows, audience: OnlyFansHistoryAudience): OnlyFansHistoryView {
  const timezone=normalizeHistoryTimezone(rows.job?.schedule_timezone); const entries:InternalHistoryEntry[]=[]; const add=(entry:InternalHistoryEntry|null)=>{ if(entry && iso(entry.occurredAt)) entries.push(entry) };
  if (rows.plan?.created_at) add({id:`plan:${rows.plan.id}:created`,kind:"lifecycle",category:"scheduling",action:"plan_created",label:"Publishing plan created",explanation:"The publishing plan was created.",occurredAt:rows.plan.created_at,provenance:"derived_lifecycle_event",metadata:audience==="operator"?{planId:rows.plan.id}:undefined});
  if (rows.job?.created_at) add({id:`job:${rows.job.id}:created`,kind:"lifecycle",category:"scheduling",action:"platform_job_created",label:"OnlyFans job created",explanation:"An assisted/manual OnlyFans publishing attempt was created.",occurredAt:rows.job.created_at,provenance:"derived_lifecycle_event",metadata:audience==="operator"?{platformJobId:rows.job.id}:undefined});
  for (const audit of rows.auditEvents ?? []) add(genericAuditEntry(audit,rows,audience));
  const evidenceEvents = [{timestamp:"created_at",action:"evidence_reserved",state:"reserved"},{timestamp:"verified_at",action:"evidence_verified",state:"verified"},{timestamp:"invalidated_at",action:"evidence_superseded",state:"superseded"},{timestamp:"failed_at",action:"evidence_failed",state:"failed"},{timestamp:"expired_at",action:"evidence_expired",state:"expired"},{timestamp:"consumed_at",action:"evidence_consumed",state:"consumed"}] as const;
  for (const evidence of rows.evidenceIntents ?? []) for (const lifecycle of evidenceEvents) { const occurredAt=evidence[lifecycle.timestamp]; if (!occurredAt) continue; const copy=evidenceLifecycleCopy(lifecycle.action,audience); add({id:`evidence:${evidence.id}:${lifecycle.action}`,kind:"evidence",category:"evidence",action:lifecycle.action,label:copy.label,explanation:copy[audience],occurredAt,provenance:"immutable_evidence_row_data",evidenceState:lifecycle.state,metadata:evidenceMetadata(evidence,audience)}) }
  for (const scheduler of rows.schedulerEvents ?? []) { if (!scheduler.status || !scheduler.updated_at) continue; const action=schedulerDerivedAction(scheduler.status); const copy=actionCopy(action,audience); const safeGateCode=typeof scheduler.safe_error_code === "string" && /^[A-Z0-9_]{1,80}$/.test(scheduler.safe_error_code) ? scheduler.safe_error_code : undefined; const gateWording=scheduleGateWording(safeGateCode,audience); add({id:`scheduler:${scheduler.id}:${scheduler.status}`,kind:"scheduler",category:"scheduling",action,label:action.startsWith("scheduler_") ? `Scheduler ${scheduler.status}` : copy.label,explanation:`${action.startsWith("scheduler_") ? "A scheduler state was recorded for this publication attempt." : copy[audience]}${gateWording ? ` ${gateWording}` : ""}`,occurredAt:scheduler.processed_at ?? scheduler.blocked_at ?? scheduler.superseded_at ?? scheduler.cancelled_at ?? scheduler.updated_at,provenance:"derived_lifecycle_event",metadata:audience==="operator"?{schedulerEventId:scheduler.id,eventType:scheduler.event_type,status:scheduler.status,scheduleRevision:scheduler.schedule_revision,safeGateCode}:undefined}) }
  let correlated=collapsePublicationConfirmations(entries); const proofSurvives=correlated.some(entry=>entry.action==="operator_onlyfans_manual_completion_proof_recorded"); const completionIdempotency=(rows.idempotencyRows ?? []).find(row=>row?.action_type==="manual_completion" && (!rows.task?.id || row?.queue_task_id===rows.task.id));
  if (!proofSurvives && rows.task?.status === "confirmed_posted_manual" && rows.task.posted_at) { const snapshot=completionIdempotency?.internal_request_snapshot ?? {}; correlated.push({id:`reconstructed:${rows.task.id}`,kind:"completion",category:"completion",action:"manual_completion_reconstructed",label:"Manual publication confirmed",explanation:"Completion proof was reconstructed from existing trusted completion state.",occurredAt:rows.task.posted_at,provenance:"reconstructed_completion_state",evidenceState:snapshot.evidence_intent_id?"proof present":"proof metadata limited",finalPostUrl:rows.task.final_post_url??snapshot.final_post_url??null,noUrlReason:rows.task.final_post_url_skip_reason??snapshot.final_post_url_skip_reason??null,metadata:audience==="operator" ? {queueTaskId:rows.task.id,platformJobId:rows.job?.id,evidenceIntentId:snapshot.evidence_intent_id,mimeType:snapshot.normalized_mime_type,actualSizeBytes:snapshot.actual_size_bytes,digest:typeof snapshot.verified_sha256 === "string" ? `${snapshot.verified_sha256.slice(0,12)}…` : undefined}:undefined,completionGroup:completionGroup(rows.job?.id,rows.task.posted_at),completionPriority:40}); correlated=collapsePublicationConfirmations(correlated) }
  const byKey=new Map<string,InternalHistoryEntry>(); for (const entry of correlated) { const key=displayDeduplicationKey(entry); const prior=byKey.get(key); if(!prior || (prior.provenance!=="append_only_audit_evidence" && entry.provenance==="append_only_audit_evidence")) byKey.set(key,entry) }
  const sorted=sortOnlyFansHistoryEntries([...byKey.values()],"oldest"); const publicEntries=sorted.map(entry=>{ const {completionGroup:_,completionPriority:__,...publicEntry}=entry; if(publicEntry.noUrlReason) publicEntry.explanation += ` ${noUrlReasonLabel(publicEntry.noUrlReason)}`; return publicEntry }); return {ok:true,timezone,timezoneLabel:timezone,entries:publicEntries}
}
