import { actionCopy, evidenceStatusLabel, noUrlReasonLabel, rejectionWording } from "./presentation"
import { normalizeHistoryTimezone } from "./timezone"
import type { OnlyFansHistoryAudience, OnlyFansHistoryEntry, OnlyFansHistoryRows, OnlyFansHistoryView } from "./types"
function iso(v:any){ return typeof v === "string" && !Number.isNaN(Date.parse(v)) ? v : null }
function metaValue(v:any){ return typeof v === "string" || typeof v === "number" || typeof v === "boolean" || v == null ? v : JSON.stringify(v) }
function completionKey(e:OnlyFansHistoryEntry){ return e.kind === "completion" ? `completion:${e.occurredAt}` : e.kind === "scheduler" ? `scheduler:${e.action}:${e.metadata?.schedulerEventId ?? ""}` : e.action === "operator_onlyfans_expired_claim_recovered" ? `claim-expired:${e.occurredAt}` : e.id }
export function normalizeOnlyFansHistory(rows: OnlyFansHistoryRows, audience: OnlyFansHistoryAudience): OnlyFansHistoryView {
  const timezone=normalizeHistoryTimezone(rows.job?.schedule_timezone); const entries:OnlyFansHistoryEntry[]=[];
  const add=(e:OnlyFansHistoryEntry)=>{ if(iso(e.occurredAt)) entries.push(e) }
  if (rows.plan?.created_at) add({id:`plan:${rows.plan.id}:created`,kind:"lifecycle",action:"plan_created",label:"Publishing plan created",explanation:"The publishing plan was created.",occurredAt:rows.plan.created_at,provenance:"derived_lifecycle_event",metadata:{planId:rows.plan.id}})
  if (rows.job?.created_at) add({id:`job:${rows.job.id}:created`,kind:"lifecycle",action:"platform_job_created",label:"OnlyFans job created",explanation:"An assisted/manual OnlyFans publishing job was created.",occurredAt:rows.job.created_at,provenance:"derived_lifecycle_event",metadata:{platformJobId:rows.job.id}})
  for (const a of rows.auditEvents ?? []) { const after=a.after_state ?? {}; const copy=actionCopy(a.action,audience); const code=after.rejection_code; add({id:`audit:${a.id}`,kind:a.action.includes("rejected")?"rejection":a.action.includes("completion")?"completion":a.entity_type?.includes("scheduler")?"scheduler":"lifecycle",action:a.action,label:copy.label,explanation:code ? (rejectionWording[code]?.[audience] ?? "Completion was rejected.") : copy[audience],occurredAt:a.created_at,sortAuditId:Number(a.id),provenance:"append_only_audit_evidence",evidenceState:after.evidence_intent_id?"proof present":null,finalPostUrl:after.final_post_url??null,noUrlReason:after.final_post_url_skip_reason??null,metadata: audience==="operator" ? Object.fromEntries(Object.entries({entityType:a.entity_type,entityId:a.entity_id,actorId:a.actor_id,queueTaskId:after.queue_task_id,platformJobId:after.platform_job_id,evidenceIntentId:after.evidence_intent_id,rejectionCode:code,mimeType:after.normalized_mime_type,actualSizeBytes:after.actual_size_bytes,digest: typeof after.verified_sha256 === "string" ? `${after.verified_sha256.slice(0,12)}…` : undefined}).map(([k,v])=>[k,metaValue(v)])) : undefined}) }
  for (const ev of rows.evidenceIntents ?? []) { const at=ev.consumed_at ?? ev.verified_at ?? ev.invalidated_at ?? ev.failed_at ?? ev.expired_at ?? ev.created_at; add({id:`evidence:${ev.id}:${ev.status}`,kind:"evidence",action:`evidence_${ev.status}`,label:evidenceStatusLabel(ev.status),explanation:ev.status === "consumed" ? "Completion proof was consumed by the manual confirmation." : evidenceStatusLabel(ev.status),occurredAt:at,provenance:"immutable_evidence_row_data",evidenceState:ev.status,metadata: audience==="operator" ? {evidenceIntentId:ev.id,replacesIntentId:ev.replaces_intent_id,replacedByIntentId:ev.replaced_by_intent_id,mimeType:ev.normalized_mime_type,actualSizeBytes:ev.actual_size_bytes,digest: typeof ev.verified_sha256 === "string" ? `${ev.verified_sha256.slice(0,12)}…` : undefined,failureCode:ev.failure_code} : {evidenceState:ev.status}}) }
  const hasProof=entries.some(e=>e.action==="operator_onlyfans_manual_completion_proof_recorded");
  if (!hasProof && rows.task?.status === "confirmed_posted_manual" && rows.task.posted_at) { const snap=(rows.idempotencyRows ?? [])[0]?.internal_request_snapshot ?? {}; add({id:`reconstructed:${rows.task.id}`,kind:"completion",action:"manual_completion_reconstructed",label:"Manual publication confirmed",explanation:"Completion proof was reconstructed from existing trusted completion state.",occurredAt:rows.task.posted_at,provenance:"reconstructed_completion_state",evidenceState:snap.evidence_intent_id?"proof present":"proof metadata limited",finalPostUrl:rows.task.final_post_url??snap.final_post_url??null,noUrlReason:rows.task.final_post_url_skip_reason??snap.final_post_url_skip_reason??null,metadata: audience==="operator" ? {queueTaskId:rows.task.id,platformJobId:rows.job?.id,evidenceIntentId:snap.evidence_intent_id,mimeType:snap.normalized_mime_type,actualSizeBytes:snap.actual_size_bytes,digest: typeof snap.verified_sha256 === "string" ? `${snap.verified_sha256.slice(0,12)}…` : undefined} : undefined}) }
  for (const s of rows.schedulerEvents ?? []) { if (!s.status || !s.updated_at) continue; add({id:`scheduler:${s.id}:${s.status}`,kind:"scheduler",action:`scheduler_${s.status}`,label:`Scheduler ${s.status}`,explanation:"Scheduler state was recorded for this OnlyFans job.",occurredAt:s.processed_at ?? s.blocked_at ?? s.superseded_at ?? s.updated_at,provenance:"derived_lifecycle_event",metadata:{schedulerEventId:s.id,status:s.status}}) }
  const byKey=new Map<string,OnlyFansHistoryEntry>();
  for (const e of entries) { const key=completionKey(e); const prior=byKey.get(key); if(!prior || (prior.provenance!=="append_only_audit_evidence" && e.provenance==="append_only_audit_evidence")) byKey.set(key,e) }
  const sorted=[...byKey.values()].sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt) || (a.sortAuditId??Number.MAX_SAFE_INTEGER)-(b.sortAuditId??Number.MAX_SAFE_INTEGER) || a.id.localeCompare(b.id));
  for (const e of sorted) if(e.noUrlReason) e.explanation += ` ${noUrlReasonLabel(e.noUrlReason)}`
  return {ok:true,timezone,timezoneLabel:timezone,entries:sorted}
}
