export type OnlyFansHistoryProvenance = "append_only_audit_evidence" | "immutable_evidence_row_data" | "reconstructed_completion_state" | "derived_lifecycle_event"
export type OnlyFansHistoryAudience = "creator" | "operator"
export type OnlyFansHistoryKind = "lifecycle" | "scheduler" | "operator" | "evidence" | "completion" | "rejection"
export type OnlyFansHistoryEntry = { id:string; kind:OnlyFansHistoryKind; action:string; label:string; explanation:string; occurredAt:string; sortAuditId?:number|null; provenance:OnlyFansHistoryProvenance; evidenceState?:string|null; finalPostUrl?:string|null; noUrlReason?:string|null; metadata?:Record<string,string|number|boolean|null|undefined> }
export type OnlyFansHistorySuccessView = { ok:true; timezone:string; timezoneLabel:string; entries:OnlyFansHistoryEntry[] }
export type OnlyFansHistoryErrorView = { ok:false; code:"not_found"|"sign_in_required"|"service_unavailable"; message:string }
export type OnlyFansHistoryView = OnlyFansHistorySuccessView | OnlyFansHistoryErrorView
export type OnlyFansCreatorHistoryAttempt = { platformJobId:string; jobState:string; createdAt:string; taskLinkState:"exact"|"limited"; history:OnlyFansHistorySuccessView }
export type OnlyFansCreatorPackageHistoryView = { ok:true; attempts:OnlyFansCreatorHistoryAttempt[] } | OnlyFansHistoryErrorView
export type OnlyFansHistoryRows = { plan?:any|null; job?:any|null; task?:any|null; schedulerEvents?:any[]; auditEvents?:any[]; evidenceIntents?:any[]; idempotencyRows?:any[] }
