import type { NormalizedVerificationInput, VerificationDecision, VerificationInput, VerificationSubjectType } from "./types"
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const IDEM = /^[A-Za-z0-9_-]{8,128}$/
const CONTROL = /[\u0000-\u001F\u007F]/
const SECRET = /(password|passwd|token|secret|cookie|session|api[_-]?key|bearer\s+[a-z0-9._-]+)/i
export function normalizeSubjectType(value: string): VerificationSubjectType { const v = value.trim().toLowerCase(); if (v !== "creator" && v !== "platform_account") throw new Error("VERIFICATION_INVALID_SUBJECT"); return v }
export function normalizeDecision(value: string): VerificationDecision { const v = value.trim().toLowerCase(); if (!["verify","revoke","mark_unverified"].includes(v)) throw new Error("VERIFICATION_INVALID_DECISION"); return v as VerificationDecision }
export function normalizeReason(value: string): string { if (CONTROL.test(value)) throw new Error("VERIFICATION_REASON_REQUIRED"); const v = value.trim().replace(/\s+/g, " "); if (!v) throw new Error("VERIFICATION_REASON_REQUIRED"); if (v.length > 1000) throw new Error("VERIFICATION_REASON_REQUIRED"); return v }
export function normalizeEvidenceReference(value: string | null | undefined, decision: VerificationDecision): string | null { const v = (value ?? "").trim().replace(/\s+/g, " "); if (!v) { if (decision === "verify") throw new Error("VERIFICATION_EVIDENCE_REQUIRED"); return null } if (v.length > 500 || CONTROL.test(v) || SECRET.test(v)) throw new Error("VERIFICATION_EVIDENCE_REQUIRED"); return v }
export function normalizeUuid(value: string): string { if (!UUID.test(value)) throw new Error("VERIFICATION_INVALID_SUBJECT"); return value }
export function normalizeTimestamp(value: string | null | undefined): string | null { if (value == null || value === "") return null; if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/.test(value) || Number.isNaN(Date.parse(value))) throw new Error("VERIFICATION_STALE"); return value }
export function normalizeIdempotencyKey(value: string | null | undefined): string { const v = (value ?? "").trim(); if (!IDEM.test(v)) throw new Error("VERIFICATION_IDEMPOTENCY_CONFLICT"); return v }
export function rejectProtectedBrowserFields(input: VerificationInput) { for (const key of ["reviewerId","actorRole","targetStatus","password","token","cookie","session","apiKey"] as const) if ((input as any)[key] !== undefined) throw new Error(key === "reviewerId" || key === "actorRole" || key === "targetStatus" ? "VERIFICATION_UNAUTHORIZED" : "VERIFICATION_EVIDENCE_REQUIRED") }
export function normalizeVerificationInput(input: VerificationInput): NormalizedVerificationInput { rejectProtectedBrowserFields(input); const decision = normalizeDecision(input.decision); return { subjectType: normalizeSubjectType(input.subjectType), subjectId: normalizeUuid(input.subjectId), decision, reason: normalizeReason(input.reason), evidenceReference: normalizeEvidenceReference(input.evidenceReference, decision), expectedUpdatedAt: normalizeTimestamp(input.expectedUpdatedAt), idempotencyKey: normalizeIdempotencyKey(input.idempotencyKey) } }
