"use client"
import { useEffect, useState } from "react"
import { supabaseBrowser } from "@/lib/supabase"

type Factor = { id: string; friendly_name?: string }
type Enrollment = { id: string; qr: string; secret: string }
export default function SecurityClient() {
  const [factors, setFactors] = useState<Factor[]>([]), [enrollment, setEnrollment] = useState<Enrollment | null>(null)
  const [code, setCode] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false)
  const supabase = supabaseBrowser()
  async function refresh() { const { data, error } = await supabase.auth.mfa.listFactors(); if (error) setMessage("Security settings are temporarily unavailable."); else setFactors(data.totp.filter((f) => f.status === "verified")) }
  useEffect(() => { void refresh() }, [])
  async function enroll() { setBusy(true); setMessage(""); const { data, error } = await supabase.auth.mfa.enroll({ factorType: "totp", friendlyName: `Authenticator ${factors.length + 1}` }); setBusy(false); if (error) return setMessage("Enrollment could not be started."); setEnrollment({ id: data.id, qr: data.totp.qr_code, secret: data.totp.secret }) }
  async function cancel() { if (enrollment) await supabase.auth.mfa.unenroll({ factorId: enrollment.id }); setEnrollment(null); setCode("") }
  async function verify() { if (!enrollment) return; setBusy(true); const { error } = await supabase.auth.mfa.challengeAndVerify({ factorId: enrollment.id, code: code.trim() }); setBusy(false); if (error) return setMessage("The verification code was not accepted."); setEnrollment(null); setCode(""); setMessage("Authenticator added."); await refresh() }
  async function remove(target: Factor) { if (!confirm(`Remove ${target.friendly_name ?? "this authenticator"}?`)) return; const stepFactor = prompt("Enter the ID of the authenticator to use for fresh verification:", factors[0]?.id); const owned = factors.find((f) => f.id === stepFactor); if (!owned) return setMessage("Select an authenticator owned by this account."); const otp = prompt("Enter its current six-digit code:"); if (!otp) return; setBusy(true); const verified = await supabase.auth.mfa.challengeAndVerify({ factorId: owned.id, code: otp.trim() }); if (verified.error) { setBusy(false); return setMessage("Fresh verification failed; nothing was removed.") } const result = await fetch("/api/account/security/mfa/factors", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ factorId: target.id }) }); setBusy(false); if (!result.ok) return setMessage("The authenticator was not removed."); setMessage("Authenticator removed."); await supabase.auth.refreshSession(); await refresh() }
  return <main className="min-h-screen bg-gray-950 text-white p-8"><div className="mx-auto max-w-2xl space-y-6"><h1 className="text-3xl font-bold">Account security</h1><p className="text-gray-300">Authenticator-app two-factor authentication is optional. Keep access to at least one verified authenticator. If you lose all factors, contact support; Sirens Forge does not provide recovery codes.</p>
    <section className="rounded-xl border border-gray-700 p-5"><h2 className="text-xl font-semibold">Verified authenticators</h2>{factors.length ? factors.map((f) => <div className="mt-3 flex justify-between" key={f.id}><span>{f.friendly_name ?? "Authenticator"}</span><button disabled={busy} onClick={() => void remove(f)} className="text-rose-300">Remove</button></div>) : <p className="mt-2 text-gray-400">No authenticator is enrolled.</p>}</section>
    {!enrollment ? <button disabled={busy} onClick={() => void enroll()} className="rounded bg-cyan-600 px-4 py-2">Add authenticator</button> : <section className="space-y-3 rounded-xl border border-cyan-700 p-5"><h2 className="text-xl">Finish enrollment</h2><img src={enrollment.qr} alt="Authenticator enrollment QR code" className="bg-white p-2" /><p>Manual secret: <code className="break-all">{enrollment.secret}</code></p><input className="bg-gray-800 p-2" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(e) => setCode(e.target.value)} /><div className="space-x-3"><button disabled={busy || !/^\d{6}$/.test(code.trim())} onClick={() => void verify()} className="rounded bg-cyan-600 px-4 py-2">Verify and activate</button><button onClick={() => void cancel()}>Cancel</button></div></section>}
    {message && <p role="status">{message}</p>}</div></main>
}
