import { z } from "zod"
import type { CreatorPlatform, PlatformAccountInput } from "./types"

export const CREATOR_ACCOUNT_PLATFORMS = ["onlyfans", "fansly"] as const
export const ATTESTATION_COPY = "I confirm that this account belongs to me or that I am authorized to manage content for it, and that the account information above is accurate."
export const PRIVACY_COPY = "Sirens Forge stores only a reference to your platform account. It does not store your password, tokens, cookies, or login session and does not log into the platform."
const HOSTS: Record<CreatorPlatform, string[]> = { onlyfans: ["onlyfans.com", "www.onlyfans.com"], fansly: ["fansly.com", "www.fansly.com"] }
const uuidSchema = z.string().uuid()
const idempotencySchema = z.string().trim().regex(/^[A-Za-z0-9_-]{8,128}$/)
export const createAccountSchema = z.object({ operation: z.literal("create"), platform: z.enum(CREATOR_ACCOUNT_PLATFORMS), platformUsername: z.string(), profileUrl: z.string().optional().nullable(), isVirtualEntity: z.boolean().default(false), creatorAttested: z.boolean().default(false), idempotencyKey: idempotencySchema })
export const updateAccountSchema = createAccountSchema.extend({ operation: z.literal("update"), accountId: uuidSchema })
export function normalizePlatform(input: string): CreatorPlatform { const p = input.trim().toLowerCase(); if (p === "fanvue") throw Object.assign(new Error("Fanvue is not available for creator account setup."), { code: "FANVUE_NOT_AVAILABLE" }); if (p !== "onlyfans" && p !== "fansly") throw Object.assign(new Error("Unsupported platform."), { code: "UNSUPPORTED_PLATFORM" }); return p }
export function normalizeUsername(input: string): string { const value = input.trim(); if (!value) throw Object.assign(new Error("Platform username is required."), { code: "INVALID_USERNAME" }); if (value.length > 80) throw Object.assign(new Error("Platform username is too long."), { code: "INVALID_USERNAME" }); return value }
function isIp(hostname: string) { return /^\d{1,3}(\.\d{1,3}){3}$/.test(hostname) || hostname.includes(":") }
export function normalizeProfileUrl(input: string | null | undefined, platform: CreatorPlatform): string | null { const raw = (input ?? "").trim(); if (!raw) return null; if (raw.length > 300) throw Object.assign(new Error("Profile URL is too long."), { code: "INVALID_PROFILE_URL" }); let url: URL; try { url = new URL(raw) } catch { throw Object.assign(new Error("Profile URL is malformed."), { code: "INVALID_PROFILE_URL" }) } if (url.protocol !== "https:" || url.username || url.password || isIp(url.hostname) || url.hostname === "localhost" || !HOSTS[platform].includes(url.hostname.toLowerCase()) || url.search || url.hash) throw Object.assign(new Error("Profile URL must be a clean HTTPS reference for the selected platform without credentials, query strings, or fragments."), { code: "INVALID_PROFILE_URL" }); return url.toString() }
function rejectBrowserControlled(input: PlatformAccountInput) { if (input.creatorId !== undefined || input.password !== undefined || input.token !== undefined || input.cookie !== undefined || input.apiKey !== undefined || input.session !== undefined) throw Object.assign(new Error("Unsupported account form fields."), { code: "INVALID_FORM" }) }
export function normalizeCreateAccountInput(input: PlatformAccountInput) { rejectBrowserControlled(input); if (input.operation !== "create") throw Object.assign(new Error("Invalid account operation."), { code: "INVALID_FORM" }); const parsed = createAccountSchema.safeParse({ ...input, platform: normalizePlatform(input.platform), idempotencyKey: input.idempotencyKey ?? "" }); if (!parsed.success) throw Object.assign(new Error("Invalid account form."), { code: "INVALID_FORM" }); const platform = parsed.data.platform; return { accountId: null, platform, platformUsername: normalizeUsername(parsed.data.platformUsername), profileUrl: normalizeProfileUrl(parsed.data.profileUrl, platform), isVirtualEntity: Boolean(parsed.data.isVirtualEntity), creatorAttested: Boolean(parsed.data.creatorAttested), idempotencyKey: parsed.data.idempotencyKey } }
export function normalizeUpdateAccountInput(input: PlatformAccountInput) { rejectBrowserControlled(input); if (input.operation !== "update") throw Object.assign(new Error("Invalid account operation."), { code: "INVALID_FORM" }); const platform = normalizePlatform(input.platform); const parsed = updateAccountSchema.safeParse({ ...input, platform, idempotencyKey: input.idempotencyKey ?? "" }); if (!parsed.success) throw Object.assign(new Error("Invalid account form."), { code: "INVALID_FORM" }); return { accountId: parsed.data.accountId, platform, platformUsername: normalizeUsername(parsed.data.platformUsername), profileUrl: normalizeProfileUrl(parsed.data.profileUrl, platform), isVirtualEntity: Boolean(parsed.data.isVirtualEntity), creatorAttested: Boolean(parsed.data.creatorAttested), idempotencyKey: parsed.data.idempotencyKey } }
export function normalizeAccountInput(input: PlatformAccountInput) { return input.operation === "create" ? normalizeCreateAccountInput(input) : normalizeUpdateAccountInput(input) }
