import assert from "node:assert/strict";import{executeAffiliatePayouts,type PayoutItem}from"../../../lib/payment-v2/payoutService";
let assertions=0;const eq=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);assertions++};const item:PayoutItem={id:"10000000-0000-4000-8000-000000000001",ledger_id:"20000000-0000-4000-8000-000000000001",amount_cents:5000,currency:"usd",source_charge_id:"ch_verified",connect_destination:"acct_bound",transfer_idempotency_key:"pfc03d:10000000-0000-4000-8000-000000000001",execution_status:"pending"};
{const calls:any[]=[];const result=await executeAffiliatePayouts({loadPending:async()=>[item],reconcileRecurring:async()=>true,beginDispatch:async()=>({...item,execution_status:"dispatching"}),createTransfer:async(p,k)=>{calls.push([p,k]);return{id:"tr_exact"}},complete:async(i,t)=>{calls.push([i,t]);return true},recordFailure:async()=>{throw 0}});eq(result,{succeeded:1,pending:0,failed:0},"success");eq(calls[0][0].source_transaction,"ch_verified","verified source charge");eq(calls[0][1],item.transfer_idempotency_key,"durable idempotency key");}
{let transfers=0,completed=0;const result=await executeAffiliatePayouts({loadPending:async()=>[item],reconcileRecurring:async()=>true,beginDispatch:async()=>({...item,execution_status:"dispatching"}),createTransfer:async()=>{transfers++;throw new Error("retry")},complete:async()=>{completed++;return true},recordFailure:async()=>{}});eq(result.failed,1,"failure retryable");eq([transfers,completed],[1,0],"failed transfer never completes ledger");}
{let transfers=0;const result=await executeAffiliatePayouts({loadPending:async()=>[{...item,payment_v2_recurring_invoice_id:"x"}],reconcileRecurring:async()=>false,beginDispatch:async()=>null,createTransfer:async()=>{transfers++;return{id:"tr_bad"}},complete:async()=>true,recordFailure:async()=>{}});eq(result.pending,1,"stale recurring remains pending");eq(transfers,0,"no unreconciled transfer");}
{const created=new Map<string,string>();let physical=0;const deps={loadPending:async()=>[item],reconcileRecurring:async()=>true,beginDispatch:async()=>({...item,execution_status:"dispatching"}),async createTransfer(_p:any,key:string){if(!created.has(key)){physical++;created.set(key,"tr_idempotent")}return{id:created.get(key)!}},complete:async()=>true,recordFailure:async()=>{}};await executeAffiliatePayouts(deps);await executeAffiliatePayouts(deps);eq(physical,1,"duplicate dispatch produces one transfer under durable Stripe idempotency identity");}
{const order:string[]=[];const corrected={...item,amount_cents:2500,source_charge_id:"ch_reconciled",execution_status:"dispatching"};let sent:any;await executeAffiliatePayouts({loadPending:async()=>[{...item,payment_v2_recurring_invoice_id:"ri",execution_status:"pending"}],reconcileRecurring:async()=>{order.push("reconcile");return true},beginDispatch:async()=>{order.push("dispatching");return corrected},createTransfer:async(p,k)=>{order.push("stripe");sent=[p,k];return{id:"tr_corrected"}},complete:async()=>true,recordFailure:async()=>{}});eq(order,["reconcile","dispatching","stripe"],"durable dispatch marker precedes Stripe");eq([sent[0].amount,sent[0].source_transaction],[2500,"ch_reconciled"],"unattempted reconciliation refresh is the frozen transfer payload");}
{const frozen={...item,execution_status:"dispatching"};const payloads:any[]=[];const deps={loadPending:async()=>[frozen],reconcileRecurring:async()=>{throw new Error("dispatch payload must not be reconciled")},beginDispatch:async()=>frozen,createTransfer:async(p:any,k:string)=>{payloads.push([p,k]);throw new Error("crash_after_dispatch")},complete:async()=>true,recordFailure:async()=>{}};await executeAffiliatePayouts(deps);await executeAffiliatePayouts(deps);eq(payloads[0],payloads[1],"dispatch retry preserves byte-for-byte parameters and idempotency key");}
{let invocation=0,reconciliations=0,transfers=0;const recurring={...item,payment_v2_recurring_invoice_id:"ri",execution_status:"pending"};const deps={loadPending:async()=>[recurring],reconcileRecurring:async()=>{reconciliations++;return true},beginDispatch:async()=>++invocation===1?null:{...recurring,execution_status:"dispatching"},createTransfer:async()=>{transfers++;return{id:"tr_recovered"}},complete:async()=>true,recordFailure:async()=>{}};eq((await executeAffiliatePayouts(deps)).pending,1,"termination before dispatch leaves item retryable");eq((await executeAffiliatePayouts(deps)).succeeded,1,"next invocation reaches dispatch without ready-state deadlock");eq([reconciliations,transfers],[2,1],"crash recovery repeats authoritative reconciliation before one transfer");}
console.log(`PFC-CORE-03D payout transfer passed (${assertions} assertions).`)
