import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{paymentFirstWebhook,PAYMENT_V2_WEBHOOK_CONTRACT,type PaymentV2Database,type PaymentV2Provider}from"../../../lib/payment-v2/webhookService";
let assertions=0;const eq=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);assertions++};const hold="10000000-0000-4000-8000-000000000004";
const invoice=(month:number)=>({id:`in_${month}`,status:"paid",customer:"cus",billing_reason:month===1?"subscription_create":"subscription_cycle",amount_paid:1000,amount_due:1000,currency:"usd",parent:{type:"subscription_details",subscription_details:{subscription:"sub"}},lines:{data:[{amount:1000,quantity:1,pricing:{type:"price_details",price_details:{price:"price_early"}},period:{start:month*1000,end:(month+1)*1000}}]},status_transitions:{paid_at:20000}});
function harness(opts:{metadata?:Record<string,string>;history?:any[];embedded?:any}={}){const calls={rpc:[]as any[],lists:0};const sub={id:"sub",customer:"cus",status:"active",metadata:opts.metadata??{checkout_contract_version:PAYMENT_V2_WEBHOOK_CONTRACT,payment_v2_hold_id:hold,tier_name:"early_bird"},items:{data:[{quantity:1,price:{id:"price_early"}}]}};const provider:PaymentV2Provider={constructEvent:()=>({id:"evt",type:"invoice.paid",created:20000,data:{object:opts.embedded??invoice(7)}}),retrieveSession:async()=>{throw 0},retrievePaymentIntent:async(id)=>({id,status:"succeeded",customer:"cus",amount:1000,currency:"usd",latest_charge:`ch_${id.slice(3)}`}),retrieveSubscription:async()=>sub,async listInvoicePayments(id){return[{id:`ip_${id}`,invoice:id,status:"paid",amount_paid:1000,currency:"usd",payment:{type:"payment_intent",payment_intent:`pi_${id.slice(3)}`}}]},async listPaidInvoices(){calls.lists++;return opts.history??[1,2,3,4,5,6,7].map(invoice)}};const db:PaymentV2Database={loadHold:async()=>[],loadTier:async()=>[],loadPurchase:async()=>[],recordPaid:async()=>"",recordTerminal:async()=>"",async reconcilePaidInvoices(a){calls.rpc.push(a);return"reconciled"}};return{calls,run:()=>paymentFirstWebhook({enabled:"true",inboxEnabled:"false",apiKey:"sk",webhookSecret:"wh",signature:"sig",readRawBody:async()=>Buffer.from("signed"),createProvider:()=>provider,createDatabase:()=>db})}}
{const h=harness();eq((await h.run()).body.status,"received","valid Clover V2 invoice processed");eq((h.calls.rpc[0].p_invoices as any[]).map(x=>x.invoiceId),["in_1","in_2","in_3","in_4","in_5","in_6","in_7"],"Invoice Payment evidence reconciled");}
{const h=harness({metadata:{}});eq((await h.run()).body.status,"ignored","legacy acknowledged");eq([h.calls.lists,h.calls.rpc.length],[0,0],"legacy zero mutations");}
{const h=harness({metadata:{checkout_contract_version:PAYMENT_V2_WEBHOOK_CONTRACT,payment_v2_hold_id:"bad",tier_name:"early_bird"}});eq((await h.run()).status,500,"malformed claimed V2 fails closed");}
{const h=harness({history:[invoice(1),invoice(7),invoice(6)]});eq((await h.run()).body.status,"received","out of order reconciled");}
{const h=harness({embedded:{id:"in_oneoff",status:"paid",customer:"cus",billing_reason:"manual"}});eq((await h.run()).body.status,"ignored","one-off invoice bypasses dormant inbox");eq(h.calls.rpc.length,0,"one-off zero mutation");}
{const updated={...invoice(2),billing_reason:"subscription_update"};const h=harness({embedded:updated});eq((await h.run()).body.status,"ignored","V2 subscription update ignored");eq(h.calls.rpc.length,0,"update zero commission mutation");}
const fullSource=readFileSync("lib/payment-v2/webhookService.ts","utf8");const source=fullSource.slice(fullSource.indexOf("async function recurringInvoice"),fullSource.indexOf("function hashBytes"));for(const removed of ["invoice.paid","invoice.payment_intent","invoice.subscription","line.price"])eq(source.includes(removed),false,`${removed} absent from Clover adapter`);
console.log(`PFC-CORE-03D recurring webhook passed (${assertions} assertions).`)
