import assert from"node:assert/strict";import{paymentFirstWebhook,PAYMENT_V2_WEBHOOK_CONTRACT,type PaymentV2Database,type PaymentV2Provider}from"../../../lib/payment-v2/webhookService";
let assertions=0;const eq=(a:unknown,b:unknown,m:string)=>{assert.deepEqual(a,b,m);assertions++};const hold="10000000-0000-4000-8000-000000000004";
const invoice=(month:number)=>({id:`in_${month}`,status:"paid",paid:true,customer:"cus",subscription:"sub",billing_reason:month===1?"subscription_create":"subscription_cycle",amount_paid:1000,amount_due:1000,currency:"usd",payment_intent:{id:`pi_${month}`,status:"succeeded",customer:"cus",amount:1000,currency:"usd",latest_charge:`ch_${month}`},lines:{data:[{amount:1000,quantity:1,price:{id:"price_early"},period:{start:month*1000,end:(month+1)*1000}}]},status_transitions:{paid_at:20000}});
function harness(opts:{metadata?:Record<string,string>;history?:any[];embedded?:any}={}){const calls={rpc:[]as any[],lists:0};const sub={id:"sub",customer:"cus",status:"active",metadata:opts.metadata??{checkout_contract_version:PAYMENT_V2_WEBHOOK_CONTRACT,payment_v2_hold_id:hold,tier_name:"early_bird"},items:{data:[{quantity:1,price:{id:"price_early"}}]}};const provider:PaymentV2Provider={constructEvent:()=>({id:"evt",type:"invoice.paid",created:20000,data:{object:opts.embedded??invoice(7)}}),retrieveSession:async()=>{throw 0},retrievePaymentIntent:async()=>{throw 0},retrieveSubscription:async()=>sub,async listPaidInvoices(){calls.lists++;return opts.history??[1,2,3,4,5,6,7].map(invoice)}};const db:PaymentV2Database={loadHold:async()=>[],loadTier:async()=>[],loadPurchase:async()=>[],recordPaid:async()=>"",recordTerminal:async()=>"",async reconcilePaidInvoices(a){calls.rpc.push(a);return"reconciled"}};return{calls,run:()=>paymentFirstWebhook({enabled:"true",inboxEnabled:"false",apiKey:"sk",webhookSecret:"wh",signature:"sig",readRawBody:async()=>Buffer.from("signed"),createProvider:()=>provider,createDatabase:()=>db})}}
{const h=harness();eq((await h.run()).body.status,"received","valid V2 invoice processed");eq((h.calls.rpc[0].p_invoices as any[]).map(x=>x.invoiceId),["in_1","in_2","in_3","in_4","in_5","in_6","in_7"],"full authoritative history reconciled regardless trigger month");}
{const h=harness({metadata:{}});eq((await h.run()).body.status,"ignored","legacy acknowledged");eq([h.calls.lists,h.calls.rpc.length],[0,0],"legacy makes zero V2 mutations");}
{const h=harness({metadata:{checkout_contract_version:PAYMENT_V2_WEBHOOK_CONTRACT,payment_v2_hold_id:"bad",tier_name:"early_bird"}});eq((await h.run()).status,500,"malformed claimed V2 fails closed");eq(h.calls.rpc.length,0,"malformed makes no mutation");}
{const h=harness({history:[invoice(1),invoice(7),invoice(6)]});eq((await h.run()).body.status,"received","month seven delivery reconciles full history");eq((h.calls.rpc[0].p_invoices as any[]).length,3,"database receives immutable period evidence");}
{const bad=invoice(2);bad.lines.data[0].price.id="other";const h=harness({embedded:invoice(1),history:[invoice(1),bad]});eq((await h.run()).body.status,"received","unrelated price invoice ignored");eq((h.calls.rpc[0].p_invoices as any[]).length,1,"only locked-price invoice reconciled");}
console.log(`PFC-CORE-03D recurring webhook passed (${assertions} assertions).`)
