import { NextRequest, NextResponse } from "next/server";
import { ensureActiveSubscription } from "@/lib/subscription-checker";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { UUID_RE } from "@/lib/video/contract";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const headers={"Cache-Control":"no-store"};
async function subject(context:{params:Promise<{projectId:string}>}) { const auth=await ensureActiveSubscription(); if(!auth.ok||!auth.user) return {response:NextResponse.json({error:auth.error,message:auth.message},{status:auth.status,headers})}; const {projectId}=await context.params; if(!UUID_RE.test(projectId)) return {response:NextResponse.json({error:"NOT_FOUND"},{status:404,headers})}; return {ownerId:auth.user.id,projectId}; }
export async function GET(_req:NextRequest,context:{params:Promise<{projectId:string}>}) { const value=await subject(context); if(value.response)return value.response; const admin=getSupabaseAdmin(); const {data,error}=await admin.rpc("creator_video_project_status",{p_owner_id:value.ownerId,p_project_id:value.projectId}); if(error) return NextResponse.json({error:error.message.includes("VIDEO_PROJECT_NOT_FOUND")?"NOT_FOUND":"VIDEO_STATUS_UNAVAILABLE"},{status:error.message.includes("VIDEO_PROJECT_NOT_FOUND")?404:503,headers}); const status=Array.isArray(data)?data[0]:data; const response:any={project_id:status.project_id,status:status.creator_status,created_at:status.created_at,started_at:status.started_at,completed_at:status.completed_at,safe_error_code:status.safe_error_code,can_cancel:status.can_cancel};
  if(status.creator_status==="completed") { const [{data:project},{data:generation},{data:assets,error:assetError}]=await Promise.all([admin.from("video_projects").select("id,owner_id,identity_id,source_generation_asset_id,request_payload,mode,requested_duration_seconds,completed_at,target_min_short_edge,storage_bucket").eq("id",value.projectId).eq("owner_id",value.ownerId).maybeSingle(),admin.from("generations").select("id,user_id,prompt,negative_prompt,body_type,mode,status,job_type,image_url,completed_at,width,height,metadata").eq("id",value.projectId).eq("user_id",value.ownerId).maybeSingle(),admin.from("generation_assets").select("id,generation_id,owner_id,ordinal,kind,private_storage_objects!inner(storage_class,bucket,object_key,mime_type)").eq("generation_id",value.projectId).eq("owner_id",value.ownerId)]);
    const asset=assets?.[0]; const object=Array.isArray(asset?.private_storage_objects)?asset.private_storage_objects[0]:asset?.private_storage_objects; const canonical=project&&generation&&generation.id===project.id&&generation.status==="completed"&&generation.job_type==="video"&&generation.image_url===null&&assets?.length===1&&asset?.ordinal===0&&asset?.kind==="video"&&object?.storage_class==="creator_generation"&&object?.mime_type==="video/mp4"&&object?.bucket===project.storage_bucket&&new RegExp(`^creator-video-projects/${project.id}/final/[^/]+$`).test(object?.object_key??"");
    if(assetError||!canonical)return NextResponse.json({error:"VIDEO_RESULT_NOT_READY"},{status:409,headers}); const metadata=generation.metadata as any; response.video_result={project_id:project.id,generation_id:generation.id,prompt:generation.prompt,negative_prompt:generation.negative_prompt,mode:project.mode,body_type:generation.body_type,completed_at:generation.completed_at,identity_id:project.identity_id,source_generation_asset_id:project.source_generation_asset_id,requested_duration_seconds:project.requested_duration_seconds,actual_duration_ms:metadata?.actual_duration_ms,fps_millihz:metadata?.fps_millihz,width:generation.width,height:generation.height,output:{id:asset.id,generation_id:asset.generation_id,kind:"video",private_asset:true}};
  } return NextResponse.json(response,{headers}); }
export async function DELETE(_req:NextRequest,context:{params:Promise<{projectId:string}>}) { const value=await subject(context); if(value.response)return value.response; const {data,error}=await getSupabaseAdmin().rpc("cancel_video_project",{p_owner_id:value.ownerId,p_project_id:value.projectId}); if(error)return NextResponse.json({error:error.message.includes("VIDEO_PROJECT_NOT_FOUND")?"NOT_FOUND":"VIDEO_CANCEL_UNAVAILABLE"},{status:error.message.includes("VIDEO_PROJECT_NOT_FOUND")?404:503,headers}); return NextResponse.json({project_id:value.projectId,status:data},{headers}); }
