import { CREATOR_PUBLISHING_MEDIA_SIGNED_URL_EXPIRES_IN_SECONDS, getCreatorPublishingMediaBucket } from "../media/core"
import { actorCanAccessCreator, resolveOperatorJobTask } from "../operator-queue/serviceCore"
import { getAttentionReasons, isActiveOnlyFansAssistedPreparation } from "../operator-queue/status"
import { isValidUuid } from "../operator-queue/validation"
import type { OnlyFansOperatorMediaKind, OnlyFansOperatorMediaMetadataResult, OnlyFansOperatorMediaMode, OnlyFansOperatorMediaRecord, OnlyFansOperatorSignedMediaResult } from "./types"

export const ONLYFANS_OPERATOR_MEDIA_ALLOWED_MIME_TYPES = ["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/webm"] as const
export const ONLYFANS_OPERATOR_MEDIA_CLAIM_EXPIRY_MARGIN_SECONDS = 5
const allowed = new Set<string>(ONLYFANS_OPERATOR_MEDIA_ALLOWED_MIME_TYPES)
const ext: Record<string,string> = { "image/jpeg":"jpg", "image/png":"png", "image/webp":"webp", "image/gif":"gif", "video/mp4":"mp4", "video/webm":"webm" }
const messages = { sign_in_required:"Sign in to access this media.", current_claim_required:"Claim this task to access its media.", media_unavailable:"Media is unavailable.", invalid_request:"Invalid media request.", service_unavailable:"Media service is unavailable." } as const
type Db = { from: (table:string)=>any; rpc: (fn:string,args:Record<string, unknown>)=>Promise<{data:unknown; error:unknown}>; storage?: any }
type Claim = { platformJobId:string; queueTaskId:string; creatorId:string; contentPackageId:string; platformAccountId:string; claimedBy:string; claimedAt:string; claimToken:string; claimExpiresAt:string }
type Deps = { admin: Db; actorId: string | null; now: () => string; bucket?: string }
type MediaRow = { id:string; content_package_id:string; storage_key:string|null; mime_type:string|null; created_at:string }
function fail(code: keyof typeof messages): any { return { ok:false, code, message:messages[code] } }
function rec(v: unknown): Record<string, unknown> | null { return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : null }
function exactKeys(r: Record<string, unknown>, keys: string[]) { const a=Object.keys(r); return a.length === keys.length && keys.every(k=>a.includes(k)) }
export function parseOnlyFansOperatorMediaMode(v: unknown): OnlyFansOperatorMediaMode | null { return v === "preview" || v === "download" ? v : null }
function parseMetadataInput(input: unknown) { if (typeof input === "string") return isValidUuid(input) ? { platformJobId: input } : null; const r=rec(input); if (!r || !exactKeys(r,["platformJobId"]) || typeof r.platformJobId !== "string" || !isValidUuid(r.platformJobId)) return null; return { platformJobId:r.platformJobId } }
function parseSigningInput(input: unknown) { const r=rec(input); if (!r || !exactKeys(r,["platformJobId","mediaAssetId","mode"]) || typeof r.platformJobId !== "string" || typeof r.mediaAssetId !== "string" || !isValidUuid(r.platformJobId) || !isValidUuid(r.mediaAssetId)) return null; const mode=parseOnlyFansOperatorMediaMode(r.mode); return mode ? { platformJobId:r.platformJobId, mediaAssetId:r.mediaAssetId, mode } : null }
function norm(m: unknown) { return typeof m === "string" ? m.trim().toLowerCase() : "" }
export function classifyOnlyFansOperatorMediaKind(mimeType: string): OnlyFansOperatorMediaKind | null { const m=norm(mimeType); if (!allowed.has(m)) return null; return m === "video/mp4" || m === "video/webm" ? "video" : "image" }
export function deriveOnlyFansOperatorMediaFilename(mediaAssetId: string, storageKey: string, mimeType: string) { const fallback = `${mediaAssetId}.${ext[norm(mimeType)] ?? "bin"}`; const raw=(storageKey.split("/").filter(Boolean).pop() ?? "").replace(/[^A-Za-z0-9._-]/g,"_").slice(0,120); return raw && /[A-Za-z0-9]/.test(raw) ? raw : fallback.slice(0,120) }
function project(row: MediaRow, displayOrder: number): OnlyFansOperatorMediaRecord | null { const mimeType=norm(row.mime_type); const kind=classifyOnlyFansOperatorMediaKind(mimeType); const key=row.storage_key?.trim(); if (!kind || !key || row.content_package_id === "") return null; return { mediaAssetId:row.id, filename:deriveOnlyFansOperatorMediaFilename(row.id,key,mimeType), mimeType, kind, createdAt:row.created_at, displayOrder } }
async function one(q:any) { const r=await q.maybeSingle(); if (r.error) throw r.error; return r.data ?? null }
async function many(q:any) { const r=await q; if (r.error) throw r.error; return r.data ?? [] }
function claimFromRow(row: any, actorId: string, nowIso: string): Claim | null { if (row.queueStatus !== "claimed" || row.claimedBy !== actorId || !row.claimedAt || !row.claimToken || !row.claimExpiresAt) return null; const exp=Date.parse(row.claimExpiresAt); if (!Number.isFinite(exp) || exp <= Date.parse(nowIso)) return null; return { platformJobId:row.platformJobId, queueTaskId:row.queueTaskId, creatorId:row.creatorId, contentPackageId:row.contentPackageId, platformAccountId:row.platformAccountId, claimedBy:row.claimedBy, claimedAt:row.claimedAt, claimToken:row.claimToken, claimExpiresAt:row.claimExpiresAt } }
async function loadSafety(admin: Db, ctx: Claim) { const [creator, consent, pkg, account, capability, source] = await Promise.all([
  one(admin.from("creator_publishing_creator_verifications").select("status").eq("creator_id",ctx.creatorId)),
  one(admin.from("creator_publishing_ai_twin_consents").select("status,revoked_at").eq("creator_id",ctx.creatorId)),
  one(admin.from("creator_publishing_content_packages").select("id,creator_id,platform_account_id,target_platform,creator_approval_status,compliance_status").eq("id",ctx.contentPackageId).eq("creator_id",ctx.creatorId).eq("platform_account_id",ctx.platformAccountId).eq("target_platform","onlyfans")),
  one(admin.from("creator_platform_accounts").select("id,creator_id,platform,verification_status").eq("id",ctx.platformAccountId).eq("creator_id",ctx.creatorId).eq("platform","onlyfans")),
  one(admin.from("creator_publishing_platform_capabilities").select("availability_status,publishing_mode").eq("platform","onlyfans")),
  admin.rpc("creator_publishing_job_source_is_current", { p_job_id: ctx.platformJobId })
]); if (source.error) throw source.error; if (!creator || !consent || !pkg || !account || !capability || source.data !== true) return null; return { creator, consent, pkg, account, capability } }
function safetyOk(s:any) { return s?.creator?.status === "verified" && s?.account?.verification_status === "verified" && s?.consent?.status === "granted" && !s?.consent?.revoked_at && s?.pkg?.creator_approval_status === "approved" && ["passed","escalated_approved"].includes(s?.pkg?.compliance_status) && s?.capability?.availability_status === "available" && s?.capability?.publishing_mode === "assisted" }
async function resolveFullEligibility(deps: Deps, platformJobId: string): Promise<Claim | null> { if (!deps.actorId) return null; const row=await resolveOperatorJobTask(deps.admin as any, platformJobId); if (!row || !isActiveOnlyFansAssistedPreparation(row)) return null; const claim=claimFromRow(row, deps.actorId, deps.now()); if (!claim) return null; if (!(await actorCanAccessCreator(deps.admin as any, deps.actorId, row.creatorId))) return null; const safety=await loadSafety(deps.admin, claim); if (!safety || !safetyOk(safety)) return null; const enriched = { ...row, creatorVerificationStatus:safety.creator.status, accountVerificationStatus:safety.account.verification_status, consentStatus:safety.consent.revoked_at ? "revoked" : safety.consent.status, creatorApprovalStatus:safety.pkg.creator_approval_status, complianceStatus:safety.pkg.compliance_status, capabilityAvailabilityStatus:safety.capability.availability_status, capabilityPublishingMode:safety.capability.publishing_mode, sourceFingerprintStale:false }; if (getAttentionReasons(enriched, deps.actorId, Date.parse(deps.now())).length) return null; return claim }
function sameRelationships(a: Claim, b: Claim) { return a.platformJobId===b.platformJobId && a.queueTaskId===b.queueTaskId && a.creatorId===b.creatorId && a.contentPackageId===b.contentPackageId && a.platformAccountId===b.platformAccountId }
function sameClaim(a: Claim, b: Claim) { return sameRelationships(a,b) && a.claimedBy===b.claimedBy && a.claimToken===b.claimToken }
async function resolveFinalClaimOnly(deps: Deps, initial: Claim): Promise<Claim | null> { if (!deps.actorId) return null; const row=await resolveOperatorJobTask(deps.admin as any, initial.platformJobId); if (!row || !isActiveOnlyFansAssistedPreparation(row) || !sameRelationships(initial, { ...initial, platformJobId:row.platformJobId, queueTaskId:row.queueTaskId, creatorId:row.creatorId, contentPackageId:row.contentPackageId, platformAccountId:row.platformAccountId })) return null; const final=claimFromRow(row, deps.actorId, deps.now()); return final && sameClaim(initial, final) ? final : null }
export function calculateOnlyFansOperatorMediaExpiresIn(claimExpiresAt: string, nowIso: string) { const remainingWholeSeconds = Math.floor((Date.parse(claimExpiresAt) - Date.parse(nowIso)) / 1000); const effectiveExpiresIn = Math.min(CREATOR_PUBLISHING_MEDIA_SIGNED_URL_EXPIRES_IN_SECONDS, remainingWholeSeconds - ONLYFANS_OPERATOR_MEDIA_CLAIM_EXPIRY_MARGIN_SECONDS); return Number.isFinite(remainingWholeSeconds) && Number.isInteger(effectiveExpiresIn) && effectiveExpiresIn > 0 ? effectiveExpiresIn : null }
export async function loadOnlyFansOperatorMediaCore(input: unknown, deps: Deps): Promise<OnlyFansOperatorMediaMetadataResult> { if (!deps.actorId) return fail("sign_in_required"); const parsed=parseMetadataInput(input); if (!parsed) return fail("invalid_request"); try { const initial=await resolveFullEligibility(deps, parsed.platformJobId); if (!initial) return fail("current_claim_required"); const rows=await many(deps.admin.from("creator_publishing_media_assets").select("id,content_package_id,storage_key,mime_type,created_at").eq("content_package_id",initial.contentPackageId).order("created_at",{ascending:true}).order("id",{ascending:true})) as MediaRow[]; const records: OnlyFansOperatorMediaRecord[]=[]; for (let i=0;i<rows.length;i++) { if (rows[i].content_package_id !== initial.contentPackageId) return fail("media_unavailable"); const p=project(rows[i], i + 1); if (!p) return fail("media_unavailable"); records.push(p) } const eligible=await resolveFullEligibility(deps, parsed.platformJobId); if (!eligible || !sameClaim(initial, eligible)) return fail("current_claim_required"); const final=await resolveFinalClaimOnly(deps, initial); if (!final) return fail("current_claim_required"); return { ok:true, media:records } } catch { return fail("service_unavailable") } }
export async function createOnlyFansOperatorSignedMediaUrlCore(input: unknown, deps: Deps): Promise<OnlyFansOperatorSignedMediaResult> { if (!deps.actorId) return fail("sign_in_required"); const parsed=parseSigningInput(input); if (!parsed) return fail("invalid_request"); try { const initial=await resolveFullEligibility(deps, parsed.platformJobId); if (!initial) return fail("current_claim_required"); const row=await one(deps.admin.from("creator_publishing_media_assets").select("id,content_package_id,storage_key,mime_type,created_at").eq("id",parsed.mediaAssetId).eq("content_package_id",initial.contentPackageId)) as MediaRow | null; if (!row || row.content_package_id !== initial.contentPackageId) return fail("media_unavailable"); const record=project(row, 1); if (!record) return fail("media_unavailable"); const eligible=await resolveFullEligibility(deps, parsed.platformJobId); if (!eligible || !sameClaim(initial, eligible)) return fail("current_claim_required"); const final=await resolveFinalClaimOnly(deps, initial); if (!final) return fail("current_claim_required"); const expiresIn=calculateOnlyFansOperatorMediaExpiresIn(final.claimExpiresAt, deps.now()); if (!expiresIn) return fail("current_claim_required"); const options = parsed.mode === "download" ? { download: record.filename } : undefined; const signed=await deps.admin.storage.from(deps.bucket ?? getCreatorPublishingMediaBucket()).createSignedUrl(row.storage_key!.trim(), expiresIn, options); if (signed.error || !signed.data?.signedUrl) return fail("service_unavailable"); return { ok:true, value:{ mediaAssetId:record.mediaAssetId, signedUrl:signed.data.signedUrl, expiresIn, mode:parsed.mode, filename:record.filename, mimeType:record.mimeType, kind:record.kind } } } catch { return fail("service_unavailable") } }
