import LegalPageLayout from "@/components/legal/LegalPageLayout"

export default function ContentRemovalPage() {
  return (
    <LegalPageLayout title="Content Removal Policy" lastUpdated="April 27, 2026">
      <section>
        <p>
          Sirens Forge provides a process for individuals and rights holders to
          request the review and removal of content that may violate their
          rights, privacy, or applicable law.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">1. Scope of This Policy</h2>
        <p>
          This policy applies to content generated, uploaded, stored, or
          distributed through Sirens Forge that may involve:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Unauthorized use of likeness or identity</li>
          <li>Privacy violations</li>
          <li>Non-consensual or exploitative content</li>
          <li>Intellectual property concerns</li>
          <li>Content that violates our Terms or Acceptable Use Policy</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold">
          2. Submitting a Removal Request
        </h2>
        <p>
          If you believe content on or generated through Sirens Forge violates
          your rights, you may submit a removal request by contacting us at:
        </p>
        <p className="font-medium">admin@sirensforge.com</p>
        <p>
          Your request should include sufficient detail to allow us to evaluate
          the claim, including:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>A description of the content in question</li>
          <li>Where the content appears (URL, screenshot, or reference)</li>
          <li>The nature of your concern (e.g., privacy, likeness, copyright)</li>
          <li>Any supporting information or documentation</li>
          <li>Contact information for follow-up</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold">3. Review Process</h2>
        <p>
          Sirens Forge will review removal requests in good faith and may request
          additional information if needed. We evaluate requests based on our
          policies, applicable law, and available evidence.
        </p>
        <p>
          Submission of a request does not guarantee removal. We may approve,
          deny, or take partial action depending on the circumstances.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">
          4. Possible Actions
        </h2>
        <p>
          If we determine that action is appropriate, we may:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Remove or restrict access to content</li>
          <li>Disable associated features or outputs</li>
          <li>Suspend or terminate accounts</li>
          <li>Preserve data for legal or investigative purposes</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold">
          5. Identity and AI Content Disclaimer
        </h2>
        <p>
          Sirens Forge is a tool that generates content based on user inputs. We
          do not verify identity ownership, likeness rights, or consent for any
          content submitted or generated by users. Users are solely responsible
          for ensuring they have the necessary rights to use any identity,
          likeness, or reference material.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">
          6. Abuse of Removal Requests
        </h2>
        <p>
          Submitting false, misleading, or abusive removal requests may result in
          denial of the request and potential restriction of access to the
          platform.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">
          7. Law Enforcement and Legal Requests
        </h2>
        <p>
          Sirens Forge may comply with valid legal requests, court orders, or law
          enforcement inquiries. We may preserve or disclose information as
          required by law.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">8. No Guarantee of Removal</h2>
        <p>
          While we review all requests, Sirens Forge is not obligated to remove
          content unless required by applicable law or our internal policies.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">9. Contact</h2>
        <p>
          To submit a removal request or ask questions about this policy, contact
          us at admin@sirensforge.com.
        </p>
      </section>
    </LegalPageLayout>
  )
}