import { evaluateCreatorPublishingCompliance } from "../evaluate"
import { deriveTrustedComplianceInput } from "./deriveInput"
import { parseApplyRpcResponse, parseTrustedFactsRpcResponse } from "./facts"
import type { ApplyRpcArgs, ComplianceSubmissionErrorCode, ComplianceSubmissionInput, ComplianceSubmissionResult, TrustedFactsRpcResponse } from "./types"
export const RFC3339_SUBMISSION_TIMESTAMP_RE=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/
const uuidRe=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, hashRe=/^[0-9a-f]{64}$/, keyRe=/^[A-Za-z0-9_-]{8,128}$/
const allowed = new Set(["contentPackageId","expectedPackageUpdatedAt","expectedMediaManifestHash","idempotencyKey"])
const protectedNames = /(?:creator|account|consent|verification|policy|outcome|rule|ai_|aiDetail|password|token|cookie|session|apiKey|credential)/i
export function safeMessage(code:ComplianceSubmissionErrorCode){ return code==="UNAUTHENTICATED"?"Sign in to run compliance review.": code==="COMPLIANCE_INVALID_FORM"?"Compliance review request was invalid.": code==="COMPLIANCE_STALE"?"Package changed; refresh and try again.": code==="COMPLIANCE_IDEMPOTENCY_CONFLICT"?"This compliance review key was already used.":"Compliance review could not be saved." }
export function normalizeComplianceSubmissionFormInput(entries:Iterable<[string, unknown]>):{ok:true;input:ComplianceSubmissionInput}|{ok:false;code:"COMPLIANCE_INVALID_FORM"}{ const values:Record<string,unknown>={}; const seen=new Set<string>(); for(const [key,value] of entries){ if(key.startsWith("$ACTION_")) continue; if(!allowed.has(key)||seen.has(key)||protectedNames.test(key)|| typeof File!=="undefined"&&value instanceof File || typeof value!=="string") return {ok:false,code:"COMPLIANCE_INVALID_FORM"}; seen.add(key); values[key]=value } if(seen.size!==allowed.size) return {ok:false,code:"COMPLIANCE_INVALID_FORM"}; const contentPackageId=values.contentPackageId, expectedPackageUpdatedAt=values.expectedPackageUpdatedAt, expectedMediaManifestHash=values.expectedMediaManifestHash, idempotencyKey=values.idempotencyKey; if(typeof contentPackageId!=="string"||!uuidRe.test(contentPackageId)) return {ok:false,code:"COMPLIANCE_INVALID_FORM"}; if(typeof expectedPackageUpdatedAt!=="string"||!RFC3339_SUBMISSION_TIMESTAMP_RE.test(expectedPackageUpdatedAt)) return {ok:false,code:"COMPLIANCE_INVALID_FORM"}; if(typeof expectedMediaManifestHash!=="string"||!hashRe.test(expectedMediaManifestHash)) return {ok:false,code:"COMPLIANCE_INVALID_FORM"}; if(typeof idempotencyKey!=="string"||!keyRe.test(idempotencyKey)) return {ok:false,code:"COMPLIANCE_INVALID_FORM"}; return {ok:true,input:{contentPackageId,expectedPackageUpdatedAt,expectedMediaManifestHash,idempotencyKey}} }
export function mapComplianceSubmissionDbError(error:unknown):ComplianceSubmissionErrorCode{ const msg=String((error as any)?.message||(error as any)?.code||""); const codes=["COMPLIANCE_PACKAGE_NOT_FOUND","COMPLIANCE_FANVUE_NOT_SUPPORTED","COMPLIANCE_PLATFORM_ACCOUNT_INVALID","COMPLIANCE_MEDIA_REQUIRED","COMPLIANCE_UNTRUSTED_MEDIA_SOURCE","COMPLIANCE_GENERATION_LINK_INVALID","COMPLIANCE_GENERATION_NOT_FOUND","COMPLIANCE_GENERATION_NOT_OWNED","COMPLIANCE_GENERATION_NOT_ELIGIBLE","COMPLIANCE_PACKAGE_LOCKED","COMPLIANCE_STALE","COMPLIANCE_INVALID_EVALUATION","COMPLIANCE_IDEMPOTENCY_CONFLICT"] as const; return codes.find(c=>msg.includes(c)) ?? "COMPLIANCE_SAVE_FAILED" }
type RpcClient={rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:unknown}>}
export async function submitTrustedComplianceWithDeps(input:ComplianceSubmissionInput,deps:{getAuthenticatedUserId:()=>Promise<string|null>;getAdminClient:()=>RpcClient}):Promise<ComplianceSubmissionResult>{ try{ let creatorId:string|null; try{creatorId=await deps.getAuthenticatedUserId()}catch{return {ok:false,code:"COMPLIANCE_SAVE_FAILED",message:safeMessage("COMPLIANCE_SAVE_FAILED")}} if(!creatorId) return {ok:false,code:"UNAUTHENTICATED",message:safeMessage("UNAUTHENTICATED")}; let admin:RpcClient; try{admin=deps.getAdminClient()}catch{return {ok:false,code:"COMPLIANCE_SAVE_FAILED",message:safeMessage("COMPLIANCE_SAVE_FAILED")}} let factsRes; try{factsRes=await admin.rpc("creator_publishing_load_compliance_facts",{p_creator_id:creatorId,p_content_package_id:input.contentPackageId})}catch{return {ok:false,code:"COMPLIANCE_SAVE_FAILED",message:safeMessage("COMPLIANCE_SAVE_FAILED")}} if(factsRes.error){ const code=mapComplianceSubmissionDbError(factsRes.error); return {ok:false,code,message:safeMessage(code)} } let trusted:TrustedFactsRpcResponse; try{ trusted=parseTrustedFactsRpcResponse(factsRes.data,creatorId); if(trusted.media_manifest_hash!==input.expectedMediaManifestHash) return {ok:false,code:"COMPLIANCE_STALE",message:safeMessage("COMPLIANCE_STALE")} }catch{return {ok:false,code:"COMPLIANCE_SAVE_FAILED",message:safeMessage("COMPLIANCE_SAVE_FAILED")}} const derived=deriveTrustedComplianceInput(trusted.facts); const evaluation=evaluateCreatorPublishingCompliance(derived.input); const args:ApplyRpcArgs={ p_creator_id:creatorId,p_content_package_id:trusted.facts.package.id,p_expected_package_updated_at:input.expectedPackageUpdatedAt,p_facts_fingerprint:trusted.facts_fingerprint,p_media_manifest_hash:trusted.media_manifest_hash,p_policy_version:evaluation.policy_version,p_outcome:evaluation.outcome,p_forced_disclosure_text:evaluation.forced_disclosure_text,p_normalized_caption:evaluation.normalized_caption,p_ai_flag:"ai_generated",p_ai_detail:derived.aiDetail,p_rule_hits:evaluation.rule_hits,p_reasons:evaluation.reasons,p_review_requirements:evaluation.review_requirements,p_evaluator_metadata:evaluation.metadata,p_idempotency_key:input.idempotencyKey}; let applyRes; try{applyRes=await admin.rpc("creator_publishing_apply_automated_compliance_evaluation",args as unknown as Record<string,unknown>)}catch{return {ok:false,code:"COMPLIANCE_SAVE_FAILED",message:safeMessage("COMPLIANCE_SAVE_FAILED")}} if(applyRes.error){ const code=mapComplianceSubmissionDbError(applyRes.error); return {ok:false,code,message:safeMessage(code)} } try{return {ok:true,result:parseApplyRpcResponse(applyRes.data,creatorId,trusted.facts.package.id)}}catch{return {ok:false,code:"COMPLIANCE_SAVE_FAILED",message:safeMessage("COMPLIANCE_SAVE_FAILED")}} }catch{return {ok:false,code:"COMPLIANCE_SAVE_FAILED",message:safeMessage("COMPLIANCE_SAVE_FAILED")}} }
