import type { ComplianceAiDetail, ComplianceInput, ComplianceOutcome, ComplianceRuleHit } from "../types"

export const TRUSTED_FACTS_SCHEMA_VERSION = "creator-publishing-compliance-facts-v1" as const
export const SAFE_ERROR_CODES = ["UNAUTHENTICATED","COMPLIANCE_INVALID_FORM","COMPLIANCE_PACKAGE_NOT_FOUND","COMPLIANCE_FANVUE_NOT_SUPPORTED","COMPLIANCE_PLATFORM_ACCOUNT_INVALID","COMPLIANCE_MEDIA_REQUIRED","COMPLIANCE_UNTRUSTED_MEDIA_SOURCE","COMPLIANCE_GENERATION_LINK_INVALID","COMPLIANCE_GENERATION_NOT_FOUND","COMPLIANCE_GENERATION_NOT_OWNED","COMPLIANCE_GENERATION_NOT_ELIGIBLE","COMPLIANCE_PACKAGE_LOCKED","COMPLIANCE_HUMAN_REVIEW_LOCKED","COMPLIANCE_STALE","COMPLIANCE_INVALID_EVALUATION","COMPLIANCE_IDEMPOTENCY_CONFLICT","COMPLIANCE_SAVE_FAILED"] as const
export type ComplianceSubmissionErrorCode = typeof SAFE_ERROR_CODES[number]
export type Platform = "onlyfans" | "fansly"
export type VerificationStatus = "verified" | "unverified" | "revoked" | "unattested" | "creator_attested"
export type ConsentStatus = "granted" | "revoked" | "missing"
export type TrustedMediaRow = { id:string; storage_key:string; mime_type:string; sha256:string; source:"ai_pipeline"; ai_generation_metadata:{generation_id:string} & Record<string, unknown> }
export type TrustedGenerationRow = { generation_id:string; user_id:string; status:"completed"; lora_used:string|null; job_type:string|null; body_type:string|null; mode:string|null; r2_bucket:string; r2_key:string; safe_classification_metadata: Partial<Record<keyof ComplianceAiDetail, boolean>> }
export type TrustedComplianceFacts = { schema_version: typeof TRUSTED_FACTS_SCHEMA_VERSION; package:{ id:string; creator_id:string; platform_account_id:string; target_platform:Platform; title:string; caption_body:string; second_person_present:boolean; creator_approval_status:string; compliance_status:string; compliance_policy_version:string|null; updated_at:string }; platform_account:{ id:string; creator_id:string; platform:Platform; verification_status:VerificationStatus; updated_at:string|null; is_virtual_entity:boolean }; creator_verification:{ status:VerificationStatus; updated_at:string|null }; ai_twin_consent:{ status:ConsentStatus; attestation_version:string|null; attestation_text_sha256:string|null; granted_at:string|null; revoked_at:string|null; updated_at:string|null }; media_manifest:TrustedMediaRow[]; generation_manifest:TrustedGenerationRow[]; co_performer_summary:{ record_count:number; all_platform_release_confirmed:boolean }; active_queue_task:boolean; human_review_lock:{ locked:boolean; reason:string|null; latest_review_id:string|null; latest_review_outcome:string|null; latest_review_created_at:string|null } }
export type TrustedFactsRpcResponse = { facts:TrustedComplianceFacts; facts_fingerprint:string; media_manifest_hash:string }
export type ComplianceSubmissionInput = { contentPackageId:string; expectedPackageUpdatedAt:string; expectedMediaManifestHash:string; idempotencyKey:string }
export type ComplianceSubmissionApplyResponse = { content_package_id:string; creator_id:string; prior_compliance_status:string|null; resulting_compliance_status:ComplianceOutcome; policy_version:string; review_record_id:string; audit_event_ids:[string]; idempotent:boolean; outcome:"evaluated"|"idempotent"; evaluated_at:string; updated_at:string }
export type ComplianceSubmissionResult = { ok:true; result:ComplianceSubmissionApplyResponse } | { ok:false; code:ComplianceSubmissionErrorCode; message:string }
export type DerivedCompliance = { input:ComplianceInput; aiDetail:ComplianceAiDetail }
export type ApplyRpcArgs = { p_creator_id:string; p_content_package_id:string; p_expected_package_updated_at:string; p_facts_fingerprint:string; p_media_manifest_hash:string; p_policy_version:string; p_outcome:ComplianceOutcome; p_forced_disclosure_text:string|null; p_normalized_caption:string; p_ai_flag:"ai_generated"; p_ai_detail:ComplianceAiDetail; p_rule_hits:readonly ComplianceRuleHit[]; p_reasons:readonly string[]; p_review_requirements:readonly string[]; p_evaluator_metadata:Record<string, unknown>; p_effective_ai_twin_consent_status:"granted"|"missing"|"not_applicable"; p_idempotency_key:string }
