import assert from "node:assert/strict"
import test from "node:test"
import { validateCreatorReplyCandidate } from "../../../lib/sirens-mind/creator-reply-validator"
const valid=(segments:unknown[],sources:string[]=[])=>validateCreatorReplyCandidate("",{version:2,segments},sources)
test("renders leading commands, questions, challenges, creator actions, and thoughts",()=>{for(const value of ["command_come_closer","command_answer","challenge_continue","ask_intent"])assert.equal(valid([{kind:"speech",value}]).ok,true);for(const [kind,value] of [["action","grin"],["thought","curious"]])assert.equal(valid([{kind,value}]).ok,true)})
test("closed primitives cannot encode command compliance or mid-sentence subscriber action",()=>{assert.equal(valid([{kind:"speech",value:"command_come_closer"}]).text,"Come closer.");for(const text of ["You kneel for me.","I grin as you kneel in front of me."])assert.equal(valid([{kind:"action",value:"grin",text}]).code,"INVALID_SEGMENT")})
test("creator action cannot smuggle environmental props",()=>{assert.equal(valid([{kind:"action",value:"wait",text:"I lean against the dumpster and wait."}]).code,"INVALID_SEGMENT")})
test("free-form dialogue cannot smuggle world state, subscriber action, or motive",()=>{assert.equal(valid([{kind:"speech",value:"cautious",text:"The alley is empty, and I know you came here for me."}]).code,"INVALID_SEGMENT")})
test("grounded evidence must equal one complete authoritative source and renders exactly",()=>{assert.equal(valid([{kind:"grounded",evidence:"dark alley"}],["dark alley"]).text,"dark alley");assert.equal(valid([{kind:"grounded",evidence:"dark alley",text:"A dumpster sits in the dark alley."}],["dark alley"]).code,"UNGROUNDED_REFERENCE");assert.equal(valid([{kind:"grounded",evidence:"dark alley"}],["We meet in a dark alley"]).code,"UNGROUNDED_REFERENCE")})
test("rejects provider prose, malformed metadata, unknown primitives, and generated state",()=>{assert.equal(validateCreatorReplyCandidate("I invent prose.",{version:2,segments:[{kind:"speech",value:"greeting"}]},[]).code,"VISIBLE_CONTENT_FORBIDDEN");assert.equal(validateCreatorReplyCandidate("",{version:1,segments:[]},[]).code,"MALFORMED_METADATA");assert.equal(valid([{kind:"speech",value:"invented"}]).code,"INVALID_SEGMENT");assert.equal(validateCreatorReplyCandidate("",{version:2,segments:[{kind:"speech",value:"greeting"}],state:{}},[]).code,"MALFORMED_METADATA")})
