import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const source = readFileSync("app/api/nsfw-gpt/headless/route.ts", "utf8")
const post = source.slice(source.indexOf("export async function POST"))
const auth = post.indexOf("const auth = await ensureActiveSubscription()")
const deny = post.indexOf("if (!auth.ok)")
const parse = post.indexOf("req.json()")
const provider = post.indexOf("fetch(`${baseUrl}/chat/completions`")
assert.ok(auth >= 0 && auth < deny && deny < parse && parse < provider)
assert.equal((post.match(/fetch\(`\$\{baseUrl\}\/chat\/completions`/g) || []).length, 1)
assert.ok(post.indexOf('error: "PROMPT_ENGINE_UNAVAILABLE"') < provider)
assert.ok(post.includes('interactionMode === "conversation" ? CONVERSATION_GOVERNOR : HEADLESS_CONTRACT'))
assert.ok(post.includes('interactionMode === "conversation" ? [conversationTransport] : []'))
assert.ok(post.includes('interactionMode === "headless" ? [buildOutputTypeSystem(finalOutputType)] : []'))
const mixedModeRejection = post.indexOf("isInvalidInteractionCombination(interactionMode, task, body.refine_type)")
assert.ok(mixedModeRejection >= 0 && mixedModeRejection < provider, "mixed conversation/refine requests must be denied before provider fetch")
for (const bound of ["MAX_DESCRIPTION_CHARS", "MAX_HISTORY_MESSAGES", "MAX_HISTORY_MESSAGE_CHARS", "MAX_HISTORY_TOTAL_CHARS", "MAX_VAULT_IDS", "MAX_MACRO_IDS"]) assert.ok(source.includes(bound))
for (const safeError of ["INVALID_SIRENS_MIND_REQUEST", "PROMPT_ENGINE_UNAVAILABLE", "PROMPT_ENGINE_RESPONSE_INVALID"]) assert.ok(post.includes(safeError))
for (const leak of ["provider_status", "raw_text", "UNHANDLED_EXCEPTION", "err?.message"]) assert.ok(!post.includes(leak), `browser response must not leak ${leak}`)
assert.ok(post.includes('kind === "clarification"'))
assert.ok(post.includes('kind !== "prompt" || !message || !prompt || !target'))
console.log("lock02aSirensMindAuthorization source contract ok")
