import test from "node:test";import assert from "node:assert/strict";import { randomBytes } from "node:crypto"
import { decryptCreatorReplyData, encryptCreatorReplyData } from "../../../lib/sirens-mind/creator-reply-crypto"
import { MAX_RECENT_TURNS, trimCreatorReplyTurns } from "../../../lib/sirens-mind/creator-reply-checkpoint"
const env={SIRENS_MIND_CREATOR_REPLY_DATA_ENCRYPTION_KEY:randomBytes(32).toString("base64"),SIRENS_MIND_CREATOR_REPLY_DATA_KEY_VERSION:"1"} as NodeJS.ProcessEnv
test("Creator Reply encryption is randomized, authenticated, and AAD-bound",()=>{const a=encryptCreatorReplyData("recognizable private fixture","entity:a",env),b=encryptCreatorReplyData("recognizable private fixture","entity:a",env);assert.notEqual(a,b);assert.equal(decryptCreatorReplyData(a,"entity:a",env),"recognizable private fixture");assert.ok(!a.includes("recognizable"));assert.throws(()=>decryptCreatorReplyData(a,"entity:b",env));assert.throws(()=>decryptCreatorReplyData("bad","entity:a",env));assert.throws(()=>encryptCreatorReplyData("x","a",{...env,SIRENS_MIND_CREATOR_REPLY_DATA_ENCRYPTION_KEY:"bad"}))})
test("recent tail retains at most three exchanges and removes oldest first",()=>{const turns=Array.from({length:10},(_,i)=>({role:(i%2?"creator":"subscriber") as "creator"|"subscriber",text:String(i)}));const kept=trimCreatorReplyTurns(turns);assert.equal(kept.length,MAX_RECENT_TURNS);assert.deepEqual(kept.map(x=>x.text),["4","5","6","7","8","9"])})
import fs from "node:fs"
const source=(p:string)=>fs.readFileSync(p,"utf8")
test("chat uses database subscriber, conversation, recent tail, and checkpoint CAS authority",()=>{const r=source("app/api/sirens-mind/chat/route.ts");assert.match(r,/loadCreatorReplyAuthority/);assert.match(r,/saveCreatorReplyCheckpoint/);assert.match(r,/checkpoint\.recent_turns/);assert.match(r,/memory_status/);assert.doesNotMatch(r,/parseCreatorReplyContinuity\(body\.creator_reply_continuity\)/)})
test("client sends selection IDs and never stores Creator Reply thread or continuity",()=>{const ui=source("components/chat/ChatUI.tsx");assert.match(ui,/subscriber_id: subscriberId, conversation_id: conversationId/);assert.match(ui,/history: creatorReply \? \[\]/);assert.doesNotMatch(ui,/sirens_mind_creator_reply_thread|creator_reply_continuity/)})
test("refresh and reselection hydrate the bounded durable conversation before Direction is enabled",()=>{const ui=source("components/chat/ChatUI.tsx"),route=source("app/api/sirens-mind/creator-reply/conversations/[conversationId]/route.ts"),service=source("lib/sirens-mind/creator-reply-service.ts");assert.match(ui,/fetch\(`\/api\/sirens-mind\/creator-reply\/conversations\/\$\{conversationId\}`/);assert.match(ui,/payload\?\.conversation\?\.subscriber_id !== subscriberId/);assert.match(ui,/recent_turns\.map/);assert.match(ui,/completed: true/);assert.match(ui,/!creatorReplyHydrating && messages\.some/);assert.match(route,/export async function GET/);assert.match(route,/loadCreatorReplyConversation/);assert.match(service,/eq\("workspace_id",w\)\.eq\("id",conversationId\)/);assert.match(service,/conversationCheckpointAad\(w,conversationId\)/);assert.match(service,/recent_turns:parsed\.recent_turns/)})
test("workspace exposes subscriber and conversation controls with custom platform",()=>{const ui=source("components/chat/CreatorReplyWorkspace.tsx");for(const phrase of ["Search subscribers","Filter platform","Custom platform","New Conversation","Reset Context","Resume"])assert.match(ui,new RegExp(phrase));assert.match(ui,/sessionStorage/);assert.doesNotMatch(ui,/localStorage/)})
test("migration enforces private multi-tenancy, one active conversation, and CAS",()=>{const schema=source("supabase/migrations/20260902120000_creator_reply_durable_workspace.sql")+source("supabase/migrations/20260902130000_creator_reply_atomic_operations.sql")+source("supabase/migrations/20260902140000_creator_reply_transactional_lifecycle.sql");for(const phrase of ["workspace_members","enable row level security","one_active","pg_advisory_xact_lock","checkpoint_revision=p_expected_revision","revoke all on function"])assert.match(schema,new RegExp(phrase))})
test("grounding permits explicit notes, natural paraphrase, and never promotes creator output to subscriber fact",()=>{const p=source("prompts/nsfw_gpt/nsfw_gpt.creator_reply.system.txt");assert.match(p,/Subscriber Profile \/ Key Notes/);assert.match(p,/Prior creator outbound replies.*never factual evidence/);assert.match(p,/authority_id/);assert.match(p,/stable `id`/);assert.match(p,/Do not copy, quote, paraphrase, or manufacture evidence text/);assert.doesNotMatch(p,/closed set of safe creator-owned primitives/)})
test("no transcript or message ledger migration exists",()=>{const migration=source("supabase/migrations/20260902120000_creator_reply_durable_workspace.sql");assert.doesNotMatch(migration,/creator_reply_messages|conversation_transcripts|chat_history/)})
test("recent tail rejects malformed role order and drops oldest complete pair",()=>{assert.deepEqual(trimCreatorReplyTurns([{role:"creator",text:"bad"},{role:"subscriber",text:"order"}]),[]);const huge=Array.from({length:6},(_,i)=>({role:(i%2?"creator":"subscriber") as "creator"|"subscriber",text:String(i).repeat(6000)}));const kept=trimCreatorReplyTurns(huge);assert.deepEqual(kept.map(x=>x.text[0]),["2","3","4","5"]);assert.equal(kept[0].role,"subscriber");assert.equal(kept.at(-1)?.role,"creator")})
test("service uses transactional lifecycle RPCs and active-only authority",()=>{const service=source("lib/sirens-mind/creator-reply-service.ts"),sql=source("supabase/migrations/20260902140000_creator_reply_transactional_lifecycle.sql");for(const rpc of ["creator_reply_create_subscriber","creator_reply_new_conversation","creator_reply_resume_conversation"])assert.match(service,new RegExp(`rpc\\("${rpc}"`));assert.match(service,/eq\("status","active"\)/);assert.match(sql,/status='active' and checkpoint_revision=p_expected_revision/)})
test("management UI provides editing, archives, labels, and dirty discard protection",()=>{const ui=source("components/chat/CreatorReplyWorkspace.tsx");for(const text of ["Edit Subscriber","Key Notes","Archived","Unarchive","Rename","Discard the subscriber information"])assert.match(ui,new RegExp(text))})
test("final blockers keep least-privilege grants, validate before resume, and preserve chat on notices",()=>{const grant=source("supabase/migrations/20260902150000_creator_reply_service_role_table_grants.sql"),service=source("lib/sirens-mind/creator-reply-service.ts"),ui=source("components/chat/CreatorReplyWorkspace.tsx");assert.match(grant,/grant select, update, delete.*subscribers to service_role/);assert.match(grant,/grant select, update.*conversations to service_role/);const resume=service.slice(service.indexOf("export async function resumeConversation"),service.indexOf("export async function resetConversation"));assert.ok(resume.indexOf("parseCreatorReplyCheckpoint")<resume.indexOf('rpc("creator_reply_resume_conversation"'));const rename=service.slice(service.indexOf("export async function renameConversation"),service.indexOf("export async function loadCreatorReplyAuthority"));assert.match(rename,/in\("status",\["active","paused"\]\)/);assert.match(rename,/checkpoint_revision/);assert.match(ui,/chatEpoch/);assert.match(ui,/key=\{`\$\{active.id\}:\$\{conversation.id\}:\$\{chatEpoch\}`\}/);assert.doesNotMatch(ui,/key=\{`[^`]*notice/);assert.match(ui,/Current conversation/)})
test("Creator Reply owns a polished single-shell presentation",()=>{const workspace=source("components/chat/CreatorReplyWorkspace.tsx"),chat=source("components/chat/ChatUI.tsx");assert.match(workspace,/min-h-dvh/);assert.match(workspace,/Ready for a subscriber/);assert.match(workspace,/Private Library/);assert.match(workspace,/Subscriber Memory/);assert.match(workspace,/role="alertdialog"/);assert.match(workspace,/<ChatUI[\s\S]*embedded/);assert.doesNotMatch(workspace,/\bprompt\s*\(/);assert.doesNotMatch(workspace,/\bconfirm\s*\(/);assert.match(chat,/embedded\?: boolean/);assert.match(chat,/!embedded \? \(/);assert.match(chat,/embedded\n\s*\? "flex h-full min-h-0/);assert.match(chat,/relative h-dvh w-full overflow-hidden bg-black text-white/)})
