import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import { isInvalidInteractionCombination } from "../../../app/api/nsfw-gpt/headless/route"
const [route, chat, input, generator, page, bundle] = await Promise.all([
  readFile("app/api/nsfw-gpt/headless/route.ts", "utf8"), readFile("components/chat/ChatUI.tsx", "utf8"),
  readFile("components/chat/ChatInput.tsx", "utf8"), readFile("app/generate/page.tsx", "utf8"),
  readFile("app/sirens-mind/page.tsx", "utf8"), readFile("prompts/nsfw_gpt/bundle.conversational.system.txt", "utf8"),
])
assert.match(chat, /interaction_mode: "conversation"/)
assert.match(generator, /interaction_mode: "headless"/)
assert.match(route, /interactionMode === "conversation" \? CONVERSATION_GOVERNOR : HEADLESS_CONTRACT/)
assert.match(route, /kind === "clarification"/)
assert.match(route, /kind !== "prompt" \|\| !message \|\| !prompt \|\| !target/)
assert.match(chat, /data\.kind === "clarification"/)
assert.match(chat, /canUseInGenerator: true/)
const storageWrite = chat.indexOf("window.sessionStorage.setItem(")
const storageFailure = chat.indexOf("I couldn't securely transfer this prompt to Generator")
const storageFailureReturn = chat.indexOf("return", storageFailure)
const generatorNavigation = chat.indexOf('window.location.assign("/generate")')
assert.ok(storageWrite >= 0 && storageFailure > storageWrite)
assert.ok(storageFailureReturn > storageFailure && generatorNavigation > storageFailureReturn)
assert.match(input, /onSend: \(userText: string, selectedMode: Mode\)/)
assert.match(input, /await onSend\(trimmed, localMode\)/)
assert.doesNotMatch(input, /setTimeout/)
assert.match(chat, /mode: selectedMode/)
for (const mode of ["SAFE", "NSFW", "ULTRA"]) assert.ok(input.includes(`modeButton("${mode}")`))
assert.ok(generator.includes("GENERATOR_MIND_CONTEXT_STORAGE_KEY"))
assert.ok(page.includes("GENERATOR_MIND_CONTEXT_KEY"))
for (const field of ["generation_target", "prompt", "negative_prompt", "identity", "created_at", "version"]) assert.ok(generator.includes(field))
for (const forbidden of ["artifact_r2_bucket", "artifact_r2_key", "provider", "checkpoint", "service_credentials"]) assert.ok(!page.includes(forbidden))
assert.match(generator, /mode === "image_to_video" && imageFile && !sourceGenerationAssetId/)
assert.match(generator, /local source image must remain on Generator/)
assert.match(generator, /mode === "image_to_video" && isUuidLike\(sourceGenerationAssetId\)[\s\S]*source_generation_asset_id: sourceGenerationAssetId!\.toLowerCase\(\)/)
assert.match(page, /parsed\.generation_target === "image_to_video"[\s\S]*canonicalUuid\(parsed\.source_generation_asset_id\)/)
assert.match(page, /initialSourceGenerationAssetId=\{context\?\.source_generation_asset_id\}/)
assert.match(chat, /msg\.meta\.generationTarget === "image_to_video" && initialSourceGenerationAssetId[\s\S]*source_generation_asset_id: initialSourceGenerationAssetId/)
assert.match(generator, /incomingMode === "image_to_video"[\s\S]*isUuidLike\(payload\.source_generation_asset_id\.trim\(\)\)[\s\S]*setSourceGenerationAssetId\(incomingSourceGenerationAssetId\)[\s\S]*setImageFile\(null\)[\s\S]*setPendingVideoSourceUpload\(null\)/)
assert.match(page, /canonicalUuid[\s\S]*\? trimmed\.toLowerCase\(\)[\s\S]*: undefined/)
assert.doesNotMatch(chat, /source_generation_asset_id[\s\S]*URLSearchParams/)
for (const forbidden of ["imagePreviewUrl", "signed_url", "storage_bucket", "object_key", "sha256", "File bytes"]) {
  assert.ok(!page.includes(forbidden), `Mind context must not contain ${forbidden}`)
}
assert.doesNotMatch(generator, /IMAGE, VIDEO, or STORY output/)
assert.match(bundle, /fluid, adaptive clarification/)
assert.doesNotMatch(bundle, /Blocks generation until confirmation|Guide users through the funnel in order/)
assert.equal(isInvalidInteractionCombination("conversation", "refine_prompt", undefined), true)
assert.equal(isInvalidInteractionCombination("conversation", "refine_prompt_variants", undefined), true)
assert.equal(isInvalidInteractionCombination("conversation", null, "cinematic"), true)
assert.equal(isInvalidInteractionCombination("conversation", null, undefined), false)
assert.equal(isInvalidInteractionCombination("headless", "refine_prompt", "cinematic"), false)
assert.equal(isInvalidInteractionCombination("headless", "refine_prompt_variants", "photoreal"), false)
const mixedModeRejection = route.indexOf("isInvalidInteractionCombination(interactionMode, task, body.refine_type)")
const providerCall = route.indexOf("fetch(`${baseUrl}/chat/completions`")
assert.ok(mixedModeRejection >= 0 && mixedModeRejection < providerCall)
for (const invalidTask of ["refine_prompt", "refine_prompt_variants"]) {
  assert.ok(route.includes(`task !== \"${invalidTask}\"`), `${invalidTask} remains bounded`)
}
assert.match(generator, /interaction_mode: "headless"[\s\S]*task: "refine_prompt_variants"/)
assert.match(route, /interactionMode === "conversation" \? \[conversationTransport\] : \[\]/)
assert.match(route, /ensureThreeRefineVariants/)
console.log("Phase 6 Siren's Mind contracts: PASS")
