import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

const databaseUrl = process.env.CALLABLE_FUNCTION_HARDENING_DATABASE_URL;
if (!databaseUrl) throw new Error("CALLABLE_FUNCTION_HARDENING_DATABASE_URL is required; no database was contacted");
const url = new URL(databaseUrl);
if (!['postgres:', 'postgresql:'].includes(url.protocol) || !['localhost','127.0.0.1','[::1]'].includes(url.hostname)
  || url.port !== '5432' || url.pathname !== '/callable_function_hardening_test' || url.search || url.hash)
  throw new Error("callable-function hardening safety boundary rejected non-local or unexpected database URL");
const migration = readFileSync("supabase/migrations/20260821005423_harden_callable_function_boundaries.sql", "utf8");
const rollback = readFileSync("supabase/manual/harden_callable_function_boundaries_rollback.sql", "utf8");
function psql(sql, ok=true) { const r=spawnSync('psql',[databaseUrl,'-X','-v','ON_ERROR_STOP=1','-qAt'],{input:sql,encoding:'utf8'}); if((r.status===0)!==ok) throw new Error(`psql expectation failed\nstdout=${r.stdout}\nstderr=${r.stderr}`); return r.stdout.trim(); }
const targets=[['auto_approve_caption_templates',''],['auto_approve_cta_variants',''],['auto_approve_hashtag_sets',''],['claim_next_lora_job',''],['creator_publishing_audit_events_prevent_mutation',''],['creator_publishing_escalated_approved_has_review',''],['creator_publishing_prevent_creator_controlled_field_update',''],['creator_publishing_queue_jsonb_has_forbidden_credential_key','jsonb'],['dataset_doctor_images_enforce_parent_match',''],['dataset_doctor_images_refresh_counts',''],['dataset_doctor_mark_approved','uuid, text, text'],['dataset_doctor_mark_exported','uuid'],['dataset_doctor_queue_lora_training','uuid, text, text, integer'],['dataset_doctor_selections_enforce_parent_match',''],['dataset_doctor_set_active_job','uuid, uuid'],['increment_generation_count',''],['refresh_dataset_doctor_job_counts','uuid'],['set_updated_at',''],['update_collection_item_count',''],['update_collections_updated_at',''],['update_updated_at_column','']];
const genericTables=['creator_publishing_audit_events','creator_publishing_content_packages','affiliate_ledger','autopost_accounts','autopost_jobs','autopost_rules','content_post_media','content_post_targets','content_posts','creator_platform_accounts','creator_publishing_ai_twin_consents','creator_publishing_creator_verifications','creator_publishing_operator_authorizations','creator_publishing_plans','creator_publishing_platform_capabilities','creator_publishing_platform_jobs','creator_publishing_queue_tasks','creator_publishing_scheduler_events','ai_influencers','commissions','content_posts_legacy_ai_influencer','crypto_payments','crypto_wallet_addresses','payouts','subscription_tiers','system_stats','user_subscriptions'];
const genericSql=genericTables.map(t=>`create table public.${t}(id uuid primary key default gen_random_uuid(), updated_at timestamptz, compliance_status text);`).join('\n');
const grants=targets.map(([n,a])=>`revoke all on function public.${n}(${a}) from public,postgres,anon,authenticated,service_role; grant execute on function public.${n}(${a}) to public,postgres,anon,authenticated,service_role;`).join('\n');
const fixture=`
drop schema if exists public cascade; create schema public;
do $$begin if not exists(select from pg_roles where rolname='anon')then create role anon nologin;end if;if not exists(select from pg_roles where rolname='authenticated')then create role authenticated nologin;end if;if not exists(select from pg_roles where rolname='service_role')then create role service_role nologin;end if;end$$;
grant usage on schema public to anon,authenticated,service_role;
create table public.autopost_settings(id int primary key,auto_approve boolean); insert into public.autopost_settings values(1,true);
create table public.caption_templates(id serial primary key,approved boolean default false); create table public.cta_variants(like public.caption_templates including all); create table public.hashtag_sets(like public.caption_templates including all);
create table public.profiles(id uuid primary key,generation_count int default 0,updated_at timestamptz); create table public.generations(id serial primary key,user_id uuid,updated_at timestamptz);
create table public.collections(id uuid primary key,item_count int default 0,updated_at timestamptz); create table public.collection_items(id serial primary key,collection_id uuid);
create table public.user_loras(id uuid primary key,status text,created_at timestamptz,started_at timestamptz,error_message text,dataset_r2_bucket text,dataset_r2_prefix text,image_count int,progress int,completed_at timestamptz,updated_at timestamptz,dataset_doctor_job_id uuid);
create table public.dataset_doctor_jobs(id uuid primary key,status text,final_r2_bucket text,final_r2_prefix text,approved_at timestamptz,exported_at timestamptz,updated_at timestamptz,raw_count int default 0,accepted_count int default 0,rejected_count int default 0,review_count int default 0);
create table public.dataset_doctor_images(id uuid primary key,job_id uuid,decision text,updated_at timestamptz); create table public.dataset_doctor_selections(id uuid primary key,job_id uuid,image_id uuid);
create table public.creator_publishing_compliance_reviews(id uuid primary key,content_package_id uuid);
${genericSql}
create function public.auto_approve_caption_templates()returns trigger language plpgsql as $$declare s autopost_settings%rowtype;begin select * into s from autopost_settings limit 1;new.approved=s.auto_approve;return new;end$$;
create function public.auto_approve_cta_variants()returns trigger language plpgsql as $$declare s autopost_settings%rowtype;begin select * into s from autopost_settings limit 1;new.approved=s.auto_approve;return new;end$$;
create function public.auto_approve_hashtag_sets()returns trigger language plpgsql as $$declare s autopost_settings%rowtype;begin select * into s from autopost_settings limit 1;new.approved=s.auto_approve;return new;end$$;
create function public.claim_next_lora_job()returns setof public.user_loras language plpgsql as $$declare job public.user_loras;begin select * into job from public.user_loras where status='queued' order by created_at limit 1 for update skip locked;if not found then return;end if;update public.user_loras set status='training',started_at=now(),error_message=null where id=job.id;return query select * from public.user_loras where id=job.id;end$$;
create function public.creator_publishing_audit_events_prevent_mutation()returns trigger language plpgsql as $$begin raise exception 'immutable';end$$;
create function public.creator_publishing_escalated_approved_has_review()returns trigger language plpgsql as $$begin perform 1 from public.creator_publishing_compliance_reviews limit 1;return new;end$$;
create function public.creator_publishing_prevent_creator_controlled_field_update()returns trigger language plpgsql as $$begin return new;end$$;
create function public.creator_publishing_queue_jsonb_has_forbidden_credential_key(value jsonb)returns boolean language plpgsql immutable as $$declare v jsonb; k text;begin if jsonb_typeof(value)='object'then for k,v in select * from jsonb_each(value)loop if lower(k) in('password','access_token','platform_secret')or public.creator_publishing_queue_jsonb_has_forbidden_credential_key(v)then return true;end if;end loop;elsif jsonb_typeof(value)='array'then for v in select * from jsonb_array_elements(value)loop if public.creator_publishing_queue_jsonb_has_forbidden_credential_key(v)then return true;end if;end loop;end if;return false;end$$;
alter table public.creator_publishing_content_packages add constraint no_credentials check(not public.creator_publishing_queue_jsonb_has_forbidden_credential_key(to_jsonb(compliance_status)));
create function public.dataset_doctor_images_enforce_parent_match()returns trigger language plpgsql as $$begin if not exists(select 1 from public.dataset_doctor_jobs where id=new.job_id)then raise exception 'parent mismatch';end if;return new;end$$;
create function public.refresh_dataset_doctor_job_counts(p_job_id uuid)returns void language plpgsql as $$begin update public.dataset_doctor_jobs j set raw_count=(select count(*)from public.dataset_doctor_images i where i.job_id=p_job_id),accepted_count=(select count(*)from public.dataset_doctor_images i where i.job_id=p_job_id and decision='accepted'),rejected_count=(select count(*)from public.dataset_doctor_images i where i.job_id=p_job_id and decision='rejected'),review_count=(select count(*)from public.dataset_doctor_images i where i.job_id=p_job_id and decision='review'),updated_at=now()where j.id=p_job_id;end$$;
create function public.dataset_doctor_images_refresh_counts()returns trigger language plpgsql as $$begin perform public.refresh_dataset_doctor_job_counts(coalesce(new.job_id,old.job_id));return coalesce(new,old);end$$;
create function public.dataset_doctor_selections_enforce_parent_match()returns trigger language plpgsql as $$begin if not exists(select 1 from public.dataset_doctor_images where id=new.image_id and job_id=new.job_id)then raise exception 'selection parent mismatch';end if;return new;end$$;
create function public.dataset_doctor_mark_approved(p_job_id uuid,p_final_r2_bucket text,p_final_r2_prefix text)returns void language plpgsql as $$begin update public.dataset_doctor_jobs set status='approved',final_r2_bucket=p_final_r2_bucket,final_r2_prefix=p_final_r2_prefix,approved_at=now(),updated_at=now()where id=p_job_id;end$$;
create function public.dataset_doctor_mark_exported(p_job_id uuid)returns void language plpgsql as $$begin update public.dataset_doctor_jobs set status='exported',exported_at=now(),updated_at=now()where id=p_job_id;end$$;
create function public.dataset_doctor_queue_lora_training(p_lora_id uuid,p_dataset_bucket text,p_dataset_prefix text,p_image_count integer)returns void language plpgsql as $$begin update public.user_loras set dataset_r2_bucket=p_dataset_bucket,dataset_r2_prefix=p_dataset_prefix,image_count=p_image_count,status='queued',progress=0,error_message=null,started_at=null,completed_at=null,updated_at=now()where id=p_lora_id;end$$;
create function public.dataset_doctor_set_active_job(p_lora_id uuid,p_job_id uuid)returns void language plpgsql as $$begin update public.user_loras set dataset_doctor_job_id=p_job_id where id=p_lora_id;end$$;
create function public.increment_generation_count()returns trigger language plpgsql as $$begin update profiles set generation_count=generation_count+1 where id=new.user_id;return new;end$$;
create function public.set_updated_at()returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create function public.update_collection_item_count()returns trigger language plpgsql as $$begin update collections set item_count=(select count(*)from public.collection_items where collection_id=coalesce(new.collection_id,old.collection_id))where id=coalesce(new.collection_id,old.collection_id);return coalesce(new,old);end$$;
create function public.update_collections_updated_at()returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create function public.update_updated_at_column()returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create trigger trg_auto_approve_caption_templates before insert on public.caption_templates for each row execute function public.auto_approve_caption_templates();create trigger trg_auto_approve_cta_variants before insert on public.cta_variants for each row execute function public.auto_approve_cta_variants();create trigger trg_auto_approve_hashtag_sets before insert on public.hashtag_sets for each row execute function public.auto_approve_hashtag_sets();
create trigger trg_creator_publishing_audit_events_no_delete before delete on public.creator_publishing_audit_events for each row execute function public.creator_publishing_audit_events_prevent_mutation();create trigger trg_creator_publishing_audit_events_no_update before update on public.creator_publishing_audit_events for each row execute function public.creator_publishing_audit_events_prevent_mutation();
create trigger trg_creator_publishing_escalated_approved_has_review before insert or update of compliance_status on public.creator_publishing_content_packages for each row execute function public.creator_publishing_escalated_approved_has_review();create trigger trg_creator_publishing_prevent_creator_controlled_field_update before insert or update on public.creator_publishing_content_packages for each row execute function public.creator_publishing_prevent_creator_controlled_field_update();
create trigger trg_dataset_doctor_images_parent_match before insert or update on public.dataset_doctor_images for each row execute function public.dataset_doctor_images_enforce_parent_match();create trigger trg_dataset_doctor_images_refresh_counts after insert or delete or update on public.dataset_doctor_images for each row execute function public.dataset_doctor_images_refresh_counts();create trigger trg_dataset_doctor_selections_parent_match before insert or update on public.dataset_doctor_selections for each row execute function public.dataset_doctor_selections_enforce_parent_match();
create trigger increment_user_generations after insert on public.generations for each row execute function public.increment_generation_count();create trigger update_collection_items_count after insert or delete on public.collection_items for each row execute function public.update_collection_item_count();create trigger trigger_update_collections_timestamp before update on public.collections for each row execute function public.update_collections_updated_at();
${['affiliate_ledger','autopost_accounts','autopost_jobs','autopost_rules','content_post_media','content_post_targets','content_posts','creator_platform_accounts','creator_publishing_ai_twin_consents','creator_publishing_content_packages','creator_publishing_creator_verifications','creator_publishing_operator_authorizations','creator_publishing_plans','creator_publishing_platform_capabilities','creator_publishing_platform_jobs','creator_publishing_queue_tasks','creator_publishing_scheduler_events','dataset_doctor_images','dataset_doctor_jobs'].map((t,i)=>`create trigger set_updated_at_${i} before update on public.${t} for each row execute function public.set_updated_at();`).join('\n')}
${['ai_influencers','collections','commissions','content_posts_legacy_ai_influencer','crypto_payments','crypto_wallet_addresses','generations','payouts','profiles','subscription_tiers','system_stats','user_subscriptions'].map((t,i)=>`create trigger legacy_updated_at_${i} before update on public.${t} for each row execute function public.update_updated_at_column();`).join('\n')}
create function public.get_my_affiliate_ledger_summary()returns int language sql security definer set search_path=pg_catalog,pg_temp as $$select 1$$;revoke all on function public.get_my_affiliate_ledger_summary()from public,anon,service_role;grant execute on function public.get_my_affiliate_ledger_summary()to authenticated;
grant all on all tables in schema public to service_role;
${grants}`;
psql(fixture);
const list=targets.map(([n,a])=>`public.${n}(${a})`).join(',');
if(psql(`select count(*) from pg_proc where oid in (${targets.map(([n,a])=>`'public.${n}(${a})'::regprocedure`).join(',')}) and proconfig is null`) !== '21')throw new Error('pre-state proconfig mismatch');
psql(migration);
for(const [n,a] of targets){const sig=`public.${n}(${a})`;if(psql(`select exists(select 1 from pg_catalog.aclexplode((select proacl from pg_proc where oid='${sig}'::regprocedure))a where a.grantee=0 and a.privilege_type='EXECUTE')||','||has_function_privilege('anon','${sig}','EXECUTE')||','||has_function_privilege('authenticated','${sig}','EXECUTE')||','||has_function_privilege('service_role','${sig}','EXECUTE')||','||has_function_privilege('postgres','${sig}','EXECUTE')`)!=='false,false,false,true,true')throw new Error(`ACL mismatch ${sig}`);}
psql(`insert into public.caption_templates(approved)values(false);insert into public.cta_variants(approved)values(false);insert into public.hashtag_sets(approved)values(false);`);if(psql(`select bool_and(approved)from(select approved from public.caption_templates union all select approved from public.cta_variants union all select approved from public.hashtag_sets)s`)!=='t')throw new Error('auto approval failed');
const u='10000000-0000-0000-0000-000000000001',j='20000000-0000-0000-0000-000000000001',i='30000000-0000-0000-0000-000000000001';psql(`insert into public.profiles(id)values('${u}');insert into public.generations(user_id)values('${u}');insert into public.collections(id)values('${j}');insert into public.collection_items(collection_id)values('${j}');insert into public.dataset_doctor_jobs(id)values('${j}');insert into public.dataset_doctor_images(id,job_id,decision)values('${i}','${j}','accepted');insert into public.dataset_doctor_selections(id,job_id,image_id)values(gen_random_uuid(),'${j}','${i}');`);if(psql(`select generation_count from public.profiles where id='${u}';select item_count from public.collections where id='${j}';select raw_count||','||accepted_count from public.dataset_doctor_jobs where id='${j}'`) !== '1\n1\n1,1')throw new Error('trigger behavior failed');
psql(`set role service_role;select public.dataset_doctor_mark_approved('${j}','bucket','prefix');reset role;insert into public.user_loras(id,status)values('${u}','new');set role service_role;select public.dataset_doctor_queue_lora_training('${u}','bucket','prefix',5);reset role;`);
if(psql(`select public.creator_publishing_queue_jsonb_has_forbidden_credential_key('{"safe":{"access_token":"x"}}');select has_function_privilege('authenticated','public.get_my_affiliate_ledger_summary()','EXECUTE')`) !== 't\nt')throw new Error('helper or legitimate RPC changed');
psql(rollback);if(psql(`select count(*) from pg_proc where oid in (${targets.map(([n,a])=>`'public.${n}(${a})'::regprocedure`).join(',')}) and proconfig is null`) !== '21')throw new Error('rollback proconfig mismatch');
console.log('Callable-function disposable PostgreSQL integration passed: 21 ACL/search paths, trigger/helper/service behavior, legitimate RPC, and rollback');
