import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import assert from "node:assert/strict";

const databaseUrl=process.env.LOCK05C_DATABASE_URL;
if(!databaseUrl) throw new Error("LOCK05C_DATABASE_URL is required; no database was contacted");
const url=new URL(databaseUrl);
if(!['postgres:','postgresql:'].includes(url.protocol)||!['localhost','127.0.0.1','[::1]'].includes(url.hostname)||url.port!=='5432'||url.pathname!=='/lock05c_test'||url.search||url.hash) throw new Error("LOCK05C safety boundary rejected non-local or unexpected database URL");
const file=path=>readFileSync(path,"utf8");
function sql(statement,expectedSuccess=true){const result=spawnSync("psql",[databaseUrl,"-X","-v","ON_ERROR_STOP=1","-qAt"],{input:statement,encoding:"utf8"});if((result.status===0)!==expectedSuccess)throw new Error(`psql expectation failed\nstdout=${result.stdout}\nstderr=${result.stderr}`);return result.stdout.trim()}
const profileColumns=`id uuid primary key,email text,seat_number integer,is_og_vip boolean,tokens bigint default 500,badge text,created_at timestamptz default now(),user_id uuid unique,tier text default 'token_only',referral_code text,referred_by uuid,stripe_customer_id text,stripe_subscription_id text,subscription_status text,is_beta_tester boolean,og_seat_number integer,updated_at timestamptz default now(),username text,full_name text,avatar_url text,role text,clerk_id text,last_login_at timestamptz,metadata jsonb,stripe_connect_account_id text,must_change_password boolean,password_hash text,is_tester boolean,stripe_connect_onboarded boolean,referral_email_sent_at timestamptz,total_generations integer,constraint check_tier_valid check(tier in ('og_throne','monthly_29','monthly_59','monthly_79','token_only'))`;
const fixture=`
drop schema if exists lock05c_backup_20260811_pre_apply cascade; drop schema if exists auth cascade; drop schema public cascade;
create schema public authorization postgres; create schema auth authorization postgres;
do $$begin if not exists(select from pg_roles where rolname='anon')then create role anon nologin;end if;if not exists(select from pg_roles where rolname='authenticated')then create role authenticated nologin;end if;if not exists(select from pg_roles where rolname='service_role')then create role service_role nologin bypassrls;end if;alter role service_role bypassrls;end$$;
grant usage on schema public,auth to anon,authenticated,service_role;
create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');
create table public.profiles(${profileColumns}); alter table profiles enable row level security;
create policy profiles_authenticated_own_select on profiles as permissive for select to authenticated using(user_id=auth.uid());
grant select on profiles to service_role;
grant select(id,email,seat_number,is_og_vip,tokens,badge,created_at,user_id,tier,referral_code,referred_by,stripe_customer_id,stripe_subscription_id,subscription_status,is_beta_tester,og_seat_number,updated_at,username,full_name,avatar_url,role,clerk_id,last_login_at,metadata,stripe_connect_account_id,must_change_password,is_tester,stripe_connect_onboarded,referral_email_sent_at,total_generations)on profiles to authenticated;
grant update(stripe_customer_id,stripe_connect_account_id,stripe_connect_onboarded)on profiles to service_role;
create function public.generate_referral_code()returns text language sql as $$select 'REF'||substr(md5(random()::text),1,8)$$;
create function public.handle_new_user()returns trigger language plpgsql security definer set search_path to pg_catalog,public,pg_temp as $$begin insert into public.profiles(id,user_id,email,referral_code,tier,badge,tokens,subscription_status,role,is_og_vip,is_beta_tester,must_change_password,created_at,updated_at) values(new.id,new.id,new.email,public.generate_referral_code(),'token_only','Plebian',0,'none','user',false,false,false,now(),now());return new;end$$;
create function public.initialize_new_user()returns trigger language plpgsql set search_path to pg_catalog,pg_temp as $$begin new.tokens:=0;if new.tier is null then new.tier:='free';end if;return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create trigger on_profile_created before insert on profiles for each row execute function public.initialize_new_user();
create table public.user_subscriptions(id uuid primary key,user_id uuid,status text,tier_name text,current_period_end timestamptz);
create table public.token_packs(id uuid primary key default gen_random_uuid(),name text not null,display_name text not null,tokens integer not null,price_usd numeric(10,2) not null,stripe_price_id text not null,bonus_tokens integer default 0,total_tokens integer generated always as (tokens + bonus_tokens) stored,is_active boolean default true,sort_order integer default 0,popular boolean default false,created_at timestamptz default now(),updated_at timestamptz default now()); alter table token_packs enable row level security;
create policy token_packs_public_read on token_packs as permissive for select to public using(true); grant select on token_packs to authenticated;
create table public.token_transactions(id uuid primary key,user_id uuid,amount integer,reason text); alter table token_transactions enable row level security;
create policy token_transactions_own on token_transactions as restrictive for select to authenticated using(user_id=auth.uid()); grant select on token_transactions to authenticated;
create table public.generations(id uuid primary key,tokens_cost integer); create table public.purchases(id uuid primary key,tokens_received integer,purchase_type text default 'tokens');
create table public.referrals(id uuid primary key,reward_tokens integer); create table public.system_stats(id uuid primary key,tokens_purchased bigint,tokens_spent bigint);
create table public.crypto_payments(id uuid primary key,token_pack_id uuid,constraint crypto_payments_token_pack_id_fkey foreign key(token_pack_id)references token_packs(id));
create function public.add_tokens(uuid,integer,text)returns void language plpgsql security definer as $$begin end$$;
create function public.deduct_tokens(uuid,integer)returns boolean language plpgsql security definer as $$begin return true;end$$;
create function public.deduct_tokens(uuid,integer,text)returns boolean language plpgsql security definer as $$begin return true;end$$;
create function public.complete_referral_reward(uuid)returns boolean language plpgsql security definer as $$begin return true;end$$;
create function public.get_user_stats(uuid)returns table(total_generations bigint,total_collections bigint,total_tokens_spent integer,total_referrals bigint,current_streak integer)language plpgsql security definer as $$begin return;end$$;
revoke execute on function add_tokens(uuid,integer,text),deduct_tokens(uuid,integer),deduct_tokens(uuid,integer,text)from public,anon,authenticated;
insert into token_packs(id,name,display_name,tokens,price_usd,stripe_price_id,bonus_tokens,is_active,sort_order,popular,created_at,updated_at) values
('10000000-0000-0000-0000-000000000001','pack_50','50 Token Pack',50,2.99,'price_1SScdNFjcWRhhOnz4fdtkych',0,true,0,false,'2026-08-11T00:00:00Z','2026-08-11T00:00:00Z'),
('10000000-0000-0000-0000-000000000002','pack_200','200 Token Pack',200,9.99,'price_1SSce8FjcWRhhOnz9lAXHETb',0,true,1,true,'2026-08-11T00:00:01Z','2026-08-11T00:00:01Z'),
('10000000-0000-0000-0000-000000000003','pack_500','500 Token Pack',500,19.99,'price_1SSceqFjcWRhhOnzfkiKHhGX',0,true,2,false,'2026-08-11T00:00:02Z','2026-08-11T00:00:02Z');
insert into profiles(id,email,user_id,tier,tokens,password_hash,role,is_og_vip,is_beta_tester,is_tester,must_change_password)select ('20000000-0000-0000-0000-'||lpad(g::text,12,'0'))::uuid,'u'||g||'@test',('30000000-0000-0000-0000-'||lpad(g::text,12,'0'))::uuid,case when g=22 then 'token_only' else 'og_throne'end,0,'secret-'||g,'user',false,false,false,false from generate_series(1,22)g;
insert into user_subscriptions values('40000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000022','active','og_throne',now()+interval '1 month');
insert into generations select ('50000000-0000-0000-0000-'||lpad(g::text,12,'0'))::uuid,1 from generate_series(1,10)g;`;
const policySemantics=()=>sql(`select c.relname||'|'||p.polname||'|'||p.polpermissive::text||'|'||p.polcmd::text||'|'||array_to_string(array(select case when role_oid=0 then 'PUBLIC' else r.rolname end from unnest(p.polroles) role_oid left join pg_roles r on r.oid=role_oid order by case when role_oid=0 then 'PUBLIC' else r.rolname end),',')||'|'||coalesce(pg_get_expr(p.polqual,p.polrelid),'NULL')||'|'||coalesce(pg_get_expr(p.polwithcheck,p.polrelid),'NULL') from pg_policy p join pg_class c on c.oid=p.polrelid where p.polrelid in ('profiles'::regclass,'token_packs'::regclass,'token_transactions'::regclass) order by c.relname,p.polname`);
const explicitProfileAcls=()=>sql(`select a.attname||'|'||case when x.grantee=0 then 'PUBLIC' else grantee.rolname end||'|'||grantor.rolname||'|'||x.privilege_type||'|'||x.is_grantable from pg_attribute a cross join lateral aclexplode(a.attacl)x left join pg_roles grantee on grantee.oid=x.grantee join pg_roles grantor on grantor.oid=x.grantor where a.attrelid='profiles'::regclass and a.attnum>0 and not a.attisdropped order by a.attname,case when x.grantee=0 then 'PUBLIC' else grantee.rolname end,grantor.rolname,x.privilege_type,x.is_grantable`);
const explicitAclCounts=()=>sql(`select count(*)||'|'||count(*)filter(where grantee.rolname='authenticated'and x.privilege_type='SELECT')||'|'||count(*)filter(where grantee.rolname='service_role'and x.privilege_type='UPDATE')||'|'||count(*)filter(where grantee.rolname='service_role'and x.privilege_type='SELECT') from pg_attribute a cross join lateral aclexplode(a.attacl)x left join pg_roles grantee on grantee.oid=x.grantee where a.attrelid='profiles'::regclass and a.attnum>0 and not a.attisdropped`);
const profileState=()=>sql("select md5(string_agg(id||'|'||user_id||'|'||tier||'|'||tokens,';' order by id))from profiles");
const hashes=()=>sql("select md5(string_agg(password_hash,',' order by id))from profiles");
const packs=(relation="public.token_packs")=>sql(`select md5(string_agg(row_to_json(t)::text,';' order by id))from ${relation} t`);
const generatedColumn=(relation="public.token_packs")=>sql(`select count(*)||'|'||string_agg(a.attname||'|'||format_type(a.atttypid,a.atttypmod)||'|'||a.attgenerated::text||'|'||pg_get_expr(d.adbin,d.adrelid),';' order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid='${relation}'::regclass and a.attnum>0 and not a.attisdropped and a.attgenerated<>''`);
const invalidGeneratedValues=(relation="public.token_packs")=>sql(`select count(*) from ${relation} where total_tokens is distinct from tokens+bonus_tokens`);

sql(fixture); const beforeProfiles=profileState(),beforeHashes=hashes(),beforePacks=packs(),beforePolicies=policySemantics(),beforeExplicitAcls=explicitProfileAcls();
assert.equal(explicitAclCounts(),'33|30|3|0');
assert.equal(generatedColumn(),'1|total_tokens|integer|s|(tokens + bonus_tokens)');
assert.equal(invalidGeneratedValues(),'0');
assert.equal(sql("select string_agg(name||'|'||total_tokens,',' order by sort_order) from token_packs"),'pack_50|50,pack_200|200,pack_500|500');
sql(file("supabase/manual/lock05c_token_retirement_backup.sql"));
assert.equal(sql("select has_schema_privilege('anon','lock05c_backup_20260811_pre_apply','USAGE')||'|'||has_schema_privilege('authenticated','lock05c_backup_20260811_pre_apply','USAGE')||'|'||has_schema_privilege('service_role','lock05c_backup_20260811_pre_apply','USAGE')"),'false|false|false');
assert.equal(sql("select count(*) from information_schema.columns where table_schema='lock05c_backup_20260811_pre_apply'and column_name='password_hash'"),'0');
assert.equal(sql("select count(*) from lock05c_backup_20260811_pre_apply.policies where table_name in ('profiles','token_packs','token_transactions') and cardinality(role_names)>0"),'3');
assert.equal(sql("select role_names::text from lock05c_backup_20260811_pre_apply.policies where policy_name='token_packs_public_read'"),'{PUBLIC}');
assert.equal(generatedColumn('lock05c_backup_20260811_pre_apply.token_packs'),'1|total_tokens|integer|s|(tokens + bonus_tokens)');
assert.equal(invalidGeneratedValues('lock05c_backup_20260811_pre_apply.token_packs'),'0');
assert.equal(packs('lock05c_backup_20260811_pre_apply.token_packs'),beforePacks);
sql(file("supabase/migrations/20260811070000_lock05c_permanent_token_retirement.sql"));
assert.equal(sql("select to_regclass('public.token_packs') is null and to_regclass('public.token_transactions') is null"),'t');
assert.equal(sql("select count(*) from information_schema.columns where table_schema='public'and (table_name,column_name)in(('profiles','tokens'),('generations','tokens_cost'),('purchases','tokens_received'),('referrals','reward_tokens'),('system_stats','tokens_purchased'),('system_stats','tokens_spent'),('crypto_payments','token_pack_id'))"),'0');
assert.equal(sql("select count(*) from pg_proc where oid in (to_regprocedure('public.add_tokens(uuid,integer,text)'),to_regprocedure('public.deduct_tokens(uuid,integer)'),to_regprocedure('public.deduct_tokens(uuid,integer,text)'),to_regprocedure('public.complete_referral_reward(uuid)'),to_regprocedure('public.get_user_stats(uuid)'))"),'0');
assert.equal(sql("select count(*)||'|'||count(*)filter(where tier='og_throne') from profiles where id='20000000-0000-0000-0000-000000000022'"),'1|1');
assert.equal(sql("select count(*) from pg_attrdef where adrelid='profiles'::regclass and adnum=(select attnum from pg_attribute where attrelid='profiles'::regclass and attname='tier')"),'0');
assert.equal(sql("select has_table_privilege('authenticated','profiles','SELECT')||'|'||has_column_privilege('authenticated','profiles','password_hash','SELECT')"),'false|false');
assert.equal(sql("select count(*) from pg_attribute a cross join lateral aclexplode(a.attacl)x where a.attrelid='profiles'::regclass and x.grantee=(select oid from pg_roles where rolname='authenticated')and x.privilege_type='SELECT'and not a.attisdropped"),'29');
assert.equal(explicitAclCounts(),'32|29|3|0');
assert.equal(hashes(),beforeHashes);
sql("insert into auth.users values('60000000-0000-0000-0000-000000000001','new@test','{}');");
assert.equal(sql("select (id='60000000-0000-0000-0000-000000000001')||'|'||(user_id='60000000-0000-0000-0000-000000000001')||'|'||(email='new@test')||'|'||(referral_code is not null)||'|'||(tier is null)||'|'||(badge='Plebian')||'|'||(subscription_status='none')||'|'||(role='user')||'|'||(is_og_vip=false)||'|'||(is_beta_tester=false)||'|'||(must_change_password=false) from profiles where id='60000000-0000-0000-0000-000000000001'"),'true|true|true|true|true|true|true|true|true|true|true');
assert.equal(sql("select count(*)from information_schema.columns where table_schema='public'and table_name='profiles'and column_name='tokens'"),'0');
sql("delete from profiles where id='60000000-0000-0000-0000-000000000001';delete from auth.users where id='60000000-0000-0000-0000-000000000001';");
sql(file("supabase/manual/lock05c_token_retirement_rollback.sql"));
assert.equal(sql("select to_regclass('public.token_packs') is not null and to_regclass('public.token_transactions') is not null"),'t');
assert.equal(sql("select count(*) from information_schema.columns where table_schema='public'and (table_name,column_name)in(('profiles','tokens'),('generations','tokens_cost'),('purchases','tokens_received'),('referrals','reward_tokens'),('system_stats','tokens_purchased'),('system_stats','tokens_spent'),('crypto_payments','token_pack_id'))"),'7');
assert.equal(sql("select count(*) from pg_proc where oid in ('public.handle_new_user()'::regprocedure,'public.initialize_new_user()'::regprocedure,'public.add_tokens(uuid,integer,text)'::regprocedure,'public.deduct_tokens(uuid,integer)'::regprocedure,'public.deduct_tokens(uuid,integer,text)'::regprocedure,'public.complete_referral_reward(uuid)'::regprocedure,'public.get_user_stats(uuid)'::regprocedure)"),'7');
assert.equal(sql("select count(*) from pg_trigger where not tgisinternal and tgname in ('on_auth_user_created','on_profile_created')"),'2');
assert.match(sql("select pg_get_expr(adbin,adrelid) from pg_attrdef where adrelid='profiles'::regclass and adnum=(select attnum from pg_attribute where attrelid='profiles'::regclass and attname='tier')"),/token_only/);
assert.match(sql("select pg_get_expr(adbin,adrelid) from pg_attrdef where adrelid='purchases'::regclass and adnum=(select attnum from pg_attribute where attrelid='purchases'::regclass and attname='purchase_type')"),/tokens/);
assert.equal(generatedColumn(),'1|total_tokens|integer|s|(tokens + bonus_tokens)'); assert.equal(invalidGeneratedValues(),'0');
assert.equal(explicitAclCounts(),'33|30|3|0'); assert.equal(explicitProfileAcls(),beforeExplicitAcls);
assert.equal(policySemantics(),beforePolicies); assert.equal(profileState(),beforeProfiles); assert.equal(packs(),beforePacks); assert.equal(hashes(),beforeHashes);
console.log("LOCK-05C disposable PostgreSQL integration passed: realistic generated-column prestate, private backup, generated-column backup equality, forward retirement, exact signup, LOCK-05B privileges, rollback, generated-column restoration, explicit ACL equality, policy equality, password_hash immutability, and semantic equality verified");
