-- Phase 4: provider-neutral subscriber Video application. Applying is separately authorized.
begin;
alter table public.video_projects alter column identity_id drop not null;

create table public.video_source_uploads(
 id uuid primary key, owner_id uuid not null references auth.users(id) on delete restrict,
 staging_bucket text not null, staging_key text not null unique, final_bucket text, final_key text unique,
 expected_mime_type text not null check(expected_mime_type in ('image/jpeg','image/png','image/webp')),
 expected_size_bytes bigint not null check(expected_size_bytes between 1 and 52428800), expires_at timestamptz not null,
 finalization_claim_token uuid, finalization_claim_expires_at timestamptz,
 completed_at timestamptz, generation_asset_id uuid unique references public.generation_assets(id) on delete restrict,
 created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(),
 check(expires_at between created_at+interval '20 minutes' and created_at+interval '40 minutes'),
 check(staging_bucket=btrim(staging_bucket) and staging_bucket~'^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$' and (final_bucket is null or (final_bucket=btrim(final_bucket) and final_bucket=staging_bucket))),
 check(staging_key=btrim(staging_key) and (final_key is null or final_key=btrim(final_key))),
 check((expected_mime_type='image/jpeg' and staging_key~'\.jpg$' and (final_key is null or final_key~'\.jpg$')) or (expected_mime_type='image/png' and staging_key~'\.png$' and (final_key is null or final_key~'\.png$')) or (expected_mime_type='image/webp' and staging_key~'\.webp$' and (final_key is null or final_key~'\.webp$'))),
 check((finalization_claim_token is null)=(finalization_claim_expires_at is null))
);
alter table public.video_source_uploads enable row level security; alter table public.video_source_uploads force row level security;
revoke all on table public.video_source_uploads from public,anon,authenticated,service_role;

create function public.create_video_source_upload(p_upload_id uuid,p_owner_id uuid,p_staging_bucket text,p_staging_key text,p_expected_mime text,p_expected_size bigint,p_expires_at timestamptz) returns void language plpgsql security definer set search_path=pg_catalog,public as $$
declare ext text;
begin
 if p_upload_id is null or p_owner_id is null or p_expected_mime not in ('image/jpeg','image/png','image/webp') or p_expected_size not between 1 and 52428800 or p_expires_at not between clock_timestamp()+interval '20 minutes' and clock_timestamp()+interval '40 minutes' or p_staging_bucket<>btrim(p_staging_bucket) or p_staging_key<>btrim(p_staging_key) or p_staging_bucket!~'^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$' then raise exception 'VIDEO_SOURCE_UPLOAD_INVALID'; end if;
 ext:=case p_expected_mime when 'image/jpeg' then 'jpg' when 'image/png' then 'png' else 'webp' end;
 if p_staging_key!~('^creator-video-source-staging/'||p_owner_id::text||'/'||p_upload_id::text||'\.'||ext||'$') then raise exception 'VIDEO_SOURCE_UPLOAD_INVALID'; end if;
 insert into public.video_source_uploads(id,owner_id,staging_bucket,staging_key,expected_mime_type,expected_size_bytes,expires_at) values(p_upload_id,p_owner_id,p_staging_bucket,p_staging_key,p_expected_mime,p_expected_size,p_expires_at);
end$$;

create function public.claim_video_source_upload_finalization(p_upload_id uuid,p_owner_id uuid,p_claim_token uuid) returns table(claimed boolean,staging_bucket text,staging_key text,expected_mime_type text,expected_size_bytes bigint,generation_id uuid,generation_asset_id uuid) language plpgsql security definer set search_path=pg_catalog,public as $$
declare u public.video_source_uploads;
begin
 if p_upload_id is null or p_owner_id is null or p_claim_token is null then raise exception 'VIDEO_SOURCE_UPLOAD_NOT_FOUND'; end if;
 select * into u from public.video_source_uploads where id=p_upload_id and owner_id=p_owner_id for update;
 if not found then raise exception 'VIDEO_SOURCE_UPLOAD_NOT_FOUND'; end if;
 if u.generation_asset_id is not null then return query select false,u.staging_bucket,u.staging_key,u.expected_mime_type,u.expected_size_bytes,a.generation_id,a.id from public.generation_assets a where a.id=u.generation_asset_id; return; end if;
 if u.expires_at<=clock_timestamp() then raise exception 'VIDEO_SOURCE_UPLOAD_EXPIRED'; end if;
 if u.finalization_claim_token is not null and u.finalization_claim_expires_at>clock_timestamp() then return query select false,u.staging_bucket,u.staging_key,u.expected_mime_type,u.expected_size_bytes,null::uuid,null::uuid; return; end if;
 update public.video_source_uploads set finalization_claim_token=p_claim_token,finalization_claim_expires_at=clock_timestamp()+interval '2 minutes',updated_at=clock_timestamp() where id=u.id;
 return query select true,u.staging_bucket,u.staging_key,u.expected_mime_type,u.expected_size_bytes,null::uuid,null::uuid;
end$$;

create function public.finalize_video_source_upload(p_upload_id uuid,p_owner_id uuid,p_claim_token uuid,p_final_bucket text,p_final_key text,p_mime_type text,p_size_bytes bigint,p_sha256 text) returns table(generation_id uuid,generation_asset_id uuid) language plpgsql security definer set search_path=pg_catalog,public as $$
declare u public.video_source_uploads; gid uuid; oid uuid; aid uuid; ext text;
begin
 select * into u from public.video_source_uploads where id=p_upload_id and owner_id=p_owner_id for update; if not found then raise exception 'VIDEO_SOURCE_UPLOAD_NOT_FOUND'; end if;
 if u.generation_asset_id is not null then return query select a.generation_id,a.id from public.generation_assets a where a.id=u.generation_asset_id; return; end if;
 if u.finalization_claim_token is distinct from p_claim_token or u.finalization_claim_expires_at<=clock_timestamp() then raise exception 'VIDEO_SOURCE_UPLOAD_CLAIM_INVALID'; end if;
 ext:=case u.expected_mime_type when 'image/jpeg' then 'jpg' when 'image/png' then 'png' else 'webp' end;
 if u.expires_at<=clock_timestamp() or p_final_bucket is distinct from u.staging_bucket or p_final_key is null or p_final_key<>btrim(p_final_key) or p_final_key!~('^creator-video-sources/'||p_owner_id::text||'/'||p_upload_id::text||'/'||p_sha256||'-'||p_claim_token::text||'\.'||ext||'$') or p_mime_type<>u.expected_mime_type or p_size_bytes<>u.expected_size_bytes or p_sha256!~'^[0-9a-f]{64}$' then raise exception 'VIDEO_SOURCE_UPLOAD_VERIFICATION_INVALID'; end if;
 gid:=gen_random_uuid();
 insert into public.generations(id,user_id,prompt,image_url,job_type,body_type,mode,status,negative_prompt,completed_at,metadata,updated_at) values(gid,p_owner_id,'',null,'image','none','video_source_import','completed','',clock_timestamp(),jsonb_build_object('kind','image','policy_version',1,'private_creator_media',true,'source_mode','video_source_import','video_source_upload_id',u.id),clock_timestamp());
 insert into public.private_storage_objects(owner_id,storage_class,bucket,object_key,mime_type,size_bytes,sha256,source_reference) values(p_owner_id,'creator_generation',p_final_bucket,p_final_key,p_mime_type,p_size_bytes,p_sha256,jsonb_build_object('video_source_upload_id',u.id,'generation_id',gid)) returning id into oid;
 insert into public.generation_assets(generation_id,storage_object_id,owner_id,ordinal,kind) values(gid,oid,p_owner_id,0,'image') returning id into aid;
 update public.video_source_uploads set final_bucket=p_final_bucket,final_key=p_final_key,generation_asset_id=aid,completed_at=clock_timestamp(),finalization_claim_token=null,finalization_claim_expires_at=null,updated_at=clock_timestamp() where id=u.id;
 return query select gid,aid;
end$$;

create or replace function public.submit_video_project_compute_jobs(p_owner_id uuid,p_identity_id uuid,p_source_generation_asset_id uuid,p_idempotency_key text,p_request_fingerprint text,p_request_payload jsonb,p_priority_class text)
returns table(project_id uuid,creator_status text,created_at timestamptz,completed_at timestamptz,can_cancel boolean) language plpgsql security definer set search_path=pg_catalog,public as $$
declare p public.video_projects; vj public.compute_jobs; sj public.compute_jobs; vp public.compute_scheduler_policies; sp public.compute_scheduler_policies; duration integer; segments integer; v_mode text; motion numeric; source jsonb:=null; identity_reference jsonb:=null; manifest jsonb;
begin
 if p_owner_id is null or length(p_idempotency_key) not between 1 and 128 or p_request_fingerprint!~'^[0-9a-f]{64}$' or jsonb_typeof(p_request_payload)<>'object' or p_priority_class not in ('og','standard') or (select array_agg(k order by k) from jsonb_object_keys(p_request_payload) k)<>array['body_type','identity_id','mode','motion_strength','negative_prompt','prompt','requested_duration_seconds','source_generation_asset_id']::text[] then raise exception 'INVALID_VIDEO_PROJECT_SUBMISSION'; end if;
 if jsonb_typeof(p_request_payload->'mode')<>'string' or jsonb_typeof(p_request_payload->'prompt')<>'string' or jsonb_typeof(p_request_payload->'negative_prompt')<>'string' or jsonb_typeof(p_request_payload->'body_type')<>'string' or jsonb_typeof(p_request_payload->'requested_duration_seconds')<>'number' or p_request_payload->>'requested_duration_seconds'!~'^[0-9]+$' or jsonb_typeof(p_request_payload->'motion_strength')<>'number' or p_request_payload->>'motion_strength'!~'^(0|1)(\.[0-9]+)?$' or jsonb_typeof(p_request_payload->'identity_id') not in ('string','null') or jsonb_typeof(p_request_payload->'source_generation_asset_id') not in ('string','null') then raise exception 'INVALID_VIDEO_PROJECT_REQUEST'; end if;
 if p_request_payload->'identity_id' is distinct from coalesce(to_jsonb(p_identity_id),'null'::jsonb) or p_request_payload->'source_generation_asset_id' is distinct from coalesce(to_jsonb(p_source_generation_asset_id),'null'::jsonb) then raise exception 'INVALID_VIDEO_PROJECT_SUBMISSION'; end if;
 v_mode:=p_request_payload->>'mode'; duration:=(p_request_payload->>'requested_duration_seconds')::integer; motion:=(p_request_payload->>'motion_strength')::numeric; segments:=case p_priority_class when 'standard' then 2 else 3 end;
 if v_mode not in ('text_to_video','image_to_video') or p_request_payload->>'body_type' not in ('body_feminine','body_masculine','none') or length(p_request_payload->>'prompt')>4000 or length(p_request_payload->>'negative_prompt')>4000 or (v_mode='text_to_video' and btrim(p_request_payload->>'prompt')='') then raise exception 'INVALID_VIDEO_PROJECT_REQUEST'; end if;
 if (p_priority_class='standard' and (duration not between 10 and 15 or motion not between .40 and .80)) or (p_priority_class='og' and (duration not between 20 and 25 or motion not between .60 and 1.00)) then raise exception 'VIDEO_TIER_INVALID'; end if;
 if v_mode='text_to_video' and p_source_generation_asset_id is not null then raise exception 'VIDEO_SOURCE_MODE_INVALID'; end if; if v_mode='image_to_video' and p_source_generation_asset_id is null then raise exception 'VIDEO_SOURCE_REQUIRED'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_owner_id::text||':video-project:'||p_idempotency_key,0)); select * into p from public.video_projects x where x.owner_id=p_owner_id and x.idempotency_key=p_idempotency_key; if found then if p.request_fingerprint<>p_request_fingerprint then raise exception 'IDEMPOTENCY_CONFLICT'; end if; return query select p.id,x->>'creator_status',p.created_at,case when x->>'creator_status'='completed' then p.completed_at else null end,(x->>'can_cancel')::boolean from public.video_project_creator_projection(p) x; return; end if;
 if p_identity_id is not null then select jsonb_build_object('id',l.id,'bucket',btrim(l.artifact_r2_bucket),'key',btrim(l.artifact_r2_key),'trigger_token',btrim(l.trigger_token)) into identity_reference from public.user_loras l where l.id=p_identity_id and l.user_id=p_owner_id and l.status='completed' and btrim(coalesce(l.artifact_r2_bucket,''))<>'' and btrim(coalesce(l.artifact_r2_key,''))<>'' and btrim(coalesce(l.trigger_token,''))<>'' for update; if identity_reference is null then raise exception 'VIDEO_IDENTITY_NOT_READY'; end if; end if;
 if v_mode='image_to_video' then select jsonb_build_object('bucket',o.bucket,'object_key',o.object_key,'mime_type',o.mime_type,'size_bytes',o.size_bytes,'sha256',o.sha256) into source from public.generation_assets ga join public.generations g on g.id=ga.generation_id join public.private_storage_objects o on o.id=ga.storage_object_id where ga.id=p_source_generation_asset_id and ga.owner_id=p_owner_id and ga.kind='image' and g.user_id=p_owner_id and g.status='completed' and g.image_url is null and o.owner_id=p_owner_id and o.storage_class='creator_generation' and o.mime_type in ('image/jpeg','image/png','image/webp') for update of ga,g,o; if source is null then raise exception 'VIDEO_SOURCE_INVALID'; end if; end if;
 select * into vp from public.compute_scheduler_policies where workload='video' and enabled for update; if not found then raise exception 'COMPUTE_POLICY_UNCONFIGURED'; end if; select * into sp from public.compute_scheduler_policies where workload='stitch' and enabled for update; if not found then raise exception 'COMPUTE_POLICY_UNCONFIGURED'; end if; p.id:=gen_random_uuid();
 manifest:=jsonb_build_object('project_id',p.id,'mode',v_mode,'segment_count',segments,'requested_duration_seconds',duration,'target_fps',30,'target_min_short_edge',1080,'prompt',btrim(p_request_payload->>'prompt'),'negative_prompt',btrim(p_request_payload->>'negative_prompt'),'body_type',p_request_payload->>'body_type','motion_strength',motion,'identity_id',p_identity_id,'identity_reference',identity_reference,'source',source);
 insert into public.compute_jobs(owner_id,workload,idempotency_key,request_fingerprint,request_payload,priority_class,max_attempts) values(p_owner_id,'video','project:'||p.id,p_request_fingerprint,manifest,p_priority_class,vp.max_attempts) returning * into vj;
 insert into public.compute_jobs(owner_id,workload,idempotency_key,request_fingerprint,request_payload,priority_class,max_attempts) values(p_owner_id,'stitch','project:'||p.id,p_request_fingerprint,jsonb_build_object('project_id',p.id,'segment_count',segments,'requested_duration_seconds',duration,'target_fps',30,'target_min_short_edge',1080),p_priority_class,sp.max_attempts) returning * into sj;
 insert into public.video_projects(id,owner_id,identity_id,source_generation_asset_id,idempotency_key,request_fingerprint,request_payload,priority_class,mode,requested_duration_seconds,segment_count,video_job_id,stitch_job_id) values(p.id,p_owner_id,p_identity_id,p_source_generation_asset_id,p_idempotency_key,p_request_fingerprint,p_request_payload,p_priority_class,v_mode,duration,segments,vj.id,sj.id) returning * into p; return query select p.id,'queued',p.created_at,p.completed_at,true;
end$$;

create function public.phase4_video_project_manifest(p public.video_projects) returns jsonb language plpgsql set search_path=pg_catalog,public as $$
declare source jsonb:=null; identity_reference jsonb:=null; expected jsonb;
begin
 if p.identity_id is not null then select jsonb_build_object('id',l.id,'bucket',btrim(l.artifact_r2_bucket),'key',btrim(l.artifact_r2_key),'trigger_token',btrim(l.trigger_token)) into identity_reference from public.user_loras l where l.id=p.identity_id and l.user_id=p.owner_id and l.status='completed' and btrim(coalesce(l.artifact_r2_bucket,''))<>'' and btrim(coalesce(l.artifact_r2_key,''))<>'' and btrim(coalesce(l.trigger_token,''))<>''; if identity_reference is null then raise exception 'VIDEO_IDENTITY_NOT_READY'; end if; end if;
 if p.mode='image_to_video' then select jsonb_build_object('bucket',o.bucket,'object_key',o.object_key,'mime_type',o.mime_type,'size_bytes',o.size_bytes,'sha256',o.sha256) into source from public.generation_assets ga join public.generations g on g.id=ga.generation_id join public.private_storage_objects o on o.id=ga.storage_object_id where ga.id=p.source_generation_asset_id and ga.owner_id=p.owner_id and ga.kind='image' and g.user_id=p.owner_id and g.status='completed' and g.image_url is null and o.owner_id=p.owner_id and o.storage_class='creator_generation' and o.mime_type in ('image/jpeg','image/png','image/webp'); if source is null then raise exception 'VIDEO_SOURCE_INVALID'; end if; end if;
 expected:=jsonb_build_object('project_id',p.id,'mode',p.mode,'segment_count',p.segment_count,'requested_duration_seconds',p.requested_duration_seconds,'target_fps',p.target_fps,'target_min_short_edge',p.target_min_short_edge,'prompt',btrim(p.request_payload->>'prompt'),'negative_prompt',btrim(p.request_payload->>'negative_prompt'),'body_type',p.request_payload->>'body_type','motion_strength',(p.request_payload->>'motion_strength')::numeric,'identity_id',p.identity_id,'identity_reference',identity_reference,'source',source); return expected;
end$$;

create or replace function public.video_compute_manifest(p_job_id uuid,p_attempt_id uuid,p_lease_token uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare j public.compute_jobs;a public.compute_job_attempts;p public.video_projects;m jsonb;begin select * into j from public.compute_jobs where id=p_job_id;select * into a from public.compute_job_attempts where id=p_attempt_id and job_id=p_job_id;if not found or j.workload<>'video' or j.state not in('claimed','running','cancel_requested') or j.lease_token is distinct from p_lease_token or j.lease_expires_at<=clock_timestamp() or a.lease_token<>p_lease_token or a.ordinal<>j.attempt_count or a.finished_at is not null then raise exception 'VIDEO_MANIFEST_AUTHORITY_MISMATCH';end if;select * into p from public.video_projects where video_job_id=j.id and owner_id=j.owner_id;if not found then raise exception 'VIDEO_PROJECT_BINDING_MISMATCH';end if;m:=public.phase4_video_project_manifest(p);if j.request_payload is distinct from m then raise exception 'VIDEO_REQUEST_AUTHORITY_MISMATCH';end if;return m;end$$;
create or replace function public.recovered_video_compute_manifest(p_job_id uuid,p_attempt_id uuid,p_recovery_token uuid,p_recovery_lease_token uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare j public.compute_jobs;a public.compute_job_attempts;p public.video_projects;m jsonb;begin select * into j from public.compute_jobs where id=p_job_id;select * into a from public.compute_job_attempts where id=p_attempt_id and job_id=p_job_id;if not found or j.workload<>'video' or j.state<>'recovering' or a.finished_at is not null or a.ordinal<>j.attempt_count or a.recovery_token is distinct from p_recovery_token or a.recovery_lease_token is distinct from p_recovery_lease_token or a.recovery_lease_expires_at<=clock_timestamp() then raise exception 'VIDEO_RECOVERY_AUTHORITY_MISMATCH';end if;select * into p from public.video_projects where video_job_id=j.id and owner_id=j.owner_id;if not found then raise exception 'VIDEO_PROJECT_BINDING_MISMATCH';end if;m:=public.phase4_video_project_manifest(p);if j.request_payload is distinct from m then raise exception 'VIDEO_REQUEST_AUTHORITY_MISMATCH';end if;return m;end$$;

create function public.creator_video_project_product(p_owner_id uuid,p_project_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare p public.video_projects;v public.compute_jobs;s public.compute_jobs;g public.generations;a public.generation_assets;o public.private_storage_objects;x jsonb;aid uuid;
begin select * into p from public.video_projects where id=p_project_id and owner_id=p_owner_id;if not found then raise exception 'VIDEO_PROJECT_NOT_FOUND';end if;x:=public.video_project_creator_projection(p);if x->>'creator_status'<>'completed' then raise exception 'VIDEO_PRODUCT_NOT_CANONICAL';end if;select * into v from public.compute_jobs where id=p.video_job_id and owner_id=p.owner_id and workload='video' and state='succeeded';select * into s from public.compute_jobs where id=p.stitch_job_id and owner_id=p.owner_id and workload='stitch' and state='succeeded';if v.id is null or s.id is null then raise exception 'VIDEO_PRODUCT_NOT_CANONICAL';end if;aid:=(s.result_reference->'asset_ids'->>0)::uuid;if (select array_agg(k order by k) from jsonb_object_keys(s.result_reference) k)<>array['asset_ids','generation_id','project_id']::text[] or s.result_reference->>'project_id'<>p.id::text or s.result_reference->>'generation_id'<>p.id::text or jsonb_array_length(s.result_reference->'asset_ids')<>1 then raise exception 'VIDEO_PRODUCT_NOT_CANONICAL';end if;select * into g from public.generations where id=p.id and user_id=p.owner_id and status='completed' and job_type='video' and image_url is null;select * into a from public.generation_assets where id=aid and generation_id=p.id and owner_id=p.owner_id and ordinal=0 and kind='video';if g.id is null or a.id is null or (select count(*) from public.generation_assets where generation_id=p.id)<>1 then raise exception 'VIDEO_PRODUCT_NOT_CANONICAL';end if;select * into o from public.private_storage_objects where id=a.storage_object_id and owner_id=p.owner_id and storage_class='creator_generation' and mime_type='video/mp4' and bucket=p.storage_bucket and object_key~('^creator-video-projects/'||p.id::text||'/final/[^/]+$');if o.id is null then raise exception 'VIDEO_PRODUCT_NOT_CANONICAL';end if;return jsonb_build_object('project_id',p.id,'generation_id',g.id,'prompt',g.prompt,'negative_prompt',g.negative_prompt,'mode',p.mode,'body_type',g.body_type,'completed_at',g.completed_at,'identity_id',p.identity_id,'source_generation_asset_id',p.source_generation_asset_id,'requested_duration_seconds',p.requested_duration_seconds,'motion_strength',(p.request_payload->>'motion_strength')::numeric,'actual_duration_ms',(g.metadata->>'actual_duration_ms')::integer,'fps_millihz',(g.metadata->>'fps_millihz')::integer,'width',g.width,'height',g.height,'output',jsonb_build_object('id',a.id,'generation_id',g.id,'kind','video','private_asset',true));end$$;
revoke all on function public.create_video_source_upload(uuid,uuid,text,text,text,bigint,timestamptz),public.claim_video_source_upload_finalization(uuid,uuid,uuid),public.finalize_video_source_upload(uuid,uuid,uuid,text,text,text,bigint,text),public.creator_video_project_product(uuid,uuid) from public,anon,authenticated,service_role;
grant execute on function public.create_video_source_upload(uuid,uuid,text,text,text,bigint,timestamptz),public.claim_video_source_upload_finalization(uuid,uuid,uuid),public.finalize_video_source_upload(uuid,uuid,uuid,text,text,text,bigint,text),public.creator_video_project_product(uuid,uuid) to service_role;
revoke all on function public.phase4_video_project_manifest(public.video_projects) from public,anon,authenticated,service_role;
commit;
