-- Task 13: trusted creator-triggered compliance submission. No queue tasks, platform network calls, credentials, uploads, generation changes, or human decisions.
create unique index if not exists creator_publishing_compliance_evaluated_actor_key_uidx
  on public.creator_publishing_audit_events(actor_id, idempotency_key)
  where action = 'creator_publishing_compliance_evaluated' and idempotency_key is not null;

create or replace function public.creator_publishing_build_compliance_facts(p_creator_id uuid, p_content_package_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_package public.creator_publishing_content_packages%rowtype; v_account public.creator_platform_accounts%rowtype; v_creator_verification public.creator_publishing_creator_verifications%rowtype; v_consent public.creator_publishing_ai_twin_consents%rowtype; v_media jsonb := '[]'::jsonb; v_generations jsonb := '[]'::jsonb; v_generation_ids uuid[]; v_media_count int; v_bad_count int; v_duplicate_count int; v_co_count int; v_co_all boolean; v_active_queue boolean; v_profile_id uuid;
begin
  select * into v_package from public.creator_publishing_content_packages where id=p_content_package_id;
  if not found or v_package.creator_id <> p_creator_id then raise exception 'COMPLIANCE_PACKAGE_NOT_FOUND'; end if;
  if v_package.target_platform = 'fanvue' then raise exception 'COMPLIANCE_FANVUE_NOT_SUPPORTED'; end if;
  if v_package.creator_approval_status = 'approved' then raise exception 'COMPLIANCE_PACKAGE_LOCKED'; end if;
  select exists(select 1 from public.creator_publishing_queue_tasks q where q.content_package_id=v_package.id and q.status <> 'archived') into v_active_queue;
  if v_active_queue then raise exception 'COMPLIANCE_PACKAGE_LOCKED'; end if;
  select * into v_account from public.creator_platform_accounts where id=v_package.platform_account_id;
  if not found or v_account.creator_id<>p_creator_id or v_account.platform<>v_package.target_platform then raise exception 'COMPLIANCE_PLATFORM_ACCOUNT_INVALID'; end if;
  select * into v_creator_verification from public.creator_publishing_creator_verifications where creator_id=p_creator_id;
  select * into v_consent from public.creator_publishing_ai_twin_consents where creator_id=p_creator_id;
  select count(*) into v_media_count from public.creator_publishing_media_assets where content_package_id=v_package.id;
  if v_media_count = 0 then raise exception 'COMPLIANCE_MEDIA_REQUIRED'; end if;
  select count(*) into v_bad_count from public.creator_publishing_media_assets where content_package_id=v_package.id and source <> 'ai_pipeline';
  if v_bad_count > 0 then raise exception 'COMPLIANCE_UNTRUSTED_MEDIA_SOURCE'; end if;
  select count(*) into v_bad_count from public.creator_publishing_media_assets where content_package_id=v_package.id and (ai_generation_metadata->>'generation_id') is null;
  if v_bad_count > 0 then raise exception 'COMPLIANCE_GENERATION_LINK_INVALID'; end if;
  begin
    select array_agg((ai_generation_metadata->>'generation_id')::uuid order by (ai_generation_metadata->>'generation_id')::uuid) into v_generation_ids from public.creator_publishing_media_assets where content_package_id=v_package.id;
  exception when invalid_text_representation then raise exception 'COMPLIANCE_GENERATION_LINK_INVALID'; end;
  select count(*) - count(distinct (ai_generation_metadata->>'generation_id')) into v_duplicate_count from public.creator_publishing_media_assets where content_package_id=v_package.id;
  if v_duplicate_count > 0 then raise exception 'COMPLIANCE_GENERATION_LINK_INVALID'; end if;
  select id into v_profile_id from public.profiles where user_id=p_creator_id limit 1;
  if exists (select 1 from unnest(v_generation_ids) gid left join public.generations g on g.id=gid where g.id is null) then raise exception 'COMPLIANCE_GENERATION_NOT_FOUND'; end if;
  if exists (select 1 from public.generations g where g.id=any(v_generation_ids) and g.user_id not in (p_creator_id, coalesce(v_profile_id,p_creator_id))) then raise exception 'COMPLIANCE_GENERATION_NOT_OWNED'; end if;
  if exists (select 1 from public.generations g where g.id=any(v_generation_ids) and (g.status <> 'completed' or nullif(btrim(coalesce(g.r2_bucket,'')),'') is null or nullif(btrim(coalesce(g.r2_key,'')),'') is null or coalesce((g.metadata->>'placeholder')::boolean,false) or coalesce((g.metadata->>'is_placeholder')::boolean,false) or coalesce((g.metadata->>'test')::boolean,false) or coalesce((g.metadata->>'is_test')::boolean,false) or coalesce((g.metadata->>'unsafe')::boolean,false) or lower(coalesce(g.metadata->>'safety',''))='unsafe')) then raise exception 'COMPLIANCE_GENERATION_NOT_ELIGIBLE'; end if;
  select jsonb_agg(jsonb_build_object('id',m.id,'storage_key',m.storage_key,'mime_type',m.mime_type,'sha256',lower(m.sha256),'source',m.source,'ai_generation_metadata',m.ai_generation_metadata) order by m.id) into v_media from public.creator_publishing_media_assets m where m.content_package_id=v_package.id;
  select jsonb_agg(jsonb_build_object('generation_id',g.id,'user_id',g.user_id,'status',g.status,'lora_used',g.lora_used,'job_type',g.job_type,'body_type',g.body_type,'mode',g.mode,'r2_bucket',g.r2_bucket,'r2_key',g.r2_key,'safe_classification_metadata', jsonb_strip_nulls(jsonb_build_object('non_photorealistic',case when jsonb_typeof(g.metadata->'non_photorealistic')='boolean' then g.metadata->'non_photorealistic' end,'photorealistic',case when jsonb_typeof(g.metadata->'photorealistic')='boolean' then g.metadata->'photorealistic' end,'lifelike',case when jsonb_typeof(g.metadata->'lifelike')='boolean' then g.metadata->'lifelike' end,'deepfake',case when jsonb_typeof(g.metadata->'deepfake')='boolean' then g.metadata->'deepfake' end,'face_swap',case when jsonb_typeof(g.metadata->'face_swap')='boolean' then g.metadata->'face_swap' end,'unauthorized_face_swap',case when jsonb_typeof(g.metadata->'unauthorized_face_swap')='boolean' then g.metadata->'unauthorized_face_swap' end,'third_party_likeness',case when jsonb_typeof(g.metadata->'third_party_likeness')='boolean' then g.metadata->'third_party_likeness' end,'ai_background_edit',case when jsonb_typeof(g.metadata->'ai_background_edit')='boolean' then g.metadata->'ai_background_edit' end,'ai_outfit_edit',case when jsonb_typeof(g.metadata->'ai_outfit_edit')='boolean' then g.metadata->'ai_outfit_edit' end,'ai_lighting_edit',case when jsonb_typeof(g.metadata->'ai_lighting_edit')='boolean' then g.metadata->'ai_lighting_edit' end,'body_adjacent_edit',case when jsonb_typeof(g.metadata->'body_adjacent_edit')='boolean' then g.metadata->'body_adjacent_edit' end,'upscaled',case when jsonb_typeof(g.metadata->'upscaled')='boolean' then g.metadata->'upscaled' end,'creator_likeness_drift',case when jsonb_typeof(g.metadata->'creator_likeness_drift')='boolean' then g.metadata->'creator_likeness_drift' end,'heavy_alteration',case when jsonb_typeof(g.metadata->'heavy_alteration')='boolean' then g.metadata->'heavy_alteration' end,'synthetic_persona',case when jsonb_typeof(g.metadata->'synthetic_persona')='boolean' then g.metadata->'synthetic_persona' end,'fictional_persona',case when jsonb_typeof(g.metadata->'fictional_persona')='boolean' then g.metadata->'fictional_persona' end,'composite_persona',case when jsonb_typeof(g.metadata->'composite_persona')='boolean' then g.metadata->'composite_persona' end,'ai_contribution_more_than_cosmetic',case when jsonb_typeof(g.metadata->'ai_contribution_more_than_cosmetic')='boolean' then g.metadata->'ai_contribution_more_than_cosmetic' end,'borderline_lifelike_stylized',case when jsonb_typeof(g.metadata->'borderline_lifelike_stylized')='boolean' then g.metadata->'borderline_lifelike_stylized' end,'ambiguous_background_people',case when jsonb_typeof(g.metadata->'ambiguous_background_people')='boolean' then g.metadata->'ambiguous_background_people' end))) order by g.id) into v_generations from public.generations g where g.id=any(v_generation_ids);
  select count(*), coalesce(bool_and(platform_release_confirmed), false) into v_co_count, v_co_all from public.creator_publishing_co_performer_records where content_package_id=v_package.id;
  return jsonb_build_object('schema_version','creator-publishing-compliance-facts-v1','package',jsonb_build_object('id',v_package.id,'creator_id',v_package.creator_id,'platform_account_id',v_package.platform_account_id,'target_platform',v_package.target_platform,'title',v_package.title,'caption_body',v_package.caption_body,'second_person_present',v_package.second_person_present,'creator_approval_status',v_package.creator_approval_status,'compliance_status',v_package.compliance_status,'compliance_policy_version',v_package.compliance_policy_version,'updated_at',v_package.updated_at),'platform_account',jsonb_build_object('id',v_account.id,'creator_id',v_account.creator_id,'platform',v_account.platform,'verification_status',v_account.verification_status,'updated_at',v_account.updated_at,'is_virtual_entity',v_account.is_virtual_entity),'creator_verification',jsonb_build_object('status',coalesce(v_creator_verification.status,'unverified'),'updated_at',v_creator_verification.updated_at),'ai_twin_consent',jsonb_build_object('status',coalesce(v_consent.status,'missing'),'attestation_version',v_consent.attestation_version,'attestation_text_sha256',v_consent.attestation_text_sha256,'granted_at',v_consent.granted_at,'revoked_at',v_consent.revoked_at,'updated_at',v_consent.updated_at),'media_manifest',v_media,'generation_manifest',v_generations,'co_performer_summary',jsonb_build_object('record_count',v_co_count,'all_platform_release_confirmed',v_co_all),'active_queue_task',v_active_queue);
end; $$;

create or replace function public.creator_publishing_load_compliance_facts(p_creator_id uuid, p_content_package_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_facts jsonb; begin v_facts := public.creator_publishing_build_compliance_facts(p_creator_id,p_content_package_id); return jsonb_build_object('facts',v_facts,'facts_fingerprint',encode(extensions.digest(v_facts::text,'sha256'),'hex'),'media_manifest_hash',encode(extensions.digest((v_facts->'media_manifest')::text,'sha256'),'hex')); end; $$;

create or replace function public.creator_publishing_apply_automated_compliance_evaluation(p_creator_id uuid,p_content_package_id uuid,p_expected_package_updated_at timestamptz,p_facts_fingerprint text,p_media_manifest_hash text,p_policy_version text,p_outcome text,p_forced_disclosure_text text,p_normalized_caption text,p_ai_flag text,p_ai_detail jsonb,p_rule_hits jsonb,p_reasons jsonb,p_review_requirements jsonb,p_evaluator_metadata jsonb,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_now timestamptz:=transaction_timestamp(); v_package public.creator_publishing_content_packages%rowtype; v_account public.creator_platform_accounts%rowtype; v_cv public.creator_publishing_creator_verifications%rowtype; v_consent public.creator_publishing_ai_twin_consents%rowtype; v_facts jsonb; v_review_id uuid; v_audit_id bigint; v_prior text; v_request jsonb; v_request_fingerprint text; v_existing public.creator_publishing_audit_events%rowtype; v_result_state jsonb; v_result_fp text; v_review_outcome text; v_has_block boolean; v_has_review boolean; v_stored_updated timestamptz;
begin
  if p_creator_id is null or p_content_package_id is null or p_expected_package_updated_at is null or coalesce(p_facts_fingerprint,'') !~ '^[0-9a-f]{64}$' or coalesce(p_media_manifest_hash,'') !~ '^[0-9a-f]{64}$' or length(btrim(coalesce(p_policy_version,''))) not between 1 and 120 or coalesce(p_idempotency_key,'') !~ '^[A-Za-z0-9_-]{8,128}$' or p_outcome not in ('passed','manual_review','blocked') or p_ai_flag <> 'ai_generated' or jsonb_typeof(p_ai_detail) <> 'object' or jsonb_typeof(p_rule_hits) <> 'array' or jsonb_typeof(p_reasons) <> 'array' or jsonb_typeof(p_review_requirements) <> 'array' or jsonb_typeof(p_evaluator_metadata) <> 'object' or p_normalized_caption is null or length(p_normalized_caption) > 12000 or public.creator_publishing_queue_jsonb_has_forbidden_credential_key(p_ai_detail) or public.creator_publishing_queue_jsonb_has_forbidden_credential_key(p_evaluator_metadata) then raise exception 'COMPLIANCE_INVALID_EVALUATION'; end if;
  if exists (select 1 from jsonb_array_elements(p_rule_hits) h where jsonb_typeof(h) <> 'object' or coalesce(h->>'rule_id','')='' or h->>'severity' not in ('allow','review','block') or coalesce(h->>'category','')='' or coalesce(h->>'message','')='' or coalesce(h->>'source','')='' or coalesce(h->>'field','')='' or not (h ? 'evidence') or jsonb_typeof(h->'override_allowed') <> 'boolean' or public.creator_publishing_queue_jsonb_has_forbidden_credential_key(h)) then raise exception 'COMPLIANCE_INVALID_EVALUATION'; end if;
  select exists(select 1 from jsonb_array_elements(p_rule_hits) h where h->>'severity'='block'), exists(select 1 from jsonb_array_elements(p_rule_hits) h where h->>'severity'='review') into v_has_block, v_has_review;
  if (v_has_block and p_outcome <> 'blocked') or (not v_has_block and v_has_review and p_outcome <> 'manual_review') or (not v_has_block and not v_has_review and p_outcome <> 'passed') then raise exception 'COMPLIANCE_INVALID_EVALUATION'; end if;
  v_request := jsonb_build_object('creator_id',p_creator_id,'content_package_id',p_content_package_id,'expected_updated_at',p_expected_package_updated_at,'facts_fingerprint',p_facts_fingerprint,'media_manifest_hash',p_media_manifest_hash,'policy_version',p_policy_version,'outcome',p_outcome,'forced_disclosure_text',p_forced_disclosure_text,'normalized_caption',p_normalized_caption,'ai_flag',p_ai_flag,'ai_detail',p_ai_detail,'rule_hits',p_rule_hits,'reasons',p_reasons,'review_requirements',p_review_requirements,'evaluator_metadata',p_evaluator_metadata);
  v_request_fingerprint := encode(extensions.digest(v_request::text,'sha256'),'hex');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('creator_compliance_key:'||p_creator_id::text||':'||p_idempotency_key,0));
  select * into v_existing from public.creator_publishing_audit_events where actor_id=p_creator_id and idempotency_key=p_idempotency_key and action='creator_publishing_compliance_evaluated' limit 1;
  if found then
    if coalesce(v_existing.after_state->>'request_fingerprint','') !~ '^[0-9a-f]{64}$' or v_existing.after_state->>'request_fingerprint' <> v_request_fingerprint then raise exception 'COMPLIANCE_IDEMPOTENCY_CONFLICT'; end if;
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('creator_compliance_package:'||p_content_package_id::text,0));
    begin v_stored_updated := (v_existing.after_state->>'resulting_updated_at')::timestamptz; exception when others then raise exception 'COMPLIANCE_IDEMPOTENCY_CONFLICT'; end;
    select * into v_package from public.creator_publishing_content_packages where id=p_content_package_id for update; if not found or v_package.updated_at is distinct from v_stored_updated then raise exception 'COMPLIANCE_IDEMPOTENCY_CONFLICT'; end if;
    v_result_state := jsonb_build_object('content_package_id',v_package.id,'compliance_status',v_package.compliance_status,'compliance_policy_version',v_package.compliance_policy_version,'forced_disclosure_text',v_package.forced_disclosure_text,'ai_flag',v_package.ai_flag,'ai_detail',v_package.ai_detail,'creator_approval_status',v_package.creator_approval_status,'updated_at',v_package.updated_at);
    if encode(extensions.digest(v_result_state::text,'sha256'),'hex') <> v_existing.after_state->>'resulting_package_state_fingerprint' then raise exception 'COMPLIANCE_IDEMPOTENCY_CONFLICT'; end if;
    if not exists(select 1 from public.creator_publishing_compliance_reviews where id=(v_existing.after_state->>'review_record_id')::uuid and content_package_id=p_content_package_id and review_source='automated' and compliance_policy_version=p_policy_version) then raise exception 'COMPLIANCE_IDEMPOTENCY_CONFLICT'; end if;
    return jsonb_build_object('content_package_id',p_content_package_id,'creator_id',p_creator_id,'prior_compliance_status',v_existing.before_state->>'compliance_status','resulting_compliance_status',v_package.compliance_status,'policy_version',p_policy_version,'review_record_id',v_existing.after_state->>'review_record_id','audit_event_ids',jsonb_build_array(v_existing.id::text),'idempotent',true,'outcome','idempotent','evaluated_at',v_existing.created_at,'updated_at',v_package.updated_at);
  end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('creator_compliance_package:'||p_content_package_id::text,0));
  select * into v_package from public.creator_publishing_content_packages where id=p_content_package_id for update; if not found or v_package.creator_id<>p_creator_id or v_package.target_platform='fanvue' or v_package.creator_approval_status='approved' or v_package.updated_at is distinct from p_expected_package_updated_at or exists(select 1 from public.creator_publishing_queue_tasks where content_package_id=p_content_package_id and status<>'archived') then raise exception 'COMPLIANCE_STALE'; end if;
  select * into v_account from public.creator_platform_accounts where id=v_package.platform_account_id for update; select * into v_cv from public.creator_publishing_creator_verifications where creator_id=p_creator_id for update; select * into v_consent from public.creator_publishing_ai_twin_consents where creator_id=p_creator_id for update;
  v_facts := public.creator_publishing_build_compliance_facts(p_creator_id,p_content_package_id);
  if encode(extensions.digest(v_facts::text,'sha256'),'hex')<>p_facts_fingerprint or encode(extensions.digest((v_facts->'media_manifest')::text,'sha256'),'hex')<>p_media_manifest_hash then raise exception 'COMPLIANCE_STALE'; end if;
  if v_package.target_platform='fansly' and p_forced_disclosure_text is not null then raise exception 'COMPLIANCE_INVALID_EVALUATION'; end if;
  if v_package.target_platform='onlyfans' and p_forced_disclosure_text is not null and (p_forced_disclosure_text not in ('#ai','#AIGenerated') or left(p_normalized_caption,length(p_forced_disclosure_text))<>p_forced_disclosure_text or regexp_count(p_normalized_caption,'(^|\s)(#ai|#AIGenerated)(\s|$)','i') <> 1) then raise exception 'COMPLIANCE_INVALID_EVALUATION'; end if;
  v_prior:=v_package.compliance_status; v_review_outcome:=case p_outcome when 'passed' then 'pass' when 'manual_review' then 'manual_review' else 'block' end;
  update public.creator_publishing_content_packages set compliance_status=p_outcome, compliance_policy_version=p_policy_version, forced_disclosure_text=p_forced_disclosure_text, ai_flag=p_ai_flag, ai_detail=p_ai_detail, creator_approval_status='pending', creator_approved_by=null, creator_approved_at=null, updated_at=v_now where id=p_content_package_id returning * into v_package;
  insert into public.creator_publishing_compliance_reviews(content_package_id,reviewer_id,outcome,review_source,notes,escalated_approval_reason,rule_hits,compliance_policy_version,created_at,review_metadata) values(p_content_package_id,null,v_review_outcome,'automated',nullif(array_to_string(array(select jsonb_array_elements_text(p_reasons)),E'\n'),''),null,p_rule_hits,p_policy_version,v_now,jsonb_build_object('schema_version','creator-publishing-compliance-evaluation-v1','facts_fingerprint',p_facts_fingerprint,'media_manifest_hash',p_media_manifest_hash,'normalized_caption',p_normalized_caption,'reasons',p_reasons,'review_requirements',p_review_requirements,'evaluator_metadata',p_evaluator_metadata,'trusted_ai_flag',p_ai_flag,'trusted_ai_detail',p_ai_detail,'ai_twin_consent_status',v_facts->'ai_twin_consent'->>'status','idempotency_key',p_idempotency_key)) returning id into v_review_id;
  v_result_state := jsonb_build_object('content_package_id',v_package.id,'compliance_status',v_package.compliance_status,'compliance_policy_version',v_package.compliance_policy_version,'forced_disclosure_text',v_package.forced_disclosure_text,'ai_flag',v_package.ai_flag,'ai_detail',v_package.ai_detail,'creator_approval_status',v_package.creator_approval_status,'updated_at',v_package.updated_at);
  v_result_fp := encode(extensions.digest(v_result_state::text,'sha256'),'hex');
  insert into public.creator_publishing_audit_events(entity_type,entity_id,actor_id,actor_role,action,before_state,after_state,idempotency_key,created_at) values('creator_publishing_content_package',p_content_package_id,p_creator_id,'creator_publishing_compliance_service','creator_publishing_compliance_evaluated',jsonb_build_object('compliance_status',v_prior,'compliance_policy_version',null),jsonb_build_object('resulting_compliance_status',p_outcome,'policy_version',p_policy_version,'review_record_id',v_review_id,'request_fingerprint',v_request_fingerprint,'facts_fingerprint',p_facts_fingerprint,'media_manifest_hash',p_media_manifest_hash,'resulting_package_state_fingerprint',v_result_fp,'resulting_updated_at',v_package.updated_at,'outcome',p_outcome,'trusted_ai_summary',jsonb_build_object('ai_flag',p_ai_flag,'ai_detail',p_ai_detail),'timestamp',v_now),p_idempotency_key,v_now) returning id into v_audit_id;
  return jsonb_build_object('content_package_id',p_content_package_id,'creator_id',p_creator_id,'prior_compliance_status',v_prior,'resulting_compliance_status',p_outcome,'policy_version',p_policy_version,'review_record_id',v_review_id,'audit_event_ids',jsonb_build_array(v_audit_id::text),'idempotent',false,'outcome','evaluated','evaluated_at',v_now,'updated_at',v_package.updated_at);
end; $$;

revoke all on function public.creator_publishing_build_compliance_facts(uuid, uuid) from PUBLIC; revoke execute on function public.creator_publishing_build_compliance_facts(uuid, uuid) from anon; revoke execute on function public.creator_publishing_build_compliance_facts(uuid, uuid) from authenticated;
revoke all on function public.creator_publishing_load_compliance_facts(uuid, uuid) from PUBLIC; revoke execute on function public.creator_publishing_load_compliance_facts(uuid, uuid) from anon; revoke execute on function public.creator_publishing_load_compliance_facts(uuid, uuid) from authenticated; grant execute on function public.creator_publishing_load_compliance_facts(uuid, uuid) to service_role;
revoke all on function public.creator_publishing_apply_automated_compliance_evaluation(uuid, uuid, timestamptz, text, text, text, text, text, text, text, jsonb, jsonb, jsonb, jsonb, jsonb, text) from PUBLIC; revoke execute on function public.creator_publishing_apply_automated_compliance_evaluation(uuid, uuid, timestamptz, text, text, text, text, text, text, text, jsonb, jsonb, jsonb, jsonb, jsonb, text) from anon; revoke execute on function public.creator_publishing_apply_automated_compliance_evaluation(uuid, uuid, timestamptz, text, text, text, text, text, text, text, jsonb, jsonb, jsonb, jsonb, jsonb, text) from authenticated; grant execute on function public.creator_publishing_apply_automated_compliance_evaluation(uuid, uuid, timestamptz, text, text, text, text, text, text, text, jsonb, jsonb, jsonb, jsonb, jsonb, text) to service_role;
