-- ADR Gates 7-13: extend canonical CPQ jobs and publish_due scheduler events for dormant Fanvue execution.
alter table public.creator_publishing_platform_jobs drop constraint creator_publishing_jobs_no_fanvue;
alter table public.creator_publishing_platform_jobs drop constraint creator_publishing_platform_jobs_job_state_check;
alter table public.creator_publishing_platform_jobs add constraint creator_publishing_platform_jobs_job_state_check check(job_state in('draft','ready_to_publish','direct_publish_queued','publishing_direct','published_direct','direct_publish_failed','retry_scheduled','authentication_required','platform_rejected','scheduled_internally','awaiting_operator','due_now','claimed','scheduled_on_platform','awaiting_post_confirmation','confirmed_posted_manual','failed_manual_upload','needs_fix','skipped','blocked','archived','package_ready','ready_for_export','exported','reconnect_required','uncertain','cancelled'));
alter table public.creator_publishing_platform_jobs add constraint creator_publishing_jobs_id_creator_unique unique(id,creator_id), add column oauth_account_id uuid, add column publication_type text, add column server_idempotency_key text, add column attempt_count integer not null default 0, add column next_attempt_at timestamptz, add column lease_token uuid, add column leased_at timestamptz, add column posted_at timestamptz, add column terminal_classification text, add column safe_error_code text, add column provider_post_uuid uuid,
 add constraint creator_publishing_fanvue_oauth_owner_fk foreign key(oauth_account_id,creator_id,target_platform) references public.autopost_accounts(id,user_id,platform) on delete restrict,
 add constraint creator_publishing_fanvue_execution_shape_check check(target_platform<>'fanvue' or(oauth_account_id is not null and publication_type in('text','image','video') and server_idempotency_key is not null)), add constraint creator_publishing_fanvue_attempt_count_check check(attempt_count between 0 and 3);
create unique index creator_publishing_fanvue_server_idempotency_uidx on public.creator_publishing_platform_jobs(creator_id,server_idempotency_key) where target_platform='fanvue';
create unique index creator_publishing_fanvue_provider_proof_uidx on public.creator_publishing_platform_jobs(provider_post_uuid) where provider_post_uuid is not null;
create table public.creator_publishing_fanvue_attempts(id uuid primary key default gen_random_uuid(),job_id uuid not null,creator_id uuid not null,attempt_ordinal integer not null check(attempt_ordinal between 1 and 3),lease_token uuid not null,started_at timestamptz not null default clock_timestamp(),provider_create_dispatched_at timestamptz,finished_at timestamptz,outcome_class text check(outcome_class in('success','retryable_pre_create','permanent','reconnect_required','uncertain')),provider_create_attempted boolean not null default false,upload_attempted boolean not null default false,refresh_attempted boolean not null default false,safe_error_code text,status_class text,provider_post_uuid uuid,uncertainty_classification text,created_at timestamptz not null default clock_timestamp(),constraint creator_publishing_fanvue_attempt_job_owner_fk foreign key(job_id,creator_id) references public.creator_publishing_platform_jobs(id,creator_id) on delete cascade,constraint creator_publishing_fanvue_attempt_ordinal_unique unique(job_id,attempt_ordinal),constraint creator_publishing_fanvue_attempt_proof_check check(provider_post_uuid is null or outcome_class='success'));
create unique index creator_publishing_fanvue_attempt_provider_proof_uidx on public.creator_publishing_fanvue_attempts(provider_post_uuid) where provider_post_uuid is not null;
alter table public.creator_publishing_fanvue_attempts enable row level security; create policy creator_publishing_fanvue_attempts_select_own on public.creator_publishing_fanvue_attempts for select to authenticated using(creator_id=auth.uid()); grant select on public.creator_publishing_fanvue_attempts to authenticated; revoke insert,update,delete,truncate,references,trigger on public.creator_publishing_fanvue_attempts from anon,authenticated;

create function public.creator_publishing_claim_scheduled_fanvue_jobs(p_limit integer default 1,p_lease_minutes integer default 15) returns table(job_id uuid,attempt_id uuid,lease_token uuid,attempt_ordinal integer) language plpgsql security definer set search_path=public,pg_temp as $$
declare v_recovered integer;begin
 if p_limit not between 1 and 10 or p_lease_minutes not between 1 and 30 then raise exception 'FANVUE_CLAIM_ARGUMENT_INVALID';end if;
 -- A stale dispatched attempt is ambiguous: atomically fail closed before selecting executable work.
 with ambiguous as(select j.id job_id,a.id attempt_id from public.creator_publishing_platform_jobs j join public.creator_publishing_fanvue_attempts a on a.job_id=j.id and a.attempt_ordinal=j.attempt_count where j.target_platform='fanvue' and j.job_state='publishing_direct' and j.leased_at<clock_timestamp()-make_interval(mins=>p_lease_minutes) and a.finished_at is null and a.provider_create_dispatched_at is not null for update of j,a),finish_a as(update public.creator_publishing_fanvue_attempts a set finished_at=clock_timestamp(),outcome_class='uncertain',provider_create_attempted=true,safe_error_code='FANVUE_CREATE_DISPATCH_CRASH_UNCERTAIN',uncertainty_classification='lease_expired_after_create_dispatch' from ambiguous x where a.id=x.attempt_id),finish_j as(update public.creator_publishing_platform_jobs j set job_state='uncertain',terminal_classification='uncertain',safe_error_code='FANVUE_CREATE_DISPATCH_CRASH_UNCERTAIN',next_attempt_at=null,lease_token=null,leased_at=null,updated_at=clock_timestamp() from ambiguous x where j.id=x.job_id returning j.id) select count(*) into v_recovered from finish_j;
 return query with eligible as(
  select j.id,coalesce(a.id,gen_random_uuid()) attempt_id,coalesce(a.attempt_ordinal,j.attempt_count+1) ordinal
  from public.creator_publishing_platform_jobs j join public.creator_publishing_scheduler_events e on e.platform_job_id=j.id and e.event_type='publish_due' and e.schedule_revision=j.schedule_revision and e.status='processed' and e.due_at=j.intended_publish_at
  left join public.creator_publishing_fanvue_attempts a on a.job_id=j.id and a.attempt_ordinal=j.attempt_count and a.finished_at is null and a.provider_create_dispatched_at is null
  where j.target_platform='fanvue' and j.cancelled_at is null and j.attempt_count<3 and j.intended_publish_at<=clock_timestamp() and(j.next_attempt_at is null or j.next_attempt_at<=clock_timestamp()) and(j.job_state in('direct_publish_queued','retry_scheduled') or(j.job_state='publishing_direct' and j.leased_at<clock_timestamp()-make_interval(mins=>p_lease_minutes))) order by j.intended_publish_at,j.id for update of j skip locked limit p_limit),claimed as(update public.creator_publishing_platform_jobs j set job_state='publishing_direct',lease_token=gen_random_uuid(),leased_at=clock_timestamp(),attempt_count=e.ordinal,updated_at=clock_timestamp() from eligible e where j.id=e.id returning j.id,e.attempt_id,j.lease_token,e.ordinal),attempts as(insert into public.creator_publishing_fanvue_attempts(id,job_id,creator_id,attempt_ordinal,lease_token) select c.attempt_id,c.id,j.creator_id,c.ordinal,c.lease_token from claimed c join public.creator_publishing_platform_jobs j on j.id=c.id on conflict(id) do update set lease_token=excluded.lease_token,started_at=clock_timestamp() returning id)
 select c.id,c.attempt_id,c.lease_token,c.ordinal from claimed c join attempts a on a.id=c.attempt_id;
end$$;
revoke all on function public.creator_publishing_claim_scheduled_fanvue_jobs(integer,integer) from public,anon,authenticated;grant execute on function public.creator_publishing_claim_scheduled_fanvue_jobs(integer,integer) to service_role;
create function public.creator_publishing_mark_fanvue_create_dispatched(p_attempt_id uuid,p_lease_token uuid) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$declare n integer;begin update public.creator_publishing_fanvue_attempts a set provider_create_dispatched_at=clock_timestamp() where a.id=p_attempt_id and a.lease_token=p_lease_token and a.finished_at is null and a.provider_create_dispatched_at is null and exists(select 1 from public.creator_publishing_platform_jobs j where j.id=a.job_id and j.lease_token=p_lease_token and j.job_state='publishing_direct');get diagnostics n=row_count;return n=1;end$$;
revoke all on function public.creator_publishing_mark_fanvue_create_dispatched(uuid,uuid) from public,anon,authenticated;grant execute on function public.creator_publishing_mark_fanvue_create_dispatched(uuid,uuid) to service_role;
create function public.creator_publishing_finish_fanvue_attempt(p_attempt_id uuid,p_lease_token uuid,p_outcome text,p_upload boolean,p_refresh boolean,p_safe_code text,p_status text,p_proof uuid default null,p_next timestamptz default null) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$declare a public.creator_publishing_fanvue_attempts%rowtype;j public.creator_publishing_platform_jobs%rowtype;s text;begin select * into a from public.creator_publishing_fanvue_attempts where id=p_attempt_id and lease_token=p_lease_token for update;if not found then return false;end if;select * into j from public.creator_publishing_platform_jobs where id=a.job_id and lease_token=p_lease_token for update;if not found then return false;end if;if p_outcome='success' and p_proof is null then raise exception 'FANVUE_PROVIDER_PROOF_REQUIRED';end if;if p_outcome='retryable_pre_create' and(a.provider_create_dispatched_at is not null or p_next is null or j.attempt_count>=3)then raise exception 'FANVUE_RETRY_INVALID';end if;s:=case p_outcome when'success'then'published_direct' when'retryable_pre_create'then'retry_scheduled' when'reconnect_required'then'reconnect_required' when'uncertain'then'uncertain' else'direct_publish_failed'end;update public.creator_publishing_fanvue_attempts set finished_at=clock_timestamp(),outcome_class=p_outcome,provider_create_attempted=provider_create_dispatched_at is not null,upload_attempted=p_upload,refresh_attempted=p_refresh,safe_error_code=p_safe_code,status_class=p_status,provider_post_uuid=p_proof where id=a.id;update public.creator_publishing_platform_jobs set job_state=s,next_attempt_at=case when p_outcome='retryable_pre_create'then p_next end,posted_at=case when p_outcome='success'then clock_timestamp()end,terminal_classification=case when p_outcome='retryable_pre_create'then null else p_outcome end,safe_error_code=p_safe_code,provider_post_uuid=p_proof,lease_token=null,leased_at=null,updated_at=clock_timestamp()where id=j.id;return true;end$$;
revoke all on function public.creator_publishing_finish_fanvue_attempt(uuid,uuid,text,boolean,boolean,text,text,uuid,timestamptz) from public,anon,authenticated;grant execute on function public.creator_publishing_finish_fanvue_attempt(uuid,uuid,text,boolean,boolean,text,text,uuid,timestamptz) to service_role;
create view public.creator_publishing_fanvue_history with(security_invoker=true) as select id,creator_id,content_package_id,platform_account_id destination_id,publication_type,intended_publish_at scheduled_at,job_state state,next_attempt_at,posted_at,safe_error_code,created_at,updated_at from public.creator_publishing_platform_jobs where target_platform='fanvue';grant select on public.creator_publishing_fanvue_history to authenticated;
