-- LOCK-06 Supabase production boundary hardening.
-- Filename generated by the official Supabase CLI in PR #267 CI.
-- Production application remains separately gated by backup, migration-ledger reconciliation, and explicit human authorization.

begin;

do $lock06_pre$
declare
  v_sale oid := to_regclass('public.sale_counters');
  v_muses oid := to_regclass('public.muses');
  v_trigger_fn oid := to_regprocedure('public.record_lora_terminal_status()');
  v_public_default_execute boolean;
  v_bad boolean := false;
begin
  select exists (
    select 1
    from pg_roles r
    left join pg_default_acl d
      on d.defaclrole=r.oid
     and d.defaclnamespace=0
     and d.defaclobjtype='f'
    cross join lateral aclexplode(coalesce(d.defaclacl, acldefault('f', r.oid))) a
    where r.rolname='postgres' and a.grantee=0 and a.privilege_type='EXECUTE'
  ) into v_public_default_execute;

  v_bad := v_bad or not v_public_default_execute;

  v_bad := v_bad or v_sale is null
    or not exists (
      select 1 from pg_class c
      where c.oid=v_sale and c.relkind='v'
        and not (coalesce(c.reloptions,'{}'::text[]) @> array['security_invoker=true'])
    )
    or not has_table_privilege('anon',v_sale,'SELECT')
    or not has_table_privilege('authenticated',v_sale,'SELECT')
    or not has_table_privilege('service_role',v_sale,'SELECT');

  v_bad := v_bad or v_muses is null
    or not exists (select 1 from pg_class c where c.oid=v_muses and c.relkind='r' and c.relrowsecurity)
    or not has_table_privilege('anon',v_muses,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
    or not has_table_privilege('authenticated',v_muses,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
    or not has_table_privilege('service_role',v_muses,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
    or (select count(*) from pg_policy where polrelid=v_muses) <> 1
    or not exists (
      select 1 from pg_policy
      where polrelid=v_muses and polname='public read muses' and polcmd='r'
        and pg_get_expr(polqual,polrelid)='true' and polwithcheck is null
    );

  v_bad := v_bad or v_trigger_fn is null
    or not exists (
      select 1 from pg_proc p join pg_roles r on r.oid=p.proowner
      where p.oid=v_trigger_fn and r.rolname='postgres' and p.prosecdef and p.proconfig is null
        and not has_function_privilege('anon',p.oid,'EXECUTE')
        and not has_function_privilege('authenticated',p.oid,'EXECUTE')
        and has_function_privilege('service_role',p.oid,'EXECUTE')
    )
    or not exists (
      select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid
      where c.oid=to_regclass('public.user_loras') and t.tgfoid=v_trigger_fn
        and t.tgname='lora_terminal_status_trigger' and not t.tgisinternal and t.tgenabled<>'D'
    );

  if v_bad then
    raise exception using errcode='P0001', message='LOCK06_DRIFT';
  end if;
end
$lock06_pre$;

alter view public.sale_counters set (security_invoker = true);
revoke select on public.sale_counters from anon, authenticated;

revoke all privileges on table public.muses from anon, authenticated;
drop policy "public read muses" on public.muses;

alter function public.record_lora_terminal_status() set search_path = pg_catalog, pg_temp;

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres
  revoke execute on functions from public;

do $lock06_post$
declare
  v_sale oid := to_regclass('public.sale_counters');
  v_muses oid := to_regclass('public.muses');
  v_trigger_fn oid := to_regprocedure('public.record_lora_terminal_status()');
  v_public_default_execute boolean;
  v_bad boolean := false;
begin
  select exists (
    select 1
    from pg_roles r
    left join pg_default_acl d
      on d.defaclrole=r.oid
     and d.defaclnamespace=0
     and d.defaclobjtype='f'
    cross join lateral aclexplode(coalesce(d.defaclacl, acldefault('f', r.oid))) a
    where r.rolname='postgres' and a.grantee=0 and a.privilege_type='EXECUTE'
  ) into v_public_default_execute;

  v_bad := v_bad or v_public_default_execute;

  v_bad := v_bad or v_sale is null
    or not exists (
      select 1 from pg_class c
      where c.oid=v_sale and c.relkind='v'
        and coalesce(c.reloptions,'{}'::text[]) @> array['security_invoker=true']
    )
    or has_table_privilege('anon',v_sale,'SELECT')
    or has_table_privilege('authenticated',v_sale,'SELECT')
    or not has_table_privilege('service_role',v_sale,'SELECT');

  v_bad := v_bad or v_muses is null
    or not exists (select 1 from pg_class c where c.oid=v_muses and c.relkind='r' and c.relrowsecurity)
    or has_table_privilege('anon',v_muses,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
    or has_table_privilege('authenticated',v_muses,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
    or not has_table_privilege('service_role',v_muses,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
    or exists (select 1 from pg_policy where polrelid=v_muses);

  v_bad := v_bad or v_trigger_fn is null
    or not exists (
      select 1 from pg_proc p join pg_roles r on r.oid=p.proowner
      where p.oid=v_trigger_fn and r.rolname='postgres' and p.prosecdef
        and p.proconfig=array['search_path=pg_catalog, pg_temp']::text[]
        and not has_function_privilege('anon',p.oid,'EXECUTE')
        and not has_function_privilege('authenticated',p.oid,'EXECUTE')
        and has_function_privilege('service_role',p.oid,'EXECUTE')
    )
    or not exists (
      select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid
      where c.oid=to_regclass('public.user_loras') and t.tgfoid=v_trigger_fn
        and t.tgname='lora_terminal_status_trigger' and not t.tgisinternal and t.tgenabled<>'D'
    );

  v_bad := v_bad or exists (
    select 1
    from pg_default_acl d
    join pg_roles owner_role on owner_role.oid=d.defaclrole
    join pg_namespace n on n.oid=d.defaclnamespace
    cross join lateral aclexplode(d.defaclacl) a
    left join pg_roles grantee on grantee.oid=a.grantee
    where owner_role.rolname='postgres' and n.nspname='public'
      and (
        (d.defaclobjtype='r' and coalesce(grantee.rolname,'PUBLIC') in ('anon','authenticated','service_role') and a.privilege_type in ('SELECT','INSERT','UPDATE','DELETE'))
        or (d.defaclobjtype='S' and coalesce(grantee.rolname,'PUBLIC') in ('anon','authenticated','service_role') and a.privilege_type in ('USAGE','SELECT'))
        or (d.defaclobjtype='f' and coalesce(grantee.rolname,'PUBLIC') in ('anon','authenticated','service_role') and a.privilege_type='EXECUTE')
      )
  );

  if v_bad then
    raise exception using errcode='P0001', message='LOCK06_POSTCONDITION_FAILED';
  end if;
end
$lock06_post$;

commit;
