-- Phase 4: provider-neutral subscriber Video application. Applying is separately authorized.
begin;
alter table public.video_projects alter column identity_id drop not null;

create table public.video_source_uploads(
 id uuid primary key, owner_id uuid not null references auth.users(id) on delete restrict,
 staging_bucket text not null, staging_key text not null unique, final_bucket text not null, final_key text not null unique,
 expected_mime_type text not null check(expected_mime_type in ('image/jpeg','image/png','image/webp')),
 expected_size_bytes bigint not null check(expected_size_bytes between 1 and 52428800), expires_at timestamptz not null,
 completed_at timestamptz, generation_asset_id uuid unique references public.generation_assets(id) on delete restrict,
 created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp()
);
alter table public.video_source_uploads enable row level security; alter table public.video_source_uploads force row level security;
revoke all on table public.video_source_uploads from public,anon,authenticated,service_role;

create function public.create_video_source_upload(p_upload_id uuid,p_owner_id uuid,p_staging_bucket text,p_staging_key text,p_final_bucket text,p_final_key text,p_expected_mime text,p_expected_size bigint,p_expires_at timestamptz) returns void language plpgsql security definer set search_path=pg_catalog,public as $$
begin if p_upload_id is null or p_owner_id is null or p_expected_mime not in ('image/jpeg','image/png','image/webp') or p_expected_size not between 1 and 52428800 or p_expires_at<=clock_timestamp() or p_staging_key!~('^creator-video-source-staging/'||p_owner_id::text||'/'||p_upload_id::text||'\\.(jpg|png|webp)$') or p_final_key!~('^creator-video-sources/'||p_owner_id::text||'/'||p_upload_id::text||'/source\\.(jpg|png|webp)$') then raise exception 'VIDEO_SOURCE_UPLOAD_INVALID'; end if; insert into public.video_source_uploads(id,owner_id,staging_bucket,staging_key,final_bucket,final_key,expected_mime_type,expected_size_bytes,expires_at) values(p_upload_id,p_owner_id,p_staging_bucket,p_staging_key,p_final_bucket,p_final_key,p_expected_mime,p_expected_size,p_expires_at); end$$;
create function public.get_video_source_upload(p_upload_id uuid,p_owner_id uuid) returns table(upload_id uuid,staging_key text,final_key text,expected_mime_type text,expected_size_bytes bigint,generation_id uuid,generation_asset_id uuid) language sql security definer set search_path=pg_catalog,public as $$ select u.id,u.staging_key,u.final_key,u.expected_mime_type,u.expected_size_bytes,a.generation_id,u.generation_asset_id from public.video_source_uploads u left join public.generation_assets a on a.id=u.generation_asset_id where u.id=p_upload_id and u.owner_id=p_owner_id and (u.completed_at is not null or u.expires_at>clock_timestamp()) $$;
create function public.finalize_video_source_upload(p_upload_id uuid,p_owner_id uuid,p_mime_type text,p_size_bytes bigint,p_sha256 text) returns table(generation_id uuid,generation_asset_id uuid) language plpgsql security definer set search_path=pg_catalog,public as $$
declare u public.video_source_uploads; gid uuid; oid uuid; aid uuid;
begin select * into u from public.video_source_uploads where id=p_upload_id and owner_id=p_owner_id for update; if not found then raise exception 'VIDEO_SOURCE_UPLOAD_NOT_FOUND'; end if; if u.generation_asset_id is not null then return query select a.generation_id,a.id from public.generation_assets a where a.id=u.generation_asset_id; return; end if; if u.expires_at<=clock_timestamp() or p_mime_type<>u.expected_mime_type or p_size_bytes<>u.expected_size_bytes or p_sha256!~'^[0-9a-f]{64}$' then raise exception 'VIDEO_SOURCE_UPLOAD_VERIFICATION_INVALID'; end if; gid:=gen_random_uuid(); insert into public.generations(id,user_id,prompt,image_url,job_type,body_type,mode,status,negative_prompt,completed_at,metadata,updated_at) values(gid,p_owner_id,'',null,'image','none','video_source_import','completed','',clock_timestamp(),jsonb_build_object('kind','image','private_creator_media',true,'source_mode','video_source_import','video_source_upload_id',u.id),clock_timestamp()); insert into public.private_storage_objects(owner_id,storage_class,bucket,object_key,mime_type,size_bytes,sha256,source_reference) values(p_owner_id,'creator_generation',u.final_bucket,u.final_key,p_mime_type,p_size_bytes,p_sha256,jsonb_build_object('video_source_upload_id',u.id,'generation_id',gid)) returning id into oid; insert into public.generation_assets(generation_id,storage_object_id,owner_id,ordinal,kind) values(gid,oid,p_owner_id,0,'image') returning id into aid; update public.video_source_uploads set generation_asset_id=aid,completed_at=clock_timestamp(),updated_at=clock_timestamp() where id=u.id; return query select gid,aid; end$$;

create or replace function public.submit_video_project_compute_jobs(p_owner_id uuid,p_identity_id uuid,p_source_generation_asset_id uuid,p_idempotency_key text,p_request_fingerprint text,p_request_payload jsonb,p_priority_class text)
returns table(project_id uuid,creator_status text,created_at timestamptz,completed_at timestamptz,can_cancel boolean) language plpgsql security definer set search_path=pg_catalog,public as $$
declare p public.video_projects; vj public.compute_jobs; sj public.compute_jobs; vp public.compute_scheduler_policies; sp public.compute_scheduler_policies; duration integer; segments integer; v_mode text; motion numeric; source jsonb; identity_reference jsonb;
begin
 if p_owner_id is null or length(p_idempotency_key) not between 1 and 128 or p_request_fingerprint!~'^[0-9a-f]{64}$' or jsonb_typeof(p_request_payload)<>'object' or p_priority_class not in ('og','standard') or (select array_agg(k order by k) from jsonb_object_keys(p_request_payload) k)<>array['body_type','identity_id','mode','motion_strength','negative_prompt','prompt','requested_duration_seconds','source_generation_asset_id']::text[] or p_request_payload->'identity_id' is distinct from coalesce(to_jsonb(p_identity_id),'null'::jsonb) or p_request_payload->'source_generation_asset_id' is distinct from coalesce(to_jsonb(p_source_generation_asset_id),'null'::jsonb) then raise exception 'INVALID_VIDEO_PROJECT_SUBMISSION'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_owner_id::text||':video-project:'||p_idempotency_key,0)); select * into p from public.video_projects x where x.owner_id=p_owner_id and x.idempotency_key=p_idempotency_key; if found then if p.request_fingerprint<>p_request_fingerprint then raise exception 'IDEMPOTENCY_CONFLICT'; end if; return query select p.id,x->>'creator_status',p.created_at,case when x->>'creator_status'='completed' then p.completed_at else null end,(x->>'can_cancel')::boolean from public.video_project_creator_projection(p) x; return; end if;
 if p_identity_id is not null then select jsonb_build_object('id',l.id,'bucket',l.artifact_r2_bucket,'key',l.artifact_r2_key,'trigger_token',l.trigger_token) into identity_reference from public.user_loras l where l.id=p_identity_id and l.user_id=p_owner_id and l.status='completed' and btrim(coalesce(l.artifact_r2_bucket,''))<>'' and btrim(coalesce(l.artifact_r2_key,''))<>'' and btrim(coalesce(l.trigger_token,''))<>'' for update; if identity_reference is null then raise exception 'VIDEO_IDENTITY_NOT_READY'; end if; end if;
 v_mode:=p_request_payload->>'mode'; duration:=(p_request_payload->>'requested_duration_seconds')::integer; motion:=(p_request_payload->>'motion_strength')::numeric; segments:=case p_priority_class when 'standard' then 2 else 3 end; if v_mode not in ('text_to_video','image_to_video') or p_request_payload->>'body_type' not in ('body_feminine','body_masculine','none') or (v_mode='text_to_video' and btrim(p_request_payload->>'prompt')='') then raise exception 'INVALID_VIDEO_PROJECT_REQUEST'; end if; if (p_priority_class='standard' and (duration not between 10 and 15 or motion not between .40 and .80)) or (p_priority_class='og' and (duration not between 20 and 25 or motion not between .60 and 1.00)) then raise exception 'VIDEO_TIER_INVALID'; end if;
 if v_mode='text_to_video' and p_source_generation_asset_id is not null then raise exception 'VIDEO_SOURCE_MODE_INVALID'; end if; if v_mode='image_to_video' then select jsonb_build_object('bucket',o.bucket,'object_key',o.object_key,'mime_type',o.mime_type,'size_bytes',o.size_bytes,'sha256',o.sha256) into source from public.generation_assets ga join public.generations g on g.id=ga.generation_id join public.private_storage_objects o on o.id=ga.storage_object_id where ga.id=p_source_generation_asset_id and ga.owner_id=p_owner_id and ga.kind='image' and g.user_id=p_owner_id and g.status='completed' and g.image_url is null and o.owner_id=p_owner_id and o.mime_type in ('image/jpeg','image/png','image/webp') for update of ga,g,o; if source is null then raise exception 'VIDEO_SOURCE_INVALID'; end if; end if;
 select * into vp from public.compute_scheduler_policies where workload='video' and enabled for update; if not found then raise exception 'COMPUTE_POLICY_UNCONFIGURED'; end if; select * into sp from public.compute_scheduler_policies where workload='stitch' and enabled for update; if not found then raise exception 'COMPUTE_POLICY_UNCONFIGURED'; end if; p.id:=gen_random_uuid();
 insert into public.compute_jobs(owner_id,workload,idempotency_key,request_fingerprint,request_payload,priority_class,max_attempts) values(p_owner_id,'video','project:'||p.id,p_request_fingerprint,jsonb_build_object('project_id',p.id,'mode',v_mode,'segment_count',segments,'requested_duration_seconds',duration,'target_fps',30,'target_min_short_edge',1080,'prompt',p_request_payload->>'prompt','negative_prompt',p_request_payload->>'negative_prompt','body_type',p_request_payload->>'body_type','motion_strength',motion,'identity_id',p_identity_id,'identity_reference',identity_reference,'source',source),p_priority_class,vp.max_attempts) returning * into vj;
 insert into public.compute_jobs(owner_id,workload,idempotency_key,request_fingerprint,request_payload,priority_class,max_attempts) values(p_owner_id,'stitch','project:'||p.id,p_request_fingerprint,jsonb_build_object('project_id',p.id,'segment_count',segments,'requested_duration_seconds',duration,'target_fps',30,'target_min_short_edge',1080),p_priority_class,sp.max_attempts) returning * into sj;
 insert into public.video_projects(id,owner_id,identity_id,source_generation_asset_id,idempotency_key,request_fingerprint,request_payload,priority_class,mode,requested_duration_seconds,segment_count,video_job_id,stitch_job_id) values(p.id,p_owner_id,p_identity_id,p_source_generation_asset_id,p_idempotency_key,p_request_fingerprint,p_request_payload,p_priority_class,v_mode,duration,segments,vj.id,sj.id) returning * into p; return query select p.id,'queued',p.created_at,p.completed_at,true;
end$$;

-- Normal and recovery manifests return the same immutable provider-neutral request.
create or replace function public.video_compute_manifest(p_job_id uuid,p_attempt_id uuid,p_lease_token uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare j public.compute_jobs;a public.compute_job_attempts; begin select * into j from public.compute_jobs where id=p_job_id;select * into a from public.compute_job_attempts where id=p_attempt_id and job_id=j.id;if not found or j.workload<>'video' or j.state not in('claimed','running','cancel_requested') or j.lease_token is distinct from p_lease_token or j.lease_expires_at<=clock_timestamp() or a.lease_token<>p_lease_token or a.ordinal<>j.attempt_count or a.finished_at is not null then raise exception 'VIDEO_MANIFEST_AUTHORITY_MISMATCH';end if;return j.request_payload;end$$;
create or replace function public.recovered_video_compute_manifest(p_job_id uuid,p_attempt_id uuid,p_recovery_token uuid,p_recovery_lease_token uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare j public.compute_jobs;a public.compute_job_attempts; begin select * into j from public.compute_jobs where id=p_job_id;select * into a from public.compute_job_attempts where id=p_attempt_id and job_id=j.id;if not found or j.workload<>'video' or j.state<>'recovering' or a.finished_at is not null or a.recovery_token is distinct from p_recovery_token or a.recovery_lease_token is distinct from p_recovery_lease_token or a.recovery_lease_expires_at<=clock_timestamp() or a.ordinal<>j.attempt_count then raise exception 'VIDEO_RECOVERY_AUTHORITY_MISMATCH';end if;return j.request_payload;end$$;
revoke all on function public.create_video_source_upload(uuid,uuid,text,text,text,text,text,bigint,timestamptz),public.get_video_source_upload(uuid,uuid),public.finalize_video_source_upload(uuid,uuid,text,bigint,text) from public,anon,authenticated,service_role;
grant execute on function public.create_video_source_upload(uuid,uuid,text,text,text,text,text,bigint,timestamptz),public.get_video_source_upload(uuid,uuid),public.finalize_video_source_upload(uuid,uuid,text,bigint,text) to service_role;
commit;
