import { z } from "zod"
import type { NormalizedPackageComposerInput, PackageComposerInput } from "./types"
export const TITLE_MAX=160, CAPTION_MAX=5000, NOTES_MAX=1000
const uuid=z.string().uuid(); const idem=z.string().trim().regex(/^[A-Za-z0-9_-]{8,128}$/); const ts=z.string().datetime({offset:true})
const protectedFields=["creatorId","creator_id","targetPlatform","target_platform","aiFlag","ai_flag","aiDetail","ai_detail","forcedDisclosureText","forced_disclosure_text","complianceStatus","compliance_status","compliancePolicyVersion","compliance_policy_version","creatorApprovalStatus","creator_approval_status","creatorApprovedBy","creator_approved_by","creatorApprovedAt","creator_approved_at","platformMeta","platform_meta","scheduledFor","scheduled_for","scheduleTimezone","schedule_timezone","actorId","actor_id","actorRole","actor_role","auditState","password","token","cookie","apiKey","session"]
export function rejectProtectedPackageFields(input: Record<string,unknown>) { for (const f of protectedFields) if (Object.prototype.hasOwnProperty.call(input,f) && input[f] !== undefined) throw Object.assign(new Error(`Protected field ${f} is not accepted.`),{code:"INVALID_FORM"}) }
function title(v: unknown){ const s=String(v??"").trim(); if(!s) throw Object.assign(new Error("Title required"),{code:"INVALID_FORM"}); if(s.length>TITLE_MAX) throw Object.assign(new Error("Title too long"),{code:"INVALID_FORM"}); return s }
function caption(v: unknown){ const s=String(v??"").replace(/\r\n/g,"\n").replace(/\r/g,"\n"); if(s.length>CAPTION_MAX) throw Object.assign(new Error("Caption too long"),{code:"INVALID_FORM"}); return s }
function note(v: unknown){ const s=String(v??"").trim(); if(!s) return null; if(s.length>NOTES_MAX) throw Object.assign(new Error("Note too long"),{code:"INVALID_FORM"}); return s }
export function normalizePackageComposerInput(input: PackageComposerInput): NormalizedPackageComposerInput { rejectProtectedPackageFields(input); if(input.operation!=="create"&&input.operation!=="update") throw Object.assign(new Error("Invalid operation"),{code:"INVALID_OPERATION"}); const base={ platformAccountId: uuid.parse(input.platformAccountId), title:title(input.title), captionBody:caption(input.captionBody), secondPersonPresent:Boolean(input.secondPersonPresent), priceNotes:note(input.priceNotes), visibilityNotes:note(input.visibilityNotes), idempotencyKey: idem.parse(input.idempotencyKey??"")}; if(input.operation==="create"){ if(input.contentPackageId || input.expectedUpdatedAt) throw Object.assign(new Error("Invalid create"),{code:"INVALID_FORM"}); return { operation:"create", contentPackageId:null, expectedUpdatedAt:null, ...base }} const cid=uuid.safeParse(input.contentPackageId); const exp=ts.safeParse(input.expectedUpdatedAt); if(!cid.success||!exp.success) throw Object.assign(new Error("Invalid update"),{code:"INVALID_FORM"}); return {operation:"update", contentPackageId:cid.data, expectedUpdatedAt:exp.data, ...base} }
