import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createManifest, serializeManifest, validateRights } from "../manifest";
import { getCandidate, listCandidates } from "../registry";
import { assertNoSecret, validateLocalPath } from "../security";
import { scanSafeTensor } from "../safetensors";
import type { ArtifactResult, Candidate } from "../types";
import { verifyArtifact } from "../verifier";

async function fixture(name:string, values:number[]):Promise<{file:string;candidate:Candidate}>{
  const dir=await mkdtemp(path.join(os.tmpdir(),"sf-model-gate-"));
  const header=Buffer.from(JSON.stringify({weights:{dtype:"F32",shape:[values.length],data_offsets:[0,values.length*4]}}).padEnd(128," "));
  const prefix=Buffer.alloc(8);prefix.writeBigUInt64LE(BigInt(header.length));const data=Buffer.alloc(values.length*4);values.forEach((v,i)=>data.writeFloatLE(v,i*4));const bytes=Buffer.concat([prefix,header,data]);
  const file=path.join(dir,name);await writeFile(file,bytes);const sha=createHash("sha256").update(bytes).digest("hex").toUpperCase();
  return {file,candidate:{...getCandidate("bigasp-v2"),filename:name,bytes:bytes.length,sha256:sha}};
}

test("registry contains exact locked candidate values",()=>{
  const [bigasp,cyber]=listCandidates();
  assert.deepEqual({id:bigasp.candidateId,model:bigasp.model,version:bigasp.version,creator:bigasp.creator,architecture:bigasp.architecture,modelId:bigasp.modelId,versionId:bigasp.versionId,fileId:bigasp.fileId,filename:bigasp.filename,bytes:bigasp.bytes,sha256:bigasp.sha256,status:bigasp.status,productionStatus:bigasp.productionStatus},{id:"bigasp-v2",model:"bigASP",version:"v2.0",creator:"Nutbutter",architecture:"SDXL 1.0",modelId:"502468",versionId:"991916",fileId:"897883",filename:"bigasp_v20.safetensors",bytes:6938040682,sha256:"6C77BE501B95DA35528431C224CCFB51B0AE948857431B3556DB64E213CC1EDF",status:"TECHNICAL_CANARY_CANDIDATE",productionStatus:"NOT_APPROVED"});
  assert.deepEqual({id:cyber.candidateId,model:cyber.model,version:cyber.version,creator:cyber.creator,architecture:cyber.architecture,modelId:cyber.modelId,versionId:cyber.versionId,fileId:cyber.fileId,filename:cyber.filename,bytes:cyber.bytes,sha256:cyber.sha256,status:cyber.status,productionStatus:cyber.productionStatus},{id:"cyberrealistic-xl-v10",model:"CyberRealistic XL",version:"v10.0",creator:"Cyberdelia",architecture:"SDXL 1.0",modelId:"312530",versionId:"2840768",fileId:undefined,filename:"CyberRealisticXLPlay_V10.0_FP16.safetensors",bytes:6938041288,sha256:"FD5E870B5BBCE4BDDEB64F4BB8E49C57F84AB793C0262A503F0123BE435E667D",status:"TECHNICAL_CANARY_CANDIDATE",productionStatus:"NOT_APPROVED"});
});
test("unknown candidates fail closed",()=>assert.throws(()=>getCandidate("unknown"),/UNKNOWN_CANDIDATE/));
test("valid synthetic SafeTensor is accepted and finite counts are exact",async()=>{const f=await fixture("valid.safetensors",[1,-2,0]);const r=await verifyArtifact(f.candidate.candidateId,f.file,f.candidate);assert.equal(r.artifact.ok,true);assert.equal(r.state,"TENSOR_VERIFIED");assert.deepEqual(r.tensors,[{name:"weights",dtype:"F32",shape:[3],nanCount:0,positiveInfinityCount:0,negativeInfinityCount:0}]);});
test("NaN, positive infinity, and negative infinity are counted",async()=>{const f=await fixture("counts.safetensors",[NaN,Infinity,-Infinity]);assert.deepEqual(await scanSafeTensor(f.file),[{name:"weights",dtype:"F32",shape:[3],nanCount:1,positiveInfinityCount:1,negativeInfinityCount:1}]);});
test("bigASP non-finite blocks and Cyber requires review",async()=>{const f=await fixture("candidate.safetensors",[NaN]);const big=await verifyArtifact("bigasp-v2",f.file,f.candidate);const cyber=await verifyArtifact("cyberrealistic-xl-v10",f.file,{...f.candidate,candidateId:"cyberrealistic-xl-v10",nonFinitePolicy:"REVIEW_REQUIRED"});assert.equal(big.state,"BLOCKED");assert.equal(cyber.state,"REVIEW_REQUIRED");});
test("filename, size, and SHA mismatches reject",async()=>{const f=await fixture("actual.safetensors",[1]);let r=await verifyArtifact("bigasp-v2",f.file,{...f.candidate,filename:"other.safetensors"});assert.ok(r.artifact.failures.includes("FILENAME_MISMATCH"));r=await verifyArtifact("bigasp-v2",f.file,{...f.candidate,bytes:f.candidate.bytes+1});assert.ok(r.artifact.failures.includes("BYTE_SIZE_MISMATCH"));r=await verifyArtifact("bigasp-v2",f.file,{...f.candidate,sha256:"0".repeat(64)});assert.ok(r.artifact.failures.includes("SHA256_MISMATCH"));});
test("malformed SafeTensor and unsafe formats reject",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"sf-invalid-")),file=path.join(dir,"bad.safetensors");await writeFile(file,"not safetensors");const bytes=(await readFile(file)).length,sha=createHash("sha256").update(await readFile(file)).digest("hex").toUpperCase();let r=await verifyArtifact("bigasp-v2",file,{...getCandidate("bigasp-v2"),filename:"bad.safetensors",bytes,sha256:sha});assert.match(r.artifact.failures.join(),/MALFORMED_SAFETENSOR/);const pickle=path.join(dir,"bad.ckpt");await writeFile(pickle,"pickle");r=await verifyArtifact("bigasp-v2",pickle,{...getCandidate("bigasp-v2"),filename:"bad.ckpt",bytes:6,sha256:createHash("sha256").update("pickle").digest("hex").toUpperCase()});assert.ok(r.artifact.failures.includes("UNSAFE_CHECKPOINT_FORMAT"));});
test("UNKNOWN rights remain UNKNOWN and Production approval cannot be produced",async()=>{const f=await fixture("manifest.safetensors",[1]),artifact:ArtifactResult={ok:true,candidateId:"bigasp-v2",path:f.file,filename:path.basename(f.file),bytes:f.candidate.bytes,sha256:f.candidate.sha256,failures:[]};const evidence=path.join(path.dirname(f.file),"license.txt");await writeFile(evidence,"preserved evidence");const args={candidateId:"bigasp-v2",capturedAtUtc:"2026-08-22T00:00:00.000Z",evidencePaths:[evidence],rights:{commercial_outputs:"CONFIRMED" as const},artifact,tensors:await scanSafeTensor(f.file),scanState:"TENSOR_VERIFIED" as const};const a=await createManifest(args),b=await createManifest(args);assert.equal(a.rights.cloud_operation,"UNKNOWN");assert.equal(a.status,"EVIDENCE_INCOMPLETE");assert.notEqual(a.status as string,"PRODUCTION_APPROVED");assert.equal(a.evidenceFiles[0].sha256,createHash("sha256").update("preserved evidence").digest("hex").toUpperCase());assert.equal(serializeManifest(a),serializeManifest(b));assert.equal(validateRights({}).lawful_explicit_nsfw,"UNKNOWN");});
test("secrets, relative paths, traversal, and symlinks reject",async()=>{assert.throws(()=>assertNoSecret("access_token=abc"),/SENSITIVE_VALUE/);assert.throws(()=>validateLocalPath("relative/file"),/UNSAFE_PATH/);assert.throws(()=>validateLocalPath("/tmp/../outside"),/UNSAFE_PATH/);const f=await fixture("real.safetensors",[1]),link=path.join(path.dirname(f.file),"link.safetensors");await symlink(f.file,link);const r=await verifyArtifact("bigasp-v2",link,{...f.candidate,filename:"link.safetensors"});assert.ok(r.artifact.failures.includes("UNSAFE_PATH"));});
