-- EMERGENCY MANUAL ROLLBACK ONLY. Requires a fresh backup and explicit human approval. Never run automatically.
-- Restores the verified source-only prestate; Production remains separately gated.
begin;

do $rollback_preflight$ begin
  if has_function_privilege('anon','public.autopost_accounts_preserve_fanvue_provider_identity()','EXECUTE') then raise exception 'FINAL_LP_ROLLBACK_DRIFT'; end if;
end $rollback_preflight$;

grant DELETE, INSERT, SELECT, UPDATE on table public._backup_autopost_rules_before_content_payload_20250628_001 to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.autopost_job_logs to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.autopost_jobs to anon, authenticated;
grant DELETE on table public.autopost_rules to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_platform_accounts to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_ai_twin_consents to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_audit_events to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_co_performer_records to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_compliance_reviews to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_content_packages to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_creator_verifications to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_media_assets to anon, authenticated;
grant DELETE, INSERT, SELECT, UPDATE on table public.creator_publishing_media_upload_intents to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_plans to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_platform_jobs to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.creator_publishing_queue_tasks to anon, authenticated;
grant DELETE, INSERT, SELECT, UPDATE on table public.creator_publishing_trusted_reviewers to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.crypto_payments to anon, authenticated;
grant DELETE on table public.crypto_wallet_addresses to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.subscription_history to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.subscription_tiers to anon, authenticated;
grant DELETE on table public.user_loras to anon, authenticated;
grant DELETE, INSERT, UPDATE on table public.user_subscriptions to anon, authenticated;
grant select on table public.creator_publishing_fanvue_attempts to anon;
grant truncate, trigger, references, maintain on table public._backup_autopost_rules_before_content_payload_20250628_001 to anon, authenticated;
grant truncate, trigger, references, maintain on table public.ai_influencers to anon, authenticated;
grant truncate, trigger, references, maintain on table public.approved_media to anon, authenticated;
grant truncate, trigger, references, maintain on table public.autopost_job_logs to anon, authenticated;
grant truncate, trigger, references, maintain on table public.autopost_jobs to anon, authenticated;
grant truncate, trigger, references, maintain on table public.autopost_rules to anon, authenticated;
grant truncate, trigger, references, maintain on table public.autopost_run_results to anon, authenticated;
grant truncate, trigger, references, maintain on table public.autopost_runs to anon, authenticated;
grant truncate, trigger, references, maintain on table public.autopost_settings to anon, authenticated;
grant truncate, trigger, references, maintain on table public.campaign_links to anon, authenticated;
grant truncate, trigger, references, maintain on table public.caption_templates to anon, authenticated;
grant truncate, trigger, references, maintain on table public.collection_items to anon, authenticated;
grant truncate, trigger, references, maintain on table public.collections to anon, authenticated;
grant truncate, trigger, references, maintain on table public.content_generation_jobs to anon, authenticated;
grant truncate, trigger, references, maintain on table public.content_post_media to anon, authenticated;
grant truncate, trigger, references, maintain on table public.content_post_targets to anon, authenticated;
grant truncate, trigger, references, maintain on table public.content_posts to anon, authenticated;
grant truncate, trigger, references, maintain on table public.content_posts_legacy_ai_influencer to anon, authenticated;
grant truncate, trigger, references, maintain on table public.content_usage_log to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_platform_accounts to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_ai_twin_consents to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_audit_events to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_co_performer_records to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_compliance_reviews to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_content_packages to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_creator_verifications to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_media_assets to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_media_upload_intents to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_plans to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_platform_jobs to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_queue_tasks to anon, authenticated;
grant truncate, trigger, references, maintain on table public.creator_publishing_trusted_reviewers to anon, authenticated;
grant truncate, trigger, references, maintain on table public.crypto_payments to anon, authenticated;
grant truncate, trigger, references, maintain on table public.crypto_wallet_addresses to anon, authenticated;
grant truncate, trigger, references, maintain on table public.cta_variants to anon, authenticated;
grant truncate, trigger, references, maintain on table public.dataset_doctor_images to anon, authenticated;
grant truncate, trigger, references, maintain on table public.dataset_doctor_jobs to anon, authenticated;
grant truncate, trigger, references, maintain on table public.dataset_doctor_selections to anon, authenticated;
grant truncate, trigger, references, maintain on table public.generations to anon, authenticated;
grant truncate, trigger, references, maintain on table public.hashtag_sets to anon, authenticated;
grant truncate, trigger, references, maintain on table public.lora_status_events to anon, authenticated;
grant truncate, trigger, references, maintain on table public.model_enrollments to anon, authenticated;
grant truncate, trigger, references, maintain on table public.models to anon, authenticated;
grant truncate, trigger, references, maintain on table public.platform_connections to anon, authenticated;
grant truncate, trigger, references, maintain on table public.post_logs to anon, authenticated;
grant truncate, trigger, references, maintain on table public.posting_rules to anon, authenticated;
grant truncate, trigger, references, maintain on table public.purchases to anon, authenticated;
grant truncate, trigger, references, maintain on table public.scheduled_posts to anon, authenticated;
grant truncate, trigger, references, maintain on table public.sf_users to anon, authenticated;
grant truncate, trigger, references, maintain on table public.subscription_history to anon, authenticated;
grant truncate, trigger, references, maintain on table public.subscription_tiers to anon, authenticated;
grant truncate, trigger, references, maintain on table public.system_stats to anon, authenticated;
grant truncate, trigger, references, maintain on table public.user_loras to anon, authenticated;
grant truncate, trigger, references, maintain on table public.user_subscriptions to anon, authenticated;
grant truncate, trigger, references, maintain on table public.webhook_logs to anon, authenticated;
grant maintain on table public.autopost_accounts to anon, authenticated;
grant maintain on table public.creator_publishing_fanvue_attempts to anon, authenticated;
grant execute on function public.autopost_accounts_preserve_fanvue_provider_identity() to public, anon, authenticated;
grant execute on function public.creator_publishing_aggregate_plan_status(uuid) to public, anon, authenticated;
grant execute on function public.creator_publishing_autopost_source_fingerprint(uuid) to public, anon, authenticated;
grant execute on function public.creator_publishing_job_source_is_current(uuid) to public, anon, authenticated;
grant execute on function public.creator_publishing_scheduler_validate_timezone(text) to public, anon, authenticated;
grant select on table public.creator_publishing_fanvue_history to anon, authenticated;
grant usage, select, update on sequence public.autopost_job_logs_id_seq to anon, authenticated;
grant usage, select, update on sequence public.creator_publishing_audit_events_id_seq to anon, authenticated;
grant usage, select, update on sequence public.purchases_id_seq to anon, authenticated;
alter default privileges for role postgres in schema public grant truncate, trigger, references, maintain on tables to anon, authenticated;
alter default privileges for role postgres in schema public grant update on sequences to anon, authenticated;

do $rollback_postcondition$ begin
  if not has_function_privilege('anon','public.autopost_accounts_preserve_fanvue_provider_identity()','EXECUTE') or not has_table_privilege('anon','public.creator_publishing_fanvue_history','SELECT') or not has_sequence_privilege('authenticated','public.purchases_id_seq','UPDATE') then raise exception 'FINAL_LP_ROLLBACK_POSTCONDITION_FAILED'; end if;
end $rollback_postcondition$;
commit;
